File "function_invalidation.good.php", line 48, characters 15-19:
Invalid argument (Typing[4110])
  File "function_invalidation.good.php", line 19, characters 20-22:
  Expected `int`
  File "function_invalidation.good.php", line 10, characters 10-13:
  But got `?int`
  File "function_invalidation.good.php", line 47, characters 5-29:
  All the local information about `$c->i` has been invalidated during this call.
This is a limitation of the type-checker; use a local if that's the problem.
File "function_invalidation.good.php", line 51, characters 15-19:
Invalid argument (Typing[4110])
  File "function_invalidation.good.php", line 19, characters 20-22:
  Expected `int`
  File "function_invalidation.good.php", line 10, characters 10-13:
  But got `?int`
  File "function_invalidation.good.php", line 47, characters 5-29:
  All the local information about `$c->i` has been invalidated during this call.
This is a limitation of the type-checker; use a local if that's the problem.
File "function_invalidation.good.php", line 54, characters 15-19:
Invalid argument (Typing[4110])
  File "function_invalidation.good.php", line 19, characters 20-22:
  Expected `int`
  File "function_invalidation.good.php", line 10, characters 10-13:
  But got `?int`
  File "function_invalidation.good.php", line 47, characters 5-29:
  All the local information about `$c->i` has been invalidated during this call.
This is a limitation of the type-checker; use a local if that's the problem.
File "function_invalidation.good.php", line 57, characters 15-19:
Invalid argument (Typing[4110])
  File "function_invalidation.good.php", line 19, characters 20-22:
  Expected `int`
  File "function_invalidation.good.php", line 10, characters 10-13:
  But got `?int`
  File "function_invalidation.good.php", line 47, characters 5-29:
  All the local information about `$c->i` has been invalidated during this call.
This is a limitation of the type-checker; use a local if that's the problem.
File "function_invalidation.good.php", line 60, characters 15-19:
Invalid argument (Typing[4110])
  File "function_invalidation.good.php", line 19, characters 20-22:
  Expected `int`
  File "function_invalidation.good.php", line 10, characters 10-13:
  But got `?int`
  File "function_invalidation.good.php", line 47, characters 5-29:
  All the local information about `$c->i` has been invalidated during this call.
This is a limitation of the type-checker; use a local if that's the problem.
File "function_invalidation.good.php", line 63, characters 15-19:
Invalid argument (Typing[4110])
  File "function_invalidation.good.php", line 19, characters 20-22:
  Expected `int`
  File "function_invalidation.good.php", line 10, characters 10-13:
  But got `?int`
  File "function_invalidation.good.php", line 47, characters 5-29:
  All the local information about `$c->i` has been invalidated during this call.
This is a limitation of the type-checker; use a local if that's the problem.
