File "using_bad_new.php", line 16, characters 8-19:
Disposable objects may only be created in a 'using' statement or 'return' from function marked <<__ReturnDisposable>> (Typing[4187])
File "using_bad_new.php", line 21, characters 10-21:
Disposable objects may only be created in a 'using' statement or 'return' from function marked <<__ReturnDisposable>> (Typing[4187])
File "using_bad_new.php", line 24, characters 8-24:
Disposable objects may only be created in a 'using' statement or 'return' from function marked <<__ReturnDisposable>> (Typing[4187])
