Fanout calculation on line 43
{'cursor': 'cursor,0,integration-test,<hash-redacted-for-test>',
 'debug': {'dependencies': [{'hash': '-3688026448255553557',
                             'variant': 'Type Foo'}],
           'fanout_dependents': ['3296325908251159198', '-3688026448255553557'],
           'relevant_dep_edges': [{'dependency': {'hash': '416070026525687657',
                                                  'variant': 'Type Bar'},
                                   'dependent': {'hash': '-3688026448255553557',
                                                 'variant': 'Type Foo'}},
                                  {'dependency': {'hash': '416070026525687657',
                                                  'variant': 'Type Bar'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}},
                                  {'dependency': {'hash': '-2679637873881058158',
                                                  'variant': 'Cstr Foo'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}},
                                  {'dependency': {'hash': '-1159392632468753808',
                                                  'variant': 'Method '
                                                             'Foo::getSomething'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}},
                                  {'dependency': {'hash': '670249962391539800',
                                                  'variant': 'Method '
                                                             'Bar::someMethod'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}},
                                  {'dependency': {'hash': '-3688026448255553557',
                                                  'variant': 'Type Foo'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}}]},
 'explanations': {'foo.php': {'added_symbols': [],
                              'modified_symbols': [{'name': '\\Foo',
                                                    'num_outgoing_edges': 2,
                                                    'outgoing_files': ['uses_foo.php',
                                                                       'foo.php'],
                                                    'type': 'FileInfo.Class'}],
                              'removed_symbols': []}},
 'files': ['foo.php', 'uses_foo.php'],
 'telemetry': '<telemetry-redacted-for-test>'}

Typecheck for change set on line 44
No errors!
(Additionally, hh_fanout errors matched hh_server errors.)

Fanout calculation on line 55
{'cursor': 'cursor,4,integration-test,<hash-redacted-for-test>',
 'debug': {'dependencies': [{'hash': '-3688026448255553557',
                             'variant': 'Type Foo'}],
           'fanout_dependents': ['3296325908251159198', '-3688026448255553557'],
           'relevant_dep_edges': [{'dependency': {'hash': '416052434339636281',
                                                  'variant': 'Type Baz'},
                                   'dependent': {'hash': '-3688026448255553557',
                                                 'variant': 'Type Foo'}},
                                  {'dependency': {'hash': '416052434339636281',
                                                  'variant': 'Type Baz'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}},
                                  {'dependency': {'hash': '-2679637873881058158',
                                                  'variant': 'Cstr Foo'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}},
                                  {'dependency': {'hash': '-1159392632468753808',
                                                  'variant': 'Method '
                                                             'Foo::getSomething'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}},
                                  {'dependency': {'hash': '4320680632481376520',
                                                  'variant': 'Method '
                                                             'Baz::someMethod'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}},
                                  {'dependency': {'hash': '-3688026448255553557',
                                                  'variant': 'Type Foo'},
                                   'dependent': {'hash': '3296325908251159198',
                                                 'variant': 'Fun uses_foo'}}]},
 'explanations': {'foo.php': {'added_symbols': [],
                              'modified_symbols': [{'name': '\\Foo',
                                                    'num_outgoing_edges': 2,
                                                    'outgoing_files': ['uses_foo.php',
                                                                       'foo.php'],
                                                    'type': 'FileInfo.Class'}],
                              'removed_symbols': []}},
 'files': ['foo.php', 'uses_foo.php'],
 'telemetry': '<telemetry-redacted-for-test>'}

Typecheck for change set on line 56
File "/uses_foo.php", line 14, characters 10-33:
Invalid return type (Typing[4110])
  File "/uses_foo.php", line 2, characters 22-24:
  Expected `int`
  File "/baz.php", line 3, characters 33-38:
  But got `string`
(Additionally, hh_fanout errors matched hh_server errors.)
