WARN: File "lambda_called_on_bad_keyset.php", line 3, characters 16-20:
Array access on type `keyset<string>` returns the key (if present) or throws an exception. Consider using `C\contains_key` to check for membership instead. (Warn[12034])
ERROR: File "lambda_called_on_bad_keyset.php", line 3, characters 19-19:
Invalid index type for this keyset (Typing[4449])
  File "lambda_called_on_bad_keyset.php", line 4, characters 6-24:
  This is a string
  File "lambda_called_on_bad_keyset.php", line 3, characters 19-19:
  It is incompatible with an int
