File "module_methods_basic.php--B.php", line 7, characters 9-9:
You cannot access internal members from module `A` in module `B` (Typing[4112])
  File "module_methods_basic.php--A.php", line 7, characters 19-19:
  This method is internal
File "module_methods_basic.php--B.php", line 11, characters 30-30:
You cannot access internal members from module `A` in module `B` (Typing[4112])
  File "module_methods_basic.php--A.php", line 7, characters 19-19:
  This method is internal
File "module_methods_basic.php--main.php", line 2, characters 33-33:
You cannot access internal members outside of a module (Typing[4112])
  File "module_methods_basic.php--A.php", line 7, characters 19-19:
  This method is internal
