WARN: File "module_weird_type_locations.php--also-A.php", line 7, characters 3-11:
This `as` assertion will always succeed and hence is redundant. The expression on the left has a type `T` which is a subtype of `int`. (Warn[12011])
WARN: File "module_weird_type_locations.php--not-A.php", line 7, characters 3-11:
This `as` assertion will always succeed and hence is redundant. The expression on the left has a type `T` which is a subtype of `int`. (Warn[12011])
ERROR: File "module_weird_type_locations.php--also-A.php", line 6, characters 42-44:
You cannot use this type in a public declaration. (Typing[4446])
  File "module_weird_type_locations.php--A.php", line 6, characters 15-17:
  It is declared as `internal` here
ERROR: File "module_weird_type_locations.php--not-A.php", line 6, characters 39-41:
Cannot access an internal element from module `A` in module `B` (Typing[4444])
  File "module_weird_type_locations.php--A.php", line 6, characters 15-17:
  This is from module `A`
ERROR: File "module_weird_type_locations.php--not-A.php", line 7, characters 9-11:
Cannot access an internal element from module `A` in module `B` (Typing[4444])
  File "module_weird_type_locations.php--A.php", line 6, characters 15-17:
  This is from module `A`
ERROR: File "module_weird_type_locations.php--not-A.php", line 11, characters 20-22:
Cannot access an internal element from module `A` in module `B` (Typing[4444])
  File "module_weird_type_locations.php--A.php", line 6, characters 15-17:
  This is from module `A`
ERROR: File "module_weird_type_locations.php--not-A.php", line 13, characters 39-44:
Cannot access an internal element from module `A` in module `B` (Typing[4444])
  File "module_weird_type_locations.php--A.php", line 8, characters 16-21:
  This is from module `A`
