File "module_class_expr.php--here.php", line 8, characters 15-15:
Cannot access an internal element from module `there` in module `here` (Typing[4444])
  File "module_class_expr.php--there.php", line 5, characters 16-16:
  This is from module `there`
File "module_class_expr.php--here.php", line 9, characters 11-11:
Cannot access an internal element from module `there` in module `here` (Typing[4444])
  File "module_class_expr.php--there.php", line 5, characters 16-16:
  This is from module `there`
File "module_class_expr.php--here.php", line 10, characters 5-5:
Cannot access an internal element from module `there` in module `here` (Typing[4444])
  File "module_class_expr.php--there.php", line 5, characters 16-16:
  This is from module `there`
