File "module_internal_class.php--everywhere.php", line 3, characters 17-17:
Cannot access an internal element from module `here` outside of a module (Typing[4444])
  File "module_internal_class.php--here.php", line 6, characters 16-16:
  This is from module `here`
File "module_internal_class.php--here.php", line 14, characters 9-9:
You cannot use this type in a public declaration. (Typing[4446])
  File "module_internal_class.php--here.php", line 6, characters 16-16:
  It is declared as `internal` here
File "module_internal_class.php--here.php", line 18, characters 11-11:
You cannot use this type in a public declaration. (Typing[4446])
  File "module_internal_class.php--here.php", line 6, characters 16-16:
  It is declared as `internal` here
File "module_internal_class.php--here.php", line 22, characters 24-24:
You cannot use this type in a public declaration. (Typing[4446])
  File "module_internal_class.php--here.php", line 6, characters 16-16:
  It is declared as `internal` here
File "module_internal_class.php--here.php", line 26, characters 26-26:
You cannot use this type in a public declaration. (Typing[4446])
  File "module_internal_class.php--here.php", line 6, characters 16-16:
  It is declared as `internal` here
File "module_internal_class.php--there.php", line 5, characters 17-17:
Cannot access an internal element from module `here` in module `there` (Typing[4444])
  File "module_internal_class.php--here.php", line 6, characters 16-16:
  This is from module `here`
