File "module_inheritance.php--A.php", line 21, characters 21-23:
This member visibility is: `internal` (Typing[4113])
  File "module_inheritance.php--A.php", line 6, characters 19-21:
  `public` was expected
File "module_inheritance.php--B.php", line 7, characters 21-23:
This member visibility is: `internal` (Typing[4113])
  File "module_inheritance.php--A.php", line 6, characters 19-21:
  `public` was expected
File "module_inheritance.php--B.php", line 15, characters 21-28:
Cannot override this member in module `B` (Typing[4444])
  File "module_inheritance.php--A.php", line 8, characters 21-28:
  This member is internal to module `A`
