<?hh // decl /* -*- php -*- */
/**
 * Copyright (c) 2014, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the "hack" directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 */
const int MW_AbsoluteIntent = 3;
const int MW_AddCompositeOp = 2;
const int MW_AddEvaluateOperator = 1;
const int MW_AddNoisePreview = 14;
const int MW_AllChannels = 255;
const int MW_AlphaChannel = 8;
const int MW_AndEvaluateOperator = 2;
const int MW_AnyStretch = 10;
const int MW_AnyStyle = 4;
const int MW_AreaResource = 1;
const int MW_AtopCompositeOp = 3;
const int MW_BZipCompression = 2;
const int MW_BackgroundDispose = 2;
const int MW_BesselFilter = 14;
const int MW_BevelJoin = 3;
const int MW_BilevelType = 1;
const int MW_BlackChannel = 32;
const int MW_BlackmanFilter = 7;
const int MW_BlendCompositeOp = 4;
const int MW_BlobError = 435;
const int MW_BlobFatalError = 735;
const int MW_BlobWarning = 335;
const int MW_BlueChannel = 4;
const int MW_BlurPreview = 16;
const int MW_BoxFilter = 2;
const int MW_BrightnessPreview = 6;
const int MW_BumpmapCompositeOp = 5;
const int MW_ButtCap = 1;
const int MW_CMYKColorspace = 12;
const int MW_CacheError = 445;
const int MW_CacheFatalError = 745;
const int MW_CacheWarning = 345;
const int MW_CatromFilter = 11;
const int MW_CenterAlign = 2;
const int MW_CenterGravity = 5;
const int MW_CharPixel = 1;
const int MW_CharcoalDrawingPreview = 28;
const int MW_ClearCompositeOp = 7;
const int MW_CoderError = 450;
const int MW_CoderFatalError = 750;
const int MW_CoderWarning = 350;
const int MW_ColorBurnCompositeOp = 8;
const int MW_ColorDodgeCompositeOp = 9;
const int MW_ColorSeparationMatteType = 9;
const int MW_ColorSeparationType = 8;
const int MW_ColorizeCompositeOp = 10;
const int MW_ConcatenateMode = 3;
const int MW_CondensedStretch = 4;
const int MW_ConfigureError = 495;
const int MW_ConfigureFatalError = 795;
const int MW_ConfigureWarning = 395;
const int MW_ConstantVirtualPixelMethod = 2;
const int MW_CopyBlackCompositeOp = 11;
const int MW_CopyBlueCompositeOp = 12;
const int MW_CopyCompositeOp = 13;
const int MW_CopyCyanCompositeOp = 14;
const int MW_CopyGreenCompositeOp = 15;
const int MW_CopyMagentaCompositeOp = 16;
const int MW_CopyOpacityCompositeOp = 17;
const int MW_CopyRedCompositeOp = 18;
const int MW_CopyYellowCompositeOp = 19;
const int MW_CorruptImageError = 425;
const int MW_CorruptImageFatalError = 725;
const int MW_CorruptImageWarning = 325;
const int MW_CubicFilter = 10;
const int MW_CyanChannel = 1;
const int MW_DarkenCompositeOp = 20;
const int MW_DelegateError = 415;
const int MW_DelegateFatalError = 715;
const int MW_DelegateWarning = 315;
const int MW_DespecklePreview = 12;
const int MW_DifferenceCompositeOp = 26;
const int MW_DiskResource = 2;
const int MW_DisplaceCompositeOp = 27;
const int MW_DissolveCompositeOp = 28;
const int MW_DivideEvaluateOperator = 3;
const int MW_DoublePixel = 2;
const int MW_DrawError = 460;
const int MW_DrawFatalError = 760;
const int MW_DrawWarning = 360;
const int MW_DstAtopCompositeOp = 21;
const int MW_DstCompositeOp = 22;
const int MW_DstInCompositeOp = 23;
const int MW_DstOutCompositeOp = 24;
const int MW_DstOverCompositeOp = 25;
const int MW_DullPreview = 9;
const int MW_EastGravity = 6;
const int MW_EdgeDetectPreview = 18;
const int MW_EdgeVirtualPixelMethod = 4;
const int MW_ErrorException = 400;
const int MW_EvenOddRule = 1;
const int MW_ExclusionCompositeOp = 29;
const int MW_ExpandedStretch = 7;
const int MW_ExtraCondensedStretch = 3;
const int MW_ExtraExpandedStretch = 8;
const int MW_FatalErrorException = 700;
const int MW_FaxCompression = 3;
const int MW_FileOpenError = 430;
const int MW_FileOpenFatalError = 730;
const int MW_FileOpenWarning = 330;
const int MW_FileResource = 3;
const int MW_FillToBorderMethod = 4;
const int MW_FloatPixel = 3;
const int MW_FloodfillMethod = 3;
const int MW_ForgetGravity = 0;
const int MW_FrameMode = 1;
const int MW_GRAYColorspace = 2;
const int MW_GammaPreview = 7;
const int MW_GaussianFilter = 8;
const int MW_GaussianNoise = 2;
const int MW_GrayscaleMatteType = 3;
const int MW_GrayscalePreview = 10;
const int MW_GrayscaleType = 2;
const int MW_GreenChannel = 2;
const int MW_Group4Compression = 4;
const int MW_HSBColorspace = 14;
const int MW_HSLColorspace = 15;
const int MW_HWBColorspace = 16;
const int MW_HammingFilter = 6;
const int MW_HanningFilter = 5;
const int MW_HardLightCompositeOp = 30;
const int MW_HermiteFilter = 4;
const int MW_HueCompositeOp = 31;
const int MW_HuePreview = 4;
const int MW_ImageError = 465;
const int MW_ImageFatalError = 765;
const int MW_ImageWarning = 365;
const int MW_ImplodePreview = 25;
const int MW_ImpulseNoise = 4;
const int MW_InCompositeOp = 32;
const int MW_IndexChannel = 32;
const int MW_IntegerPixel = 4;
const int MW_ItalicStyle = 2;
const int MW_JPEGCompression = 5;
const int MW_JPEGPreview = 29;
const int MW_LABColorspace = 5;
const int MW_LZWCompression = 8;
const int MW_LanczosFilter = 13;
const int MW_LaplacianNoise = 5;
const int MW_LeftAlign = 1;
const int MW_LeftShiftEvaluateOperator = 4;
const int MW_LightenCompositeOp = 33;
const int MW_LineInterlace = 2;
const int MW_LineThroughDecoration = 4;
const int MW_LongPixel = 5;
const int MW_LosslessJPEGCompression = 7;
const int MW_LuminizeCompositeOp = 35;
const int MW_MagentaChannel = 2;
const int MW_MapResource = 4;
const int MW_MaxEvaluateOperator = 5;
const int MW_MaxRGB = 65535;
const int MW_MeanAbsoluteErrorMetric = 2;
const int MW_MeanSquaredErrorMetric = 4;
const int MW_MemoryResource = 5;
const int MW_MinEvaluateOperator = 6;
const int MW_MinusCompositeOp = 36;
const int MW_MirrorVirtualPixelMethod = 5;
const int MW_MissingDelegateError = 420;
const int MW_MissingDelegateFatalError = 720;
const int MW_MissingDelegateWarning = 320;
const int MW_MitchellFilter = 12;
const int MW_MiterJoin = 1;
const int MW_ModulateCompositeOp = 37;
const int MW_ModuleError = 455;
const int MW_ModuleFatalError = 755;
const int MW_ModuleWarning = 355;
const int MW_MonitorError = 485;
const int MW_MonitorFatalError = 785;
const int MW_MonitorWarning = 385;
const int MW_MultiplicativeGaussianNoise = 3;
const int MW_MultiplyCompositeOp = 38;
const int MW_MultiplyEvaluateOperator = 7;
const int MW_NoCompositeOp = 1;
const int MW_NoCompression = 1;
const int MW_NoDecoration = 1;
const int MW_NoInterlace = 1;
const int MW_NonZeroRule = 2;
const int MW_NoneDispose = 1;
const int MW_NormalStretch = 1;
const int MW_NormalStyle = 1;
const int MW_NorthEastGravity = 3;
const int MW_NorthGravity = 2;
const int MW_NorthWestGravity = 1;
const int MW_OHTAColorspace = 4;
const int MW_ObjectBoundingBox = 3;
const int MW_ObliqueStyle = 3;
const int MW_OilPaintPreview = 27;
const int MW_OpacityChannel = 8;
const int MW_OpaqueOpacity = 0;
const int MW_OptimizeType = 10;
const int MW_OptionError = 410;
const int MW_OptionFatalError = 710;
const int MW_OptionWarning = 310;
const int MW_OrEvaluateOperator = 8;
const int MW_OutCompositeOp = 39;
const int MW_OverCompositeOp = 40;
const int MW_OverlayCompositeOp = 41;
const int MW_OverlineDecoration = 3;
const int MW_PaletteMatteType = 5;
const int MW_PaletteType = 4;
const int MW_PartitionInterlace = 4;
const int MW_PeakAbsoluteErrorMetric = 5;
const int MW_PeakSignalToNoiseRatioMetric = 6;
const int MW_PerceptualIntent = 2;
const int MW_PixelsPerCentimeterResolution = 2;
const int MW_PixelsPerInchResolution = 1;
const int MW_PlaneInterlace = 3;
const int MW_PlusCompositeOp = 42;
const int MW_PointFilter = 1;
const int MW_PointMethod = 1;
const int MW_PoissonNoise = 6;
const int MW_PreviousDispose = 3;
const int MW_QuadraticFilter = 9;
const int MW_QuantizePreview = 11;
const int MW_QuantumRange = 65535;
const int MW_RGBColorspace = 1;
const int MW_RLECompression = 9;
const int MW_RaisePreview = 22;
const int MW_RedChannel = 1;
const int MW_ReduceNoisePreview = 13;
const int MW_RegistryError = 490;
const int MW_RegistryFatalError = 790;
const int MW_RegistryWarning = 390;
const int MW_RelativeIntent = 4;
const int MW_ReplaceCompositeOp = 43;
const int MW_ReplaceMethod = 2;
const int MW_ResetMethod = 5;
const int MW_ResourceLimitError = 400;
const int MW_ResourceLimitFatalError = 700;
const int MW_ResourceLimitWarning = 300;
const int MW_RightAlign = 3;
const int MW_RightShiftEvaluateOperator = 9;
const int MW_RollPreview = 3;
const int MW_RootMeanSquaredErrorMetric = 7;
const int MW_RotatePreview = 1;
const int MW_RoundCap = 2;
const int MW_RoundJoin = 2;
const int MW_SaturateCompositeOp = 44;
const int MW_SaturationIntent = 1;
const int MW_SaturationPreview = 5;
const int MW_ScreenCompositeOp = 45;
const int MW_SegmentPreview = 23;
const int MW_SemiCondensedStretch = 5;
const int MW_SemiExpandedStretch = 6;
const int MW_SetEvaluateOperator = 10;
const int MW_ShadePreview = 21;
const int MW_SharpenPreview = 15;
const int MW_ShearPreview = 2;
const int MW_ShortPixel = 7;
const int MW_SincFilter = 15;
const int MW_SoftLightCompositeOp = 46;
const int MW_SolarizePreview = 20;
const int MW_SouthEastGravity = 9;
const int MW_SouthGravity = 8;
const int MW_SouthWestGravity = 7;
const int MW_SpiffPreview = 8;
const int MW_SpreadPreview = 19;
const int MW_SquareCap = 3;
const int MW_SrcAtopCompositeOp = 47;
const int MW_SrcCompositeOp = 48;
const int MW_SrcInCompositeOp = 49;
const int MW_SrcOutCompositeOp = 50;
const int MW_SrcOverCompositeOp = 51;
const int MW_StaticGravity = 10;
const int MW_StreamError = 440;
const int MW_StreamFatalError = 740;
const int MW_StreamWarning = 340;
const int MW_SubtractCompositeOp = 52;
const int MW_SubtractEvaluateOperator = 11;
const int MW_SwirlPreview = 24;
const int MW_ThresholdCompositeOp = 53;
const int MW_ThresholdPreview = 17;
const int MW_TileVirtualPixelMethod = 7;
const int MW_TransparentColorspace = 3;
const int MW_TransparentOpacity = 65535;
const int MW_TriangleFilter = 3;
const int MW_TrueColorMatteType = 7;
const int MW_TrueColorType = 6;
const int MW_TypeError = 405;
const int MW_TypeFatalError = 705;
const int MW_TypeWarning = 305;
const int MW_UltraCondensedStretch = 2;
const int MW_UltraExpandedStretch = 9;
const int MW_UndefinedAlign = 0;
const int MW_UndefinedCap = 0;
const int MW_UndefinedChannel = 0;
const int MW_UndefinedColorspace = 0;
const int MW_UndefinedCompositeOp = 0;
const int MW_UndefinedCompression = 0;
const int MW_UndefinedDecoration = 0;
const int MW_UndefinedDispose = 0;
const int MW_UndefinedEvaluateOperator = 0;
const int MW_UndefinedException = 0;
const int MW_UndefinedFilter = 0;
const int MW_UndefinedGravity = 0;
const int MW_UndefinedIntent = 0;
const int MW_UndefinedInterlace = 0;
const int MW_UndefinedJoin = 0;
const int MW_UndefinedMethod = 0;
const int MW_UndefinedMetric = 0;
const int MW_UndefinedMode = 0;
const int MW_UndefinedNoise = 0;
const int MW_UndefinedPathUnits = 0;
const int MW_UndefinedPixel = 0;
const int MW_UndefinedPreview = 0;
const int MW_UndefinedResolution = 0;
const int MW_UndefinedResource = 0;
const int MW_UndefinedRule = 0;
const int MW_UndefinedStretch = 0;
const int MW_UndefinedStyle = 0;
const int MW_UndefinedType = 0;
const int MW_UndefinedVirtualPixelMethod = 0;
const int MW_UnderlineDecoration = 2;
const int MW_UnframeMode = 2;
const int MW_UniformNoise = 1;
const int MW_UnrecognizedDispose = 0;
const int MW_UserSpace = 1;
const int MW_UserSpaceOnUse = 2;
const int MW_WandError = 470;
const int MW_WandFatalError = 770;
const int MW_WandWarning = 370;
const int MW_WarningException = 300;
const int MW_WavePreview = 26;
const int MW_WestGravity = 4;
const int MW_XYZColorspace = 6;
const int MW_XorCompositeOp = 54;
const int MW_XorEvaluateOperator = 12;
const int MW_YCCColorspace = 8;
const int MW_YCbCrColorspace = 7;
const int MW_YIQColorspace = 9;
const int MW_YPbPrColorspace = 10;
const int MW_YUVColorspace = 11;
const int MW_YellowChannel = 4;
const int MW_ZipCompression = 10;
const int MW_sRGBColorspace = 13;

function magickgetcopyright();
function magickgethomeurl();
function magickgetpackagename();
function magickgetquantumdepth();
function magickgetreleasedate();
function magickgetresourcelimit($resource_type);
function magickgetversion();
function magickgetversionnumber();
function magickgetversionstring();
function magickqueryconfigureoption($option);
function magickqueryconfigureoptions($pattern);
function magickqueryfonts($pattern);
function magickqueryformats($pattern);
function magicksetresourcelimit($resource_type, $limit);
function newdrawingwand();
function newmagickwand();
function newpixeliterator($mgck_wnd);
function newpixelregioniterator($mgck_wnd, $x, $y, $columns, $rows);
function newpixelwand($imagemagick_col_str = null);
function newpixelwandarray($num_pxl_wnds);
function newpixelwands($num_pxl_wnds);
function destroydrawingwand($drw_wnd);
function destroymagickwand($mgck_wnd);
function destroypixeliterator($pxl_iter);
function destroypixelwand($pxl_wnd);
function destroypixelwandarray($pxl_wnd_array);
function destroypixelwands($pxl_wnd_array);
function isdrawingwand($var);
function ismagickwand($var);
function ispixeliterator($var);
function ispixelwand($var);
function cleardrawingwand($drw_wnd);
function clearmagickwand($mgck_wnd);
function clearpixeliterator($pxl_iter);
function clearpixelwand($pxl_wnd);
function clonedrawingwand($drw_wnd);
function clonemagickwand($mgck_wnd);
function wandgetexception($wnd);
function wandgetexceptionstring($wnd);
function wandgetexceptiontype($wnd);
function wandhasexception($wnd);
function drawaffine($drw_wnd, $sx, $sy, $rx, $ry, $tx, $ty);
function drawannotation($drw_wnd, $x, $y, $text);
function drawarc($drw_wnd, $sx, $sy, $ex, $ey, $sd, $ed);
function drawbezier($drw_wnd, $x_y_points_array);
function drawcircle($drw_wnd, $ox, $oy, $px, $py);
function drawcolor($drw_wnd, $x, $y, $paint_method);
function drawcomment($drw_wnd, $comment);
function drawcomposite($drw_wnd, $composite_operator, $x, $y, $width, $height, $mgck_wnd);
function drawellipse($drw_wnd, $ox, $oy, $rx, $ry, $start, $end);
function drawgetclippath($drw_wnd);
function drawgetcliprule($drw_wnd);
function drawgetclipunits($drw_wnd);
function drawgetexception($drw_wnd);
function drawgetexceptionstring($drw_wnd);
function drawgetexceptiontype($drw_wnd);
function drawgetfillalpha($drw_wnd);
function drawgetfillcolor($drw_wnd);
function drawgetfillopacity($drw_wnd);
function drawgetfillrule($drw_wnd);
function drawgetfont($drw_wnd);
function drawgetfontfamily($drw_wnd);
function drawgetfontsize($drw_wnd);
function drawgetfontstretch($drw_wnd);
function drawgetfontstyle($drw_wnd);
function drawgetfontweight($drw_wnd);
function drawgetgravity($drw_wnd);
function drawgetstrokealpha($drw_wnd);
function drawgetstrokeantialias($drw_wnd);
function drawgetstrokecolor($drw_wnd);
function drawgetstrokedasharray($drw_wnd);
function drawgetstrokedashoffset($drw_wnd);
function drawgetstrokelinecap($drw_wnd);
function drawgetstrokelinejoin($drw_wnd);
function drawgetstrokemiterlimit($drw_wnd);
function drawgetstrokeopacity($drw_wnd);
function drawgetstrokewidth($drw_wnd);
function drawgettextalignment($drw_wnd);
function drawgettextantialias($drw_wnd);
function drawgettextdecoration($drw_wnd);
function drawgettextencoding($drw_wnd);
function drawgettextundercolor($drw_wnd);
function drawgetvectorgraphics($drw_wnd);
function drawline($drw_wnd, $sx, $sy, $ex, $ey);
function drawmatte($drw_wnd, $x, $y, $paint_method);
function drawpathclose($drw_wnd);
function drawpathcurvetoabsolute($drw_wnd, $x1, $y1, $x2, $y2, $x, $y);
function drawpathcurvetoquadraticbezierabsolute($drw_wnd, $x1, $y1, $x, $y);
function drawpathcurvetoquadraticbezierrelative($drw_wnd, $x1, $y1, $x, $y);
function drawpathcurvetoquadraticbeziersmoothabsolute($drw_wnd, $x, $y);
function drawpathcurvetoquadraticbeziersmoothrelative($drw_wnd, $x, $y);
function drawpathcurvetorelative($drw_wnd, $x1, $y1, $x2, $y2, $x, $y);
function drawpathcurvetosmoothabsolute($drw_wnd, $x2, $y2, $x, $y);
function drawpathcurvetosmoothrelative($drw_wnd, $x2, $y2, $x, $y);
function drawpathellipticarcabsolute($drw_wnd, $rx, $ry, $x_axis_rotation, $large_arc_flag, $sweep_flag, $x, $y);
function drawpathellipticarcrelative($drw_wnd, $rx, $ry, $x_axis_rotation, $large_arc_flag, $sweep_flag, $x, $y);
function drawpathfinish($drw_wnd);
function drawpathlinetoabsolute($drw_wnd, $x, $y);
function drawpathlinetohorizontalabsolute($drw_wnd, $x);
function drawpathlinetohorizontalrelative($drw_wnd, $x);
function drawpathlinetorelative($drw_wnd, $x, $y);
function drawpathlinetoverticalabsolute($drw_wnd, $y);
function drawpathlinetoverticalrelative($drw_wnd, $y);
function drawpathmovetoabsolute($drw_wnd, $x, $y);
function drawpathmovetorelative($drw_wnd, $x, $y);
function drawpathstart($drw_wnd);
function drawpoint($drw_wnd, $x, $y);
function drawpolygon($drw_wnd, $x_y_points_array);
function drawpolyline($drw_wnd, $x_y_points_array);
function drawrectangle($drw_wnd, $x1, $y1, $x2, $y2);
function drawrender($drw_wnd);
function drawrotate($drw_wnd, $degrees);
function drawroundrectangle($drw_wnd, $x1, $y1, $x2, $y2, $rx, $ry);
function drawscale($drw_wnd, $x, $y);
function drawsetclippath($drw_wnd, $clip_path);
function drawsetcliprule($drw_wnd, $fill_rule);
function drawsetclipunits($drw_wnd, $clip_path_units);
function drawsetfillalpha($drw_wnd, $fill_opacity);
function drawsetfillcolor($drw_wnd, $fill_pxl_wnd);
function drawsetfillopacity($drw_wnd, $fill_opacity);
function drawsetfillpatternurl($drw_wnd, $fill_url);
function drawsetfillrule($drw_wnd, $fill_rule);
function drawsetfont($drw_wnd, $font_file);
function drawsetfontfamily($drw_wnd, $font_family);
function drawsetfontsize($drw_wnd, $pointsize);
function drawsetfontstretch($drw_wnd, $stretch_type);
function drawsetfontstyle($drw_wnd, $style_type);
function drawsetfontweight($drw_wnd, $font_weight);
function drawsetgravity($drw_wnd, $gravity_type);
function drawsetstrokealpha($drw_wnd, $stroke_opacity);
function drawsetstrokeantialias($drw_wnd, $stroke_antialias = true);
function drawsetstrokecolor($drw_wnd, $strokecolor_pxl_wnd);
function drawsetstrokedasharray($drw_wnd, $dash_array = null);
function drawsetstrokedashoffset($drw_wnd, $dash_offset);
function drawsetstrokelinecap($drw_wnd, $line_cap);
function drawsetstrokelinejoin($drw_wnd, $line_join);
function drawsetstrokemiterlimit($drw_wnd, $miterlimit);
function drawsetstrokeopacity($drw_wnd, $stroke_opacity);
function drawsetstrokepatternurl($drw_wnd, $stroke_url);
function drawsetstrokewidth($drw_wnd, $stroke_width);
function drawsettextalignment($drw_wnd, $align_type);
function drawsettextantialias($drw_wnd, $text_antialias = true);
function drawsettextdecoration($drw_wnd, $decoration_type);
function drawsettextencoding($drw_wnd, $encoding);
function drawsettextundercolor($drw_wnd, $undercolor_pxl_wnd);
function drawsetvectorgraphics($drw_wnd, $vector_graphics);
function drawsetviewbox($drw_wnd, $x1, $y1, $x2, $y2);
function drawskewx($drw_wnd, $degrees);
function drawskewy($drw_wnd, $degrees);
function drawtranslate($drw_wnd, $x, $y);
function pushdrawingwand($drw_wnd);
function drawpushclippath($drw_wnd, $clip_path_id);
function drawpushdefs($drw_wnd);
function drawpushpattern($drw_wnd, $pattern_id, $x, $y, $width, $height);
function popdrawingwand($drw_wnd);
function drawpopclippath($drw_wnd);
function drawpopdefs($drw_wnd);
function drawpoppattern($drw_wnd);
function magickadaptivethresholdimage($mgck_wnd, $width, $height, $offset);
function magickaddimage($mgck_wnd, $add_wand);
function magickaddnoiseimage($mgck_wnd, $noise_type);
function magickaffinetransformimage($mgck_wnd, $drw_wnd);
function magickannotateimage($mgck_wnd, $drw_wnd, $x, $y, $angle, $text);
function magickappendimages($mgck_wnd, $stack_vertical = false);
function magickaverageimages($mgck_wnd);
function magickblackthresholdimage($mgck_wnd, $threshold_pxl_wnd);
function magickblurimage($mgck_wnd, $radius, $sigma, $channel_type = 0);
function magickborderimage($mgck_wnd, $bordercolor, $width, $height);
function magickcharcoalimage($mgck_wnd, $radius, $sigma);
function magickchopimage($mgck_wnd, $width, $height, $x, $y);
function magickclipimage($mgck_wnd);
function magickclippathimage($mgck_wnd, $pathname, $inside);
function magickcoalesceimages($mgck_wnd);
function magickcolorfloodfillimage($mgck_wnd, $fillcolor_pxl_wnd, $fuzz, $bordercolor_pxl_wnd, $x, $y);
function magickcolorizeimage($mgck_wnd, $colorize, $opacity_pxl_wnd);
function magickcombineimages($mgck_wnd, $channel_type);
function magickcommentimage($mgck_wnd, $comment);
function magickcompareimages($mgck_wnd, $reference_wnd, $metric_type, $channel_type = 0);
function magickcompositeimage($mgck_wnd, $composite_wnd, $composite_operator, $x, $y);
function magickconstituteimage($mgck_wnd, $columns, $rows, $smap, $storage_type, $pixel_array);
function magickcontrastimage($mgck_wnd, $sharpen);
function magickconvolveimage($mgck_wnd, $kernel_array, $channel_type = 0);
function magickcropimage($mgck_wnd, $width, $height, $x, $y);
function magickcyclecolormapimage($mgck_wnd, $num_positions);
function magickdeconstructimages($mgck_wnd);
function magickdescribeimage($mgck_wnd);
function magickdespeckleimage($mgck_wnd);
function magickdrawimage($mgck_wnd, $drw_wnd);
function magickechoimageblob($mgck_wnd);
function magickechoimagesblob($mgck_wnd);
function magickedgeimage($mgck_wnd, $radius);
function magickembossimage($mgck_wnd, $radius, $sigma);
function magickenhanceimage($mgck_wnd);
function magickequalizeimage($mgck_wnd);
function magickevaluateimage($mgck_wnd, $evaluate_op, $constant, $channel_type = 0);
function magickflattenimages($mgck_wnd);
function magickflipimage($mgck_wnd);
function magickflopimage($mgck_wnd);
function magickframeimage($mgck_wnd, $matte_color, $width, $height, $inner_bevel, $outer_bevel);
function magickfximage($mgck_wnd, $expression, $channel_type = 0);
function magickgammaimage($mgck_wnd, $gamma, $channel_type = 0);
function magickgaussianblurimage($mgck_wnd, $radius, $sigma, $channel_type = 0);
function magickgetcharheight($mgck_wnd, $drw_wnd, $txt, $multiline = false);
function magickgetcharwidth($mgck_wnd, $drw_wnd, $txt, $multiline = false);
function magickgetexception($mgck_wnd);
function magickgetexceptionstring($mgck_wnd);
function magickgetexceptiontype($mgck_wnd);
function magickgetfilename($mgck_wnd);
function magickgetformat($mgck_wnd);
function magickgetimage($mgck_wnd);
function magickgetimagebackgroundcolor($mgck_wnd);
function magickgetimageblob($mgck_wnd);
function magickgetimageblueprimary($mgck_wnd);
function magickgetimagebordercolor($mgck_wnd);
function magickgetimagechannelmean($mgck_wnd, $channel_type);
function magickgetimagecolormapcolor($mgck_wnd, $index);
function magickgetimagecolors($mgck_wnd);
function magickgetimagecolorspace($mgck_wnd);
function magickgetimagecompose($mgck_wnd);
function magickgetimagecompression($mgck_wnd);
function magickgetimagecompressionquality($mgck_wnd);
function magickgetimagedelay($mgck_wnd);
function magickgetimagedepth($mgck_wnd, $channel_type = 0);
function magickgetimagedispose($mgck_wnd);
function magickgetimageextrema($mgck_wnd, $channel_type = 0);
function magickgetimagefilename($mgck_wnd);
function magickgetimageformat($mgck_wnd);
function magickgetimagegamma($mgck_wnd);
function magickgetimagegreenprimary($mgck_wnd);
function magickgetimageheight($mgck_wnd);
function magickgetimagehistogram($mgck_wnd);
function magickgetimageindex($mgck_wnd);
function magickgetimageinterlacescheme($mgck_wnd);
function magickgetimageiterations($mgck_wnd);
function magickgetimagemattecolor($mgck_wnd);
function magickgetimagemimetype($mgck_wnd);
function magickgetimagepixels($mgck_wnd, $x_offset, $y_offset, $columns, $rows, $smap, $storage_type);
function magickgetimageprofile($mgck_wnd, $name);
function magickgetimageredprimary($mgck_wnd);
function magickgetimagerenderingintent($mgck_wnd);
function magickgetimageresolution($mgck_wnd);
function magickgetimagescene($mgck_wnd);
function magickgetimagesignature($mgck_wnd);
function magickgetimagesize($mgck_wnd);
function magickgetimagetype($mgck_wnd);
function magickgetimageunits($mgck_wnd);
function magickgetimagevirtualpixelmethod($mgck_wnd);
function magickgetimagewhitepoint($mgck_wnd);
function magickgetimagewidth($mgck_wnd);
function magickgetimagesblob($mgck_wnd);
function magickgetinterlacescheme($mgck_wnd);
function magickgetmaxtextadvance($mgck_wnd, $drw_wnd, $txt, $multiline = false);
function magickgetmimetype($mgck_wnd);
function magickgetnumberimages($mgck_wnd);
function magickgetsamplingfactors($mgck_wnd);
function magickgetsize($mgck_wnd);
function magickgetstringheight($mgck_wnd, $drw_wnd, $txt, $multiline = false);
function magickgetstringwidth($mgck_wnd, $drw_wnd, $txt, $multiline = false);
function magickgettextascent($mgck_wnd, $drw_wnd, $txt, $multiline = false);
function magickgettextdescent($mgck_wnd, $drw_wnd, $txt, $multiline = false);
function magickgetwandsize($mgck_wnd);
function magickhasnextimage($mgck_wnd);
function magickhaspreviousimage($mgck_wnd);
function magickimplodeimage($mgck_wnd, $amount);
function magicklabelimage($mgck_wnd, $label);
function magicklevelimage($mgck_wnd, $black_point, $gamma, $white_point, $channel_type = 0);
function magickmagnifyimage($mgck_wnd);
function magickmapimage($mgck_wnd, $map_wand, $dither);
function magickmattefloodfillimage($mgck_wnd, $opacity, $fuzz, $bordercolor_pxl_wnd, $x, $y);
function magickmedianfilterimage($mgck_wnd, $radius);
function magickminifyimage($mgck_wnd);
function magickmodulateimage($mgck_wnd, $brightness, $saturation, $hue);
function magickmontageimage($mgck_wnd, $drw_wnd, $tile_geometry, $thumbnail_geometry, $montage_mode, $frame);
function magickmorphimages($mgck_wnd, $number_frames);
function magickmosaicimages($mgck_wnd);
function magickmotionblurimage($mgck_wnd, $radius, $sigma, $angle);
function magicknegateimage($mgck_wnd, $only_the_gray = false, $channel_type = 0);
function magicknewimage($mgck_wnd, $width, $height, $imagemagick_col_str = null);
function magicknextimage($mgck_wnd);
function magicknormalizeimage($mgck_wnd);
function magickoilpaintimage($mgck_wnd, $radius);
function magickpaintopaqueimage($mgck_wnd, $target_pxl_wnd, $fill_pxl_wnd, $fuzz = 0.0);
function magickpainttransparentimage($mgck_wnd, $target, $opacity = MW_TransparentOpacity, $fuzz = 0.0);
function magickpingimage($mgck_wnd, $filename);
function magickposterizeimage($mgck_wnd, $levels, $dither);
function magickpreviewimages($mgck_wnd, $preview);
function magickpreviousimage($mgck_wnd);
function magickprofileimage($mgck_wnd, $name, $profile = null);
function magickquantizeimage($mgck_wnd, $number_colors, $colorspace_type, $treedepth, $dither, $measure_error);
function magickquantizeimages($mgck_wnd, $number_colors, $colorspace_type, $treedepth, $dither, $measure_error);
function magickqueryfontmetrics($mgck_wnd, $drw_wnd, $txt, $multiline = false);
function magickradialblurimage($mgck_wnd, $angle);
function magickraiseimage($mgck_wnd, $width, $height, $x, $y, $raise);
function magickreadimage($mgck_wnd, $filename);
function magickreadimageblob($mgck_wnd, $blob);
function magickreadimagefile($mgck_wnd, $handle);
function magickreadimages($mgck_wnd, $img_filenames_array);
function magickreducenoiseimage($mgck_wnd, $radius);
function magickremoveimage($mgck_wnd);
function magickremoveimageprofile($mgck_wnd, $name);
function magickremoveimageprofiles($mgck_wnd);
function magickresampleimage($mgck_wnd, $x_resolution, $y_resolution, $filter_type, $blur);
function magickresetiterator($mgck_wnd);
function magickresizeimage($mgck_wnd, $columns, $rows, $filter_type, $blur);
function magickrollimage($mgck_wnd, $x_offset, $y_offset);
function magickrotateimage($mgck_wnd, $background, $degrees);
function magicksampleimage($mgck_wnd, $columns, $rows);
function magickscaleimage($mgck_wnd, $columns, $rows);
function magickseparateimagechannel($mgck_wnd, $channel_type);
function magicksetcompressionquality($mgck_wnd, $quality);
function magicksetfilename($mgck_wnd, $filename = null);
function magicksetfirstiterator($mgck_wnd);
function magicksetformat($mgck_wnd, $format);
function magicksetimage($mgck_wnd, $replace_wand);
function magicksetimagebackgroundcolor($mgck_wnd, $background_pxl_wnd);
function magicksetimagebias($mgck_wnd, $bias);
function magicksetimageblueprimary($mgck_wnd, $x, $y);
function magicksetimagebordercolor($mgck_wnd, $border_pxl_wnd);
function magicksetimagecolormapcolor($mgck_wnd, $index, $mapcolor_pxl_wnd);
function magicksetimagecolorspace($mgck_wnd, $colorspace_type);
function magicksetimagecompose($mgck_wnd, $composite_operator);
function magicksetimagecompression($mgck_wnd, $compression_type);
function magicksetimagecompressionquality($mgck_wnd, $quality);
function magicksetimagedelay($mgck_wnd, $delay);
function magicksetimagedepth($mgck_wnd, $depth, $channel_type = 0);
function magicksetimagedispose($mgck_wnd, $dispose_type);
function magicksetimagefilename($mgck_wnd, $filename = null);
function magicksetimageformat($mgck_wnd, $format);
function magicksetimagegamma($mgck_wnd, $gamma);
function magicksetimagegreenprimary($mgck_wnd, $x, $y);
function magicksetimageindex($mgck_wnd, $index);
function magicksetimageinterlacescheme($mgck_wnd, $interlace_type);
function magicksetimageiterations($mgck_wnd, $iterations);
function magicksetimagemattecolor($mgck_wnd, $matte_pxl_wnd);
function magicksetimageoption($mgck_wnd, $format, $key, $value);
function magicksetimagepixels($mgck_wnd, $x_offset, $y_offset, $columns, $rows, $smap, $storage_type, $pixel_array);
function magicksetimageprofile($mgck_wnd, $name, $profile);
function magicksetimageredprimary($mgck_wnd, $x, $y);
function magicksetimagerenderingintent($mgck_wnd, $rendering_intent);
function magicksetimageresolution($mgck_wnd, $x_resolution, $y_resolution);
function magicksetimagescene($mgck_wnd, $scene);
function magicksetimagetype($mgck_wnd, $image_type);
function magicksetimageunits($mgck_wnd, $resolution_type);
function magicksetimagevirtualpixelmethod($mgck_wnd, $virtual_pixel_method);
function magicksetimagewhitepoint($mgck_wnd, $x, $y);
function magicksetinterlacescheme($mgck_wnd, $interlace_type);
function magicksetlastiterator($mgck_wnd);
function magicksetpassphrase($mgck_wnd, $passphrase);
function magicksetresolution($mgck_wnd, $x_resolution, $y_resolution);
function magicksetsamplingfactors($mgck_wnd, $number_factors, $sampling_factors);
function magicksetsize($mgck_wnd, $columns, $rows);
function magicksetwandsize($mgck_wnd, $columns, $rows);
function magicksharpenimage($mgck_wnd, $radius, $sigma, $channel_type = 0);
function magickshaveimage($mgck_wnd, $columns, $rows);
function magickshearimage($mgck_wnd, $background, $x_shear, $y_shear);
function magicksolarizeimage($mgck_wnd, $threshold);
function magickspliceimage($mgck_wnd, $width, $height, $x, $y);
function magickspreadimage($mgck_wnd, $radius);
function magicksteganoimage($mgck_wnd, $watermark_wand, $offset);
function magickstereoimage($mgck_wnd, $offset_wand);
function magickstripimage($mgck_wnd);
function magickswirlimage($mgck_wnd, $degrees);
function magicktextureimage($mgck_wnd, $texture_wand);
function magickthresholdimage($mgck_wnd, $threshold, $channel_type = 0);
function magicktintimage($mgck_wnd, $tint_pxl_wnd, $opacity_pxl_wnd);
function magicktransformimage($mgck_wnd, $crop, $geometry);
function magicktrimimage($mgck_wnd, $fuzz);
function magickunsharpmaskimage($mgck_wnd, $radius, $sigma, $amount, $threshold, $channel_type = 0);
function magickwaveimage($mgck_wnd, $amplitude, $wave_length);
function magickwhitethresholdimage($mgck_wnd, $threshold_pxl_wnd);
function magickwriteimage($mgck_wnd, $filename);
function magickwriteimagefile($mgck_wnd, $handle);
function magickwriteimages($mgck_wnd, $filename = "", $join_images = false);
function magickwriteimagesfile($mgck_wnd, $handle);
function pixelgetalpha($pxl_wnd);
function pixelgetalphaquantum($pxl_wnd);
function pixelgetblack($pxl_wnd);
function pixelgetblackquantum($pxl_wnd);
function pixelgetblue($pxl_wnd);
function pixelgetbluequantum($pxl_wnd);
function pixelgetcolorasstring($pxl_wnd);
function pixelgetcolorcount($pxl_wnd);
function pixelgetcyan($pxl_wnd);
function pixelgetcyanquantum($pxl_wnd);
function pixelgetexception($pxl_wnd);
function pixelgetexceptionstring($pxl_wnd);
function pixelgetexceptiontype($pxl_wnd);
function pixelgetgreen($pxl_wnd);
function pixelgetgreenquantum($pxl_wnd);
function pixelgetindex($pxl_wnd);
function pixelgetmagenta($pxl_wnd);
function pixelgetmagentaquantum($pxl_wnd);
function pixelgetopacity($pxl_wnd);
function pixelgetopacityquantum($pxl_wnd);
function pixelgetquantumcolor($pxl_wnd);
function pixelgetred($pxl_wnd);
function pixelgetredquantum($pxl_wnd);
function pixelgetyellow($pxl_wnd);
function pixelgetyellowquantum($pxl_wnd);
function pixelsetalpha($pxl_wnd, $alpha);
function pixelsetalphaquantum($pxl_wnd, $alpha);
function pixelsetblack($pxl_wnd, $black);
function pixelsetblackquantum($pxl_wnd, $black);
function pixelsetblue($pxl_wnd, $blue);
function pixelsetbluequantum($pxl_wnd, $blue);
function pixelsetcolor($pxl_wnd, $imagemagick_col_str);
function pixelsetcolorcount($pxl_wnd, $count);
function pixelsetcyan($pxl_wnd, $cyan);
function pixelsetcyanquantum($pxl_wnd, $cyan);
function pixelsetgreen($pxl_wnd, $green);
function pixelsetgreenquantum($pxl_wnd, $green);
function pixelsetindex($pxl_wnd, $index);
function pixelsetmagenta($pxl_wnd, $magenta);
function pixelsetmagentaquantum($pxl_wnd, $magenta);
function pixelsetopacity($pxl_wnd, $opacity);
function pixelsetopacityquantum($pxl_wnd, $opacity);
function pixelsetquantumcolor($pxl_wnd, $red, $green, $blue, $opacity = 0.0);
function pixelsetred($pxl_wnd, $red);
function pixelsetredquantum($pxl_wnd, $red);
function pixelsetyellow($pxl_wnd, $yellow);
function pixelsetyellowquantum($pxl_wnd, $yellow);
function pixelgetiteratorexception($pxl_iter);
function pixelgetiteratorexceptionstring($pxl_iter);
function pixelgetiteratorexceptiontype($pxl_iter);
function pixelgetnextiteratorrow($pxl_iter);
function pixelresetiterator($pxl_iter);
function pixelsetiteratorrow($pxl_iter, $row);
function pixelsynciterator($pxl_iter);
