HHVM_EXTENSION_CHECK_DEPENDENCIES(icu ICU)
if (ENABLE_EXTENSION_ICU)  
  HHVM_SELECT_SOURCES(HRE_CURRENT_EXT_PATH)
  message(STATUS "Building the ICU extension")
else()
  message("Not building the ICU extension")
endif ()