HHVM_DEFINE_EXTENSION("icu" REQUIRED
  SOURCES
    CodePointBreakIterator.cpp
    ext_icu.cpp
    ext_icu_break_iterator.cpp
    ext_icu_calendar.cpp
    ext_icu_collator.cpp
    ext_icu_date_fmt.cpp
    ext_icu_date_pattern_gen.cpp
    ext_icu_grapheme.cpp
    ext_icu_iterator.cpp
    ext_icu_locale.cpp
    ext_icu_misc.cpp
    ext_icu_msg_fmt.cpp
    ext_icu_normalizer.cpp
    ext_icu_num_fmt.cpp
    ext_icu_rsrc_bundle.cpp
    ext_icu_timezone.cpp
    ext_icu_transliterator.cpp
    ext_icu_uchar.cpp
    ext_icu_uconverter.cpp
    ext_icu_ucsdet.cpp
    ext_icu_uspoof.cpp
    icu.cpp
    ICUMatcher.cpp
    ICUTransliterator.cpp
    LifeEventTokenizer.cpp
  HEADERS
    CodePointBreakIterator.h
    ext_icu_break_iterator.h
    ext_icu_calendar.h
    ext_icu_collator.h
    ext_icu_date_fmt.h
    ext_icu_date_pattern_gen.h
    ext_icu_iterator.h
    ext_icu_locale.h
    ext_icu_msg_fmt.h
    ext_icu_num_fmt.h
    ext_icu_rsrc_bundle.h
    ext_icu_timezone.h
    ext_icu_transliterator.h
    ext_icu_uconverter.h
    ext_icu_ucsdet.h
    ext_icu_uspoof.h
    icu.h
    ICUMatcher.h
    ICUTransliterator.h
    LifeEventTokenizer.h
    ublockcode-enum.h
    ucharcategory-enum.h
    uchardirection-enum.h
    uother-enum.h
    uproperty-enum.h
  SYSTEMLIB
    ext_icu.php
    ext_icu_break_iterator.php
    ext_icu_calendar.php
    ext_icu_collator.php
    ext_icu_date_fmt.php
    ext_icu_date_pattern_gen.php
    ext_icu_grapheme.php
    ext_icu_iterator.php
    ext_icu_locale.php
    ext_icu_misc.php
    ext_icu_msg_fmt.php
    ext_icu_normalizer.php
    ext_icu_num_fmt.php
    ext_icu_rsrc_bundle.php
    ext_icu_timezone.php
    ext_icu_transliterator.php
    ext_icu_uchar.php
    ext_icu_uconverter.php
    ext_icu_ucsdet.php
    ext_icu_uspoof.php
  DEPENDS
    libBoost
    libICU
)
