HipHop Warning: each() expects exactly 1 parameter, 0 given in hphp/test/zend/bad/007.php on line %d
NULL

HipHop Warning: Variable passed to each() is not an array or object in hphp/test/zend/bad/007.php on line %d
NULL

HipHop Warning: Variable passed to each() is not an array or object in hphp/test/zend/bad/007.php on line %d
NULL
array(4) {
  [1]=>
  int(1)
  ["value"]=>
  int(1)
  [0]=>
  int(0)
  ["key"]=>
  int(0)
}
array(4) {
  [1]=>
  int(1)
  ["value"]=>
  int(1)
  [0]=>
  string(1) "a"
  ["key"]=>
  string(1) "a"
}
array(4) {
  [1]=>
  int(1)
  ["value"]=>
  int(1)
  [0]=>
  int(0)
  ["key"]=>
  int(0)
}
Done
