array(1) {
  [0]=>
  string(%d) "%s"
}
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}

HipHop Warning: get_included_files() expects exactly 0 parameters, 2 given in hphp/test/zend/bad/014.php on line %d
NULL
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}

HipHop Warning: get_included_files() expects exactly 0 parameters, 1 given in hphp/test/zend/bad/014.php on line %d
NULL
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}
Done
