array(1) {
  [0]=>
  string(%d) "%s"
}
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}
HipHop Warning: Missing argument 0 for get_included_files() in hphp/test/zend/bad/014.php on line %d
NULL
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}
HipHop Warning: Missing argument 0 for get_included_files() in hphp/test/zend/bad/014.php on line %d
NULL
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}
Done
