
HipHop Warning:  Echoing a tainted string:
  the originally tainted string was : 'great'
  it was tainted at :
    #0 fb_taint(), called at [/data/users/jjeannin/hphp/src/test/tainting/taint05.php:4]
  it was successively modified at:
    #0 at [/data/users/jjeannin/hphp/src/test/tainting/taint05.php:5]
    ---
  it was echoed at :
    #0 at [/data/users/jjeannin/hphp/src/test/tainting/taint05.php:6]
  the echoed string is : 'worse great'

[end of the echoed string]


worse greatHipHop Warning:  Echoing a tainted string:
  the originally tainted string was : 'great'
  it was tainted at :
    #0 fb_taint(), called at [/data/users/jjeannin/hphp/src/test/tainting/taint05.php:7]
  it was successively modified at:
    <never>
  it was echoed at :
    #0 at [/data/users/jjeannin/hphp/src/test/tainting/taint05.php:8]
  the echoed string is : 'great'

[end of the echoed string]


greatHipHop Warning:  Echoing a tainted string:
  the originally tainted string was : 'great'
  it was tainted at :
    #0 fb_taint(), called at [/data/users/jjeannin/hphp/src/test/tainting/taint05.php:4]
  it was successively modified at:
    #0 at [/data/users/jjeannin/hphp/src/test/tainting/taint05.php:5]
    ---
  it was echoed at :
    #0 at [/data/users/jjeannin/hphp/src/test/tainting/taint05.php:9]
  the echoed string is : 'worse great'

[end of the echoed string]


worse great