// @generated by hh_manual
class Foo {}
function container_example2(readonly Foo $x) : void {
  $container = readonly vec[]; // container is now a readonly vec
  $container_literal = vec[new Foo(), readonly new Foo()]; // $container_literal is readonly
}
