\*\*\*\ Testing\ ob\_get\_level\(\)\ \:\ basic\ functionality\ \*\*\*\
\
\-\-\ Testing\ ob\_get\_level\(\)\ function\ with\ Zero\ arguments\ \-\-\
int\(0\)\
int\(1\)\
int\(2\)\
int\(1\)\
int\(0\)\
HipHop\ Notice\:\ ob\_end\_flush\(\)\:\ failed\ to\ delete\ and\ flush\ buffer\.\ No\ buffer\ to\ delete\ or\ flush\ in\ hphp\/test\/zend\/bad\/tests\-output\/ob\_get\_level\_basic\_001\.php\ on\ line\ 26\
int\(0\)\
Done