HipHop Warning: ob_start(): class 'nonExistent' not found in hphp/test/zend/bad/tests-output/ob_start_error_002.php on line 13
HipHop Notice: ob_start(): failed to create buffer in hphp/test/zend/bad/tests-output/ob_start_error_002.php on line 13
bool(false)
HipHop Warning: ob_start(): class 'C' does not have a method 'nonExistent' in hphp/test/zend/bad/tests-output/ob_start_error_002.php on line 14
HipHop Notice: ob_start(): failed to create buffer in hphp/test/zend/bad/tests-output/ob_start_error_002.php on line 14
bool(false)
HipHop Warning: ob_start(): class 'C' does not have a method 'no' in hphp/test/zend/bad/tests-output/ob_start_error_002.php on line 15
HipHop Notice: ob_start(): failed to create buffer in hphp/test/zend/bad/tests-output/ob_start_error_002.php on line 15
bool(false)
HipHop Warning: ob_start(): function 'no' not found or invalid function name in hphp/test/zend/bad/tests-output/ob_start_error_002.php on line 16
HipHop Notice: ob_start(): failed to create buffer in hphp/test/zend/bad/tests-output/ob_start_error_002.php on line 16
bool(false)
done
