[
  {
    "diagnostics":[],
    "edit":{
      "changes":{
        "FILE.php":[
          {
            "newText":"$placeholder0 = yield 2;\n    ",
            "range":{"end":{"character":4,"line":5},"start":{"character":4,"line":5}}
          },
          {
            "newText":"$placeholder0",
            "range":{"end":{"character":11,"line":5},"start":{"character":4,"line":5}}
          }
        ]
      }
    },
    "kind":"refactor",
    "title":"Extract into variable"
  },
  {
    "diagnostics":[],
    "edit":{
      "changes":{
        "FILE.php":[
          {
            "newText":"  private function method0(): Iterator<_> {\n    yield 2;\n  }\n\n",
            "range":{"end":{"character":0,"line":3},"start":{"character":0,"line":3}}
          },
          {
            "newText":"foreach ($this->method0() as $value__) {\n      \n    }",
            "range":{"end":{"character":12,"line":5},"start":{"character":4,"line":5}}
          }
        ]
      }
    },
    "kind":"refactor",
    "title":"Extract into method"
  }
]
