Code actions available:
------------------------------------------
Extract into method (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"  private function method0(): void {\n    $x = 1;\n    $y = $x;\n  }\n\n",
          "range":{"end":{"character":0,"line":7},"start":{"character":0,"line":7}}
        },
        {
          "newText":"$this->method0();",
          "range":{"end":{"character":16,"line":12},"start":{"character":8,"line":11}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Extract into method"
}

Applied edit for code action:
------------------------------------------
<?hh

function cond(): bool {
  return false;
}

class Klass {
  private function method0(): void {
    $x = 1;
    $y = $x;
  }

  public function foo(): void {
    if (cond()) {
      while (cond()) {
        /*range-start*/
        $this->method0();
        /*range-end*/;
      }
    }
  }
}

