Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: refactor)
Extract into method (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"  private function ${0:method0}(): Iterator<_> {\n  yield 2;\n  }\n\n",
          "range":{"end":{"character":0,"line":3},"start":{"character":0,"line":3}}
        },
        {
          "newText":"foreach ($this->${0:method0}() as $value__) {\n      \n    }",
          "range":{"end":{"character":12,"line":5},"start":{"character":4,"line":5}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Extract into method"
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function ${0:method0}(): Iterator<_> {
  yield 2;
  }

  public function foo(): Iterator<int> {
    /*range-start*/
    foreach ($this->${0:method0}() as $value__) {
      
    }
    /*range-end*/
  }
}

