Code actions available:
------------------------------------------
Extract into method (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"  private function method0(\\HH\\Awaitable<void> $awaitable, int $n): int {\n    $x = $n * 2;\n    $y = $awaitable;\n    return $x;\n  }\n\n",
          "range":{"end":{"character":0,"line":5},"start":{"character":0,"line":5}}
        },
        {
          "newText":"$x = $this->method0($awaitable, $n);",
          "range":{"end":{"character":20,"line":9},"start":{"character":4,"line":8}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Extract into method"
}

Applied edit for code action:
------------------------------------------
<?hh

async function genVoid(): Awaitable<void> {}

class Klass {
  private function method0(\HH\Awaitable<void> $awaitable, int $n): int {
    $x = $n * 2;
    $y = $awaitable;
    return $x;
  }

  public function foo(int $n): void {
    $awaitable = genVoid();
    /*range-start*/
    $x = $this->method0($awaitable, $n);
    /*range-end*/
    $x + 2;
  }
}

