Code actions available:
------------------------------------------
Extract into method (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"  private function method3(): void {\n    $x = 1;\n  }\n\n",
          "range":{"end":{"character":0,"line":5},"start":{"character":0,"line":5}}
        },
        {
          "newText":"$this->method3();",
          "range":{"end":{"character":11,"line":8},"start":{"character":4,"line":8}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Extract into method"
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  public function method0(): void {}
  public static async function method1(): Promise<void> {}
  private function method3(): void {
    $x = 1;
  }

  public function method2(): void {
    // extracted method should be called "method3" because 0-2 inclusive are taken
    /*range-start*/
    $this->method3();
    /*range-end*/
  }
}

