Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: refactor)
Extract into method (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"  private function method0(): KeyedIterator<_> {\n    yield 2 => \"\";\n  }\n\n",
          "range":{"end":{"character":0,"line":3},"start":{"character":0,"line":3}}
        },
        {
          "newText":"foreach ($this->method0() as $key__ => $value__) {\n      \n    }",
          "range":{"end":{"character":18,"line":5},"start":{"character":4,"line":5}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Extract into method"
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function method0(): KeyedIterator<_> {
    yield 2 => "";
  }

  public function foo(): KeyedIterator<int, string> {
    /*range-start*/
    foreach ($this->method0() as $key__ => $value__) {
      
    }
    /*range-end*/
  }
}

