<?php
// Copyright 2004-present Facebook. All Rights Reserved.
// This file is @generated by
// fbcode/hphp/facebook/tools/code_model/Generate.sh

namespace HH\CodeModel {


/** The sort order to use when grouping query results */

class Orders /* extends Enum<Order> */ {
  /** (no order specified)  */
  const Order PHP_NOT_SPECIFIED = 1;
  /** ascending */
  const Order PHP_ASCENDING = 2;
  /** descending */
  const Order PHP_DESCENDING = 3;
}
}
