File "global_write.php", line 22, characters 5-26:
[Foo::set_bar]{Foo::$bar}(Bar) A static variable is directly written. (Other[11001])
File "global_write.php", line 47, characters 3-16:
[test_fun_call]{Foo::$bar}(Bar) A global variable is directly read. (Other[11004])
File "global_write.php", line 48, characters 3-14:
[test_fun_call]{Foo::$bar}(int) A global variable is written. (Other[11002])
File "global_write.php", line 51, characters 10-11:
[test_fun_call]{Foo::$bar}(Bar) A global variable is passed to (or returned from) a function call. (Other[11003])
