File "array_filter2.php", line 7, characters 5-42:
Invalid argument (Typing[4110])
File "array_filter2.php", line 13, characters 19-21:
This is an int
File "array_filter2.php", line 5, characters 15-23:
It is incompatible with a mixed value
File "array_filter2.php", line 8, characters 7-22:
Single argument array_filter converts KeyedContainer<Tk, ?Tv> to array<Tk, Tv>, and Container<?Tv> to array<mixed, Tv>
