array
array<Tstring>
array<[174]Tint, Tstring>
array<Tarraykey, Tstring>
array<[183]Tint, Tstring>
X
X
intersect(array<Tarraykey, Tstring>, array<[195]Tint, Tstring>)
array
array<option(Tstring)>
array<[202]Tint, [203]option(Tstring)>
array<Tarraykey, [207]option(Tstring)>
array<[211]Tint, [212]option(Tstring)>
X
X
intersect(array<Tarraykey, [220]option(Tstring)>, array<[223]Tint, [224]option(Tstring)>)
No errors
