File "asyncgen4.php", line 14, characters 5-15:
  dynamic
File "asyncgen4.php", line 15, characters 5-15:
  dynamic
File "asyncgen4.php", line 9, characters 3-16:
Invalid yield (Typing[4110])
File "asyncgen4.php", line 7, characters 21-48:
Expected Generator<int, string, void>
File "asyncgen4.php", line 9, characters 3-16:
But got AsyncGenerator<int, string, [unresolved]> (result of 'async function' with 'yield' in the body)
