File "call_in_static_dict.php", line 7, characters 27-32:
Expected constant expression for initializer (Parsing[1002])
File "call_in_static_dict.php", line 7, characters 10-11:
Please add a type hint `public SomeType x` (Naming[2001])
File "call_in_static_dict.php", line 4, characters 26-26:
Was expecting a return type hint (Typing[4030])
File "call_in_static_dict.php", line 7, characters 27-32:
This call is not allowed because its coeffects are incompatible with the context (Typing[4390])
  File "call_in_static_dict.php", line 7, characters 15-33:
  From this declaration, the context of this function body provides the capability set {}
  File "call_in_static_dict.php", line 4, characters 26-26:
  But the function being called requires the default capability set {AccessGlobals, Output, WriteProperty}
  File "coeffect/contexts.hhi", line 28, characters 1-23:
  Hack provides a list of supported contexts here
