File "capitalization2.php--f2.php", line 2, characters 14-22:
Could not find `cAmelCase`. (Naming[2006])
File "capitalization2.php--f1.php", line 3, characters 7-15:
Did you mean `~~Ca~~melCase` instead (which only differs by case)?
File "capitalization2.php--f2.php", line 9, characters 17-25:
Could not find `camelcase`. (Naming[2006])
File "capitalization2.php--f1.php", line 3, characters 7-15:
Did you mean `~~C~~amel~~C~~ase` instead (which only differs by case)?
File "capitalization2.php--f2.php", line 10, characters 14-22:
Could not find `cAMELcASE`. (Naming[2006])
File "capitalization2.php--f1.php", line 3, characters 7-15:
Did you mean `~~CamelCase~~` instead (which only differs by case)?
