File "concrete_redeclare_concrete_class_constant_bad.php--file2.hack", line 1, characters 17-17:
Some members in class `B` are incompatible with those declared in type `A` (Typing[4348])
  File "concrete_redeclare_concrete_class_constant_bad.php--file1.php", line 5, characters 9-11:
  Expected `int`
  File "concrete_redeclare_concrete_class_constant_bad.php--file2.hack", line 2, characters 9-16:
  But got `arraykey`
