--- ocaml
+++ rupro
@@ -1,130 +1,130 @@
 FoldedClass {
     name: "\\Test",
     pos: Pos(root|delayed_subst1.php, 3:11-15),
     kind: Cinterface,
     substs: {
         "\\BaseXXX": SubstContext {
             subst: Subst(
                 {
-                    "T": int,
+                    "T": num,
                 },
             ),
-            class_context: "\\Test",
+            class_context: "\\C",
             from_req_extends: false,
         },
         "\\C": SubstContext {
             subst: Subst(
                 {},
             ),
             class_context: "\\Test",
             from_req_extends: false,
         },
     },
     ancestors: {
         "\\BaseXXX": BaseXXX<int>,
         "\\C": C,
     },
     methods: {
         "get": FoldedElement {
             flags: ABSTRACT,
             origin: "\\BaseXXX",
             visibility: Public,
             deprecated: None,
         },
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|delayed_subst1.php, 3:11-15),
             ty: HH\classname<this>,
             origin: "\\Test",
             refs: [],
         },
     },
     extends: {
         "\\BaseXXX",
         "\\C",
     },
 }
 FoldedClass {
     name: "\\BaseXXX",
     pos: Pos(root|delayed_subst1.php, 5:11-18),
     kind: Cinterface,
     tparams: [
         Tparam {
             variance: Covariant,
             name: (
                 Pos(root|delayed_subst1.php, 5:20-21),
                 "T",
             ),
             tparams: [],
             constraints: [
                 (
                     ConstraintAs,
                     num,
                 ),
             ],
             reified: Erased,
             user_attributes: [],
         },
     ],
     methods: {
         "get": FoldedElement {
             flags: ABSTRACT,
             origin: "\\BaseXXX",
             visibility: Public,
             deprecated: None,
         },
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|delayed_subst1.php, 5:11-18),
             ty: HH\classname<this>,
             origin: "\\BaseXXX",
             refs: [],
         },
     },
 }
 FoldedClass {
     name: "\\C",
     pos: Pos(root|delayed_subst1.php, 9:11-12),
     kind: Cinterface,
     substs: {
         "\\BaseXXX": SubstContext {
             subst: Subst(
                 {
                     "T": num,
                 },
             ),
             class_context: "\\C",
             from_req_extends: false,
         },
     },
     ancestors: {
         "\\BaseXXX": BaseXXX<num>,
     },
     methods: {
         "get": FoldedElement {
             flags: ABSTRACT,
             origin: "\\BaseXXX",
             visibility: Public,
             deprecated: None,
         },
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|delayed_subst1.php, 9:11-12),
             ty: HH\classname<this>,
             origin: "\\C",
             refs: [],
         },
     },
     extends: {
         "\\BaseXXX",
     },
 }
