File "elseif2.php", line 15, characters 5-5:
A semicolon `;` is expected here. (Parsing[1002])
File "elseif2.php", line 14, characters 5-10:
Unbound name: `elseif` (a global function) (Naming[2049])
File "elseif2.php", line 15, characters 5-8:
Unbound name: `else` (a global constant) (Naming[2049])
File "elseif2.php", line 14, characters 5-18:
Cannot use `[]` for reading (NastCheck[3047])
File "elseif2.php", line 15, characters 5-8:
Cannot use `[]` for reading (NastCheck[3047])
File "elseif2.php", line 15, characters 5-8:
Unbound global constant (Typing) (Typing[4106])
File "elseif2.php", line 14, characters 5-10:
Unbound name (typing): `elseif` (Typing[4107])
