File "fake_members8.php", line 25, characters 14-21:
Invalid return type (Typing[4110])
File "fake_members8.php", line 22, characters 27-27:
Expected Z
File "fake_members8.php", line 16, characters 11-15:
But got mixed
File "fake_members8.php", line 24, characters 7-20:
All the local information about $this->x has been invalidated during this call.
This is a limitation of the type-checker, use a local if that's the problem.
