File "generic_subtyping4.php", line 52, characters 14-20:
Invalid argument (Typing[4110])
File "generic_subtyping4.php", line 12, characters 19-19:
Some type constraint(s) are violated here
File "generic_subtyping4.php", line 12, characters 19-19:
T is a constrained type parameter
File "generic_subtyping4.php", line 41, characters 19-22:
Expected bool
File "generic_subtyping4.php", line 12, characters 19-19:
But got dynamic
