object
generic this as <App \BaseField<generic T, >>
App \INeedsFoo<[1]intersect(), >
[2]intersect(App \INeedsFoo<[3]intersect(X), >, generic this as <App \BaseField<generic T, >>)
File "instanceof_static_with_reqs.php", line 31, characters 12-17:
Invalid return type (Typing[4110])
File "instanceof_static_with_reqs.php", line 7, characters 49-52:
This is the type 'this'
  that is compatible with an object of type BaseField
File "instanceof_static_with_reqs.php", line 23, characters 27-35:
It is incompatible with an object of type INeedsFoo
