File "newtype8.php--test.php", line 10, characters 3-13:
  bool
File "newtype8.php--test.php", line 13, characters 3-13:
  string
File "newtype8.php--test.php", line 16, characters 3-13:
  string
File "newtype8.php--test.php", line 19, characters 3-13:
  int
File "newtype8.php--test.php", line 22, characters 3-13:
  int
File "newtype8.php--test.php", line 9, characters 8-14:
This comparison has invalid types.  Only comparisons in which both arguments are strings, nums, DateTime, or DateTimeImmutable are allowed (Typing[4240])
File "newtype8.php--test.php", line 5, characters 3-11:
This is a dynamic value or a value of type FooString because it is an unenforceable type
File "newtype8.php--test.php", line 9, characters 13-14:
This is a string
