File "option_unify.php", line 4, characters 10-19:
Invalid return type (Typing[4336])
  File "option_unify.php", line 4, characters 45-53:
  Expected `Vector<T>`
  File "option_unify.php", line 4, characters 10-19:
  But got `void` because this function does not always return a value
File "option_unify.php", line 19, characters 10-16:
Invalid return type (Typing[4110])
  File "option_unify.php", line 8, characters 26-31:
  Expected `string`
  File "option_unify.php", line 10, characters 24-25:
  But got `int`
