File "override_final.php", line 17, characters 7-9:
Class Bar does not correctly implement all required members  (Typing[4070])
File "override_final.php", line 17, characters 19-21:
Some members are incompatible with those declared in type Foo
Read the following to see why:
File "override_final.php", line 18, characters 22-23:
You cannot override this method
File "override_final.php", line 14, characters 28-29:
It was declared as final
