File "shape_unification_disallows_providing_required_field_where_optional_field_is_consumed.php", line 8, characters 14-15:
Invalid argument (Typing[4110])
File "shape_unification_disallows_providing_required_field_where_optional_field_is_consumed.php", line 7, characters 25-41:
Expected ~shape('x' => ~int) because it is an unenforceable type
File "shape_unification_disallows_providing_required_field_where_optional_field_is_consumed.php", line 5, characters 31-48:
But got shape(?'x' => ~int)
