File "static_and_arrow3.php", line 18, characters 12-13:
Could not find method f2 in an object of type Foo (Typing[4053])
File "static_and_arrow3.php", line 13, characters 26-27:
The closest thing is f2 but it's a static method
File "static_and_arrow3.php", line 18, characters 5-9:
This is why I think it is an object of type Foo
File "static_and_arrow3.php", line 16, characters 7-9:
Declaration of Foo is here
