File "tc_in_enum_class.php", line 99, characters 5-15:
  arraykey
File "tc_in_enum_class.php", line 106, characters 5-15:
  nothing
File "tc_in_enum_class.php", line 104, characters 20-23:
Invalid argument (Typing[4110])
  File "tc_in_enum_class.php", line 48, characters 23-25:
  Expected `int`
  File "tc_in_enum_class.php", line 92, characters 29-44:
  But got `<expr#1>::T::TSource as IAntParent::T::TSource`
