WARN: File "ternary3.php", line 25, characters 10-13:
Sketchy condition: testing the truthiness of a string may not behave as expected.
The values `""` and `"0"` are both considered falsy. To check for non-emptiness, use `!Str\is_empty`. (Warn[12006])
WARN: File "ternary3.php", line 25, characters 10-13:
This is a sketchy null check on an expression of type ?string.
It detects nulls, but it will also detect many other falsy values, including `false`, `0`, `0.0`, `""`, `"0"`, empty Containers, and more.
If you want to test for them, please consider doing so explicitly.
If you only meant to test for `null`, use `$x ?? $default` instead of `$x ?: $default` (Warn[12003])
