File "test_foreach.php", line 14, characters 12-13:
Invalid return type (Typing[4110])
File "test_foreach.php", line 12, characters 37-42:
This is a string
File "test_foreach.php", line 12, characters 19-21:
It is incompatible with an int
File "builtins.hhi", line 20, characters 45-46:
  via this generic Tk
File "builtins.hhi", line 14, characters 51-52:
  via this generic Tk
File "builtins.hhi", line 9, characters 59-60:
  via this generic Tk
