File "test_foreach2.php", line 14, characters 12-13:
Invalid return type (Typing[4110])
File "test_foreach2.php", line 12, characters 37-39:
Expected int
File "test_foreach2.php", line 12, characters 24-29:
But got string
File "collections/Map.hhi", line 59, characters 64-65:
  via this generic Tv
File "collections/interfaces.hhi", line 1136, characters 63-64:
  via this generic Tv
File "collections/interfaces.hhi", line 865, characters 61-62:
  via this generic Tv
File "rx/interfaces.hhi", line 389, characters 36-37:
  via this generic Tv
File "rx/interfaces.hhi", line 35, characters 63-64:
  via this generic Tv
