File "test_foreach2.php", line 14, characters 12-13:
Invalid return type (Typing[4110])
  File "test_foreach2.php", line 12, characters 37-39:
  Expected `int`
  File "test_foreach2.php", line 12, characters 24-29:
  But got `string`
  File "collections/Map.hhi", line 58, characters 32-33:
    via this generic `Tv`
  File "collections/interfaces.hhi", line 1108, characters 26-27:
    via this generic `Tv`
  File "collections/interfaces.hhi", line 842, characters 26-27:
    via this generic `Tv`
  File "interfaces.hhi", line 115, characters 49-50:
    via this generic `Tv`
