File "test_foreach.php", line 14, characters 12-13:
Invalid return type (Typing[4110])
  File "test_foreach.php", line 12, characters 37-42:
  Expected `string`
  File "test_foreach.php", line 12, characters 19-21:
  But got `int`
  File "collections/Map.hhi", line 56, characters 60-61:
    via this generic `Tk`
  File "collections/interfaces.hhi", line 1138, characters 59-60:
    via this generic `Tk`
  File "collections/interfaces.hhi", line 867, characters 57-58:
    via this generic `Tk`
  File "rx/interfaces.hhi", line 384, characters 32-33:
    via this generic `Tk`
  File "rx/interfaces.hhi", line 37, characters 59-60:
    via this generic `Tk`
