File "trait_diamond_4.php", line 13, characters 7-13:
Class `MyClass` inherits trait method `testFun` via multiple traits.  Remove the multiple paths or override the method (Typing[4439])
  File "trait_diamond_4.php", line 7, characters 26-32:
  Trait method is defined here
  File "trait_diamond_4.php", line 15, characters 7-14:
  `MyClass` uses `MyTrait2`
  File "trait_diamond_4.php", line 10, characters 7-14:
  `MyTrait2` uses `MyTrait1`
  File "trait_diamond_4.php", line 14, characters 7-14:
  `MyClass` uses `MyTrait1`
