File "trivial_strict_eq_newtype.php--file3.php", line 4, characters 7-19:
This expression is always `false` (Typing[4118])
  File "trivial_strict_eq_newtype.php--file3.php", line 3, characters 15-17:
  This is a value of type Foo
  File "trivial_strict_eq_newtype.php--file1.php", line 6, characters 9-11:
  Typedef definition comes from here
  File "trivial_strict_eq_newtype.php--file1.php", line 4, characters 9-9:
  Typedef definition comes from here
  File "trivial_strict_eq_newtype.php--file1.php", line 2, characters 9-9:
  Typedef definition comes from here
  File "trivial_strict_eq_newtype.php--file3.php", line 3, characters 25-27:
  This is a value of type Bar
  File "trivial_strict_eq_newtype.php--file2.php", line 3, characters 9-11:
  Typedef definition comes from here
