File "typedef_string_concat2.php", line 8, characters 19-19:
Was expecting a return type hint (Typing[4030])
File "typedef_string_concat2.php", line 13, characters 12-15:
No instance method `blah` in `C` (Typing[4053])
  File "typedef_string_concat2.php", line 8, characters 19-19:
  Did you mean `f` instead?
  File "typedef_string_concat2.php", line 5, characters 7-7:
  This is why I think it is an object of type C
  File "typedef_string_concat2.php", line 5, characters 7-7:
  Declaration of `C` is here
