--- ocaml
+++ rupro
@@ -1,28 +1,25 @@
 FoldedClass {
     name: "\\Foo",
     pos: Pos(root|type__toString.php, 12:7-10),
     kind: Cclass(
         Concrete,
     ),
-    ancestors: {
-        "\\StringishObject": StringishObject,
-    },
     methods: {
         "__toString": FoldedElement {
             flags: (empty),
             origin: "\\Foo",
             visibility: Public,
             deprecated: None,
         },
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|type__toString.php, 12:7-10),
             ty: HH\classname<this>,
             origin: "\\Foo",
             refs: [],
         },
     },
 }
