File "var_args_inheritance2.php", line 16, characters 7-7:
This object is of type B (Typing[4041])
File "var_args_inheritance2.php", line 16, characters 17-17:
It is incompatible with this object of type A
because some declarations are incompatible.
Read the following to see why:
File "var_args_inheritance2.php", line 17, characters 19-20:
Too many mandatory arguments
File "var_args_inheritance2.php", line 13, characters 19-20:
Because of this definition
