// @generated by hh_manual from manual/hack/08-arrays-and-collections/15-varray-and-darray.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
function get_items(bool $b): varray_or_darray<int, string> {
  if ($b) {
    return vec['a', 'b'];
  } else {
    return dict[5 => 'c'];
  }
}
