File "typing.extends1.bad.php", line 62, characters 18-21:
Invalid argument (Typing[4110])
  File "typing.extends1.bad.php", line 35, characters 3-3:
  Expected `F`
  File "typing.extends1.bad.php", line 57, characters 22-22:
  But got `E`
  File "typing.extends1.bad.php", line 41, characters 33-43:
    resulting from expanding the type constant `Ext::TEnum`
  File "typing.extends1.bad.php", line 57, characters 22-22:
  This type argument to `HH\Elt` only allows supertypes (it is contravariant)
