File "4329-4330-enum_constaint_must_be_arraykey_and_compatible.php", line 4, characters 6-8:
This enum declaration is invalid.
Read the following to see why: (Typing[4342])
File "BuiltinEnum.hhi", line 43, characters 32-39:
Member getNames has the wrong type
File "BuiltinEnum.hhi", line 43, characters 73-80:
Expected arraykey
File "4329-4330-enum_constaint_must_be_arraykey_and_compatible.php", line 4, characters 19-22:
But got bool
File "4329-4330-enum_constaint_must_be_arraykey_and_compatible.php", line 4, characters 6-8:
Invalid constraint on enum (Typing[4329])
File "4329-4330-enum_constaint_must_be_arraykey_and_compatible.php", line 4, characters 6-8:
Expected arraykey arising from an implicit 'as arraykey' constraint on this type
File "4329-4330-enum_constaint_must_be_arraykey_and_compatible.php", line 4, characters 19-22:
But got bool
File "4329-4330-enum_constaint_must_be_arraykey_and_compatible.php", line 4, characters 6-8:
Invalid constraint on enum (Typing[4330])
File "4329-4330-enum_constaint_must_be_arraykey_and_compatible.php", line 4, characters 19-22:
Expected bool
File "4329-4330-enum_constaint_must_be_arraykey_and_compatible.php", line 4, characters 12-14:
But got int
