[(Fun
    { f_span = [3:1-5:2]; f_readonly_this = None; f_annotation = (); 
      f_mode = Mstrict; f_readonly_ret = None; f_ret = ((int), (Some ([3:21-24], (Hprim Tint)))); 
      f_name = ([3:10-11], "\\f"); f_tparams = []; f_where_constraints = []; 
      f_variadic = FVnonVariadic;
      f_params =
      [{ param_annotation = ([3:16-18], int); param_type_hint = ((int), (Some ([3:12-15], (Hprim Tint)))); 
         param_is_variadic = false; param_pos = [3:16-18]; param_name = "$x"; 
         param_expr = None; param_readonly = None; param_callconv = None; 
         param_user_attributes = []; param_visibility = None }
        ];
      f_ctxs = None; f_unsafe_ctxs = None;
      f_body = { fb_ast = [([4:3-17], (Return (Some (([4:10-16], int), (Binop (Plus, (([4:10-12], int), (Lvar ([4:10-12], $x))), (([4:15-16], int), (Int "3"))))))))]; fb_annotation = () };
      f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
      f_external = false;
      f_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      f_doc_comment = None })