[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict;
      fd_fun =
      { f_span = [3:1-70]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((Awaitable<string>), (Some ([3:38-55], (Happly (([3:38-47], "\\HH\\Awaitable"), [([3:48-54], (Hprim Tstring))]))))); 
        f_name = ([3:16-25], "\\genString"); f_tparams = []; f_where_constraints = []; 
        f_variadic = FVnonVariadic;
        f_params =
        [{ param_annotation = ([3:33-35], string); param_type_hint = ((string), (Some ([3:26-32], (Hprim Tstring)))); 
           param_is_variadic = false; param_pos = [3:33-35]; param_name = "$s"; 
           param_expr = None; param_readonly = None; param_callconv = None; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([3:58-68], (Return (Some (([3:65-67], string), [3:65-67], (Lvar ([3:65-67], $s))))))]; fb_annotation = () }; 
        f_fun_kind = FAsync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None }
      });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict;
       fd_fun =
       { f_span = [5:1-12:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([5:18-22], (Hprim Tvoid)))); 
         f_name = ([5:10-14], "\\test"); f_tparams = []; f_where_constraints = []; 
         f_variadic = FVnonVariadic; f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([6:3-8:5],
             (Expr
                (([6:3-8:4], (function(): Awaitable<void>)), [6:3-8:4],
                 (Binop ((Eq None), (([6:3-6], (function(): Awaitable<void>)), [6:3-6], (Lvar ([6:3-6], $f0))),
                    (([6:9-8:4], (function(): Awaitable<void>)), [6:9-8:4],
                     (Lfun (
                        { f_span = [6:9-8:4]; f_readonly_this = None; 
                          f_annotation = (); f_readonly_ret = None; f_ret = ((Awaitable<void>), None); 
                          f_name = ([6:9-8:4], ";anonymous"); f_tparams = []; 
                          f_where_constraints = []; f_variadic = FVnonVariadic; 
                          f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
                          f_body =
                          { fb_ast =
                            [([7:5-35],
                              (Expr
                                 (([7:5-34], string), [7:5-34],
                                  (Binop ((Eq None), (([7:5-9], string), [7:5-9], (Lvar ([7:5-9], $str))),
                                     (([7:12-34], string), [7:12-34],
                                      (Await
                                         (([7:18-34], Awaitable<string>), [7:18-34],
                                          (Call ((([7:18-27], (function(string $s): Awaitable<string>)), [7:18-27], (Id ([7:18-27], "\\genString"))), 
                                             [], [(([7:28-33], string), [7:28-33], (String "foo"))], None)))))
                                     )))))
                              ];
                            fb_annotation = () };
                          f_fun_kind = FAsync; f_user_attributes = []; 
                          f_external = false; f_doc_comment = None },
                        [])))
                    )))));
             ([9:3-11:5],
              (Expr
                 (([9:3-11:4], (function(string $x): Awaitable<void>)), [9:3-11:4],
                  (Binop ((Eq None), (([9:3-6], (function(string $x): Awaitable<void>)), [9:3-6], (Lvar ([9:3-6], $f1))),
                     (([9:9-11:4], (function(string $x): Awaitable<void>)), [9:9-11:4],
                      (Lfun (
                         { f_span = [9:9-11:4]; f_readonly_this = None; 
                           f_annotation = (); f_readonly_ret = None; 
                           f_ret = ((Awaitable<void>), None); f_name = ([9:9-11:4], ";anonymous"); 
                           f_tparams = []; f_where_constraints = []; 
                           f_variadic = FVnonVariadic;
                           f_params =
                           [{ param_annotation = ([9:15-17], string); 
                              param_type_hint = ((string), None); param_is_variadic = false; 
                              param_pos = [9:15-17]; param_name = "$x"; 
                              param_expr = None; param_readonly = None; 
                              param_callconv = None; param_user_attributes = []; 
                              param_visibility = None }
                             ];
                           f_ctxs = None; f_unsafe_ctxs = None;
                           f_body =
                           { fb_ast =
                             [([10:5-32],
                               (Expr
                                  (([10:5-31], string), [10:5-31],
                                   (Binop ((Eq None), (([10:5-9], string), [10:5-9], (Lvar ([10:5-9], $str))),
                                      (([10:12-31], string), [10:12-31],
                                       (Await
                                          (([10:18-31], Awaitable<string>), [10:18-31],
                                           (Call ((([10:18-27], (function(string $s): Awaitable<string>)), [10:18-27], (Id ([10:18-27], "\\genString"))), 
                                              [], [(([10:28-30], string), [10:28-30], (Lvar ([10:28-30], $x)))], None)))))
                                      )))))
                               ];
                             fb_annotation = () };
                           f_fun_kind = FAsync; f_user_attributes = []; 
                           f_external = false; f_doc_comment = None },
                         [])))
                     )))))
             ];
           fb_annotation = () };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None }
       })