[(Class
    { c_span = [12:1-22:2]; c_annotation = (); c_mode = <opaque>;
      c_final = false; c_is_xhp = false; c_kind = Cnormal;
      c_name = ([12:7-16], "\\TestClass");
      c_tparams = { c_tparam_list = []; c_tparam_constraints = <opaque> };
      c_extends = []; c_uses = []; c_method_redeclarations = [];
      c_xhp_attr_uses = []; c_xhp_category = None; c_req_extends = [];
      c_req_implements = []; c_implements = []; c_consts = [];
      c_typeconsts = [];
      c_static_vars =
      [{ cv_final = false; cv_is_xhp = false; cv_visibility = Private;
         cv_type = (Some ([13:18-22], (Hoption ([13:19-22], (Hprim Tint)))));
         cv_id = ([13:23-25], "x");
         cv_expr = (Some (([13:28-32], null), Null));
         cv_user_attributes = []; cv_doc_comment = None;
         cv_is_promoted_variadic = false }
        ];
      c_vars = []; c_constructor = None;
      c_static_methods =
      [{ m_span = [15:3-21:4]; m_annotation = (); m_final = false;
         m_abstract = false; m_static = true; m_visibility = Public;
         m_name = ([15:26-29], "get"); m_tparams = [];
         m_where_constraints = []; m_variadic = FVnonVariadic; m_params = [];
         m_body =
         { fb_ast =
           [([16:5-20:6],
             (If (
                (([16:9-17], ?int),
                 (Class_get ((([16:9-13], TestClass), CIself),
                    (CGstring ([16:15-17], "$x"))))),
                [([17:7-23],
                  (Return
                     (Some (([17:14-22], int),
                            (Class_get ((([17:14-18], TestClass), CIself),
                               (CGstring ([17:20-22], "$x"))))))))
                  ],
                [([19:7-16], (Return (Some (([19:14-15], int), (Int "0")))))]
                )))
             ];
           fb_annotation = No unsafe blocks };
         m_fun_kind = FSync; m_user_attributes = [];
         m_ret = (Some ([15:33-36], (Hprim Tint))); m_external = false;
         m_doc_comment = None }
        ];
      c_methods = []; c_attributes = []; c_xhp_children = [];
      c_xhp_attrs = []; c_namespace = <opaque>; c_user_attributes = [];
      c_file_attributes = []; c_enum = None; c_pu_enums = [];
      c_doc_comment =
      (Some "/**\n * Copyright (c) 2014, Facebook, Inc.\n * All rights reserved.\n *\n * This source code is licensed under the MIT license found in the\n * LICENSE file in the \"hack\" directory of this source tree.\n *\n *\n */")
      })
  ]
