[(Fun
    { f_span = [3:1-5:2]; f_readonly_this = None; f_annotation = (); 
      f_mode = Mstrict; f_readonly_ret = None; f_ret = ((void), (Some ([3:25-29], (Hprim Tvoid)))); 
      f_name = ([3:10-11], "\\f"); f_tparams = []; f_where_constraints = []; 
      f_variadic = FVnonVariadic; f_params = []; f_ctxs = (Some ([3:13-23], [([3:14-22], (Happly (([3:14-22], "\\HH\\Contexts\\defaults"), [])))]));
      f_unsafe_ctxs = (Some ([3:13-23], [([3:14-22], (Happly (([3:14-22], "\\HH\\Contexts\\Unsafe\\defaults"), [])))]));
      f_body =
      { fb_ast =
        [([4:3-24],
          (Expr
             (([4:3-23], (function(mixed $i): void)),
              (Binop ((Eq None), (([4:3-5], (function(mixed $i): void)), (Lvar ([4:3-5], $x))),
                 (([4:8-23], (function(mixed $i): void)),
                  (Lfun (
                     { f_span = [4:8-23]; f_readonly_this = None; f_annotation = (); 
                       f_mode = Mstrict; f_readonly_ret = None; f_ret = ((void), None); 
                       f_name = ([4:8-23], ";anonymous"); f_tparams = []; 
                       f_where_constraints = []; f_variadic = FVnonVariadic;
                       f_params =
                       [{ param_annotation = ([4:9-11], mixed); param_type_hint = ((mixed), None); 
                          param_is_variadic = false; param_pos = [4:9-11]; 
                          param_name = "$i"; param_expr = None; param_readonly = None; 
                          param_callconv = None; param_user_attributes = []; 
                          param_visibility = None }
                         ];
                       f_ctxs = (Some ([4:12-16], [([4:13-15], (Happly (([4:13-15], "\\HH\\Contexts\\rx"), [])))]));
                       f_unsafe_ctxs = (Some ([4:12-16], [([4:13-15], (Happly (([4:13-15], "\\HH\\Contexts\\Unsafe\\rx"), [])))])); 
                       f_body = { fb_ast = [([Pos.none], Noop)]; fb_annotation = () }; 
                       f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
                       f_external = false;
                       f_namespace =
                       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
                         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; 
                         ns_const_uses = <opaque>; ns_name = None; ns_auto_ns_map = []; 
                         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
                       f_doc_comment = None },
                     [])))
                 )))))
          ];
        fb_annotation = () };
      f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
      f_external = false;
      f_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      f_doc_comment = None })