[(Class
    { c_span = [7:1-45]; c_annotation = (); c_mode = <opaque>;
      c_final = false; c_is_xhp = false; c_kind = Cnormal;
      c_name = ([7:7-12], "\\A\\AttrA");
      c_tparams = { c_tparam_list = []; c_tparam_constraints = <opaque> };
      c_extends = []; c_uses = []; c_method_redeclarations = [];
      c_xhp_attr_uses = []; c_xhp_category = None; c_req_extends = [];
      c_req_implements = [];
      c_implements =
      [([7:24-41], (Happly (([7:24-41], "\\HH\\FileAttribute"), [])))];
      c_consts = []; c_typeconsts = []; c_static_vars = []; c_vars = [];
      c_constructor = None; c_static_methods = []; c_methods = [];
      c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace = <opaque>; c_user_attributes = [];
      c_file_attributes =
      [{ fa_user_attributes =
         [{ ua_name = ([5:9-14], "\\A\\AttrA"); ua_params = [] }];
         fa_namespace = <opaque> };
        { fa_user_attributes =
          [{ ua_name = ([11:9-14], "\\B\\AttrB"); ua_params = [] }];
          fa_namespace = <opaque> }
        ];
      c_enum = None; c_pu_enums = []; c_doc_comment = None });
  (Class
     { c_span = [13:1-45]; c_annotation = (); c_mode = <opaque>;
       c_final = false; c_is_xhp = false; c_kind = Cnormal;
       c_name = ([13:7-12], "\\B\\AttrB");
       c_tparams = { c_tparam_list = []; c_tparam_constraints = <opaque> };
       c_extends = []; c_uses = []; c_method_redeclarations = [];
       c_xhp_attr_uses = []; c_xhp_category = None; c_req_extends = [];
       c_req_implements = [];
       c_implements =
       [([13:24-41], (Happly (([13:24-41], "\\HH\\FileAttribute"), [])))];
       c_consts = []; c_typeconsts = []; c_static_vars = []; c_vars = [];
       c_constructor = None; c_static_methods = []; c_methods = [];
       c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
       c_namespace = <opaque>; c_user_attributes = [];
       c_file_attributes =
       [{ fa_user_attributes =
          [{ ua_name = ([5:9-14], "\\A\\AttrA"); ua_params = [] }];
          fa_namespace = <opaque> };
         { fa_user_attributes =
           [{ ua_name = ([11:9-14], "\\B\\AttrB"); ua_params = [] }];
           fa_namespace = <opaque> }
         ];
       c_enum = None; c_pu_enums = []; c_doc_comment = None })
  ]
