[(Class
    { c_span = [7:1-45]; c_annotation = (); c_mode = Mstrict; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
      c_name = ([7:7-12], "\\A\\AttrA"); c_tparams = []; c_extends = []; 
      c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; 
      c_implements = [([7:24-41], (Happly (([7:24-41], "\\HH\\FileAttribute"), [])))]; 
      c_where_constraints = []; c_consts = []; c_typeconsts = []; c_vars = []; 
      c_methods = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "A"); 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = [{ ua_name = ([7:7-12], "__SupportDynamicType"); ua_params = [] }];
      c_file_attributes =
      [{ fa_user_attributes = [{ ua_name = ([5:9-14], "\\A\\AttrA"); ua_params = [] }];
         fa_namespace =
         { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
           ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "A"); 
           ns_is_codegen = false; ns_disable_xhp_element_mangling = false }
         };
        { fa_user_attributes = [{ ua_name = ([11:9-14], "\\B\\AttrB"); ua_params = [] }];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "B"); 
            ns_is_codegen = false; ns_disable_xhp_element_mangling = false }
          }
        ];
      c_docs_url = None; c_enum = None; c_doc_comment = None; c_emit_id = None; 
      c_internal = false; c_module = None });
  (Class
     { c_span = [13:1-45]; c_annotation = (); c_mode = Mstrict; c_final = false; 
       c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
       c_name = ([13:7-12], "\\B\\AttrB"); c_tparams = []; c_extends = []; 
       c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; 
       c_implements = [([13:24-41], (Happly (([13:24-41], "\\HH\\FileAttribute"), [])))]; 
       c_where_constraints = []; c_consts = []; c_typeconsts = []; c_vars = []; 
       c_methods = []; c_xhp_children = []; c_xhp_attrs = [];
       c_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "B"); 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       c_user_attributes = [{ ua_name = ([13:7-12], "__SupportDynamicType"); ua_params = [] }];
       c_file_attributes =
       [{ fa_user_attributes = [{ ua_name = ([5:9-14], "\\A\\AttrA"); ua_params = [] }];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "A"); 
            ns_is_codegen = false; ns_disable_xhp_element_mangling = false }
          };
         { fa_user_attributes = [{ ua_name = ([11:9-14], "\\B\\AttrB"); ua_params = [] }];
           fa_namespace =
           { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
             ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "B"); 
             ns_is_codegen = false; ns_disable_xhp_element_mangling = false }
           }
         ];
       c_docs_url = None; c_enum = None; c_doc_comment = None; c_emit_id = None; 
       c_internal = false; c_module = None })