Errors:
  [9:57-10:1] A semicolon `;` is expected here.
  [12:33-56] Attribute arguments must be literals
[(Class
    { c_span = [4:3-6:4]; c_annotation = (); c_mode = Mstrict; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
      c_name = ([4:9-30], "\\A\\MyStringFileAttribute"); c_tparams = []; 
      c_extends = []; c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; 
      c_reqs = []; c_implements = [([4:42-59], (Happly (([4:42-59], "\\HH\\FileAttribute"), [])))]; 
      c_where_constraints = []; c_consts = []; c_typeconsts = [];
      c_vars =
      [{ cv_final = false; cv_xhp_attr = None; cv_abstract = false; cv_readonly = false; 
         cv_visibility = Public; cv_type = ((string), (Some ([5:40-46], (Hprim Tstring)))); 
         cv_id = ([5:47-58], "attr_value"); cv_expr = None; cv_user_attributes = []; 
         cv_doc_comment = None; cv_is_static = false; cv_span = [5:47-58] }
        ];
      c_methods =
      [{ m_span = [5:5-63]; m_annotation = (); m_final = false; m_abstract = false; 
         m_static = false; m_readonly_this = false; m_visibility = Public; 
         m_name = ([5:21-32], "__construct"); m_tparams = []; m_where_constraints = [];
         m_params =
         [{ param_annotation = (string); param_type_hint = ((string), (Some ([5:40-46], (Hprim Tstring)))); 
            param_is_variadic = false; param_pos = [5:47-58]; param_name = "$attr_value"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = (Some Public) }
           ];
         m_ctxs = None; m_unsafe_ctxs = None;
         m_body =
         { fb_ast =
           [([5:47-58],
             (Expr
                ((string), [5:47-58],
                 (Binop
                    { bop = (Eq None); lhs = ((string), [5:47-58], (Obj_get (((this), [5:47-58], This), ((string), [5:47-58], (Id ([5:47-58], "attr_value"))), OG_nullthrows, Is_prop)));
                      rhs = ((string), [5:47-58], (Lvar ([5:47-58], $attr_value))) }))));
             ([Pos.none], Noop)]
           };
         m_fun_kind = FSync; m_user_attributes = []; m_readonly_ret = None; 
         m_ret = ((void), (Some ([5:21-32], (Hprim Tvoid)))); m_external = false; 
         m_doc_comment = None }
        ];
      c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "A"); 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = [{ ua_name = ([4:9-30], "__SupportDynamicType"); ua_params = [] }];
      c_file_attributes =
      [{ fa_user_attributes =
         [{ ua_name = ([12:11-32], "\\A\\MyStringFileAttribute");
            ua_params = [((string), [12:33-56], (Class_const (((A\MyClass), [12:33-40], (CI ([12:33-40], "\\A\\MyClass"))), ([12:42-56], "MY_CLASS_CONST"))))] }
           ];
         fa_namespace =
         { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
           ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "A"); 
           ns_is_codegen = false; ns_disable_xhp_element_mangling = false }
         }
        ];
      c_docs_url = None; c_enum = None; c_doc_comment = None; c_emit_id = None; 
      c_internal = false; c_module = None });
  (Class
     { c_span = [8:3-10:4]; c_annotation = (); c_mode = Mstrict; c_final = false; 
       c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
       c_name = ([8:9-16], "\\A\\MyClass"); c_tparams = []; c_extends = []; 
       c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; 
       c_implements = []; c_where_constraints = [];
       c_consts =
       [{ cc_user_attributes = []; cc_type = (Some ([9:11-17], (Hprim Tstring))); 
          cc_id = ([9:18-32], "MY_CLASS_CONST"); cc_kind = (CCConcrete ((string), [9:35-57], (String "my class const value"))); 
          cc_span = [9:5-57]; cc_doc_comment = None }
         ];
       c_typeconsts = []; c_vars = []; c_methods = []; c_xhp_children = []; 
       c_xhp_attrs = [];
       c_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "A"); 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       c_user_attributes = [{ ua_name = ([8:9-16], "__SupportDynamicType"); ua_params = [] }];
       c_file_attributes =
       [{ fa_user_attributes =
          [{ ua_name = ([12:11-32], "\\A\\MyStringFileAttribute");
             ua_params = [((string), [12:33-56], (Class_const (((A\MyClass), [12:33-40], (CI ([12:33-40], "\\A\\MyClass"))), ([12:42-56], "MY_CLASS_CONST"))))] }
            ];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "A"); 
            ns_is_codegen = false; ns_disable_xhp_element_mangling = false }
          }
         ];
       c_docs_url = None; c_enum = None; c_doc_comment = None; c_emit_id = None; 
       c_internal = false; c_module = None });
  (Class
     { c_span = [16:3-25]; c_annotation = (); c_mode = Mstrict; c_final = false; 
       c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
       c_name = ([16:9-21], "\\B\\MyOtherClass"); c_tparams = []; c_extends = []; 
       c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; 
       c_implements = []; c_where_constraints = []; c_consts = []; c_typeconsts = []; 
       c_vars = []; c_methods = []; c_xhp_children = []; c_xhp_attrs = [];
       c_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "B"); 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       c_user_attributes = [{ ua_name = ([16:9-21], "__SupportDynamicType"); ua_params = [] }];
       c_file_attributes =
       [{ fa_user_attributes =
          [{ ua_name = ([12:11-32], "\\A\\MyStringFileAttribute");
             ua_params = [((string), [12:33-56], (Class_const (((A\MyClass), [12:33-40], (CI ([12:33-40], "\\A\\MyClass"))), ([12:42-56], "MY_CLASS_CONST"))))] }
            ];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = (Some "A"); 
            ns_is_codegen = false; ns_disable_xhp_element_mangling = false }
          }
         ];
       c_docs_url = None; c_enum = None; c_doc_comment = None; c_emit_id = None; 
       c_internal = false; c_module = None })