Errors:
  [4:7-21] Unbound global function: 'unbound_func' is not a valid name for fun()
  [4:7-21] Unbound name (typing): unbound_func
[(Fun
    { f_span = [3:1-5:2]; f_annotation = (); f_mode = <opaque>;
      f_ret = ((void), (Some ([3:18-22], (Hprim Tvoid))));
      f_name = ([3:10-14], "\\test"); f_tparams = [];
      f_where_constraints = []; f_variadic = FVnonVariadic; f_params = [];
      f_body =
      { fb_ast =
        [([4:3-23],
          (Expr (([4:3-22], _), (Fun_id ([4:7-21], "\\unbound_func")))))];
        fb_annotation = No unsafe blocks };
      f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = [];
      f_external = false; f_namespace = <opaque>; f_doc_comment = None;
      f_static = false })
  ]
