[(Module
    { md_annotation = (); md_name = ([6:12-15], "a.b"); md_user_attributes = [];
      md_file_attributes =
      [{ fa_user_attributes = [{ ua_name = ([3:8-32], "__EnableUnstableFeatures"); ua_params = [((string), [3:33-42], (String "modules"))] }];
         fa_namespace =
         { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
           ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
           ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false }
         }
        ];
      md_span = [6:1-7:2]; md_mode = Mstrict; md_doc_comment = (Some ([5:1-29], "/** this is a doc comment */")); 
      md_exports = None; md_imports = None })