[(Class
    { c_span = [3:1-6:2]; c_annotation = (); c_mode = Mpartial; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = Cnormal; 
      c_name = ([3:7-8], "\\C"); c_tparams = []; c_extends = []; c_uses = []; 
      c_use_as_alias = []; c_insteadof_alias = []; c_xhp_attr_uses = []; 
      c_xhp_category = None; c_reqs = []; c_implements = []; c_implements_dynamic = false; 
      c_where_constraints = []; c_consts = []; c_typeconsts = []; c_vars = [];
      c_methods =
      [{ m_span = [4:3-46]; m_annotation = (); m_final = false; m_abstract = false; 
         m_static = true; m_readonly_this = false; m_visibility = Public; 
         m_name = ([4:26-35], "staticFoo"); m_tparams = []; m_where_constraints = []; 
         m_variadic = FVnonVariadic; m_params = []; m_ctxs = None; m_unsafe_ctxs = None; 
         m_body = { fb_ast = [([Pos.none], Noop)]; fb_annotation = () }; 
         m_fun_kind = FSync; m_user_attributes = []; m_readonly_ret = None; 
         m_ret = ((void), (Some ([4:39-43], (Hprim Tvoid)))); m_external = false; 
         m_doc_comment = None };
        { m_span = [5:3-41]; m_annotation = (); m_final = false; m_abstract = false; 
          m_static = false; m_readonly_this = false; m_visibility = Public; 
          m_name = ([5:19-30], "instanceFoo"); m_tparams = []; m_where_constraints = []; 
          m_variadic = FVnonVariadic; m_params = []; m_ctxs = None; m_unsafe_ctxs = None; 
          m_body = { fb_ast = [([Pos.none], Noop)]; fb_annotation = () }; 
          m_fun_kind = FSync; m_user_attributes = []; m_readonly_ret = None; 
          m_ret = ((void), (Some ([5:34-38], (Hprim Tvoid)))); m_external = false; 
          m_doc_comment = None }
        ];
      c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_enum = None; 
      c_doc_comment = None; c_emit_id = None });
  (Fun
     { f_span = [8:1-22:2]; f_readonly_this = None; f_annotation = (); 
       f_mode = Mpartial; f_readonly_ret = None; f_ret = ((void), (Some ([8:22-26], (Hprim Tvoid)))); 
       f_name = ([8:10-14], "\\test"); f_tparams = []; f_where_constraints = []; 
       f_variadic = FVnonVariadic;
       f_params =
       [{ param_annotation = ([8:17-19], C); param_type_hint = ((C), (Some ([8:15-16], (Happly (([8:15-16], "\\C"), []))))); 
          param_is_variadic = false; param_pos = [8:17-19]; param_name = "$c"; 
          param_expr = None; param_readonly = None; param_callconv = None; 
          param_user_attributes = []; param_visibility = None }
         ];
       f_ctxs = None; f_unsafe_ctxs = None;
       f_body =
       { fb_ast =
         [([9:3-15], (Expr (([9:3-15], void), (Call ((([9:3-7], _), (Id ([9:3-7], "echo"))), [], [(([9:8-13], string), (String "foo"))], None)))));
           ([10:3-16], (Expr (([10:3-15], void), (Call ((([10:3-15], _), (Id ([10:3-15], "echo"))), [], [(([10:9-14], string), (String "foo"))], None)))));
           ([12:3-15], (Expr (([12:3-14], (function(C $c): void)), (Fun_id ([12:7-13], "\\test")))));
           ([13:3-37], (Expr (([13:3-36], (function(): void)), (Smethod_id ((([13:14-15], C), (CI ([13:14-15], "\\C"))), ([13:24-35], "staticFoo"))))));
           ([14:3-32], (Expr (([14:3-31], (function(): void)), (Method_id ((([14:13-15], C), (Lvar ([14:13-15], $c))), ([14:17-30], "instanceFoo"))))));
           ([15:3-40], (Expr (([15:3-39], (function(C): void)), (Method_caller (([15:15-16], "\\C"), ([15:25-38], "instanceFoo"))))));
           ([17:3-13], (Expr (([17:3-12], bool), (Call ((([17:3-8], (function($x): bool)), (Id ([17:3-8], "\\isset"))), [], [(([17:9-11], C), (Lvar ([17:9-11], $c)))], None)))));
           ([18:3-13], (Expr (([18:3-13], void), (Call ((([18:3-8], (function($x): void)), (Id ([18:3-8], "\\unset"))), [], [(([18:9-11], C), (Lvar ([18:9-11], $c)))], None)))));
           ([20:3-26],
            (If ((([20:13-17], bool), (Unop (Unot, (([20:13-17], bool), True)))),
               [([20:3-25],
                 (Expr
                    (([20:3-25], noreturn),
                     (Call ((([20:3-12], (function(HH\FormatString<PlainSprintf> $fmt, ...): noreturn)), (Id ([20:3-12], "\\HH\\invariant_violation"))), 
                        [], [(([20:19-24], string), (String "foo"))], None)))))
                 ],
               [([Pos.none], Noop)])));
           ([21:3-30],
            (Expr
               (([21:3-29], noreturn),
                (Call ((([21:3-22], (function(HH\FormatString<PlainSprintf> $fmt, ...): noreturn)), (Id ([21:3-22], "\\HH\\invariant_violation"))), 
                   [], [(([21:23-28], string), (String "foo"))], None)))))
           ];
         fb_annotation = () };
       f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
       f_external = false;
       f_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       f_doc_comment = None })