[(Fun
    { Aast.AnnotatedAST.f_annotation = (); f_mode = <opaque>;
      f_ret =
      (Some ([3:18-3:20],
             (Aast_defs.Hfun (true, false,
                [([3:32-3:35], (Aast_defs.Hprim Aast_defs.Tint))], [None],
                Aast_defs.Hnon_variadic,
                ([3:39-3:43], (Aast_defs.Hprim Aast_defs.Tvoid))))));
      f_name = ([3:10-3:13], "\\foo"); f_tparams = [];
      f_where_constraints = []; f_variadic = FVnonVariadic; f_params = [];
      f_body =
      (NamedBody { Aast.AnnotatedAST.fnb_nast = [Noop]; fnb_unsafe = true });
      f_fun_kind = Ast_defs.FSync;
      f_user_attributes =
      [{ Aast.AnnotatedAST.ua_name = ([2:3-2:7], "__Rx"); ua_params = [] }];
      f_ret_by_ref = false })
  ]
