Errors:
  [6:21-23] Tc is a type parameter. Type parameters cannot themselves take type parameters (e.g. Tc<int> doesn't make sense)
  [4:10-12] Name already bound: Tc
  [4:7-9] Previous definition is here
[(Class
    { c_span = [4:1-7:2]; c_annotation = (); c_mode = <opaque>;
      c_final = false; c_is_xhp = false; c_kind = Cnormal;
      c_name = ([4:7-9], "\\Tc");
      c_tparams =
      { c_tparam_list =
        [{ tp_variance = Invariant; tp_name = ([4:10-12], "Tc");
           tp_constraints = []; tp_reified = Erased; tp_user_attributes = []
           }
          ];
        c_tparam_constraints = <opaque> };
      c_extends = []; c_uses = []; c_method_redeclarations = [];
      c_xhp_attr_uses = []; c_xhp_category = None; c_req_extends = [];
      c_req_implements = []; c_implements = []; c_consts = [];
      c_typeconsts = []; c_static_vars = []; c_vars = [];
      c_constructor = None; c_static_methods = [];
      c_methods =
      [{ m_span = [6:3-41]; m_annotation = (); m_final = false;
         m_abstract = false; m_static = false; m_visibility = Public;
         m_name = ([6:19-20], "f"); m_tparams = []; m_where_constraints = [];
         m_variadic = FVnonVariadic;
         m_params =
         [{ param_annotation = ([6:29-31], Tc);
            param_hint = (Some ([6:21-28], (Habstr "Tc")));
            param_is_reference = false; param_is_variadic = false;
            param_pos = [6:29-31]; param_name = "$x"; param_expr = None;
            param_callconv = None; param_user_attributes = [] }
           ];
         m_body =
         { fb_ast = [([Pos.none], Noop)]; fb_annotation = No unsafe blocks };
         m_fun_kind = FSync; m_user_attributes = [];
         m_ret = (Some ([6:34-38], (Hprim Tvoid))); m_external = false;
         m_doc_comment = None }
        ];
      c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace = <opaque>; c_user_attributes = []; c_file_attributes = [];
      c_enum = None; c_pu_enums = []; c_doc_comment = None });
  (Class
     { c_span = [9:1-12:2]; c_annotation = (); c_mode = <opaque>;
       c_final = false; c_is_xhp = false; c_kind = Cnormal;
       c_name = ([9:7-15], "\\Tc_other");
       c_tparams = { c_tparam_list = []; c_tparam_constraints = <opaque> };
       c_extends = []; c_uses = []; c_method_redeclarations = [];
       c_xhp_attr_uses = []; c_xhp_category = None; c_req_extends = [];
       c_req_implements = []; c_implements = []; c_consts = [];
       c_typeconsts = []; c_static_vars = []; c_vars = [];
       c_constructor = None; c_static_methods = [];
       c_methods =
       [{ m_span = [11:3-41]; m_annotation = (); m_final = false;
          m_abstract = false; m_static = false; m_visibility = Public;
          m_name = ([11:19-20], "f"); m_tparams = [];
          m_where_constraints = []; m_variadic = FVnonVariadic;
          m_params =
          [{ param_annotation = ([11:29-31], Tc<int>);
             param_hint =
             (Some ([11:21-28],
                    (Happly (([11:21-23], "\\Tc"),
                       [([11:24-27], (Hprim Tint))]))));
             param_is_reference = false; param_is_variadic = false;
             param_pos = [11:29-31]; param_name = "$x"; param_expr = None;
             param_callconv = None; param_user_attributes = [] }
            ];
          m_body =
          { fb_ast = [([Pos.none], Noop)]; fb_annotation = No unsafe blocks };
          m_fun_kind = FSync; m_user_attributes = [];
          m_ret = (Some ([11:34-38], (Hprim Tvoid))); m_external = false;
          m_doc_comment = None }
         ];
       c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
       c_namespace = <opaque>; c_user_attributes = [];
       c_file_attributes = []; c_enum = None; c_pu_enums = [];
       c_doc_comment = None })
  ]
