Errors:
  [7:3-13] `Tcat` cannot be used with `new` because it does not have the `<<__Newable>>` attribute
  [7:7-11] Erased generics can only be used in type hints because they do not exist at runtime.
[(Class
    { c_span = [4:1-14]; c_annotation = (); c_mode = Mstrict; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = Cnormal; 
      c_name = ([4:7-11], "\\Tcat"); c_tparams = []; c_extends = []; 
      c_uses = []; c_use_as_alias = []; c_insteadof_alias = []; c_xhp_attr_uses = []; 
      c_xhp_category = None; c_reqs = []; c_implements = []; c_implements_dynamic = false; 
      c_where_constraints = []; c_consts = []; c_typeconsts = []; c_vars = []; 
      c_methods = []; c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_enum = None; 
      c_doc_comment = None; c_emit_id = None });
  (Fun
     { f_span = [6:1-8:2]; f_readonly_this = None; f_annotation = (); 
       f_mode = Mstrict; f_readonly_ret = None; f_ret = ((void), (Some ([6:21-25], (Hprim Tvoid)))); 
       f_name = ([6:10-11], "\\f"); f_tparams = [{ tp_variance = Invariant; tp_name = ([6:12-16], "Tcat"); tp_parameters = []; tp_constraints = []; tp_reified = Erased; tp_user_attributes = [] }];
       f_where_constraints = []; f_variadic = FVnonVariadic; f_params = []; 
       f_ctxs = None; f_unsafe_ctxs = None;
       f_body = { fb_ast = [([7:3-14], (Expr (([7:3-13], Tcat), (New ((([7:7-11], Tcat), (CI ([7:7-11], "Tcat"))), [], [], None, ([7:7-11], _))))))]; fb_annotation = () }; 
       f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
       f_external = false;
       f_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       f_doc_comment = None });
  (Fun
     { f_span = [10:1-12:2]; f_readonly_this = None; f_annotation = (); 
       f_mode = Mstrict; f_readonly_ret = None; f_ret = ((void), (Some ([10:15-19], (Hprim Tvoid)))); 
       f_name = ([10:10-11], "\\g"); f_tparams = []; f_where_constraints = []; 
       f_variadic = FVnonVariadic; f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
       f_body = { fb_ast = [([11:3-14], (Expr (([11:3-13], Tcat), (New ((([11:7-11], Tcat), (CI ([11:7-11], "\\Tcat"))), [], [], None, ([11:7-11], _))))))]; fb_annotation = () }; 
       f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
       f_external = false;
       f_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       f_doc_comment = None })