[(AnnotatedAST.Fun
    { AnnotatedAST.f_mode = <opaque>;
      f_ret = (Some (<p>, (Hprim Tint)));
      f_name = (<p>, "\\f"); f_tparams = [];
      f_where_constraints = []; f_variadic = AnnotatedAST.FVnonVariadic;
      f_params = [];
      f_body =
      (AnnotatedAST.NamedBody
         { AnnotatedAST.fnb_nast =
           [(AnnotatedAST.Static_var
               [((Some int),
                 (AnnotatedAST.Binop ((Eq None),
                    ((Some int), (AnnotatedAST.Lvar (<p>, $x))),
                    ((Some int), (AnnotatedAST.Int (<p>, "42"))))))
                 ]);
             (AnnotatedAST.Return (<p>,
                (Some ((Some int), (AnnotatedAST.Lvar (<p>, $x))))
                ))
             ];
           fnb_unsafe = false });
      f_fun_kind = FSync; f_user_attributes = []; f_ret_by_ref = true });
  (AnnotatedAST.Class
     { AnnotatedAST.c_mode = <opaque>; c_final = false; c_is_xhp = false;
       c_kind = Cnormal; c_name = (<p>, "\\C");
       c_tparams = <opaque>; c_extends = []; c_uses = [];
       c_xhp_attr_uses = []; c_xhp_category = []; c_req_extends = [];
       c_req_implements = []; c_implements = []; c_consts = [];
       c_typeconsts = []; c_static_vars = [];
       c_vars =
       [{ AnnotatedAST.cv_final = false; cv_is_xhp = false;
          cv_visibility = Private;
          cv_type = (Some (<p>, (Hprim Tint)));
          cv_id = (<p>, "x");
          cv_expr =
          (Some ((Some int), (AnnotatedAST.Int (<p>, "42")))) }
         ];
       c_constructor = None; c_static_methods = [];
       c_methods =
       [{ AnnotatedAST.m_final = false; m_abstract = false;
          m_visibility = Public; m_name = (<p>, "f");
          m_tparams = []; m_where_constraints = [];
          m_variadic = AnnotatedAST.FVnonVariadic; m_params = [];
          m_body =
          (AnnotatedAST.NamedBody
             { AnnotatedAST.fnb_nast =
               [(AnnotatedAST.Return (<p>,
                   (Some ((Some int),
                          (AnnotatedAST.Obj_get (
                             ((Some <static>), AnnotatedAST.This),
                             (None,
                              (AnnotatedAST.Id (<p>, "x"))),
                             OG_nullthrows))))
                   ))
                 ];
               fnb_unsafe = false });
          m_fun_kind = FSync; m_user_attributes = [];
          m_ret = (Some (<p>, (Hprim Tint)));
          m_ret_by_ref = true }
         ];
       c_user_attributes = []; c_enum = None })
  ]
