[(AnnotatedAST.Fun
    { AnnotatedAST.f_annotation = (); f_mode = <opaque>;
      f_ret = (Some ([3:16-3:19], (Hprim Tint)));
      f_name = ([3:11-3:12], "\\f"); f_tparams = [];
      f_where_constraints = []; f_variadic = AnnotatedAST.FVnonVariadic;
      f_params = [];
      f_body =
      (AnnotatedAST.NamedBody
         { AnnotatedAST.fnb_nast =
           [(AnnotatedAST.Static_var
               [(([4:10-4:17], Some int),
                 (AnnotatedAST.Binop ((Eq None),
                    (([4:10-4:12], Some int),
                     (AnnotatedAST.Lvar ([4:10-4:12], $x))),
                    (([4:15-4:17], Some int),
                     (AnnotatedAST.Int ([4:15-4:17], "42")))
                    )))
                 ]);
             (AnnotatedAST.Return ([5:3-5:13],
                (Some (([5:10-5:12], Some int),
                       (AnnotatedAST.Lvar ([5:10-5:12], $x))))
                ))
             ];
           fnb_unsafe = false });
      f_fun_kind = FSync; f_user_attributes = []; f_ret_by_ref = true });
  (AnnotatedAST.Class
     { AnnotatedAST.c_annotation = (); c_mode = <opaque>; c_final = false;
       c_is_xhp = false; c_kind = Cnormal; c_name = ([8:7-8:8], "\\C");
       c_tparams = <opaque>; c_extends = []; c_uses = [];
       c_xhp_attr_uses = []; c_xhp_category = []; c_req_extends = [];
       c_req_implements = []; c_implements = []; c_consts = [];
       c_typeconsts = []; c_static_vars = [];
       c_vars =
       [{ AnnotatedAST.cv_final = false; cv_is_xhp = false;
          cv_visibility = Private;
          cv_type = (Some ([9:11-9:14], (Hprim Tint)));
          cv_id = ([9:15-9:17], "x");
          cv_expr =
          (Some (([9:20-9:22], Some int),
                 (AnnotatedAST.Int ([9:20-9:22], "42"))));
          cv_user_attributes = [] }
         ];
       c_constructor = None; c_static_methods = [];
       c_methods =
       [{ AnnotatedAST.m_annotation = (); m_final = false;
          m_abstract = false; m_visibility = Public;
          m_name = ([10:20-10:21], "f"); m_tparams = [];
          m_where_constraints = []; m_variadic = AnnotatedAST.FVnonVariadic;
          m_params = [];
          m_body =
          (AnnotatedAST.NamedBody
             { AnnotatedAST.fnb_nast =
               [(AnnotatedAST.Return ([11:5-11:21],
                   (Some (([11:12-11:20], Some int),
                          (AnnotatedAST.Obj_get (
                             (([11:12-11:17], Some <static>),
                              AnnotatedAST.This),
                             (([11:19-11:20], Some int),
                              (AnnotatedAST.Id ([11:19-11:20], "x"))),
                             OG_nullthrows))))
                   ))
                 ];
               fnb_unsafe = false });
          m_fun_kind = FSync; m_user_attributes = [];
          m_ret = (Some ([10:25-10:28], (Hprim Tint))); m_ret_by_ref = true }
         ];
       c_user_attributes = []; c_enum = None })
  ]
