[(Fun
    { Aast.AnnotatedAST.f_annotation = (); f_mode = <opaque>;
      f_ret = (Some ([3:51-54], (Hprim Tint)));
      f_name = ([3:10-14], "\\test"); f_tparams = [];
      f_where_constraints = []; f_variadic = FVnonVariadic;
      f_params =
      [{ Aast.AnnotatedAST.param_annotation = ([3:20-22], bool);
         param_hint = (Some ([3:15-19], (Hprim Tbool)));
         param_is_reference = false; param_is_variadic = false;
         param_pos = [3:20-22]; param_name = "$b"; param_expr = None;
         param_callconv = None; param_user_attributes = [] };
        { Aast.AnnotatedAST.param_annotation =
          ([3:46-48], (function(int): int));
          param_hint =
          (Some ([3:24-45],
                 (Hfun (FNonreactive, false, [([3:35-38], (Hprim Tint))],
                    [None], Hnon_variadic, ([3:41-44], (Hprim Tint))))));
          param_is_reference = false; param_is_variadic = false;
          param_pos = [3:46-48]; param_name = "$f"; param_expr = None;
          param_callconv = None; param_user_attributes = [] }
        ];
      f_body =
      (NamedBody
         { Aast.AnnotatedAST.fnb_nast =
           [(If ((([4:7-9], bool), (Lvar ([4:7-9], $b))), [Noop], [Noop]));
             (Return ([5:3-16],
                (Some (([5:10-15], int),
                       (Call (Cnormal,
                          (([5:10-12], (function(int): int)),
                           (Lvar ([5:10-12], $f))),
                          [], [(([5:13-14], int), (Int "1"))], []))))
                ))
             ];
           fnb_unsafe = false });
      f_fun_kind = FSync; f_user_attributes = []; f_ret_by_ref = false })
  ]
