Errors:
  [13:3-16] Invalid assignment
  [5:12-15] Expected `int`
  [3:23-29] But got `string`
[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict;
      fd_fun =
      { f_span = [3:1-15:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((int), (Some ([3:35-38], (Hprim Tint)))); 
        f_name = ([3:10-14], "\\test"); f_tparams = []; f_where_constraints = []; 
        f_variadic = FVnonVariadic;
        f_params =
        [{ param_annotation = ([3:19-21], int); param_type_hint = ((int), (Some ([3:15-18], (Hprim Tint)))); 
           param_is_variadic = false; param_pos = [3:19-21]; param_name = "$i"; 
           param_expr = None; param_readonly = None; param_callconv = None; 
           param_user_attributes = []; param_visibility = None };
          { param_annotation = ([3:30-32], string); param_type_hint = ((string), (Some ([3:23-29], (Hprim Tstring)))); 
            param_is_variadic = false; param_pos = [3:30-32]; param_name = "$s"; 
            param_expr = None; param_readonly = None; param_callconv = None; 
            param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([4:3-26],
            (Expr
               (([4:3-25], Vector<int>), [4:3-25],
                (Binop ((Eq None), (([4:3-9], Vector<int>), [4:3-9], (Lvar ([4:3-9], $items))),
                   (([4:12-25], Vector<int>), [4:12-25], (ValCollection (Vector, None, [(([4:21-23], int), [4:21-23], (Lvar ([4:21-23], $i)))]))))))));
            ([5:3-12:5],
             (Expr
                (([5:3-12:4], (function(): int)), [5:3-12:4],
                 (Binop ((Eq None), (([5:3-5], (function(): int)), [5:3-5], (Lvar ([5:3-5], $f))),
                    (([5:8-12:4], (function(): int)), [5:8-12:4],
                     (Lfun (
                        { f_span = [5:8-12:4]; f_readonly_this = None; 
                          f_annotation = (); f_readonly_ret = None; f_ret = ((int), (Some ([5:12-15], (Hprim Tint)))); 
                          f_name = ([5:8-12:4], ";anonymous"); f_tparams = []; 
                          f_where_constraints = []; f_variadic = FVnonVariadic; 
                          f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
                          f_body =
                          { fb_ast =
                            [([10:5-23],
                              (Expr
                                 (([10:5-22], int), [10:5-22],
                                  (Binop ((Eq None), (([10:5-10], int), [10:5-10], (Lvar ([10:5-10], $item))),
                                     (([10:13-22], int), [10:13-22],
                                      (Array_get ((([10:13-19], Vector<int>), [10:13-19], (Lvar ([10:13-19], $items))), (Some (([10:20-21], int), [10:20-21], (Int "1"))))))
                                     )))));
                              ([11:5-18], (Return (Some (([11:12-17], int), [11:12-17], (Lvar ([11:12-17], $item))))))];
                            fb_annotation = () };
                          f_fun_kind = FSync; f_user_attributes = []; 
                          f_external = false; f_doc_comment = None },
                        [([10:13-19], $items)])))
                    )))));
            ([13:3-17],
             (Expr
                (([13:3-16], string), [13:3-16],
                 (Binop ((Eq None), (([13:3-11], string), [13:3-11], (Array_get ((([13:3-9], Vector<int>), [13:3-9], (Lvar ([13:3-9], $items))), None))),
                    (([13:14-16], string), [13:14-16], (Hole ((([13:14-16], string), [13:14-16], (Lvar ([13:14-16], $s))), (string), (int), Typing))))))));
            ([14:3-15], (Return (Some (([14:10-14], int), [14:10-14], (Call ((([14:10-12], (function(): int)), [14:10-12], (Lvar ([14:10-12], $f))), [], [], None))))))];
          fb_annotation = () };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None }
      })