[(Fun
    { f_span = [12:1-21:2]; f_annotation = (); f_mode = <opaque>;
      f_ret = None; f_name = ([12:10-13], "\\foo"); f_tparams = [];
      f_where_constraints = []; f_variadic = FVnonVariadic;
      f_params =
      [{ param_annotation = ([12:19-21], bool);
         param_hint = (Some ([12:14-18], (Hprim Tbool)));
         param_is_reference = false; param_is_variadic = false;
         param_pos = [12:19-21]; param_name = "$b"; param_expr = None;
         param_callconv = None; param_user_attributes = [] }
        ];
      f_body =
      (NamedBody
         { fnb_nast =
           [(If ((([13:7-9], bool), (Lvar ([13:7-9], $b))),
               [(Expr
                   (([15:7-12], _),
                    (Call (Cnormal,
                       (([15:7-10], _), (Id ([15:7-10], "\\bar"))), [], 
                       [], []))));
                 (Unsafe_block
                    [(Expr
                        (([17:7-12], _),
                         (Call (Cnormal,
                            (([17:7-10], _), (Id ([17:7-10], "\\baz"))), 
                            [], [], []))))
                      ]);
                 (Expr
                    (([19:5-10], _),
                     (Call (Cnormal,
                        (([19:5-8], _), (Id ([19:5-8], "\\qux"))), [], 
                        [], []))))
                 ],
               [Noop]))
             ];
           fnb_unsafe = true });
      f_fun_kind = FSync; f_user_attributes = []; f_ret_by_ref = false;
      f_external = false; f_namespace = <opaque>;
      f_doc_comment =
      (Some "/**\n * Copyright (c) 2014, Facebook, Inc.\n * All rights reserved.\n *\n * This source code is licensed under the MIT license found in the\n * LICENSE file in the \"hack\" directory of this source tree.\n *\n *\n */");
      f_static = false })
  ]
