[(Class
    { c_span = [3:1-7:2]; c_annotation = (); c_mode = <opaque>;
      c_final = false; c_is_xhp = false; c_kind = Cnormal;
      c_name = ([3:7-12], "\\Three");
      c_tparams = { c_tparam_list = []; c_tparam_constraints = <opaque> };
      c_extends = []; c_uses = []; c_method_redeclarations = [];
      c_xhp_attr_uses = []; c_xhp_category = None; c_req_extends = [];
      c_req_implements = []; c_implements = []; c_consts = [];
      c_typeconsts = []; c_static_vars = []; c_vars = [];
      c_constructor = None; c_static_methods = [];
      c_methods =
      [{ m_span = [4:3-6:4]; m_annotation = (); m_final = false;
         m_abstract = false; m_static = false; m_visibility = Public;
         m_name = ([4:19-29], "__toString"); m_tparams = [];
         m_where_constraints = []; m_variadic = FVnonVariadic; m_params = [];
         m_body =
         { fb_ast =
           [([5:5-16], (Return (Some (([5:12-15], string), (String "3")))))];
           fb_annotation = No unsafe blocks };
         m_fun_kind = FSync; m_user_attributes = [];
         m_ret = (Some ([4:33-39], (Hprim Tstring))); m_external = false;
         m_doc_comment = None }
        ];
      c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace = <opaque>; c_user_attributes = []; c_file_attributes = [];
      c_enum = None; c_pu_enums = []; c_doc_comment = None });
  (Fun
     { f_span = [9:1-13:2]; f_annotation = (); f_mode = <opaque>;
       f_ret = (Some ([9:18-21], (Hprim Tint)));
       f_name = ([9:10-14], "\\test"); f_tparams = [];
       f_where_constraints = []; f_variadic = FVnonVariadic; f_params = [];
       f_body =
       { fb_ast =
         [([10:3-10],
           (Expr
              (([10:3-9], int),
               (Binop ((Eq None), (([10:3-5], int), (Lvar ([10:3-5], $x))),
                  (([10:8-9], int), (Int "0")))))));
           ([11:21-51],
            (Expr
               (([11:21-50], _),
                (Unsafe_expr
                   (([11:21-50], _),
                    (Call (Cnormal,
                       (([11:21-25], _), (Id ([11:21-25], "\\eval"))), 
                       [],
                       [(([11:26-49], _),
                         (Binop (Dot,
                            (([11:26-45], _),
                             (Binop (Dot,
                                (([11:26-33], _), (String "$x = ")),
                                (([11:34-45], _),
                                 (New (
                                    (([11:38-43], _),
                                     (CI ([11:38-43], "\\Three"))),
                                    [], [], [], ([11:38-43], _))))
                                ))),
                            (([11:46-49], _), (String ";")))))
                         ],
                       [])))))));
           ([12:3-13],
            (Return (Some (([12:10-12], int), (Lvar ([12:10-12], $x))))))
           ];
         fb_annotation = No unsafe blocks };
       f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = [];
       f_external = false; f_namespace = <opaque>; f_doc_comment = None;
       f_static = false })
  ]
