{
  "actual_type": "bool",
  "full_actual_type": {
    "src_pos": {
      "filename": "/call_multiple.php",
      "line": 5,
      "char_start": 24,
      "char_end": 27
    },
    "kind": "primitive",
    "name": "bool"
  },
  "expected_type": "int",
  "full_expected_type": {
    "src_pos": {
      "filename": "/call_multiple.php",
      "line": 3,
      "char_start": 12,
      "char_end": 14
    },
    "kind": "primitive",
    "name": "int"
  }
}
