HHVM_DEFINE_EXTENSION("imagick"
  IS_ENABLED EXT_IMAGICK
  SOURCES
    constants.cpp
    ext_imagick.cpp
    imagick.cpp
    imagickdraw.cpp
    imagickpixel.cpp
    imagicpixeliterator.cpp
  HEADERS
    constants.h
    ext_imagick.h
  EXTENSION_LIBRARY
    ext_imagick.php
  DEPENDS_UPON
    ext_std
    ext_string
    libMagickWand
)
