=== hh_client result ===
argv: hh_client decompress-zhhdg
cwd: <test_tmp>/root
exit_code: 2
stdout:
<empty>
stderr:
The '--path' option is required.
=== telemetry ===
[
  {
    "argv": "hh_client decompress-zhhdg",
    "client_command": "Args",
    "event": "CLIENT_BAD_ARGS",
    "exception": "Stdlib.Arg.Bad(\"The '--path' option is required.\")",
    "exit_code": 2,
    "exit_status": "Exit_status.Input_error",
    "process": "client"
  },
  {
    "event": "INIT_INFO"
  }
]
