=== hh_client result ===
argv: hh_client lsp .
cwd: <test_tmp>/root
exit_code: 1
stdout:
<empty>
stderr:
Error: could not find a .hhconfig file in <test_tmp>/no_config or any of its parent directories. Do you have a .hhconfig in your code's root directory?
<stack trace omitted>
=== telemetry ===
[
  {
    "argv": "hh_client lsp .",
    "event": "CLIENT_LSP_START",
    "process": "client"
  },
  {
    "event": "INIT_INFO"
  },
  {
    "event": "INIT_INFO"
  },
  {
    "event": "SERVERLESS_IDE_DONE",
    "exit_code": 0,
    "process": "clientIdeDaemon"
  },
  {
    "event": "SERVERLESS_IDE_EXIT",
    "process": "clientIdeDaemon"
  }
]
