=== hh_client result ===
argv: hh_client lsp ../no_config
cwd: <test_tmp>/root
exit_code: 1
stdout:
<empty>
stderr:
Error: could not find a .hhconfig file in <test_tmp>/no_config or any of its parent directories. Do you have a .hhconfig in your code's root directory?
=== telemetry ===
[
  {
    "argv": "hh_client lsp ../no_config",
    "client_command": "Args",
    "event": "CLIENT_BAD_ARGS",
    "exception": "Stdlib.Arg.Bad(\"Error: could not find a .hhconfig file in <test_tmp>/no_config or any of its parent directories. Do you have a .hhconfig in your code's root directory?\")",
    "exit_code": 1,
    "exit_status": "Exit_status.Input_error",
    "process": "client"
  },
  {
    "event": "INIT_INFO"
  }
]
