=== hh_client result ===
argv: hh_client ../no_config/missing
cwd: <test_tmp>/root
exit_code: 64
stdout:
<empty>
stderr:
Error: ../no_config/missing is not a directory
=== telemetry ===
[
  {
    "argv": "hh_client ../no_config/missing",
    "client_command": "Args",
    "event": "CLIENT_BAD_ARGS",
    "exception": "Stdlib.Arg.Bad(\"Error: ../no_config/missing is not a directory\")",
    "exit_code": 64,
    "exit_status": "Exit_status.Client_bad_args",
    "process": "client"
  },
  {
    "event": "INIT_INFO"
  }
]
