=== hh_client result ===
argv: hh_client --lint test.php --lint test.php
cwd: <test_tmp>/root
exit_code: 2
stdout:
<empty>
stderr:
hh_client: only a single mode should be specified.
Usage: hh_client check [OPTION]... [WWW-ROOT]
<usage omitted>
=== telemetry ===
[
  {
    "argv": "hh_client --lint test.php --lint test.php",
    "client_command": "Args",
    "event": "CLIENT_BAD_ARGS",
    "exception": "Stdlib.Arg.Bad(\"hh_client: only a single mode should be specified.\")",
    "exit_code": 2,
    "exit_status": "Exit_status.Input_error",
    "process": "client"
  },
  {
    "event": "INIT_INFO"
  }
]
