=== hh_client result ===
argv: hh_client --refactor Bogus old new
cwd: <test_tmp>/root
exit_code: 64
stdout:
<empty>
stderr:
hh_client: wrong argument 'Bogus'; option '--refactor' expects one of: Class Function Method.
Usage: hh_client check [OPTION]... [WWW-ROOT]
<usage omitted>
=== telemetry ===
[
  {
    "argv": "hh_client --refactor Bogus old new",
    "client_command": "Args",
    "event": "CLIENT_BAD_ARGS",
    "exception": "Stdlib.Arg.Bad(\"hh_client: wrong argument 'Bogus'; option '--refactor' expects one of: Class Function Method.\")",
    "exit_code": 64,
    "exit_status": "Exit_status.Client_bad_args",
    "process": "client"
  },
  {
    "event": "INIT_INFO"
  }
]
