ERROR: File "is_as_splat_banned.php", line 13, characters 13-39:
Invalid `is` expression hint (Typing[4195])
  File "is_as_splat_banned.php", line 13, characters 13-39:
  The `is` operator cannot be used with a shape type with a splat element
ERROR: File "is_as_splat_banned.php", line 14, characters 9-35:
Invalid `as` expression hint (Typing[4195])
  File "is_as_splat_banned.php", line 14, characters 9-35:
  The `as` operator cannot be used with a shape type with a splat element
ERROR: File "is_as_splat_banned.php", line 18, characters 13-23:
Invalid `is` expression hint (Typing[4195])
  File "is_as_splat_banned.php", line 18, characters 13-23:
  The `is` operator cannot be used with a shape type with a splat element
ERROR: File "is_as_splat_banned.php", line 19, characters 9-19:
Invalid `as` expression hint (Typing[4195])
  File "is_as_splat_banned.php", line 19, characters 9-19:
  The `as` operator cannot be used with a shape type with a splat element
