ERROR: File "typaram_splat_requires_feature.php", line 15, characters 14-14:
This generic parameter is redundant because it only appears in a covariant (output) position with useless `as` bound. Consider replacing uses of generic parameter with `nothing` or specifying `<<__Explicit>>` on the generic parameter (Typing[4366])
ERROR: File "typaram_splat_requires_feature.php", line 15, characters 50-50:
`T` requires the unstable feature `shape_splat_type_parameters`. Add `<<file: __EnableUnstableFeatures('shape_splat_type_parameters')>>` to use it. (Typing[4509])
