Test begin
In C::__construct()
HipHop Notice:  Undefined variable: this in src/test/vm/FPushClsMethod.php on line 11
In C::sMeth(): $this::
In D::D()
In E::E()
In E::__construct()
In C::__construct()
HipHop Notice:  Undefined variable: this in src/test/vm/FPushClsMethod.php on line 11
In C::sMeth(): $this::
In D::D()
In E::E()
In E::__construct()
In I::__construct()
In D::D()
In J::J()
In E::E()
In K::K()
In K::__construct()
In C::__construct()
HipHop Notice:  Undefined variable: this in src/test/vm/FPushClsMethod.php on line 11
In C::sMeth(): $this::
In C::__construct()
HipHop Notice:  Undefined variable: this in src/test/vm/FPushClsMethod.php on line 11
In C::sMeth(): $this::
In D::D()
In D::D()
In D::D()
In E::E()
In E::E()
In E::__construct()
In E::__construct()
In C::__construct()
HipHop Notice:  Undefined variable: this in src/test/vm/FPushClsMethod.php on line 11
In C::sMeth(): $this::
In C::__construct()
HipHop Notice:  Undefined variable: this in src/test/vm/FPushClsMethod.php on line 11
In C::sMeth(): $this::
In D::D()
In D::D()
In E::E()
In E::E()
In E::__construct()
In E::__construct()
In I::__construct()
In I::__construct()
In D::D()
In D::D()
In J::J()
In J::J()
In E::E()
In E::E()
In K::K()
In K::K()
In K::__construct()
In K::__construct()
Test end
