HHVM_EXTENSION_CHECK_DEPENDENCIES(xsl LibXslt)
if (ENABLE_EXTENSION_XSL)
  HHVM_SELECT_SOURCES(HRE_CURRENT_EXT_PATH)
  message(STATUS "Building the xsl extension")
else()
  message("Not building the xsl extension")
endif ()