(*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the "hack" directory of this source tree.
 *
 *)

let is_statement =
  Full_fidelity_positioned_syntax.(
    function
    | ExpressionStatement _
    | EchoStatement _
    | ContinueStatement _
    | BreakStatement _
    | ThrowStatement _
    | YieldBreakStatement _
    | ReturnStatement _
    | MatchStatement _
    | SwitchStatement _
    | ForeachStatement _
    | ForStatement _
    | DoStatement _
    | TryStatement _
    | IfStatement _
    | WhileStatement _
    | UsingStatementFunctionScoped _
    | UsingStatementBlockScoped _
    | DeclareLocalStatement _
    | UnsetStatement _
    | CompoundStatement _ ->
      true
    | Token _
    | Missing
    | SyntaxList _
    | EndOfFile _
    | Script _
    | QualifiedName _
    | MatchStatementArm _
    | ModuleName _
    | SimpleTypeSpecifier _
    | LiteralExpression _
    | PrefixedStringExpression _
    | PrefixedCodeExpression _
    | VariableExpression _
    | PipeVariableExpression _
    | FileAttributeSpecification _
    | EnumDeclaration _
    | EnumUse _
    | Enumerator _
    | EnumClassDeclaration _
    | EnumClassEnumerator _
    | AliasDeclaration _
    | ContextAliasDeclaration _
    | CaseTypeDeclaration _
    | CaseTypeVariant _
    | PropertyDeclaration _
    | PropertyDeclarator _
    | NamespaceDeclaration _
    | NamespaceDeclarationHeader _
    | NamespaceBody _
    | NamespaceEmptyBody _
    | NamespaceUseDeclaration _
    | NamespaceGroupUseDeclaration _
    | NamespaceUseClause _
    | FunctionDeclaration _
    | FunctionDeclarationHeader _
    | Contexts _
    | WhereClause _
    | WhereConstraint _
    | MethodishDeclaration _
    | MethodishTraitResolution _
    | ClassishDeclaration _
    | ClassishBody _
    | TraitUse _
    | RequireClause _
    | ConstDeclaration _
    | ConstantDeclarator _
    | TypeConstDeclaration _
    | ContextConstDeclaration _
    | DecoratedExpression _
    | ParameterDeclaration _
    | OldAttributeSpecification _
    | AttributeSpecification _
    | Attribute _
    | InclusionExpression _
    | InclusionDirective _
    | MarkupSection _
    | MarkupSuffix _
    | ElseClause _
    | CatchClause _
    | FinallyClause _
    | SwitchSection _
    | SwitchFallthrough _
    | CaseLabel _
    | DefaultLabel _
    | ConcurrentStatement _
    | SimpleInitializer _
    | AnonymousClass _
    | AnonymousFunction _
    | AnonymousFunctionUseClause _
    | VariablePattern _
    | ConstructorPattern _
    | RefinementPattern _
    | LambdaExpression _
    | LambdaSignature _
    | CastExpression _
    | ScopeResolutionExpression _
    | MemberSelectionExpression _
    | SafeMemberSelectionExpression _
    | EmbeddedMemberSelectionExpression _
    | YieldExpression _
    | PrefixUnaryExpression _
    | PostfixUnaryExpression _
    | BinaryExpression _
    | IsExpression _
    | AsExpression _
    | NullableAsExpression _
    | UpcastExpression _
    | ConditionalExpression _
    | EvalExpression _
    | IssetExpression _
    | NameofExpression _
    | FunctionCallExpression _
    | FunctionPointerExpression _
    | ParenthesizedExpression _
    | BracedExpression _
    | ETSpliceExpression _
    | EmbeddedBracedExpression _
    | ListExpression _
    | CollectionLiteralExpression _
    | ObjectCreationExpression _
    | ConstructorCall _
    | DarrayIntrinsicExpression _
    | DictionaryIntrinsicExpression _
    | KeysetIntrinsicExpression _
    | VarrayIntrinsicExpression _
    | VectorIntrinsicExpression _
    | ElementInitializer _
    | SubscriptExpression _
    | EmbeddedSubscriptExpression _
    | AwaitableCreationExpression _
    | XHPChildrenDeclaration _
    | XHPChildrenParenthesizedList _
    | XHPCategoryDeclaration _
    | XHPEnumType _
    | XHPLateinit _
    | XHPRequired _
    | XHPClassAttributeDeclaration _
    | XHPClassAttribute _
    | XHPSimpleClassAttribute _
    | XHPSimpleAttribute _
    | XHPSpreadAttribute _
    | XHPOpen _
    | XHPExpression _
    | XHPClose _
    | TypeConstant _
    | VectorTypeSpecifier _
    | KeysetTypeSpecifier _
    | TupleTypeExplicitSpecifier _
    | VarrayTypeSpecifier _
    | FunctionCtxTypeSpecifier _
    | TypeParameter _
    | TypeConstraint _
    | ContextConstraint _
    | DarrayTypeSpecifier _
    | DictionaryTypeSpecifier _
    | ClosureTypeSpecifier _
    | ClosureParameterTypeSpecifier _
    | TupleOrUnionOrIntersectionElementTypeSpecifier _
    | TypeRefinement _
    | TypeInRefinement _
    | CtxInRefinement _
    | ClassnameTypeSpecifier _
    | ClassPtrTypeSpecifier _
    | FieldSpecifier _
    | FieldInitializer _
    | ShapeTypeSpecifier _
    | ShapeExpression _
    | TupleExpression _
    | GenericTypeSpecifier _
    | NullableTypeSpecifier _
    | LikeTypeSpecifier _
    | SoftTypeSpecifier _
    | AttributizedSpecifier _
    | ReifiedTypeArgument _
    | TypeArguments _
    | TypeParameters _
    | TupleTypeSpecifier _
    | UnionTypeSpecifier _
    | IntersectionTypeSpecifier _
    | ErrorSyntax _
    | ListItem _
    | EnumClassLabelExpression _
    | ModuleDeclaration _
    | ModuleMembershipDeclaration _
    | PackageExpression _ ->
      false)
