((script 216
  ((list 216
    ((markup_section 4
      ((missing 0 ()) (() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))
       (missing 0 ())))
     (classish_declaration 200
      ((missing 0 ()) (missing 0 ())
       (((end_of_line 1)) interface 9 ((whitespace 1)))
       (() name 2 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 187
        ((() { 1 ((end_of_line 1)))
         (list 147
          ((const_declaration 30
            ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 12
              ((list_item 12
                ((constant_declarator 12
                  ((() name 8 ((whitespace 1)))
                   (simple_initializer 3
                    ((() = 1 ((whitespace 1)))
                     (literal 1 ((() decimal_literal 1 ())))))))
                 (missing 0 ())))))
             (() ";" 1
              ((whitespace 1) (single_line_comment 8) (end_of_line 1)))))
           (const_declaration 33
            ((list 7 ((((whitespace 2)) private 7 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 14
              ((list_item 14
                ((constant_declarator 14
                  ((() name 10 ((whitespace 1)))
                   (simple_initializer 3
                    ((() = 1 ((whitespace 1)))
                     (literal 1 ((() decimal_literal 1 ())))))))
                 (missing 0 ())))))
             (() ";" 1
              ((whitespace 2) (single_line_comment 32) (end_of_line 1)))))
           (const_declaration 35
            ((list 9 ((((whitespace 2)) protected 9 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 14
              ((list_item 14
                ((constant_declarator 14
                  ((() name 10 ((whitespace 1)))
                   (simple_initializer 3
                    ((() = 1 ((whitespace 1)))
                     (literal 1 ((() decimal_literal 1 ())))))))
                 (missing 0 ())))))
             (() ";" 1
              ((whitespace 2) (single_line_comment 32) (end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
