((script 162
  ((list 162
    ((markup_section 4
      ((missing 0 ()) (() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))
       (missing 0 ())))
     (classish_declaration 146
      ((missing 0 ())
       (list 8 ((((end_of_line 1)) abstract 8 ((whitespace 1)))))
       (() class 5 ((whitespace 1))) (() name 1 ((whitespace 1)))
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ())
       (classish_body 129
        ((() { 1 ((end_of_line 1)))
         (list 123
          ((const_declaration 42
            ((list 22
              ((((whitespace 2)) public 6 ((whitespace 1)))
               (() abstract 8 ((whitespace 1)))
               (() public 6 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 8
              ((list_item 8
                ((constant_declarator 8 ((() name 8 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 38
            ((list 18
              ((((whitespace 2)) abstract 8 ((whitespace 1)))
               (() protected 9 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 8
              ((list_item 8
                ((constant_declarator 8 ((() name 8 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((list 17
              ((((whitespace 2)) abstract 8 ((whitespace 1)))
               (() abstract 8 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 8
              ((list_item 8
                ((constant_declarator 8 ((() name 8 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
