((script 210
  ((list 210
    ((markup_section 4
      ((missing 0 ()) (() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))
       (missing 0 ())))
     (classish_declaration 194
      ((missing 0 ())
       (list 8 ((((end_of_line 1)) abstract 8 ((whitespace 1)))))
       (() class 5 ((whitespace 1))) (() name 1 ((whitespace 1)))
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ())
       (classish_body 177
        ((() { 1 ((end_of_line 1)))
         (list 171
          ((const_declaration 40
            ((list 15
              ((((whitespace 2)) public 6 ((whitespace 1)))
               (() abstract 8 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 13
              ((list_item 13
                ((constant_declarator 13 ((() name 13 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 40
            ((list 18
              ((((whitespace 2)) protected 9 ((whitespace 1)))
               (() abstract 8 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 10
              ((list_item 10
                ((constant_declarator 10 ((() name 10 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 41
            ((list 15
              ((((whitespace 2)) abstract 8 ((whitespace 1)))
               (() public 6 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 14
              ((list_item 14
                ((constant_declarator 14 ((() name 14 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 41
            ((list 18
              ((((whitespace 2)) abstract 8 ((whitespace 1)))
               (() protected 9 ((whitespace 1)))))
             (() const 5 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 11
              ((list_item 11
                ((constant_declarator 11 ((() name 11 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
