<?hh

// untyped
function f($a) {
  <unchecked>echo</unchecked> <unchecked>$a</unchecked>;
}

// partially typed array
function g(array $a) {
  <unchecked>echo</unchecked> <partial>$a</partial>;
}

// partially typed return value
async function h() {
  return <checked>1</checked>;
}

// partially typed return value used here
function i() {
  <unchecked>echo</unchecked> <partial>h</partial>();
}

function strict(int $x): int {
  return <checked>$x</checked>;
}

function use_strict() {
  <unchecked>echo</unchecked> <checked>strict</checked>(<checked>1</checked>);
}
