=== Shape analysis results for call_assign_2.php
Constraints after closing for \f:
Parameter at [9:12-30]
Allocation at [4:8-23]
Debug at [6:11-13]
SK Base [4:8-23] : shape('a' => int)
SK Base ?1 : shape('b' => bool)
SK Derived [4:8-23] : shape('a' => int)
SK Derived [5:5-7] : shape('a' => int)
SK Derived [6:11-13] : shape('a' => int)
SK Derived ?1 : shape('a' => int)
SK Derived ?1 : shape('b' => bool)
SK Derived ?2 : shape('a' => int)
SK Derived ?2 : shape('b' => bool)
[4:8-23] ⊆ [4:8-23]
[4:8-23] ⊆ [5:5-7]
[4:8-23] ⊆ [6:11-13]
[4:8-23] ⊆ ?1
[4:8-23] ⊆ ?2
[5:5-7] ⊆ [5:5-7]
[6:11-13] ⊆ [6:11-13]
[9:12-30] ⊆ [9:12-30]
?1 ⊆ ?1
?1 ⊆ ?2
?2 ⊆ ?2

Constraints after closing for \g:
Parameter at [9:12-30]
SK Base ?1 : shape('b' => bool)
SK Derived ?1 : shape('b' => bool)
SK Derived ?2 : shape('b' => bool)
[9:12-30] ⊆ [9:12-30]
?1 ⊆ ?1
?1 ⊆ ?2
?2 ⊆ ?2
Arg(\g, 0) ⊆ ?1
Arg(\g, 0) ⊆ ?2
Arg(\g, 0) ⊆ Arg(\g, 0)

