File "array_get_bad.php", line 43, characters 15-22:
Invalid index type for this Map (Typing[4324])
  File "array_get_bad.php", line 22, characters 7-12:
  This is a string
  File "array_get_bad.php", line 43, characters 20-21:
  It is incompatible with an int
File "array_get_bad.php", line 45, characters 15-23:
Invalid index type for this ImmMap (Typing[4324])
  File "array_get_bad.php", line 23, characters 10-15:
  This is a string
  File "array_get_bad.php", line 45, characters 21-22:
  It is incompatible with an int
