=== SDT analysis results for multiple_hierarchies.php
{"entry_kind":"stats","id_cnt":4,"nadable_cnt":4,"syntactically_nadable_cnt":4}
{"entry_kind":"add_no_auto_dynamic_attr","items":[{"kind":"(Cclass Concrete)","sid":"\\E"}]}
{"entry_kind":"add_no_auto_dynamic_attr","items":[{"kind":"(Cclass Concrete)","sid":"\\C"},{"kind":"Cinterface","sid":"\\I"}]}
{"entry_kind":"add_no_auto_dynamic_attr","items":[{"kind":"(Cclass Concrete)","sid":"\\D"},{"kind":"Cinterface","sid":"\\I"}]}
