File "redeclare_to_const.php", line 5, characters 7-7:
Class D does not correctly implement all required members  (Typing[4204])
File "redeclare_to_const.php", line 5, characters 17-17:
Some members are incompatible with those declared in type C
Read the following to see why:
File "redeclare_to_const.php", line 4, characters 28-30:
This property is not __Const
File "redeclare_to_const.php", line 5, characters 47-49:
This property is __Const
