// @generated by hh_manual from manual/hack/05-functions/02-anonymous-functions.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
async function example_snippet_wrapper(): Awaitable<void> {
  $f = function($x) { return $x + 1; };
}
