// @generated by hh_manual from manual/hack/05-functions/25-named-parameters.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
<<file: __EnableUnstableFeatures('named_parameters')>>

function schedule_retry(
    string $job,
    named int $delay_ms = 1000,
    named int $max_attempts = 3,
): void {
    // ...
}
