File "shape_idx_nullable_optional_field_with_nullable_default_return.php", line 8, characters 22-23:
Invalid argument (Typing[4110])
  File "shape_idx_nullable_optional_field_with_nullable_default_return.php", line 7, characters 4-6:
  Expected `int`
  File "shape_idx_nullable_optional_field_with_nullable_default_return.php", line 5, characters 17-20:
  But got `null`
File "shape_idx_nullable_optional_field_with_nullable_default_return.php", line 8, characters 31-38:
Invalid argument (Typing[4110])
  File "shape_idx_nullable_optional_field_with_nullable_default_return.php", line 7, characters 4-6:
  Expected `int`
  File "shape_idx_nullable_optional_field_with_nullable_default_return.php", line 6, characters 3-6:
  But got `null`
