Code actions available:
------------------------------------------
Flip around comma (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"\"b\" => true, \"a\" => true",
          "range":{"end":{"character":60,"line":3},"start":{"character":9,"line":3}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Flip around comma"
}

Applied edit for code action:
------------------------------------------
<?hh

function foo(): void {
    dict["b" => true, "a" => true];
}

