Code actions available:
------------------------------------------
Flip around comma (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"int $b, Box<int> $a",
          "range":{"end":{"character":69,"line":7},"start":{"character":22,"line":7}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Flip around comma"
}

Applied edit for code action:
------------------------------------------
<?hh

class Box<T> {
  public function __construct(public T $val){}
}

class Klass {
  public function foo(int $b, Box<int> $a): void {}
}

