ERROR: File "explicit_ro_cast.php", line 23, characters 9-24:
This function call returns a readonly value. It must be explicitly wrapped in a readonly expression. (Typing[4412])
  File "explicit_ro_cast.php", line 16, characters 10-25:
  The function call is defined here.
ERROR: File "explicit_ro_cast.php", line 24, characters 9-30:
Typing error (Typing[4411])
  File "explicit_ro_cast.php", line 7, characters 28-43:
  Function readonly return mismatch
  File "explicit_ro_cast.php", line 7, characters 28-43:
  This function returns a readonly value
  File "explicit_ro_cast.php", line 24, characters 9-30:
  This function does not return a readonly value
