((script 58
  ((list 58
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (function_declaration 42
      ((missing 0 ())
       (function_declaration_header 40
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 1 ()) (missing 0 ()) (() "(" 1 ())
         (list 22
          ((list_item 22
            ((parameter_declaration 22
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (simple_type_specifier 4 ((() bool 4 ((whitespace 1)))))
               (() variable 2 ((whitespace 1)))
               (simple_initializer 14
                ((() = 1 ((whitespace 1)))
                 (prefix_unary_expression 12
                  ((() await 5 ((whitespace 1)))
                   (function_call_expression 6
                    ((() name 4 ()) (missing 0 ()) (() "(" 1 ())
                     (missing 0 ()) (() ")" 1 ())))))))))
             (missing 0 ())))))
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ()))) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
