((script 110
  ((list 110
    ((markup_section 5
      ((() markup 0 ())
       (markup_suffix 5 ((() <? 2 ()) (() name 3 ((end_of_line 1)))))))
     (classish_declaration 64
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 56
        ((() { 1 ((end_of_line 1)))
         (list 50
          ((methodish_declaration 50
            ((missing 0 ())
             (function_declaration_header 26
              ((list 13
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() static 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (compound_statement 23
              ((() { 1 ((end_of_line 1)))
               (list 13
                ((return_statement 13
                  ((((whitespace 4)) return 6 ((whitespace 1)))
                   (literal 5 ((() double_quoted_string_literal 5 ())))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (function_declaration 37
      ((missing 0 ())
       (function_declaration_header 35
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 2 ()) (missing 0 ()) (() "(" 1 ())
         (list 16
          ((list_item 16
            ((parameter_declaration 16
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
               (() variable 2 ((whitespace 1)))
               (simple_initializer 13
                ((() = 1 ((whitespace 1)))
                 (vector_intrinsic_expression 11
                  ((() vec 3 ()) (missing 0 ()) (() [ 1 ())
                   (list 6
                    ((list_item 6
                      ((function_call_expression 6
                        ((scope_resolution_expression 4
                          ((() name 1 ()) (() :: 2 ()) (() name 1 ())))
                         (missing 0 ()) (() "(" 1 ()) (missing 0 ())
                         (() ")" 1 ())))
                       (missing 0 ())))))
                   (() ] 1 ())))))))
             (missing 0 ())))))
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ()))) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
