((script 229
  ((list 229
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (classish_declaration 156
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((single_line_comment 56) (end_of_line 1) (end_of_line 1)) class 5
        ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 148
        ((() { 1 ((end_of_line 1)))
         (list 142
          ((const_declaration 25
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 11
              ((list_item 11
                ((constant_declarator 11
                  ((() name 1 ((whitespace 1)))
                   (simple_initializer 9
                    ((() = 1 ((whitespace 1)))
                     (literal 7 ((() double_quoted_string_literal 7 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (property_declaration 29
            ((missing 0 ())
             (list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 14
              ((list_item 14
                ((property_declarator 14
                  ((() variable 2 ((whitespace 1)))
                   (simple_initializer 11
                    ((() = 1 ((whitespace 1)))
                     (literal 9
                      ((list 9
                        ((() double_quoted_string_literal_head 1 ())
                         (() $ 1 ())
                         (embedded_braced_expression 6
                          ((() { 1 ())
                           (scope_resolution_expression 4
                            ((() name 1 ()) (() :: 2 ()) (() name 1 ())))
                           (() } 1 ())))
                         (() double_quoted_string_literal_tail 1 ())))))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 28
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 14
              ((list_item 14
                ((constant_declarator 14
                  ((() name 2 ((whitespace 1)))
                   (simple_initializer 11
                    ((() = 1 ((whitespace 1)))
                     (literal 9
                      ((list 9
                        ((() double_quoted_string_literal_head 1 ())
                         (() $ 1 ())
                         (embedded_braced_expression 6
                          ((() { 1 ())
                           (scope_resolution_expression 4
                            ((() name 1 ()) (() :: 2 ()) (() name 1 ())))
                           (() } 1 ())))
                         (() double_quoted_string_literal_tail 1 ())))))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (methodish_declaration 50
            ((missing 0 ())
             (function_declaration_header 48
              ((list 6
                ((((end_of_line 1) (whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 3 ()) (missing 0 ())
               (() "(" 1 ())
               (list 21
                ((list_item 21
                  ((parameter_declaration 21
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (simple_type_specifier 6
                      ((() string 6 ((whitespace 1)))))
                     (() variable 2 ((whitespace 1)))
                     (simple_initializer 11
                      ((() = 1 ((whitespace 1)))
                       (literal 9
                        ((list 9
                          ((() double_quoted_string_literal_head 1 ())
                           (() $ 1 ())
                           (embedded_braced_expression 6
                            ((() { 1 ())
                             (scope_resolution_expression 4
                              ((() name 1 ()) (() :: 2 ()) (() name 1 ())))
                             (() } 1 ())))
                           (() double_quoted_string_literal_tail 1 ())))))))))
                   (missing 0 ())))))
               (() ")" 1 ()) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ()))) (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
