\*\*\*\ Testing\ open\_basedir\ configuration\ \[readlink\]\ \*\*\*\
bool\(true\)\
bool\(true\)\
bool\(true\)\
bool\(true\)\
bool\(true\)\
HipHop Warning: .+
bool\(false\)\
HipHop Warning: .+
bool\(false\)\
HipHop Warning: .+
bool\(false\)\
HipHop Warning: .+
bool\(false\)\
HipHop Warning: .+
bool\(false\)\
HipHop Warning: .+
bool\(false\)\
HipHop Warning: .+
bool\(false\)\
\*\*\*\ Finished\ testing\ open\_basedir\ configuration\ \[readlink\]\ \*\*\*