# closure.good.php starts here

.filepath "closure.good.php";

.adata A_0 = """Y:2:{s:4:\"kind\";i:21;s:13:\"generic_types\";y:1:{Y:1:{s:4:\"kind\";i:4;}}}""";
.adata A_1 = """k:0:{}""";

.main (1,1) {
  .srcloc 4:7,4:7;
  DefCls 0
  Int 1
  RetC
}

.class {} C (4,13) {
  .method {}{(TE as <"HH\\mixed" N upper_bound>)} [public static] (10,12) <"HH\\void" N > derive(<"TE" "TE" extended_hint type_var> $field) {
    .declvars $_;
    .srcloc 10:17,12:116;
    VerifyParamType $field
    .srcloc 11:10,11:41;
    NullUninit
    NullUninit
    NullUninit
    .srcloc 11:35,11:40;
    CGetL $field
    .srcloc 11:10,11:41;
    FCallClsMethodSD <> 1 1 "0" - "" "" Static "pu$Entry$generator"
    .srcloc 11:5,11:41;
    SetL $_
    .srcloc 11:5,11:42;
    PopC
    .srcloc 12:4,12:4;
    Null
    RetC
  }
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (5,5) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$Entry$Members$memoize_impl() {
    .srcloc 5:8,5:12;
    Keyset @A_1
    .srcloc 5:8,5:12;
    Array @A_0
    VerifyRetTypeTS
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (5,5) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$Entry$Members() {
    .ismemoizewrapper;
    .srcloc 5:8,5:12;
    MemoGet L0 L:0+0
    RetC
  L0:
    NullUninit
    NullUninit
    NullUninit
    FCallClsMethodD <> 0 1 "" - "" "" "C" "pu$Entry$Members$memoize_impl"
    MemoSet L:0+0
    RetC
  }
}

# closure.good.php ends here
