# members.good.php starts here

.filepath "members.good.php";

.adata A_0 = """Y:2:{s:4:\"kind\";i:20;s:13:\"generic_types\";y:1:{Y:1:{s:4:\"kind\";i:9;}}}""";
.adata A_1 = """Y:2:{s:4:\"kind\";i:21;s:13:\"generic_types\";y:1:{Y:1:{s:4:\"kind\";i:4;}}}""";
.adata A_2 = """k:4:{s:2:\"A0\";s:2:\"A1\";s:2:\"A2\";s:2:\"A3\";}""";

.function {} (25,30) <"HH\\void" N > foo(<"HH\\vec<HH\\mixed>" "HH\\vec" > $v) {
  .numiters 1;
  .declvars $x;
  .srcloc 25:1,30:102;
  Array @A_0
  VerifyParamTypeTS $v
  .srcloc 26:12,26:13;
  CGetL $v
  .srcloc 26:12,26:13;
  IterInit 0 NK V:$x L0
  .try {
  L1:
    .srcloc 27:10,27:22;
    NullUninit
    NullUninit
    .srcloc 27:20,27:21;
    CGetL $x
    .srcloc 27:10,27:22;
    FCallClsMethodD <> 1 1 "0" - "" "" "C" "pu$E$val"
    .srcloc 27:5,27:23;
    Print
    .srcloc 27:5,27:23;
    PopC
    .srcloc 28:10,28:13;
    String "\n"
    .srcloc 28:5,28:14;
    Print
    .srcloc 28:5,28:14;
    PopC
    .srcloc 26:3,29:65;
    IterNext 0 NK V:$x L1
    Jmp L0
  } .catch {
    IterFree 0
    Throw
  }
L0:
  .srcloc 30:2,30:2;
  Null
  RetC
}

.function {} ["__EntryPoint"("""y:0:{}""")] (33,36) <"HH\\void" N > main() {
  .declvars $v;
  .srcloc 34:8,34:22;
  NullUninit
  NullUninit
  .srcloc 34:8,34:22;
  FCallClsMethodD <> 0 1 "" - "" "" "C" "pu$E$Members"
  .srcloc 34:3,34:22;
  SetL $v
  .srcloc 34:3,34:23;
  PopC
  .srcloc 35:3,35:9;
  NullUninit
  NullUninit
  .srcloc 35:7,35:8;
  CGetL $v
  .srcloc 35:3,35:9;
  FCallFuncD <> 1 1 "0" - "" "foo"
  .srcloc 35:3,35:9;
  PopC
  .srcloc 36:2,36:2;
  Null
  RetC
}

.class {} C (7,23) {
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members$memoize_impl() {
    .srcloc 8:8,8:8;
    Keyset @A_2
    .srcloc 8:8,8:8;
    Array @A_1
    VerifyRetTypeTS
    RetC
  }
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\mixed" N > pu$E$val$memoize_impl(<"HH\\string" "HH\\string" > $atom) {
    .srcloc 8:8,8:8;
    VerifyParamType $atom
    .srcloc 8:8,8:8;
    String "A0"
    .srcloc 8:8,8:8;
    CGetL2 $atom
    Eq
    JmpNZ L0
    .srcloc 8:8,8:8;
    String "A1"
    .srcloc 8:8,8:8;
    CGetL2 $atom
    Eq
    JmpNZ L1
    .srcloc 8:8,8:8;
    String "A2"
    .srcloc 8:8,8:8;
    CGetL2 $atom
    Eq
    JmpNZ L2
    .srcloc 8:8,8:8;
    String "A3"
    .srcloc 8:8,8:8;
    CGetL2 $atom
    Eq
    JmpNZ L3
    Jmp L4
  L0:
    .srcloc 11:13,11:14;
    Int 42
    .srcloc 8:8,8:8;
    RetC
  L1:
    .srcloc 14:13,14:14;
    Int 43
    .srcloc 8:8,8:8;
    RetC
  L2:
    .srcloc 17:13,17:14;
    Int 44
    .srcloc 8:8,8:8;
    RetC
  L3:
    .srcloc 20:13,20:14;
    Int 45
    .srcloc 8:8,8:8;
    RetC
  L4:
    .srcloc 8:8,8:8;
    NewObjD "Exception"
    Dup
    NullUninit
    .srcloc 8:8,8:8;
    String "\\C:@E::val unknown atom access: "
    .srcloc 8:8,8:8;
    CGetL $atom
    Concat
    .srcloc 8:8,8:8;
    FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
    PopC
    LockObj
    .srcloc 8:8,8:8;
    Throw
    .srcloc 8:9,8:9;
    Null
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members() {
    .ismemoizewrapper;
    .srcloc 8:8,8:8;
    MemoGet L0 L:0+0
    RetC
  L0:
    NullUninit
    NullUninit
    FCallClsMethodD <> 0 1 "" - "" "" "C" "pu$E$Members$memoize_impl"
    MemoSet L:0+0
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\mixed" N > pu$E$val(<"HH\\string" "HH\\string" > $atom) {
    .ismemoizewrapper;
    .srcloc 8:8,8:8;
    VerifyParamType $atom
    GetMemoKeyL $atom
    SetL _1
    PopC
    MemoGet L0 L:1+1
    RetC
  L0:
    NullUninit
    NullUninit
    CGetL $atom
    FCallClsMethodD <> 1 1 "" - "" "" "C" "pu$E$val$memoize_impl"
    MemoSet L:1+1
    RetC
  }
}

.file_attributes ["__EnableUnstableFeatures"("""y:1:{s:16:\"pocket_universes\";}""")] ;

# members.good.php ends here
