# trait_uses_trait.good.php starts here

.filepath "trait_uses_trait.good.php";

.adata A_0 = """Y:2:{s:4:\"kind\";i:21;s:13:\"generic_types\";y:1:{Y:1:{s:4:\"kind\";i:4;}}}""";
.adata A_1 = """k:1:{s:1:\"X\";}""";
.adata A_2 = """k:1:{s:1:\"J\";}""";
.adata A_3 = """v:1:{s:8:\"MyTraitB\";}""";
.adata A_4 = """k:1:{s:1:\"K\";}""";
.adata A_5 = """v:1:{s:8:\"MyTraitA\";}""";

.function {} ["__EntryPoint"("""y:0:{}""")] (43,47) <"HH\\void" N > main() {
  .srcloc 44:8,44:23;
  NullUninit
  NullUninit
  .srcloc 44:20,44:22;
  String "K"
  .srcloc 44:8,44:23;
  FCallClsMethodD <> 1 1 "0" - "" "" "C" "pu$E$value"
  .srcloc 44:25,44:28;
  String "\n"
  .srcloc 44:8,44:28;
  Concat
  .srcloc 44:3,44:29;
  Print
  .srcloc 44:3,44:29;
  PopC
  .srcloc 45:8,45:23;
  NullUninit
  NullUninit
  .srcloc 45:20,45:22;
  String "J"
  .srcloc 45:8,45:23;
  FCallClsMethodD <> 1 1 "0" - "" "" "C" "pu$E$value"
  .srcloc 45:25,45:28;
  String "\n"
  .srcloc 45:8,45:28;
  Concat
  .srcloc 45:3,45:29;
  Print
  .srcloc 45:3,45:29;
  PopC
  .srcloc 46:8,46:23;
  NullUninit
  NullUninit
  .srcloc 46:20,46:22;
  String "X"
  .srcloc 46:8,46:23;
  FCallClsMethodD <> 1 1 "0" - "" "" "C" "pu$E$value"
  .srcloc 46:25,46:28;
  String "\n"
  .srcloc 46:8,46:28;
  Concat
  .srcloc 46:3,46:29;
  Print
  .srcloc 46:3,46:29;
  PopC
  .srcloc 47:2,47:2;
  Null
  RetC
}

.class {} [final trait] MyTraitB (7,14) {
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members$memoize_impl() {
    .srcloc 8:8,8:8;
    Keyset @A_1
    .srcloc 8:8,8:8;
    Array @A_0
    VerifyRetTypeTS
    RetC
  }
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\mixed" N > pu$E$value$memoize_impl(<"HH\\string" "HH\\string" > $atom) {
    .srcloc 8:8,8:8;
    VerifyParamType $atom
    .srcloc 8:8,8:8;
    String "X"
    .srcloc 8:8,8:8;
    CGetL2 $atom
    Eq
    JmpNZ L0
    Jmp L1
  L0:
    .srcloc 11:15,11:16;
    Int 42
    .srcloc 8:8,8:8;
    RetC
  L1:
    .srcloc 8:8,8:8;
    NewObjD "Exception"
    Dup
    NullUninit
    .srcloc 8:8,8:8;
    String "\\MyTraitB:@E::value unknown atom access: "
    .srcloc 8:8,8:8;
    CGetL $atom
    Concat
    .srcloc 8:8,8:8;
    FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
    PopC
    LockObj
    .srcloc 8:8,8:8;
    Throw
    .srcloc 8:9,8:9;
    Null
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members() {
    .ismemoizewrapper;
    .srcloc 8:8,8:8;
    MemoGet L0 L:0+0
    RetC
  L0:
    NullUninit
    NullUninit
    FCallClsMethodSD <> 0 1 "" - "" "" Self "pu$E$Members$memoize_impl"
    MemoSet L:0+0
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\mixed" N > pu$E$value(<"HH\\string" "HH\\string" > $atom) {
    .ismemoizewrapper;
    .srcloc 8:8,8:8;
    VerifyParamType $atom
    GetMemoKeyL $atom
    SetL _1
    PopC
    MemoGet L0 L:1+1
    RetC
  L0:
    NullUninit
    NullUninit
    CGetL $atom
    FCallClsMethodSD <> 1 1 "" - "" "" Self "pu$E$value$memoize_impl"
    MemoSet L:1+1
    RetC
  }
}

.class {} [final trait] MyTraitA (16,25) {
  .use MyTraitB;
  .method {}{} [private static "__Memoize"("""y:0:{}""") "__Override"("""y:0:{}""")] (19,19) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members$memoize_impl() {
    .numiters 2;
    .declvars $result $traits_classes $traits_class $class $method $parent_members $p $_;
    .srcloc 19:8,19:8;
    Keyset @A_2
    .srcloc 19:8,19:8;
    SetL $result
    .srcloc 19:8,19:8;
    PopC
    .srcloc 19:8,19:8;
    Vec @A_3
    .srcloc 19:8,19:8;
    SetL $traits_classes
    .srcloc 19:8,19:8;
    PopC
    .srcloc 19:8,19:8;
    CGetL $traits_classes
    .srcloc 19:8,19:8;
    IterInit 0 NK V:$traits_class L0
    .try {
    L5:
      .try {
        .srcloc 19:8,19:8;
        NewObjD "ReflectionClass"
        Dup
        NullUninit
        .srcloc 19:8,19:8;
        CGetL $traits_class
        .srcloc 19:8,19:8;
        FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
        PopC
        LockObj
        .srcloc 19:8,19:8;
        SetL $class
        .srcloc 19:8,19:8;
        PopC
        .srcloc 19:8,19:8;
        CGetL $class
        NullUninit
        .srcloc 19:8,19:8;
        String "pu$E$Members"
        .srcloc 19:8,19:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "getMethod"
        .srcloc 19:8,19:8;
        SetL $method
        .srcloc 19:8,19:8;
        PopC
        .srcloc 19:8,19:8;
        CGetL $method
        NullUninit
        .srcloc 19:8,19:8;
        Null
        .srcloc 19:8,19:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "invoke"
        .srcloc 19:8,19:8;
        SetL $parent_members
        .srcloc 19:8,19:8;
        PopC
        .srcloc 19:8,19:8;
        CGetL $parent_members
        .srcloc 19:8,19:8;
        IterInit 1 NK V:$p L1
        .try {
        L2:
          .srcloc 19:8,19:8;
          CGetL $p
          .srcloc 19:8,19:8;
          BaseL $result Define
          .srcloc 19:8,19:8;
          SetM 0 W
          .srcloc 19:8,19:8;
          PopC
          .srcloc 19:8,19:8;
          IterNext 1 NK V:$p L2
          Jmp L1
        } .catch {
          IterFree 1
          Throw
        }
      L1:
        .srcloc 19:8,19:8;
        Jmp L3
      } .catch {
        Dup
        InstanceOfD "ReflectionException"
        JmpZ L4
        SetL $_
        PopC
        .srcloc 19:8,19:8;
        Jmp L3
      L4:
        Throw
      }
    L3:
      .srcloc 19:8,19:8;
      IterNext 0 NK V:$traits_class L5
      Jmp L0
    } .catch {
      IterFree 0
      Throw
    }
  L0:
    .srcloc 19:8,19:8;
    CGetL $result
    .srcloc 19:8,19:8;
    Array @A_0
    VerifyRetTypeTS
    RetC
  }
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (19,19) <"HH\\mixed" N > pu$E$value$memoize_impl(<"HH\\string" "HH\\string" > $atom) {
    .numiters 1;
    .declvars $trait_classes $trait_class $class $method $_;
    .srcloc 19:8,19:8;
    VerifyParamType $atom
    .srcloc 19:8,19:8;
    String "J"
    .srcloc 19:8,19:8;
    CGetL2 $atom
    Eq
    JmpNZ L0
    Jmp L1
  L0:
    .srcloc 22:15,22:18;
    Int 1664
    .srcloc 19:8,19:8;
    RetC
  L1:
    .srcloc 19:8,19:8;
    Vec @A_3
    .srcloc 19:8,19:8;
    SetL $trait_classes
    .srcloc 19:8,19:8;
    PopC
    .srcloc 19:8,19:8;
    CGetL $trait_classes
    .srcloc 19:8,19:8;
    IterInit 0 NK V:$trait_class L2
    .try {
    L5:
      .try {
        .srcloc 19:8,19:8;
        NewObjD "ReflectionClass"
        Dup
        NullUninit
        .srcloc 19:8,19:8;
        CGetL $trait_class
        .srcloc 19:8,19:8;
        FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
        PopC
        LockObj
        .srcloc 19:8,19:8;
        SetL $class
        .srcloc 19:8,19:8;
        PopC
        .srcloc 19:8,19:8;
        CGetL $class
        NullUninit
        .srcloc 19:8,19:8;
        String "pu$E$value"
        .srcloc 19:8,19:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "getMethod"
        .srcloc 19:8,19:8;
        SetL $method
        .srcloc 19:8,19:8;
        PopC
        .srcloc 19:8,19:8;
        CGetL $method
        NullUninit
        .srcloc 19:8,19:8;
        Null
        .srcloc 19:8,19:8;
        CGetL $atom
        .srcloc 19:8,19:8;
        FCallObjMethodD <> 2 1 "00" - "" "" NullThrows "invoke"
        .srcloc 19:8,19:8;
        IterFree 0
        RetC
        .srcloc 19:8,19:8;
        Jmp L3
      } .catch {
        Dup
        InstanceOfD "Exception"
        JmpZ L4
        SetL $_
        PopC
        .srcloc 19:8,19:8;
        Jmp L3
      L4:
        Throw
      }
    L3:
      .srcloc 19:8,19:8;
      IterNext 0 NK V:$trait_class L5
      Jmp L2
    } .catch {
      IterFree 0
      Throw
    }
  L2:
    .srcloc 19:8,19:8;
    NewObjD "Exception"
    Dup
    NullUninit
    .srcloc 19:8,19:8;
    String "\\MyTraitA:@E::value unknown atom access: "
    .srcloc 19:8,19:8;
    CGetL $atom
    Concat
    .srcloc 19:8,19:8;
    FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
    PopC
    LockObj
    .srcloc 19:8,19:8;
    Throw
    .srcloc 19:9,19:9;
    Null
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""") "__Override"("""y:0:{}""")] (19,19) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members() {
    .ismemoizewrapper;
    .srcloc 19:8,19:8;
    MemoGet L0 L:0+0
    RetC
  L0:
    NullUninit
    NullUninit
    FCallClsMethodSD <> 0 1 "" - "" "" Self "pu$E$Members$memoize_impl"
    MemoSet L:0+0
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (19,19) <"HH\\mixed" N > pu$E$value(<"HH\\string" "HH\\string" > $atom) {
    .ismemoizewrapper;
    .srcloc 19:8,19:8;
    VerifyParamType $atom
    GetMemoKeyL $atom
    SetL _1
    PopC
    MemoGet L0 L:1+1
    RetC
  L0:
    NullUninit
    NullUninit
    CGetL $atom
    FCallClsMethodSD <> 1 1 "" - "" "" Self "pu$E$value$memoize_impl"
    MemoSet L:1+1
    RetC
  }
}

.class {} C (27,38) {
  .use MyTraitA;
  .method {}{} [private static "__Memoize"("""y:0:{}""") "__Override"("""y:0:{}""")] (30,30) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members$memoize_impl() {
    .numiters 2;
    .declvars $result $traits_classes $traits_class $class $method $parent_members $p $_;
    .srcloc 30:8,30:8;
    Keyset @A_4
    .srcloc 30:8,30:8;
    SetL $result
    .srcloc 30:8,30:8;
    PopC
    .srcloc 30:8,30:8;
    Vec @A_5
    .srcloc 30:8,30:8;
    SetL $traits_classes
    .srcloc 30:8,30:8;
    PopC
    .srcloc 30:8,30:8;
    CGetL $traits_classes
    .srcloc 30:8,30:8;
    IterInit 0 NK V:$traits_class L0
    .try {
    L5:
      .try {
        .srcloc 30:8,30:8;
        NewObjD "ReflectionClass"
        Dup
        NullUninit
        .srcloc 30:8,30:8;
        CGetL $traits_class
        .srcloc 30:8,30:8;
        FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
        PopC
        LockObj
        .srcloc 30:8,30:8;
        SetL $class
        .srcloc 30:8,30:8;
        PopC
        .srcloc 30:8,30:8;
        CGetL $class
        NullUninit
        .srcloc 30:8,30:8;
        String "pu$E$Members"
        .srcloc 30:8,30:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "getMethod"
        .srcloc 30:8,30:8;
        SetL $method
        .srcloc 30:8,30:8;
        PopC
        .srcloc 30:8,30:8;
        CGetL $method
        NullUninit
        .srcloc 30:8,30:8;
        Null
        .srcloc 30:8,30:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "invoke"
        .srcloc 30:8,30:8;
        SetL $parent_members
        .srcloc 30:8,30:8;
        PopC
        .srcloc 30:8,30:8;
        CGetL $parent_members
        .srcloc 30:8,30:8;
        IterInit 1 NK V:$p L1
        .try {
        L2:
          .srcloc 30:8,30:8;
          CGetL $p
          .srcloc 30:8,30:8;
          BaseL $result Define
          .srcloc 30:8,30:8;
          SetM 0 W
          .srcloc 30:8,30:8;
          PopC
          .srcloc 30:8,30:8;
          IterNext 1 NK V:$p L2
          Jmp L1
        } .catch {
          IterFree 1
          Throw
        }
      L1:
        .srcloc 30:8,30:8;
        Jmp L3
      } .catch {
        Dup
        InstanceOfD "ReflectionException"
        JmpZ L4
        SetL $_
        PopC
        .srcloc 30:8,30:8;
        Jmp L3
      L4:
        Throw
      }
    L3:
      .srcloc 30:8,30:8;
      IterNext 0 NK V:$traits_class L5
      Jmp L0
    } .catch {
      IterFree 0
      Throw
    }
  L0:
    .srcloc 30:8,30:8;
    CGetL $result
    .srcloc 30:8,30:8;
    Array @A_0
    VerifyRetTypeTS
    RetC
  }
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (30,30) <"HH\\mixed" N > pu$E$value$memoize_impl(<"HH\\string" "HH\\string" > $atom) {
    .numiters 1;
    .declvars $trait_classes $trait_class $class $method $_;
    .srcloc 30:8,30:8;
    VerifyParamType $atom
    .srcloc 30:8,30:8;
    String "K"
    .srcloc 30:8,30:8;
    CGetL2 $atom
    Eq
    JmpNZ L0
    Jmp L1
  L0:
    .srcloc 35:15,35:18;
    String "yo"
    .srcloc 30:8,30:8;
    RetC
  L1:
    .srcloc 30:8,30:8;
    Vec @A_5
    .srcloc 30:8,30:8;
    SetL $trait_classes
    .srcloc 30:8,30:8;
    PopC
    .srcloc 30:8,30:8;
    CGetL $trait_classes
    .srcloc 30:8,30:8;
    IterInit 0 NK V:$trait_class L2
    .try {
    L5:
      .try {
        .srcloc 30:8,30:8;
        NewObjD "ReflectionClass"
        Dup
        NullUninit
        .srcloc 30:8,30:8;
        CGetL $trait_class
        .srcloc 30:8,30:8;
        FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
        PopC
        LockObj
        .srcloc 30:8,30:8;
        SetL $class
        .srcloc 30:8,30:8;
        PopC
        .srcloc 30:8,30:8;
        CGetL $class
        NullUninit
        .srcloc 30:8,30:8;
        String "pu$E$value"
        .srcloc 30:8,30:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "getMethod"
        .srcloc 30:8,30:8;
        SetL $method
        .srcloc 30:8,30:8;
        PopC
        .srcloc 30:8,30:8;
        CGetL $method
        NullUninit
        .srcloc 30:8,30:8;
        Null
        .srcloc 30:8,30:8;
        CGetL $atom
        .srcloc 30:8,30:8;
        FCallObjMethodD <> 2 1 "00" - "" "" NullThrows "invoke"
        .srcloc 30:8,30:8;
        IterFree 0
        RetC
        .srcloc 30:8,30:8;
        Jmp L3
      } .catch {
        Dup
        InstanceOfD "Exception"
        JmpZ L4
        SetL $_
        PopC
        .srcloc 30:8,30:8;
        Jmp L3
      L4:
        Throw
      }
    L3:
      .srcloc 30:8,30:8;
      IterNext 0 NK V:$trait_class L5
      Jmp L2
    } .catch {
      IterFree 0
      Throw
    }
  L2:
    .srcloc 30:8,30:8;
    NewObjD "Exception"
    Dup
    NullUninit
    .srcloc 30:8,30:8;
    String "\\C:@E::value unknown atom access: "
    .srcloc 30:8,30:8;
    CGetL $atom
    Concat
    .srcloc 30:8,30:8;
    FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
    PopC
    LockObj
    .srcloc 30:8,30:8;
    Throw
    .srcloc 30:9,30:9;
    Null
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""") "__Override"("""y:0:{}""")] (30,30) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members() {
    .ismemoizewrapper;
    .srcloc 30:8,30:8;
    MemoGet L0 L:0+0
    RetC
  L0:
    NullUninit
    NullUninit
    FCallClsMethodD <> 0 1 "" - "" "" "C" "pu$E$Members$memoize_impl"
    MemoSet L:0+0
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (30,30) <"HH\\mixed" N > pu$E$value(<"HH\\string" "HH\\string" > $atom) {
    .ismemoizewrapper;
    .srcloc 30:8,30:8;
    VerifyParamType $atom
    GetMemoKeyL $atom
    SetL _1
    PopC
    MemoGet L0 L:1+1
    RetC
  L0:
    NullUninit
    NullUninit
    CGetL $atom
    FCallClsMethodD <> 1 1 "" - "" "" "C" "pu$E$value$memoize_impl"
    MemoSet L:1+1
    RetC
  }
}

.class {} D (40,40) extends C {
}

.file_attributes ["__EnableUnstableFeatures"("""y:1:{s:16:\"pocket_universes\";}""")] ;

# trait_uses_trait.good.php ends here
