# trait_members.good.php starts here

.filepath "trait_members.good.php";

.adata A_0 = """Y:2:{s:4:\"kind\";i:21;s:13:\"generic_types\";y:1:{Y:1:{s:4:\"kind\";i:4;}}}""";
.adata A_1 = """k:1:{s:1:\"J\";}""";
.adata A_2 = """k:1:{s:1:\"X\";}""";
.adata A_3 = """k:1:{s:1:\"K\";}""";
.adata A_4 = """v:2:{s:8:\"MyTraitA\";s:8:\"MyTraitB\";}""";

.function {} ["__EntryPoint"("""y:0:{}""")] (40,44) <"HH\\void" N > main() {
  .numiters 1;
  .declvars $member;
  .srcloc 41:12,41:26;
  NullUninit
  NullUninit
  .srcloc 41:12,41:26;
  FCallClsMethodD <> 0 1 "" - "" "" "C" "pu$E$Members"
  .srcloc 41:12,41:26;
  IterInit 0 NK V:$member L0
  .try {
  L1:
    .srcloc 42:18,42:21;
    String ": "
    .srcloc 42:10,42:21;
    CGetL2 $member
    Concat
    .srcloc 42:24,42:43;
    NullUninit
    NullUninit
    .srcloc 42:36,42:42;
    CGetL $member
    .srcloc 42:24,42:43;
    FCallClsMethodD <> 1 1 "0" - "" "" "C" "pu$E$value"
    .srcloc 42:10,42:44;
    Concat
    .srcloc 42:46,42:49;
    String "\n"
    .srcloc 42:10,42:49;
    Concat
    .srcloc 42:5,42:50;
    Print
    .srcloc 42:5,42:50;
    PopC
    .srcloc 41:3,43:95;
    IterNext 0 NK V:$member L1
    Jmp L0
  } .catch {
    IterFree 0
    Throw
  }
L0:
  .srcloc 44:2,44:2;
  Null
  RetC
}

.class {} [final trait] MyTraitA (7,14) {
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members$memoize_impl() {
    .srcloc 8:8,8:8;
    Keyset @A_1
    .srcloc 8:8,8:8;
    Array @A_0
    VerifyRetTypeTS
    RetC
  }
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\mixed" N > pu$E$value$memoize_impl(<"HH\\string" "HH\\string" > $atom) {
    .srcloc 8:8,8:8;
    VerifyParamType $atom
    .srcloc 8:8,8:8;
    String "J"
    .srcloc 8:8,8:8;
    CGetL2 $atom
    Eq
    JmpNZ L0
    Jmp L1
  L0:
    .srcloc 11:15,11:18;
    Int 1664
    .srcloc 8:8,8:8;
    RetC
  L1:
    .srcloc 8:8,8:8;
    NewObjD "Exception"
    Dup
    NullUninit
    .srcloc 8:8,8:8;
    String "\\MyTraitA:@E::value unknown atom access: "
    .srcloc 8:8,8:8;
    CGetL $atom
    Concat
    .srcloc 8:8,8:8;
    FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
    PopC
    LockObj
    .srcloc 8:8,8:8;
    Throw
    .srcloc 8:9,8:9;
    Null
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members() {
    .ismemoizewrapper;
    .srcloc 8:8,8:8;
    MemoGet L0 L:0+0
    RetC
  L0:
    NullUninit
    NullUninit
    FCallClsMethodSD <> 0 1 "" - "" "" Self "pu$E$Members$memoize_impl"
    MemoSet L:0+0
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (8,8) <"HH\\mixed" N > pu$E$value(<"HH\\string" "HH\\string" > $atom) {
    .ismemoizewrapper;
    .srcloc 8:8,8:8;
    VerifyParamType $atom
    GetMemoKeyL $atom
    SetL _1
    PopC
    MemoGet L0 L:1+1
    RetC
  L0:
    NullUninit
    NullUninit
    CGetL $atom
    FCallClsMethodSD <> 1 1 "" - "" "" Self "pu$E$value$memoize_impl"
    MemoSet L:1+1
    RetC
  }
}

.class {} [final trait] MyTraitB (16,23) {
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (17,17) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members$memoize_impl() {
    .srcloc 17:8,17:8;
    Keyset @A_2
    .srcloc 17:8,17:8;
    Array @A_0
    VerifyRetTypeTS
    RetC
  }
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (17,17) <"HH\\mixed" N > pu$E$value$memoize_impl(<"HH\\string" "HH\\string" > $atom) {
    .srcloc 17:8,17:8;
    VerifyParamType $atom
    .srcloc 17:8,17:8;
    String "X"
    .srcloc 17:8,17:8;
    CGetL2 $atom
    Eq
    JmpNZ L0
    Jmp L1
  L0:
    .srcloc 20:15,20:16;
    Int 42
    .srcloc 17:8,17:8;
    RetC
  L1:
    .srcloc 17:8,17:8;
    NewObjD "Exception"
    Dup
    NullUninit
    .srcloc 17:8,17:8;
    String "\\MyTraitB:@E::value unknown atom access: "
    .srcloc 17:8,17:8;
    CGetL $atom
    Concat
    .srcloc 17:8,17:8;
    FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
    PopC
    LockObj
    .srcloc 17:8,17:8;
    Throw
    .srcloc 17:9,17:9;
    Null
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (17,17) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members() {
    .ismemoizewrapper;
    .srcloc 17:8,17:8;
    MemoGet L0 L:0+0
    RetC
  L0:
    NullUninit
    NullUninit
    FCallClsMethodSD <> 0 1 "" - "" "" Self "pu$E$Members$memoize_impl"
    MemoSet L:0+0
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (17,17) <"HH\\mixed" N > pu$E$value(<"HH\\string" "HH\\string" > $atom) {
    .ismemoizewrapper;
    .srcloc 17:8,17:8;
    VerifyParamType $atom
    GetMemoKeyL $atom
    SetL _1
    PopC
    MemoGet L0 L:1+1
    RetC
  L0:
    NullUninit
    NullUninit
    CGetL $atom
    FCallClsMethodSD <> 1 1 "" - "" "" Self "pu$E$value$memoize_impl"
    MemoSet L:1+1
    RetC
  }
}

.class {} C (25,37) {
  .use MyTraitA MyTraitB;
  .method {}{} [private static "__Memoize"("""y:0:{}""") "__Override"("""y:0:{}""")] (29,29) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members$memoize_impl() {
    .numiters 2;
    .declvars $result $traits_classes $traits_class $class $method $parent_members $p $_;
    .srcloc 29:8,29:8;
    Keyset @A_3
    .srcloc 29:8,29:8;
    SetL $result
    .srcloc 29:8,29:8;
    PopC
    .srcloc 29:8,29:8;
    Vec @A_4
    .srcloc 29:8,29:8;
    SetL $traits_classes
    .srcloc 29:8,29:8;
    PopC
    .srcloc 29:8,29:8;
    CGetL $traits_classes
    .srcloc 29:8,29:8;
    IterInit 0 NK V:$traits_class L0
    .try {
    L5:
      .try {
        .srcloc 29:8,29:8;
        NewObjD "ReflectionClass"
        Dup
        NullUninit
        .srcloc 29:8,29:8;
        CGetL $traits_class
        .srcloc 29:8,29:8;
        FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
        PopC
        LockObj
        .srcloc 29:8,29:8;
        SetL $class
        .srcloc 29:8,29:8;
        PopC
        .srcloc 29:8,29:8;
        CGetL $class
        NullUninit
        .srcloc 29:8,29:8;
        String "pu$E$Members"
        .srcloc 29:8,29:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "getMethod"
        .srcloc 29:8,29:8;
        SetL $method
        .srcloc 29:8,29:8;
        PopC
        .srcloc 29:8,29:8;
        CGetL $method
        NullUninit
        .srcloc 29:8,29:8;
        Null
        .srcloc 29:8,29:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "invoke"
        .srcloc 29:8,29:8;
        SetL $parent_members
        .srcloc 29:8,29:8;
        PopC
        .srcloc 29:8,29:8;
        CGetL $parent_members
        .srcloc 29:8,29:8;
        IterInit 1 NK V:$p L1
        .try {
        L2:
          .srcloc 29:8,29:8;
          CGetL $p
          .srcloc 29:8,29:8;
          BaseL $result Define
          .srcloc 29:8,29:8;
          SetM 0 W
          .srcloc 29:8,29:8;
          PopC
          .srcloc 29:8,29:8;
          IterNext 1 NK V:$p L2
          Jmp L1
        } .catch {
          IterFree 1
          Throw
        }
      L1:
        .srcloc 29:8,29:8;
        Jmp L3
      } .catch {
        Dup
        InstanceOfD "ReflectionException"
        JmpZ L4
        SetL $_
        PopC
        .srcloc 29:8,29:8;
        Jmp L3
      L4:
        Throw
      }
    L3:
      .srcloc 29:8,29:8;
      IterNext 0 NK V:$traits_class L5
      Jmp L0
    } .catch {
      IterFree 0
      Throw
    }
  L0:
    .srcloc 29:8,29:8;
    CGetL $result
    .srcloc 29:8,29:8;
    Array @A_0
    VerifyRetTypeTS
    RetC
  }
  .method {}{} [private static "__Memoize"("""y:0:{}""")] (29,29) <"HH\\mixed" N > pu$E$value$memoize_impl(<"HH\\string" "HH\\string" > $atom) {
    .numiters 1;
    .declvars $trait_classes $trait_class $class $method $_;
    .srcloc 29:8,29:8;
    VerifyParamType $atom
    .srcloc 29:8,29:8;
    String "K"
    .srcloc 29:8,29:8;
    CGetL2 $atom
    Eq
    JmpNZ L0
    Jmp L1
  L0:
    .srcloc 34:15,34:18;
    String "yo"
    .srcloc 29:8,29:8;
    RetC
  L1:
    .srcloc 29:8,29:8;
    Vec @A_4
    .srcloc 29:8,29:8;
    SetL $trait_classes
    .srcloc 29:8,29:8;
    PopC
    .srcloc 29:8,29:8;
    CGetL $trait_classes
    .srcloc 29:8,29:8;
    IterInit 0 NK V:$trait_class L2
    .try {
    L5:
      .try {
        .srcloc 29:8,29:8;
        NewObjD "ReflectionClass"
        Dup
        NullUninit
        .srcloc 29:8,29:8;
        CGetL $trait_class
        .srcloc 29:8,29:8;
        FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
        PopC
        LockObj
        .srcloc 29:8,29:8;
        SetL $class
        .srcloc 29:8,29:8;
        PopC
        .srcloc 29:8,29:8;
        CGetL $class
        NullUninit
        .srcloc 29:8,29:8;
        String "pu$E$value"
        .srcloc 29:8,29:8;
        FCallObjMethodD <> 1 1 "0" - "" "" NullThrows "getMethod"
        .srcloc 29:8,29:8;
        SetL $method
        .srcloc 29:8,29:8;
        PopC
        .srcloc 29:8,29:8;
        CGetL $method
        NullUninit
        .srcloc 29:8,29:8;
        Null
        .srcloc 29:8,29:8;
        CGetL $atom
        .srcloc 29:8,29:8;
        FCallObjMethodD <> 2 1 "00" - "" "" NullThrows "invoke"
        .srcloc 29:8,29:8;
        IterFree 0
        RetC
        .srcloc 29:8,29:8;
        Jmp L3
      } .catch {
        Dup
        InstanceOfD "Exception"
        JmpZ L4
        SetL $_
        PopC
        .srcloc 29:8,29:8;
        Jmp L3
      L4:
        Throw
      }
    L3:
      .srcloc 29:8,29:8;
      IterNext 0 NK V:$trait_class L5
      Jmp L2
    } .catch {
      IterFree 0
      Throw
    }
  L2:
    .srcloc 29:8,29:8;
    NewObjD "Exception"
    Dup
    NullUninit
    .srcloc 29:8,29:8;
    String "\\C:@E::value unknown atom access: "
    .srcloc 29:8,29:8;
    CGetL $atom
    Concat
    .srcloc 29:8,29:8;
    FCallCtor <LockWhileUnwinding> 1 1 "0" - "" ""
    PopC
    LockObj
    .srcloc 29:8,29:8;
    Throw
    .srcloc 29:9,29:9;
    Null
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""") "__Override"("""y:0:{}""")] (29,29) <"HH\\keyset<HH\\string>" "HH\\keyset" extended_hint> pu$E$Members() {
    .ismemoizewrapper;
    .srcloc 29:8,29:8;
    MemoGet L0 L:0+0
    RetC
  L0:
    NullUninit
    NullUninit
    FCallClsMethodD <> 0 1 "" - "" "" "C" "pu$E$Members$memoize_impl"
    MemoSet L:0+0
    RetC
  }
  .method {}{} [public static "__Memoize"("""y:0:{}""")] (29,29) <"HH\\mixed" N > pu$E$value(<"HH\\string" "HH\\string" > $atom) {
    .ismemoizewrapper;
    .srcloc 29:8,29:8;
    VerifyParamType $atom
    GetMemoKeyL $atom
    SetL _1
    PopC
    MemoGet L0 L:1+1
    RetC
  L0:
    NullUninit
    NullUninit
    CGetL $atom
    FCallClsMethodD <> 1 1 "" - "" "" "C" "pu$E$value$memoize_impl"
    MemoSet L:1+1
    RetC
  }
}

.file_attributes ["__EnableUnstableFeatures"("""y:1:{s:16:\"pocket_universes\";}""")] ;

# trait_members.good.php ends here
