=== Shape analysis results for bop.php
Summary for \test_amp:
[78:19-36] [Parameter]:
  shape('a' => int, 'b' => int)
[80:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_ampamp:
[43:22-40] [Parameter]:
  shape('a' => bool, 'b' => bool)
[45:13-15] [Debug]:
  shape('a' => bool, 'b' => bool)
Summary for \test_bar:
[83:19-36] [Parameter]:
  shape('a' => int, 'b' => int)
[85:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_barbar:
[48:22-40] [Parameter]:
  shape('a' => bool, 'b' => bool)
[50:13-15] [Debug]:
  shape('a' => bool, 'b' => bool)
Summary for \test_cmp:
[108:19-36] [Parameter]:
  shape('a' => int, 'b' => int)
[110:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_diff:
[38:20-37] [Parameter]:
  shape('a' => int, 'b' => int)
[40:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_dot:
[73:19-39] [Parameter]:
  shape('a' => string, 'b' => string)
[75:13-15] [Debug]:
  shape('a' => string, 'b' => string)
Summary for \test_eq1:
[113:19-36] [Parameter]:
  shape('b' => int)
Summary for \test_eq2:
[117:19-36] [Parameter]:
  shape()
Summary for \test_eqeq:
[23:20-37] [Parameter]:
  shape('a' => int, 'b' => int)
[25:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_eqeqeq:
[28:22-39] [Parameter]:
  shape('a' => int, 'b' => int)
[30:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_gt:
[63:18-35] [Parameter]:
  shape('a' => int, 'b' => int)
[65:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_gte:
[68:19-36] [Parameter]:
  shape('a' => int, 'b' => int)
[70:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_gtgt:
[93:20-37] [Parameter]:
  shape('a' => int, 'b' => int)
[95:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_lt:
[53:18-35] [Parameter]:
  shape('a' => int, 'b' => int)
[55:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_lte:
[58:19-36] [Parameter]:
  shape('a' => int, 'b' => int)
[60:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_ltlt:
[88:20-37] [Parameter]:
  shape('a' => int, 'b' => int)
[90:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_minus:
[8:21-38] [Parameter]:
  shape('a' => int, 'b' => int)
[10:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_percent:
[98:23-40] [Parameter]:
  shape('a' => int, 'b' => int)
[100:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_plus:
[3:20-37] [Parameter]:
  shape('a' => int, 'b' => int)
[5:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_slash:
[18:21-38] [Parameter]:
  shape('a' => int, 'b' => int)
[20:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_star:
[13:20-37] [Parameter]:
  shape('a' => int, 'b' => int)
[15:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_starstar:
[33:24-41] [Parameter]:
  shape('a' => int, 'b' => int)
[35:13-15] [Debug]:
  shape('a' => int, 'b' => int)
Summary for \test_xor:
[103:19-36] [Parameter]:
  shape('a' => int, 'b' => int)
[105:13-15] [Debug]:
  shape('a' => int, 'b' => int)
