/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010-2014 Facebook, Inc. (http://www.facebook.com)     |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/
#ifndef incl_HPHP_TRANSLATOR_INSTRS_H_
#define incl_HPHP_TRANSLATOR_INSTRS_H_

/*
 * Macros used for dispatch in the translator.
 */

#define REGULAR_INSTRS \
  CASE(IterBreak) \
  CASE(DecodeCufIter) \
  CASE(IterNext) \
  CASE(IterNextK) \
  CASE(WIterInit) \
  CASE(WIterInitK) \
  CASE(WIterNext) \
  CASE(WIterNextK) \
  CASE(MIterInit)  \
  CASE(MIterInitK) \
  CASE(MIterNext) \
  CASE(MIterNextK) \
  CASE(IterInitK) \
  CASE(IterInit) \
  CASE(JmpZ) \
  CASE(JmpNZ) \
  CASE(Jmp) \
  CASE(JmpNS) \
  CASE(BindM) \
  CASE(CGetM) \
  CASE(EmptyM) \
  CASE(FPassM) \
  CASE(IncDecM) \
  CASE(IssetM) \
  CASE(SetM) \
  CASE(SetOpM) \
  CASE(SetWithRefLM) \
  CASE(SetWithRefRM) \
  CASE(UnsetM) \
  CASE(VGetM) \
  CASE(FCallArray) \
  CASE(FCall) \
  CASE(FCallD) \
  CASE(ClsCnsD) \
  CASE(FPassCW) \
  CASE(FPassCE) \
  CASE(FPassR) \
  CASE(FPassV) \
  CASE(FPassG) \
  CASE(FPassL) \
  CASE(FPassS) \
  CASE(FCallBuiltin) \
  CASE(NewStructArray) \
  CASE(Switch) \
  CASE(SSwitch) \
  CASE(Lt) \
  CASE(Lte) \
  CASE(Gt) \
  CASE(Gte) \
  CASE(SetOpL) \
  CASE(InitProp) \
  CASE(BreakTraceHint) \
  CASE(IsTypeL) \
  CASE(IsTypeC) \
  CASE(IncDecL) \
  CASE(DefCls) \
  CASE(FPushCuf) \
  CASE(FPushCufF) \
  CASE(FPushCufSafe) \
  CASE(IncStat) \
  CASE(Eq) \
  CASE(Neq) \
  CASE(AssertRATL) \
  CASE(AssertRATStk) \
  CASE(SetL) \
  CASE(BindL) \
  CASE(EmptyL) \
  CASE(CastBool) \
  CASE(Same) \
  CASE(NSame) \
  CASE(Yield) \
  CASE(YieldK) \
  CASE(ContEnter) \
  CASE(ContRaise) \
  CASE(CreateCont) \
  CASE(Await) \
  CASE(BitAnd) \
  CASE(BitOr) \
  CASE(BitXor) \
  CASE(Sub) \
  CASE(Mul) \
  CASE(SubO) \
  CASE(MulO) \
  CASE(Add) \
  CASE(AddO) \
  CASE(AGetC) \
  CASE(AGetL) \
  CASE(AKExists) \
  CASE(Abs) \
  CASE(AddElemC) \
  CASE(AddNewElemC) \
  CASE(Array) \
  CASE(ArrayIdx) \
  CASE(BareThis) \
  CASE(BindG) \
  CASE(BindS) \
  CASE(BitNot) \
  CASE(CGetG) \
  CASE(CGetL) \
  CASE(CGetL2) \
  CASE(CGetS) \
  CASE(CIterFree) \
  CASE(CastArray) \
  CASE(CastDouble) \
  CASE(CastInt) \
  CASE(CastObject) \
  CASE(CastString) \
  CASE(Ceil) \
  CASE(CheckProp) \
  CASE(CheckThis) \
  CASE(Clone) \
  CASE(Cns) \
  CASE(CnsE) \
  CASE(CnsU) \
  CASE(ColAddElemC) \
  CASE(ColAddNewElemC) \
  CASE(ConcatN) \
  CASE(Concat) \
  CASE(ContCheck) \
  CASE(ContCurrent) \
  CASE(ContKey) \
  CASE(ContValid) \
  CASE(CreateCl) \
  CASE(DefCns) \
  CASE(DefFunc) \
  CASE(Dir) \
  CASE(Div) \
  CASE(Double) \
  CASE(Dup) \
  CASE(EmptyG) \
  CASE(EmptyS) \
  CASE(FPushClsMethodD) \
  CASE(FPushClsMethod) \
  CASE(FPushClsMethodF) \
  CASE(FPushCtor) \
  CASE(FPushCtorD) \
  CASE(FPushCufIter) \
  CASE(FPushFunc) \
  CASE(FPushFuncD) \
  CASE(FPushFuncU) \
  CASE(FPushObjMethodD) \
  CASE(False) \
  CASE(File) \
  CASE(Floor) \
  CASE(Idx) \
  CASE(InitThisLoc) \
  CASE(InstanceOf) \
  CASE(InstanceOfD) \
  CASE(Int) \
  CASE(IssetG) \
  CASE(IssetL) \
  CASE(IssetS) \
  CASE(IterFree) \
  CASE(LateBoundCls) \
  CASE(MIterFree) \
  CASE(Mod) \
  CASE(Pow) \
  CASE(NameA) \
  CASE(NativeImpl) \
  CASE(NewArray) \
  CASE(NewCol) \
  CASE(NewLikeArrayL) \
  CASE(NewMixedArray) \
  CASE(NewVArray) \
  CASE(NewMIArray) \
  CASE(NewMSArray) \
  CASE(NewPackedArray) \
  CASE(Not) \
  CASE(Null) \
  CASE(NullUninit) \
  CASE(OODeclExists) \
  CASE(Parent) \
  CASE(PopA) \
  CASE(PopC) \
  CASE(PopR) \
  CASE(PopV) \
  CASE(Print) \
  CASE(PushL) \
  CASE(RetC) \
  CASE(RetV) \
  CASE(Self) \
  CASE(SetG) \
  CASE(SetS) \
  CASE(Shl) \
  CASE(Shr) \
  CASE(Silence) \
  CASE(Sqrt) \
  CASE(StaticLoc) \
  CASE(StaticLocInit) \
  CASE(String) \
  CASE(Strlen) \
  CASE(This) \
  CASE(True) \
  CASE(Unbox) \
  CASE(UnboxR) \
  CASE(UnsetL) \
  CASE(VGetG) \
  CASE(VGetL) \
  CASE(VGetS) \
  CASE(VerifyParamType) \
  CASE(VerifyRetTypeC) \
  CASE(VerifyRetTypeV) \
  CASE(Xor) \
  /* */

#define INTERP_ONE_INSTRS \
  CASE(LowInvalid) \
  CASE(Nop) \
  CASE(Box) \
  CASE(BoxR) \
  CASE(BoxRNop) \
  CASE(UnboxRNop) \
  CASE(RGetCNop) \
  CASE(AddElemV) \
  CASE(AddNewElemV) \
  CASE(ClsCns) \
  CASE(Exit) \
  CASE(Fatal) \
  CASE(Unwind) \
  CASE(Throw) \
  CASE(CGetL3) \
  CASE(CGetN) \
  CASE(VGetN) \
  CASE(IssetN) \
  CASE(EmptyN) \
  CASE(SetN) \
  CASE(SetOpN) \
  CASE(SetOpG) \
  CASE(SetOpS) \
  CASE(IncDecN) \
  CASE(IncDecG) \
  CASE(IncDecS) \
  CASE(BindN) \
  CASE(UnsetN) \
  CASE(UnsetG) \
  CASE(FPushObjMethod) \
  /* TODO: move these out of interp one---they aren't */ \
  CASE(FPassC) \
  CASE(FPassVNop) \
  CASE(FPassN) \
  CASE(FCallUnpack) \
  CASE(CufSafeArray) \
  CASE(CufSafeReturn) \
  CASE(Incl) \
  CASE(InclOnce) \
  CASE(Req) \
  CASE(ReqOnce) \
  CASE(ReqDoc) \
  CASE(Eval) \
  CASE(DefClsNop) \
  CASE(DefTypeAlias) \
  CASE(Catch) \
  CASE(HighInvalid) \
  /*  */

#endif
