Code actions available:
------------------------------------------
Add override for FooParent::somePureMethod (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"\n  <<__Override>>\n  public function somePureMethod()[]: int {}\n\n",
          "range":{"end":{"character":29,"line":6},"start":{"character":29,"line":6}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Add override for FooParent::somePureMethod"
}

Applied edit for code action:
------------------------------------------
<?hh

abstract class FooParent {
  abstract public function somePureMethod()[]: int;
}

class Foo extends FooParent {
  <<__Override>>
  public function somePureMethod()[]: int {}

}
  //                  ^ at-caret

