ERROR: File "box_get_set.php", line 9, characters 55-56:
Type access is only valid for a class, `self`, or `this`. To relate type parameters and type constants, you likely want to use the 'with refinement' feature instead. (Naming[2129])
ERROR: File "box_get_set.php", line 44, characters 34-36:
Invalid argument (Typing[4110])
  File "box_get_set.php", line 44, characters 10-15:
  Expected `string`
  File "box_get_set.php", line 33, characters 20-20:
    via this generic `T`
  File "box_get_set.php", line 26, characters 18-20:
  But got `int`
ERROR: File "box_get_set.php", line 46, characters 18-21:
Invalid argument (Typing[4110])
  File "box_get_set.php", line 26, characters 18-20:
  Expected `int`
  File "box_get_set.php", line 46, characters 18-21:
  But got `string`
