<?hh // partial

function f(<<__Soft>> darray<int, string> $v) : <<__Soft>> ?int {
  $v[3] = "foo";
  foreach ($v as $k => $v) {
    return $k;
  }
  return null;
}

function ff() : <<__Soft>> void {
  expect<?int>(f(darray[2 => "fs"]));
}

function g(<<__Soft>> darray<int, string> $v) : <<__Soft>> darray<int, string> {
  expect<string>($v[0]);
  return $v;
}

function gg() : <<__Soft>> void {
  g(darray[0 => "sdf"]);
}

function h(): <<__Soft>> darray<int, string> {
  return darray[0 => 'billie', 3 => 'willie'];
}

function i(): <<__Soft>> darray<int, string> {
  $x = darray[];
  $x[3] = 'bob';
  return $x;
}

function expect<T>(T $_): void {}
