ERROR: File "enum_uncheckable_values.php", line 13, characters 6-17:
This enum has members whose values cannot be statically checked for duplicates. Use literal values, or add `<<__AllowUncheckedEnumValues>>` to the enum. (Typing[4520])
  File "enum_uncheckable_values.php", line 14, characters 3-3:
  `A` cannot be checked
ERROR: File "enum_uncheckable_values.php", line 19, characters 6-14:
This enum has members whose values cannot be statically checked for duplicates. Use literal values, or add `<<__AllowUncheckedEnumValues>>` to the enum. (Typing[4520])
  File "enum_uncheckable_values.php", line 20, characters 3-3:
  `X` cannot be checked
ERROR: File "enum_uncheckable_values.php", line 25, characters 6-21:
This enum has members whose values cannot be statically checked for duplicates. Use literal values, or add `<<__AllowUncheckedEnumValues>>` to the enum. (Typing[4520])
  File "enum_uncheckable_values.php", line 26, characters 3-3:
  `P` cannot be checked
  File "enum_uncheckable_values.php", line 27, characters 3-3:
  `Q` cannot be checked
