File "dep_types_and_null.php", line 15, characters 3-13:
  Ref as Ref<^(?^_)>
File "dep_types_and_null.php", line 17, characters 3-13:
  Ref as Ref<^?string>
File "dep_types_and_null.php", line 18, characters 3-20:
  ^?string
File "dep_types_and_null.php", line 24, characters 3-13:
  Ref as Ref<^(?^_)>
File "dep_types_and_null.php", line 25, characters 3-20:
  ^(?^_)
File "dep_types_and_null.php", line 28, characters 3-13:
  Ref as Ref<^(Exception as Exception | <expr#1> as Exception | ?^_)>
No errors
