File "static_method_expr_dep.php", line 14, characters 5-20:
  ~this where this as C
File "static_method_expr_dep.php", line 20, characters 5-20:
  ~this where this as C
File "static_method_expr_dep.php", line 26, characters 5-20:
  ~this where this as C
File "static_method_expr_dep.php", line 32, characters 5-15:
  ~exact C
File "static_method_expr_dep.php", line 38, characters 5-15:
  ~exact P
No errors
