Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"$${0:placeholder1} = 1 * 2;\n  $x = /*range-start*/$${0:placeholder1}/*range-end*/ + 3;",
          "range":{"end":{"character":45,"line":5},"start":{"character":2,"line":5}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Extract into variable"
}

Applied edit for code action:
------------------------------------------
<?hh

function main(): void {
  $placeholder0 = "";
  // the next placeholder should be called: $placeholder1
  $${0:placeholder1} = 1 * 2;
  $x = /*range-start*/$${0:placeholder1}/*range-end*/ + 3;
}

