HHVM_DEFINE_EXTENSION("vsdebug"
  SOURCES
    breakpoint.cpp
    breakpoint_command.cpp
    command_queue.cpp
    command.cpp
    completions_command.cpp
    configuration_done_command.cpp
    continue_command.cpp
    debugger.cpp
    evaluate_command.cpp
    ext_vsdebug.cpp
    fdtransport.cpp
    hook.cpp
    info_command.cpp
    initialize_command.cpp
    launch_attach_command.cpp
    logging.cpp
    pause_command.cpp
    php_executor.cpp
    resolve_bps_command.cpp
    run_psp_command.cpp
    run_to_location_command.cpp
    scopes_command.cpp
    session.cpp
    set_variable_command.cpp
    socket_transport.cpp
    stack_trace_command.cpp
    step_command.cpp
    terminate_thread_command.cpp
    threads_command.cpp
    transport.cpp
    variables_command.cpp
  HEADERS
    break_mode.h
    breakpoint.h
    client_preferences.h
    command_queue.h
    command.h
    debugger.h
    ext_vsdebug.h
    fdtransport.h
    hook.h
    logging.h
    php_executor.h
    server_object.h
    session.h
    socket_transport.h
    transport.h
  DEPENDS
    libFolly
)
