File "array_get_bad.php", line 29, characters 18-20:
This is a string (Typing[4110])
  File "array_get_bad.php", line 14, characters 3-13:
  It is incompatible with an int
File "array_get_bad.php", line 31, characters 17-19:
This is a string (Typing[4110])
  File "hhi_lib__srcs/hackarray.hhi", line 13, characters 56-58:
  It is incompatible with an int
File "array_get_bad.php", line 33, characters 22-24:
This is a string (Typing[4110])
  File "hhi_lib__srcs/collections/interfaces.hhi", line 301, characters 51-53:
  It is incompatible with an int
File "array_get_bad.php", line 35, characters 23-25:
This is a string (Typing[4110])
  File "hhi_lib__srcs/collections/interfaces.hhi", line 301, characters 51-53:
  It is incompatible with an int
File "array_get_bad.php", line 37, characters 23-25:
This is a string (Typing[4110])
  File "hhi_lib__srcs/collections/interfaces.hhi", line 301, characters 51-53:
  It is incompatible with an int
File "array_get_bad.php", line 39, characters 19-20:
This is an int (Typing[4110])
  File "array_get_bad.php", line 20, characters 9-14:
  It is incompatible with a string
File "array_get_bad.php", line 41, characters 18-19:
This is an int (Typing[4110])
  File "array_get_bad.php", line 21, characters 8-13:
  It is incompatible with a string
  File "hhi_lib__srcs/hackarray.hhi", line 11, characters 75-76:
    via this generic Tk
File "array_get_bad.php", line 43, characters 20-21:
This is an int (Typing[4110])
  File "array_get_bad.php", line 22, characters 7-12:
  It is incompatible with a string
  File "hhi_lib__srcs/collections/Map.hhi", line 57, characters 47-48:
    via this generic Tk
  File "hhi_lib__srcs/collections/interfaces.hhi", line 1126, characters 47-48:
    via this generic Tk
  File "hhi_lib__srcs/collections/interfaces.hhi", line 856, characters 52-53:
    via this generic Tk
File "array_get_bad.php", line 45, characters 21-22:
This is an int (Typing[4110])
  File "array_get_bad.php", line 23, characters 10-15:
  It is incompatible with a string
  File "hhi_lib__srcs/collections/ImmMap.hhi", line 43, characters 61-62:
    via this generic Tk
  File "hhi_lib__srcs/collections/interfaces.hhi", line 856, characters 52-53:
    via this generic Tk
File "array_get_bad.php", line 47, characters 21-22:
This is an int (Typing[4110])
  File "array_get_bad.php", line 24, characters 12-17:
  It is incompatible with a string
  File "hhi_lib__srcs/collections/interfaces.hhi", line 856, characters 52-53:
    via this generic Tk
File "array_get_bad.php", line 49, characters 20-21:
This is an int (Typing[4110])
  File "array_get_bad.php", line 25, characters 10-15:
  It is incompatible with a string
  File "hhi_lib__srcs/hackarray.hhi", line 12, characters 71-71:
    via this generic T
