Code actions available:
------------------------------------------
await expression (CodeActionKind: quickfix) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"Awaitable<mixed>",
          "range":{"end":{"character":32,"line":7},"start":{"character":27,"line":7}}
        },
        {
          "newText":"async ",
          "range":{"end":{"character":9,"line":7},"start":{"character":9,"line":7}}
        },
        {
          "newText":"return (int)await gen_int() + 3;",
          "range":{"end":{"character":30,"line":8},"start":{"character":4,"line":8}}
        }
      ]
    }
  },
  "kind":"quickfix",
  "title":"await expression"
}

Applied edit for code action:
------------------------------------------
<?hh

async function gen_int(): Awaitable<int> {
  return 1;
}

class A {
  public async function repro(): Awaitable<mixed> {
    return (int)await gen_int() + 3;
            //  ^ at-caret should be a quickfix (not a refactoring)
  }
}

