Code actions available:
------------------------------------------
Change to `void` (CodeActionKind: quickfix)
await expression (CodeActionKind: refactor) SELECTED
Extract into variable (CodeActionKind: refactor)

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"async ",
          "range":{"end":{"character":0,"line":7},"start":{"character":0,"line":7}}
        },
        {
          "newText":"$_ = /*range-start*/ await gen_int()/*range-end*/ + 3;",
          "range":{"end":{"character":52,"line":9},"start":{"character":4,"line":9}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"await expression"
}

Applied edit for code action:
------------------------------------------
<?hh

async function gen_int(): Awaitable<int> {
  return 1;
}

function example(): void {
async   // The refactor should not chang ethe return type of this lambda:
  (): Awaitable<mixed> ==> {
    $_ = /*range-start*/ await gen_int()/*range-end*/ + 3;
  };
}

