
---> 1. Trying to assign by reference the return value of a function that returns by value:

Strict Standards: Only variables should be assigned by reference in hphp/test/zend/bad/tests-lang/returnByReference.005.php on line 20
int(5)
int(100)

---> 2. Trying to assign by reference the return value of a function that returns a constant by ref:

HipHop Notice: Only variable references should be returned by reference in hphp/test/zend/bad/tests-lang/returnByReference.005.php on line 8
int(5)
int(100)

---> 3. Trying to assign by reference the return value of a function that returns by ref:
int(5)
int(5)
