comparing .main
Semdiff succeeded
comparing key foo
Semdiff failed
pc=;53, pc'=;53, i=String "finally 3" i'=String "finally 3x" asn={}{}

Edits = 

for foo:
- L4:
- String "finally 3"
+ L4:
+ String "finally 3x"
- L1:
+ L1:
- JmpZ L7
+ JmpZ L6
- L7:
+ L6:
+ UnsetL _2
+ UnsetL _3
+ F11:
+ UnsetL _2
+ UnsetL _3
+ String "inner, inner finally "
+ Print
+ PopC
+ Unwind
+ UnsetL _2
+ UnsetL _3
- JmpZ L6
+ JmpZ L7
- L6:
- String "inner, inner finally "
+ L7:
- Print
- PopC
- Unwind
- F11:
+ UnsetL _2
+ UnsetL _3
