# case_type.php--Foo.php starts here

.filepath "case_type.php--Foo.php";


.alias Foo = <"HH\\int"> (3,3) """D:1:{s:4:\"kind\";i:1;}""";
.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:10:\"case_types\";}""")] ;

# case_type.php--Foo.php ends here
# case_type.php--Arraykey.php starts here

.filepath "case_type.php--Arraykey.php";

.fatal 3:11,3:18 Parse "Cannot use `Arraykey` as a type name as it is reserved";

# case_type.php--Arraykey.php ends here
# case_type.php--Bool.php starts here

.filepath "case_type.php--Bool.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--Bool.php ends here
# case_type.php--Callable.php starts here

.filepath "case_type.php--Callable.php";

.fatal 3:11,3:18 Parse "Cannot use `Callable` as a type name as it is reserved";

# case_type.php--Callable.php ends here
# case_type.php--Classname.php starts here

.filepath "case_type.php--Classname.php";


.alias Classname = <"HH\\int"> (3,3) """D:1:{s:4:\"kind\";i:1;}""";
.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:10:\"case_types\";}""")] ;

# case_type.php--Classname.php ends here
# case_type.php--Darray.php starts here

.filepath "case_type.php--Darray.php";

.fatal 3:11,3:16 Parse "Cannot use `Darray` as a type name as it is reserved";

# case_type.php--Darray.php ends here
# case_type.php--Dynamic.php starts here

.filepath "case_type.php--Dynamic.php";

.fatal 3:11,3:17 Parse "Cannot use `Dynamic` as a type name as it is reserved";

# case_type.php--Dynamic.php ends here
# case_type.php--False.php starts here

.filepath "case_type.php--False.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--False.php ends here
# case_type.php--Float.php starts here

.filepath "case_type.php--Float.php";

.fatal 3:11,3:15 Parse "Cannot use `Float` as a type name as it is reserved";

# case_type.php--Float.php ends here
# case_type.php--Int.php starts here

.filepath "case_type.php--Int.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--Int.php ends here
# case_type.php--Mixed.php starts here

.filepath "case_type.php--Mixed.php";

.fatal 3:11,3:15 Parse "Cannot use `Mixed` as a type name as it is reserved";

# case_type.php--Mixed.php ends here
# case_type.php--Nonnull.php starts here

.filepath "case_type.php--Nonnull.php";

.fatal 3:11,3:17 Parse "Cannot use `Nonnull` as a type name as it is reserved";

# case_type.php--Nonnull.php ends here
# case_type.php--Noreturn.php starts here

.filepath "case_type.php--Noreturn.php";

.fatal 3:11,3:18 Parse "Cannot use `Noreturn` as a type name as it is reserved";

# case_type.php--Noreturn.php ends here
# case_type.php--Nothing.php starts here

.filepath "case_type.php--Nothing.php";

.fatal 3:11,3:17 Parse "Cannot use `Nothing` as a type name as it is reserved";

# case_type.php--Nothing.php ends here
# case_type.php--Null.php starts here

.filepath "case_type.php--Null.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--Null.php ends here
# case_type.php--Num.php starts here

.filepath "case_type.php--Num.php";

.fatal 3:11,3:13 Parse "Cannot use `Num` as a type name as it is reserved";

# case_type.php--Num.php ends here
# case_type.php--Parent.php starts here

.filepath "case_type.php--Parent.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--Parent.php ends here
# case_type.php--Resource.php starts here

.filepath "case_type.php--Resource.php";

.fatal 3:11,3:18 Parse "Cannot use `Resource` as a type name as it is reserved";

# case_type.php--Resource.php ends here
# case_type.php--Self.php starts here

.filepath "case_type.php--Self.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--Self.php ends here
# case_type.php--Static.php starts here

.filepath "case_type.php--Static.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--Static.php ends here
# case_type.php--String.php starts here

.filepath "case_type.php--String.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--String.php ends here
# case_type.php--This.php starts here

.filepath "case_type.php--This.php";

.fatal 3:11,3:14 Parse "Cannot use `This` as a type name as it is reserved";

# case_type.php--This.php ends here
# case_type.php--True.php starts here

.filepath "case_type.php--True.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--True.php ends here
# case_type.php--Varray.php starts here

.filepath "case_type.php--Varray.php";

.fatal 3:11,3:16 Parse "Cannot use `Varray` as a type name as it is reserved";

# case_type.php--Varray.php ends here
# case_type.php--Void.php starts here

.filepath "case_type.php--Void.php";

.fatal 3:11,3:11 Parse "A name is expected here.";

# case_type.php--Void.php ends here
# case_type.php--_.php starts here

.filepath "case_type.php--_.php";

.fatal 3:11,3:11 Parse "Cannot use `_` as a type name as it is reserved";

# case_type.php--_.php ends here
