# interface.php--Foo.php starts here

.filepath "interface.php--Foo.php";


.class {} [interface] Foo (2,2) {
}

# interface.php--Foo.php ends here
# interface.php--Arraykey.php starts here

.filepath "interface.php--Arraykey.php";

.fatal 2:11,2:18 Parse "Cannot use `Arraykey` as a type name as it is reserved";

# interface.php--Arraykey.php ends here
# interface.php--Bool.php starts here

.filepath "interface.php--Bool.php";

.fatal 2:11,2:14 Parse "Cannot use `Bool` as a type name as it is reserved";

# interface.php--Bool.php ends here
# interface.php--Callable.php starts here

.filepath "interface.php--Callable.php";

.fatal 2:11,2:18 Parse "Cannot use `Callable` as a type name as it is reserved";

# interface.php--Callable.php ends here
# interface.php--Classname.php starts here

.filepath "interface.php--Classname.php";


.class {} [interface] Classname (2,2) {
}

# interface.php--Classname.php ends here
# interface.php--Darray.php starts here

.filepath "interface.php--Darray.php";

.fatal 2:11,2:16 Parse "Cannot use `Darray` as a type name as it is reserved";

# interface.php--Darray.php ends here
# interface.php--Dynamic.php starts here

.filepath "interface.php--Dynamic.php";

.fatal 2:11,2:17 Parse "Cannot use `Dynamic` as a type name as it is reserved";

# interface.php--Dynamic.php ends here
# interface.php--False.php starts here

.filepath "interface.php--False.php";

.fatal 2:11,2:15 Parse "Cannot use `False` as a type name as it is reserved";

# interface.php--False.php ends here
# interface.php--Float.php starts here

.filepath "interface.php--Float.php";

.fatal 2:11,2:15 Parse "Cannot use `Float` as a type name as it is reserved";

# interface.php--Float.php ends here
# interface.php--Int.php starts here

.filepath "interface.php--Int.php";

.fatal 2:11,2:13 Parse "Cannot use `Int` as a type name as it is reserved";

# interface.php--Int.php ends here
# interface.php--Mixed.php starts here

.filepath "interface.php--Mixed.php";

.fatal 2:11,2:15 Parse "Cannot use `Mixed` as a type name as it is reserved";

# interface.php--Mixed.php ends here
# interface.php--Nonnull.php starts here

.filepath "interface.php--Nonnull.php";

.fatal 2:11,2:17 Parse "Cannot use `Nonnull` as a type name as it is reserved";

# interface.php--Nonnull.php ends here
# interface.php--Noreturn.php starts here

.filepath "interface.php--Noreturn.php";

.fatal 2:11,2:18 Parse "Cannot use `Noreturn` as a type name as it is reserved";

# interface.php--Noreturn.php ends here
# interface.php--Nothing.php starts here

.filepath "interface.php--Nothing.php";

.fatal 2:11,2:17 Parse "Cannot use `Nothing` as a type name as it is reserved";

# interface.php--Nothing.php ends here
# interface.php--Null.php starts here

.filepath "interface.php--Null.php";

.fatal 2:11,2:14 Parse "Cannot use `Null` as a type name as it is reserved";

# interface.php--Null.php ends here
# interface.php--Num.php starts here

.filepath "interface.php--Num.php";

.fatal 2:11,2:13 Parse "Cannot use `Num` as a type name as it is reserved";

# interface.php--Num.php ends here
# interface.php--Parent.php starts here

.filepath "interface.php--Parent.php";

.fatal 2:11,2:16 Parse "Cannot use `Parent` as a type name as it is reserved";

# interface.php--Parent.php ends here
# interface.php--Resource.php starts here

.filepath "interface.php--Resource.php";

.fatal 2:11,2:18 Parse "Cannot use `Resource` as a type name as it is reserved";

# interface.php--Resource.php ends here
# interface.php--Self.php starts here

.filepath "interface.php--Self.php";

.fatal 2:11,2:14 Parse "Cannot use `Self` as a type name as it is reserved";

# interface.php--Self.php ends here
# interface.php--Static.php starts here

.filepath "interface.php--Static.php";

.fatal 2:11,2:11 Parse "A name is expected here.";

# interface.php--Static.php ends here
# interface.php--String.php starts here

.filepath "interface.php--String.php";

.fatal 2:11,2:16 Parse "Cannot use `String` as a type name as it is reserved";

# interface.php--String.php ends here
# interface.php--This.php starts here

.filepath "interface.php--This.php";

.fatal 2:11,2:14 Parse "Cannot use `This` as a type name as it is reserved";

# interface.php--This.php ends here
# interface.php--True.php starts here

.filepath "interface.php--True.php";

.fatal 2:11,2:14 Parse "Cannot use `True` as a type name as it is reserved";

# interface.php--True.php ends here
# interface.php--Varray.php starts here

.filepath "interface.php--Varray.php";

.fatal 2:11,2:16 Parse "Cannot use `Varray` as a type name as it is reserved";

# interface.php--Varray.php ends here
# interface.php--Void.php starts here

.filepath "interface.php--Void.php";

.fatal 2:11,2:14 Parse "Cannot use `Void` as a type name as it is reserved";

# interface.php--Void.php ends here
# interface.php--_.php starts here

.filepath "interface.php--_.php";

.fatal 2:11,2:11 Parse "Cannot use `_` as a type name as it is reserved";

# interface.php--_.php ends here
