# module_newtype.php--mm.php starts here

.filepath "module_newtype.php--mm.php";


.module mm (2,2) {
}

# module_newtype.php--mm.php ends here
# module_newtype.php--Foo.php starts here

.filepath "module_newtype.php--Foo.php";


.module_use "mm";

.alias Foo = <"HH\\int"> (3,3) """D:3:{s:4:\"kind\";i:1;s:6:\"opaque\";b:1;s:5:\"alias\";s:3:\"Foo\";}""";
# module_newtype.php--Foo.php ends here
# module_newtype.php--Arraykey.php starts here

.filepath "module_newtype.php--Arraykey.php";

.fatal 3:16,3:23 Parse "Cannot use `Arraykey` as a type name as it is reserved";

# module_newtype.php--Arraykey.php ends here
# module_newtype.php--Bool.php starts here

.filepath "module_newtype.php--Bool.php";

.fatal 3:16,3:19 Parse "Cannot use `Bool` as a type name as it is reserved";

# module_newtype.php--Bool.php ends here
# module_newtype.php--Callable.php starts here

.filepath "module_newtype.php--Callable.php";

.fatal 3:16,3:23 Parse "Cannot use `Callable` as a type name as it is reserved";

# module_newtype.php--Callable.php ends here
# module_newtype.php--Classname.php starts here

.filepath "module_newtype.php--Classname.php";


.module_use "mm";

.alias Classname = <"HH\\int"> (3,3) """D:3:{s:4:\"kind\";i:1;s:6:\"opaque\";b:1;s:5:\"alias\";s:9:\"Classname\";}""";
# module_newtype.php--Classname.php ends here
# module_newtype.php--Darray.php starts here

.filepath "module_newtype.php--Darray.php";

.fatal 3:16,3:21 Parse "Cannot use `Darray` as a type name as it is reserved";

# module_newtype.php--Darray.php ends here
# module_newtype.php--Dynamic.php starts here

.filepath "module_newtype.php--Dynamic.php";

.fatal 3:16,3:22 Parse "Cannot use `Dynamic` as a type name as it is reserved";

# module_newtype.php--Dynamic.php ends here
# module_newtype.php--False.php starts here

.filepath "module_newtype.php--False.php";

.fatal 3:16,3:20 Parse "Cannot use `False` as a type name as it is reserved";

# module_newtype.php--False.php ends here
# module_newtype.php--Float.php starts here

.filepath "module_newtype.php--Float.php";

.fatal 3:16,3:20 Parse "Cannot use `Float` as a type name as it is reserved";

# module_newtype.php--Float.php ends here
# module_newtype.php--Int.php starts here

.filepath "module_newtype.php--Int.php";

.fatal 3:16,3:18 Parse "Cannot use `Int` as a type name as it is reserved";

# module_newtype.php--Int.php ends here
# module_newtype.php--Mixed.php starts here

.filepath "module_newtype.php--Mixed.php";

.fatal 3:16,3:20 Parse "Cannot use `Mixed` as a type name as it is reserved";

# module_newtype.php--Mixed.php ends here
# module_newtype.php--Nonnull.php starts here

.filepath "module_newtype.php--Nonnull.php";

.fatal 3:16,3:22 Parse "Cannot use `Nonnull` as a type name as it is reserved";

# module_newtype.php--Nonnull.php ends here
# module_newtype.php--Noreturn.php starts here

.filepath "module_newtype.php--Noreturn.php";

.fatal 3:16,3:23 Parse "Cannot use `Noreturn` as a type name as it is reserved";

# module_newtype.php--Noreturn.php ends here
# module_newtype.php--Nothing.php starts here

.filepath "module_newtype.php--Nothing.php";

.fatal 3:16,3:22 Parse "Cannot use `Nothing` as a type name as it is reserved";

# module_newtype.php--Nothing.php ends here
# module_newtype.php--Null.php starts here

.filepath "module_newtype.php--Null.php";

.fatal 3:16,3:19 Parse "Cannot use `Null` as a type name as it is reserved";

# module_newtype.php--Null.php ends here
# module_newtype.php--Num.php starts here

.filepath "module_newtype.php--Num.php";

.fatal 3:16,3:18 Parse "Cannot use `Num` as a type name as it is reserved";

# module_newtype.php--Num.php ends here
# module_newtype.php--Parent.php starts here

.filepath "module_newtype.php--Parent.php";

.fatal 3:16,3:21 Parse "Cannot use `Parent` as a type name as it is reserved";

# module_newtype.php--Parent.php ends here
# module_newtype.php--Resource.php starts here

.filepath "module_newtype.php--Resource.php";

.fatal 3:16,3:23 Parse "Cannot use `Resource` as a type name as it is reserved";

# module_newtype.php--Resource.php ends here
# module_newtype.php--Self.php starts here

.filepath "module_newtype.php--Self.php";

.fatal 3:16,3:19 Parse "Cannot use `Self` as a type name as it is reserved";

# module_newtype.php--Self.php ends here
# module_newtype.php--Static.php starts here

.filepath "module_newtype.php--Static.php";

.fatal 3:16,3:16 Parse "A name is expected here.";

# module_newtype.php--Static.php ends here
# module_newtype.php--String.php starts here

.filepath "module_newtype.php--String.php";

.fatal 3:16,3:21 Parse "Cannot use `String` as a type name as it is reserved";

# module_newtype.php--String.php ends here
# module_newtype.php--This.php starts here

.filepath "module_newtype.php--This.php";

.fatal 3:16,3:19 Parse "Cannot use `This` as a type name as it is reserved";

# module_newtype.php--This.php ends here
# module_newtype.php--True.php starts here

.filepath "module_newtype.php--True.php";

.fatal 3:16,3:19 Parse "Cannot use `True` as a type name as it is reserved";

# module_newtype.php--True.php ends here
# module_newtype.php--Varray.php starts here

.filepath "module_newtype.php--Varray.php";

.fatal 3:16,3:21 Parse "Cannot use `Varray` as a type name as it is reserved";

# module_newtype.php--Varray.php ends here
# module_newtype.php--Void.php starts here

.filepath "module_newtype.php--Void.php";

.fatal 3:16,3:19 Parse "Cannot use `Void` as a type name as it is reserved";

# module_newtype.php--Void.php ends here
# module_newtype.php--_.php starts here

.filepath "module_newtype.php--_.php";

.fatal 3:16,3:16 Parse "Cannot use `_` as a type name as it is reserved";

# module_newtype.php--_.php ends here
