# newctx.php--defaults.php starts here

.filepath "newctx.php--defaults.php";


.class {} [interface] HH\Contexts\I (4,4) {
}

.alias HH\Contexts\defaults = <"HH\\varray"> (3,3) """D:2:{s:4:\"kind\";i:10;s:10:\"elem_types\";v:1:{D:2:{s:4:\"kind\";i:101;s:9:\"classname\";s:13:\"HH\\Contexts\\I\";}}}""";
# newctx.php--defaults.php ends here
# newctx.php--Foo.php starts here

.filepath "newctx.php--Foo.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Foo.php ends here
# newctx.php--Arraykey.php starts here

.filepath "newctx.php--Arraykey.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Arraykey.php ends here
# newctx.php--Bool.php starts here

.filepath "newctx.php--Bool.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--Bool.php ends here
# newctx.php--Callable.php starts here

.filepath "newctx.php--Callable.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Callable.php ends here
# newctx.php--Classname.php starts here

.filepath "newctx.php--Classname.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Classname.php ends here
# newctx.php--Darray.php starts here

.filepath "newctx.php--Darray.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Darray.php ends here
# newctx.php--Dynamic.php starts here

.filepath "newctx.php--Dynamic.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Dynamic.php ends here
# newctx.php--False.php starts here

.filepath "newctx.php--False.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--False.php ends here
# newctx.php--Float.php starts here

.filepath "newctx.php--Float.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Float.php ends here
# newctx.php--Int.php starts here

.filepath "newctx.php--Int.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--Int.php ends here
# newctx.php--Mixed.php starts here

.filepath "newctx.php--Mixed.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Mixed.php ends here
# newctx.php--Nonnull.php starts here

.filepath "newctx.php--Nonnull.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Nonnull.php ends here
# newctx.php--Noreturn.php starts here

.filepath "newctx.php--Noreturn.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Noreturn.php ends here
# newctx.php--Nothing.php starts here

.filepath "newctx.php--Nothing.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Nothing.php ends here
# newctx.php--Null.php starts here

.filepath "newctx.php--Null.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--Null.php ends here
# newctx.php--Num.php starts here

.filepath "newctx.php--Num.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Num.php ends here
# newctx.php--Parent.php starts here

.filepath "newctx.php--Parent.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--Parent.php ends here
# newctx.php--Resource.php starts here

.filepath "newctx.php--Resource.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Resource.php ends here
# newctx.php--Self.php starts here

.filepath "newctx.php--Self.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--Self.php ends here
# newctx.php--String.php starts here

.filepath "newctx.php--String.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--String.php ends here
# newctx.php--This.php starts here

.filepath "newctx.php--This.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--This.php ends here
# newctx.php--True.php starts here

.filepath "newctx.php--True.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--True.php ends here
# newctx.php--Varray.php starts here

.filepath "newctx.php--Varray.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--Varray.php ends here
# newctx.php--Void.php starts here

.filepath "newctx.php--Void.php";

.fatal 3:8,3:8 Parse "A name is expected here.";

# newctx.php--Void.php ends here
# newctx.php--_.php starts here

.filepath "newctx.php--_.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--_.php ends here
# newctx.php--NFoo.php starts here

.filepath "newctx.php--NFoo.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NFoo.php ends here
# newctx.php--NArraykey.php starts here

.filepath "newctx.php--NArraykey.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NArraykey.php ends here
# newctx.php--NBool.php starts here

.filepath "newctx.php--NBool.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NBool.php ends here
# newctx.php--NCallable.php starts here

.filepath "newctx.php--NCallable.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NCallable.php ends here
# newctx.php--NClassname.php starts here

.filepath "newctx.php--NClassname.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NClassname.php ends here
# newctx.php--NDarray.php starts here

.filepath "newctx.php--NDarray.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NDarray.php ends here
# newctx.php--NDynamic.php starts here

.filepath "newctx.php--NDynamic.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NDynamic.php ends here
# newctx.php--NFalse.php starts here

.filepath "newctx.php--NFalse.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NFalse.php ends here
# newctx.php--NFloat.php starts here

.filepath "newctx.php--NFloat.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NFloat.php ends here
# newctx.php--NInt.php starts here

.filepath "newctx.php--NInt.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NInt.php ends here
# newctx.php--NMixed.php starts here

.filepath "newctx.php--NMixed.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NMixed.php ends here
# newctx.php--NNonnull.php starts here

.filepath "newctx.php--NNonnull.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NNonnull.php ends here
# newctx.php--NNoreturn.php starts here

.filepath "newctx.php--NNoreturn.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NNoreturn.php ends here
# newctx.php--NNothing.php starts here

.filepath "newctx.php--NNothing.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NNothing.php ends here
# newctx.php--NNull.php starts here

.filepath "newctx.php--NNull.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NNull.php ends here
# newctx.php--NNum.php starts here

.filepath "newctx.php--NNum.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NNum.php ends here
# newctx.php--NParent.php starts here

.filepath "newctx.php--NParent.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NParent.php ends here
# newctx.php--NResource.php starts here

.filepath "newctx.php--NResource.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NResource.php ends here
# newctx.php--NSelf.php starts here

.filepath "newctx.php--NSelf.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NSelf.php ends here
# newctx.php--NString.php starts here

.filepath "newctx.php--NString.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NString.php ends here
# newctx.php--NThis.php starts here

.filepath "newctx.php--NThis.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NThis.php ends here
# newctx.php--NTrue.php starts here

.filepath "newctx.php--NTrue.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NTrue.php ends here
# newctx.php--NVarray.php starts here

.filepath "newctx.php--NVarray.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--NVarray.php ends here
# newctx.php--NVoid.php starts here

.filepath "newctx.php--NVoid.php";

.fatal 4:8,4:8 Parse "A name is expected here.";

# newctx.php--NVoid.php ends here
# newctx.php--N_.php starts here

.filepath "newctx.php--N_.php";


.file_attributes ["__EnableUnstableFeatures"("""v:1:{s:31:\"context_alias_declaration_short\";}""")] ;

# newctx.php--N_.php ends here
