/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010 Facebook, Inc. (http://www.facebook.com)          |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXT_INTL_H__
#define __EXT_INTL_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>
#include <runtime/base/zend/zend_collator.h>
#include <unicode/ucol.h> // icu

namespace HPHP {

///////////////////////////////////////////////////////////////////////////////

int64 f_intl_get_error_code();
String f_intl_get_error_message();
String f_intl_error_name(int64 error_code);
bool f_intl_is_failure(int64 error_code);

///////////////////////////////////////////////////////////////////////////////

extern const int64 q_collator_SORT_REGULAR;
extern const int64 q_collator_SORT_NUMERIC;
extern const int64 q_collator_SORT_STRING;
extern const int64 q_collator_FRENCH_COLLATION;
extern const int64 q_collator_ALTERNATE_HANDLING;
extern const int64 q_collator_CASE_FIRST;
extern const int64 q_collator_CASE_LEVEL;
extern const int64 q_collator_NORMALIZATION_MODE;
extern const int64 q_collator_STRENGTH;
extern const int64 q_collator_HIRAGANA_QUATERNARY_MODE;
extern const int64 q_collator_NUMERIC_COLLATION;
extern const int64 q_collator_DEFAULT_VALUE;
extern const int64 q_collator_PRIMARY;
extern const int64 q_collator_SECONDARY;
extern const int64 q_collator_TERTIARY;
extern const int64 q_collator_DEFAULT_STRENGTH;
extern const int64 q_collator_QUATERNARY;
extern const int64 q_collator_IDENTICAL;
extern const int64 q_collator_OFF;
extern const int64 q_collator_ON;
extern const int64 q_collator_SHIFTED;
extern const int64 q_collator_NON_IGNORABLE;
extern const int64 q_collator_LOWER_FIRST;
extern const int64 q_collator_UPPER_FIRST;

///////////////////////////////////////////////////////////////////////////////
// class Collator

FORWARD_DECLARE_CLASS(collator);
class c_collator : public ExtObjectData, public Sweepable {
 public:
  BEGIN_CLASS_MAP(collator)
  END_CLASS_MAP(collator)
  DECLARE_CLASS(collator, Collator, ObjectData)
  DECLARE_INVOKES_FROM_EVAL
  ObjectData* dynCreate(CArrRef params, bool init = true);

  // need to implement
  public: c_collator();
  public: ~c_collator();
  public: void t___construct(CStrRef locale);
  public: bool t_asort(Variant arr, int64 sort_flag = q_collator_SORT_REGULAR);
  public: Variant t_compare(CStrRef str1, CStrRef str2);
  public: static Variant ti_create(const char* cls, CStrRef locale);
  public: static Variant t_create(CStrRef locale) {
    return ti_create("collator", locale);
  }
  public: int64 t_getattribute(int64 attr);
  public: int64 t_geterrorcode();
  public: String t_geterrormessage();
  public: String t_getlocale(int64 type = 0);
  public: int64 t_getstrength();
  public: bool t_setattribute(int64 attr, int64 val);
  public: bool t_setstrength(int64 strength);
  public: bool t_sortwithsortkeys(Variant arr);
  public: bool t_sort(Variant arr, int64 sort_flag = q_collator_SORT_REGULAR);
  public: Variant t___destruct();

  // implemented by HPHP
  public: c_collator *create(String locale);
  public: void dynConstruct(CArrRef Params);
  public: void dynConstructFromEval(Eval::VariableEnvironment &env, const Eval::FunctionCallExpression *call);
  public: virtual void destruct();

 private:
  String     m_locale;
  UCollator *m_ucoll;
  intl_error m_errcode;
};

Variant f_collator_asort(CVarRef obj, Variant arr, int64 sort_flag = 0);
Variant f_collator_compare(CVarRef obj, CStrRef str1, CStrRef str2);
Variant f_collator_create(CStrRef locale);
Variant f_collator_get_attribute(CVarRef obj, int64 attr);
Variant f_collator_get_error_code(CVarRef obj);
Variant f_collator_get_error_message(CVarRef obj);
Variant f_collator_get_locale(CVarRef obj, int64 type = 0);
Variant f_collator_get_strength(CVarRef obj);
Variant f_collator_set_attribute(CVarRef obj, int64 attr, int64 val);
Variant f_collator_set_strength(CVarRef obj, int64 strength);
Variant f_collator_sort_with_sort_keys(CVarRef obj, Variant arr);
Variant f_collator_sort(CVarRef obj, Variant arr, int64 sort_flag = 0);

///////////////////////////////////////////////////////////////////////////////

extern const int64 q_locale_ACTUAL_LOCALE;
extern const int64 q_locale_VALID_LOCALE;

///////////////////////////////////////////////////////////////////////////////

FORWARD_DECLARE_CLASS(locale);
class c_locale : public ExtObjectData {
 public:
  BEGIN_CLASS_MAP(locale)
  END_CLASS_MAP(locale)
  DECLARE_CLASS(locale, Locale, ObjectData)
  DECLARE_INVOKES_FROM_EVAL
  ObjectData* dynCreate(CArrRef params, bool init = true);

  // need to implement
  public: c_locale();
  public: ~c_locale();
  public: void t___construct();
  public: Variant t___destruct();

  // implemented by HPHP
  public: c_locale *create();
  public: void dynConstruct(CArrRef Params);
  public: void dynConstructFromEval(Eval::VariableEnvironment &env,
                                    const Eval::FunctionCallExpression *call);
  public: virtual void destruct();

};

///////////////////////////////////////////////////////////////////////////////

extern const int64 q_normalizer_NONE;
extern const int64 q_normalizer_FORM_D;
extern const int64 q_normalizer_NFD;
extern const int64 q_normalizer_FORM_KD;
extern const int64 q_normalizer_NFKD;
extern const int64 q_normalizer_FORM_C;
extern const int64 q_normalizer_NFC;
extern const int64 q_normalizer_FORM_KC;
extern const int64 q_normalizer_NFKC;

///////////////////////////////////////////////////////////////////////////////
// class Normalizer

FORWARD_DECLARE_CLASS(normalizer);
class c_normalizer : public ExtObjectData, public Sweepable {
 public:
  BEGIN_CLASS_MAP(normalizer)
  END_CLASS_MAP(normalizer)
  DECLARE_CLASS(normalizer, Normalizer, ObjectData)
  DECLARE_INVOKES_FROM_EVAL
  ObjectData* dynCreate(CArrRef params, bool init = true);

  // need to implement
  public: c_normalizer();
  public: ~c_normalizer();
  public: void t___construct();
  public: static Variant ti_isnormalized(const char* cls , CStrRef input, int64 form = q_normalizer_FORM_C);
  public: static Variant t_isnormalized(CStrRef input, int64 form = q_normalizer_FORM_C) {
    return ti_isnormalized("normalizer", input, form);
  }
  public: static Variant ti_normalize(const char* cls , CStrRef input, int64 form = q_normalizer_FORM_C);
  public: static Variant t_normalize(CStrRef input, int64 form = q_normalizer_FORM_C) {
    return ti_normalize("normalizer", input, form);
  }
  public: Variant t___destruct();

  // implemented by HPHP
  public: c_normalizer *create();
  public: void dynConstruct(CArrRef Params);
  public: void dynConstructFromEval(Eval::VariableEnvironment &env,
                                    const Eval::FunctionCallExpression *call);
  public: virtual void destruct();

};

///////////////////////////////////////////////////////////////////////////////
// IDN functions

Variant f_idn_to_ascii(CStrRef domain, Variant errorcode = null);
Variant f_idn_to_unicode(CStrRef domain, Variant errorcode = null);
Variant f_idn_to_utf8(CStrRef domain, Variant errorcode = null);

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_INTL_H__
