/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010 Facebook, Inc. (http://www.facebook.com)          |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXT_MAILPARSE_H__
#define __EXT_MAILPARSE_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

bool f_mail(CStrRef to, CStrRef subject, CStrRef message, CStrRef additional_headers = null_string, CStrRef additional_parameters = null_string);
int f_ezmlm_hash(CStrRef addr);
Object f_mailparse_msg_create();
bool f_mailparse_msg_free(CObjRef mimemail);
Variant f_mailparse_msg_parse_file(CStrRef filename);
bool f_mailparse_msg_parse(CObjRef mimemail, CStrRef data);
Variant f_mailparse_msg_extract_part_file(CObjRef mimemail, CVarRef filename, CVarRef callbackfunc = "");
Variant f_mailparse_msg_extract_whole_part_file(CObjRef mimemail, CVarRef filename, CVarRef callbackfunc = "");
Variant f_mailparse_msg_extract_part(CObjRef mimemail, CVarRef msgbody, CVarRef callbackfunc = "");
Array f_mailparse_msg_get_part_data(CObjRef mimemail);
Variant f_mailparse_msg_get_part(CObjRef mimemail, CStrRef mimesection);
Array f_mailparse_msg_get_structure(CObjRef mimemail);
Array f_mailparse_rfc822_parse_addresses(CStrRef addresses);
bool f_mailparse_stream_encode(CObjRef sourcefp, CObjRef destfp, CStrRef encoding);
Variant f_mailparse_uudecode_all(CObjRef fp);
Variant f_mailparse_determine_best_xfer_encoding(CObjRef fp);

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_MAILPARSE_H__
