=== Shape analysis results for darray_type_hint.php
[
  {
    "directives":[
      {
        "pos":{"path":"darray_type_hint.php","line":11,"start":15,"end":33},
        "kind":"Hint",
        "type":"shape('a' => int)"
      },
      {
        "pos":{"path":"darray_type_hint.php","line":12,"start":10,"end":26},
        "kind":"Allocation",
        "type":"shape('a' => int)"
      }
    ],
    "error_count":0
  },
  {
    "directives":[
      {
        "pos":{"path":"darray_type_hint.php","line":7,"start":15,"end":35},
        "kind":"Hint",
        "type":"shape('a' => int)"
      },
      {
        "pos":{"path":"darray_type_hint.php","line":8,"start":10,"end":24},
        "kind":"Allocation",
        "type":"shape('a' => int)"
      }
    ],
    "error_count":0
  },
  {
    "directives":[
      {
        "pos":{"path":"darray_type_hint.php","line":3,"start":15,"end":35},
        "kind":"Hint",
        "type":"shape('a' => int)"
      },
      {
        "pos":{"path":"darray_type_hint.php","line":4,"start":10,"end":26},
        "kind":"Allocation",
        "type":"shape('a' => int)"
      }
    ],
    "error_count":0
  }
]