FoldedClass {
    name: "\\C",
    pos: Pos(root|abstract_method.php, 3:16-17),
    kind: Cclass(
        Abstract,
    ),
    methods: {
        "f": FoldedElement {
            flags: ABSTRACT,
            origin: "\\C",
            visibility: Public,
            deprecated: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|abstract_method.php, 3:16-17),
            ty: HH\classname<this>,
            origin: "\\C",
            refs: [],
        },
    },
}

They matched!
