[("\\f",
  (Shallow_decl_defs.Fun
     { Typing_defs.fe_deprecated = None;
       fe_type =
       (Rwitness (root|at_most_rx_as_func_with_optional_func.php line 4, characters 10-10),
        (Tfun
           { ft_arity = (Fstandard ());
             ft_tparams =
             [{ Typing_defs_core.tp_variance = Invariant;
                tp_name = ([4:12-13], "T"); tp_tparams = [];
                tp_constraints = []; tp_reified = Erased;
                tp_user_attributes = [] }
               ];
             ft_where_constraints = [];
             ft_params =
             [{ fp_pos = [6:24-34]; fp_name = (Some "$predicate");
                fp_type =
                { et_enforced = false;
                  et_type =
                  (Rhint (root|at_most_rx_as_func_with_optional_func.php line 6, characters 3-22),
                   (Toption
                      (Rhint (root|at_most_rx_as_func_with_optional_func.php line 6, characters 4-22),
                       (Tfun
                          { ft_arity = (Fstandard ()); ft_tparams = [];
                            ft_where_constraints = [];
                            ft_params =
                            [{ fp_pos = [6:14-15]; fp_name = None;
                               fp_type =
                               { et_enforced = false;
                                 et_type =
                                 (Rhint (root|at_most_rx_as_func_with_optional_func.php line 6, characters 14-14),
                                  (Tgeneric ("T", [])))
                                 };
                               fp_rx_annotation = None;
                               fp_flags =
                               (make_fp_flags ~mutability:None
                                 ~accept_disposable:false ~has_default:false
                                 ~mode:Typing_defs_core.FPnormal
                                 ~ifc_external:false ~ifc_can_call:false
                                 ~is_atom:false ~readonly:false
                                 ~const_function:false);
                                }
                              ];
                            ft_implicit_params =
                            { capability = (CapDefaults [6:4-23]) };
                            ft_ret =
                            { et_enforced = false;
                              et_type =
                              (Rhint (root|at_most_rx_as_func_with_optional_func.php line 6, characters 18-21),
                               (Tprim Tbool))
                              };
                            ft_flags =
                            (make_ft_flags FSync None
                              ~return_disposable:false ~returns_mutable:false
                              ~returns_void_to_rx:false
                              ~returns_readonly:false ~readonly_this:false
                              ~is_const:false);
                            ft_reactive = RxVar {};
                            ft_ifc_decl = FDPolicied {PUBLIC} }))))
                  };
                fp_rx_annotation = (Some Param_rx_var);
                fp_flags =
                (make_fp_flags ~mutability:None ~accept_disposable:false
                  ~has_default:true ~mode:Typing_defs_core.FPnormal
                  ~ifc_external:false ~ifc_can_call:false ~is_atom:false
                  ~readonly:false ~const_function:false);
                 }
               ];
             ft_implicit_params = { capability = (CapDefaults [4:10-11]) };
             ft_ret =
             { et_enforced = false;
               et_type =
               (Rhint (root|at_most_rx_as_func_with_optional_func.php line 7, characters 4-7),
                (Tprim Tbool))
               };
             ft_flags =
             (make_ft_flags FSync None ~return_disposable:false
               ~returns_mutable:false ~returns_void_to_rx:false
               ~returns_readonly:false ~readonly_this:false ~is_const:false);
             ft_reactive = Pure {}; ft_ifc_decl = FDPolicied {PUBLIC} }));
       fe_pos = [4:10-11]; fe_php_std_lib = false }))
  ]

They matched!
