FoldedClass {
    name: "\\C",
    pos: Pos(root|class_const_with_parens.php, 3:7-8),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "X": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|class_const_with_parens.php, 4:13-14),
            ty: int,
            origin: "\\C",
            refs: [],
        },
        "Y": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|class_const_with_parens.php, 5:13-14),
            ty: int,
            origin: "\\C",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|class_const_with_parens.php, 3:7-8),
            ty: HH\classname<this>,
            origin: "\\C",
            refs: [],
        },
    },
}

They matched!
