FoldedClass {
    name: "\\DictConsts",
    pos: Pos(root|classes_const_keyword.php, 4:7-17),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "CDICT": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 5:27-32),
            ty: HH\dict<int, string>,
            origin: "\\DictConsts",
            refs: [],
        },
        "CNESTED_DICT": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 6:38-50),
            ty: HH\dict<int, HH\dict<int, string>>,
            origin: "\\DictConsts",
            refs: [],
        },
        "CNESTED_DICT_FLOAT": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 8:37-55),
            ty: HH\dict<int, HH\dict<int, float>>,
            origin: "\\DictConsts",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 4:7-17),
            ty: HH\classname<this>,
            origin: "\\DictConsts",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\AbstractConsts",
    pos: Pos(root|classes_const_keyword.php, 12:16-30),
    kind: Cclass(
        Abstract,
    ),
    consts: {
        "CABSTRACT_INT": ClassConst {
            is_synthesized: false,
            kind: CCAbstract(
                false,
            ),
            pos: Pos(root|classes_const_keyword.php, 13:22-35),
            ty: int,
            origin: "\\AbstractConsts",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 12:16-30),
            ty: HH\classname<this>,
            origin: "\\AbstractConsts",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\VecConsts",
    pos: Pos(root|classes_const_keyword.php, 16:7-16),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "CNESTED_VEC": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 18:23-34),
            ty: HH\vec<HH\vec<int>>,
            origin: "\\VecConsts",
            refs: [],
        },
        "CVEC": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 17:18-22),
            ty: HH\vec<int>,
            origin: "\\VecConsts",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 16:7-16),
            ty: HH\classname<this>,
            origin: "\\VecConsts",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\ArrayConsts",
    pos: Pos(root|classes_const_keyword.php, 21:7-18),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "CCLASSNAME_KEYSET": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 24:27-44),
            ty: HH\keyset<string>,
            origin: "\\ArrayConsts",
            refs: [],
        },
        "CDARRAY": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 22:29-36),
            ty: HH\dict<string, int>,
            origin: "\\ArrayConsts",
            refs: [],
        },
        "CKEYSET": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 23:24-31),
            ty: HH\keyset<string>,
            origin: "\\ArrayConsts",
            refs: [],
        },
        "CVARRAY": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 25:24-31),
            ty: HH\vec<string>,
            origin: "\\ArrayConsts",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 21:7-18),
            ty: HH\classname<this>,
            origin: "\\ArrayConsts",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\BinopConsts",
    pos: Pos(root|classes_const_keyword.php, 28:7-18),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "CBOOL": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 32:14-19),
            ty: bool,
            origin: "\\BinopConsts",
            refs: [],
        },
        "CFLOAT": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 30:15-21),
            ty: float,
            origin: "\\BinopConsts",
            refs: [],
        },
        "CINT": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 29:13-17),
            ty: int,
            origin: "\\BinopConsts",
            refs: [],
        },
        "CSTRING": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 31:16-23),
            ty: string,
            origin: "\\BinopConsts",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 28:7-18),
            ty: HH\classname<this>,
            origin: "\\BinopConsts",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\ShapeConsts",
    pos: Pos(root|classes_const_keyword.php, 35:7-18),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "CSHAPE": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 36:47-53),
            ty: shape('a' => int, 'b' => string, ...),
            origin: "\\ShapeConsts",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 35:7-18),
            ty: HH\classname<this>,
            origin: "\\ShapeConsts",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\TupleConsts",
    pos: Pos(root|classes_const_keyword.php, 40:7-18),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "COPTION": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 41:33-40),
            ty: (int, ?(string, float)),
            origin: "\\TupleConsts",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 40:7-18),
            ty: HH\classname<this>,
            origin: "\\TupleConsts",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\ClassnameConsts",
    pos: Pos(root|classes_const_keyword.php, 44:7-22),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "CCLASSNAME": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 45:32-42),
            ty: HH\classname<TupleConsts>,
            origin: "\\ClassnameConsts",
            refs: [
                ClassConstRef(
                    From(
                        "\\TupleConsts",
                    ),
                    "class",
                ),
            ],
        },
        "CCLASSNAME2": ClassConst {
            is_synthesized: false,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 46:36-47),
            ty: HH\classname<ClassnameConsts>,
            origin: "\\ClassnameConsts",
            refs: [
                ClassConstRef(
                    Self_,
                    "class",
                ),
            ],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_keyword.php, 44:7-22),
            ty: HH\classname<this>,
            origin: "\\ClassnameConsts",
            refs: [],
        },
    },
}

They matched!
