Parsed decls:

{ Direct_decl_parser.classes =
  { "A" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cabstract;
      sc_name = ([4:16-17], "\\A"); sc_tparams = [];
      sc_where_constraints = []; sc_extends = []; sc_uses = [];
      sc_method_redeclarations = []; sc_xhp_attr_uses = [];
      sc_req_extends = []; sc_req_implements = []; sc_implements = [];
      sc_consts = []; sc_typeconsts = []; sc_pu_enums = [];
      sc_props =
      [{ Shallow_decl_defs.sp_const = true; sp_xhp_attr = None;
         sp_lateinit = false; sp_lsb = false; sp_name = ([5:40-42], "p");
         sp_needs_init = true;
         sp_type =
         (Some (Rhint (root|classes_const_attribute.php line 5, characters 31-38),
                (Tprim Tarraykey)));
         sp_abstract = true; sp_visibility = Public; sp_fixme_codes = {} }
        ];
      sc_sprops = []; sc_constructor = None; sc_static_methods = [];
      sc_methods = []; sc_user_attributes = []; sc_enum_type = None;
      sc_decl_errors = <opaque> };
    "B" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cnormal;
      sc_name = ([8:7-8], "\\B"); sc_tparams = []; sc_where_constraints = [];
      sc_extends =
      [(Rhint (root|classes_const_attribute.php line 8, characters 17-17),
        (Tapply (([8:17-18], "\\A"), [])))];
      sc_uses = []; sc_method_redeclarations = []; sc_xhp_attr_uses = [];
      sc_req_extends = []; sc_req_implements = []; sc_implements = [];
      sc_consts = []; sc_typeconsts = []; sc_pu_enums = [];
      sc_props =
      [{ Shallow_decl_defs.sp_const = true; sp_xhp_attr = None;
         sp_lateinit = false; sp_lsb = false; sp_name = ([9:26-28], "p");
         sp_needs_init = false;
         sp_type =
         (Some (Rhint (root|classes_const_attribute.php line 9, characters 22-24),
                (Tprim Tint)));
         sp_abstract = false; sp_visibility = Public; sp_fixme_codes = {} }
        ];
      sc_sprops = []; sc_constructor = None; sc_static_methods = [];
      sc_methods = []; sc_user_attributes = []; sc_enum_type = None;
      sc_decl_errors = <opaque> } };
  funs = {}; typedefs = {}; consts = {} }

They matched!
