FoldedClass {
    name: "\\C",
    pos: Pos(root|classes_reified_generics.php, 3:7-8),
    kind: Cclass(
        Concrete,
    ),
    tparams: [
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|classes_reified_generics.php, 3:15-16),
                "T",
            ),
            tparams: [],
            constraints: [],
            reified: Reified,
            user_attributes: [],
        },
    ],
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_reified_generics.php, 3:7-8),
            ty: HH\classname<this>,
            origin: "\\C",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\X",
    pos: Pos(root|classes_reified_generics.php, 5:16-17),
    kind: Cclass(
        Abstract,
    ),
    consts: {
        "TFoo": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_reified_generics.php, 7:14-18),
            ty: HH\TypeStructure<this::TFoo>,
            origin: "\\X",
            refs: [],
        },
        "X2": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_reified_generics.php, 9:14-16),
            ty: HH\TypeStructure<this::X2>,
            origin: "\\X",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_reified_generics.php, 5:16-17),
            ty: HH\classname<this>,
            origin: "\\X",
            refs: [],
        },
    },
    type_consts: {
        "TFoo": TypeConst {
            is_synthesized: false,
            name: (
                Pos(root|classes_reified_generics.php, 7:14-18),
                "TFoo",
            ),
            kind: ConcreteTypeconst {
                ty: int,
            },
            origin: "\\X",
            enforceable: None,
            reifiable: Some(
                Pos(root|classes_reified_generics.php, 6:5-16),
            ),
            is_concretized: false,
            is_ctx: false,
        },
        "X2": TypeConst {
            is_synthesized: false,
            name: (
                Pos(root|classes_reified_generics.php, 9:14-16),
                "X2",
            ),
            kind: ConcreteTypeconst {
                ty: C<this::TFoo>,
            },
            origin: "\\X",
            enforceable: None,
            reifiable: None,
            is_concretized: false,
            is_ctx: false,
        },
    },
}

They matched!
