FoldedClass {
    name: "\\A",
    pos: Pos(root|classes_const_attribute.php, 4:16-17),
    kind: Cclass(
        Abstract,
    ),
    props: {
        "p": FoldedElement {
            flags: ABSTRACT | FINAL | CONST | NEEDS_INIT,
            origin: "\\A",
            visibility: Public,
            deprecated: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_attribute.php, 4:16-17),
            ty: HH\classname<this>,
            origin: "\\A",
            refs: [],
        },
    },
    deferred_init_members: {
        "p",
    },
}
FoldedClass {
    name: "\\B",
    pos: Pos(root|classes_const_attribute.php, 8:7-8),
    kind: Cclass(
        Concrete,
    ),
    substs: {
        "\\A": SubstContext {
            subst: Subst(
                {},
            ),
            class_context: "\\B",
            from_req_extends: false,
        },
    },
    ancestors: {
        "\\A": A,
    },
    props: {
        "p": FoldedElement {
            flags: FINAL | CONST,
            origin: "\\B",
            visibility: Public,
            deprecated: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|classes_const_attribute.php, 8:7-8),
            ty: HH\classname<this>,
            origin: "\\B",
            refs: [],
        },
    },
    extends: {
        "\\A",
    },
}

They matched!
