Parsed decls:

{ Direct_decl_parser.classes =
  { "\\E" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cenum;
      sc_name = ([6:6-7], "\\E"); sc_tparams = []; sc_where_constraints = [];
      sc_extends =
      [(Rhint (root|classname.php line 6, characters 6-6),
        (Tapply (([6:6-7], "\\HH\\BuiltinEnum"),
           [(Rhint (root|classname.php line 6, characters 6-6),
             (Tapply (([6:6-7], "\\E"), [])))]
           )))
        ];
      sc_uses = []; sc_xhp_attr_uses = []; sc_req_extends = [];
      sc_req_implements = []; sc_implements = [];
      sc_consts =
      [{ Shallow_decl_defs.scc_abstract = false;
         scc_expr =
         (Some ([7:9-19],
                (Class_const (([7:9-12], (CI ([7:9-12], "\\Foo"))),
                   ([7:14-19], "class")))));
         scc_name = ([7:3-6], "FOO");
         scc_type = (Rnone (| line 0, characters 0-0), Tany) }
        ];
      sc_typeconsts = []; sc_pu_enums = []; sc_props = []; sc_sprops = [];
      sc_constructor = None; sc_static_methods = []; sc_methods = [];
      sc_user_attributes = [];
      sc_enum_type =
      (Some { te_base =
              (Rhint (root|classname.php line 6, characters 9-14),
               (Tprim Tstring));
              te_constraint = None });
      sc_decl_errors = <opaque> };
    "\\Foo" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cnormal;
      sc_name = ([3:7-10], "\\Foo"); sc_tparams = [];
      sc_where_constraints = []; sc_extends = []; sc_uses = [];
      sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
      sc_implements = []; sc_consts = []; sc_typeconsts = [];
      sc_pu_enums = []; sc_props = []; sc_sprops = []; sc_constructor = None;
      sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
      sc_enum_type = None; sc_decl_errors = <opaque> } };
  funs = {}; typedefs = {}; consts = {} }

They matched!
