FoldedClass {
    name: "\\E",
    pos: Pos(root|constraints_mentioning_tparams_in_same_list.php, 3:7-8),
    kind: Cclass(
        Concrete,
    ),
    tparams: [
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 3:9-11),
                "Ta",
            ),
            tparams: [],
            constraints: [],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 3:13-15),
                "Tb",
            ),
            tparams: [],
            constraints: [],
            reified: Erased,
            user_attributes: [],
        },
    ],
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|constraints_mentioning_tparams_in_same_list.php, 3:7-8),
            ty: HH\classname<this>,
            origin: "\\E",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\I",
    pos: Pos(root|constraints_mentioning_tparams_in_same_list.php, 5:11-12),
    kind: Cinterface,
    tparams: [
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 6:3-5),
                "Ta",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    arraykey,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 7:3-5),
                "Tb",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    Ta,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 8:3-5),
                "Tc",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    Td,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 9:3-5),
                "Td",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    E<Ta, Tf>,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 10:3-5),
                "Tf",
            ),
            tparams: [],
            constraints: [],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 11:3-7),
                "Tarr",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    HH\vec<Ta>,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 12:3-8),
                "Tlike",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    ~Ta,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 13:3-7),
                "Topt",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    ?Ta,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 14:3-7),
                "Tfun",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    (function(Ta): Tb),
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 15:3-9),
                "Tshape",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    shape('a' => Ta),
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 16:3-8),
                "Tdarr",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    HH\dict<Ta, Tb>,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 17:3-8),
                "Tvarr",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    HH\vec<Ta>,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 18:3-9),
                "Tvdarr",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    vec_or_dict<Ta, Tb>,
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
        Tparam {
            variance: Invariant,
            name: (
                Pos(root|constraints_mentioning_tparams_in_same_list.php, 19:3-9),
                "Ttuple",
            ),
            tparams: [],
            constraints: [
                (
                    ConstraintAs,
                    (Ta, Tb),
                ),
            ],
            reified: Erased,
            user_attributes: [],
        },
    ],
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|constraints_mentioning_tparams_in_same_list.php, 5:11-12),
            ty: HH\classname<this>,
            origin: "\\I",
            refs: [],
        },
    },
}

They matched!
