FoldedClass {
    name: "\\C",
    pos: Pos(root|ctx_const_lower_bound.php, 3:16-17),
    kind: Cclass(
        Abstract,
    ),
    consts: {
        "C": ClassConst {
            is_synthesized: true,
            kind: CCAbstract(
                false,
            ),
            pos: Pos(root|ctx_const_lower_bound.php, 4:22-23),
            ty: HH\TypeStructure<this::C>,
            origin: "\\C",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|ctx_const_lower_bound.php, 3:16-17),
            ty: HH\classname<this>,
            origin: "\\C",
            refs: [],
        },
    },
    type_consts: {
        "C": TypeConst {
            is_synthesized: false,
            name: (
                Pos(root|ctx_const_lower_bound.php, 4:22-23),
                "C",
            ),
            kind: AbstractTypeconst {
                as_constraint: None,
                super_constraint: Some(
                    &(HH\Contexts\defaults),
                ),
                default: None,
            },
            origin: "\\C",
            enforceable: None,
            reifiable: None,
            is_concretized: false,
            is_ctx: true,
        },
    },
}
FoldedClass {
    name: "\\D",
    pos: Pos(root|ctx_const_lower_bound.php, 7:16-17),
    kind: Cclass(
        Abstract,
    ),
    consts: {
        "C": ClassConst {
            is_synthesized: true,
            kind: CCAbstract(
                true,
            ),
            pos: Pos(root|ctx_const_lower_bound.php, 8:22-23),
            ty: HH\TypeStructure<this::C>,
            origin: "\\D",
            refs: [],
        },
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|ctx_const_lower_bound.php, 7:16-17),
            ty: HH\classname<this>,
            origin: "\\D",
            refs: [],
        },
    },
    type_consts: {
        "C": TypeConst {
            is_synthesized: false,
            name: (
                Pos(root|ctx_const_lower_bound.php, 8:22-23),
                "C",
            ),
            kind: AbstractTypeconst {
                as_constraint: None,
                super_constraint: Some(
                    &(HH\Contexts\defaults),
                ),
                default: Some(
                    &(),
                ),
            },
            origin: "\\D",
            enforceable: None,
            reifiable: None,
            is_concretized: false,
            is_ctx: true,
        },
    },
}

They matched!
