[("\\WithLowerThenUpperBound",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cinterface;
       sc_name = ([3:11-34], "\\WithLowerThenUpperBound"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
       sc_implements = []; sc_implements_dynamic = false; sc_consts = [];
       sc_typeconsts =
       [{ Shallow_decl_defs.stc_abstract = Typing_defs.TCConcrete;
          stc_as_constraint =
          (Some (Rhint ([4:35-39]),
                 (Tintersection
                    [(Rhint ([4:36-38]),
                      (Tapply (([4:36-38], "\\HH\\Contexts\\rx"), [])))])));
          stc_super_constraint =
          (Some (Rhint ([4:21-31]),
                 (Tintersection
                    [(Rhint ([4:22-30]),
                      (Tapply (([4:22-30], "\\HH\\Contexts\\defaults"), [])))
                      ])));
          stc_name = ([4:13-14], "C"); stc_type = None;
          stc_enforceable = ([Pos.none], false); stc_reifiable = None }
         ];
       sc_props = []; sc_sprops = []; sc_constructor = None;
       sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
       sc_enum_type = None }));
  ("\\WithUpperThenLowerBound",
   (Shallow_decl_defs.Class
      { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
        sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cinterface;
        sc_name = ([7:11-34], "\\WithUpperThenLowerBound"); sc_tparams = [];
        sc_where_constraints = []; sc_extends = []; sc_uses = [];
        sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
        sc_implements = []; sc_implements_dynamic = false; sc_consts = [];
        sc_typeconsts =
        [{ Shallow_decl_defs.stc_abstract = Typing_defs.TCConcrete;
           stc_as_constraint =
           (Some (Rhint ([8:18-31]),
                  (Tintersection
                     [(Rhint ([8:19-30]),
                       (Tapply (([8:19-30], "\\HH\\Contexts\\write_props"),
                          [])))
                       ])));
           stc_super_constraint =
           (Some (Rhint ([8:38-48]),
                  (Tintersection
                     [(Rhint ([8:39-47]),
                       (Tapply (([8:39-47], "\\HH\\Contexts\\defaults"), [])))
                       ])));
           stc_name = ([8:13-14], "C"); stc_type = None;
           stc_enforceable = ([Pos.none], false); stc_reifiable = None }
          ];
        sc_props = []; sc_sprops = []; sc_constructor = None;
        sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
        sc_enum_type = None }))
  ]

They matched!
