[("\\I",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cinterface;
       sc_module = None; sc_name = ([3:11-12], "\\I"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_xhp_enum_values = {}; sc_req_extends = [];
       sc_req_implements = []; sc_implements = [];
       sc_support_dynamic_type = false; sc_consts = [];
       sc_typeconsts =
       [{ Shallow_decl_defs.stc_name = ([4:41-42], "T");
          stc_kind =
          (Typing_defs.TCAbstract
             { Typing_defs.atc_as_constraint =
               (Some (Rhint ([4:46-54]), (Tprim Tarraykey)));
               atc_super_constraint = None; atc_default = None });
          stc_enforceable = ([4:5-18], true); stc_reifiable = None;
          stc_is_ctx = false }
         ];
       sc_props = []; sc_sprops = []; sc_constructor = None;
       sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
       sc_enum_type = None }))
  ]

They matched!
