[("\\E",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = Cenum; sc_module = None;
       sc_name = ([4:6-7], "\\E"); sc_tparams = [];
       sc_where_constraints = [];
       sc_extends =
       [(Rhint ([4:6-7]),
         (Tapply (([4:6-7], "\\HH\\BuiltinEnum"),
            [(Rhint ([4:6-7]), (Tapply (([4:6-7], "\\E"), [])))])))
         ];
       sc_uses = []; sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = []; sc_implements = [];
       sc_support_dynamic_type = false;
       sc_consts =
       [{ Shallow_decl_defs.scc_abstract = Typing_defs.CCConcrete;
          scc_name = ([5:3-4], "A");
          scc_type = (Rwitness_from_decl ([5:7-10]), (Tprim Tstring));
          scc_refs = []; scc_value = None };
         { Shallow_decl_defs.scc_abstract = Typing_defs.CCConcrete;
           scc_name = ([6:3-4], "B");
           scc_type = (Rwitness_from_decl ([6:7-10]), (Tprim Tstring));
           scc_refs = []; scc_value = None }
         ];
       sc_typeconsts = []; sc_props = []; sc_sprops = [];
       sc_constructor = None; sc_static_methods = []; sc_methods = [];
       sc_user_attributes =
       [{ Typing_defs_core.ua_name = ([3:18-21], "\\Bar"); ua_params = [] };
         { Typing_defs_core.ua_name = ([3:3-6], "\\Foo");
           ua_params =
           [(Typing_defs_core.String "a"); (Typing_defs_core.String "b")] }
         ];
       sc_enum_type =
       (Some { Typing_defs.te_base = (Rhint ([4:10-16]), (Tprim Tstring));
               te_constraint = None; te_includes = [] });
       sc_docs_url = None }))
  ]
