[("\\A",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
       sc_module = None; sc_name = ([3:7-8], "\\A"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = [];
       sc_implements =
       [(Rhint ([3:20-37]),
         (Tapply (([3:20-37], "\\HH\\ClassAttribute"), [])))];
       sc_support_dynamic_type = false; sc_consts = []; sc_typeconsts = [];
       sc_props =
       [{ Shallow_decl_defs.sp_name = ([4:49-51], "i"); sp_xhp_attr = None;
          sp_type =
          (Rhint ([4:38-48]),
           (Tapply (([4:38-41], "\\HH\\vec"), [(Rhint ([4:42-47]), Tmixed)])));
          sp_visibility = Public; sp_flags = needs_init }
         ];
       sc_sprops = [];
       sc_constructor =
       (Some { Shallow_decl_defs.sm_name = ([4:19-30], "__construct");
               sm_type =
               (Rwitness_from_decl ([4:19-30]),
                (Tfun
                   { ft_tparams = []; ft_where_constraints = [];
                     ft_params =
                     [{ fp_pos = [4:49-51]; fp_name = (Some "$i");
                        fp_type =
                        { et_enforced = Typing_defs_core.Unenforced;
                          et_type =
                          (Rhint ([4:38-48]),
                           (Tapply (([4:38-41], "\\HH\\vec"),
                              [(Rhint ([4:42-47]), Tmixed)])))
                          };
                        fp_flags =
                        (make_fp_flags ~accept_disposable:false
                          ~has_default:false ~mode:Typing_defs_core.FPnormal
                          ~ifc_external:false ~ifc_can_call:false
                          ~readonly:false);
                         }
                       ];
                     ft_implicit_params =
                     { capability = (CapDefaults [4:19-30]) };
                     ft_ret =
                     { et_enforced = Typing_defs_core.Unenforced;
                       et_type =
                       (Rwitness_from_decl ([4:19-30]), (Tprim Tvoid)) };
                     ft_flags =
                     { Typing_defs_flags.Fun.return_disposable = false;
                       async = false; generator = false; fun_kind = FSync;
                       instantiated_targs = false;
                       is_function_pointer = false; returns_readonly = false;
                       readonly_this = false; support_dynamic_type = false;
                       is_memoized = false; variadic = false };
                     ft_ifc_decl = FDPolicied {PUBLIC};
                     ft_cross_package = None }));
               sm_visibility = Public; sm_deprecated = None;
               sm_flags = (empty); sm_attributes = [] });
       sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
       sc_enum_type = None; sc_docs_url = None }));
  ("\\Foo",
   (Shallow_decl_defs.Class
      { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
        sc_abstract = false; sc_is_xhp = false; sc_internal = false;
        sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
        sc_module = None; sc_name = ([8:7-10], "\\Foo"); sc_tparams = [];
        sc_where_constraints = []; sc_extends = []; sc_uses = [];
        sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
        sc_xhp_marked_empty = false; sc_req_extends = [];
        sc_req_implements = []; sc_req_class = []; sc_implements = [];
        sc_support_dynamic_type = false;
        sc_consts =
        [{ Shallow_decl_defs.scc_abstract = Typing_defs.CCConcrete;
           scc_name = ([9:16-19], "KEY");
           scc_type = (Rhint ([9:9-15]), (Tprim Tstring)); scc_refs = [] }
          ];
        sc_typeconsts = []; sc_props = []; sc_sprops = [];
        sc_constructor = None; sc_static_methods = []; sc_methods = [];
        sc_user_attributes =
        [{ Typing_defs_core.ua_name = ([7:3-4], "\\A"); ua_params = [] }];
        sc_enum_type = None; sc_docs_url = None }));
  ("\\Bar",
   (Shallow_decl_defs.Class
      { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
        sc_abstract = false; sc_is_xhp = false; sc_internal = false;
        sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
        sc_module = None; sc_name = ([15:7-10], "\\Bar"); sc_tparams = [];
        sc_where_constraints = []; sc_extends = []; sc_uses = [];
        sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
        sc_xhp_marked_empty = false; sc_req_extends = [];
        sc_req_implements = []; sc_req_class = []; sc_implements = [];
        sc_support_dynamic_type = false; sc_consts = []; sc_typeconsts = [];
        sc_props = []; sc_sprops = []; sc_constructor = None;
        sc_static_methods = []; sc_methods = [];
        sc_user_attributes =
        [{ Typing_defs_core.ua_name = ([12:3-4], "\\A"); ua_params = [] }];
        sc_enum_type = None; sc_docs_url = None }))
  ]
