FoldedClass {
    name: "\\C",
    pos: Pos(root|memoize_lsb.php, 3:13-14),
    kind: Cclass(
        Concrete,
    ),
    is_final: true,
    static_methods: {
        "f": FoldedElement {
            flags: (empty),
            origin: "\\C",
            visibility: Public,
            deprecated: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|memoize_lsb.php, 3:13-14),
            ty: HH\classname<this>,
            origin: "\\C",
            refs: [],
        },
    },
}

They matched!
