File root|module_attr.php--module_here.php
[("here",
  (Shallow_decl_defs.Module
     { Typing_defs.mdt_pos = [2:12-16]; mdt_exports = None;
       mdt_imports = None }))
  ]

File root|module_attr.php--module_there.php
[("there",
  (Shallow_decl_defs.Module
     { Typing_defs.mdt_pos = [2:12-17]; mdt_exports = None;
       mdt_imports = None }))
  ]

File root|module_attr.php--module_elsewhere.php
[("elsewhere",
  (Shallow_decl_defs.Module
     { Typing_defs.mdt_pos = [2:12-21]; mdt_exports = None;
       mdt_imports = None }))
  ]

File root|module_attr.php--here.php
[("\\foo",
  (Shallow_decl_defs.Fun
     { Typing_defs.fe_deprecated = None;
       fe_module = (Some ([2:8-12], "here")); fe_internal = false;
       fe_type =
       (Rwitness_from_decl ([4:10-13]),
        (Tfun
           { ft_tparams = []; ft_where_constraints = []; ft_params = [];
             ft_implicit_params = { capability = (CapDefaults [4:10-13]) };
             ft_ret = (Rhint ([4:16-20]), (Tprim Tvoid));
             ft_flags =
             { Typing_defs_flags.Fun.return_disposable = false;
               async = false; generator = false; fun_kind = FSync;
               instantiated_targs = false; is_function_pointer = false;
               returns_readonly = false; readonly_this = false;
               support_dynamic_type = false; is_memoized = false;
               variadic = false };
             ft_cross_package = None }));
       fe_pos = [4:10-13]; fe_php_std_lib = false;
       fe_support_dynamic_type = false; fe_no_auto_dynamic = false;
       fe_no_auto_likes = false }));
  ("\\Talias",
   (Shallow_decl_defs.Typedef
      { Typing_defs.td_module = (Some ([2:8-12], "here")); td_pos = [6:6-12];
        td_vis = Transparent; td_tparams = []; td_as_constraint = None;
        td_super_constraint = None;
        td_type = (Rhint ([6:15-18]), (Tprim Tint)); td_is_ctx = false;
        td_attributes = []; td_internal = false; td_docs_url = None }));
  ("\\Topaque",
   (Shallow_decl_defs.Typedef
      { Typing_defs.td_module = (Some ([2:8-12], "here")); td_pos = [8:9-16];
        td_vis = Opaque; td_tparams = []; td_as_constraint = None;
        td_super_constraint = None;
        td_type = (Rhint ([8:19-25]), (Tprim Tstring)); td_is_ctx = false;
        td_attributes = []; td_internal = false; td_docs_url = None }))
  ]

File root|module_attr.php--there.php
[("\\C",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
       sc_module = (Some ([2:8-13], "there")); sc_name = ([4:7-8], "\\C");
       sc_tparams = []; sc_where_constraints = []; sc_extends = [];
       sc_uses = []; sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = []; sc_implements = [];
       sc_support_dynamic_type = false; sc_consts = []; sc_typeconsts = [];
       sc_props = []; sc_sprops = []; sc_constructor = None;
       sc_static_methods = [];
       sc_methods =
       [{ Shallow_decl_defs.sm_name = ([5:19-22], "bar");
          sm_type =
          (Rwitness_from_decl ([5:19-22]),
           (Tfun
              { ft_tparams = []; ft_where_constraints = []; ft_params = [];
                ft_implicit_params = { capability = (CapDefaults [5:19-22]) };
                ft_ret = (Rhint ([5:25-29]), (Tprim Tvoid));
                ft_flags =
                { Typing_defs_flags.Fun.return_disposable = false;
                  async = false; generator = false; fun_kind = FSync;
                  instantiated_targs = false; is_function_pointer = false;
                  returns_readonly = false; readonly_this = false;
                  support_dynamic_type = false; is_memoized = false;
                  variadic = false };
                ft_cross_package = None }));
          sm_visibility = Public; sm_deprecated = None;
          sm_flags =
          { Shallow_decl_defs.MethodFlags.abstract = false; final = false;
            override = false; dynamicallycallable = false;
            php_std_lib = false; support_dynamic_type = false };
          sm_attributes = []; sm_sort_text = None }
         ];
       sc_user_attributes = []; sc_enum_type = None; sc_docs_url = None }))
  ]

File root|module_attr.php--elsewhere.php
[("\\E",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = Cenum;
       sc_module = (Some ([2:8-17], "elsewhere"));
       sc_name = ([5:6-7], "\\E"); sc_tparams = [];
       sc_where_constraints = [];
       sc_extends =
       [(Rhint ([5:6-7]),
         (Tapply (([5:6-7], "\\HH\\BuiltinEnum"),
            [(Rhint ([5:6-7]), (Tapply (([5:6-7], "\\E"), [])))])))
         ];
       sc_uses = []; sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = []; sc_implements = [];
       sc_support_dynamic_type = false;
       sc_consts =
       [{ Shallow_decl_defs.scc_abstract = Typing_defs.CCConcrete;
          scc_name = ([6:3-4], "A");
          scc_type = (Rwitness_from_decl ([6:7-8]), (Tprim Tint));
          scc_refs = []; scc_value = None }
         ];
       sc_typeconsts = []; sc_props = []; sc_sprops = [];
       sc_constructor = None; sc_static_methods = []; sc_methods = [];
       sc_user_attributes = [];
       sc_enum_type =
       (Some { Typing_defs.te_base = (Rhint ([5:10-13]), (Tprim Tint));
               te_constraint = None; te_includes = [] });
       sc_docs_url = None }))
  ]
