File root|module_static_prop.php--modules.php


File root|module_static_prop.php--A.php
FoldedClass {
    name: "\\A",
    pos: Pos(root|module_static_prop.php--A.php, 6:7-8),
    kind: Cclass(
        Concrete,
    ),
    module: (
        Pos(root|module_static_prop.php--A.php, 4:54-57),
        "A",
    ),
    static_props: {
        "$x": FoldedElement {
            flags: FINAL,
            origin: "\\A",
            visibility: Internal(
                "A",
            ),
            deprecated: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|module_static_prop.php--A.php, 6:7-8),
            ty: HH\classname<this>,
            origin: "\\A",
            refs: [],
        },
    },
}

File root|module_static_prop.php--B.php


File root|module_static_prop.php--no-module.php


They matched!
