File root|module_methods.php--modules.php
[("A",
  (Shallow_decl_defs.Module
     { Typing_defs.mdt_pos = [4:12-13]; mdt_exports = None;
       mdt_imports = None }))
  ]

File root|module_methods.php--A.php
[("\\A",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
       sc_module = (Some ([5:8-9], "A")); sc_name = ([7:7-8], "\\A");
       sc_tparams = []; sc_where_constraints = []; sc_extends = [];
       sc_uses = []; sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = []; sc_implements = [];
       sc_support_dynamic_type = false; sc_consts = []; sc_typeconsts = [];
       sc_props = []; sc_sprops = []; sc_constructor = None;
       sc_static_methods = [];
       sc_methods =
       [{ Shallow_decl_defs.sm_name = ([8:21-22], "f");
          sm_type =
          (Rwitness_from_decl ([8:21-22]),
           (Tfun
              { ft_tparams = []; ft_where_constraints = []; ft_params = [];
                ft_implicit_params = { capability = (CapDefaults [8:21-22]) };
                ft_ret =
                { et_enforced = Typing_defs_core.Unenforced;
                  et_type = (Rhint ([8:26-30]), (Tprim Tvoid)) };
                ft_flags =
                { Typing_defs_flags.Fun.return_disposable = false;
                  async = false; generator = false; fun_kind = FSync;
                  instantiated_targs = false; is_function_pointer = false;
                  returns_readonly = false; readonly_this = false;
                  support_dynamic_type = false; is_memoized = false;
                  variadic = false };
                ft_ifc_decl = (FDPolicied (Some "PUBLIC"));
                ft_cross_package = None }));
          sm_visibility = Internal; sm_deprecated = None; sm_flags = (empty);
          sm_attributes = [] }
         ];
       sc_user_attributes = []; sc_enum_type = None; sc_docs_url = None }))
  ]

File root|module_methods.php--main.php
[("\\main",
  (Shallow_decl_defs.Fun
     { Typing_defs.fe_deprecated = None; fe_module = None;
       fe_internal = false;
       fe_type =
       (Rwitness_from_decl ([4:10-14]),
        (Tfun
           { ft_tparams = []; ft_where_constraints = []; ft_params = [];
             ft_implicit_params = { capability = (CapDefaults [4:10-14]) };
             ft_ret =
             { et_enforced = Typing_defs_core.Unenforced;
               et_type = (Rhint ([4:18-22]), (Tprim Tvoid)) };
             ft_flags =
             { Typing_defs_flags.Fun.return_disposable = false;
               async = false; generator = false; fun_kind = FSync;
               instantiated_targs = false; is_function_pointer = false;
               returns_readonly = false; readonly_this = false;
               support_dynamic_type = false; is_memoized = false;
               variadic = false };
             ft_ifc_decl = (FDPolicied (Some "PUBLIC"));
             ft_cross_package = None }));
       fe_pos = [4:10-14]; fe_php_std_lib = false;
       fe_support_dynamic_type = false; fe_no_auto_dynamic = false;
       fe_no_auto_likes = false }))
  ]
