File root|module_static_prop.php--A.php
{ Decl_defs.dc_need_init = false; dc_abstract = false; dc_final = false;
  dc_const = false; dc_internal = false; dc_deferred_init_members = {};
  dc_kind = (Cclass Concrete); dc_is_xhp = false; dc_has_xhp_keyword = false;
  dc_module = (Some ([4:54-57], "A")); dc_name = "\\A"; dc_pos = [6:7-8];
  dc_tparams = []; dc_where_constraints = []; dc_substs = {};
  dc_consts =
  { "class" ->
    { Typing_defs.cc_synthesized = true;
      cc_abstract = Typing_defs.CCConcrete; cc_pos = [6:7-8];
      cc_type =
      (Rclass_class ([6:7-8]),
       (Tapply (([6:7-8], "\\HH\\classname"),
          [(Rclass_class ([6:7-8]), Tthis)])));
      cc_origin = "\\A"; cc_refs = [] } };
  dc_typeconsts = {}; dc_props = {};
  dc_sprops =
  { "$x" ->
    { Decl_defs.elt_flags =
      { "Abstract" -> false;
        "Const" -> false;
        "Dynamicallycallable" -> false;
        "Final" -> true;
        "Lateinit" -> false;
        "Lsb" -> false;
        "NeedsInit" -> false;
        "ReadonlyProp" -> false;
        "SuperfluousOverride" -> false;
        "SupportDynamicType" -> false;
        "Synthesized" -> false;
        "XaHasDefault" -> false;
        "XaTagLateinit" -> false;
        "XaTagRequired" -> false };
      elt_origin = "\\A"; elt_visibility = (Typing_defs_core.Vinternal "A");
      elt_deprecated = None } };
  dc_methods = {}; dc_smethods = {};
  dc_construct = (None, Typing_defs_core.Inconsistent); dc_ancestors = {};
  dc_support_dynamic_type = false; dc_req_ancestors = [];
  dc_req_ancestors_extends = {}; dc_extends = {}; dc_sealed_whitelist = None;
  dc_xhp_attr_deps = {}; dc_xhp_enum_values = {}; dc_enum_type = None;
  dc_decl_errors = <opaque>; dc_condition_types = {} }

File root|module_static_prop.php--B.php


File root|module_static_prop.php--no-module.php


They matched!
