The following class(es) differed between the legacy and parsed versions:


[C]
--- legacy
+++ parsed
@@ -1,11 +1,11 @@
 { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false; sc_is_xhp = false;
   sc_has_xhp_keyword = false; sc_kind = Cnormal; sc_name = ([7:7-8], "\\C");
   sc_tparams = []; sc_where_constraints = []; sc_extends = []; sc_uses = [];
   sc_method_redeclarations = []; sc_xhp_attr_uses = []; sc_req_extends = [];
   sc_req_implements = []; sc_implements = []; sc_consts = [];
   sc_typeconsts = []; sc_pu_enums = []; sc_props = []; sc_sprops = [];
   sc_constructor = None; sc_static_methods = []; sc_methods = [];
   sc_user_attributes =
-  [{ ua_name = ([6:8-11], "\\Bar"); ua_params = [] };
-    { ua_name = ([6:3-6], "\\Foo"); ua_params = [] }];
+  [{ ua_name = ([6:8-11], "Bar"); ua_params = [] };
+    { ua_name = ([6:3-6], "Foo"); ua_params = [] }];
   sc_enum_type = None; sc_decl_errors = <opaque> }
\ No newline at end of file
