[("\\A",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cnormal;
       sc_name = ([3:7-8], "\\A"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
       sc_implements = []; sc_implements_dynamic = false; sc_consts = [];
       sc_typeconsts = []; sc_props = []; sc_sprops = [];
       sc_constructor = None; sc_static_methods = []; sc_methods = [];
       sc_user_attributes = []; sc_enum_type = None }));
  ("\\f",
   (Shallow_decl_defs.Fun
      { Typing_defs.fe_deprecated = None;
        fe_type =
        (Rwitness (root|mutable_as_hint1.php line 7, characters 10-10),
         (Tfun
            { ft_arity = (Fstandard ()); ft_tparams = [];
              ft_where_constraints = [];
              ft_params =
              [{ fp_pos = [7:23-25]; fp_name = (Some "$a");
                 fp_type =
                 { et_enforced = false;
                   et_type =
                   (Rhint (root|mutable_as_hint1.php line 7, characters 20-20),
                    (Tapply (([7:20-21], "\\A"), [])))
                   };
                 fp_rx_annotation = None;
                 fp_flags =
                 (make_fp_flags ~mutability:None ~accept_disposable:false
                   ~has_default:false ~mode:Typing_defs_core.FPnormal
                   ~ifc_external:false ~ifc_can_call:false ~is_atom:false
                   ~readonly:false);
                  }
                ];
              ft_implicit_params = { capability = (CapDefaults [7:10-11]) };
              ft_ret =
              { et_enforced = false;
                et_type =
                (Rhint (root|mutable_as_hint1.php line 7, characters 28-31),
                 (Tprim Tvoid))
                };
              ft_flags =
              (make_ft_flags FSync None ~return_disposable:false
                ~returns_mutable:false ~returns_void_to_rx:false
                ~returns_readonly:false ~readonly_this:false);
              ft_reactive = Reactive {}; ft_ifc_decl = FDPolicied {PUBLIC} }));
        fe_pos = [7:10-11]; fe_php_std_lib = false }))
  ]

They matched!
