FoldedClass {
    name: "\\NS1\\NS2\\C",
    pos: Pos(root|namespace_import.php, 8:13-14),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|namespace_import.php, 8:13-14),
            ty: HH\classname<this>,
            origin: "\\NS1\\NS2\\C",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\D",
    pos: Pos(root|namespace_import.php, 19:9-10),
    kind: Cclass(
        Concrete,
    ),
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: Pos(root|namespace_import.php, 19:9-10),
            ty: HH\classname<this>,
            origin: "\\D",
            refs: [],
        },
    },
    sealed_whitelist: {
        "\\NS1\\NS2\\C",
    },
}

They matched!
