[("\\id",
  (Shallow_decl_defs.Fun
     { Typing_defs.fe_deprecated = None; fe_module = None;
       fe_internal = false;
       fe_type =
       (Rwitness_from_decl ([31:10-12]),
        (Tfun
           { ft_tparams = []; ft_where_constraints = [];
             ft_params =
             [{ fp_pos = [31:20-22]; fp_name = (Some "$x");
                fp_type =
                { et_enforced = Typing_defs_core.Unenforced;
                  et_type =
                  (Rhint ([31:13-19]),
                   (Tapply (([31:13-19], "\\MyNamespace\\MyType"), [])))
                  };
                fp_flags =
                { Typing_defs_flags.FunParam.accept_disposable = false;
                  inout = false; has_default = false; ifc_external = false;
                  ifc_can_call = false; readonly = false };
                 }
               ];
             ft_implicit_params = { capability = (CapDefaults [31:10-12]) };
             ft_ret =
             { et_enforced = Typing_defs_core.Unenforced;
               et_type =
               (Rhint ([31:25-32]),
                (Tapply (([31:25-32], "\\MyNamespace\\MyType"), [])))
               };
             ft_flags =
             { Typing_defs_flags.Fun.return_disposable = false;
               async = false; generator = false; fun_kind = FSync;
               instantiated_targs = false; is_function_pointer = false;
               returns_readonly = false; readonly_this = false;
               support_dynamic_type = false; is_memoized = false;
               variadic = false };
             ft_ifc_decl = FDPolicied {PUBLIC}; ft_cross_package = None }));
       fe_pos = [31:10-12]; fe_php_std_lib = false;
       fe_support_dynamic_type = false; fe_no_auto_dynamic = false;
       fe_no_auto_likes = false }));
  ("\\other_id",
   (Shallow_decl_defs.Fun
      { Typing_defs.fe_deprecated = None; fe_module = None;
        fe_internal = false;
        fe_type =
        (Rwitness_from_decl ([35:10-18]),
         (Tfun
            { ft_tparams = []; ft_where_constraints = [];
              ft_params =
              [{ fp_pos = [35:31-33]; fp_name = (Some "$x");
                 fp_type =
                 { et_enforced = Typing_defs_core.Unenforced;
                   et_type =
                   (Rhint ([35:19-30]),
                    (Tapply (([35:19-30], "\\MyNamespace\\MyOtherType"), [])))
                   };
                 fp_flags =
                 { Typing_defs_flags.FunParam.accept_disposable = false;
                   inout = false; has_default = false; ifc_external = false;
                   ifc_can_call = false; readonly = false };
                  }
                ];
              ft_implicit_params = { capability = (CapDefaults [35:10-18]) };
              ft_ret =
              { et_enforced = Typing_defs_core.Unenforced;
                et_type =
                (Rhint ([35:36-48]),
                 (Tapply (([35:36-48], "\\MyNamespace\\MyOtherType"), [])))
                };
              ft_flags =
              { Typing_defs_flags.Fun.return_disposable = false;
                async = false; generator = false; fun_kind = FSync;
                instantiated_targs = false; is_function_pointer = false;
                returns_readonly = false; readonly_this = false;
                support_dynamic_type = false; is_memoized = false;
                variadic = false };
              ft_ifc_decl = FDPolicied {PUBLIC}; ft_cross_package = None }));
        fe_pos = [35:10-18]; fe_php_std_lib = false;
        fe_support_dynamic_type = false; fe_no_auto_dynamic = false;
        fe_no_auto_likes = false }));
  ("\\braced_id",
   (Shallow_decl_defs.Fun
      { Typing_defs.fe_deprecated = None; fe_module = None;
        fe_internal = false;
        fe_type =
        (Rwitness_from_decl ([39:10-19]),
         (Tfun
            { ft_tparams = []; ft_where_constraints = [];
              ft_params =
              [{ fp_pos = [39:33-35]; fp_name = (Some "$x");
                 fp_type =
                 { et_enforced = Typing_defs_core.Unenforced;
                   et_type =
                   (Rhint ([39:20-32]),
                    (Tapply (([39:20-32], "\\MyNamespace\\MyBracedType"), 
                       [])))
                   };
                 fp_flags =
                 { Typing_defs_flags.FunParam.accept_disposable = false;
                   inout = false; has_default = false; ifc_external = false;
                   ifc_can_call = false; readonly = false };
                  }
                ];
              ft_implicit_params = { capability = (CapDefaults [39:10-19]) };
              ft_ret =
              { et_enforced = Typing_defs_core.Unenforced;
                et_type =
                (Rhint ([39:38-51]),
                 (Tapply (([39:38-51], "\\MyNamespace\\MyBracedType"), [])))
                };
              ft_flags =
              { Typing_defs_flags.Fun.return_disposable = false;
                async = false; generator = false; fun_kind = FSync;
                instantiated_targs = false; is_function_pointer = false;
                returns_readonly = false; readonly_this = false;
                support_dynamic_type = false; is_memoized = false;
                variadic = false };
              ft_ifc_decl = FDPolicied {PUBLIC}; ft_cross_package = None }));
        fe_pos = [39:10-19]; fe_php_std_lib = false;
        fe_support_dynamic_type = false; fe_no_auto_dynamic = false;
        fe_no_auto_likes = false }))
  ]
