Parsed decls:

{ Direct_decl_parser.classes =
  { "\\C" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cabstract;
      sc_name = ([3:16-17], "\\C"); sc_tparams = [];
      sc_where_constraints = []; sc_extends = []; sc_uses = [];
      sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
      sc_implements = []; sc_consts = [];
      sc_typeconsts =
      [{ Shallow_decl_defs.stc_abstract = TCPartiallyAbstract;
         stc_constraint =
         (Some (Rhint (root|partially_abstract_type_const.php line 4, characters 19-23),
                Tmixed));
         stc_name = ([4:14-15], "T");
         stc_type =
         (Some (Rhint (root|partially_abstract_type_const.php line 4, characters 27-29),
                (Tprim Tnum)));
         stc_enforceable = ([Pos.none], false); stc_reifiable = None }
        ];
      sc_pu_enums = []; sc_props = []; sc_sprops = []; sc_constructor = None;
      sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
      sc_enum_type = None } };
  funs = {}; typedefs = {}; consts = {} }

They matched!
