[("\\C",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
       sc_module = None; sc_name = ([3:7-8], "\\C"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = []; sc_implements = [];
       sc_support_dynamic_type = false; sc_consts = []; sc_typeconsts = [];
       sc_props = [];
       sc_sprops =
       [{ Shallow_decl_defs.sp_name = ([4:16-18], "$b"); sp_xhp_attr = None;
          sp_type =
          (Rhint ([4:10-15]), (Toption (Rhint ([4:11-15]), (Tprim Tbool))));
          sp_visibility = Public;
          sp_flags =
          { Shallow_decl_defs.PropFlags.abstract = false; const = false;
            lateinit = false; lsb = false; needs_init = true;
            php_std_lib = false; readonly = false;
            safe_global_variable = false; no_auto_likes = false }
          }
         ];
       sc_constructor = None; sc_static_methods = []; sc_methods = [];
       sc_user_attributes = []; sc_enum_type = None; sc_docs_url = None }))
  ]
