[("\\A",
  (Shallow_decl_defs.Record
     { Typing_defs.rdt_module = None; rdt_name = ([3:8-9], "\\A");
       rdt_extends = None;
       rdt_fields =
       [(([4:7-8], "x"), Typing_defs.ValueRequired);
         (([5:7-8], "y"), Typing_defs.HasDefaultValue)];
       rdt_abstract = false; rdt_pos = [3:1-6:2] }));
  ("\\B",
   (Shallow_decl_defs.Record
      { Typing_defs.rdt_module = None; rdt_name = ([8:17-18], "\\B");
        rdt_extends = None;
        rdt_fields = [(([9:7-8], "b"), Typing_defs.ValueRequired)];
        rdt_abstract = true; rdt_pos = [8:1-10:2] }))
  ]

They matched!
