[("\\f",
  (Shallow_decl_defs.Fun
     { Typing_defs.fe_deprecated = None;
       fe_type =
       (Rwitness (root|returns_void_to_rx.php line 4, characters 10-10),
        (Tfun
           { ft_arity = (Fstandard ()); ft_tparams = [];
             ft_where_constraints = []; ft_params = [];
             ft_implicit_params =
             { capability =
               (Rhint (root|returns_void_to_rx.php line 4, characters 10-10),
                (Tunion []))
               };
             ft_ret =
             { et_enforced = false;
               et_type =
               (Rhint (root|returns_void_to_rx.php line 4, characters 15-18),
                (Tprim Tvoid))
               };
             ft_flags =
             (make_ft_flags FSync None ~return_disposable:false
               ~returns_mutable:false ~returns_void_to_rx:true);
             ft_reactive = Nonreactive; ft_ifc_decl = FDPolicied {PUBLIC} }));
       fe_pos = [4:10-11]; fe_php_std_lib = false }))
  ]

They matched!
