[("\\C",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mpartial; sc_final = false;
       sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cnormal;
       sc_name = ([3:7-8], "\\C"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
       sc_implements = []; sc_implements_dynamic = false; sc_consts = [];
       sc_typeconsts = []; sc_props = []; sc_sprops = [];
       sc_constructor = None; sc_static_methods = [];
       sc_methods =
       [{ Shallow_decl_defs.sm_abstract = false; sm_final = false;
          sm_name = ([5:19-20], "a"); sm_override = false;
          sm_dynamicallycallable = false;
          sm_reactivity = (Some (Decl_defs.Method_reactive None));
          sm_type =
          (Rwitness (root|self_param_mutability.php line 5, characters 19-19),
           (Tfun
              { ft_arity = (Fstandard ()); ft_tparams = [];
                ft_where_constraints = []; ft_params = [];
                ft_implicit_params =
                { capability =
                  (Rhint (root|self_param_mutability.php line 5, characters 19-19),
                   (Tapply (([5:19-20], "\\HH\\Contexts\\defaults"), [])))
                  };
                ft_ret =
                { et_enforced = false;
                  et_type =
                  (Rhint (root|self_param_mutability.php line 5, characters 24-27),
                   (Tprim Tvoid))
                  };
                ft_flags =
                (make_ft_flags FSync
                  (Some Typing_defs_core.Param_borrowed_mutable)
                  ~return_disposable:false ~returns_mutable:false
                  ~returns_void_to_rx:false);
                ft_reactive = Reactive {}; ft_ifc_decl = FDPolicied {PUBLIC}
                }));
          sm_visibility = Public; sm_deprecated = None };
         { Shallow_decl_defs.sm_abstract = false; sm_final = false;
           sm_name = ([8:19-20], "b"); sm_override = false;
           sm_dynamicallycallable = false;
           sm_reactivity = (Some (Decl_defs.Method_reactive None));
           sm_type =
           (Rwitness (root|self_param_mutability.php line 8, characters 19-19),
            (Tfun
               { ft_arity = (Fstandard ()); ft_tparams = [];
                 ft_where_constraints = []; ft_params = [];
                 ft_implicit_params =
                 { capability =
                   (Rhint (root|self_param_mutability.php line 8, characters 19-19),
                    (Tapply (([8:19-20], "\\HH\\Contexts\\defaults"), [])))
                   };
                 ft_ret =
                 { et_enforced = false;
                   et_type =
                   (Rhint (root|self_param_mutability.php line 8, characters 24-27),
                    (Tprim Tvoid))
                   };
                 ft_flags =
                 (make_ft_flags FSync
                   (Some Typing_defs_core.Param_maybe_mutable)
                   ~return_disposable:false ~returns_mutable:false
                   ~returns_void_to_rx:false);
                 ft_reactive = Reactive {}; ft_ifc_decl = FDPolicied {PUBLIC}
                 }));
           sm_visibility = Public; sm_deprecated = None }
         ];
       sc_user_attributes = []; sc_enum_type = None }))
  ]

They matched!
