Parsed decls:

{ Direct_decl_parser.classes =
  { "\\TestClass" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cnormal;
      sc_name = ([3:7-16], "\\TestClass"); sc_tparams = [];
      sc_where_constraints = []; sc_extends = []; sc_uses = [];
      sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
      sc_implements = [];
      sc_consts =
      [{ Shallow_decl_defs.scc_abstract = false;
         scc_name = ([4:16-19], "KEY");
         scc_type =
         (Rhint (root|shape_self.php line 4, characters 9-14),
          (Tprim Tstring))
         }
        ];
      sc_typeconsts =
      [{ Shallow_decl_defs.stc_abstract = TCConcrete; stc_constraint = None;
         stc_name = ([6:14-24], "TClassType");
         stc_type =
         (Some (Rhint (root|shape_self.php line 6, characters 27-58),
                (Tshape (Closed_shape,
                   { (SFclass_const (([7:5-9], "\\TestClass"),
                        ([7:11-14], "KEY"))) ->
                     { sft_optional = false;
                       sft_ty =
                       (Rhint (root|shape_self.php line 7, characters 18-20),
                        (Tprim Tint))
                       } }
                   ))));
         stc_enforceable = ([Pos.none], false); stc_reifiable = None }
        ];
      sc_pu_enums = []; sc_props = []; sc_sprops = []; sc_constructor = None;
      sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
      sc_enum_type = None } };
  funs = {}; typedefs = {}; consts = {} }

They matched!
