[("\\f",
  (Shallow_decl_defs.Fun
     { Typing_defs.fe_deprecated = None; fe_module = None;
       fe_internal = false;
       fe_type =
       (Rwitness_from_decl ([3:10-11]),
        (Tfun
           { ft_arity = (Fstandard ()); ft_tparams = [];
             ft_where_constraints = [];
             ft_params =
             [{ fp_pos = [3:27-29]; fp_name = (Some "$x");
                fp_type =
                { et_enforced = Typing_defs_core.Unenforced;
                  et_type = (Rhint ([3:23-26]), (Tprim Tint)) };
                fp_flags =
                (make_fp_flags ~accept_disposable:false ~has_default:false
                  ~mode:Typing_defs_core.FPnormal ~ifc_external:false
                  ~ifc_can_call:false ~via_label:false ~readonly:false);
                 }
               ];
             ft_implicit_params = { capability = (CapDefaults [3:10-11]) };
             ft_ret =
             { et_enforced = Typing_defs_core.Unenforced;
               et_type = (Rhint ([3:32-46]), (Tprim Tint)) };
             ft_flags =
             (make_ft_flags FSync ~return_disposable:false
               ~returns_readonly:false ~readonly_this:false);
             ft_ifc_decl = FDPolicied {PUBLIC} }));
       fe_pos = [3:10-11]; fe_php_std_lib = false;
       fe_support_dynamic_type = false }))
  ]

They matched!
