Parsed decls:

{ Direct_decl_parser.classes = {}; funs = {};
  typedefs =
  { "MyBool" ->
    { td_pos = [11:6-12]; td_vis = Transparent; td_tparams = [];
      td_constraint = None;
      td_type =
      (Rhint (root|typedefs.php line 11, characters 15-18), (Tprim Tbool)) };
    "MyFloat" ->
    { td_pos = [9:6-13]; td_vis = Transparent; td_tparams = [];
      td_constraint = None;
      td_type =
      (Rhint (root|typedefs.php line 9, characters 16-20), (Tprim Tfloat)) };
    "MyInt" ->
    { td_pos = [8:6-11]; td_vis = Transparent; td_tparams = [];
      td_constraint = None;
      td_type =
      (Rhint (root|typedefs.php line 8, characters 14-16), (Tprim Tint)) };
    "MyNamespace\\MyString" ->
    { td_pos = [4:10-18]; td_vis = Transparent; td_tparams = [];
      td_constraint = None;
      td_type =
      (Rhint (root|typedefs.php line 4, characters 21-26), (Tprim Tstring)) };
    "MyNamespacedType" ->
    { td_pos = [13:6-22]; td_vis = Transparent; td_tparams = [];
      td_constraint = None;
      td_type =
      (Rhint (root|typedefs.php line 13, characters 25-45),
       (Tapply (([13:25-46], "\\MyNamespace\\MyString"), [])))
      };
    "MyNum" ->
    { td_pos = [10:6-11]; td_vis = Transparent; td_tparams = [];
      td_constraint = None;
      td_type =
      (Rhint (root|typedefs.php line 10, characters 14-16), (Tprim Tnum)) };
    "MyString" ->
    { td_pos = [7:6-14]; td_vis = Transparent; td_tparams = [];
      td_constraint = None;
      td_type =
      (Rhint (root|typedefs.php line 7, characters 17-22), (Tprim Tstring)) } };
  consts = {} }

They matched!
