[("\\A",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
       sc_module = None; sc_name = ([3:7-8], "\\A"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = [];
       sc_implements =
       [(Rhint ([3:20-45]),
         (Tapply (([3:20-45], "\\HH\\TypeParameterAttribute"), [])))];
       sc_support_dynamic_type = false; sc_consts = []; sc_typeconsts = [];
       sc_props = []; sc_sprops = [];
       sc_constructor =
       (Some { Shallow_decl_defs.sm_name = ([4:19-30], "__construct");
               sm_type =
               (Rwitness_from_decl ([4:19-30]),
                (Tfun
                   { ft_tparams = []; ft_where_constraints = [];
                     ft_params = [];
                     ft_implicit_params =
                     { capability = (CapDefaults [4:19-30]) };
                     ft_ret =
                     { et_enforced = Typing_defs_core.Unenforced;
                       et_type =
                       (Rwitness_from_decl ([4:19-30]), (Tprim Tvoid)) };
                     ft_flags =
                     { Typing_defs_flags.Fun.return_disposable = false;
                       async = false; generator = false; fun_kind = FSync;
                       instantiated_targs = false;
                       is_function_pointer = false; returns_readonly = false;
                       readonly_this = false; support_dynamic_type = false;
                       is_memoized = false; variadic = false };
                     ft_cross_package = None }));
               sm_visibility = Public; sm_deprecated = None;
               sm_flags =
               { Shallow_decl_defs.MethodFlags.abstract = false;
                 final = false; override = false;
                 dynamicallycallable = false; php_std_lib = false;
                 support_dynamic_type = false };
               sm_attributes = []; sm_sort_text = None });
       sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
       sc_enum_type = None; sc_docs_url = None }));
  ("\\C",
   (Shallow_decl_defs.Class
      { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
        sc_abstract = false; sc_is_xhp = false; sc_internal = false;
        sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
        sc_module = None; sc_name = ([7:7-8], "\\C");
        sc_tparams =
        [{ Typing_defs_core.tp_variance = Invariant;
           tp_name = ([7:36-38], "T1"); tp_tparams = []; tp_constraints = [];
           tp_reified = Reified;
           tp_user_attributes =
           [{ Typing_defs_core.ua_name = ([7:26-27], "\\A"); ua_params = [] };
             { Typing_defs_core.ua_name = ([7:11-24], "__Enforceable");
               ua_params = [] }
             ]
           }
          ];
        sc_where_constraints = []; sc_extends = []; sc_uses = [];
        sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
        sc_xhp_marked_empty = false; sc_req_extends = [];
        sc_req_implements = []; sc_req_class = []; sc_implements = [];
        sc_support_dynamic_type = false; sc_consts = []; sc_typeconsts = [];
        sc_props = []; sc_sprops = []; sc_constructor = None;
        sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
        sc_enum_type = None; sc_docs_url = None }))
  ]
