[("\\C",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
       sc_module = None; sc_name = ([3:7-8], "\\C"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = []; sc_implements = [];
       sc_support_dynamic_type = false; sc_consts = [];
       sc_typeconsts =
       [{ Shallow_decl_defs.stc_name = ([4:14-15], "T");
          stc_kind =
          (Typing_defs.TCConcrete
             { Typing_defs.tc_type = (Rhint ([4:18-21]), (Tprim Tint)) });
          stc_enforceable = ([Pos.none], false); stc_reifiable = None;
          stc_is_ctx = false }
         ];
       sc_props =
       [{ Shallow_decl_defs.sp_name = ([6:21-23], "a"); sp_xhp_attr = None;
          sp_type =
          (Rhint ([6:13-20]),
           (Taccess ((Rhint ([6:13-20]), Tthis), [([6:19-20], "T")])));
          sp_visibility = Private; sp_flags = needs_init }
         ];
       sc_sprops = [];
       sc_constructor =
       (Some { Shallow_decl_defs.sm_name = ([5:19-30], "__construct");
               sm_type =
               (Rwitness_from_decl ([5:19-30]),
                (Tfun
                   { ft_tparams = []; ft_where_constraints = [];
                     ft_params =
                     [{ fp_pos = [6:21-23]; fp_name = (Some "$a");
                        fp_type =
                        { et_enforced = Typing_defs_core.Unenforced;
                          et_type =
                          (Rhint ([6:13-20]),
                           (Taccess
                              ((Rhint ([6:13-20]), Tthis), [([6:19-20], "T")])))
                          };
                        fp_flags =
                        { Typing_defs_flags.FunParam.accept_disposable =
                          false; inout = false; has_default = false;
                          ifc_external = false; ifc_can_call = false;
                          readonly = false };
                         }
                       ];
                     ft_implicit_params =
                     { capability = (CapDefaults [5:19-30]) };
                     ft_ret =
                     { et_enforced = Typing_defs_core.Unenforced;
                       et_type =
                       (Rwitness_from_decl ([5:19-30]), (Tprim Tvoid)) };
                     ft_flags =
                     { Typing_defs_flags.Fun.return_disposable = false;
                       async = false; generator = false; fun_kind = FSync;
                       instantiated_targs = false;
                       is_function_pointer = false; returns_readonly = false;
                       readonly_this = false; support_dynamic_type = false;
                       is_memoized = false; variadic = false };
                     ft_ifc_decl = FDPolicied {PUBLIC};
                     ft_cross_package = None }));
               sm_visibility = Public; sm_deprecated = None;
               sm_flags = (empty); sm_attributes = [] });
       sc_static_methods = []; sc_methods = []; sc_user_attributes = [];
       sc_enum_type = None; sc_docs_url = None }))
  ]
