[("\\Y",
  (Shallow_decl_defs.Class
     { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
       sc_abstract = false; sc_is_xhp = false; sc_internal = false;
       sc_has_xhp_keyword = false; sc_kind = (Cclass Concrete);
       sc_module = None; sc_name = ([12:7-8], "\\Y"); sc_tparams = [];
       sc_where_constraints = []; sc_extends = []; sc_uses = [];
       sc_xhp_attr_uses = []; sc_xhp_enum_values = {};
       sc_xhp_marked_empty = false; sc_req_extends = [];
       sc_req_implements = []; sc_req_class = []; sc_implements = [];
       sc_support_dynamic_type = false; sc_consts = []; sc_typeconsts = [];
       sc_props =
       [{ Shallow_decl_defs.sp_name = ([14:10-12], "x"); sp_xhp_attr = None;
          sp_type = (Rwitness_from_decl ([14:10-12]), Tany);
          sp_visibility = Public;
          sp_flags =
          { Shallow_decl_defs.PropFlags.abstract = false; const = false;
            lateinit = false; lsb = false; needs_init = false;
            php_std_lib = false; readonly = false;
            safe_global_variable = false; no_auto_likes = false }
          }
         ];
       sc_sprops = []; sc_constructor = None; sc_static_methods = [];
       sc_methods = []; sc_user_attributes = []; sc_enum_type = None;
       sc_docs_url = None }))
  ]
