Parsed decls:

{ Direct_decl_parser.classes =
  { "\\X\\C" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cnormal;
      sc_name = ([11:9-10], "\\X\\C"); sc_tparams = [];
      sc_where_constraints = []; sc_extends = []; sc_uses = [];
      sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
      sc_implements = []; sc_consts = []; sc_typeconsts = [];
      sc_pu_enums = []; sc_props = []; sc_sprops = []; sc_constructor = None;
      sc_static_methods = []; sc_methods = [];
      sc_user_attributes =
      [{ Typing_defs_core.ua_name = ([10:10-15], "\\X\\Y\\Bar");
         ua_classname_params = [] };
        { Typing_defs_core.ua_name = ([10:5-8], "\\X\\Foo");
          ua_classname_params = [] }
        ];
      sc_enum_type = None };
    "\\X\\Foo" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cnormal;
      sc_name = ([4:9-12], "\\X\\Foo"); sc_tparams = [];
      sc_where_constraints = []; sc_extends = []; sc_uses = [];
      sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
      sc_implements =
      [(Rhint (root|user_attributes_in_namespaces.php line 4, characters 24-41),
        (Tapply (([4:24-42], "\\HH\\ClassAttribute"), [])))];
      sc_consts = []; sc_typeconsts = []; sc_pu_enums = []; sc_props = [];
      sc_sprops = []; sc_constructor = None; sc_static_methods = [];
      sc_methods = []; sc_user_attributes = []; sc_enum_type = None };
    "\\X\\Y\\Bar" ->
    { Shallow_decl_defs.sc_mode = Mstrict; sc_final = false;
      sc_is_xhp = false; sc_has_xhp_keyword = false; sc_kind = Cnormal;
      sc_name = ([7:11-14], "\\X\\Y\\Bar"); sc_tparams = [];
      sc_where_constraints = []; sc_extends = []; sc_uses = [];
      sc_xhp_attr_uses = []; sc_req_extends = []; sc_req_implements = [];
      sc_implements =
      [(Rhint (root|user_attributes_in_namespaces.php line 7, characters 26-43),
        (Tapply (([7:26-44], "\\HH\\ClassAttribute"), [])))];
      sc_consts = []; sc_typeconsts = []; sc_pu_enums = []; sc_props = [];
      sc_sprops = []; sc_constructor = None; sc_static_methods = [];
      sc_methods = []; sc_user_attributes = []; sc_enum_type = None } };
  funs = {}; typedefs = {}; consts = {} }

They matched!
