[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mpartial;
      fd_fun =
      { f_span = [3:1-5:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((int), None); f_name = ([3:10-13], "\\foo"); 
        f_tparams = []; f_where_constraints = []; f_variadic = FVnonVariadic;
        f_params =
        [{ param_annotation = ([3:18-20], int); param_type_hint = ((int), (Some ([3:14-17], (Hprim Tint)))); 
           param_is_variadic = false; param_pos = [3:18-20]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = None; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body = { fb_ast = [([4:3-17], (Return (Some (([4:10-16], int), (Binop (Star, (([4:10-12], int), (Lvar ([4:10-12], $x))), (([4:15-16], int), (Int "2"))))))))]; fb_annotation = () };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None }
      })