[(Class
    { c_span = [3:1-7:2]; c_annotation = (); c_mode = Mpartial; c_final = false;
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = Cnormal;
      c_name = ([3:7-8], "\\C"); c_tparams = []; c_extends = []; c_uses = [];
      c_use_as_alias = []; c_insteadof_alias = []; c_xhp_attr_uses = [];
      c_xhp_category = None; c_reqs = []; c_implements = []; c_support_dynamic_type = false;
      c_where_constraints = []; c_consts = []; c_typeconsts = []; c_vars = [];
      c_methods =
      [{ m_span = [4:3-6:4]; m_annotation = (); m_final = false; m_abstract = false;
         m_static = false; m_readonly_this = false; m_visibility = Public;
         m_name = ([4:19-22], "foo"); m_tparams = []; m_where_constraints = [];
         m_variadic = FVnonVariadic;
         m_params =
         [{ param_annotation = ([4:27-29], int); param_type_hint = ((int), (Some ([4:23-26], (Hprim Tint))));
            param_is_variadic = false; param_pos = [4:27-29]; param_name = "$x";
            param_expr = None; param_readonly = None; param_callconv = None;
            param_user_attributes = []; param_visibility = None }
           ];
         m_ctxs = None; m_unsafe_ctxs = None; m_body = { fb_ast = [([5:5-14], (Return (Some (([5:12-13], int), (Int "1")))))]; fb_annotation = () };
         m_fun_kind = FSync; m_user_attributes = []; m_readonly_ret = None;
         m_ret = ((int), None); m_external = false; m_doc_comment = None }
        ];
      c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>;
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>;
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_enum = None;
      c_doc_comment = None; c_emit_id = None })
