((script 159
  ((list 159
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (namespace_declaration 9
      ((((end_of_line 1) (single_line_comment 64) (end_of_line 1)
         (single_line_comment 64) (end_of_line 1) (end_of_line 1))
        namespace 9 ((whitespace 1)))
       (missing 0 ())
       (namespace_body 0 ((missing 0 ()) (missing 0 ()) (missing 0 ())))))
     (namespace_declaration 12
      ((() namespace 9 ((whitespace 1))) (missing 0 ())
       (namespace_body 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
