((script 96
  ((list 96
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (namespace_declaration 33
      ((((end_of_line 1) (single_line_comment 55) (end_of_line 1)
         (end_of_line 1))
        namespace 9 ((whitespace 1)))
       (qualified_name 22
        ((list 22
          ((list_item 9 ((() name 8 ()) (() "\\" 1 ())))
           (list_item 13 ((() name 12 ()) (() "\\" 1 ())))))))
       (namespace_empty_body 1 ((() ";" 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
