File "dup_parent_type.bad.php--file1.php", line 6, characters 17-17:
In Pocket Universe `C:@F`, atom `A` is missing type `S` (Naming[2108])
File "dup_parent_type.bad.php--file1.php", line 6, characters 17-17:
In Pocket Universe `C:@F`, atom `A` is missing value `foo` (Naming[2108])
File "dup_parent_type.bad.php--file1.php", line 13, characters 15-15:
Pocket Universe case type `T` is already declared in `B:@F` (Naming[2101])
File "dup_parent_type.bad.php--file1.php", line 14, characters 12-14:
Pocket Universe case value `foo` is already declared in `B:@F` (Naming[2101])
File "dup_parent_type.bad.php--file2.php", line 6, characters 17-17:
In Pocket Universe `B:@F`, atom `A` is missing type `S` (Naming[2108])
File "dup_parent_type.bad.php--file2.php", line 6, characters 17-17:
In Pocket Universe `B:@F`, atom `A` is missing value `foo` (Naming[2108])
File "dup_parent_type.bad.php--file2.php", line 8, characters 15-15:
Pocket Universe case type `T` is already declared in `A:@F` (Naming[2101])
File "dup_parent_type.bad.php--file2.php", line 10, characters 17-19:
Pocket Universe case value `key` is already declared in `A:@F` (Naming[2101])
File "dup_parent_type.bad.php--file3.php", line 12, characters 7-7:
In Pocket Universe `A:@F`, atom `A` is missing type `S` (Naming[2108])
