File "unify_error1.php", line 13, characters 12-16:
Invalid argument (Typing[4110])
  File "unify_error1.php", line 3, characters 19-21:
  Expected `int`
  File "unify_error1.php", line 8, characters 17-17:
  But got `num`
File "unify_error1.php", line 13, characters 12-16:
Invalid argument (Typing[4110])
  File "unify_error1.php", line 3, characters 19-21:
  Expected `int`
  File "unify_error1.php", line 10, characters 23-27:
  But got `string`
