File "obj_get_lvar_partial.php", line 8, characters 18-19:
Dynamic access of properties and methods is only permitted on values of type `dynamic`. (Naming[2011])
  File "obj_get_lvar_partial.php", line 8, characters 18-19:
  Did you mean `->x` instead?
File "obj_get_lvar_partial.php", line 9, characters 18-19:
Dynamic access of properties and methods is only permitted on values of type `dynamic`. (Naming[2011])
  File "obj_get_lvar_partial.php", line 9, characters 18-19:
  Did you mean `->x` instead?
File "obj_get_lvar_partial.php", line 10, characters 12-13:
Dynamic access of properties and methods is only permitted on values of type `dynamic`. (Naming[2011])
  File "obj_get_lvar_partial.php", line 10, characters 12-13:
  Did you mean `->x` instead?
File "obj_get_lvar_partial.php", line 11, characters 12-13:
Dynamic access of properties and methods is only permitted on values of type `dynamic`. (Naming[2011])
  File "obj_get_lvar_partial.php", line 11, characters 12-13:
  Did you mean `->x` instead?
File "obj_get_lvar_partial.php", line 12, characters 12-13:
Dynamic access of properties and methods is only permitted on values of type `dynamic`. (Naming[2011])
  File "obj_get_lvar_partial.php", line 12, characters 12-13:
  Did you mean `->x` instead?
File "obj_get_lvar_partial.php", line 14, characters 10-11:
Dynamic access of properties and methods is only permitted on values of type `dynamic`. (Naming[2011])
  File "obj_get_lvar_partial.php", line 14, characters 10-11:
  Did you mean `->x` instead?
File "obj_get_lvar_partial.php", line 15, characters 22-23:
Dynamic access of properties and methods is only permitted on values of type `dynamic`. (Naming[2011])
  File "obj_get_lvar_partial.php", line 15, characters 22-23:
  Did you mean `->x` instead?
File "obj_get_lvar_partial.php", line 8, characters 5-19:
Dynamic access of property (Typing[4110])
  File "obj_get_lvar_partial.php", line 8, characters 5-19:
  Expected `dynamic`
  File "obj_get_lvar_partial.php", line 8, characters 10-12:
  Type `Bar` is not a subtype of `dynamic` under dynamic-aware subtyping
File "obj_get_lvar_partial.php", line 9, characters 5-19:
Dynamic access of property (Typing[4110])
  File "obj_get_lvar_partial.php", line 9, characters 5-19:
  Expected `dynamic`
  File "obj_get_lvar_partial.php", line 9, characters 10-12:
  Type `Bar` is not a subtype of `dynamic` under dynamic-aware subtyping
File "obj_get_lvar_partial.php", line 10, characters 5-13:
Dynamic access of property (Typing[4110])
  File "obj_get_lvar_partial.php", line 10, characters 5-13:
  Expected `dynamic`
  File "obj_get_lvar_partial.php", line 10, characters 5-9:
  Type `this` is not a subtype of `dynamic` under dynamic-aware subtyping
File "obj_get_lvar_partial.php", line 11, characters 5-13:
Dynamic access of property (Typing[4110])
  File "obj_get_lvar_partial.php", line 11, characters 5-13:
  Expected `dynamic`
  File "obj_get_lvar_partial.php", line 11, characters 5-9:
  Type `this` is not a subtype of `dynamic` under dynamic-aware subtyping
File "obj_get_lvar_partial.php", line 12, characters 5-13:
Dynamic access of property (Typing[4110])
  File "obj_get_lvar_partial.php", line 12, characters 5-13:
  Expected `dynamic`
  File "obj_get_lvar_partial.php", line 12, characters 5-9:
  Type `this` is not a subtype of `dynamic` under dynamic-aware subtyping
