File "obj_get.php", line 5, characters 3-13:
  dynamic
File "obj_get.php", line 7, characters 3-13:
  dynamic
WARN: File "obj_get.php", line 6, characters 12-19:
Property accessed on a value of type `dynamic` (Warn[12042])
  File "obj_get.php", line 3, characters 21-27:
  This expression has type `dynamic`
WARN: File "obj_get.php", line 8, characters 7-14:
Property accessed on a value of type `dynamic` (Warn[12042])
  File "obj_get.php", line 3, characters 21-27:
  This expression has type `dynamic`
