File "obj_get_lvar_partial.php", line 8, characters 18-19:
Dynamic method or attribute access is not allowed on a non-dynamic value. (Naming[2011])
File "obj_get_lvar_partial.php", line 9, characters 18-19:
Dynamic method or attribute access is not allowed on a non-dynamic value. (Naming[2011])
File "obj_get_lvar_partial.php", line 10, characters 12-13:
Dynamic method or attribute access is not allowed on a non-dynamic value. (Naming[2011])
File "obj_get_lvar_partial.php", line 11, characters 12-13:
Dynamic method or attribute access is not allowed on a non-dynamic value. (Naming[2011])
File "obj_get_lvar_partial.php", line 12, characters 12-13:
Dynamic method or attribute access is not allowed on a non-dynamic value. (Naming[2011])
File "obj_get_lvar_partial.php", line 14, characters 10-11:
Dynamic method or attribute access is not allowed on a non-dynamic value. (Naming[2011])
File "obj_get_lvar_partial.php", line 15, characters 22-23:
Dynamic method or attribute access is not allowed on a non-dynamic value. (Naming[2011])
