--- ocaml
+++ rupro
@@ -1,110 +1,110 @@
 FoldedClass {
     name: "\\MyTrait1",
     pos: Pos(root|trait_diamond_no_attr_2.bad.php, 6:7-15),
     kind: Ctrait,
     methods: {
         "testFun": FoldedElement {
             flags: (empty),
             origin: "\\MyTrait1",
             visibility: Public,
             deprecated: None,
         },
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|trait_diamond_no_attr_2.bad.php, 6:7-15),
             ty: HH\classname<this>,
             origin: "\\MyTrait1",
             refs: [],
         },
     },
 }
 FoldedClass {
     name: "\\MyTrait2",
     pos: Pos(root|trait_diamond_no_attr_2.bad.php, 9:7-15),
     kind: Ctrait,
     substs: {
         "\\MyTrait1": SubstContext {
             subst: Subst(
                 {},
             ),
             class_context: "\\MyTrait2",
             from_req_extends: false,
         },
     },
     ancestors: {
         "\\MyTrait1": MyTrait1,
     },
     methods: {
         "testFun": FoldedElement {
             flags: (empty),
             origin: "\\MyTrait1",
             visibility: Public,
             deprecated: None,
         },
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|trait_diamond_no_attr_2.bad.php, 9:7-15),
             ty: HH\classname<this>,
             origin: "\\MyTrait2",
             refs: [],
         },
     },
     extends: {
         "\\MyTrait1",
     },
 }
 FoldedClass {
     name: "\\MyClass",
     pos: Pos(root|trait_diamond_no_attr_2.bad.php, 14:7-14),
     kind: Cclass(
         Concrete,
     ),
     substs: {
         "\\MyTrait1": SubstContext {
             subst: Subst(
                 {},
             ),
-            class_context: "\\MyTrait2",
+            class_context: "\\MyClass",
             from_req_extends: false,
         },
         "\\MyTrait2": SubstContext {
             subst: Subst(
                 {},
             ),
             class_context: "\\MyClass",
             from_req_extends: false,
         },
     },
     ancestors: {
         "\\MyTrait1": MyTrait1,
         "\\MyTrait2": MyTrait2,
     },
     methods: {
         "testFun": FoldedElement {
             flags: (empty),
             origin: "\\MyTrait1",
             visibility: Public,
             deprecated: None,
         },
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|trait_diamond_no_attr_2.bad.php, 14:7-14),
             ty: HH\classname<this>,
             origin: "\\MyClass",
             refs: [],
         },
     },
     extends: {
         "\\MyTrait1",
         "\\MyTrait2",
     },
 }
