File "trait_diamond_property_2.bad.php", line 17, characters 7-13:
Class `MyClass` inherits generic trait property `myprop` via multiple paths at different types. (Typing[4462])
  File "trait_diamond_property_2.bad.php", line 10, characters 10-11:
  Trait property is defined here
  File "trait_diamond_property_2.bad.php", line 19, characters 7-14:
  `MyClass` uses `MyTrait2`
  File "trait_diamond_property_2.bad.php", line 14, characters 7-19:
  `MyTrait2` uses `MyTrait1`
  File "trait_diamond_property_2.bad.php", line 18, characters 7-22:
  `MyClass` uses `MyTrait1`
