Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: refactor)
slog variable (CodeActionKind: refactor)
Extract into method (CodeActionKind: refactor)
Extract shape type (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"type T${0:placeholder_} = shape();\n\n",
          "range":{"end":{"character":0,"line":2},"start":{"character":0,"line":2}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Extract shape type"
}

Applied edit for code action:
------------------------------------------
<?hh

type T${0:placeholder_} = shape();

class C {
  public function foo(): void {
    $x =/*range-start*/ shape() /*range-end*/;
  }
}

