<?hh

CLASS :BUSCEMI {
  ATTRIBUTE ENUM {'NOPE'} YOUNG @REQUIRED;
  CATEGORY %COOL;
  CHILDREN (%COOL);
  PUBLIC FUNCTION RENDER() {
    return "HOW DO YOU DO, FELLOW KIDS?\n";
  }
}

$X = <BUSCEMI YOUNG="NOPE"/>;
ECHO $X->RENDER();
