f1
  kind: function
  position: File "", line 7, characters 10-11:
  span: File "", line 7, character 1 - line 7, character 16:
  modifiers: 
  params:
  docblock:
/*
  Multi line
  doc block
*/

f2
  kind: function
  position: File "", line 11, characters 10-11:
  span: File "", line 11, character 1 - line 11, character 16:
  modifiers: 
  params:
  docblock:
/* Newline between docblock and function */

no_docblock1
  kind: function
  position: File "", line 16, characters 10-21:
  span: File "", line 16, character 1 - line 16, character 26:
  modifiers: 
  params:

f4
  kind: function
  position: File "", line 18, characters 10-11:
  span: File "", line 18, character 1 - line 18, character 16:
  modifiers: 
  params:
  docblock:
/* Narrow space */

no_docblock2
  kind: function
  position: File "", line 19, characters 10-21:
  span: File "", line 19, character 1 - line 19, character 26:
  modifiers: 
  params:

C
  kind: class
  position: File "", line 22, characters 7-7:
  span: File "", line 22, character 1 - line 33, character 1:
  modifiers: 
  docblock:
// line comment

  x
    kind: property
    position: File "", line 25, characters 17-18:
    span: File "", line 25, character 17 - line 25, character 18:
    modifiers: public 
    docblock:
/* Property */

  m1
    kind: method
    position: File "", line 30, characters 19-20:
    span: File "", line 30, character 3 - line 32, character 3:
    modifiers: public 
    params:
    docblock:
// multi
// line
// line comment

