MyEnumClassKind
  kind: class
  id: type_id::MyEnumClassKind
  position: line 3, characters 7-21
  span: line 3, character 1 - line 3, character 24
  modifiers: 

MyEnumClass
  kind: enum
  id: type_id::MyEnumClass
  position: line 4, characters 12-22
  span: line 4, character 1 - line 7, character 1
  modifiers: 

  First
    kind: class constant
    id: class_const::MyEnumClass::First
    position: line 5, characters 19-23
    span: line 5, character 19 - line 5, character 47
    modifiers: 

  Second
    kind: class constant
    id: class_const::MyEnumClass::Second
    position: line 6, characters 19-24
    span: line 6, character 19 - line 6, character 48
    modifiers: 

