foo
  type: function
  position: File "", line 3, characters 10-12:

bar
  type: function
  position: File "", line 5, characters 10-12:

C
  type: class
  position: File "", line 7, characters 7-7:

  foo
    type: method
    position: File "", line 8, characters 19-21:
    static: false
    extents: File "", line 8, character 3 - line 8, character 26:

  bar
    type: method
    position: File "", line 10, characters 26-28:
    static: true
    extents: File "", line 10, character 3 - line 10, character 33:


