foo
  kind: enum
  id: type_id::foo
  position: line 3, characters 6-8
  span: line 3, character 1 - line 3, character 20
  modifiers: 

I
  kind: interface
  id: type_id::I
  position: line 5, characters 11-11
  span: line 5, character 1 - line 5, character 14
  modifiers: 

T
  kind: trait
  id: type_id::T
  position: line 7, characters 7-7
  span: line 7, character 1 - line 7, character 10
  modifiers: 

