C
  kind: class
  id: type_id::C
  position: line 3, characters 16-16
  span: line 3, character 1 - line 7, character 1
  modifiers: abstract 

  Ta
    kind: typeconst
    id: class_const::C::Ta
    position: line 4, characters 14-15
    span: line 4, character 3 - line 4, character 25
    modifiers: 
    detail: const type Ta = string;

  Tb
    kind: typeconst
    id: class_const::C::Tb
    position: line 5, characters 23-24
    span: line 5, character 3 - line 5, character 25
    modifiers: abstract 
    detail: abstract const type Tb;

  Tc
    kind: typeconst
    id: class_const::C::Tc
    position: line 6, characters 23-24
    span: line 6, character 3 - line 6, character 32
    modifiers: abstract 
    detail: abstract const type Tc as int;

