ERROR: File "tparam_class_method_bad.php", line 4, characters 3-4:
It is no longer allowed to use a `classname<T>` in this position. Please use a `class<T>` instead. (Typing[4482])
  File "tparam_class_method_bad.php", line 3, characters 18-29:
  Definition is here
ERROR: File "tparam_class_method_bad.php", line 4, characters 7-18:
You are trying to access the static method `doesNotExist` but this is a value of generic type T (Typing[4252])
  File "tparam_class_method_bad.php", line 3, characters 28-28:
  Definition is here
