((script 83
  ((list 83
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 8) (end_of_line 1)))))))
     (classish_declaration 67
      ((missing 0 ())
       (list 8 ((((end_of_line 1)) abstract 8 ((whitespace 1)))))
       (missing 0 ()) (() class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 50
        ((() { 1 ((end_of_line 1)))
         (list 23
          ((property_declaration 23
            ((missing 0 ())
             (list 15
              ((((whitespace 2)) public 6 ((whitespace 1)))
               (() abstract 8 ((whitespace 1)))))
             (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
             (list 2
              ((list_item 2
                ((property_declarator 2 ((() variable 2 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1
              ((whitespace 1) (single_line_comment 20) (end_of_line 1)))))))
         (() } 1 ())))))
     (expression_statement 1 ((missing 0 ()) (() ";" 1 ((end_of_line 1)))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
