{
  "kind": "script",
  "script_declarations": {
    "kind": "list",
    "elements": [
      {
        "kind": "markup_section",
        "markup_suffix": {
          "kind": "markup_suffix",
          "markup_suffix_less_than_question": {
            "kind": "token",
            "token": {
              "kind": "<?",
              "text": "<?",
              "offset": 0,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 1
            }
          },
          "markup_suffix_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "hh",
              "offset": 2,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 4,
                  "width": 1
                }
              ],
              "line_number": 1
            }
          }
        }
      },
      {
        "kind": "file_attribute_specification",
        "file_attribute_specification_left_double_angle": {
          "kind": "token",
          "token": {
            "kind": "<<",
            "text": "<<",
            "offset": 5,
            "leading_width": 1,
            "width": 2,
            "trailing_width": 0,
            "leading": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 5,
                "width": 1
              }
            ],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_keyword": {
          "kind": "token",
          "token": {
            "kind": "file",
            "text": "file",
            "offset": 8,
            "leading_width": 0,
            "width": 4,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_colon": {
          "kind": "token",
          "token": {
            "kind": ":",
            "text": ":",
            "offset": 12,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_attributes": {
          "kind": "list",
          "elements": [
            {
              "kind": "list_item",
              "list_item": {
                "kind": "constructor_call",
                "constructor_call_type": {
                  "kind": "simple_type_specifier",
                  "simple_type_specifier": {
                    "kind": "token",
                    "token": {
                      "kind": "name",
                      "text": "__EnableUnstableFeatures",
                      "offset": 13,
                      "leading_width": 0,
                      "width": 24,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 3
                    }
                  }
                },
                "constructor_call_left_paren": {
                  "kind": "token",
                  "token": {
                    "kind": "(",
                    "text": "(",
                    "offset": 37,
                    "leading_width": 0,
                    "width": 1,
                    "trailing_width": 0,
                    "leading": [],
                    "trailing": [],
                    "line_number": 3
                  }
                },
                "constructor_call_argument_list": {
                  "kind": "list",
                  "elements": [
                    {
                      "kind": "list_item",
                      "list_item": {
                        "kind": "literal",
                        "literal_expression": {
                          "kind": "token",
                          "token": {
                            "kind": "single_quoted_string_literal",
                            "text": "'class_aliases_everywhere'",
                            "offset": 38,
                            "leading_width": 0,
                            "width": 26,
                            "trailing_width": 0,
                            "leading": [],
                            "trailing": [],
                            "line_number": 3
                          }
                        }
                      }
                    }
                  ]
                },
                "constructor_call_right_paren": {
                  "kind": "token",
                  "token": {
                    "kind": ")",
                    "text": ")",
                    "offset": 64,
                    "leading_width": 0,
                    "width": 1,
                    "trailing_width": 0,
                    "leading": [],
                    "trailing": [],
                    "line_number": 3
                  }
                }
              }
            }
          ]
        },
        "file_attribute_specification_right_double_angle": {
          "kind": "token",
          "token": {
            "kind": ">>",
            "text": ">>",
            "offset": 65,
            "leading_width": 0,
            "width": 2,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 67,
                "width": 1
              }
            ],
            "line_number": 3
          }
        }
      },
      {
        "kind": "class_alias_declaration",
        "class_alias_keyword": {
          "kind": "token",
          "token": {
            "kind": "class",
            "text": "class",
            "offset": 68,
            "leading_width": 1,
            "width": 5,
            "trailing_width": 1,
            "leading": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 68,
                "width": 1
              }
            ],
            "trailing": [
              { "kind": "whitespace", "text": " ", "offset": 74, "width": 1 }
            ],
            "line_number": 5
          }
        },
        "class_alias_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "C",
            "offset": 75,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              { "kind": "whitespace", "text": " ", "offset": 76, "width": 1 }
            ],
            "line_number": 5
          }
        },
        "class_alias_equal": {
          "kind": "token",
          "token": {
            "kind": "=",
            "text": "=",
            "offset": 77,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              { "kind": "whitespace", "text": " ", "offset": 78, "width": 1 }
            ],
            "line_number": 5
          }
        },
        "class_alias_original_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "D",
            "offset": 79,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 5
          }
        },
        "class_alias_semicolon": {
          "kind": "token",
          "token": {
            "kind": ";",
            "text": ";",
            "offset": 80,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 81,
                "width": 1
              }
            ],
            "line_number": 5
          }
        }
      },
      {
        "kind": "class_alias_declaration",
        "class_alias_keyword": {
          "kind": "token",
          "token": {
            "kind": "class",
            "text": "class",
            "offset": 82,
            "leading_width": 1,
            "width": 5,
            "trailing_width": 1,
            "leading": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 82,
                "width": 1
              }
            ],
            "trailing": [
              { "kind": "whitespace", "text": " ", "offset": 88, "width": 1 }
            ],
            "line_number": 7
          }
        },
        "class_alias_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "C",
            "offset": 89,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 7
          }
        },
        "class_alias_type_parameters": {
          "kind": "type_parameters",
          "type_parameters_left_angle": {
            "kind": "token",
            "token": {
              "kind": "<",
              "text": "<",
              "offset": 90,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 7
            }
          },
          "type_parameters_parameters": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "type_parameter",
                  "type_name": {
                    "kind": "token",
                    "token": {
                      "kind": "name",
                      "text": "T",
                      "offset": 91,
                      "leading_width": 0,
                      "width": 1,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 7
                    }
                  }
                }
              }
            ]
          },
          "type_parameters_right_angle": {
            "kind": "token",
            "token": {
              "kind": ">",
              "text": ">",
              "offset": 92,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 93,
                  "width": 1
                }
              ],
              "line_number": 7
            }
          }
        },
        "class_alias_equal": {
          "kind": "token",
          "token": {
            "kind": "=",
            "text": "=",
            "offset": 94,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              { "kind": "whitespace", "text": " ", "offset": 95, "width": 1 }
            ],
            "line_number": 7
          }
        },
        "class_alias_original_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "D",
            "offset": 96,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 7
          }
        },
        "class_alias_original_type_parameters": {
          "kind": "type_parameters",
          "type_parameters_left_angle": {
            "kind": "token",
            "token": {
              "kind": "<",
              "text": "<",
              "offset": 97,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 7
            }
          },
          "type_parameters_parameters": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "type_parameter",
                  "type_name": {
                    "kind": "token",
                    "token": {
                      "kind": "name",
                      "text": "T",
                      "offset": 98,
                      "leading_width": 0,
                      "width": 1,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 7
                    }
                  }
                }
              }
            ]
          },
          "type_parameters_right_angle": {
            "kind": "token",
            "token": {
              "kind": ">",
              "text": ">",
              "offset": 99,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 7
            }
          }
        },
        "class_alias_semicolon": {
          "kind": "token",
          "token": {
            "kind": ";",
            "text": ";",
            "offset": 100,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 101,
                "width": 1
              }
            ],
            "line_number": 7
          }
        }
      },
      {
        "kind": "class_alias_declaration",
        "class_alias_keyword": {
          "kind": "token",
          "token": {
            "kind": "interface",
            "text": "interface",
            "offset": 102,
            "leading_width": 1,
            "width": 9,
            "trailing_width": 1,
            "leading": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 102,
                "width": 1
              }
            ],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 112,
                "width": 1
              }
            ],
            "line_number": 9
          }
        },
        "class_alias_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "I",
            "offset": 113,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 114,
                "width": 1
              }
            ],
            "line_number": 9
          }
        },
        "class_alias_equal": {
          "kind": "token",
          "token": {
            "kind": "=",
            "text": "=",
            "offset": 115,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 116,
                "width": 1
              }
            ],
            "line_number": 9
          }
        },
        "class_alias_original_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "J",
            "offset": 117,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 9
          }
        },
        "class_alias_semicolon": {
          "kind": "token",
          "token": {
            "kind": ";",
            "text": ";",
            "offset": 118,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 119,
                "width": 1
              }
            ],
            "line_number": 9
          }
        }
      },
      {
        "kind": "class_alias_declaration",
        "class_alias_keyword": {
          "kind": "token",
          "token": {
            "kind": "interface",
            "text": "interface",
            "offset": 120,
            "leading_width": 1,
            "width": 9,
            "trailing_width": 1,
            "leading": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 120,
                "width": 1
              }
            ],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 130,
                "width": 1
              }
            ],
            "line_number": 11
          }
        },
        "class_alias_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "I",
            "offset": 131,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 11
          }
        },
        "class_alias_type_parameters": {
          "kind": "type_parameters",
          "type_parameters_left_angle": {
            "kind": "token",
            "token": {
              "kind": "<",
              "text": "<",
              "offset": 132,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 11
            }
          },
          "type_parameters_parameters": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "type_parameter",
                  "type_name": {
                    "kind": "token",
                    "token": {
                      "kind": "name",
                      "text": "T",
                      "offset": 133,
                      "leading_width": 0,
                      "width": 1,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 11
                    }
                  }
                }
              }
            ]
          },
          "type_parameters_right_angle": {
            "kind": "token",
            "token": {
              "kind": ">",
              "text": ">",
              "offset": 134,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 135,
                  "width": 1
                }
              ],
              "line_number": 11
            }
          }
        },
        "class_alias_equal": {
          "kind": "token",
          "token": {
            "kind": "=",
            "text": "=",
            "offset": 136,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 137,
                "width": 1
              }
            ],
            "line_number": 11
          }
        },
        "class_alias_original_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "J",
            "offset": 138,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 11
          }
        },
        "class_alias_original_type_parameters": {
          "kind": "type_parameters",
          "type_parameters_left_angle": {
            "kind": "token",
            "token": {
              "kind": "<",
              "text": "<",
              "offset": 139,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 11
            }
          },
          "type_parameters_parameters": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "type_parameter",
                  "type_name": {
                    "kind": "token",
                    "token": {
                      "kind": "name",
                      "text": "T",
                      "offset": 140,
                      "leading_width": 0,
                      "width": 1,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 11
                    }
                  }
                }
              }
            ]
          },
          "type_parameters_right_angle": {
            "kind": "token",
            "token": {
              "kind": ">",
              "text": ">",
              "offset": 141,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 11
            }
          }
        },
        "class_alias_semicolon": {
          "kind": "token",
          "token": {
            "kind": ";",
            "text": ";",
            "offset": 142,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 143,
                "width": 1
              }
            ],
            "line_number": 11
          }
        }
      },
      {
        "kind": "class_alias_declaration",
        "class_alias_keyword": {
          "kind": "token",
          "token": {
            "kind": "trait",
            "text": "trait",
            "offset": 144,
            "leading_width": 17,
            "width": 5,
            "trailing_width": 1,
            "leading": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 144,
                "width": 1
              },
              {
                "kind": "single_line_comment",
                "text": "// syntax error",
                "offset": 145,
                "width": 15
              },
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 160,
                "width": 1
              }
            ],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 166,
                "width": 1
              }
            ],
            "line_number": 14
          }
        },
        "class_alias_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "T1",
            "offset": 167,
            "leading_width": 0,
            "width": 2,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 169,
                "width": 1
              }
            ],
            "line_number": 14
          }
        },
        "class_alias_equal": {
          "kind": "token",
          "token": {
            "kind": "=",
            "text": "=",
            "offset": 170,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 171,
                "width": 1
              }
            ],
            "line_number": 14
          }
        },
        "class_alias_original_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "T2",
            "offset": 172,
            "leading_width": 0,
            "width": 2,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 14
          }
        },
        "class_alias_semicolon": {
          "kind": "token",
          "token": {
            "kind": ";",
            "text": ";",
            "offset": 174,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 175,
                "width": 1
              }
            ],
            "line_number": 14
          }
        }
      },
      {
        "kind": "end_of_file",
        "end_of_file_token": {
          "kind": "token",
          "token": {
            "kind": "end_of_file",
            "text": "",
            "offset": 176,
            "leading_width": 0,
            "width": 0,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 15
          }
        }
      }
    ]
  }
}
