((script 170
  ((list 170
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 107
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((single_line_comment 56) (end_of_line 1) (end_of_line 1)) class 5
        ((whitespace 1)))
       (() name 17 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 83
        ((() { 1 ((end_of_line 1)))
         (list 77
          ((methodish_declaration 77
            ((missing 0 ())
             (function_declaration_header 26
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 3 ()) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ()) (() : 1 ())
               (simple_type_specifier 4 ((() void 4 ()))) (missing 0 ())))
             (compound_statement 51
              ((() { 1 ((end_of_line 1)))
               (list 41
                ((expression_statement 20
                  ((binary_expression 19
                    ((variable 2
                      ((((whitespace 4)) variable 2 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (object_creation_expression 14
                      ((() new 3 ((whitespace 1)))
                       (constructor_call 10
                        ((simple_type_specifier 8 ((() name 8 ())))
                         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))))))
                   (() ";" 1 ((end_of_line 1)))))
                 (expression_statement 16
                  ((binary_expression 15
                    ((member_selection_expression 8
                      ((variable 2 ((((whitespace 4)) variable 2 ())))
                       (() -> 2 ())
                       (braced_expression 4
                        ((() { 1 ())
                         (literal 2 ((() single_quoted_string_literal 2 ())))
                         (() } 1 ((whitespace 1)))))))
                     (() = 1 ((whitespace 1)))
                     (literal 4 ((() boolean_literal 4 ())))))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
