((script 58
  ((list 58
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (file_attribute_specification 23
      ((((end_of_line 1)) << 2 ()) (() file 4 ()) (() : 1 ((whitespace 1)))
       (list 13
        ((list_item 13
          ((constructor_call 13
            ((simple_type_specifier 11 ((() name 11 ()))) (() "(" 1 ())
             (missing 0 ()) (() ")" 1 ())))
           (missing 0 ())))))
       (() >> 2 ((end_of_line 1)))))
     (namespace_declaration 17
      ((((end_of_line 1)) namespace 9 ((whitespace 1)))
       (() name 3 ((whitespace 1)))
       (namespace_body 3
        ((() { 1 ((whitespace 1))) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
