((script 66
  ((list 66
    ((markup_section 5
      ((missing 0 ()) (() markup 0 ())
       (markup_suffix 5 ((() <? 2 ()) (() name 3 ((end_of_line 1)))))
       (missing 0 ())))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (missing 0 ()) (() name 5 ()) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (missing 0 ()) (() name 5 ()) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (expression_statement 8
      ((function_call_expression 7
        ((((end_of_line 1)) name 5 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((function_call_expression 7
        ((() name 5 ()) (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))