(3,13)-(3,13) A closing angle bracket `>` is expected here.
(3,14)-(3,14) A class member, method, type, trait usage, trait require, xhp attribute, xhp use, or xhp category is expected here.
(3,16)-(3,16) A class member, method, type, trait usage, trait require, xhp attribute, xhp use, or xhp category is expected here.
(3,19)-(3,19) A class member, method, type, trait usage, trait require, xhp attribute, xhp use, or xhp category is expected here.
(3,20)-(3,20) A class member, method, type, trait usage, trait require, xhp attribute, xhp use, or xhp category is expected here.
