((script 121
  ((list 121
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 115
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 107
        ((() { 1 ((end_of_line 1)))
         (list 101
          ((const_declaration 71
            ((list 62
              ((((whitespace 2)) abstract 8 ((whitespace 1)))
               (() final 5 ((whitespace 1))) (() static 6 ((whitespace 1)))
               (() private 7 ((whitespace 1)))
               (() protected 9 ((whitespace 1)))
               (() public 6 ((whitespace 1))) (() async 5 ((whitespace 1)))
               (() coroutine 9 ((whitespace 1)))))
             (() const 5 ((whitespace 1))) (missing 0 ())
             (list 1
              ((list_item 1
                ((constant_declarator 1 ((() name 1 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 26
            ((list 17
              ((((end_of_line 1) (whitespace 2)) abstract 8 ((whitespace 1)))
               (() abstract 8 ((whitespace 1)))))
             (() const 5 ((whitespace 1))) (missing 0 ())
             (list 1
              ((list_item 1
                ((constant_declarator 1 ((() name 1 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
