((script 143
  ((list 143
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 137
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 129
        ((() { 1 ((end_of_line 1)))
         (list 123
          ((trait_use_conflict_resolution 123
            ((((whitespace 2)) use 3 ((whitespace 1)))
             (list 1
              ((list_item 1
                ((simple_type_specifier 1 ((() name 1 ((whitespace 1)))))
                 (missing 0 ())))))
             (() { 1 ((end_of_line 1)))
             (list 107
              ((list_item 73
                ((trait_use_alias_item 72
                  ((scope_resolution_expression 4
                    ((simple_type_specifier 1 ((((whitespace 4)) name 1 ())))
                     (() :: 2 ()) (() name 1 ((whitespace 1)))))
                   (() as 2 ((whitespace 1)))
                   (list 62
                    ((() abstract 8 ((whitespace 1)))
                     (() final 5 ((whitespace 1)))
                     (() static 6 ((whitespace 1)))
                     (() private 7 ((whitespace 1)))
                     (() protected 9 ((whitespace 1)))
                     (() public 6 ((whitespace 1)))
                     (() async 5 ((whitespace 1)))
                     (() coroutine 9 ((whitespace 1)))))
                   (simple_type_specifier 1 ((() name 1 ())))))
                 (() ";" 1 ((end_of_line 1)))))
               (list_item 28
                ((trait_use_alias_item 27
                  ((scope_resolution_expression 4
                    ((simple_type_specifier 1
                      ((((end_of_line 1) (whitespace 4)) name 1 ())))
                     (() :: 2 ()) (() name 1 ((whitespace 1)))))
                   (() as 2 ((whitespace 1)))
                   (list 17
                    ((() abstract 8 ((whitespace 1)))
                     (() abstract 8 ((whitespace 1)))))
                   (simple_type_specifier 1 ((() name 1 ())))))
                 (() ";" 1 ((end_of_line 1)))))))
             (((whitespace 2)) } 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
