((script 188
  ((list 188
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 78
      ((missing 0 ())
       (function_declaration_header 75
        ((list 62
          ((((end_of_line 1) (single_line_comment 74) (end_of_line 1)) async
            5 ((whitespace 1)))
           (() abstract 8 ((whitespace 1))) (() final 5 ((whitespace 1)))
           (() static 6 ((whitespace 1))) (() private 7 ((whitespace 1)))
           (() protected 9 ((whitespace 1))) (() public 6 ((whitespace 1)))
           (() coroutine 9 ((whitespace 1)))))
         (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
         (missing 0 ()) (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 27
      ((missing 0 ())
       (function_declaration_header 24
        ((list 11
          ((((end_of_line 1)) async 5 ((whitespace 1)))
           (() async 5 ((whitespace 1)))))
         (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
         (missing 0 ()) (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
