(5,13)-(5,21) Trait use aliases cannot be declared abstract
(5,28)-(5,34) Trait use aliases cannot be declared static
(5,53)-(5,59) Trait use aliases cannot have multiple visibility modifiers
(5,60)-(5,65) Trait use aliases cannot be declared async
(5,66)-(5,75) Trait use aliases cannot be declared coroutine
(7,13)-(7,21) Trait use aliases cannot be declared abstract
(7,22)-(7,30) Trait use aliases cannot have duplicate modifiers
(7,22)-(7,30) Trait use aliases cannot be declared abstract
