((script 2896
  ((list 2896
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 22
      ((missing 0 ())
       (function_declaration_header 19
        ((missing 0 ())
         (((end_of_line 1) (single_line_comment 27) (end_of_line 1)) function
          8 ((whitespace 1)))
         (error 8 ((() abstract 8 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() array 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 16
      ((missing 0 ())
       (function_declaration_header 13
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 2 ((() as 2 ()))) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() async 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() await 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() break 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 18
      ((missing 0 ())
       (function_declaration_header 15
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 4 ((() case 4 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() catch 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() class 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() clone 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() const 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 22
      ((missing 0 ())
       (function_declaration_header 19
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 8 ((() continue 8 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 21
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 7 ((() default 7 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 16
      ((missing 0 ())
       (function_declaration_header 13
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 2 ((() do 2 ()))) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 18
      ((missing 0 ())
       (function_declaration_header 15
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 4 ((() echo 4 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 18
      ((missing 0 ())
       (function_declaration_header 15
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 4 ((() else 4 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 20
      ((missing 0 ())
       (function_declaration_header 17
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 6 ((() elseif 6 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 20
      ((missing 0 ())
       (function_declaration_header 17
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 6 ((() endfor 6 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 24
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 10 ((() endforeach 10 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() endif 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 23
      ((missing 0 ())
       (function_declaration_header 20
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 9 ((() endswitch 9 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 22
      ((missing 0 ())
       (function_declaration_header 19
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 8 ((() endwhile 8 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 18
      ((missing 0 ())
       (function_declaration_header 15
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 4 ((() eval 4 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 21
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 7 ((() extends 7 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() final 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 21
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 7 ((() finally 7 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 17
      ((missing 0 ())
       (function_declaration_header 14
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 3 ((() for 3 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 21
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 7 ((() foreach 7 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 22
      ((missing 0 ())
       (function_declaration_header 19
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 8 ((() function 8 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 20
      ((missing 0 ())
       (function_declaration_header 17
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 6 ((() global 6 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 18
      ((missing 0 ())
       (function_declaration_header 15
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 4 ((() goto 4 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 16
      ((missing 0 ())
       (function_declaration_header 13
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 2 ((() if 2 ()))) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 24
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 10 ((() implements 10 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 21
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 7 ((() include 7 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 26
      ((missing 0 ())
       (function_declaration_header 23
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 12 ((() include_once 12 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() inout 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 24
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 10 ((() instanceof 10 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 23
      ((missing 0 ())
       (function_declaration_header 20
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 9 ((() insteadof 9 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 23
      ((missing 0 ())
       (function_declaration_header 20
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 9 ((() interface 9 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 18
      ((missing 0 ())
       (function_declaration_header 15
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 4 ((() list 4 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 23
      ((missing 0 ())
       (function_declaration_header 20
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 9 ((() namespace 9 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 17
      ((missing 0 ())
       (function_declaration_header 14
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 3 ((() new 3 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() print 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 21
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 7 ((() private 7 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 23
      ((missing 0 ())
       (function_declaration_header 20
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 9 ((() protected 9 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 20
      ((missing 0 ())
       (function_declaration_header 17
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 6 ((() public 6 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 21
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 7 ((() require 7 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 26
      ((missing 0 ())
       (function_declaration_header 23
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 12 ((() require_once 12 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 20
      ((missing 0 ())
       (function_declaration_header 17
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 6 ((() return 6 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() shape 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 20
      ((missing 0 ())
       (function_declaration_header 17
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 6 ((() static 6 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 20
      ((missing 0 ())
       (function_declaration_header 17
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 6 ((() switch 6 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() throw 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() trait 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 17
      ((missing 0 ())
       (function_declaration_header 14
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 3 ((() try 3 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 17
      ((missing 0 ())
       (function_declaration_header 14
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 3 ((() use 3 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() using 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 17
      ((missing 0 ())
       (function_declaration_header 14
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 3 ((() var 3 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() while 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 19
      ((missing 0 ())
       (function_declaration_header 16
        ((missing 0 ()) (() function 8 ((whitespace 1)))
         (error 5 ((() yield 5 ()))) (missing 0 ()) (() "(" 1 ())
         (missing 0 ()) (() ")" 1 ((whitespace 1))) (missing 0 ())
         (missing 0 ()) (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (expression_statement 8
      ((array_intrinsic_expression 7
        ((((end_of_line 1) (single_line_comment 153) (end_of_line 1)) array 5
          ())
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 5
      ((function_call_expression 4
        ((() as 2 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((lambda_expression 7
        ((missing 0 ()) (() async 5 ()) (missing 0 ())
         (lambda_signature 2
          ((() "(" 1 ()) (missing 0 ()) (() ")" 1 ()) (missing 0 ())
           (missing 0 ())))
         (missing 0 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((prefix_unary_expression 7
        ((() await 5 ())
         (parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (break_statement 5 ((() break 5 ()) (missing 0 ())))
     (expression_statement 3
      ((parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (case_label 7
      ((() case 4 ())
       (parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((function_call_expression 7
        ((() catch 5 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((prefix_unary_expression 7
        ((((single_line_comment 150) (end_of_line 1)) clone 5 ())
         (parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (const_declaration 5
      ((missing 0 ()) (() const 5 ()) (missing 0 ())
       (list 0
        ((list_item 0
          ((constant_declarator 0 ((missing 0 ()) (missing 0 ())))
           (missing 0 ())))))
       (missing 0 ())))
     (expression_statement 3
      ((parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (continue_statement 8 ((() continue 8 ()) (missing 0 ())))
     (expression_statement 3
      ((parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 10
      ((function_call_expression 9
        ((() name 7 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (default_label 7 ((() default 7 ()) (missing 0 ())))
     (expression_statement 3
      ((parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (do_statement 13
      ((() do 2 ())
       (expression_statement 3
        ((parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
         (() ";" 1 ((end_of_line 1)))))
       (missing 0 ()) (((extra_token_error 4)) "(" 1 ()) (() ")" 1 ())
       (missing 0 ()) (() ";" 1 ((end_of_line 1)))))
     (expression_statement 7
      ((function_call_expression 6
        ((() else 4 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 9
      ((function_call_expression 8
        ((() elseif 6 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 9
      ((function_call_expression 8
        ((() endfor 6 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 13
      ((function_call_expression 12
        ((() endforeach 10 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 13
      ((function_call_expression 12
        ((() name 10 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((function_call_expression 7
        ((() endif 5 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 12
      ((function_call_expression 11
        ((() endswitch 9 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 11
      ((function_call_expression 10
        ((() endwhile 8 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 7
      ((eval_expression 6
        ((() eval 4 ()) (() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 10
      ((function_call_expression 9
        ((() extends 7 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 10
      ((function_call_expression 9
        ((((single_line_comment 150) (end_of_line 1)) finally 7 ())
         (missing 0 ()) (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (for_statement 39
      ((() for 3 ()) (() "(" 1 ())
       (list 1 ((list_item 1 ((() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))
       (list 9
        ((list_item 9
          ((function_call_expression 9
            ((() foreach 7 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
             (() ")" 1 ())))
           (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))
       (list 11
        ((list_item 11
          ((anonymous_function 11
            ((missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
             (() function 8 ()) (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())
             (missing 0 ()) (missing 0 ()) (missing 0 ())
             (() ";" 1 ((end_of_line 1)))))
           (missing 0 ())))))
       (missing 0 ())
       (expression_statement 9
        ((function_call_expression 8
          ((() global 6 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
           (() ")" 1 ())))
         (() ";" 1 ((end_of_line 1)))))))
     (goto_statement 7
      ((() goto 4 ()) (() "(" 1 ())
       (((extra_token_error 1)) ";" 1 ((end_of_line 1)))))
     (if_statement 5
      ((() if 2 ()) (() "(" 1 ()) (() ")" 1 ()) (missing 0 ())
       (expression_statement 1 ((missing 0 ()) (() ";" 1 ((end_of_line 1)))))
       (missing 0 ()) (missing 0 ())))
     (expression_statement 13
      ((function_call_expression 12
        ((() implements 10 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (inclusion_directive 10
      ((inclusion_expression 9
        ((() include 7 ())
         (parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (inclusion_directive 15
      ((inclusion_expression 14
        ((() include_once 12 ())
         (parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((function_call_expression 7
        ((() inout 5 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 13
      ((function_call_expression 12
        ((() instanceof 10 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 12
      ((function_call_expression 11
        ((() insteadof 9 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 7
      ((list_expression 6
        ((((single_line_comment 154) (end_of_line 1)) list 4 ())
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (namespace_declaration 9
      ((() namespace 9 ()) (missing 0 ())
       (namespace_body 0 ((missing 0 ()) (missing 0 ()) (missing 0 ())))))
     (expression_statement 3
      ((parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 6
      ((object_creation_expression 5
        ((() new 3 ())
         (constructor_call 2
          ((parenthesized_expression 2
            ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
           (missing 0 ()) (missing 0 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((prefix_unary_expression 7
        ((() print 5 ())
         (parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 10
      ((function_call_expression 9
        ((() private 7 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 12
      ((function_call_expression 11
        ((() protected 9 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 9
      ((function_call_expression 8
        ((() public 6 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (inclusion_directive 10
      ((inclusion_expression 9
        ((() require 7 ())
         (parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (inclusion_directive 15
      ((inclusion_expression 14
        ((() require_once 12 ())
         (parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (return_statement 9
      ((() return 6 ())
       (parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 8
      ((shape_expression 7
        ((() shape 5 ()) (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 3
      ((lambda_expression 2
        ((missing 0 ()) (missing 0 ()) (missing 0 ())
         (lambda_signature 2
          ((((extra_token_error 6)) "(" 1 ()) (missing 0 ()) (() ")" 1 ())
           (missing 0 ()) (missing 0 ())))
         (missing 0 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (throw_statement 8
      ((((single_line_comment 145) (end_of_line 1)) throw 5 ())
       (parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (namespace_use_declaration 3
      ((((single_line_comment 150) (end_of_line 1) (single_line_comment 143)
         (end_of_line 1))
        use 3 ())
       (missing 0 ())
       (list 0
        ((list_item 0
          ((namespace_use_clause 0
            ((missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())))
           (missing 0 ())))))
       (missing 0 ())))
     (expression_statement 3
      ((parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (using_statement_function_scoped 8
      ((missing 0 ()) (() using 5 ())
       (parenthesized_expression 2
        ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 6
      ((function_call_expression 5
        ((() var 3 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (while_statement 8
      ((() while 5 ()) (() "(" 1 ()) (() ")" 1 ()) (missing 0 ())
       (expression_statement 1 ((missing 0 ()) (() ";" 1 ((end_of_line 1)))))))
     (expression_statement 8
      ((yield_expression 7
        ((() yield 5 ())
         (parenthesized_expression 2
          ((() "(" 1 ()) (() ")" 1 ()) (missing 0 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
