(4,18)-(4,18) A name or __construct keyword is expected here.
(5,15)-(5,15) A name or __construct keyword is expected here.
(6,12)-(6,12) A name or __construct keyword is expected here.
(7,15)-(7,15) A name or __construct keyword is expected here.
(8,15)-(8,15) A name or __construct keyword is expected here.
(9,15)-(9,15) A name or __construct keyword is expected here.
(10,14)-(10,14) A name or __construct keyword is expected here.
(11,15)-(11,15) A name or __construct keyword is expected here.
(12,15)-(12,15) A name or __construct keyword is expected here.
(13,15)-(13,15) A name or __construct keyword is expected here.
(14,15)-(14,15) A name or __construct keyword is expected here.
(15,18)-(15,18) A name or __construct keyword is expected here.
(16,17)-(16,17) A name or __construct keyword is expected here.
(17,12)-(17,12) A name or __construct keyword is expected here.
(18,14)-(18,14) A name or __construct keyword is expected here.
(19,14)-(19,14) A name or __construct keyword is expected here.
(20,16)-(20,16) A name or __construct keyword is expected here.
(21,16)-(21,16) A name or __construct keyword is expected here.
(22,20)-(22,20) A name or __construct keyword is expected here.
(23,15)-(23,15) A name or __construct keyword is expected here.
(24,19)-(24,19) A name or __construct keyword is expected here.
(25,18)-(25,18) A name or __construct keyword is expected here.
(26,14)-(26,14) A name or __construct keyword is expected here.
(27,17)-(27,17) A name or __construct keyword is expected here.
(28,15)-(28,15) A name or __construct keyword is expected here.
(29,17)-(29,17) A name or __construct keyword is expected here.
(30,13)-(30,13) A name or __construct keyword is expected here.
(31,17)-(31,17) A name or __construct keyword is expected here.
(32,18)-(32,18) A name or __construct keyword is expected here.
(33,16)-(33,16) A name or __construct keyword is expected here.
(34,14)-(34,14) A name or __construct keyword is expected here.
(35,12)-(35,12) A name or __construct keyword is expected here.
(36,20)-(36,20) A name or __construct keyword is expected here.
(37,17)-(37,17) A name or __construct keyword is expected here.
(38,22)-(38,22) A name or __construct keyword is expected here.
(39,15)-(39,15) A name or __construct keyword is expected here.
(40,20)-(40,20) A name or __construct keyword is expected here.
(41,19)-(41,19) A name or __construct keyword is expected here.
(42,19)-(42,19) A name or __construct keyword is expected here.
(43,14)-(43,14) A name or __construct keyword is expected here.
(44,19)-(44,19) A name or __construct keyword is expected here.
(45,13)-(45,13) A name or __construct keyword is expected here.
(46,15)-(46,15) A name or __construct keyword is expected here.
(47,17)-(47,17) A name or __construct keyword is expected here.
(48,19)-(48,19) A name or __construct keyword is expected here.
(49,16)-(49,16) A name or __construct keyword is expected here.
(50,17)-(50,17) A name or __construct keyword is expected here.
(51,22)-(51,22) A name or __construct keyword is expected here.
(52,16)-(52,16) A name or __construct keyword is expected here.
(53,15)-(53,15) A name or __construct keyword is expected here.
(54,16)-(54,16) A name or __construct keyword is expected here.
(55,16)-(55,16) A name or __construct keyword is expected here.
(56,15)-(56,15) A name or __construct keyword is expected here.
(57,15)-(57,15) A name or __construct keyword is expected here.
(58,13)-(58,13) A name or __construct keyword is expected here.
(59,13)-(59,13) A name or __construct keyword is expected here.
(60,15)-(60,15) A name or __construct keyword is expected here.
(61,13)-(61,13) A name or __construct keyword is expected here.
(62,15)-(62,15) A name or __construct keyword is expected here.
(63,15)-(63,15) A name or __construct keyword is expected here.
(67,3)-(67,3) An expression is expected here.
(68,8)-(68,8) A lambda arrow ('==>') is expected here.
(69,8)-(69,8) An expression is expected here.
(70,6)-(70,6) A semicolon (';') is expected here.
(70,8)-(70,8) An expression is expected here.
(71,7)-(71,7) An expression is expected here.
(71,7)-(71,7) A colon (':') is expected here.
(71,8)-(72,1) A case statement may only appear directly inside a switch.
(72,6)-(72,6) An expression is expected here.
(74,8)-(74,8) An expression is expected here.
(75,6)-(75,6) A name is expected here.
(75,6)-(75,6) A concrete constant declaration must have an initializer.
(75,8)-(75,8) An expression is expected here.
(76,9)-(76,9) A semicolon (';') is expected here.
(76,11)-(76,11) An expression is expected here.
(78,8)-(78,8) A colon (':') is expected here.
(78,10)-(78,10) An expression is expected here.
(79,5)-(79,5) An expression is expected here.
(79,6)-(80,1) The 'while' keyword is expected here.
(80,1)-(80,5) Encountered unexpected token 'echo'.
(80,7)-(80,7) An expression is expected here.
(81,5)-(81,5) An expression is expected here.
(82,7)-(82,7) An expression is expected here.
(83,7)-(83,7) An expression is expected here.
(84,11)-(84,11) An expression is expected here.
(86,6)-(86,6) An expression is expected here.
(87,10)-(87,10) An expression is expected here.
(88,9)-(88,9) An expression is expected here.
(89,7)-(89,7) An expression is expected here.
(90,8)-(90,8) An expression is expected here.
(92,8)-(92,8) An expression is expected here.
(93,6)-(93,6) An expression is expected here.
(94,8)-(94,8) An expression is expected here.
(95,12)-(96,1) A right parenthesis (')') is expected here.
(96,7)-(96,7) An expression is expected here.
(97,6)-(97,7) Encountered unexpected token ')'.
(98,5)-(98,5) An expression is expected here.
(99,11)-(99,11) An expression is expected here.
(100,10)-(100,10) An expression is expected here.
(101,15)-(101,15) An expression is expected here.
(102,6)-(102,6) An expression is expected here.
(103,11)-(103,11) An expression is expected here.
(104,10)-(104,10) An expression is expected here.
(107,1)-(107,9) No code may exist outside of namespace {}
(107,1)-(107,9) Namespace declaration statement has to be the very first statement in the script
(107,10)-(107,10) A name is expected here.
(107,12)-(107,12) An expression is expected here.
(108,4)-(108,5) A constructor initializing an object must be passed a (possibly empty) list of arguments. Did you mean 'new ()()'?
(108,6)-(108,6) An expression is expected here.
(109,8)-(109,8) An expression is expected here.
(110,8)-(110,8) An expression is expected here.
(111,10)-(111,10) An expression is expected here.
(112,7)-(112,7) An expression is expected here.
(113,10)-(113,10) An expression is expected here.
(114,15)-(114,15) An expression is expected here.
(115,9)-(115,9) An expression is expected here.
(117,1)-(117,7) Encountered unexpected token 'static'.
(117,9)-(117,9) A lambda arrow ('==>') is expected here.
(119,8)-(119,8) An expression is expected here.
(122,4)-(122,4) A name is expected here.
(122,6)-(122,6) An expression is expected here.
(123,1)-(123,8) Using statement in function scoped form may only be used at the top level of a function or a method
(123,8)-(123,8) An expression is expected here.
(124,4)-(124,4) An expression is expected here.
(125,8)-(125,8) An expression is expected here.
(126,1)-(126,7) Yield can only be used inside a function
(126,8)-(126,8) An expression is expected here.
