((script 276
  ((list 276
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 63
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((delimited_comment 206) (end_of_line 1) (end_of_line 1)) class 5
        ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 55
        ((() { 1 ((end_of_line 1)))
         (list 49
          ((methodish_declaration 49
            ((missing 0 ())
             (function_declaration_header 27
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
               (() "(" 1 ())
               (list 2
                ((list_item 2
                  ((parameter_declaration 2
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (missing 0 ()) (() variable 2 ()) (missing 0 ())))
                   (missing 0 ())))))
               (() ")" 1 ()) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 21
              ((() { 1 ((end_of_line 1)))
               (list 11
                ((expression_statement 11
                  ((binary_expression 10
                    ((variable 5
                      ((((whitespace 4)) variable 5 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (variable 2 ((() variable 2 ())))))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
