((script 828
  ((list 828
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (classish_declaration 812
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 804
        ((() { 1 ((end_of_line 1)))
         (list 769
          ((methodish_declaration 38
            ((missing 0 ())
             (function_declaration_header 35
              ((list 14
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() private 7 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 35
            ((missing 0 ())
             (function_declaration_header 32
              ((list 11
                ((((whitespace 2)) final 5 ((whitespace 1)))
                 (() final 5 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 44
            ((missing 0 ())
             (function_declaration_header 42
              ((list 21
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() abstract 8 ((whitespace 1)))
                 (() final 5 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (missing 0 ()) (() ";" 1 ((end_of_line 1)))))
           (methodish_declaration 39
            ((missing 0 ())
             (function_declaration_header 37
              ((list 16
                ((((whitespace 2)) private 7 ((whitespace 1)))
                 (() abstract 8 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (missing 0 ()) (() ";" 1 ((end_of_line 1)))))
           (methodish_declaration 46
            ((missing 0 ())
             (function_declaration_header 43
              ((list 22
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() abstract 8 ((whitespace 1)))
                 (() static 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 45
            ((missing 0 ())
             (function_declaration_header 43
              ((list 22
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() abstract 8 ((whitespace 1)))
                 (() static 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (missing 0 ()) (() ";" 1 ((end_of_line 1)))))
           (methodish_declaration 29
            ((missing 0 ())
             (function_declaration_header 27
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (missing 0 ()) (() ";" 1 ((end_of_line 1)))))
           (methodish_declaration 40
            ((missing 0 ())
             (function_declaration_header 37
              ((list 13
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() static 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1)))
               (() __construct 11 ((whitespace 1))) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 46
            ((missing 0 ())
             (function_declaration_header 43
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1)))
               (() __construct 11 ((whitespace 1))) (missing 0 ())
               (() "(" 1 ())
               (list 13
                ((list_item 13
                  ((parameter_declaration 13
                    ((missing 0 ()) (() public 6 ((whitespace 1)))
                     (missing 0 ())
                     (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
                     (() variable 2 ()) (missing 0 ())))
                   (missing 0 ())))))
               (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 41
            ((missing 0 ())
             (function_declaration_header 39
              ((list 15
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() abstract 8 ((whitespace 1)))))
               (() function 8 ((whitespace 1)))
               (() __construct 11 ((whitespace 1))) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (missing 0 ()) (() ";" 1 ((end_of_line 1)))))
           (methodish_declaration 42
            ((missing 0 ())
             (function_declaration_header 39
              ((list 15
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() abstract 8 ((whitespace 1)))))
               (() function 8 ((whitespace 1)))
               (() __construct 11 ((whitespace 1))) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 43
            ((missing 0 ())
             (function_declaration_header 40
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ())
               (list 13
                ((list_item 13
                  ((parameter_declaration 13
                    ((missing 0 ()) (() public 6 ((whitespace 1)))
                     (missing 0 ())
                     (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
                     (() variable 2 ()) (missing 0 ())))
                   (missing 0 ())))))
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 39
            ((missing 0 ())
             (function_declaration_header 36
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1)))
               (() __construct 11 ((whitespace 1))) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (() : 1 ((whitespace 1)))
               (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 40
            ((missing 0 ())
             (function_declaration_header 37
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1)))
               (() __construct 11 ((whitespace 1))) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 33
            ((missing 0 ())
             (function_declaration_header 30
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ())
               (list 3
                ((list_item 3
                  ((variadic_parameter 3
                    ((missing 0 ()) (missing 0 ()) (() ... 3 ())))
                   (missing 0 ())))))
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ())
               (() } 1
                ((whitespace 1) (single_line_comment 12) (end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 34
            ((missing 0 ())
             (function_declaration_header 31
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ())
               (list 4
                ((list_item 4
                  ((variadic_parameter 3
                    ((missing 0 ()) (missing 0 ()) (() ... 3 ())))
                   (() , 1 ())))))
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ())
               (() } 1
                ((whitespace 1) (single_line_comment 32) (end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 41
            ((missing 0 ())
             (function_declaration_header 38
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ((whitespace 1)))
               (missing 0 ()) (() "(" 1 ())
               (list 11
                ((list_item 4
                  ((variadic_parameter 3
                    ((missing 0 ()) (missing 0 ()) (() ... 3 ())))
                   (() , 1 ((whitespace 1)))))
                 (list_item 6
                  ((parameter_declaration 6
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
                     (() variable 2 ()) (missing 0 ())))
                   (missing 0 ())))))
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ())
               (() } 1
                ((whitespace 1) (single_line_comment 28) (end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
