(5,17)-(5,17) A semicolon is expected here.
(5,19)-(5,19) A semicolon is expected here.
(5,21)-(5,21) An expression is expected here.
(5,21)-(5,23) Encountered unexpected token '34'.
(3,7)-(3,15) A constructor initializing an object must be passed a (possibly empty) list of arguments. Did you mean 'new Point()'?
(5,7)-(5,15) A constructor initializing an object must be passed a (possibly empty) list of arguments. Did you mean 'new Point()'?
(7,7)-(7,38) A constructor initializing an object must be passed a (possibly empty) list of arguments. Did you mean 'new RReeaallllyyLLoonnggNNaammee()'?
