(3,11)-(3,15) A constructor initializing an object must be passed a (possibly empty) list of arguments. Did you mean 'new Point()'?
(5,11)-(5,15) A constructor initializing an object must be passed a (possibly empty) list of arguments. Did you mean 'new Point()'?
(5,17)-(5,17) A semicolon (';') is expected here.
(5,19)-(5,19) A semicolon (';') is expected here.
(5,21)-(5,21) An expression is expected here.
(5,21)-(5,23) Encountered unexpected token '34'.
(7,11)-(7,38) A constructor initializing an object must be passed a (possibly empty) list of arguments. Did you mean 'new RReeaallllyyLLoonnggNNaammee()'?
(10,11)-(10,17) Unexpected node on right hand side of instanceof: literal
(11,11)-(11,22) A scope resolution (::) on the right side of an instanceof operator must start with a class name, `self`, `parent`, or `static`, and end with a variable
(13,11)-(13,22) A scope resolution (::) on the right side of an instanceof operator must start with a class name, `self`, `parent`, or `static`, and end with a variable
(13,11)-(13,33) Only classnames and variables are allowed before '::'.
(14,11)-(14,37) Only classnames and variables are allowed before '::'.
