((script 14
  ((list 14
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (expression_statement 8
      ((binary_expression 7
        ((variable 2 ((((end_of_line 1)) variable 2 ()))) (() ?: 2 ())
         (function_call_expression 3
          ((() name 1 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
           (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
