((script 103
  ((list 103
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (alias_declaration 16
      ((missing 0 ()) (((end_of_line 1)) type 4 ((whitespace 1)))
       (() name 2 ())
       (type_parameters 3
        ((() < 1 ())
         (list 1
          ((list_item 1
            ((type_parameter 1
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (() name 1 ())
               (missing 0 ())))
             (missing 0 ())))))
         (() > 1 ((whitespace 1)))))
       (missing 0 ()) (() = 1 ((whitespace 1)))
       (simple_type_specifier 2 ((() name 2 ())))
       (() ";" 1 ((end_of_line 1)))))
     (alias_declaration 13
      ((missing 0 ()) (() type 4 ((whitespace 1)))
       (() name 2 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (() = 1 ((whitespace 1))) (simple_type_specifier 2 ((() name 2 ())))
       (() ";" 1 ((end_of_line 1)))))
     (alias_declaration 16
      ((missing 0 ()) (() type 4 ((whitespace 1))) (() name 2 ())
       (type_parameters 3
        ((() < 1 ())
         (list 1
          ((list_item 1
            ((type_parameter 1
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (() name 1 ())
               (missing 0 ())))
             (missing 0 ())))))
         (() > 1 ((whitespace 1)))))
       (missing 0 ()) (() = 1 ((whitespace 1)))
       (simple_type_specifier 2 ((() name 2 ())))
       (() ";" 1 ((end_of_line 1)))))
     (alias_declaration 18
      ((missing 0 ()) (() type 4 ((whitespace 1))) (() name 2 ())
       (type_parameters 6
        ((() < 1 ())
         (list 4
          ((list_item 2
            ((type_parameter 1
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (() name 1 ())
               (missing 0 ())))
             (() , 1 ((whitespace 1)))))
           (list_item 1
            ((type_parameter 1
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (() name 1 ())
               (missing 0 ())))
             (missing 0 ())))))
         (() > 1 ((whitespace 1)))))
       (missing 0 ()) (() = 1 ((whitespace 1)))
       (simple_type_specifier 1 ((() name 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (alias_declaration 20
      ((missing 0 ()) (() type 4 ((whitespace 1))) (() name 2 ())
       (type_parameters 8
        ((() < 1 ())
         (list 6
          ((list_item 4
            ((type_parameter 3
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (() name 3 ())
               (missing 0 ())))
             (() , 1 ((whitespace 1)))))
           (list_item 1
            ((type_parameter 1
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (() name 1 ())
               (missing 0 ())))
             (missing 0 ())))))
         (() > 1 ((whitespace 1)))))
       (missing 0 ()) (() = 1 ((whitespace 1)))
       (simple_type_specifier 1 ((() name 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
