((script 67
  ((list 67
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 62
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (() class 5 ((whitespace 1))) (() name 1 ((whitespace 1)))
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ())
       (classish_body 54
        ((() { 1 ((end_of_line 1)))
         (list 48
          ((type_const_declaration 20
            ((missing 0 ()) (missing 0 ())
             (((whitespace 2)) const 5 ((whitespace 1)))
             (() type 4 ((whitespace 1))) (() name 2 ((whitespace 1)))
             (missing 0 ()) (missing 0 ()) (() = 1 ((whitespace 1)))
             (simple_type_specifier 3 ((() int 3 ())))
             (() ";" 1 ((end_of_line 1)))))
           (type_const_declaration 25
            ((missing 0 ()) (missing 0 ())
             (((whitespace 2)) const 5 ((whitespace 1)))
             (() type 4 ((whitespace 1))) (() name 2 ((whitespace 1)))
             (missing 0 ())
             (type_constraint 5
              ((() as 2 ((whitespace 1)))
               (simple_type_specifier 2 ((() name 2 ((whitespace 1)))))))
             (() = 1 ((whitespace 1)))
             (simple_type_specifier 2 ((() name 2 ())))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
