((script 670
  ((list 670
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (expression_statement 8
      ((function_call_expression 7
        ((((end_of_line 1) (single_line_comment 51) (end_of_line 1)) name 1
          ())
         (missing 0 ()) (() "(" 1 ())
         (list 4
          ((list_item 4
            ((literal 4 ((() single_quoted_string_literal 4 ())))
             (missing 0 ())))))
         (() ")" 1 ())))
       (() ";" 1 ((whitespace 1) (single_line_comment 36) (end_of_line 1)))))
     (expression_statement 20
      ((function_call_expression 19
        ((() name 2 ())
         (type_arguments 8
          ((() < 1 ())
           (list 6
            ((list_item 6
              ((simple_type_specifier 6 ((() string 6 ()))) (missing 0 ())))))
           (() > 1 ())))
         (() "(" 1 ())
         (list 7
          ((list_item 7
            ((literal 7 ((() single_quoted_string_literal 7 ())))
             (missing 0 ())))))
         (() ")" 1 ())))
       (() ";" 1 ((whitespace 1) (single_line_comment 26) (end_of_line 1)))))
     (expression_statement 20
      ((function_call_expression 19
        ((() name 3 ()) (missing 0 ()) (() "(" 1 ())
         (list 14
          ((list_item 6
            ((binary_expression 5
              ((literal 1 ((() decimal_literal 1 ((whitespace 1)))))
               (() < 1 ((whitespace 1)))
               (literal 1 ((() decimal_literal 1 ())))))
             (() , 1 ((whitespace 1)))))
           (list_item 7
            ((tuple_expression 7
              ((() tuple 5 ()) (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
             (missing 0 ())))))
         (() ")" 1 ())))
       (() ";" 1 ((whitespace 1) (single_line_comment 48) (end_of_line 1)))))
     (expression_statement 24
      ((function_call_expression 23
        ((() name 4 ()) (missing 0 ()) (() "(" 1 ())
         (list 17
          ((list_item 8
            ((binary_expression 7
              ((() name 3 ((whitespace 1))) (() < 1 ((whitespace 1)))
               (literal 1 ((() decimal_literal 1 ())))))
             (() , 1 ((whitespace 1)))))
           (list_item 8
            ((binary_expression 8
              ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
               (() > 1 ((whitespace 1))) (() name 3 ())))
             (missing 0 ())))))
         (() ")" 1 ())))
       (() ";" 1 ((whitespace 1) (single_line_comment 44) (end_of_line 1)))))
     (expression_statement 25
      ((function_call_expression 24
        ((() name 5 ()) (missing 0 ()) (() "(" 1 ())
         (list 17
          ((list_item 17
            ((function_call_expression 17
              ((() name 3 ())
               (type_arguments 12
                ((() < 1 ())
                 (list 10
                  ((list_item 4
                    ((simple_type_specifier 3 ((() int 3 ()))) (() , 1 ())))
                   (list_item 6
                    ((simple_type_specifier 6 ((() string 6 ())))
                     (missing 0 ())))))
                 (() > 1 ())))
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
             (missing 0 ())))))
         (() ")" 1 ())))
       (() ";" 1 ((whitespace 1) (single_line_comment 36) (end_of_line 1)))))
     (expression_statement 25
      ((binary_expression 24
        ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
         (() * 1 ((whitespace 1)))
         (function_call_expression 19
          ((() name 2 ())
           (type_arguments 8
            ((() < 1 ())
             (list 6
              ((list_item 6
                ((simple_type_specifier 6 ((() string 6 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ())
           (list 7
            ((list_item 7
              ((literal 7 ((() single_quoted_string_literal 7 ())))
               (missing 0 ())))))
           (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 17
      ((binary_expression 16
        ((variable 2 ((((end_of_line 1)) variable 2 ((whitespace 1)))))
         (() ?? 2 ((whitespace 1)))
         (function_call_expression 10
          ((() name 3 ())
           (type_arguments 5
            ((() < 1 ())
             (list 3
              ((list_item 3
                ((simple_type_specifier 3 ((() name 3 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 16
      ((binary_expression 15
        ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
         (() * 1 ((whitespace 1)))
         (function_call_expression 10
          ((() name 3 ())
           (type_arguments 5
            ((() < 1 ())
             (list 3
              ((list_item 3
                ((simple_type_specifier 3 ((() name 3 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 18
      ((binary_expression 17
        ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
         (() * 1 ((whitespace 1)))
         (function_call_expression 12
          ((() name 3 ())
           (type_arguments 5
            ((() < 1 ())
             (list 3
              ((list_item 3
                ((simple_type_specifier 3 ((() name 3 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ())
           (list 2
            ((list_item 2 ((variable 2 ((() variable 2 ()))) (missing 0 ())))))
           (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 22
      ((binary_expression 21
        ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
         (() * 1 ((whitespace 1)))
         (function_call_expression 16
          ((() name 3 ())
           (type_arguments 5
            ((() < 1 ())
             (list 3
              ((list_item 3
                ((simple_type_specifier 3 ((() name 3 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ())
           (list 6
            ((list_item 3
              ((variable 2 ((() variable 2 ()))) (() , 1 ((whitespace 1)))))
             (list_item 2 ((variable 2 ((() variable 2 ()))) (missing 0 ())))))
           (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 19
      ((binary_expression 18
        ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
         (() * 1 ((whitespace 1)))
         (function_call_expression 13
          ((scope_resolution_expression 6
            ((() name 1 ()) (() :: 2 ()) (() name 3 ())))
           (type_arguments 5
            ((() < 1 ())
             (list 3
              ((list_item 3
                ((simple_type_specifier 3 ((() name 3 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 21
      ((binary_expression 20
        ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
         (() * 1 ((whitespace 1)))
         (function_call_expression 15
          ((scope_resolution_expression 6
            ((() name 1 ()) (() :: 2 ()) (() name 3 ())))
           (type_arguments 5
            ((() < 1 ())
             (list 3
              ((list_item 3
                ((simple_type_specifier 3 ((() name 3 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ())
           (list 2
            ((list_item 2 ((variable 2 ((() variable 2 ()))) (missing 0 ())))))
           (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 25
      ((binary_expression 24
        ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
         (() * 1 ((whitespace 1)))
         (function_call_expression 19
          ((scope_resolution_expression 6
            ((() name 1 ()) (() :: 2 ()) (() name 3 ())))
           (type_arguments 5
            ((() < 1 ())
             (list 3
              ((list_item 3
                ((simple_type_specifier 3 ((() name 3 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ())
           (list 6
            ((list_item 3
              ((variable 2 ((() variable 2 ()))) (() , 1 ((whitespace 1)))))
             (list_item 2 ((variable 2 ((() variable 2 ()))) (missing 0 ())))))
           (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 16
      ((function_call_expression 15
        ((() name 3 ()) (missing 0 ()) (() "(" 1 ())
         (list 10
          ((list_item 10
            ((function_call_expression 10
              ((() name 3 ())
               (type_arguments 5
                ((() < 1 ())
                 (list 3
                  ((list_item 3
                    ((simple_type_specifier 3 ((() name 3 ())))
                     (missing 0 ())))))
                 (() > 1 ())))
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
             (missing 0 ())))))
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 18
      ((function_call_expression 17
        ((() name 3 ()) (missing 0 ()) (() "(" 1 ())
         (list 12
          ((list_item 12
            ((function_call_expression 12
              ((() name 3 ())
               (type_arguments 5
                ((() < 1 ())
                 (list 3
                  ((list_item 3
                    ((simple_type_specifier 3 ((() name 3 ())))
                     (missing 0 ())))))
                 (() > 1 ())))
               (() "(" 1 ())
               (list 2
                ((list_item 2
                  ((variable 2 ((() variable 2 ()))) (missing 0 ())))))
               (() ")" 1 ())))
             (missing 0 ())))))
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 22
      ((function_call_expression 21
        ((() name 3 ()) (missing 0 ()) (() "(" 1 ())
         (list 16
          ((list_item 16
            ((function_call_expression 16
              ((() name 3 ())
               (type_arguments 5
                ((() < 1 ())
                 (list 3
                  ((list_item 3
                    ((simple_type_specifier 3 ((() name 3 ())))
                     (missing 0 ())))))
                 (() > 1 ())))
               (() "(" 1 ())
               (list 6
                ((list_item 3
                  ((variable 2 ((() variable 2 ())))
                   (() , 1 ((whitespace 1)))))
                 (list_item 2
                  ((variable 2 ((() variable 2 ()))) (missing 0 ())))))
               (() ")" 1 ())))
             (missing 0 ())))))
         (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 15
      ((binary_expression 14
        ((() name 3 ()) (() < 1 ())
         (function_call_expression 10
          ((() name 3 ())
           (type_arguments 5
            ((() < 1 ())
             (list 3
              ((list_item 3
                ((simple_type_specifier 3 ((() name 3 ()))) (missing 0 ())))))
             (() > 1 ())))
           (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 14
      ((binary_expression 13
        ((binary_expression 8
          ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
           (() * 1 ((whitespace 1))) (() name 3 ((whitespace 1)))))
         (() < 1 ((whitespace 1))) (literal 2 ((() decimal_literal 2 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 19
      ((binary_expression 18
        ((binary_expression 8
          ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
           (() * 1 ((whitespace 1))) (() name 3 ((whitespace 1)))))
         (() < 1 ((whitespace 1)))
         (binary_expression 7
          ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
           (() + 1 ((whitespace 1))) (literal 2 ((() decimal_literal 2 ())))))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 23
      ((binary_expression 22
        ((binary_expression 13
          ((binary_expression 8
            ((literal 2 ((() decimal_literal 2 ((whitespace 1)))))
             (() * 1 ((whitespace 1))) (() name 3 ((whitespace 1)))))
           (() < 1 ((whitespace 1)))
           (literal 2 ((() decimal_literal 2 ((whitespace 1)))))))
         (() === 3 ((whitespace 1))) (literal 4 ((() boolean_literal 4 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
