((script 52
  ((list 52
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (function_declaration 36
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 3 ()) (missing 0 ()) (() "(" 1 ())
         (list 8
          ((list_item 8
            ((parameter_declaration 8
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (error 8 ((() function 8 ()))) (missing 0 ()) (missing 0 ())))
             (missing 0 ())))))
         (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())))
       (compound_statement 15
        ((missing 0 ())
         (list 15
          ((expression_statement 5
            ((parenthesized_expression 5
              ((() "(" 1 ()) (() ... 3 ()) (() ")" 1 ())))
             (missing 0 ())))
           (expression_statement 1 ((() ")" 1 ()) (missing 0 ())))
           (expression_statement 1
            ((() : 1 ((whitespace 1))) (missing 0 ())))
           (expression_statement 7
            ((collection_literal_expression 7
              ((simple_type_specifier 4 ((() name 4 ((whitespace 1)))))
               (() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (missing 0 ())))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
