((script 123
  ((list 123
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 44
      ((missing 0 ())
       (function_declaration_header 40
        ((missing 0 ()) (() function 8 ((whitespace 1))) (() name 3 ())
         (missing 0 ()) (() "(" 1 ())
         (list 19
          ((list_item 13
            ((parameter_declaration 12
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
               (() variable 4 ((whitespace 1)))
               (simple_initializer 3
                ((() = 1 ((whitespace 1)))
                 (literal 1 ((() decimal_literal 1 ())))))))
             (() , 1 ((whitespace 1)))))
           (list_item 5
            ((parameter_declaration 5
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
               (() variable 5 ()) (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 3
        ((() { 1 ((end_of_line 1))) (missing 0 ())
         (() } 1 ((end_of_line 1)))))))
     (classish_declaration 73
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (() class 5 ((whitespace 1))) (() name 1 ((whitespace 1)))
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ())
       (classish_body 65
        ((() { 1 ((end_of_line 1)))
         (list 59
          ((methodish_declaration 59
            ((missing 0 ())
             (function_declaration_header 53
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 3 ()) (missing 0 ())
               (() "(" 1 ())
               (list 25
                ((list_item 13
                  ((parameter_declaration 12
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
                     (() variable 4 ((whitespace 1)))
                     (simple_initializer 3
                      ((() = 1 ((whitespace 1)))
                       (literal 1 ((() decimal_literal 1 ())))))))
                   (() , 1 ((whitespace 1)))))
                 (list_item 6
                  ((parameter_declaration 5
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (missing 0 ()) (() variable 5 ()) (missing 0 ())))
                   (() , 1 ((whitespace 1)))))
                 (list_item 4
                  ((parameter_declaration 4
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (missing 0 ()) (() variable 4 ()) (missing 0 ())))
                   (missing 0 ())))))
               (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 5
              ((() { 1 ((end_of_line 1))) (missing 0 ())
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
