((script 217
  ((list 217
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (function_declaration 104
      ((missing 0 ())
       (function_declaration_header 58
        ((missing 0 ())
         (((end_of_line 1) (delimited_comment 95) (end_of_line 1)
           (end_of_line 1))
          function 8 ((whitespace 1)))
         (() name 3 ()) (missing 0 ()) (() "(" 1 ())
         (list 19
          ((list_item 19
            ((parameter_declaration 19
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (dictionary_type_specifier 16
                ((() dict 4 ()) (() < 1 ())
                 (list 10
                  ((list_item 4
                    ((simple_type_specifier 3 ((() int 3 ()))) (() , 1 ())))
                   (list_item 6
                    ((simple_type_specifier 5 ((() name 5 ()))) (() , 1 ())))))
                 (() > 1 ((whitespace 1)))))
               (() variable 2 ()) (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (dictionary_type_specifier 23
          ((() dict 4 ()) (() < 1 ((end_of_line 1)))
           (list 13
            ((list_item 4
              ((simple_type_specifier 3 ((((whitespace 2)) int 3 ())))
               (() , 1 ((end_of_line 1)))))
             (list_item 6
              ((simple_type_specifier 5 ((((whitespace 2)) name 5 ())))
               (() , 1 ((end_of_line 1)))))))
           (() > 1 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 45
        ((() { 1 ((end_of_line 1)))
         (list 10
          ((return_statement 10
            ((((whitespace 2) (fix_me 26) (end_of_line 1) (whitespace 2))
              return 6 ((whitespace 1)))
             (variable 2 ((() variable 2 ()))) (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
