((script 259
  ((list 259
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 39
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 31
        ((() { 1 ((end_of_line 1)))
         (list 25
          ((methodish_declaration 25
            ((missing 0 ())
             (function_declaration_header 22
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ())
               (type_parameters 3
                ((() < 1 ())
                 (list 1
                  ((list_item 1
                    ((type_parameter 1
                      ((missing 0 ()) (missing 0 ()) (missing 0 ())
                       (() name 1 ()) (missing 0 ())))
                     (missing 0 ())))))
                 (() > 1 ())))
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (classish_declaration 46
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (() class 5 ((whitespace 1))) (() name 1 ((whitespace 1)))
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ())
       (classish_body 38
        ((() { 1 ((end_of_line 1)))
         (list 32
          ((methodish_declaration 32
            ((missing 0 ())
             (function_declaration_header 29
              ((list 13
                ((((whitespace 2)) public 6 ((whitespace 1)))
                 (() static 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ())
               (type_parameters 3
                ((() < 1 ())
                 (list 1
                  ((list_item 1
                    ((type_parameter 1
                      ((missing 0 ()) (missing 0 ()) (missing 0 ())
                       (() name 1 ()) (missing 0 ())))
                     (missing 0 ())))))
                 (() > 1 ())))
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (expression_statement 9
      ((binary_expression 8
        ((variable 2 ((((end_of_line 1)) variable 2 ((whitespace 1)))))
         (() = 1 ((whitespace 1)))
         (literal 3 ((() single_quoted_string_literal 3 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 13
      ((binary_expression 12
        ((variable 2 ((() variable 2 ((whitespace 1)))))
         (() = 1 ((whitespace 1)))
         (object_creation_expression 7
          ((() new 3 ((whitespace 1)))
           (constructor_call 3
            ((simple_type_specifier 1 ((() name 1 ()))) (() "(" 1 ())
             (missing 0 ()) (() ")" 1 ())))))))
       (() ";" 1 ((end_of_line 1)))))
     (expression_statement 13
      ((function_call_expression 12
        ((member_selection_expression 5
          ((variable 2 ((((end_of_line 1)) variable 2 ()))) (() -> 2 ())
           (() name 1 ())))
         (type_arguments 5
          ((() < 1 ())
           (list 3
            ((list_item 3
              ((simple_type_specifier 3 ((() int 3 ()))) (missing 0 ())))))
           (() > 1 ())))
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((whitespace 2) (single_line_comment 5) (end_of_line 1)))))
     (expression_statement 14
      ((function_call_expression 13
        ((member_selection_expression 6
          ((variable 2 ((() variable 2 ()))) (() -> 2 ()) (() variable 2 ())))
         (type_arguments 5
          ((() < 1 ())
           (list 3
            ((list_item 3
              ((simple_type_specifier 3 ((() int 3 ()))) (missing 0 ())))))
           (() > 1 ())))
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((whitespace 1) (single_line_comment 14) (end_of_line 1)))))
     (expression_statement 14
      ((function_call_expression 13
        ((safe_member_selection_expression 6
          ((variable 2 ((((end_of_line 1)) variable 2 ()))) (() ?-> 3 ())
           (() name 1 ())))
         (type_arguments 5
          ((() < 1 ())
           (list 3
            ((list_item 3
              ((simple_type_specifier 3 ((() int 3 ()))) (missing 0 ())))))
           (() > 1 ())))
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((whitespace 1) (single_line_comment 5) (end_of_line 1)))))
     (expression_statement 15
      ((function_call_expression 14
        ((safe_member_selection_expression 7
          ((variable 2 ((() variable 2 ()))) (() ?-> 3 ())
           (() variable 2 ())))
         (type_arguments 5
          ((() < 1 ())
           (list 3
            ((list_item 3
              ((simple_type_specifier 3 ((() int 3 ()))) (missing 0 ())))))
           (() > 1 ())))
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((whitespace 1) (single_line_comment 15) (end_of_line 1)))))
     (expression_statement 12
      ((function_call_expression 11
        ((scope_resolution_expression 4
          ((((end_of_line 1)) name 1 ()) (() :: 2 ()) (() name 1 ())))
         (type_arguments 5
          ((() < 1 ())
           (list 3
            ((list_item 3
              ((simple_type_specifier 3 ((() int 3 ()))) (missing 0 ())))))
           (() > 1 ())))
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((whitespace 3) (single_line_comment 5) (end_of_line 1)))))
     (expression_statement 13
      ((function_call_expression 12
        ((scope_resolution_expression 5
          ((() name 1 ()) (() :: 2 ()) (() variable 2 ())))
         (type_arguments 5
          ((() < 1 ())
           (list 3
            ((list_item 3
              ((simple_type_specifier 3 ((() int 3 ()))) (missing 0 ())))))
           (() > 1 ())))
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((whitespace 2) (single_line_comment 14) (end_of_line 1)))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
