(script
 (list
  (markup_section (missing) ((markup))
   (markup_suffix ((<?)) ((name) (end_of_line))) (missing))
  (function_declaration (missing)
   (function_declaration_header (missing) ((function) (whitespace)) (missing)
    ((name) (whitespace)) (missing) ((lparen)) (missing)
    ((rparen) (whitespace)) (missing) (missing) (missing))
   (compound_statement (({) (end_of_line))
    (list
     (expression_statement
      (binary_expression (variable ((whitespace) (variable) (whitespace)))
       ((=) (whitespace))
       (awaitable_creation_expression (missing) ((async) (whitespace))
        (missing) (compound_statement (({)) (missing) ((})))))
      ((";") (end_of_line)))
     (expression_statement
      (binary_expression (variable ((whitespace) (variable) (whitespace)))
       ((=) (whitespace))
       (binary_expression
        (awaitable_creation_expression (missing) ((async) (whitespace))
         (missing) (compound_statement (({)) (missing) ((}) (whitespace))))
        ((+) (whitespace)) (literal ((decimal_literal)))))
      ((";") (end_of_line)))
     (expression_statement
      (binary_expression (variable ((whitespace) (variable) (whitespace)))
       ((=) (whitespace))
       (binary_expression (literal ((decimal_literal) (whitespace)))
        ((+) (whitespace))
        (awaitable_creation_expression (missing) ((async) (whitespace))
         (missing) (compound_statement (({)) (missing) ((}))))))
      ((";") (end_of_line)))
     (expression_statement
      (binary_expression (variable ((whitespace) (variable) (whitespace)))
       ((=) (whitespace))
       (binary_expression
        (awaitable_creation_expression (missing) ((async) (whitespace))
         (missing) (compound_statement (({)) (missing) ((}) (whitespace))))
        ((+) (whitespace))
        (awaitable_creation_expression (missing) ((async) (whitespace))
         (missing) (compound_statement (({)) (missing) ((}))))))
      ((";") (end_of_line)))
     (expression_statement
      (binary_expression (variable ((whitespace) (variable) (whitespace)))
       ((=) (whitespace))
       (awaitable_creation_expression (missing) ((async) (whitespace))
        (missing)
        (compound_statement (({) (end_of_line))
         (list
          (expression_statement
           (binary_expression
            (variable ((whitespace) (variable) (whitespace)))
            ((=) (whitespace)) (literal ((decimal_literal))))
           ((";") (end_of_line))))
         ((whitespace) (})))))
      ((";") (end_of_line)))
     (expression_statement
      (binary_expression (variable ((whitespace) (variable) (whitespace)))
       ((=) (whitespace))
       (awaitable_creation_expression (missing) ((async) (whitespace))
        (missing)
        (compound_statement (({) (end_of_line))
         (list
          (expression_statement
           (binary_expression
            (variable ((whitespace) (variable) (whitespace)))
            ((=) (whitespace))
            (binary_expression
             (awaitable_creation_expression (missing) ((async) (whitespace))
              (missing)
              (compound_statement (({)) (missing) ((}) (whitespace))))
             ((+) (whitespace)) (literal ((decimal_literal)))))
           ((";") (end_of_line))))
         ((whitespace) (})))))
      ((";") (end_of_line))))
    ((}))))
  (end_of_file ((end_of_file)))))
