(3,6)-(3,35) References are only allowed as function call arguments
(3,7)-(3,35) lambda_expression is not allowed in write context
(3,7)-(3,35) Only variables, members, and the results of function calls can be used as references
(4,6)-(4,21) References are only allowed as function call arguments
(4,7)-(4,21) ?-> operator is not allowed in write context
(5,6)-(5,8) References are only allowed as function call arguments
(6,6)-(6,15) References are only allowed as function call arguments
(7,6)-(7,16) References are only allowed as function call arguments
(8,6)-(8,18) References are only allowed as function call arguments
(9,6)-(9,13) References are only allowed as function call arguments
(9,7)-(9,13) Only variables, members, and the results of function calls can be used as references
(10,6)-(10,13) References are only allowed as function call arguments
(11,6)-(11,24) References are only allowed as function call arguments
(12,6)-(12,9) References are only allowed as function call arguments
(13,6)-(13,13) References are only allowed as function call arguments
(14,6)-(14,13) References are only allowed as function call arguments
(15,6)-(15,19) References are only allowed as function call arguments
(16,6)-(16,64) References are only allowed as function call arguments
(17,6)-(17,46) References are only allowed as function call arguments
