((script 62
  ((list 62
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 28
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 3 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 18
        ((() { 1 ((end_of_line 1)))
         (list 12
          ((property_declaration 12
            ((missing 0 ())
             (list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
             (missing 0 ())
             (list 4
              ((list_item 4
                ((property_declarator 4 ((() variable 4 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (classish_declaration 26
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 4 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 15
        ((() { 1 ((end_of_line 1)))
         (list 9
          ((error 3 ((((whitespace 2)) var 3 ((whitespace 1)))))
           (property_declaration 5
            ((missing 0 ()) (missing 0 ()) (missing 0 ())
             (list 4
              ((list_item 4
                ((property_declarator 4 ((() variable 4 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
