((script 144
  ((list 144
    ((markup_section 5
      ((() markup 0 ())
       (markup_suffix 5 ((() <? 2 ()) (() name 3 ((end_of_line 1)))))))
     (function_declaration 137
      ((missing 0 ())
       (function_declaration_header 26
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 1 ()) (missing 0 ()) (() "(" 1 ())
         (list 14
          ((list_item 9
            ((parameter_declaration 8
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
               (() variable 4 ((whitespace 1)))
               (simple_initializer 3
                ((() = 1 ((whitespace 1)))
                 (literal 1 ((() decimal_literal 1 ())))))))
             (() , 1 ((whitespace 1)))))
           (list_item 4
            ((parameter_declaration 4
              ((missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
               (() variable 4 ()) (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
         (missing 0 ())))
       (compound_statement 110
        ((() { 1 ((whitespace 1) (single_line_comment 49) (end_of_line 1)))
         (list 13
          ((expression_statement 13
            ((binary_expression 12
              ((subscript_expression 4
                ((variable 2 ((((whitespace 4)) variable 2 ()))) (() [ 1 ())
                 (missing 0 ()) (() ] 1 ((whitespace 1)))))
               (() = 1 ((whitespace 1)))
               (object_creation_expression 5
                ((() new 3 ((whitespace 1)))
                 (constructor_call 1
                  ((() name 1 ()) (missing 0 ()) (missing 0 ())
                   (missing 0 ())))))))
             (() ";" 1
              ((whitespace 1) (single_line_comment 38) (end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
