((script 259
  ((list 259
    ((markup_section 4
      ((missing 0 ()) (() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))
       (missing 0 ())))
     (function_declaration 41
      ((missing 0 ())
       (function_declaration_header 38
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 8 ()) (missing 0 ()) (() "(" 1 ())
         (list 12
          ((list_item 12
            ((parameter_declaration 12
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (simple_type_specifier 5 ((() mixed 5 ((whitespace 1)))))
               (decorated_expression 6
                ((() ... 3 ((whitespace 1))) (() variable 2 ())))
               (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 32
      ((missing 0 ())
       (function_declaration_header 29
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 3 ()) (missing 0 ()) (() "(" 1 ())
         (list 8
          ((list_item 8
            ((parameter_declaration 8
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
               (decorated_expression 4
                ((() & 1 ((whitespace 1))) (() variable 2 ())))
               (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 43
      ((missing 0 ())
       (function_declaration_header 40
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 6 ()) (missing 0 ()) (() "(" 1 ())
         (list 16
          ((list_item 16
            ((parameter_declaration 16
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (simple_type_specifier 5 ((() mixed 5 ((whitespace 1)))))
               (decorated_expression 10
                ((() ... 3 ((whitespace 1)))
                 (decorated_expression 6
                  ((() ... 3 ((whitespace 1))) (() variable 2 ())))))
               (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 37
      ((missing 0 ())
       (function_declaration_header 34
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 6 ()) (missing 0 ()) (() "(" 1 ())
         (list 10
          ((list_item 10
            ((parameter_declaration 10
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
               (decorated_expression 6
                ((() & 1 ((whitespace 1)))
                 (decorated_expression 4
                  ((() & 1 ((whitespace 1))) (() variable 2 ())))))
               (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 39
      ((missing 0 ())
       (function_declaration_header 36
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 6 ()) (missing 0 ()) (() "(" 1 ())
         (list 12
          ((list_item 12
            ((parameter_declaration 12
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
               (decorated_expression 8
                ((() ... 3 ((whitespace 1)))
                 (decorated_expression 4
                  ((() & 1 ((whitespace 1))) (() variable 2 ())))))
               (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 41
      ((missing 0 ())
       (function_declaration_header 38
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 6 ()) (missing 0 ()) (() "(" 1 ())
         (list 14
          ((list_item 14
            ((parameter_declaration 14
              ((missing 0 ()) (missing 0 ()) (missing 0 ())
               (simple_type_specifier 5 ((() mixed 5 ((whitespace 1)))))
               (decorated_expression 8
                ((() & 1 ((whitespace 1)))
                 (decorated_expression 6
                  ((() ... 3 ((whitespace 1))) (() variable 2 ())))))
               (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ((whitespace 1))) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
