((script 70
  ((list 70
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 65
      ((missing 0 ())
       (function_declaration_header 12
        ((missing 0 ()) (() function 8 ((whitespace 1))) (() name 1 ())
         (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
         (missing 0 ())))
       (compound_statement 52
        ((() { 1 ((end_of_line 1)))
         (list 45
          ((expression_statement 16
            ((binary_expression 15
              ((variable 2 ((((whitespace 2)) variable 2 ((whitespace 1)))))
               (() = 1 ((end_of_line 1)))
               (literal 10 ((() heredoc_string_literal 10 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (expression_statement 26
            ((binary_expression 24
              ((variable 2 ((((whitespace 2)) variable 2 ((whitespace 1)))))
               (() = 1 ((end_of_line 1)))
               (literal 19 ((() nowdoc_string_literal 19 ((end_of_line 1)))))))
             (() ";" 1 ((end_of_line 1)))))))
         (((end_of_line 1)) } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
