(3,14)-(3,15) Cannot mix bracketed namespace declarations with unbracketed namespace declarations
  (2,15)-(2,17) First unbracketed namespace occurrence here
(5,16)-(5,17) Cannot mix bracketed namespace declarations with unbracketed namespace declarations
  (2,15)-(2,17) First unbracketed namespace occurrence here
(8,18)-(8,19) Cannot mix bracketed namespace declarations with unbracketed namespace declarations
  (2,15)-(2,17) First unbracketed namespace occurrence here
