((script 2698
  ((list 2698
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (alias_declaration 309
      ((missing 0 ())
       (((end_of_line 1) (single_line_comment 52) (end_of_line 1)
         (single_line_comment 71) (end_of_line 1) (single_line_comment 78)
         (end_of_line 1) (end_of_line 1))
        type 4 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (() = 1 ((whitespace 1)))
       (shape_type_specifier 299
        ((() shape 5 ()) (() "(" 1 ((end_of_line 1)))
         (list 288
          ((list_item 23
            ((field_specifier 22
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (simple_type_specifier 6 ((() string 6 ())))))
             (() , 1 ((end_of_line 1)))))
           (list_item 20
            ((field_specifier 19
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (simple_type_specifier 3 ((() int 3 ())))))
             (() , 1 ((end_of_line 1)))))
           (list_item 20
            ((field_specifier 19
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (simple_type_specifier 3 ((() int 3 ())))))
             (() , 1 ((end_of_line 1)))))
           (list_item 23
            ((field_specifier 22
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (simple_type_specifier 6 ((() string 6 ())))))
             (() , 1 ((end_of_line 1)))))
           (list_item 20
            ((field_specifier 19
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (simple_type_specifier 3 ((() int 3 ())))))
             (() , 1 ((end_of_line 1)))))
           (list_item 21
            ((field_specifier 20
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (nullable_type_specifier 4
                ((() ? 1 ()) (simple_type_specifier 3 ((() int 3 ())))))))
             (() , 1 ((end_of_line 1)))))
           (list_item 24
            ((field_specifier 23
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (nullable_type_specifier 7
                ((() ? 1 ()) (simple_type_specifier 6 ((() string 6 ())))))))
             (() , 1 ((end_of_line 1)))))
           (list_item 26
            ((field_specifier 25
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (nullable_type_specifier 9
                ((() ? 1 ())
                 (generic_type_specifier 8
                  ((() name 3 ())
                   (type_arguments 5
                    ((() < 1 ())
                     (list 3
                      ((list_item 3
                        ((simple_type_specifier 3 ((() int 3 ())))
                         (missing 0 ())))))
                     (() > 1 ())))))))))
             (() , 1 ((end_of_line 1)))))
           (list_item 29
            ((field_specifier 28
              ((missing 0 ())
               (scope_resolution_expression 12
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 9 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (nullable_type_specifier 12
                ((() ? 1 ())
                 (generic_type_specifier 11
                  ((() name 3 ())
                   (type_arguments 8
                    ((() < 1 ())
                     (list 6
                      ((list_item 6
                        ((simple_type_specifier 6 ((() string 6 ())))
                         (missing 0 ())))))
                     (() > 1 ())))))))))
             (() , 1 ((end_of_line 1)))))
           (list_item 30
            ((field_specifier 29
              ((missing 0 ())
               (scope_resolution_expression 13
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 10 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (nullable_type_specifier 12
                ((() ? 1 ())
                 (generic_type_specifier 11
                  ((() name 3 ())
                   (type_arguments 8
                    ((() < 1 ())
                     (list 6
                      ((list_item 6
                        ((simple_type_specifier 6 ((() string 6 ())))
                         (missing 0 ())))))
                     (() > 1 ())))))))))
             (() , 1 ((end_of_line 1)))))
           (list_item 22
            ((field_specifier 21
              ((missing 0 ())
               (scope_resolution_expression 13
                ((((whitespace 2)) name 1 ()) (() :: 2 ())
                 (() name 10 ((whitespace 1)))))
               (() => 2 ((whitespace 1)))
               (nullable_type_specifier 4
                ((() ? 1 ()) (simple_type_specifier 3 ((() int 3 ())))))))
             (() , 1 ((end_of_line 1)))))))
         (missing 0 ()) (() ")" 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (classish_declaration 2176
      ((missing 0 ())
       (list 14
        ((((end_of_line 1)) abstract 8 ((whitespace 1)))
         (() final 5 ((whitespace 1)))))
       (missing 0 ()) (() class 5 ((whitespace 1))) (() name 1 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ())
       (classish_body 2154
        ((() { 1 ((end_of_line 1)))
         (list 2148
          ((const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 37
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 23
              ((list_item 23
                ((constant_declarator 23
                  ((() name 9 ((whitespace 1)))
                   (simple_initializer 13
                    ((() = 1 ((whitespace 1)))
                     (literal 11 ((() single_quoted_string_literal 11 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 39
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 25
              ((list_item 25
                ((constant_declarator 25
                  ((() name 10 ((whitespace 1)))
                   (simple_initializer 14
                    ((() = 1 ((whitespace 1)))
                     (literal 12 ((() single_quoted_string_literal 12 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (const_declaration 39
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))
             (list 25
              ((list_item 25
                ((constant_declarator 25
                  ((() name 10 ((whitespace 1)))
                   (simple_initializer 14
                    ((() = 1 ((whitespace 1)))
                     (literal 12 ((() single_quoted_string_literal 12 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (methodish_declaration 1702
            ((missing 0 ())
             (function_declaration_header 107
              ((list 19
                ((((end_of_line 1) (end_of_line 1) (whitespace 2)) public 6
                  ((whitespace 1)))
                 (() static 6 ((whitespace 1)))
                 (() async 5 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 10 ())
               (missing 0 ()) (() "(" 1 ((end_of_line 1)))
               (list 29
                ((list_item 11
                  ((parameter_declaration 10
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (simple_type_specifier 6
                      ((((whitespace 4)) string 6 ((whitespace 1)))))
                     (() variable 3 ()) (missing 0 ())))
                   (() , 1 ((end_of_line 1)))))
                 (list_item 13
                  ((parameter_declaration 12
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (simple_type_specifier 6
                      ((((whitespace 4)) string 6 ((whitespace 1)))))
                     (() variable 5 ()) (missing 0 ())))
                   (() , 1 ((end_of_line 1)))))))
               (((whitespace 2)) ")" 1 ()) (() : 1 ((whitespace 1)))
               (generic_type_specifier 27
                ((() name 9 ())
                 (type_arguments 18
                  ((() < 1 ())
                   (list 16
                    ((list_item 16
                      ((nullable_type_specifier 16
                        ((() ? 1 ())
                         (generic_type_specifier 15
                          ((() name 5 ())
                           (type_arguments 10
                            ((() < 1 ())
                             (list 8
                              ((list_item 8
                                ((simple_type_specifier 8 ((() name 8 ())))
                                 (missing 0 ())))))
                             (() > 1 ())))))))
                       (missing 0 ())))))
                   (() > 1 ((whitespace 1)))))))
               (missing 0 ())))
             (compound_statement 1594
              ((() { 1 ((end_of_line 1)))
               (list 1584
                ((expression_statement 21
                  ((binary_expression 20
                    ((variable 16
                      ((((whitespace 4)) variable 16 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (literal 1 ((() decimal_literal 1 ())))))
                   (() ";" 1 ((end_of_line 1)))))
                 (switch_statement 1220
                  ((((whitespace 4)) switch 6 ((whitespace 1))) (() "(" 1 ())
                   (variable 5 ((() variable 5 ())))
                   (() ")" 1 ((whitespace 1))) (() { 1 ((end_of_line 1)))
                   (list 1191
                    ((switch_section 111
                      ((list 21
                        ((case_label 21
                          ((((whitespace 6)) case 4 ((whitespace 1)))
                           (scope_resolution_expression 15
                            ((() self 4 ()) (() :: 2 ()) (() name 9 ())))
                           (() : 1 ((end_of_line 1)))))))
                       (list 81
                        ((expression_statement 66
                          ((binary_expression 65
                            ((variable 16
                              ((((whitespace 8)) variable 16
                                ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (prefix_unary_expression 46
                              ((() await 5 ((end_of_line 1)))
                               (function_call_expression 30
                                ((member_selection_expression 25
                                  ((parenthesized_expression 17
                                    ((((whitespace 10)) "(" 1 ())
                                     (object_creation_expression 15
                                      ((() new 3 ((whitespace 1)))
                                       (constructor_call 11
                                        ((simple_type_specifier 9
                                          ((() name 9 ())))
                                         (() "(" 1 ()) (missing 0 ())
                                         (() ")" 1 ())))))
                                     (() ")" 1 ())))
                                   (() -> 2 ()) (() name 6 ())))
                                 (missing 0 ()) (() "(" 1 ())
                                 (list 3
                                  ((list_item 3
                                    ((variable 3 ((() variable 3 ())))
                                     (missing 0 ())))))
                                 (() ")" 1 ())))))))
                           (() ";" 1 ((end_of_line 1)))))
                         (break_statement 6
                          ((((whitespace 8)) break 5 ())
                           (() ";" 1 ((end_of_line 1)))))))
                       (missing 0 ())))
                     (switch_section 379
                      ((list 21
                        ((case_label 21
                          ((((end_of_line 1) (whitespace 6)) case 4
                            ((whitespace 1)))
                           (scope_resolution_expression 15
                            ((() self 4 ()) (() :: 2 ()) (() name 9 ())))
                           (() : 1 ((end_of_line 1)))))))
                       (list 330
                        ((expression_statement 40
                          ((binary_expression 39
                            ((variable 5
                              ((((whitespace 8) (single_line_comment 10)
                                 (end_of_line 1) (whitespace 8))
                                variable 5 ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (prefix_unary_expression 31
                              ((() await 5 ((whitespace 1)))
                               (function_call_expression 25
                                ((member_selection_expression 20
                                  ((function_call_expression 15
                                    ((scope_resolution_expression 13
                                      ((() name 9 ()) (() :: 2 ())
                                       (() name 2 ())))
                                     (missing 0 ()) (() "(" 1 ())
                                     (missing 0 ()) (() ")" 1 ())))
                                   (() -> 2 ()) (() name 3 ())))
                                 (missing 0 ()) (() "(" 1 ())
                                 (list 3
                                  ((list_item 3
                                    ((variable 3 ((() variable 3 ())))
                                     (missing 0 ())))))
                                 (() ")" 1 ())))))))
                           (() ";" 1 ((end_of_line 1)))))
                         (expression_statement 66
                          ((binary_expression 65
                            ((variable 8
                              ((((whitespace 8) (single_line_comment 59)
                                 (end_of_line 1) (whitespace 8))
                                variable 8 ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (function_call_expression 54
                              ((qualified_name 13
                                ((list 13
                                  ((list_item 4
                                    ((() name 3 ()) (() "\\" 1 ())))
                                   (list_item 9
                                    ((() name 9 ()) (missing 0 ())))))))
                               (missing 0 ()) (() "(" 1 ())
                               (list 39
                                ((list_item 39
                                  ((cast_expression 39
                                    ((() "(" 1 ()) (() string 6 ())
                                     (() ")" 1 ())
                                     (function_call_expression 31
                                      ((() name 3 ()) (missing 0 ())
                                       (() "(" 1 ())
                                       (list 26
                                        ((list_item 6
                                          ((variable 5 ((() variable 5 ())))
                                           (() , 1 ((whitespace 1)))))
                                         (list_item 19
                                          ((scope_resolution_expression 19
                                            ((() name 9 ()) (() :: 2 ())
                                             (() name 8 ())))
                                           (missing 0 ())))))
                                       (() ")" 1 ())))))
                                   (missing 0 ())))))
                               (() ")" 1 ())))))
                           (() ";" 1 ((end_of_line 1)))))
                         (expression_statement 30
                          ((binary_expression 29
                            ((variable 8
                              ((((whitespace 8)) variable 8 ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (function_call_expression 18
                              ((() name 3 ()) (missing 0 ()) (() "(" 1 ())
                               (list 13
                                ((list_item 6
                                  ((variable 5 ((() variable 5 ())))
                                   (() , 1 ((whitespace 1)))))
                                 (list_item 6
                                  ((literal 6
                                    ((() single_quoted_string_literal 6 ())))
                                   (missing 0 ())))))
                               (() ")" 1 ())))))
                           (() ";" 1 ((end_of_line 1)))))
                         (expression_statement 84
                          ((binary_expression 83
                            ((variable 16
                              ((((whitespace 8)) variable 16
                                ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (prefix_unary_expression 64
                              ((() await 5 ((end_of_line 1)))
                               (function_call_expression 48
                                ((member_selection_expression 25
                                  ((parenthesized_expression 17
                                    ((((whitespace 10)) "(" 1 ())
                                     (object_creation_expression 15
                                      ((() new 3 ((whitespace 1)))
                                       (constructor_call 11
                                        ((simple_type_specifier 9
                                          ((() name 9 ())))
                                         (() "(" 1 ()) (missing 0 ())
                                         (() ")" 1 ())))))
                                     (() ")" 1 ())))
                                   (() -> 2 ()) (() name 6 ())))
                                 (missing 0 ()) (() "(" 1 ())
                                 (list 21
                                  ((list_item 21
                                    ((binary_expression 21
                                      ((binary_expression 10
                                        ((variable 4
                                          ((() variable 4 ((whitespace 1)))))
                                         (() . 1 ((whitespace 1)))
                                         (literal 3
                                          ((() single_quoted_string_literal 3
                                            ((whitespace 1)))))))
                                       (() . 1 ((whitespace 1)))
                                       (variable 8 ((() variable 8 ())))))
                                     (missing 0 ())))))
                                 (() ")" 1 ())))))))
                           (() ";" 1 ((end_of_line 1)))))
                         (break_statement 6
                          ((((whitespace 8)) break 5 ())
                           (() ";" 1 ((end_of_line 1)))))))
                       (missing 0 ())))
                     (switch_section 252
                      ((list 21
                        ((case_label 21
                          ((((end_of_line 1) (whitespace 6)) case 4
                            ((whitespace 1)))
                           (scope_resolution_expression 15
                            ((() self 4 ()) (() :: 2 ()) (() name 9 ())))
                           (() : 1 ((end_of_line 1)))))))
                       (list 142
                        ((expression_statement 42
                          ((binary_expression 41
                            ((variable 8
                              ((((whitespace 8) (single_line_comment 17)
                                 (end_of_line 1) (whitespace 8)
                                 (single_line_comment 26) (end_of_line 1)
                                 (whitespace 8) (single_line_comment 10)
                                 (end_of_line 1) (whitespace 8))
                                variable 8 ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (function_call_expression 30
                              ((qualified_name 12
                                ((list 12
                                  ((list_item 4
                                    ((() name 3 ()) (() "\\" 1 ())))
                                   (list_item 8
                                    ((() name 8 ()) (missing 0 ())))))))
                               (missing 0 ()) (() "(" 1 ())
                               (list 16
                                ((list_item 9
                                  ((variable 8 ((() variable 8 ())))
                                   (() , 1 ((whitespace 1)))))
                                 (list_item 2
                                  ((literal 1 ((() decimal_literal 1 ())))
                                   (() , 1 ((whitespace 1)))))
                                 (list_item 3
                                  ((literal 3
                                    ((() double_quoted_string_literal 3 ())))
                                   (missing 0 ())))))
                               (() ")" 1 ())))))
                           (() ";" 1 ((end_of_line 1)))))
                         (expression_statement 76
                          ((binary_expression 75
                            ((variable 16
                              ((((whitespace 8)) variable 16
                                ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (prefix_unary_expression 56
                              ((() await 5 ((end_of_line 1)))
                               (function_call_expression 40
                                ((member_selection_expression 25
                                  ((parenthesized_expression 17
                                    ((((whitespace 10)) "(" 1 ())
                                     (object_creation_expression 15
                                      ((() new 3 ((whitespace 1)))
                                       (constructor_call 11
                                        ((simple_type_specifier 9
                                          ((() name 9 ())))
                                         (() "(" 1 ()) (missing 0 ())
                                         (() ")" 1 ())))))
                                     (() ")" 1 ())))
                                   (() -> 2 ()) (() name 6 ())))
                                 (missing 0 ()) (() "(" 1 ())
                                 (list 13
                                  ((list_item 13
                                    ((binary_expression 13
                                      ((literal 9
                                        ((() single_quoted_string_literal 9
                                          ())))
                                       (() . 1 ())
                                       (variable 3 ((() variable 3 ())))))
                                     (missing 0 ())))))
                                 (() ")" 1 ())))))))
                           (() ";" 1 ((end_of_line 1)))))
                         (break_statement 6
                          ((((whitespace 8)) break 5 ())
                           (() ";" 1 ((end_of_line 1)))))))
                       (missing 0 ())))
                     (switch_section 111
                      ((list 21
                        ((case_label 21
                          ((((end_of_line 1) (whitespace 6)) case 4
                            ((whitespace 1)))
                           (scope_resolution_expression 15
                            ((() self 4 ()) (() :: 2 ()) (() name 9 ())))
                           (() : 1 ((end_of_line 1)))))))
                       (list 81
                        ((expression_statement 66
                          ((binary_expression 65
                            ((variable 16
                              ((((whitespace 8)) variable 16
                                ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (prefix_unary_expression 46
                              ((() await 5 ((end_of_line 1)))
                               (function_call_expression 30
                                ((member_selection_expression 25
                                  ((parenthesized_expression 17
                                    ((((whitespace 10)) "(" 1 ())
                                     (object_creation_expression 15
                                      ((() new 3 ((whitespace 1)))
                                       (constructor_call 11
                                        ((simple_type_specifier 9
                                          ((() name 9 ())))
                                         (() "(" 1 ()) (missing 0 ())
                                         (() ")" 1 ())))))
                                     (() ")" 1 ())))
                                   (() -> 2 ()) (() name 6 ())))
                                 (missing 0 ()) (() "(" 1 ())
                                 (list 3
                                  ((list_item 3
                                    ((variable 3 ((() variable 3 ())))
                                     (missing 0 ())))))
                                 (() ")" 1 ())))))))
                           (() ";" 1 ((end_of_line 1)))))
                         (break_statement 6
                          ((((whitespace 8)) break 5 ())
                           (() ";" 1 ((end_of_line 1)))))))
                       (missing 0 ())))
                     (switch_section 235
                      ((list 21
                        ((case_label 21
                          ((((end_of_line 1) (whitespace 6)) case 4
                            ((whitespace 1)))
                           (scope_resolution_expression 15
                            ((() self 4 ()) (() :: 2 ()) (() name 9 ())))
                           (() : 1 ((end_of_line 1)))))))
                       (list 159
                        ((if_statement 79
                          ((((whitespace 8) (single_line_comment 18)
                             (end_of_line 1) (whitespace 8)
                             (single_line_comment 10) (end_of_line 1)
                             (whitespace 8))
                            if 2 ((whitespace 1)))
                           (() "(" 1 ())
                           (binary_expression 31
                            ((function_call_expression 26
                              ((() name 10 ()) (missing 0 ()) (() "(" 1 ())
                               (list 14
                                ((list_item 10
                                  ((literal 9
                                    ((() single_quoted_string_literal 9 ())))
                                   (() , 1 ((whitespace 1)))))
                                 (list_item 3
                                  ((variable 3 ((() variable 3 ())))
                                   (missing 0 ())))))
                               (() ")" 1 ((whitespace 1)))))
                             (() == 2 ((whitespace 1)))
                             (literal 1 ((() decimal_literal 1 ())))))
                           (() ")" 1 ((whitespace 1)))
                           (compound_statement 42
                            ((() { 1 ((end_of_line 1)))
                             (list 20
                              ((expression_statement 20
                                ((binary_expression 19
                                  ((variable 3
                                    ((((whitespace 10)) variable 3
                                      ((whitespace 1)))))
                                   (() = 1 ((whitespace 1)))
                                   (binary_expression 13
                                    ((literal 9
                                      ((() single_quoted_string_literal 9 ())))
                                     (() . 1 ())
                                     (variable 3 ((() variable 3 ())))))))
                                 (() ";" 1 ((end_of_line 1)))))))
                             (((whitespace 8)) } 1 ((end_of_line 1)))))
                           (missing 0 ()) (missing 0 ())))
                         (expression_statement 56
                          ((binary_expression 55
                            ((variable 16
                              ((((whitespace 8)) variable 16
                                ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (prefix_unary_expression 36
                              ((() await 5 ((whitespace 1)))
                               (function_call_expression 30
                                ((member_selection_expression 25
                                  ((parenthesized_expression 17
                                    ((() "(" 1 ())
                                     (object_creation_expression 15
                                      ((() new 3 ((whitespace 1)))
                                       (constructor_call 11
                                        ((simple_type_specifier 9
                                          ((() name 9 ())))
                                         (() "(" 1 ()) (missing 0 ())
                                         (() ")" 1 ())))))
                                     (() ")" 1 ())))
                                   (() -> 2 ()) (() name 6 ())))
                                 (missing 0 ()) (() "(" 1 ())
                                 (list 3
                                  ((list_item 3
                                    ((variable 3 ((() variable 3 ())))
                                     (missing 0 ())))))
                                 (() ")" 1 ())))))))
                           (() ";" 1 ((end_of_line 1)))))
                         (break_statement 6
                          ((((whitespace 8)) break 5 ())
                           (() ";" 1 ((end_of_line 1)))))))
                       (missing 0 ())))
                     (switch_section 63
                      ((list 8
                        ((default_label 8
                          ((((end_of_line 1) (whitespace 6)) default 7 ())
                           (() : 1 ((end_of_line 1)))))))
                       (list 46
                        ((expression_statement 46
                          ((function_call_expression 45
                            ((member_selection_expression 27
                              ((function_call_expression 21
                                ((((whitespace 8)) name 8 ()) (missing 0 ())
                                 (() "(" 1 ())
                                 (list 11
                                  ((list_item 11
                                    ((literal 11
                                      ((() single_quoted_string_literal 11
                                        ())))
                                     (missing 0 ())))))
                                 (() ")" 1 ())))
                               (() -> 2 ()) (() name 4 ())))
                             (missing 0 ()) (() "(" 1 ())
                             (list 16
                              ((list_item 10
                                ((literal 9
                                  ((() single_quoted_string_literal 9 ())))
                                 (() , 1 ((whitespace 1)))))
                               (list_item 5
                                ((variable 5 ((() variable 5 ())))
                                 (missing 0 ())))))
                             (() ")" 1 ())))
                           (() ";" 1 ((end_of_line 1)))))))
                       (missing 0 ())))))
                   (((whitespace 4)) } 1 ((end_of_line 1)))))
                 (expression_statement 47
                  ((binary_expression 46
                    ((variable 16
                      ((((end_of_line 1) (whitespace 4)) variable 16
                        ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (function_call_expression 27
                      ((() name 9 ()) (missing 0 ()) (() "(" 1 ())
                       (list 16
                        ((list_item 16
                          ((variable 16 ((() variable 16 ())))
                           (missing 0 ())))))
                       (() ")" 1 ())))))
                   (() ";" 1 ((end_of_line 1)))))
                 (if_statement 57
                  ((((whitespace 4)) if 2 ((whitespace 1))) (() "(" 1 ())
                   (binary_expression 25
                    ((variable 16 ((() variable 16 ((whitespace 1)))))
                     (() === 3 ((whitespace 1)))
                     (literal 4 ((() null 4 ())))))
                   (() ")" 1 ((whitespace 1)))
                   (compound_statement 26
                    ((() { 1 ((end_of_line 1)))
                     (list 12
                      ((return_statement 12
                        ((((whitespace 6)) return 6 ((whitespace 1)))
                         (literal 4 ((() null 4 ())))
                         (() ";" 1 ((end_of_line 1)))))))
                     (((whitespace 4)) } 1 ((end_of_line 1)))))
                   (missing 0 ()) (missing 0 ())))
                 (expression_statement 43
                  ((binary_expression 42
                    ((variable 8
                      ((((end_of_line 1) (whitespace 4)
                         (single_line_comment 18) (end_of_line 1)
                         (whitespace 4))
                        variable 8 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (prefix_unary_expression 31
                      ((() await 5 ((whitespace 1)))
                       (function_call_expression 25
                        ((scope_resolution_expression 23
                          ((() name 9 ()) (() :: 2 ()) (() name 12 ())))
                         (missing 0 ()) (() "(" 1 ()) (missing 0 ())
                         (() ")" 1 ())))))))
                   (() ";" 1
                    ((whitespace 1) (delimited_comment 13) (end_of_line 1)))))
                 (expression_statement 59
                  ((binary_expression 58
                    ((variable 8
                      ((((whitespace 4)) variable 8 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (prefix_unary_expression 47
                      ((() await 5 ((whitespace 1)))
                       (function_call_expression 41
                        ((scope_resolution_expression 23
                          ((() name 9 ()) (() :: 2 ()) (() name 12 ())))
                         (missing 0 ()) (() "(" 1 ())
                         (list 16
                          ((list_item 8
                            ((variable 7 ((() variable 7 ())))
                             (() , 1 ((whitespace 1)))))
                           (list_item 7
                            ((variable 7 ((() variable 7 ())))
                             (missing 0 ())))))
                         (() ")" 1 ())))))))
                   (() ";" 1 ((end_of_line 1)))))
                 (expression_statement 35
                  ((binary_expression 34
                    ((variable 8
                      ((((whitespace 4)) variable 8 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (prefix_unary_expression 23
                      ((() await 5 ((whitespace 1)))
                       (function_call_expression 17
                        ((member_selection_expression 15
                          ((variable 8 ((() variable 8 ()))) (() -> 2 ())
                           (() name 5 ())))
                         (missing 0 ()) (() "(" 1 ()) (missing 0 ())
                         (() ")" 1 ())))))))
                   (() ";" 1 ((end_of_line 1)))))
                 (return_statement 27
                  ((((end_of_line 1) (whitespace 4)) return 6
                    ((whitespace 1)))
                   (function_call_expression 19
                    ((() name 9 ()) (missing 0 ()) (() "(" 1 ())
                     (list 8
                      ((list_item 8
                        ((variable 8 ((() variable 8 ()))) (missing 0 ())))))
                     (() ")" 1 ())))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
