((script 421
  ((list 421
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (alias_declaration 51
      ((missing 0 ()) (((end_of_line 1)) type 4 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (() = 1 ((whitespace 1)))
       (attributized_specifier 41
        ((old_attribute_specification 10
          ((() << 2 ())
           (list 6
            ((list_item 6
              ((constructor_call 6
                ((() name 6 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())))
               (missing 0 ())))))
           (() >> 2 ((whitespace 1)))))
         (darray_type_specifier 30
          ((() darray 6 ()) (() < 1 ())
           (simple_type_specifier 3 ((() int 3 ())))
           (() , 1 ((whitespace 1)))
           (attributized_specifier 17
            ((old_attribute_specification 10
              ((() << 2 ())
               (list 6
                ((list_item 6
                  ((constructor_call 6
                    ((() name 6 ()) (missing 0 ()) (missing 0 ())
                     (missing 0 ())))
                   (missing 0 ())))))
               (() >> 2 ((whitespace 1)))))
             (simple_type_specifier 6 ((() string 6 ())))))
           (missing 0 ()) (() > 1 ())))))
       (() ";" 1 ((end_of_line 1)))))
     (alias_declaration 32
      ((missing 0 ()) (() type 4 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (() = 1 ((whitespace 1)))
       (varray_type_specifier 22
        ((() varray 6 ()) (() < 1 ())
         (attributized_specifier 14
          ((old_attribute_specification 10
            ((() << 2 ())
             (list 6
              ((list_item 6
                ((constructor_call 6
                  ((() name 6 ()) (missing 0 ()) (missing 0 ())
                   (missing 0 ())))
                 (missing 0 ())))))
             (() >> 2 ((whitespace 1)))))
           (simple_type_specifier 3 ((() int 3 ())))))
         (missing 0 ()) (() > 1 ())))
       (() ";" 1 ((end_of_line 1)))))
     (function_declaration 24
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 1 ())
         (type_parameters 3
          ((() < 1 ())
           (list 1
            ((list_item 1
              ((type_parameter 1
                ((missing 0 ()) (missing 0 ()) (missing 0 ()) (() name 1 ())
                 (missing 0 ())))
               (missing 0 ())))))
           (() > 1 ())))
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 2
        ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))))
     (function_declaration 95
      ((missing 0 ())
       (function_declaration_header 48
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 1 ()) (missing 0 ()) (() "(" 1 ())
         (list 17
          ((list_item 17
            ((parameter_declaration 17
              ((old_attribute_specification 10
                ((() << 2 ())
                 (list 6
                  ((list_item 6
                    ((constructor_call 6
                      ((() name 6 ()) (missing 0 ()) (missing 0 ())
                       (missing 0 ())))
                     (missing 0 ())))))
                 (() >> 2 ((whitespace 1)))))
               (missing 0 ()) (missing 0 ())
               (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))
               (() variable 2 ()) (missing 0 ())))
             (missing 0 ())))))
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (attributized_specifier 17
          ((old_attribute_specification 10
            ((() << 2 ())
             (list 6
              ((list_item 6
                ((constructor_call 6
                  ((() name 6 ()) (missing 0 ()) (missing 0 ())
                   (missing 0 ())))
                 (missing 0 ())))))
             (() >> 2 ((whitespace 1)))))
           (simple_type_specifier 6 ((() string 6 ((whitespace 1)))))))
         (missing 0 ())))
       (compound_statement 46
        ((() { 1 ((end_of_line 1)))
         (list 40
          ((expression_statement 22
            ((function_call_expression 21
              ((((whitespace 2)) name 1 ())
               (type_arguments 18
                ((() < 1 ())
                 (list 16
                  ((list_item 16
                    ((attributized_specifier 16
                      ((old_attribute_specification 10
                        ((() << 2 ())
                         (list 6
                          ((list_item 6
                            ((constructor_call 6
                              ((() name 6 ()) (missing 0 ()) (missing 0 ())
                               (missing 0 ())))
                             (missing 0 ())))))
                         (() >> 2 ((whitespace 1)))))
                       (simple_type_specifier 5 ((() float 5 ())))))
                     (missing 0 ())))))
                 (() > 1 ())))
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
             (() ";" 1 ((end_of_line 1)))))
           (return_statement 15
            ((((whitespace 2)) return 6 ((whitespace 1)))
             (literal 7 ((() double_quoted_string_literal 7 ())))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (classish_declaration 163
      ((missing 0 ())
       (list 8 ((((end_of_line 1)) abstract 8 ((whitespace 1)))))
       (missing 0 ()) (() class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 146
        ((() { 1 ((end_of_line 1)))
         (list 140
          ((property_declaration 30
            ((old_attribute_specification 10
              ((((whitespace 2)) << 2 ())
               (list 6
                ((list_item 6
                  ((constructor_call 6
                    ((() name 6 ()) (missing 0 ()) (missing 0 ())
                     (missing 0 ())))
                   (missing 0 ())))))
               (() >> 2 ((whitespace 1)))))
             (list 9 ((() protected 9 ((whitespace 1)))))
             (simple_type_specifier 5 ((() float 5 ((whitespace 1)))))
             (list 2
              ((list_item 2
                ((property_declarator 2 ((() variable 2 ()) (missing 0 ())))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (type_const_declaration 30
            ((missing 0 ()) (missing 0 ())
             (((whitespace 2)) const 5 ((whitespace 1)))
             (() type 4 ((whitespace 1))) (() name 1 ((whitespace 1)))
             (missing 0 ()) (missing 0 ()) (() = 1 ((whitespace 1)))
             (attributized_specifier 14
              ((old_attribute_specification 10
                ((() << 2 ())
                 (list 6
                  ((list_item 6
                    ((constructor_call 6
                      ((() name 6 ()) (missing 0 ()) (missing 0 ())
                       (missing 0 ())))
                     (missing 0 ())))))
                 (() >> 2 ((whitespace 1)))))
               (simple_type_specifier 3 ((() int 3 ())))))
             (() ";" 1 ((end_of_line 1)))))
           (methodish_declaration 73
            ((missing 0 ())
             (function_declaration_header 52
              ((list 12
                ((((end_of_line 1) (whitespace 2)) public 6 ((whitespace 1)))
                 (() async 5 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())
               (() : 1 ((whitespace 1)))
               (generic_type_specifier 25
                ((() name 9 ())
                 (type_arguments 16
                  ((() < 1 ())
                   (list 14
                    ((list_item 14
                      ((attributized_specifier 14
                        ((old_attribute_specification 10
                          ((() << 2 ())
                           (list 6
                            ((list_item 6
                              ((constructor_call 6
                                ((() name 6 ()) (missing 0 ()) (missing 0 ())
                                 (missing 0 ())))
                               (missing 0 ())))))
                           (() >> 2 ((whitespace 1)))))
                         (simple_type_specifier 3 ((() int 3 ())))))
                       (missing 0 ())))))
                   (() > 1 ((whitespace 1)))))))
               (missing 0 ())))
             (compound_statement 20
              ((() { 1 ((end_of_line 1)))
               (list 10
                ((return_statement 10
                  ((((whitespace 4)) return 6 ((whitespace 1)))
                   (literal 2 ((() decimal_literal 2 ())))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (classish_declaration 41
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 33
        ((() { 1 ((end_of_line 1)))
         (list 27
          ((const_declaration 27
            ((missing 0 ()) (((whitespace 2)) const 5 ((whitespace 1)))
             (attributized_specifier 14
              ((old_attribute_specification 10
                ((() << 2 ())
                 (list 6
                  ((list_item 6
                    ((constructor_call 6
                      ((() name 6 ()) (missing 0 ()) (missing 0 ())
                       (missing 0 ())))
                     (missing 0 ())))))
                 (() >> 2 ((whitespace 1)))))
               (simple_type_specifier 3 ((() int 3 ((whitespace 1)))))))
             (list 5
              ((list_item 5
                ((constant_declarator 5
                  ((() name 1 ((whitespace 1)))
                   (simple_initializer 3
                    ((() = 1 ((whitespace 1)))
                     (literal 1 ((() decimal_literal 1 ())))))))
                 (missing 0 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
