((script 85
  ((list 85
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (classish_declaration 32
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) trait 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 24
        ((() { 1 ((end_of_line 1)))
         (list 18
          ((require_clause 18
            ((((whitespace 2)) require 7 ((whitespace 1)))
             (() extends 7 ((whitespace 1)))
             (simple_type_specifier 1 ((() name 1 ())))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (classish_declaration 35
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) trait 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 27
        ((() { 1 ((end_of_line 1)))
         (list 21
          ((require_clause 21
            ((((whitespace 2)) require 7 ((whitespace 1)))
             (() implements 10 ((whitespace 1)))
             (simple_type_specifier 1 ((() name 1 ())))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
