=== Shape analysis results for call.php
Constraints for \f:
   4: Allocation at [4:9-24]
   4: ! SK [4:9-24] : shape('a' => int)
   5: Allocation at [5:9-24]
   5: ! SK [5:9-24] : shape('b' => int)
   3: Parameter (([3:15-19], "\\f"), Return)
   6: Arg(\g, (Index 0), [4:9-24])
   6: Arg(\g, (Index 1), [5:9-24])
   6: Arg(\g, Return, ?1)

Constraints for \g:
   9: Parameter at [9:12-30]
   9: Parameter at [9:36-54]
   9: Parameter (([9:12-30], "\\g"), (Index 0))
   9: Parameter (([9:36-54], "\\g"), (Index 1))
   9: Parameter (([9:61-65], "\\g"), Return)
  10: Arg(\h, (Index 0), (Param (([9:12-30], "\\g"), (Index 0))))
  10: Arg(\h, Return, ?2)

Constraints for \h:
  13: Parameter at [13:12-30]
  14: ! SK ?3 : shape('c' => int)
  14: (Param (([13:12-30], "\\h"), (Index 0))) ⊆ ?3
  13: Parameter (([13:12-30], "\\h"), (Index 0))
  13: Parameter (([13:37-41], "\\h"), Return)

