=== Shape analysis results for class_constant2.php
Constraints for \C::DICT:
   4: Constant at [4:9-28]
   4: [4:36-51] ⊆ (Constant ([4:9-28], "\\C::DICT"))
   4: ! SK [4:36-51] : shape('a' => int)
   4: Allocation at [4:36-51]
   4: Constant initialization at [4:36-51]
   4: Constant ([4:9-28], "\\C::DICT")

Constraints for \main:
   8: ? SK (ConstantIdentifier ([8:7-8], (Some "\\C"), "DICT")) : shape(?'b' => mixed)
   8: ! SK (ConstantIdentifier ([8:7-8], (Some "\\C"), "DICT")) : shape(?'b' => mixed)
   8: ConstantIdentifier ([8:7-8], (Some "\\C"), "DICT")

