EXTRA_INCLUDE_PATHS=
EXTRA_LIB_PATHS=
EXTRA_NATIVE_LIBRARIES=
BYTECODE=

ROOT=$(shell pwd)

################################################################################
#                                    Rules                                     #
################################################################################

.NOTPARALLEL:

all: build-hack copy-hack-files

clean:
	find ./bin -mindepth 1 -not -path ./bin/README -delete
	rm -f $(ROOT)/src/utils/get_build_id.gen.c
	rm -f $(ROOT)/src/options/default_buildOptions.ml
	dune clean

build-hack: _build/default/src/utils/get_build_id.gen.c
	dune build \
		src/hh_server.exe \
		src/hh_client.exe \
		src/hh_single_type_check.exe \
		src/hackfmt.exe \
		src/hh_parse.exe \
		src/hh_single_compile.exe

_build/default/src/utils/get_build_id.gen.c:
	cd $(ROOT) && \
        $(OCAML) -I scripts -w -3 -unsafe-string unix.cma scripts/gen_build_id.ml src/utils/get_build_id.gen.c

copy-hack-files: build-hack
	mkdir -p bin
	cp _build/default/src/hh_server.exe ./bin/hh_server
	cp _build/default/src/hh_client.exe ./bin/hh_client
	cp _build/default/src/hh_single_type_check.exe ./bin/hh_single_type_check
	cp _build/default/src/hackfmt.exe ./bin/hackfmt
	cp _build/default/src/hh_parse.exe ./bin/hh_parse
	cp _build/default/src/hh_single_compile.exe ./bin/hh_single_compile

.PHONY: test do-test
test: build-hack copy-hack-files
	${MAKE} do-test

do-test:
	python3 ./test/verify.py --program ./bin/hh_single_type_check ./test/autocomplete
	python3 ./test/verify.py --program ./bin/hh_single_type_check ./test/color
	python3 ./test/verify.py --program ./bin/hh_single_type_check ./test/colour
	python3 ./test/verify.py --program ./bin/hh_single_type_check ./test/coverage
	python3 ./test/verify.py --program ./bin/hh_single_type_check ./test/dumpsymbolinfo
	python3 ./test/verify.py --program ./bin/hh_single_type_check ./test/dump_inheritance
	python3 ./test/verify.py --program ./bin/hh_single_type_check ./test/typecheck
	python3 ./test/integration/runner.py ./bin/hh_server ./bin/hh_client
