/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

/* Generated by idl_list.php. Do NOT modify. */

#include <runtime/ext/ext_apache.h>
#include <runtime/ext/ext_apc.h>
#include <runtime/ext/ext_apd.h>
#include <runtime/ext/ext_array.h>
#include <runtime/ext/ext_asio.h>
#include <runtime/ext/ext_bcmath.h>
#include <runtime/ext/ext_bzip2.h>
#include <runtime/ext/ext_class.h>
#include <runtime/ext/ext_closure.h>
#include <runtime/ext/ext_collections.h>
#include <runtime/ext/ext_continuation.h>
#include <runtime/ext/ext_ctype.h>
#include <runtime/ext/ext_curl.h>
#include <runtime/ext/ext_datetime.h>
#include <runtime/ext/ext_debugger.h>
#include <runtime/ext/ext_domdocument.h>
#include <runtime/ext/ext_error.h>
#include <runtime/ext/ext_fb.h>
#include <runtime/ext/ext_file.h>
#include <runtime/ext/ext_function.h>
#include <runtime/ext/ext_hash.h>
#include <runtime/ext/ext_iconv.h>
#include <runtime/ext/ext_icu.h>
#include <runtime/ext/ext_icu_ucnv.h>
#include <runtime/ext/ext_icu_ucsdet.h>
#include <runtime/ext/ext_icu_uspoof.h>
#include <runtime/ext/ext_image.h>
#include <runtime/ext/ext_imagesprite.h>
#include <runtime/ext/ext_imap.h>
#include <runtime/ext/ext_intl.h>
#include <runtime/ext/ext_ipc.h>
#include <runtime/ext/ext_iterator.h>
#include <runtime/ext/ext_json.h>
#include <runtime/ext/ext_ldap.h>
#include <runtime/ext/ext_magick.h>
#include <runtime/ext/ext_mailparse.h>
#include <runtime/ext/ext_math.h>
#include <runtime/ext/ext_mb.h>
#include <runtime/ext/ext_mcrypt.h>
#include <runtime/ext/ext_memcache.h>
#include <runtime/ext/ext_memcached.h>
#include <runtime/ext/ext_misc.h>
#include <runtime/ext/ext_mysql.h>
#include <runtime/ext/ext_network.h>
#include <runtime/ext/ext_openssl.h>
#include <runtime/ext/ext_options.h>
#include <runtime/ext/ext_output.h>
#include <runtime/ext/ext_pdo.h>
#include <runtime/ext/ext_posix.h>
#include <runtime/ext/ext_preg.h>
#include <runtime/ext/ext_process.h>
#include <runtime/ext/ext_reflection.h>
#include <runtime/ext/ext_server.h>
#include <runtime/ext/ext_session.h>
#include <runtime/ext/ext_simplexml.h>
#include <runtime/ext/ext_soap.h>
#include <runtime/ext/ext_socket.h>
#include <runtime/ext/ext_spl.h>
#include <runtime/ext/ext_splfile.h>
#include <runtime/ext/ext_sqlite3.h>
#include <runtime/ext/ext_stream.h>
#include <runtime/ext/ext_string.h>
#include <runtime/ext/ext_thread.h>
#include <runtime/ext/ext_thrift.h>
#include <runtime/ext/ext_url.h>
#include <runtime/ext/ext_variable.h>
#include <runtime/ext/ext_xml.h>
#include <runtime/ext/ext_xmlreader.h>
#include <runtime/ext/ext_xmlwriter.h>
#include <runtime/ext/ext_zlib.h>
