((script 152
  ((list 152
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 146
      ((missing 0 ())
       (function_declaration_header 37
        ((list 5 ((((end_of_line 1)) async 5 ((whitespace 1)))))
         (() function 8 ((whitespace 1))) (() name 3 ()) (missing 0 ())
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (generic_type_specifier 15
          ((() name 9 ())
           (type_arguments 6
            ((() < 1 ())
             (list 4
              ((list_item 4
                ((simple_type_specifier 4 ((() void 4 ()))) (missing 0 ())))))
             (() > 1 ((whitespace 1)))))))
         (missing 0 ())))
       (compound_statement 108
        ((() { 1 ((end_of_line 1)))
         (list 102
          ((concurrent_statement 102
            ((((whitespace 2)) concurrent 10 ((whitespace 1)))
             (compound_statement 91
              ((() { 1 ((end_of_line 1)))
               (list 81
                ((concurrent_statement 63
                  ((((whitespace 4)) concurrent 10 ((whitespace 1)))
                   (compound_statement 52
                    ((() { 1 ((end_of_line 1)))
                     (list 38
                      ((expression_statement 18
                        ((binary_expression 17
                          ((variable 2
                            ((((whitespace 6)) variable 2 ((whitespace 1)))))
                           (() = 1 ((whitespace 1)))
                           (prefix_unary_expression 12
                            ((() await 5 ((whitespace 1)))
                             (function_call_expression 6
                              ((() name 4 ()) (missing 0 ()) (() "(" 1 ())
                               (missing 0 ()) (() ")" 1 ())))))))
                         (() ";" 1 ((end_of_line 1)))))
                       (expression_statement 13
                        ((prefix_unary_expression 12
                          ((((whitespace 6)) await 5 ((whitespace 1)))
                           (function_call_expression 6
                            ((() name 4 ()) (missing 0 ()) (() "(" 1 ())
                             (missing 0 ()) (() ")" 1 ())))))
                         (() ";" 1 ((end_of_line 1)))))))
                     (((whitespace 4)) } 1 ((end_of_line 1)))))))
                 (expression_statement 13
                  ((prefix_unary_expression 12
                    ((((whitespace 4)) await 5 ((whitespace 1)))
                     (function_call_expression 6
                      ((() name 4 ()) (missing 0 ()) (() "(" 1 ())
                       (missing 0 ()) (() ")" 1 ())))))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
