((script 85
  ((list 85
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 79
      ((missing 0 ())
       (function_declaration_header 12
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 1 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
         (missing 0 ())))
       (compound_statement 66
        ((() { 1 ((end_of_line 1)))
         (list 60
          ((concurrent_statement 60
            ((((whitespace 2)) concurrent 10 ((whitespace 1)))
             (compound_statement 49
              ((() { 1 ((end_of_line 1)))
               (list 39
                ((expression_statement 16
                  ((binary_expression 15
                    ((variable 2
                      ((((whitespace 4)) variable 2 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (prefix_unary_expression 10
                      ((() await 5 ((whitespace 1)))
                       (function_call_expression 4
                        ((() name 2 ()) (missing 0 ()) (() "(" 1 ())
                         (missing 0 ()) (() ")" 1 ())))))))
                   (() ";" 1 ((end_of_line 1)))))
                 (return_statement 18
                  ((((whitespace 4)) return 6 ((whitespace 1)))
                   (prefix_unary_expression 10
                    ((() await 5 ((whitespace 1)))
                     (function_call_expression 4
                      ((() name 2 ()) (missing 0 ()) (() "(" 1 ())
                       (missing 0 ()) (() ")" 1 ())))))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
