HHVM_EXTENSION_CHECK_DEPENDENCIES(simplexml LibXml2)
if (ENABLE_EXTENSION_SIMPLEXML)
  HHVM_SELECT_SOURCES(HRE_CURRENT_EXT_PATH)
  message(STATUS "Building the simplexml extension")
else()
  message("Not building the simplexml extension")
endif ()