Typing[4472] Cannot access a public element from package 'pkg4' in package 'pkg3' [1]
-> This is from module d, which is in package pkg4 [2]
-> Module 'c' belongs to package 'pkg3' [3]
-> And package 'pkg3' does not include package 'pkg4 [4]

cross_package_access_with_package_syntax_if_nested.php--c.php:13:5
    11 |     // only pkg1 is accessible here
    12 |     f1(); // ok
[1] 13 |     f4(); // error
    14 |   }
    15 | }

cross_package_access_with_package_syntax_if_nested.php--d.php:3:17
     1 | <?hh
     2 | module d;
[2]  3 | public function f4(): void {}

cross_package_access_with_package_syntax_if_nested.php--modules.php:3:12
     1 | <?hh
     2 | new module a {}     // package pkg1
[3]  3 | new module c {}     // package pkg3 (include pkg2)
     4 | new module d {}     // package pkg4

../PACKAGES.toml:10:11
     8 | includes = ["pkg1"]
     9 | 
[4] 10 | [packages.pkg3]
    11 | uses = ["c"]
    12 | includes = ["pkg2"]

1 error found.
