Typing[4472] Cannot access a public element which belongs to package pkg1 from package pkg3 [1]
-> This is from module a, which belongs to package pkg1 [2]
-> But this is from module c, which belongs to package pkg3 [3]
-> And package pkg3 does not include package pkg1 [4]

cross_package_access_with_package_syntax_loop.php--c.php:21:3
    19 |   };
    20 | 
[1] 21 |   f1(); // error; package info doesn't transfer after while statement
    22 | }

cross_package_access_with_package_syntax_loop.php--a.php:3:17
     1 | <?hh
     2 | module a;
[2]  3 | public function f1(): void {}

cross_package_access_with_package_syntax_loop.php--modules.php:3:12
     1 | <?hh
     2 | new module a {}     // package pkg1
[3]  3 | new module c {}     // package pkg3 (include pkg2)
     4 | new module b.b1 {}  // package pkg2
     5 | new module d {}     // package pkg4

../PACKAGES.toml:11:11
     9 | includes = ["pkg1", "default"]
    10 | 
[4] 11 | [packages.pkg3]
    12 | uses = ["c"]
    13 | includes = ["pkg2", "default"]

1 error found.
