<?hh



<<__EntryPoint>>
function main_853() :mixed{
$i = 0;
 print ++$i;
 print "\t";
 print (darray[]==true) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==true) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = true;
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == true	";
 print "\n";
 print ++$i;
 print "\t";
 print (HH\Lib\Legacy_FIXME\eq(darray[], false)) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print (HH\Lib\Legacy_FIXME\eq($a, false)) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = false;
 print (HH\Lib\Legacy_FIXME\eq(darray[], $b)) ? 'Y' : 'N';
 print (HH\Lib\Legacy_FIXME\eq($a, $b)) ? 'Y' : 'N';
 print "\t";
 print "array() == false	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==1) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==1) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 1;
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == 1	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==0) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==0) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 0;
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == 0	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==-1) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==-1) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = -1;
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == -1	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]=='1') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a =='1') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '1';
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == '1'	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]=='0') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a =='0') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '0';
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == '0'	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]=='-1') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a =='-1') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '-1';
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == '-1'	";
 print "\n";
 print ++$i;
 print "\t";
 print (HH\Lib\Legacy_FIXME\eq(darray[], null)) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print (HH\Lib\Legacy_FIXME\eq($a, null)) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = null;
 print (HH\Lib\Legacy_FIXME\eq(darray[], $b)) ? 'Y' : 'N';
 print (HH\Lib\Legacy_FIXME\eq($a, $b)) ? 'Y' : 'N';
 print "\t";
 print "array() == null	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==darray[]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==darray[]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = darray[];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array()	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==varray[1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==varray[1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = varray[1];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array(1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==varray[2]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==varray[2]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = varray[2];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array(2)	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==varray['1']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==varray['1']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = varray['1'];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array('1')	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==darray['0' => '1']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==darray['0' => '1']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = darray['0' => '1'];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array('0' => '1')	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==varray['a']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==varray['a']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = varray['a'];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array('a')	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==darray['a' => 1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==darray['a' => 1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = darray['a' => 1];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array('a' => 1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==darray['b' => 1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==darray['b' => 1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = darray['b' => 1];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array('b' => 1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==darray['a' => 1, 'b' => 2]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==darray['a' => 1, 'b' => 2]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = darray['a' => 1, 'b' => 2];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array('a' => 1, 'b' => 2)	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==varray[darray['a' => 1]]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==varray[darray['a' => 1]]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = varray[darray['a' => 1]];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array(array('a' => 1))	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]==varray[darray['b' => 1]]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a ==varray[darray['b' => 1]]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = varray[darray['b' => 1]];
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == array(array('b' => 1))	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]=='php') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a =='php') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 'php';
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == 'php'	";
 print "\n";
 print ++$i;
 print "\t";
 print (darray[]=='') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = darray[];
 print ($a =='') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '';
 print (darray[]==$b) ? 'Y' : 'N';
 print ($a ==$b) ? 'Y' : 'N';
 print "\t";
 print "array() == ''	";
 print "\n";
}
