<?hh



<<__EntryPoint>>
function main_881() :mixed{
$i = 0;
 print ++$i;
 print "\t";
 print (vec['a']===true) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===true) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = true;
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === true	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===false) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===false) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = false;
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === false	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===1) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===1) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 1;
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === 1	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===0) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===0) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 0;
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === 0	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===-1) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===-1) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = -1;
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === -1	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']==='1') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ==='1') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '1';
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === '1'	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']==='0') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ==='0') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '0';
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === '0'	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']==='-1') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ==='-1') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '-1';
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === '-1'	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===null) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===null) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = null;
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === null	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===dict[]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===dict[]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict[];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array()	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===vec[1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===vec[1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec[1];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array(1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===vec[2]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===vec[2]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec[2];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array(2)	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===vec['1']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===vec['1']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec['1'];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array('1')	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===dict['0' => '1']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===dict['0' => '1']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict['0' => '1'];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array('0' => '1')	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===vec['a']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===vec['a']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec['a'];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array('a')	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===dict['a' => 1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===dict['a' => 1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict['a' => 1];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array('a' => 1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===dict['b' => 1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===dict['b' => 1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict['b' => 1];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array('b' => 1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===dict['a' => 1, 'b' => 2]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===dict['a' => 1, 'b' => 2]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict['a' => 1, 'b' => 2];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array('a' => 1, 'b' => 2)	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===vec[dict['a' => 1]]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===vec[dict['a' => 1]]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec[dict['a' => 1]];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array(array('a' => 1))	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']===vec[dict['b' => 1]]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ===vec[dict['b' => 1]]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec[dict['b' => 1]];
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === array(array('b' => 1))	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']==='php') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ==='php') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 'php';
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === 'php'	";
 print "\n";
 print ++$i;
 print "\t";
 print (vec['a']==='') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = vec['a'];
 print ($a ==='') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '';
 print (vec['a']===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "array('a') === ''	";
 print "\n";
}
