<?hh



<<__EntryPoint>>
function main_887() :mixed{
$i = 0;
 print ++$i;
 print "\t";
 print ('php'===true) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===true) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = true;
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === true	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===false) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===false) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = false;
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === false	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===1) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===1) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 1;
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === 1	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===0) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===0) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 0;
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === 0	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===-1) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===-1) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = -1;
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === -1	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'==='1') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ==='1') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '1';
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === '1'	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'==='0') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ==='0') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '0';
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === '0'	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'==='-1') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ==='-1') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '-1';
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === '-1'	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===null) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===null) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = null;
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === null	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===dict[]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===dict[]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict[];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array()	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===vec[1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===vec[1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec[1];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array(1)	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===vec[2]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===vec[2]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec[2];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array(2)	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===vec['1']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===vec['1']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec['1'];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array('1')	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===dict['0' => '1']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===dict['0' => '1']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict['0' => '1'];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array('0' => '1')	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===vec['a']) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===vec['a']) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec['a'];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array('a')	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===dict['a' => 1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===dict['a' => 1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict['a' => 1];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array('a' => 1)	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===dict['b' => 1]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===dict['b' => 1]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict['b' => 1];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array('b' => 1)	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===dict['a' => 1, 'b' => 2]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===dict['a' => 1, 'b' => 2]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = dict['a' => 1, 'b' => 2];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array('a' => 1, 'b' => 2)	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===vec[dict['a' => 1]]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===vec[dict['a' => 1]]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec[dict['a' => 1]];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array(array('a' => 1))	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'===vec[dict['b' => 1]]) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ===vec[dict['b' => 1]]) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = vec[dict['b' => 1]];
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === array(array('b' => 1))	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'==='php') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ==='php') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 'php';
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === 'php'	";
 print "\n";
 print ++$i;
 print "\t";
 print ('php'==='') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = 'php';
 print ($a ==='') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '';
 print ('php'===$b) ? 'Y' : 'N';
 print ($a ===$b) ? 'Y' : 'N';
 print "\t";
 print "'php' === ''	";
 print "\n";
}
