<?php

$i = 0;
 print ++$i;
 print "\t";
 print (''<>true) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>true) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = true;
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> true	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>false) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>false) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = false;
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> false	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>1) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>1) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 1;
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> 1	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>0) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>0) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 0;
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> 0	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>-1) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>-1) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = -1;
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> -1	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>'1') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>'1') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '1';
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> '1'	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>'0') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>'0') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '0';
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> '0'	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>'-1') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>'-1') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '-1';
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> '-1'	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>nullptr) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>nullptr) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = nullptr;
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> nullptr	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array()) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array()) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array();
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array()	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array(1)) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array(1)) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array(1);
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array(1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array(2)) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array(2)) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array(2);
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array(2)	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array('1')) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array('1')) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array('1');
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array('1')	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array('0' => '1')) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array('0' => '1')) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array('0' => '1');
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array('0' => '1')	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array('a')) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array('a')) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array('a');
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array('a')	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array('a' => 1)) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array('a' => 1)) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array('a' => 1);
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array('a' => 1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array('b' => 1)) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array('b' => 1)) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array('b' => 1);
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array('b' => 1)	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array('a' => 1, 'b' => 2)) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array('a' => 1, 'b' => 2)) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array('a' => 1, 'b' => 2);
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array('a' => 1, 'b' => 2)	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array(array('a' => 1))) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array(array('a' => 1))) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array(array('a' => 1));
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array(array('a' => 1))	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>array(array('b' => 1))) ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>array(array('b' => 1))) ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = array(array('b' => 1));
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> array(array('b' => 1))	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>'php') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>'php') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = 'php';
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> 'php'	";
 print "\n";
 print ++$i;
 print "\t";
 print (''<>'') ? 'Y' : 'N';
 $a = 1;
 $a = 't';
 $a = '';
 print ($a <>'') ? 'Y' : 'N';
 $b = 1;
 $b = 't';
 $b = '';
 print (''<>$b) ? 'Y' : 'N';
 print ($a <>$b) ? 'Y' : 'N';
 print "\t";
 print "'' <> ''	";
 print "\n";

