File "instanceof_interface.php", line 15, characters 5-15:
  J<T#1>
  where T#1 super dynamic, T#1 super \C
File "instanceof_interface.php", line 16, characters 5-18:
  I<~C>
File "instanceof_interface.php", line 19, characters 5-15:
  K
File "instanceof_interface.php", line 20, characters 5-18:
  I<Tt>
  where Tt super dynamic, Tt as ~\C
File "instanceof_interface.php", line 23, characters 5-15:
  C
File "instanceof_interface.php", line 24, characters 5-18:
  Base<Tt>
  where Tt super dynamic, Tt super string, Tt as ~string
File "instanceof_interface.php", line 27, characters 5-15:
  H<Tt>
  where Tt super dynamic, Tt as ~\K
No errors
