File "constraint_on_construct_good.php", line 16, characters 20-23:
Some type constraint(s) here are violated (Typing[4110])
File "constraint_on_construct_good.php", line 12, characters 13-13:
'T' is a constrained type parameter
File "constraint_on_construct_good.php", line 12, characters 13-13:
Some type constraint(s) are violated here
File "constraint_on_construct_good.php", line 12, characters 13-13:
T is a constrained type parameter
File "constraint_on_construct_good.php", line 16, characters 25-27:
Expected int
File "constraint_on_construct_good.php", line 12, characters 13-13:
But got dynamic
