name = "splat"
version = "0.1.0"
defaultTargets = ["splat"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.30.0"

[[lean_lib]]
name = "Splat"

[[lean_exe]]
name = "splat"
root = "Main"
