error: Typing[4110] Invalid argument

File arraykey_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo(»$x«);
 9 | }

Expected bool

File arraykey_sub_newtype_if_unsat.php, line 3, character 20 - line 3, character 23:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (»bool«|int);
 4 | 
 5 | function foo(MyThing $_): void {}

But got arraykey

File arraykey_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 21:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»arraykey« $x): void {
 8 |   foo($x);
 9 | }

Here's why:


  Step 1 of 3                                                      

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File arraykey_sub_newtype_if_unsat.php, line 5, character 10 - line 5, character 12:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function »foo«(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this expression

File arraykey_sub_newtype_if_unsat.php, line 8, character 3 - line 8, character 9:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   »foo($x)«;
 9 | }


  Step 2 of 3                                                      

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File arraykey_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 21:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»arraykey« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File arraykey_sub_newtype_if_unsat.php, line 7, character 23 - line 7, character 24:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File arraykey_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype comes from this hint

File arraykey_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo($x);
 9 | }

which is defined here

File arraykey_sub_newtype_if_unsat.php, line 3, character 19 - line 3, character 28:

 1 | <?hh
 2 | 
 3 | newtype MyThing = »(bool|int)«;
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 3 of 3                    (here is where the error occurred) 

The supertype is a union type so next I checked the subtype constraint is satisfied for at least one element.

The subtype is the same as before.

File arraykey_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 21:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»arraykey« $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this hint

File arraykey_sub_newtype_if_unsat.php, line 3, character 20 - line 3, character 23:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (»bool«|int);
 4 | 
 5 | function foo(MyThing $_): void {}

error: Typing[4110] Invalid argument

File arraykey_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo(»$x«);
 9 | }

Expected int

File arraykey_sub_newtype_if_unsat.php, line 3, character 25 - line 3, character 27:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (bool|»int«);
 4 | 
 5 | function foo(MyThing $_): void {}

But got arraykey

File arraykey_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 21:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»arraykey« $x): void {
 8 |   foo($x);
 9 | }

Here's why:


  Step 1 of 3                                                      

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File arraykey_sub_newtype_if_unsat.php, line 5, character 10 - line 5, character 12:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function »foo«(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this expression

File arraykey_sub_newtype_if_unsat.php, line 8, character 3 - line 8, character 9:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   »foo($x)«;
 9 | }


  Step 2 of 3                                                      

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File arraykey_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 21:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»arraykey« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File arraykey_sub_newtype_if_unsat.php, line 7, character 23 - line 7, character 24:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File arraykey_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype comes from this hint

File arraykey_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo($x);
 9 | }

which is defined here

File arraykey_sub_newtype_if_unsat.php, line 3, character 19 - line 3, character 28:

 1 | <?hh
 2 | 
 3 | newtype MyThing = »(bool|int)«;
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 3 of 3                    (here is where the error occurred) 

The supertype is a union type so next I checked the subtype constraint is satisfied for at least one element.

The subtype is the same as before.

File arraykey_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 21:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»arraykey« $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this hint

File arraykey_sub_newtype_if_unsat.php, line 3, character 25 - line 3, character 27:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (bool|»int«);
 4 | 
 5 | function foo(MyThing $_): void {}

error: Typing[4110] Invalid argument

File arraykey_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo(»$x«);
 9 | }

Expected (int | bool)

File arraykey_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo($x);
 9 | }

But got arraykey

File arraykey_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 21:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»arraykey« $x): void {
 8 |   foo($x);
 9 | }

Here's why:


  Step 1 of 2                                                      

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File arraykey_sub_newtype_if_unsat.php, line 5, character 10 - line 5, character 12:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function »foo«(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this expression

File arraykey_sub_newtype_if_unsat.php, line 8, character 3 - line 8, character 9:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   »foo($x)«;
 9 | }


  Step 2 of 2                    (here is where the error occurred) 

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File arraykey_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 21:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»arraykey« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File arraykey_sub_newtype_if_unsat.php, line 7, character 23 - line 7, character 24:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File arraykey_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype comes from this hint

File arraykey_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(arraykey $x): void {
 8 |   foo($x);
 9 | }

which is defined here

File arraykey_sub_newtype_if_unsat.php, line 3, character 19 - line 3, character 28:

 1 | <?hh
 2 | 
 3 | newtype MyThing = »(bool|int)«;
 4 | 
 5 | function foo(MyThing $_): void {}

3 errors found
