error: Typing[4110] Invalid argument

Expected `Sub`

 12 | function foo(»Sub« $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

But got `Super`

 14 | function bar_1(»Super« $f): void {
 15 |   $g = $f;
 16 |   foo($g);
 17 | }

Here's why: this hint

 14 | function bar_1(»Super« $f): void {
 15 |   $g = $f;
 16 |   foo($g);
 17 | }

flows *into* this expression

 14 | function bar_1(Super »$f«): void {
 15 |   $g = $f;
 16 |   foo($g);
 17 | }

which itself flows *into* this expression

 14 | function bar_1(Super $f): void {
 15 |   $g = »$f«;
 16 |   foo($g);
 17 | }

which itself flows *into* this expression

 14 | function bar_1(Super $f): void {
 15 |   »$g« = $f;
 16 |   foo($g);
 17 | }

which itself flows *into* this expression

 14 | function bar_1(Super $f): void {
 15 |   $g = $f;
 16 |   foo(»$g«);
 17 | }

which itself flows *into* this expression, via the (contravariant) 1st function parameter

 14 | function bar_1(Super $f): void {
 15 |   $g = $f;
 16 |   »foo«($g);
 17 | }

which itself flows *from* this declaration

 12 | function »foo«(Sub $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

which itself flows *into* this hint, via the (contravariant) 1st function parameter

 12 | function foo(»Sub« $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

error: Typing[4110] Invalid argument

Expected `Sub`

 12 | function foo(»Sub« $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

But got `Super`

 19 | function bar_2(»Super« $f): void {
 20 |   $g = $f;
 21 |   $h = $g;
 22 |   foo($h);
 23 | }

Here's why: this hint

 19 | function bar_2(»Super« $f): void {
 20 |   $g = $f;
 21 |   $h = $g;
 22 |   foo($h);
 23 | }

flows *into* this expression

 19 | function bar_2(Super »$f«): void {
 20 |   $g = $f;
 21 |   $h = $g;
 22 |   foo($h);
 23 | }

which itself flows *into* this expression

 19 | function bar_2(Super $f): void {
 20 |   $g = »$f«;
 21 |   $h = $g;
 22 |   foo($h);
 23 | }

which itself flows *into* this expression

 19 | function bar_2(Super $f): void {
 20 |   »$g« = $f;
 21 |   $h = $g;
 22 |   foo($h);
 23 | }

which itself flows *into* this expression

 19 | function bar_2(Super $f): void {
 20 |   $g = $f;
 21 |   $h = »$g«;
 22 |   foo($h);
 23 | }

which itself flows *into* this expression

 19 | function bar_2(Super $f): void {
 20 |   $g = $f;
 21 |   »$h« = $g;
 22 |   foo($h);
 23 | }

which itself flows *into* this expression

 19 | function bar_2(Super $f): void {
 20 |   $g = $f;
 21 |   $h = $g;
 22 |   foo(»$h«);
 23 | }

which itself flows *into* this expression, via the (contravariant) 1st function parameter

 19 | function bar_2(Super $f): void {
 20 |   $g = $f;
 21 |   $h = $g;
 22 |   »foo«($h);
 23 | }

which itself flows *from* this declaration

 12 | function »foo«(Sub $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

which itself flows *into* this hint, via the (contravariant) 1st function parameter

 12 | function foo(»Sub« $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

error: Typing[4110] Invalid argument

Expected `Sub`

 12 | function foo(»Sub« $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

But got `Super`

 25 | function bar_3(»Super« $f): void {
 26 |   $g = $f;
 27 |   $h = $g;

Here's why: this hint

 25 | function bar_3(»Super« $f): void {
 26 |   $g = $f;
 27 |   $h = $g;

flows *into* this expression

 25 | function bar_3(Super »$f«): void {
 26 |   $g = $f;
 27 |   $h = $g;

which itself flows *into* this expression

 25 | function bar_3(Super $f): void {
 26 |   $g = »$f«;
 27 |   $h = $g;
 28 |   $i = $h;
 29 |   foo($i);
 30 | }

which itself flows *into* this expression

 25 | function bar_3(Super $f): void {
 26 |   »$g« = $f;
 27 |   $h = $g;
 28 |   $i = $h;
 29 |   foo($i);
 30 | }

which itself flows *into* this expression

 25 | function bar_3(Super $f): void {
 26 |   $g = $f;
 27 |   $h = »$g«;
 28 |   $i = $h;
 29 |   foo($i);
 30 | }

which itself flows *into* this expression

 25 | function bar_3(Super $f): void {
 26 |   $g = $f;
 27 |   »$h« = $g;
 28 |   $i = $h;
 29 |   foo($i);
 30 | }

which itself flows *into* this expression

 25 | function bar_3(Super $f): void {
 26 |   $g = $f;
 27 |   $h = $g;
 28 |   $i = »$h«;
 29 |   foo($i);
 30 | }

which itself flows *into* this expression

 25 | function bar_3(Super $f): void {
 26 |   $g = $f;
 27 |   $h = $g;
 28 |   »$i« = $h;
 29 |   foo($i);
 30 | }

which itself flows *into* this expression

 25 | function bar_3(Super $f): void {
 26 |   $g = $f;
 27 |   $h = $g;
 28 |   $i = $h;
 29 |   foo(»$i«);
 30 | }

which itself flows *into* this expression, via the (contravariant) 1st function parameter

 25 | function bar_3(Super $f): void {
 26 |   $g = $f;
 27 |   $h = $g;
 28 |   $i = $h;
 29 |   »foo«($i);
 30 | }

which itself flows *from* this declaration

 12 | function »foo«(Sub $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

which itself flows *into* this hint, via the (contravariant) 1st function parameter

 12 | function foo(»Sub« $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

error: Typing[4110] Invalid argument

Expected `Sub`

 12 | function foo(»Sub« $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

But got `Super`

 6 |   public function __construct(private Super $item) {}
 7 |   public function get(): »Super« {
 8 |     return $this->item;
 9 |   }

Here's why: this hint

 6 |   public function __construct(private Super $item) {}
 7 |   public function get(): »Super« {
 8 |     return $this->item;
 9 |   }

flows *into* this expression

 33 |   $g = $f;
 34 |   $h = »$g->get()«;
 35 |   $i = $h;
 36 |   foo($i);
 37 | }

which itself flows *into* this expression

 33 |   $g = $f;
 34 |   »$h« = $g->get();
 35 |   $i = $h;
 36 |   foo($i);
 37 | }

which itself flows *into* this expression

 33 |   $g = $f;
 34 |   $h = $g->get();
 35 |   $i = »$h«;
 36 |   foo($i);
 37 | }

which itself flows *into* this expression

 33 |   $g = $f;
 34 |   $h = $g->get();
 35 |   »$i« = $h;
 36 |   foo($i);
 37 | }

which itself flows *into* this expression

 33 |   $g = $f;
 34 |   $h = $g->get();
 35 |   $i = $h;
 36 |   foo(»$i«);
 37 | }

which itself flows *into* this expression, via the (contravariant) 1st function parameter

 33 |   $g = $f;
 34 |   $h = $g->get();
 35 |   $i = $h;
 36 |   »foo«($i);
 37 | }

which itself flows *from* this declaration

 12 | function »foo«(Sub $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

which itself flows *into* this hint, via the (contravariant) 1st function parameter

 12 | function foo(»Sub« $_): void {}
 13 | 
 14 | function bar_1(Super $f): void {

4 errors found.
