error: Typing[4110] Invalid argument

  9 | function bar(Super $f): void {
 10 |   $g = $f;
 11 |   foo(»$g«);
 12 | }

File "assign_local.php", line 11, character 7 - line 11, character 8:

Expected `Sub`

 7 | function foo(»Sub« $_): void {}
 8 | 
 9 | function bar(Super $f): void {

File "assign_local.php", line 7, character 14 - line 7, character 16:

But got `Super`

 9 | function bar(»Super« $f): void {
10 |   $g = $f;
11 |   foo($g);
12 | }

File "assign_local.php", line 9, character 14 - line 9, character 18:

This error has 7 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 9 | function bar(»Super« $f): void {
10 |   $g = $f;
11 |   foo($g);
12 | }

File "assign_local.php", line 9, character 14 - line 9, character 18:

flows into this expression because it is a parameter hint

 9 | function bar(Super »$f«): void {
10 |   $g = $f;
11 |   foo($g);
12 | }

File "assign_local.php", line 9, character 20 - line 9, character 21:

which itself flows into this expression because the local variable has this type

 9 | function bar(Super $f): void {
10 |   $g = »$f«;
11 |   foo($g);
12 | }

File "assign_local.php", line 10, character 8 - line 10, character 9:

which itself flows into this expression because of an assignment

 9 | function bar(Super $f): void {
10 |   »$g« = $f;
11 |   foo($g);
12 | }

File "assign_local.php", line 10, character 3 - line 10, character 4:

which itself flows into this expression because the local variable has this type

  9 | function bar(Super $f): void {
 10 |   $g = $f;
 11 |   foo(»$g«);
 12 | }

File "assign_local.php", line 11, character 7 - line 11, character 8:

which itself flows up into this expression as the 1st function parameter

  9 | function bar(Super $f): void {
 10 |   $g = $f;
 11 |   »foo($g)«;
 12 | }

File "assign_local.php", line 11, character 3 - line 11, character 9:

which itself flows from this function or method  because they are required to be subtypes

 7 | function »foo«(Sub $_): void {}
 8 | 
 9 | function bar(Super $f): void {

File "assign_local.php", line 7, character 10 - line 7, character 12:

which itself flows down into this hint as the 1st function parameter

 7 | function foo(»Sub« $_): void {}
 8 | 
 9 | function bar(Super $f): void {

File "assign_local.php", line 7, character 14 - line 7, character 16:

1 error found.
