error: Typing[4110] Invalid assignment

File "assign_vector_bad.php", line 4, character 3 - line 4, character 12:

 3 | function test(Vector<string> $v): Vector<arraykey> {
 4 |   »$v[0] = 42«;
 5 |   return $v;
 6 | }

Expected `string`

File "assign_vector_bad.php", line 3, character 22 - line 3, character 27:

 3 | function test(Vector<»string«> $v): Vector<arraykey> {
 4 |   $v[0] = 42;
 5 |   return $v;
 6 | }

But got `int`

File "assign_vector_bad.php", line 4, character 11 - line 4, character 12:

 3 | function test(Vector<string> $v): Vector<arraykey> {
 4 |   $v[0] = »42«;
 5 |   return $v;
 6 | }

Derivation:
{
  "Derivation":[
    {
      "Begin":{
        "sub":[
          {
            "Witness":[{"filename":"assign_vector_bad.php","line":4,"char_start":11,"char_end":12}]
          }
        ],
        "super":[
          {
            "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":22,"char_end":27}]
          }
        ]
      }
    }
  ]
}

File "", line 0, character 0 - line 0, character -1:


Reason:
{
  "Subtype":{
    "sub":[
      {
        "Witness":[{"filename":"assign_vector_bad.php","line":4,"char_start":11,"char_end":12}]
      }
    ],
    "super":[
      {
        "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":22,"char_end":27}]
      }
    ]
  }
}

File "", line 0, character 0 - line 0, character -1:


error: Typing[4110] Invalid return type

File "assign_vector_bad.php", line 5, character 10 - line 5, character 11:

 3 | function test(Vector<string> $v): Vector<arraykey> {
 4 |   $v[0] = 42;
 5 |   return »$v«;
 6 | }

Expected `string`

File "assign_vector_bad.php", line 3, character 22 - line 3, character 27:

 3 | function test(Vector<»string«> $v): Vector<arraykey> {
 4 |   $v[0] = 42;
 5 |   return $v;
 6 | }

But got `arraykey`

File "assign_vector_bad.php", line 3, character 42 - line 3, character 49:

 3 | function test(Vector<string> $v): Vector<»arraykey«> {
 4 |   $v[0] = 42;
 5 |   return $v;
 6 | }

This type argument to `Vector` must match exactly (it is invariant)

File "assign_vector_bad.php", line 3, character 42 - line 3, character 49:

 3 | function test(Vector<string> $v): Vector<»arraykey«> {
 4 |   $v[0] = 42;
 5 |   return $v;
 6 | }

Derivation:
{
  "Derivation":[
    {
      "Begin":{
        "sub":[
          {
            "Flow":{
              "from":[
                {
                  "Def":[
                    {"filename":"collections/Vector.hhi","line":48,"char_start":15,"char_end":20},
                    [
                      {
                        "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":15,"char_end":28}]
                      }
                    ]
                  ]
                }
              ],
              "kind":"Flow_param_hint",
              "into":[
                {
                  "Flow":{
                    "from":[
                      {
                        "Witness":[{"filename":"assign_vector_bad.php","line":3,"char_start":30,"char_end":31}]
                      }
                    ],
                    "kind":"Flow_local",
                    "into":[
                      {
                        "Flow":{
                          "from":[
                            {
                              "Witness":[{"filename":"assign_vector_bad.php","line":5,"char_start":10,"char_end":11}]
                            }
                          ],
                          "kind":"Flow_return_expr",
                          "into":[
                            {
                              "Witness":[{"filename":"assign_vector_bad.php","line":5,"char_start":3,"char_end":12}]
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ],
        "super":[
          {
            "Def":[
              {"filename":"collections/Vector.hhi","line":48,"char_start":15,"char_end":20},
              [
                {
                  "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":35,"char_end":50}]
                }
              ]
            ]
          }
        ]
      }
    },
    {
      "Step":{
        "rule":{
          "Using_prj":{"Prj_symm_ctor":["Ctor_class","\\HH\\Vector",0,{"Inv":[{"Contr":[]}]}]}
        },
        "on_":"Both",
        "sub":[
          {
            "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":42,"char_end":49}]
          }
        ],
        "super":[
          {
            "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":22,"char_end":27}]
          }
        ]
      }
    }
  ]
}

File "", line 0, character 0 - line 0, character -1:


Reason:
{
  "Subtype":{
    "sub":[
      {
        "Prj_both":{
          "sub_prj":[
            {
              "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":42,"char_end":49}]
            }
          ],
          "prj":{"Prj_symm_ctor":["Ctor_class","\\HH\\Vector",0,{"Inv":[{"Contr":[]}]}]},
          "sub":[
            {
              "Flow":{
                "from":[
                  {
                    "Def":[
                      {"filename":"collections/Vector.hhi","line":48,"char_start":15,"char_end":20},
                      [
                        {
                          "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":15,"char_end":28}]
                        }
                      ]
                    ]
                  }
                ],
                "kind":"Flow_param_hint",
                "into":[
                  {
                    "Flow":{
                      "from":[
                        {
                          "Witness":[{"filename":"assign_vector_bad.php","line":3,"char_start":30,"char_end":31}]
                        }
                      ],
                      "kind":"Flow_local",
                      "into":[
                        {
                          "Flow":{
                            "from":[
                              {
                                "Witness":[{"filename":"assign_vector_bad.php","line":5,"char_start":10,"char_end":11}]
                              }
                            ],
                            "kind":"Flow_return_expr",
                            "into":[
                              {
                                "Witness":[{"filename":"assign_vector_bad.php","line":5,"char_start":3,"char_end":12}]
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "super":[
            {
              "Def":[
                {"filename":"collections/Vector.hhi","line":48,"char_start":15,"char_end":20},
                [
                  {
                    "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":35,"char_end":50}]
                  }
                ]
              ]
            }
          ]
        }
      }
    ],
    "super":[
      {
        "Hint":[{"filename":"assign_vector_bad.php","line":3,"char_start":22,"char_end":27}]
      }
    ]
  }
}

File "", line 0, character 0 - line 0, character -1:


2 errors found
