error: Typing[4110] Invalid argument

 8 | function bar_1((string,Super,bool) $xyz): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   foo(»$y«);
11 | }

File "assign_list.php", line 10, character 7 - line 10, character 8:

Expected `Sub`

 6 | function foo(»Sub« $_): void {}
 7 | 
 8 | function bar_1((string,Super,bool) $xyz): void {

File "assign_list.php", line 6, character 14 - line 6, character 16:

But got `Super`

 8 | function bar_1((string,»Super«,bool) $xyz): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 8, character 24 - line 8, character 28:

This error has 13 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 8 | function bar_1((string,»Super«,bool) $xyz): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 8, character 24 - line 8, character 28:

flows up into this hint as the 1st element of the tuple

 8 | function bar_1(»(string,Super,bool)« $xyz): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 8, character 16 - line 8, character 34:

which itself flows into this expression because it is a parameter hint

 8 | function bar_1((string,Super,bool) »$xyz«): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 8, character 36 - line 8, character 39:

which itself flows into this expression because the local variable has this type

 8 | function bar_1((string,Super,bool) $xyz): void {
 9 |   list($_, $y, $_) = »$xyz«;
10 |   foo($y);
11 | }

File "assign_list.php", line 9, character 22 - line 9, character 25:

which itself flows into this destructure expression because they are required to be subtypes

 8 | function bar_1((string,Super,bool) $xyz): void {
 9 |   »list($_, $y, $_)« = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 9, character 3 - line 9, character 18:

which itself flows down into this hint as the 1st element of the tuple

 8 | function bar_1(»(string,Super,bool)« $xyz): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 8, character 16 - line 8, character 34:

which itself flows into this expression because it is a parameter hint

 8 | function bar_1((string,Super,bool) »$xyz«): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 8, character 36 - line 8, character 39:

which itself flows into this expression because the local variable has this type

 8 | function bar_1((string,Super,bool) $xyz): void {
 9 |   list($_, $y, $_) = »$xyz«;
10 |   foo($y);
11 | }

File "assign_list.php", line 9, character 22 - line 9, character 25:

which itself flows into this type variable because of an assignment

 8 | function bar_1((string,Super,bool) $xyz): void {
 9 |   list($_, »$y«, $_) = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 9, character 12 - line 9, character 13:

which itself flows into this expression because of an assignment

 8 | function bar_1((string,Super,bool) $xyz): void {
 9 |   list($_, »$y«, $_) = $xyz;
10 |   foo($y);
11 | }

File "assign_list.php", line 9, character 12 - line 9, character 13:

which itself flows into this expression because the local variable has this type

 8 | function bar_1((string,Super,bool) $xyz): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   foo(»$y«);
11 | }

File "assign_list.php", line 10, character 7 - line 10, character 8:

which itself flows up into this expression as the 1st function parameter

 8 | function bar_1((string,Super,bool) $xyz): void {
 9 |   list($_, $y, $_) = $xyz;
10 |   »foo($y)«;
11 | }

File "assign_list.php", line 10, character 3 - line 10, character 9:

which itself flows from this function or method  because they are required to be subtypes

 6 | function »foo«(Sub $_): void {}
 7 | 
 8 | function bar_1((string,Super,bool) $xyz): void {

File "assign_list.php", line 6, character 10 - line 6, character 12:

which itself flows down into this hint as the 1st function parameter

 6 | function foo(»Sub« $_): void {}
 7 | 
 8 | function bar_1((string,Super,bool) $xyz): void {

File "assign_list.php", line 6, character 14 - line 6, character 16:

1 error found.
