error: Typing[4110] Invalid argument

Expected `Sub`

 7 | function foo(»Sub« $_): void {}
 8 | 
 9 | function bar(Super $f): void {

File "assign_local.php", line 7, character 14 - line 7, character 16:

But got `Super`

 9 | function bar(»Super« $f): void {
10 |   $g = $f;
11 |   foo($g);
12 | }

File "assign_local.php", line 9, character 14 - line 9, character 18:

Flow:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rflow":[
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rflow":[
                        {
                          "Rhint":[{"filename":"assign_local.php","line":9,"char_start":14,"char_end":18}]
                        },
                        {
                          "Rwitness":[{"filename":"assign_local.php","line":9,"char_start":20,"char_end":21}]
                        }
                      ]
                    },
                    {
                      "Rwitness":[{"filename":"assign_local.php","line":10,"char_start":8,"char_end":9}]
                    }
                  ]
                },
                {
                  "Rwitness":[{"filename":"assign_local.php","line":10,"char_start":3,"char_end":4}]
                }
              ]
            },
            {
              "Rwitness":[{"filename":"assign_local.php","line":11,"char_start":7,"char_end":8}]
            }
          ]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
            {
              "Rflow":[
                {
                  "Rwitness":[{"filename":"assign_local.php","line":11,"char_start":3,"char_end":5}]
                },
                {
                  "Rsupport_dynamic_type":[{"filename":"assign_local.php","line":7,"char_start":10,"char_end":12}]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"assign_local.php","line":7,"char_start":14,"char_end":16}]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
