error: Typing[4110] Invalid argument

Expected `Super`

 11 | function takes_my_a(MyA<Sub, Super, »Super«> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 37 - line 11, character 41:

But got `Sub`

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, »Sub«> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 43 - line 13, character 45:

Flow:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[
            {
              "filename":"class_subtyping_invariant.php",
              "line":13,
              "char_start":43,
              "char_end":45
            }
          ]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",2,{"Covariant":[]}]},
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rhint":[
                        {
                          "filename":"class_subtyping_invariant.php",
                          "line":5,
                          "char_start":28,
                          "char_end":43
                        }
                      ]
                    },
                    {
                      "Rflow":[
                        {
                          "Rflow":[
                            {
                              "Rflow":[
                                {
                                  "Rhint":[
                                    {
                                      "filename":"class_subtyping_invariant.php",
                                      "line":13,
                                      "char_start":32,
                                      "char_end":46
                                    }
                                  ]
                                },
                                {
                                  "Rwitness":[
                                    {
                                      "filename":"class_subtyping_invariant.php",
                                      "line":13,
                                      "char_start":48,
                                      "char_end":49
                                    }
                                  ]
                                }
                              ]
                            },
                            {
                              "Rwitness":[
                                {
                                  "filename":"class_subtyping_invariant.php",
                                  "line":14,
                                  "char_start":14,
                                  "char_end":15
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "Rprj_symm":[
                            {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                            {
                              "Rflow":[
                                {
                                  "Rwitness":[
                                    {
                                      "filename":"class_subtyping_invariant.php",
                                      "line":14,
                                      "char_start":3,
                                      "char_end":12
                                    }
                                  ]
                                },
                                {
                                  "Rsupport_dynamic_type":[
                                    {
                                      "filename":"class_subtyping_invariant.php",
                                      "line":11,
                                      "char_start":10,
                                      "char_end":19
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "Rhint":[
                    {
                      "filename":"class_subtyping_invariant.php",
                      "line":11,
                      "char_start":21,
                      "char_end":42
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":11,
          "char_start":37,
          "char_end":41
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

error: Typing[4110] Invalid argument

Expected `Sub`

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, »Sub«> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 43 - line 13, character 45:

But got `Super`

 11 | function takes_my_a(MyA<Sub, Super, »Super«> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 37 - line 11, character 41:

Flow:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[
            {
              "filename":"class_subtyping_invariant.php",
              "line":11,
              "char_start":37,
              "char_end":41
            }
          ]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",2,{"Contravariant":[]}]},
            {
              "Rflow":[
                {
                  "Rhint":[
                    {
                      "filename":"class_subtyping_invariant.php",
                      "line":11,
                      "char_start":21,
                      "char_end":42
                    }
                  ]
                },
                {
                  "Rflow":[
                    {
                      "Rflow":[
                        {
                          "Rprj_symm":[
                            {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                            {
                              "Rflow":[
                                {
                                  "Rsupport_dynamic_type":[
                                    {
                                      "filename":"class_subtyping_invariant.php",
                                      "line":11,
                                      "char_start":10,
                                      "char_end":19
                                    }
                                  ]
                                },
                                {
                                  "Rwitness":[
                                    {
                                      "filename":"class_subtyping_invariant.php",
                                      "line":14,
                                      "char_start":3,
                                      "char_end":12
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "Rflow":[
                            {
                              "Rwitness":[
                                {
                                  "filename":"class_subtyping_invariant.php",
                                  "line":14,
                                  "char_start":14,
                                  "char_end":15
                                }
                              ]
                            },
                            {
                              "Rflow":[
                                {
                                  "Rwitness":[
                                    {
                                      "filename":"class_subtyping_invariant.php",
                                      "line":13,
                                      "char_start":48,
                                      "char_end":49
                                    }
                                  ]
                                },
                                {
                                  "Rhint":[
                                    {
                                      "filename":"class_subtyping_invariant.php",
                                      "line":13,
                                      "char_start":32,
                                      "char_end":46
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "Rhint":[
                        {
                          "filename":"class_subtyping_invariant.php",
                          "line":5,
                          "char_start":28,
                          "char_end":43
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":13,
          "char_start":43,
          "char_end":45
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

2 errors found.
