error: Typing[4110] Invalid argument

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a(»$x«);
 15 | }

File "class_subtyping_invariant.php", line 14, character 14 - line 14, character 15:

Expected `Super`

 11 | function takes_my_a(MyA<Sub, Super, »Super«> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 37 - line 11, character 41:

But got `Sub`

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, »Sub«> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 43 - line 13, character 45:

This error has 8 steps, a maximum depth of 2 and contains 1 reversal.

Here's why: this hint

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, »Sub«> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 43 - line 13, character 45:

flows up into this hint as the invariant, 3rd type parameter of the this class `\MyA`, when typing as covariant

 5 | class MyB<-T1, T2> extends »MyA<Sub, T1, T2>« {}
 6 | 
 7 | class Super {}

File "class_subtyping_invariant.php", line 5, character 28 - line 5, character 43:

which itself flows into this hint because they are subclass and superclass

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(»MyB<Super, Sub>« $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 32 - line 13, character 46:

which itself flows into this expression because it is a parameter hint

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> »$x«): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 48 - line 13, character 49:

which itself flows into this expression because the local variable has this type

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a(»$x«);
 15 | }

File "class_subtyping_invariant.php", line 14, character 14 - line 14, character 15:

which itself flows up into this expression as the 1st function parameter

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   »takes_my_a($x)«;
 15 | }

File "class_subtyping_invariant.php", line 14, character 3 - line 14, character 16:

which itself flows from this function or method  because they are required to be subtypes

 11 | function »takes_my_a«(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 10 - line 11, character 19:

which itself flows down into this hint as the 1st function parameter

 11 | function takes_my_a(»MyA<Sub, Super, Super>« $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 21 - line 11, character 42:

which itself flows down into this hint as the invariant, 3rd type parameter of the this class `\MyA`, when typing as covariant

 11 | function takes_my_a(MyA<Sub, Super, »Super«> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 37 - line 11, character 41:

Path:
{
  "stats":{"max_depth":2,"length":8,"reversals":1},
  "path_elems":[
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":13,
          "char_start":43,
          "char_end":45
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_prj",
        "in_to":{"Symm":[{"Prj_symm_ctor":["Ctor_class","\\MyA",2,{"Inv":[{"Co":[]}]}]}]}
      }
    },
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":5,
          "char_start":28,
          "char_end":43
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_extends"}},
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":13,
          "char_start":32,
          "char_end":46
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_param_hint"}},
    {
      "Rwitness":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":13,
          "char_start":48,
          "char_end":49
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_local"}},
    {
      "Rwitness":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":14,
          "char_start":14,
          "char_end":15
        }
      ]
    },
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    {
      "Rwitness":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":14,
          "char_start":3,
          "char_end":16
        }
      ]
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_subtype"}},
    {
      "Rsupport_dynamic_type":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":11,
          "char_start":10,
          "char_end":19
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype",
        "out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}
      }
    },
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":11,
          "char_start":21,
          "char_end":42
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype_toplevel",
        "out_of":{"Symm":[{"Prj_symm_ctor":["Ctor_class","\\MyA",2,{"Inv":[{"Co":[]}]}]}]}
      }
    },
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":11,
          "char_start":37,
          "char_end":41
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

error: Typing[4110] Invalid argument

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a(»$x«);
 15 | }

File "class_subtyping_invariant.php", line 14, character 14 - line 14, character 15:

Expected `Sub`

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, »Sub«> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 43 - line 13, character 45:

But got `Super`

 11 | function takes_my_a(MyA<Sub, Super, »Super«> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 37 - line 11, character 41:

This error has 8 steps, a maximum depth of 2 and contains 1 reversal.

Here's why: this hint

 11 | function takes_my_a(MyA<Sub, Super, »Super«> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 37 - line 11, character 41:

flows up into this hint as the invariant, 3rd type parameter of the this class `\MyA`, when typing as covariant

 11 | function takes_my_a(»MyA<Sub, Super, Super>« $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 21 - line 11, character 42:

which itself flows up into this function or method  as the 1st function parameter

 11 | function »takes_my_a«(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 11, character 10 - line 11, character 19:

which itself flows from this expression because they are required to be subtypes

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   »takes_my_a($x)«;
 15 | }

File "class_subtyping_invariant.php", line 14, character 3 - line 14, character 16:

which itself flows down into this expression as the 1st function parameter

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
 14 |   takes_my_a(»$x«);
 15 | }

File "class_subtyping_invariant.php", line 14, character 14 - line 14, character 15:

which itself flows into this expression because the local variable has this type

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, Sub> »$x«): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 48 - line 13, character 49:

which itself flows into this hint because it is a parameter hint

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(»MyB<Super, Sub>« $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 32 - line 13, character 46:

which itself flows into this hint because they are subclass and superclass

 5 | class MyB<-T1, T2> extends »MyA<Sub, T1, T2>« {}
 6 | 
 7 | class Super {}

File "class_subtyping_invariant.php", line 5, character 28 - line 5, character 43:

which itself flows down into this hint as the invariant, 3rd type parameter of the this class `\MyA`, when typing as covariant

 11 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
 12 | 
 13 | function subtype_bad_invariant(MyB<Super, »Sub«> $x): void {
 14 |   takes_my_a($x);
 15 | }

File "class_subtyping_invariant.php", line 13, character 43 - line 13, character 45:

Path:
{
  "stats":{"max_depth":2,"length":8,"reversals":1},
  "path_elems":[
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":11,
          "char_start":37,
          "char_end":41
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_prj",
        "in_to":{"Symm":[{"Prj_symm_ctor":["Ctor_class","\\MyA",2,{"Inv":[{"Co":[]}]}]}]}
      }
    },
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":11,
          "char_start":21,
          "char_end":42
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype",
        "in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}
      }
    },
    {
      "Rsupport_dynamic_type":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":11,
          "char_start":10,
          "char_end":19
        }
      ]
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_subtype"}},
    {
      "Rwitness":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":14,
          "char_start":3,
          "char_end":16
        }
      ]
    },
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    {
      "Rwitness":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":14,
          "char_start":14,
          "char_end":15
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_local"}},
    {
      "Rwitness":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":13,
          "char_start":48,
          "char_end":49
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_param_hint"}},
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":13,
          "char_start":32,
          "char_end":46
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_extends"}},
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":5,
          "char_start":28,
          "char_end":43
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype_toplevel",
        "out_of":{"Symm":[{"Prj_symm_ctor":["Ctor_class","\\MyA",2,{"Inv":[{"Co":[]}]}]}]}
      }
    },
    {
      "Rhint":[
        {
          "filename":"class_subtyping_invariant.php",
          "line":13,
          "char_start":43,
          "char_end":45
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

2 errors found.
