error: Typing[4110] Invalid argument [1]
-> Expected Sub [2]
-> But got Super [3]
-> Unnormalized reason:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":30,"char_end":34}]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",1,{"Contravariant":[]}]},
            {
              "Rflow":[
                {
                  "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
                },
                {
                  "Rrev":[
                    {
                      "Rflow":[
                        {
                          "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
                        },
                        {
                          "Rprj_asymm":[
                            "Prj_asymm_extends",
                            {
                              "Rflow":[
                                {
                                  "Rflow":[
                                    {
                                      "Rflow":[
                                        {
                                          "Rhint":[{"filename":"class_subtyping.php","line":15,"char_start":36,"char_end":50}]
                                        },
                                        {
                                          "Rwitness":[{"filename":"class_subtyping.php","line":15,"char_start":52,"char_end":53}]
                                        }
                                      ]
                                    },
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":16,"char_start":14,"char_end":15}]
                                    }
                                  ]
                                },
                                {
                                  "Rprj_symm":[
                                    {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                                    {
                                      "Rflow":[
                                        {
                                          "Rwitness":[{"filename":"class_subtyping.php","line":16,"char_start":3,"char_end":12}]
                                        },
                                        {
                                          "Rrev":[
                                            {
                                              "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
                                            }
                                          ]
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"class_subtyping.php","line":15,"char_start":40,"char_end":42}]
    }
  ]
} [3]
-> Normalized reason:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":30,"char_end":34}]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",1,{"Contravariant":[]}]},
            {
              "Rflow":[
                {
                  "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
                },
                {
                  "Rflow":[
                    {
                      "Rprj_asymm":[
                        "Prj_asymm_extends",
                        {
                          "Rflow":[
                            {
                              "Rprj_symm":[
                                {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                                {
                                  "Rflow":[
                                    {
                                      "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
                                    },
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":16,"char_start":3,"char_end":12}]
                                    }
                                  ]
                                }
                              ]
                            },
                            {
                              "Rflow":[
                                {
                                  "Rwitness":[{"filename":"class_subtyping.php","line":16,"char_start":14,"char_end":15}]
                                },
                                {
                                  "Rflow":[
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":15,"char_start":52,"char_end":53}]
                                    },
                                    {
                                      "Rhint":[{"filename":"class_subtyping.php","line":15,"char_start":36,"char_end":50}]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"class_subtyping.php","line":15,"char_start":40,"char_end":42}]
    }
  ]
} [3]
-> Path:
[
  {
    "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":30,"char_end":34}]
  },
  {"Fwd":[]},
  {"Prj_symm_class":["\\MyA",1,{"Contravariant":[]}]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
  },
  {"Bwd":[]},
  "Prj_asymm_extends",
  {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
  {
    "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
  },
  {"Fwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":16,"char_start":3,"char_end":12}]
  },
  {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
  {"Bwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":16,"char_start":14,"char_end":15}]
  },
  {"Bwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":15,"char_start":52,"char_end":53}]
  },
  {"Bwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":15,"char_start":36,"char_end":50}]
  },
  {"Bwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
  },
  {"Prj_symm_class":["\\MyA",1,{"Contravariant":[]}]},
  {"Fwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":15,"char_start":40,"char_end":42}]
  }
] [3]

class_subtyping.php:16:14
    11 | class Sub {}
    12 | 
[3] 13 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
    14 | 
[2] 15 | function subtype_bad_contravariant(MyB<Sub, Super> $x): void {
[1] 16 |   takes_my_a($x);
    17 | }
    18 | 

error: Typing[4110] Invalid argument [1]
-> Expected Super [2]
-> But got Sub [3]
-> Unnormalized reason:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":43,"char_end":45}]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",2,{"Covariant":[]}]},
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
                    },
                    {
                      "Rprj_asymm":[
                        "Prj_asymm_extends",
                        {
                          "Rflow":[
                            {
                              "Rflow":[
                                {
                                  "Rflow":[
                                    {
                                      "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":32,"char_end":46}]
                                    },
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":19,"char_start":48,"char_end":49}]
                                    }
                                  ]
                                },
                                {
                                  "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":14,"char_end":15}]
                                }
                              ]
                            },
                            {
                              "Rprj_symm":[
                                {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                                {
                                  "Rflow":[
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":3,"char_end":12}]
                                    },
                                    {
                                      "Rrev":[
                                        {
                                          "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":37,"char_end":41}]
    }
  ]
} [3]
-> Normalized reason:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":43,"char_end":45}]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",2,{"Covariant":[]}]},
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
                    },
                    {
                      "Rprj_asymm":[
                        "Prj_asymm_extends",
                        {
                          "Rflow":[
                            {
                              "Rflow":[
                                {
                                  "Rflow":[
                                    {
                                      "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":32,"char_end":46}]
                                    },
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":19,"char_start":48,"char_end":49}]
                                    }
                                  ]
                                },
                                {
                                  "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":14,"char_end":15}]
                                }
                              ]
                            },
                            {
                              "Rprj_symm":[
                                {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                                {
                                  "Rflow":[
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":3,"char_end":12}]
                                    },
                                    {
                                      "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":37,"char_end":41}]
    }
  ]
} [3]
-> Path:
[
  {
    "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":43,"char_end":45}]
  },
  {"Fwd":[]},
  {"Prj_symm_class":["\\MyA",2,{"Covariant":[]}]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
  },
  {"Fwd":[]},
  "Prj_asymm_extends",
  {
    "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":32,"char_end":46}]
  },
  {"Fwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":19,"char_start":48,"char_end":49}]
  },
  {"Fwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":14,"char_end":15}]
  },
  {"Fwd":[]},
  {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":3,"char_end":12}]
  },
  {"Bwd":[]},
  {
    "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
  },
  {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
  {"Fwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
  },
  {"Prj_symm_class":["\\MyA",2,{"Covariant":[]}]},
  {"Fwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":37,"char_end":41}]
  }
] [3]

class_subtyping.php:20:14
    11 | class Sub {}
    12 | 
[2] 13 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
    14 | 
    15 | function subtype_bad_contravariant(MyB<Sub, Super> $x): void {
    16 |   takes_my_a($x);
    17 | }
    18 | 
[3] 19 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
[1] 20 |   takes_my_a($x);
    21 | }
    22 | 

error: Typing[4110] Invalid argument [1]
-> Expected Sub [2]
-> But got Super [3]
-> Unnormalized reason:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":37,"char_end":41}]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",2,{"Contravariant":[]}]},
            {
              "Rflow":[
                {
                  "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
                },
                {
                  "Rrev":[
                    {
                      "Rflow":[
                        {
                          "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
                        },
                        {
                          "Rprj_asymm":[
                            "Prj_asymm_extends",
                            {
                              "Rflow":[
                                {
                                  "Rflow":[
                                    {
                                      "Rflow":[
                                        {
                                          "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":32,"char_end":46}]
                                        },
                                        {
                                          "Rwitness":[{"filename":"class_subtyping.php","line":19,"char_start":48,"char_end":49}]
                                        }
                                      ]
                                    },
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":14,"char_end":15}]
                                    }
                                  ]
                                },
                                {
                                  "Rprj_symm":[
                                    {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                                    {
                                      "Rflow":[
                                        {
                                          "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":3,"char_end":12}]
                                        },
                                        {
                                          "Rrev":[
                                            {
                                              "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
                                            }
                                          ]
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":43,"char_end":45}]
    }
  ]
} [3]
-> Normalized reason:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":37,"char_end":41}]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",2,{"Contravariant":[]}]},
            {
              "Rflow":[
                {
                  "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
                },
                {
                  "Rflow":[
                    {
                      "Rprj_asymm":[
                        "Prj_asymm_extends",
                        {
                          "Rflow":[
                            {
                              "Rprj_symm":[
                                {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                                {
                                  "Rflow":[
                                    {
                                      "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
                                    },
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":3,"char_end":12}]
                                    }
                                  ]
                                }
                              ]
                            },
                            {
                              "Rflow":[
                                {
                                  "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":14,"char_end":15}]
                                },
                                {
                                  "Rflow":[
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":19,"char_start":48,"char_end":49}]
                                    },
                                    {
                                      "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":32,"char_end":46}]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":43,"char_end":45}]
    }
  ]
} [3]
-> Path:
[
  {
    "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":37,"char_end":41}]
  },
  {"Fwd":[]},
  {"Prj_symm_class":["\\MyA",2,{"Contravariant":[]}]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
  },
  {"Bwd":[]},
  "Prj_asymm_extends",
  {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
  {
    "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
  },
  {"Fwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":3,"char_end":12}]
  },
  {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
  {"Bwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":20,"char_start":14,"char_end":15}]
  },
  {"Bwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":19,"char_start":48,"char_end":49}]
  },
  {"Bwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":32,"char_end":46}]
  },
  {"Bwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":5,"char_start":28,"char_end":43}]
  },
  {"Prj_symm_class":["\\MyA",2,{"Contravariant":[]}]},
  {"Fwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":19,"char_start":43,"char_end":45}]
  }
] [3]

class_subtyping.php:20:14
    11 | class Sub {}
    12 | 
[3] 13 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
    14 | 
    15 | function subtype_bad_contravariant(MyB<Sub, Super> $x): void {
    16 |   takes_my_a($x);
    17 | }
    18 | 
[2] 19 | function subtype_bad_invariant(MyB<Super, Sub> $x): void {
[1] 20 |   takes_my_a($x);
    21 | }
    22 | 

error: Typing[4110] Invalid argument [1]
-> Expected Sub [2]
-> But got Super [3]
-> Unnormalized reason:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"class_subtyping.php","line":23,"char_start":36,"char_end":40}]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",0,{"Covariant":[]}]},
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rhint":[{"filename":"class_subtyping.php","line":7,"char_start":28,"char_end":45}]
                    },
                    {
                      "Rprj_asymm":[
                        "Prj_asymm_extends",
                        {
                          "Rflow":[
                            {
                              "Rflow":[
                                {
                                  "Rflow":[
                                    {
                                      "Rhint":[{"filename":"class_subtyping.php","line":23,"char_start":32,"char_end":48}]
                                    },
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":23,"char_start":50,"char_end":51}]
                                    }
                                  ]
                                },
                                {
                                  "Rwitness":[{"filename":"class_subtyping.php","line":24,"char_start":14,"char_end":15}]
                                }
                              ]
                            },
                            {
                              "Rprj_symm":[
                                {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                                {
                                  "Rflow":[
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":24,"char_start":3,"char_end":12}]
                                    },
                                    {
                                      "Rrev":[
                                        {
                                          "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":25,"char_end":27}]
    }
  ]
} [3]
-> Normalized reason:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"class_subtyping.php","line":23,"char_start":36,"char_end":40}]
        },
        {
          "Rprj_symm":[
            {"Prj_symm_class":["\\MyA",0,{"Covariant":[]}]},
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rhint":[{"filename":"class_subtyping.php","line":7,"char_start":28,"char_end":45}]
                    },
                    {
                      "Rprj_asymm":[
                        "Prj_asymm_extends",
                        {
                          "Rflow":[
                            {
                              "Rflow":[
                                {
                                  "Rflow":[
                                    {
                                      "Rhint":[{"filename":"class_subtyping.php","line":23,"char_start":32,"char_end":48}]
                                    },
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":23,"char_start":50,"char_end":51}]
                                    }
                                  ]
                                },
                                {
                                  "Rwitness":[{"filename":"class_subtyping.php","line":24,"char_start":14,"char_end":15}]
                                }
                              ]
                            },
                            {
                              "Rprj_symm":[
                                {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
                                {
                                  "Rflow":[
                                    {
                                      "Rwitness":[{"filename":"class_subtyping.php","line":24,"char_start":3,"char_end":12}]
                                    },
                                    {
                                      "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":25,"char_end":27}]
    }
  ]
} [3]
-> Path:
[
  {
    "Rhint":[{"filename":"class_subtyping.php","line":23,"char_start":36,"char_end":40}]
  },
  {"Fwd":[]},
  {"Prj_symm_class":["\\MyA",0,{"Covariant":[]}]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":7,"char_start":28,"char_end":45}]
  },
  {"Fwd":[]},
  "Prj_asymm_extends",
  {
    "Rhint":[{"filename":"class_subtyping.php","line":23,"char_start":32,"char_end":48}]
  },
  {"Fwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":23,"char_start":50,"char_end":51}]
  },
  {"Fwd":[]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":24,"char_start":14,"char_end":15}]
  },
  {"Fwd":[]},
  {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
  {
    "Rwitness":[{"filename":"class_subtyping.php","line":24,"char_start":3,"char_end":12}]
  },
  {"Bwd":[]},
  {
    "Rwitness_from_decl":[{"filename":"class_subtyping.php","line":13,"char_start":10,"char_end":19}]
  },
  {"Prj_symm_fn_arg":[0,0,{"Contravariant":[]}]},
  {"Fwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":21,"char_end":42}]
  },
  {"Prj_symm_class":["\\MyA",0,{"Covariant":[]}]},
  {"Fwd":[]},
  {
    "Rhint":[{"filename":"class_subtyping.php","line":13,"char_start":25,"char_end":27}]
  }
] [3]

class_subtyping.php:24:14
    11 | class Sub {}
    12 | 
[2] 13 | function takes_my_a(MyA<Sub, Super, Super> $_): void {}
    14 | 
    15 | function subtype_bad_contravariant(MyB<Sub, Super> $x): void {
       :
    21 | }
    22 | 
[3] 23 | function subtype_bad_covariant(MyC<Super, Super> $x): void {
[1] 24 |   takes_my_a($x);
    25 | }

4 errors found.
