error: Typing[4110] Invalid argument

File "ctor_generic.php", line 21, character 33 - line 21, character 39:

 19 | final class TestServiceWA extends TestServiceBase<int, string> {
 20 |   public function __construct(int $a, string $b, ISender<int, null> $sender) {
 21 |     parent::__construct($a, $b, »$sender«);
 22 |   }
 23 | }

Expected `null`

File "ctor_generic.php", line 20, character 63 - line 20, character 66:

 19 | final class TestServiceWA extends TestServiceBase<int, string> {
 20 |   public function __construct(int $a, string $b, ISender<int, »null«> $sender) {
 21 |     parent::__construct($a, $b, $sender);
 22 |   }
 23 | }

But got `string`

File "ctor_generic.php", line 20, character 39 - line 20, character 44:

 19 | final class TestServiceWA extends TestServiceBase<int, string> {
 20 |   public function __construct(int $a, »string« $b, ISender<int, null> $sender) {
 21 |     parent::__construct($a, $b, $sender);
 22 |   }
 23 | }

Here's why:

I checked the subtype constraint in [Main] because it was implied by the other constraints on the hint.

Main

[Main] Step 1 of 2

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File "ctor_generic.php", line 12, character 19 - line 12, character 29:

 11 | abstract class TestServiceBase<TA, TB> {
 12 |   public function »__construct«(
 13 |     protected TA $a,
 14 |     protected TB $b,

The supertype comes from this expression

File "ctor_generic.php", line 21, character 5 - line 21, character 40:

 19 | final class TestServiceWA extends TestServiceBase<int, string> {
 20 |   public function __construct(int $a, string $b, ISender<int, null> $sender) {
 21 |     »parent::__construct($a, $b, $sender)«;
 22 |   }
 23 | }

[Main] Step 2 of 2 (here is where the error occurred)

These are function types so next I checked the 2nd function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File "ctor_generic.php", line 20, character 39 - line 20, character 44:

 19 | final class TestServiceWA extends TestServiceBase<int, string> {
 20 |   public function __construct(int $a, »string« $b, ISender<int, null> $sender) {
 21 |     parent::__construct($a, $b, $sender);
 22 |   }
 23 | }

and flows into this expression as the parameter hint

File "ctor_generic.php", line 21, character 29 - line 21, character 30:

 19 | final class TestServiceWA extends TestServiceBase<int, string> {
 20 |   public function __construct(int $a, string $b, ISender<int, null> $sender) {
 21 |     parent::__construct($a, »$b«, $sender);
 22 |   }
 23 | }

The supertype comes from this hint

File "ctor_generic.php", line 20, character 63 - line 20, character 66:

 19 | final class TestServiceWA extends TestServiceBase<int, string> {
 20 |   public function __construct(int $a, string $b, ISender<int, »null«> $sender) {
 21 |     parent::__construct($a, $b, $sender);
 22 |   }
 23 | }

1 error found
