error: Typing[4110] Invalid argument

 3 | function foo(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, bool $z): void{
 6 |   foo($x, $y, »$z«);
 7 | }

File "fn_call_variadic.php", line 6, character 15 - line 6, character 16:

Expected `arraykey` (variadic argument)

 3 | function foo(arraykey... »$_«): void {}
 4 | 
 5 | function bar(int $x, string $y, bool $z): void{
 6 |   foo($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 3, character 26 - line 3, character 27:

But got `bool`

 3 | function foo(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, »bool« $z): void{
 6 |   foo($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 5, character 33 - line 5, character 36:

Reason:
{
  "Subtype":{
    "sub":[
      {
        "Prj_both":{
          "sub_prj":[
            {
              "Flow":{
                "from":[
                  {
                    "Hint":[{"filename":"fn_call_variadic.php","line":5,"char_start":33,"char_end":36}]
                  }
                ],
                "kind":"Flow_param_hint",
                "into":[
                  {
                    "Flow":{
                      "from":[
                        {
                          "Witness":[{"filename":"fn_call_variadic.php","line":5,"char_start":38,"char_end":39}]
                        }
                      ],
                      "kind":"Flow_local",
                      "into":[
                        {
                          "Witness":[{"filename":"fn_call_variadic.php","line":6,"char_start":15,"char_end":16}]
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "prj":{"Prj_symm_fn_param":[2,0]},
          "sub":[
            {
              "Support_dynamic_type":[{"filename":"fn_call_variadic.php","line":3,"char_start":10,"char_end":12}]
            }
          ],
          "super":[
            {
              "Witness":[{"filename":"fn_call_variadic.php","line":6,"char_start":3,"char_end":17}]
            }
          ]
        }
      }
    ],
    "super":[
      {
        "Var_param_from_decl":[{"filename":"fn_call_variadic.php","line":3,"char_start":26,"char_end":27}]
      }
    ]
  }
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
