error: Typing[4110] Invalid argument

 3 | function foo(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, bool $z): void{
 6 |   foo($x, $y, »$z«);
 7 | }

File "fn_call_variadic.php", line 6, character 15 - line 6, character 16:

Expected `arraykey` (variadic argument)

 3 | function foo(arraykey... »$_«): void {}
 4 | 
 5 | function bar(int $x, string $y, bool $z): void{
 6 |   foo($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 3, character 26 - line 3, character 27:

But got `bool`

 3 | function foo(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, »bool« $z): void{
 6 |   foo($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 5, character 33 - line 5, character 36:

Here's why: this hint

 3 | function foo(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, »bool« $z): void{
 6 |   foo($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 5, character 33 - line 5, character 36:

flows *into* this expression

 3 | function foo(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, bool »$z«): void{
 6 |   foo($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 5, character 38 - line 5, character 39:

which itself flows *into* this expression

 3 | function foo(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, bool $z): void{
 6 |   foo($x, $y, »$z«);
 7 | }

File "fn_call_variadic.php", line 6, character 15 - line 6, character 16:

which itself flows *into* this expression, via the 3rd function parameter

 3 | function foo(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, bool $z): void{
 6 |   »foo«($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 6, character 3 - line 6, character 5:

which itself flows *from* this function or method 

 3 | function »foo«(arraykey... $_): void {}
 4 | 
 5 | function bar(int $x, string $y, bool $z): void{
 6 |   foo($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 3, character 10 - line 3, character 12:

which itself flows *into* this variadic parameter declaration, via the 1st function parameter

 3 | function foo(arraykey... »$_«): void {}
 4 | 
 5 | function bar(int $x, string $y, bool $z): void{
 6 |   foo($x, $y, $z);
 7 | }

File "fn_call_variadic.php", line 3, character 26 - line 3, character 27:

Flow:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rflow":[
            {
              "Rflow":[
                {
                  "Rhint":[{"filename":"fn_call_variadic.php","line":5,"char_start":33,"char_end":36}]
                },
                {
                  "Rwitness":[{"filename":"fn_call_variadic.php","line":5,"char_start":38,"char_end":39}]
                }
              ]
            },
            {
              "Rwitness":[{"filename":"fn_call_variadic.php","line":6,"char_start":15,"char_end":16}]
            }
          ]
        },
        {
          "Rprj":[
            {"Symm":[{"Prj_symm_fn_param":[2,0]}]},
            {
              "Rflow":[
                {
                  "Rwitness":[{"filename":"fn_call_variadic.php","line":6,"char_start":3,"char_end":5}]
                },
                {
                  "Rsupport_dynamic_type":[{"filename":"fn_call_variadic.php","line":3,"char_start":10,"char_end":12}]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rvar_param_from_decl":[{"filename":"fn_call_variadic.php","line":3,"char_start":26,"char_end":27}]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
