error: Typing[4110] Invalid argument

Expected `string`

 3 | function foo(»string« $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

But got `int`

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, »int« $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

Here's why: this hint

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, »int« $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

flows *into* this expression

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int »$y« ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

which itself flows *into* this expression

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo(»$y«, $x, 1, 'a', true);
 7 | }

which itself flows *into* this expression, via the (contravariant) 1st function parameter

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   »foo«($y, $x, 1, 'a', true);
 7 | }

which itself flows *from* this declaration

 3 | function »foo«(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

which itself flows *into* this hint, via the (contravariant) 1st function parameter

 3 | function foo(»string« $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

error: Typing[4110] Invalid argument

Expected `int`

 3 | function foo(string $_, »int« $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

But got `string`

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(»string« $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

Here's why: this hint

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(»string« $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

flows *into* this expression

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string »$x«, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

which itself flows *into* this expression

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, »$x«, 1, 'a', true);
 7 | }

which itself flows *into* this expression, via the (contravariant) 2nd function parameter

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   »foo«($y, $x, 1, 'a', true);
 7 | }

which itself flows *from* this declaration

 3 | function »foo«(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

which itself flows *into* this hint, via the (contravariant) 2nd function parameter

 3 | function foo(string $_, »int« $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

error: Typing[4110] Invalid argument

Expected `arraykey` (variadic argument)

 3 | function foo(string $_, int $_, arraykey... »$_«): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

But got `bool`

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', »true«);
 7 | }

Here's why: this expression

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', »true«);
 7 | }

flows *into* this expression, via the (contravariant) 5th function parameter

 3 | function foo(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   »foo«($y, $x, 1, 'a', true);
 7 | }

which itself flows *from* this declaration

 3 | function »foo«(string $_, int $_, arraykey... $_): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

which itself flows *into* this variadic parameter declaration, via the (contravariant) 3rd function parameter

 3 | function foo(string $_, int $_, arraykey... »$_«): void {}
 4 | 
 5 | function bar(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

error: Typing[4110] Invalid argument

Expected `string`

 5 | function bar(»string« $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

But got `int`

 13 | function baz(»int« $x): void {
 14 |   $y = qux();
 15 |   bar($x, $y);
 16 | }

Here's why: this hint

 13 | function baz(»int« $x): void {
 14 |   $y = qux();
 15 |   bar($x, $y);
 16 | }

flows *into* this expression

 13 | function baz(int »$x«): void {
 14 |   $y = qux();
 15 |   bar($x, $y);
 16 | }

which itself flows *into* this expression

 13 | function baz(int $x): void {
 14 |   $y = qux();
 15 |   bar(»$x«, $y);
 16 | }

which itself flows *into* this expression, via the (contravariant) 1st function parameter

 13 | function baz(int $x): void {
 14 |   $y = qux();
 15 |   »bar«($x, $y);
 16 | }

which itself flows *from* this declaration

 5 | function »bar«(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

which itself flows *into* this hint, via the (contravariant) 1st function parameter

 5 | function bar(»string« $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

error: Typing[4110] Invalid argument

Expected `int`

 5 | function bar(string $x, »int« $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

But got `string`

 9 | function qux(): »string« {
10 |   return 'a';
11 | }

Here's why: this hint

 9 | function qux(): »string« {
10 |   return 'a';
11 | }

flows *into* this expression

 13 | function baz(int $x): void {
 14 |   $y = »qux()«;
 15 |   bar($x, $y);
 16 | }

which itself flows *into* this expression

 13 | function baz(int $x): void {
 14 |   »$y« = qux();
 15 |   bar($x, $y);
 16 | }

which itself flows *into* this expression

 13 | function baz(int $x): void {
 14 |   $y = qux();
 15 |   bar($x, »$y«);
 16 | }

which itself flows *into* this expression, via the (contravariant) 2nd function parameter

 13 | function baz(int $x): void {
 14 |   $y = qux();
 15 |   »bar«($x, $y);
 16 | }

which itself flows *from* this declaration

 5 | function »bar«(string $x, int $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

which itself flows *into* this hint, via the (contravariant) 2nd function parameter

 5 | function bar(string $x, »int« $y ): void{
 6 |   foo($y, $x, 1, 'a', true);
 7 | }

5 errors found.
