error: Typing[4110] Invalid argument

 6 | function foo_variadic_1((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) $x): void {
 8 |   foo_variadic_1(»$x«);
 9 | }

File "fn_subtyping_variadic_1.php", line 8, character 18 - line 8, character 19:

Expected `Sub`

 6 | function foo_variadic_1((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1((function(»Sub«...):void) $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 7, character 35 - line 7, character 37:

But got `Super`

 6 | function foo_variadic_1((function(Sub, »Super«):void) $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 6, character 40 - line 6, character 44:

Here's why: this hint

 6 | function foo_variadic_1((function(Sub, »Super«):void) $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 6, character 40 - line 6, character 44:

flows *into* this hint, via the 2nd function parameter

 5 | namespace HH {
 6 |   newtype supportdyn<+T> as T = »(T & dynamic)«;
 7 | }

File "/tmp/CUUGqaLVgM/supportdynamic.hhi", line 6, character 33 - line 6, character 45:

which itself flows *from* this hint

 6 | function foo_variadic_1(»(function(Sub, Super):void)« $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 6, character 25 - line 6, character 51:

which itself flows *from* this declaration

 6 | function foo_variadic_1(»(function(Sub, Super):void)« $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 6, character 25 - line 6, character 51:

which itself flows *from* this hint

 6 | function foo_variadic_1((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1(»(function(Sub...):void)« $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 7, character 25 - line 7, character 47:

which itself flows *from* this function or method , via the 1st function parameter

 6 | function »foo_variadic_1«((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 6, character 10 - line 6, character 23:

which itself flows *into* this expression

 6 | function foo_variadic_1((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) $x): void {
 8 |   »foo_variadic_1«($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 8, character 3 - line 8, character 16:

which itself flows *from* this expression, via the 1st function parameter

 6 | function foo_variadic_1((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) $x): void {
 8 |   foo_variadic_1(»$x«);
 9 | }

File "fn_subtyping_variadic_1.php", line 8, character 18 - line 8, character 19:

which itself flows *from* this expression

 6 | function foo_variadic_1((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1((function(Sub...):void) »$x«): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 7, character 49 - line 7, character 50:

which itself flows *from* this hint

 6 | function foo_variadic_1((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1(»(function(Sub...):void)« $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 7, character 25 - line 7, character 47:

which itself flows *from* this hint

 5 | namespace HH {
 6 |   newtype supportdyn<+T> as T = »(T & dynamic)«;
 7 | }

File "/tmp/CUUGqaLVgM/supportdynamic.hhi", line 6, character 33 - line 6, character 45:

which itself flows *into* this hint, via the 1st function parameter

 6 | function foo_variadic_1((function(Sub, Super):void) $_): void {}
 7 | function bar_variadic_1((function(»Sub«...):void) $x): void {
 8 |   foo_variadic_1($x);
 9 | }

File "fn_subtyping_variadic_1.php", line 7, character 35 - line 7, character 37:

1 error found.
