error: Typing[4110] Invalid argument

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2(»$f«);
 9 | }

File "fn_subtyping_contra_2.php", line 8, character 9 - line 8, character 10:

Expected `Sub`

 6 | function foo_2((function((function(»Sub«): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 36 - line 6, character 38:

But got `Super`

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(»Super«): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 36 - line 7, character 40:

This error has 17 steps, a maximum depth of 3 and contains 3 reversals.

Here's why: this hint

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(»Super«): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 36 - line 7, character 40:

flows up into this hint as the 1st function parameter

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function(»(function(Super): void)«): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 26 - line 7, character 48:

which itself flows from this hint

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function(»(function(Super): void)«): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 26 - line 7, character 48:

which itself flows from this declaration

 6 | function foo_2((function(»(function(Sub): void)«): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 26 - line 6, character 46:

which itself flows into this hint

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2(»(function((function(Super): void)): void)« $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 16 - line 7, character 56:

which itself flows into this expression

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) »$f«): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 58 - line 7, character 59:

which itself flows into this expression

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2(»$f«);
 9 | }

File "fn_subtyping_contra_2.php", line 8, character 9 - line 8, character 10:

which itself flows up into this expression as the 1st function parameter

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   »foo_2«($f);
 9 | }

File "fn_subtyping_contra_2.php", line 8, character 3 - line 8, character 7:

which itself flows from this function or method 

 6 | function »foo_2«((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 10 - line 6, character 14:

which itself flows down into this hint as the 1st function parameter

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2(»(function((function(Super): void)): void)« $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 16 - line 7, character 56:

which itself flows into this declaration

 6 | function foo_2(»(function((function(Sub): void)): void)« $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 16 - line 6, character 54:

which itself flows into this hint

 6 | function foo_2(»(function((function(Sub): void)): void)« $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 16 - line 6, character 54:

which itself flows into this hint

 6 | function foo_2((function(»(function(Sub): void)«): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 26 - line 6, character 46:

which itself flows down into this hint as the 1st function parameter

 6 | function foo_2((function((function(»Sub«): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 36 - line 6, character 38:

Path:
{
  "stats":{"max_depth":3,"length":17,"reversals":3},
  "path_elems":[
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_2.php","line":7,"char_start":36,"char_end":40}
      ]
    },
    {"Edge":{"dir":"Fwd","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}},
    {
      "Rhint":[
        {
          "filename":"/tmp/AwcePZighI/supportdynamic.hhi",
          "line":6,
          "char_start":33,
          "char_end":45
        }
      ]
    },
    {"Edge":{"dir":"Bwd"}},
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_2.php","line":7,"char_start":26,"char_end":48}
      ]
    },
    {"Edge":{"dir":"Bwd"}},
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_2.php","line":7,"char_start":26,"char_end":48}
      ]
    },
    {"Edge":{"dir":"Bwd"}},
    {
      "Rwitness_from_decl":[
        {"filename":"fn_subtyping_contra_2.php","line":6,"char_start":26,"char_end":46}
      ]
    },
    {"Edge":{"dir":"Bwd","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}},
    {
      "Rhint":[
        {
          "filename":"/tmp/AwcePZighI/supportdynamic.hhi",
          "line":6,
          "char_start":33,
          "char_end":45
        }
      ]
    },
    {"Edge":{"dir":"Fwd"}},
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_2.php","line":7,"char_start":16,"char_end":56}
      ]
    },
    {"Edge":{"dir":"Fwd"}},
    {
      "Rwitness":[
        {"filename":"fn_subtyping_contra_2.php","line":7,"char_start":58,"char_end":59}
      ]
    },
    {"Edge":{"dir":"Fwd"}},
    {
      "Rwitness":[
        {"filename":"fn_subtyping_contra_2.php","line":8,"char_start":9,"char_end":10}
      ]
    },
    {"Edge":{"dir":"Fwd","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}},
    {
      "Rwitness":[{"filename":"fn_subtyping_contra_2.php","line":8,"char_start":3,"char_end":7}]
    },
    {"Edge":{"dir":"Bwd"}},
    {
      "Rsupport_dynamic_type":[
        {"filename":"fn_subtyping_contra_2.php","line":6,"char_start":10,"char_end":14}
      ]
    },
    {"Edge":{"dir":"Fwd","out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}},
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_2.php","line":7,"char_start":16,"char_end":56}
      ]
    },
    {"Edge":{"dir":"Fwd"}},
    {
      "Rwitness_from_decl":[
        {"filename":"fn_subtyping_contra_2.php","line":6,"char_start":16,"char_end":54}
      ]
    },
    {"Edge":{"dir":"Fwd"}},
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_2.php","line":6,"char_start":16,"char_end":54}
      ]
    },
    {"Edge":{"dir":"Fwd"}},
    {
      "Rhint":[
        {
          "filename":"/tmp/AwcePZighI/supportdynamic.hhi",
          "line":6,
          "char_start":33,
          "char_end":45
        }
      ]
    },
    {"Edge":{"dir":"Bwd","out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}},
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_2.php","line":6,"char_start":26,"char_end":46}
      ]
    },
    {"Edge":{"dir":"Bwd"}},
    {
      "Rhint":[
        {
          "filename":"/tmp/AwcePZighI/supportdynamic.hhi",
          "line":6,
          "char_start":33,
          "char_end":45
        }
      ]
    },
    {"Edge":{"dir":"Fwd","out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}},
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_2.php","line":6,"char_start":36,"char_end":38}
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
