error: Typing[4110] Invalid argument

 6 | function foo_variadic_2((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) $x): void {
 8 |   foo_variadic_2(»$x«);
 9 | }

File "fn_subtyping_variadic_2.php", line 8, character 18 - line 8, character 19:

Expected `Sub`

 6 | function foo_variadic_2((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2((function(»Sub«...):void) $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 7, character 35 - line 7, character 37:

But got `Super`

 6 | function foo_variadic_2((function(Sub, »Super«...):void) $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 6, character 40 - line 6, character 44:

This error has 9 steps, a maximum depth of 2 and contains 2 reversals.

Here's why: this hint

 6 | function foo_variadic_2((function(Sub, »Super«...):void) $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 6, character 40 - line 6, character 44:

flows up into this hint as the 2nd function parameter

 6 | function foo_variadic_2(»(function(Sub, Super...):void)« $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 6, character 25 - line 6, character 54:

which itself flows from this declaration because the type was decomposed

 6 | function foo_variadic_2(»(function(Sub, Super...):void)« $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 6, character 25 - line 6, character 54:

which itself flows from this hint because they are required to be subtypes

 6 | function foo_variadic_2((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2(»(function(Sub...):void)« $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 7, character 25 - line 7, character 47:

which itself flows up from this function or method  as the 1st function parameter

 6 | function »foo_variadic_2«((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 6, character 10 - line 6, character 23:

which itself flows into this expression because they are required to be subtypes

 6 | function foo_variadic_2((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) $x): void {
 8 |   »foo_variadic_2($x)«;
 9 | }

File "fn_subtyping_variadic_2.php", line 8, character 3 - line 8, character 20:

which itself flows down from this expression as the 1st function parameter

 6 | function foo_variadic_2((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) $x): void {
 8 |   foo_variadic_2(»$x«);
 9 | }

File "fn_subtyping_variadic_2.php", line 8, character 18 - line 8, character 19:

which itself flows from this expression because the local variable has this type

 6 | function foo_variadic_2((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2((function(Sub...):void) »$x«): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 7, character 49 - line 7, character 50:

which itself flows from this hint because it is a parameter hint

 6 | function foo_variadic_2((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2(»(function(Sub...):void)« $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 7, character 25 - line 7, character 47:

which itself flows down into this hint as the 1st function parameter

 6 | function foo_variadic_2((function(Sub, Super...):void) $_): void {}
 7 | function bar_variadic_2((function(»Sub«...):void) $x): void {
 8 |   foo_variadic_2($x);
 9 | }

File "fn_subtyping_variadic_2.php", line 7, character 35 - line 7, character 37:

Raw:
{
  "Flow":[
    {
      "Flow":[
        {
          "Def":[
            {
              "filename":"fn_subtyping_variadic_2.php",
              "line":3,
              "char_start":7,
              "char_end":11
            },
            {
              "From_witness_decl":{
                "Hint":[
                  {
                    "filename":"fn_subtyping_variadic_2.php",
                    "line":6,
                    "char_start":40,
                    "char_end":44
                  }
                ]
              }
            }
          ]
        },
        "Flow_prj",
        {
          "Prj":[
            {"Symm":[{"Prj_symm_fn_param":[1,0]}]},
            {
              "Flow":[
                {
                  "Flow":[
                    {
                      "Def":[
                        {
                          "filename":"/tmp/FyPbe1Rknp/supportdynamic.hhi",
                          "line":6,
                          "char_start":11,
                          "char_end":20
                        },
                        {
                          "From_witness_decl":{
                            "Hint":[
                              {
                                "filename":"fn_subtyping_variadic_2.php",
                                "line":6,
                                "char_start":25,
                                "char_end":54
                              }
                            ]
                          }
                        }
                      ]
                    },
                    "Flow_prj",
                    {
                      "From_witness_decl":{
                        "Witness_from_decl":[
                          {
                            "filename":"fn_subtyping_variadic_2.php",
                            "line":6,
                            "char_start":25,
                            "char_end":54
                          }
                        ]
                      }
                    }
                  ]
                },
                "Flow_subtype",
                {
                  "Rev":[
                    {
                      "Flow":[
                        {
                          "Flow":[
                            {
                              "Flow":[
                                {
                                  "Flow":[
                                    {
                                      "Def":[
                                        {
                                          "filename":"/tmp/FyPbe1Rknp/supportdynamic.hhi",
                                          "line":6,
                                          "char_start":11,
                                          "char_end":20
                                        },
                                        {
                                          "From_witness_decl":{
                                            "Hint":[
                                              {
                                                "filename":"fn_subtyping_variadic_2.php",
                                                "line":7,
                                                "char_start":25,
                                                "char_end":47
                                              }
                                            ]
                                          }
                                        }
                                      ]
                                    },
                                    "Flow_param_hint",
                                    {
                                      "From_witness_locl":{
                                        "Witness":[
                                          {
                                            "filename":"fn_subtyping_variadic_2.php",
                                            "line":7,
                                            "char_start":49,
                                            "char_end":50
                                          }
                                        ]
                                      }
                                    }
                                  ]
                                },
                                "Flow_local",
                                {
                                  "From_witness_locl":{
                                    "Witness":[
                                      {
                                        "filename":"fn_subtyping_variadic_2.php",
                                        "line":8,
                                        "char_start":18,
                                        "char_end":19
                                      }
                                    ]
                                  }
                                }
                              ]
                            },
                            "Flow_prj",
                            {
                              "Prj":[
                                {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                                {
                                  "Flow":[
                                    {
                                      "From_witness_locl":{
                                        "Witness":[
                                          {
                                            "filename":"fn_subtyping_variadic_2.php",
                                            "line":8,
                                            "char_start":3,
                                            "char_end":20
                                          }
                                        ]
                                      }
                                    },
                                    "Flow_subtype",
                                    {
                                      "Rev":[
                                        {
                                          "From_witness_decl":{
                                            "Support_dynamic_type":[
                                              {
                                                "filename":"fn_subtyping_variadic_2.php",
                                                "line":6,
                                                "char_start":10,
                                                "char_end":23
                                              }
                                            ]
                                          }
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        },
                        "Flow_prj",
                        {
                          "From_witness_decl":{
                            "Hint":[
                              {
                                "filename":"fn_subtyping_variadic_2.php",
                                "line":7,
                                "char_start":25,
                                "char_end":47
                              }
                            ]
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "Def":[
        {"filename":"fn_subtyping_variadic_2.php","line":4,"char_start":7,"char_end":9},
        {
          "From_witness_decl":{
            "Hint":[
              {
                "filename":"fn_subtyping_variadic_2.php",
                "line":7,
                "char_start":35,
                "char_end":37
              }
            ]
          }
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Normalised:
{
  "Flow":[
    {
      "Flow":[
        {
          "Def":[
            {
              "filename":"fn_subtyping_variadic_2.php",
              "line":3,
              "char_start":7,
              "char_end":11
            },
            {
              "From_witness_decl":{
                "Hint":[
                  {
                    "filename":"fn_subtyping_variadic_2.php",
                    "line":6,
                    "char_start":40,
                    "char_end":44
                  }
                ]
              }
            }
          ]
        },
        "Flow_prj",
        {
          "Prj":[
            {"Symm":[{"Prj_symm_fn_param":[1,0]}]},
            {
              "Flow":[
                {
                  "Flow":[
                    {
                      "Def":[
                        {
                          "filename":"/tmp/FyPbe1Rknp/supportdynamic.hhi",
                          "line":6,
                          "char_start":11,
                          "char_end":20
                        },
                        {
                          "From_witness_decl":{
                            "Hint":[
                              {
                                "filename":"fn_subtyping_variadic_2.php",
                                "line":6,
                                "char_start":25,
                                "char_end":54
                              }
                            ]
                          }
                        }
                      ]
                    },
                    "Flow_prj",
                    {
                      "From_witness_decl":{
                        "Witness_from_decl":[
                          {
                            "filename":"fn_subtyping_variadic_2.php",
                            "line":6,
                            "char_start":25,
                            "char_end":54
                          }
                        ]
                      }
                    }
                  ]
                },
                "Flow_subtype",
                {
                  "Flow":[
                    {
                      "From_witness_decl":{
                        "Hint":[
                          {
                            "filename":"fn_subtyping_variadic_2.php",
                            "line":7,
                            "char_start":25,
                            "char_end":47
                          }
                        ]
                      }
                    },
                    "Flow_prj",
                    {
                      "Flow":[
                        {
                          "Prj":[
                            {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                            {
                              "Flow":[
                                {
                                  "From_witness_decl":{
                                    "Support_dynamic_type":[
                                      {
                                        "filename":"fn_subtyping_variadic_2.php",
                                        "line":6,
                                        "char_start":10,
                                        "char_end":23
                                      }
                                    ]
                                  }
                                },
                                "Flow_subtype",
                                {
                                  "From_witness_locl":{
                                    "Witness":[
                                      {
                                        "filename":"fn_subtyping_variadic_2.php",
                                        "line":8,
                                        "char_start":3,
                                        "char_end":20
                                      }
                                    ]
                                  }
                                }
                              ]
                            }
                          ]
                        },
                        "Flow_prj",
                        {
                          "Flow":[
                            {
                              "From_witness_locl":{
                                "Witness":[
                                  {
                                    "filename":"fn_subtyping_variadic_2.php",
                                    "line":8,
                                    "char_start":18,
                                    "char_end":19
                                  }
                                ]
                              }
                            },
                            "Flow_local",
                            {
                              "Flow":[
                                {
                                  "From_witness_locl":{
                                    "Witness":[
                                      {
                                        "filename":"fn_subtyping_variadic_2.php",
                                        "line":7,
                                        "char_start":49,
                                        "char_end":50
                                      }
                                    ]
                                  }
                                },
                                "Flow_param_hint",
                                {
                                  "Def":[
                                    {
                                      "filename":"/tmp/FyPbe1Rknp/supportdynamic.hhi",
                                      "line":6,
                                      "char_start":11,
                                      "char_end":20
                                    },
                                    {
                                      "From_witness_decl":{
                                        "Hint":[
                                          {
                                            "filename":"fn_subtyping_variadic_2.php",
                                            "line":7,
                                            "char_start":25,
                                            "char_end":47
                                          }
                                        ]
                                      }
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "Def":[
        {"filename":"fn_subtyping_variadic_2.php","line":4,"char_start":7,"char_end":9},
        {
          "From_witness_decl":{
            "Hint":[
              {
                "filename":"fn_subtyping_variadic_2.php",
                "line":7,
                "char_start":35,
                "char_end":37
              }
            ]
          }
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Path:
{
  "stats":{"max_depth":2,"length":9,"reversals":2},
  "path_elems":[
    {
      "Def":[
        {
          "filename":"fn_subtyping_variadic_2.php",
          "line":3,
          "char_start":7,
          "char_end":11
        },
        {
          "From_witness_decl":{
            "Hint":[
              {
                "filename":"fn_subtyping_variadic_2.php",
                "line":6,
                "char_start":40,
                "char_end":44
              }
            ]
          }
        }
      ]
    },
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Symm":[{"Prj_symm_fn_param":[1,0]}]}}
    },
    {
      "Def":[
        {
          "filename":"/tmp/FyPbe1Rknp/supportdynamic.hhi",
          "line":6,
          "char_start":11,
          "char_end":20
        },
        {
          "From_witness_decl":{
            "Hint":[
              {
                "filename":"fn_subtyping_variadic_2.php",
                "line":6,
                "char_start":25,
                "char_end":54
              }
            ]
          }
        }
      ]
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_prj"}},
    {
      "From_witness_decl":{
        "Witness_from_decl":[
          {
            "filename":"fn_subtyping_variadic_2.php",
            "line":6,
            "char_start":25,
            "char_end":54
          }
        ]
      }
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_subtype"}},
    {
      "From_witness_decl":{
        "Hint":[
          {
            "filename":"fn_subtyping_variadic_2.php",
            "line":7,
            "char_start":25,
            "char_end":47
          }
        ]
      }
    },
    {
      "Edge":{"dir":"Bwd","kind":"Flow_prj","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    {
      "From_witness_decl":{
        "Support_dynamic_type":[
          {
            "filename":"fn_subtyping_variadic_2.php",
            "line":6,
            "char_start":10,
            "char_end":23
          }
        ]
      }
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_subtype"}},
    {
      "From_witness_locl":{
        "Witness":[
          {
            "filename":"fn_subtyping_variadic_2.php",
            "line":8,
            "char_start":3,
            "char_end":20
          }
        ]
      }
    },
    {
      "Edge":{"dir":"Bwd","kind":"Flow_prj","out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    {
      "From_witness_locl":{
        "Witness":[
          {
            "filename":"fn_subtyping_variadic_2.php",
            "line":8,
            "char_start":18,
            "char_end":19
          }
        ]
      }
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_local"}},
    {
      "From_witness_locl":{
        "Witness":[
          {
            "filename":"fn_subtyping_variadic_2.php",
            "line":7,
            "char_start":49,
            "char_end":50
          }
        ]
      }
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_param_hint"}},
    {
      "Def":[
        {
          "filename":"/tmp/FyPbe1Rknp/supportdynamic.hhi",
          "line":6,
          "char_start":11,
          "char_end":20
        },
        {
          "From_witness_decl":{
            "Hint":[
              {
                "filename":"fn_subtyping_variadic_2.php",
                "line":7,
                "char_start":25,
                "char_end":47
              }
            ]
          }
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype_toplevel",
        "out_of":{"Symm":[{"Prj_symm_fn_param":[1,0]}]}
      }
    },
    {
      "Def":[
        {"filename":"fn_subtyping_variadic_2.php","line":4,"char_start":7,"char_end":9},
        {
          "From_witness_decl":{
            "Hint":[
              {
                "filename":"fn_subtyping_variadic_2.php",
                "line":7,
                "char_start":35,
                "char_end":37
              }
            ]
          }
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
