error: Typing[4110] Invalid argument

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2(»$f«);
 9 | }

File "fn_subtyping_contra_2.php", line 8, character 9 - line 8, character 10:

Expected `Sub`

 6 | function foo_2((function((function(»Sub«): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 36 - line 6, character 38:

But got `Super`

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(»Super«): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 36 - line 7, character 40:

1 error found.
