error: Typing[4110] Invalid argument

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1(»$f«);
 9 | }

File "fn_subtyping_contra_1.php", line 8, character 9 - line 8, character 10:

Expected `Sub`

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(»Sub«): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 26 - line 7, character 28:

But got `Super`

 6 | function foo_1((function(»Super«): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 26 - line 6, character 30:

This error has 11 steps, a maximum depth of 2 and contains 2 reversals.

Here's why: this hint

 6 | function foo_1((function(»Super«): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 26 - line 6, character 30:

flows up into this hint as the 1st function parameter

 6 | function foo_1(»(function(Super): void)« $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 16 - line 6, character 38:

which itself flows from this declaration

 6 | function foo_1(»(function(Super): void)« $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 16 - line 6, character 38:

which itself flows from this hint

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1(»(function(Sub): void)« $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 16 - line 7, character 36:

which itself flows up from this function or method  as the 1st function parameter

 6 | function »foo_1«((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 10 - line 6, character 14:

which itself flows into this expression

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   »foo_1«($f);
 9 | }

File "fn_subtyping_contra_1.php", line 8, character 3 - line 8, character 7:

which itself flows down from this expression as the 1st function parameter

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1(»$f«);
 9 | }

File "fn_subtyping_contra_1.php", line 8, character 9 - line 8, character 10:

which itself flows from this expression

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) »$f«): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 38 - line 7, character 39:

which itself flows from this hint

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1(»(function(Sub): void)« $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 16 - line 7, character 36:

which itself flows down into this hint as the 1st function parameter

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(»Sub«): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 26 - line 7, character 28:

Flow:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[
            {"filename":"fn_subtyping_contra_1.php","line":6,"char_start":26,"char_end":30}
          ]
        },
        {
          "Rprj":[
            {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rflow":[
                        {
                          "Rhint":[
                            {
                              "filename":"/tmp/pMsnGnwRlb/supportdynamic.hhi",
                              "line":6,
                              "char_start":33,
                              "char_end":45
                            }
                          ]
                        },
                        {
                          "Rhint":[
                            {"filename":"fn_subtyping_contra_1.php","line":6,"char_start":16,"char_end":38}
                          ]
                        }
                      ]
                    },
                    {
                      "Rwitness_from_decl":[
                        {"filename":"fn_subtyping_contra_1.php","line":6,"char_start":16,"char_end":38}
                      ]
                    }
                  ]
                },
                {
                  "Rflow":[
                    {
                      "Rhint":[
                        {"filename":"fn_subtyping_contra_1.php","line":7,"char_start":16,"char_end":36}
                      ]
                    },
                    {
                      "Rflow":[
                        {
                          "Rprj":[
                            {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                            {
                              "Rflow":[
                                {
                                  "Rsupport_dynamic_type":[
                                    {"filename":"fn_subtyping_contra_1.php","line":6,"char_start":10,"char_end":14}
                                  ]
                                },
                                {
                                  "Rwitness":[{"filename":"fn_subtyping_contra_1.php","line":8,"char_start":3,"char_end":7}]
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "Rflow":[
                            {
                              "Rwitness":[
                                {"filename":"fn_subtyping_contra_1.php","line":8,"char_start":9,"char_end":10}
                              ]
                            },
                            {
                              "Rflow":[
                                {
                                  "Rwitness":[
                                    {"filename":"fn_subtyping_contra_1.php","line":7,"char_start":38,"char_end":39}
                                  ]
                                },
                                {
                                  "Rflow":[
                                    {
                                      "Rhint":[
                                        {"filename":"fn_subtyping_contra_1.php","line":7,"char_start":16,"char_end":36}
                                      ]
                                    },
                                    {
                                      "Rhint":[
                                        {
                                          "filename":"/tmp/pMsnGnwRlb/supportdynamic.hhi",
                                          "line":6,
                                          "char_start":33,
                                          "char_end":45
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[
        {"filename":"fn_subtyping_contra_1.php","line":7,"char_start":26,"char_end":28}
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
