error: Typing[4110] Invalid argument

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1(»$f«);
 9 | }

File "fn_subtyping_contra_1.php", line 8, character 9 - line 8, character 10:

Expected `Sub`

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(»Sub«): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 26 - line 7, character 28:

But got `Super`

 6 | function foo_1((function(»Super«): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 26 - line 6, character 30:

Here's why: this hint

 6 | function foo_1((function(»Super«): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 26 - line 6, character 30:

flows *into* this hint, via the (contravariant) 1st function parameter

 5 | namespace HH {
 6 |   newtype supportdyn<+T> as T = »(T & dynamic)«;
 7 | }

File "/tmp/LxMcoJPC98/supportdynamic.hhi", line 6, character 33 - line 6, character 45:

which itself flows *from* this hint

 6 | function foo_1(»(function(Super): void)« $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 16 - line 6, character 38:

which itself flows *from* this declaration

 6 | function foo_1(»(function(Super): void)« $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 16 - line 6, character 38:

which itself flows *from* this hint

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1(»(function(Sub): void)« $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 16 - line 7, character 36:

which itself flows *from* this function or method , via the (contravariant) 1st function parameter

 6 | function »foo_1«((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 6, character 10 - line 6, character 14:

which itself flows *into* this expression

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   »foo_1«($f);
 9 | }

File "fn_subtyping_contra_1.php", line 8, character 3 - line 8, character 7:

which itself flows *from* this expression, via the (contravariant) 1st function parameter

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) $f): void {
 8 |   foo_1(»$f«);
 9 | }

File "fn_subtyping_contra_1.php", line 8, character 9 - line 8, character 10:

which itself flows *from* this expression

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(Sub): void) »$f«): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 38 - line 7, character 39:

which itself flows *from* this hint

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1(»(function(Sub): void)« $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 16 - line 7, character 36:

which itself flows *from* this hint

 5 | namespace HH {
 6 |   newtype supportdyn<+T> as T = »(T & dynamic)«;
 7 | }

File "/tmp/LxMcoJPC98/supportdynamic.hhi", line 6, character 33 - line 6, character 45:

which itself flows *into* this hint, via the (contravariant) 1st function parameter

 6 | function foo_1((function(Super): void) $_): void {}
 7 | function bar_1((function(»Sub«): void) $f): void {
 8 |   foo_1($f);
 9 | }

File "fn_subtyping_contra_1.php", line 7, character 26 - line 7, character 28:

1 error found.
