error: Typing[4110] Invalid argument

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2(»$f«);
 9 | }

File "fn_subtyping_contra_2.php", line 8, character 9 - line 8, character 10:

Expected `Sub`

 6 | function foo_2((function((function(»Sub«): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 36 - line 6, character 38:

But got `Super`

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(»Super«): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 36 - line 7, character 40:

This error has 13 steps, a maximum depth of 3 and contains 3 reversals.

Here's why: this hint

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(»Super«): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 36 - line 7, character 40:

flows up into this hint as the 1st function parameter

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function(»(function(Super): void)«): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 26 - line 7, character 48:

which itself flows from this hint because the type was decomposed

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function(»(function(Super): void)«): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 26 - line 7, character 48:

which itself flows from this declaration because they are required to be subtypes

 6 | function foo_2((function(»(function(Sub): void)«): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 26 - line 6, character 46:

which itself flows up from this hint as the 1st function parameter

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2(»(function((function(Super): void)): void)« $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 16 - line 7, character 56:

which itself flows into this expression because it is a parameter hint

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) »$f«): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 58 - line 7, character 59:

which itself flows into this expression because the local variable has this type

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2(»$f«);
 9 | }

File "fn_subtyping_contra_2.php", line 8, character 9 - line 8, character 10:

which itself flows up into this expression as the 1st function parameter

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   »foo_2($f)«;
 9 | }

File "fn_subtyping_contra_2.php", line 8, character 3 - line 8, character 11:

which itself flows from this function or method  because they are required to be subtypes

 6 | function »foo_2«((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 10 - line 6, character 14:

which itself flows down into this hint as the 1st function parameter

 6 | function foo_2((function((function(Sub): void)): void) $_): void {}
 7 | function bar_2(»(function((function(Super): void)): void)« $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 7, character 16 - line 7, character 56:

which itself flows into this declaration because they are required to be subtypes

 6 | function foo_2(»(function((function(Sub): void)): void)« $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 16 - line 6, character 54:

which itself flows into this hint because the type was decomposed

 6 | function foo_2(»(function((function(Sub): void)): void)« $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 16 - line 6, character 54:

which itself flows down from this hint as the 1st function parameter

 6 | function foo_2((function(»(function(Sub): void)«): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 26 - line 6, character 46:

which itself flows down into this hint as the 1st function parameter

 6 | function foo_2((function((function(»Sub«): void)): void) $_): void {}
 7 | function bar_2((function((function(Super): void)): void) $f): void {
 8 |   foo_2($f);
 9 | }

File "fn_subtyping_contra_2.php", line 6, character 36 - line 6, character 38:

1 error found.
