error: Typing[4323] Invalid argument

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound(»$x«);
11 | }

File "generic_subtyping_upper_bound.php", line 10, character 20 - line 10, character 21:

`T` is a constrained type parameter

 7 | function rcvr_upper_bound<»T« as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 27 - line 7, character 27:

This type constraint is violated

 7 | function rcvr_upper_bound<T as »B«>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 32 - line 7, character 32:

Expected `B`

 7 | function rcvr_upper_bound<T as »B«>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 32 - line 7, character 32:

But got `A`

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as »A«>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 9, character 49 - line 9, character 49:

This error has 6 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as »A«>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 9, character 49 - line 9, character 49:

flows into this hint becuase it is the upper bound

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(»T« $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 9, character 52 - line 9, character 52:

which itself flows into this expression because it is a parameter hint

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T »$x«): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 9, character 54 - line 9, character 55:

which itself flows into this expression because the local variable has this type

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound(»$x«);
11 | }

File "generic_subtyping_upper_bound.php", line 10, character 20 - line 10, character 21:

which itself flows up into this expression as the 1st function parameter

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   »rcvr_upper_bound($x)«;
11 | }

File "generic_subtyping_upper_bound.php", line 10, character 3 - line 10, character 22:

which itself flows from this function or method  because they are required to be subtypes

 7 | function »rcvr_upper_bound«<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 10 - line 7, character 25:

which itself flows down into the constraint on the generic parameter as the 1st function parameter

 7 | function rcvr_upper_bound<T as »B«>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 32 - line 7, character 32:

error: Typing[4323] Invalid argument

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound(»$x«);
11 | }

File "generic_subtyping_upper_bound.php", line 10, character 20 - line 10, character 21:

`T` is a constrained type parameter

 7 | function rcvr_upper_bound<»T« as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 27 - line 7, character 27:

This type constraint is violated

 7 | function rcvr_upper_bound<T as »B«>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 32 - line 7, character 32:

Expected `B`

 7 | function rcvr_upper_bound<T as »B«>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 32 - line 7, character 32:

But got `T as A`

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(»T« $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 9, character 52 - line 9, character 52:

This error has 5 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(»T« $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 9, character 52 - line 9, character 52:

flows into this expression because it is a parameter hint

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T »$x«): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 9, character 54 - line 9, character 55:

which itself flows into this expression because the local variable has this type

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound(»$x«);
11 | }

File "generic_subtyping_upper_bound.php", line 10, character 20 - line 10, character 21:

which itself flows up into this expression as the 1st function parameter

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   »rcvr_upper_bound($x)«;
11 | }

File "generic_subtyping_upper_bound.php", line 10, character 3 - line 10, character 22:

which itself flows from this function or method  because they are required to be subtypes

 7 | function »rcvr_upper_bound«<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 10 - line 7, character 25:

which itself flows down into the constraint on the generic parameter as the 1st function parameter

 7 | function rcvr_upper_bound<T as »B«>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_upper_bound<T as A>(T $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_upper_bound.php", line 7, character 32 - line 7, character 32:

2 errors found.
