error: Typing[4110] Invalid argument

Expected `B`

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

But got `mixed` arising from an implicit `as mixed` constraint on this type

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

Here's why: the implicit upper bound (`mixed`) on the generic parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

flows *into* this hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

which itself flows *into* this expression

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T »$x«): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 55 - line 9, character 56:

which itself flows *into* this expression

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

which itself flows *into* this expression, via the (contravariant) 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   »rcvr_concrete«($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 3 - line 10, character 15:

which itself flows *from* this declaration

 7 | function »rcvr_concrete«(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 10 - line 7, character 22:

which itself flows *into* this hint, via the (contravariant) 1st function parameter

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

1 error found.
