error: Typing[4110] Invalid argument

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

Expected `B`

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

But got `mixed`

 5 | namespace HH {
 6 |   newtype supportdyn<+T> as T = »(T & dynamic)«;
 7 | }

File "/tmp/7A6FHhMTCm/supportdynamic.hhi", line 6, character 33 - line 6, character 45:

This error has 9 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 5 | namespace HH {
 6 |   newtype supportdyn<+T> as T = »(T & dynamic)«;
 7 | }

File "/tmp/7A6FHhMTCm/supportdynamic.hhi", line 6, character 33 - line 6, character 45:

flows into this hint because it is the definition

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<»T«>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 50 - line 9, character 50:

which itself flows into this hint becuase it is the upper bound

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

which itself flows into this expression because it is a parameter hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T »$x«): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 55 - line 9, character 56:

which itself flows into this expression because the local variable has this type

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

which itself flows up into this expression as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   »rcvr_concrete($x)«;
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 3 - line 10, character 19:

which itself flows from this function or method  because they are required to be subtypes

 7 | function »rcvr_concrete«(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 10 - line 7, character 22:

which itself flows down into this hint as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<»T«>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 50 - line 9, character 50:

which itself flows into this hint because they are required to be subtypes

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

error: Typing[4110] Invalid argument

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

Expected `B`

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

But got `T`

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

This error has 5 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

flows into this expression because it is a parameter hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T »$x«): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 55 - line 9, character 56:

which itself flows into this expression because the local variable has this type

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

which itself flows up into this expression as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   »rcvr_concrete($x)«;
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 3 - line 10, character 19:

which itself flows from this function or method  because they are required to be subtypes

 7 | function »rcvr_concrete«(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 10 - line 7, character 22:

which itself flows down into this hint as the 1st function parameter

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

2 errors found.
