error: Typing[4110] Invalid argument

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_conrete(A $x): void {
10 |   rcvr_upper_bound(»$x«);
11 | }

File "generic_subtyping_rcvr_upper_bound.php", line 10, character 20 - line 10, character 21:

Expected `B`

 7 | function rcvr_upper_bound<T as »B«>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_conrete(A $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_rcvr_upper_bound.php", line 7, character 32 - line 7, character 32:

But got `A`

 7 | function rcvr_upper_bound<T as B>(T $x): void {}
 8 | 
 9 | function call_upper_bound_with_conrete(»A« $x): void {
10 |   rcvr_upper_bound($x);
11 | }

File "generic_subtyping_rcvr_upper_bound.php", line 9, character 40 - line 9, character 40:

Reason:
{
  "Subtype":{
    "sub":[
      {
        "Prj_both":{
          "sub_prj":[
            {
              "Flow":{
                "from":[
                  {
                    "Flow":{
                      "from":[
                        {
                          "Def":[
                            {
                              "filename":"generic_subtyping_rcvr_upper_bound.php",
                              "line":4,
                              "char_start":7,
                              "char_end":7
                            },
                            [
                              {
                                "Hint":[
                                  {
                                    "filename":"generic_subtyping_rcvr_upper_bound.php",
                                    "line":9,
                                    "char_start":40,
                                    "char_end":40
                                  }
                                ]
                              }
                            ]
                          ]
                        }
                      ],
                      "kind":"Flow_param_hint",
                      "into":[
                        {
                          "Witness":[
                            {
                              "filename":"generic_subtyping_rcvr_upper_bound.php",
                              "line":9,
                              "char_start":42,
                              "char_end":43
                            }
                          ]
                        }
                      ]
                    }
                  }
                ],
                "kind":"Flow_local",
                "into":[
                  {
                    "Witness":[
                      {
                        "filename":"generic_subtyping_rcvr_upper_bound.php",
                        "line":10,
                        "char_start":20,
                        "char_end":21
                      }
                    ]
                  }
                ]
              }
            }
          ],
          "prj":{"Prj_symm_fn_param":[0,0]},
          "sub":[
            {
              "Support_dynamic_type":[
                {
                  "filename":"generic_subtyping_rcvr_upper_bound.php",
                  "line":7,
                  "char_start":10,
                  "char_end":25
                }
              ]
            }
          ],
          "super":[
            {
              "Witness":[
                {
                  "filename":"generic_subtyping_rcvr_upper_bound.php",
                  "line":10,
                  "char_start":3,
                  "char_end":22
                }
              ]
            }
          ]
        }
      }
    ],
    "super":[
      {
        "Upper_bound":{
          "bound":[
            {
              "Cstr_on_generics":[
                {
                  "filename":"generic_subtyping_rcvr_upper_bound.php",
                  "line":7,
                  "char_start":32,
                  "char_end":32
                },
                {
                  "Tuple2":[
                    {
                      "filename":"generic_subtyping_rcvr_upper_bound.php",
                      "line":7,
                      "char_start":27,
                      "char_end":27
                    },
                    "T"
                  ]
                }
              ]
            }
          ],
          "of":[
            {
              "Type_variable_generics":[
                {
                  "filename":"generic_subtyping_rcvr_upper_bound.php",
                  "line":10,
                  "char_start":3,
                  "char_end":18
                },
                "T",
                "rcvr_upper_bound"
              ]
            }
          ]
        }
      }
    ]
  }
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
