error: Typing[4110] Invalid argument

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

Expected `B`

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

But got `mixed`

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<»T«>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 50 - line 9, character 50:

This error has 7 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<»T«>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 50 - line 9, character 50:

flows into this hint becuase it is the upper bound

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

which itself flows into this expression because it is a parameter hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T »$x«): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 55 - line 9, character 56:

which itself flows into this expression because the local variable has this type

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

which itself flows up into this expression as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   »rcvr_concrete($x)«;
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 3 - line 10, character 19:

which itself flows from this function or method  because they are required to be subtypes

 7 | function »rcvr_concrete«(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 10 - line 7, character 22:

which itself flows down into this hint as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<»T«>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 50 - line 9, character 50:

which itself flows into this hint because they are required to be subtypes

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

Raw:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rflow":[
            {
              "Rdef":[
                {
                  "filename":"/tmp/jWvHwsu0Cd/supportdynamic.hhi",
                  "line":6,
                  "char_start":11,
                  "char_end":20
                },
                {
                  "Rhint":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":50,
                      "char_end":50
                    }
                  ]
                }
              ]
            },
            "Flow_upper_bound",
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rflow":[
                        {
                          "Rhint":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":9,
                              "char_start":53,
                              "char_end":53
                            }
                          ]
                        },
                        "Flow_param_hint",
                        {
                          "Rwitness":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":9,
                              "char_start":55,
                              "char_end":56
                            }
                          ]
                        }
                      ]
                    },
                    "Flow_local",
                    {
                      "Rwitness":[
                        {
                          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                          "line":10,
                          "char_start":17,
                          "char_end":18
                        }
                      ]
                    }
                  ]
                },
                "Flow_prj",
                {
                  "Rprj":[
                    {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                    {
                      "Rflow":[
                        {
                          "Rwitness":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":10,
                              "char_start":3,
                              "char_end":19
                            }
                          ]
                        },
                        "Flow_subtype",
                        {
                          "Rrev":[
                            {
                              "Rsupport_dynamic_type":[
                                {
                                  "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                                  "line":7,
                                  "char_start":10,
                                  "char_end":22
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        "Flow_upper_bound",
        {
          "Rdef":[
            {
              "filename":"/tmp/jWvHwsu0Cd/supportdynamic.hhi",
              "line":6,
              "char_start":11,
              "char_end":20
            },
            {
              "Rhint":[
                {
                  "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                  "line":9,
                  "char_start":50,
                  "char_end":50
                }
              ]
            }
          ]
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "Rdef":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":5,
          "char_start":7,
          "char_end":7
        },
        {
          "Rhint":[
            {
              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
              "line":7,
              "char_start":24,
              "char_end":24
            }
          ]
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Normalised:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rflow":[
            {
              "Rdef":[
                {
                  "filename":"/tmp/jWvHwsu0Cd/supportdynamic.hhi",
                  "line":6,
                  "char_start":11,
                  "char_end":20
                },
                {
                  "Rhint":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":50,
                      "char_end":50
                    }
                  ]
                }
              ]
            },
            "Flow_upper_bound",
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rflow":[
                        {
                          "Rhint":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":9,
                              "char_start":53,
                              "char_end":53
                            }
                          ]
                        },
                        "Flow_param_hint",
                        {
                          "Rwitness":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":9,
                              "char_start":55,
                              "char_end":56
                            }
                          ]
                        }
                      ]
                    },
                    "Flow_local",
                    {
                      "Rwitness":[
                        {
                          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                          "line":10,
                          "char_start":17,
                          "char_end":18
                        }
                      ]
                    }
                  ]
                },
                "Flow_prj",
                {
                  "Rprj":[
                    {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                    {
                      "Rflow":[
                        {
                          "Rwitness":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":10,
                              "char_start":3,
                              "char_end":19
                            }
                          ]
                        },
                        "Flow_subtype",
                        {
                          "Rsupport_dynamic_type":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":7,
                              "char_start":10,
                              "char_end":22
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        "Flow_upper_bound",
        {
          "Rdef":[
            {
              "filename":"/tmp/jWvHwsu0Cd/supportdynamic.hhi",
              "line":6,
              "char_start":11,
              "char_end":20
            },
            {
              "Rhint":[
                {
                  "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                  "line":9,
                  "char_start":50,
                  "char_end":50
                }
              ]
            }
          ]
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "Rdef":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":5,
          "char_start":7,
          "char_end":7
        },
        {
          "Rhint":[
            {
              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
              "line":7,
              "char_start":24,
              "char_end":24
            }
          ]
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Path:
{
  "stats":{"max_depth":1,"length":7,"reversals":1},
  "path_elems":[
    {
      "Rdef":[
        {
          "filename":"/tmp/jWvHwsu0Cd/supportdynamic.hhi",
          "line":6,
          "char_start":11,
          "char_end":20
        },
        {
          "Rhint":[
            {
              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
              "line":9,
              "char_start":50,
              "char_end":50
            }
          ]
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_upper_bound"}},
    {
      "Rhint":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":9,
          "char_start":53,
          "char_end":53
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_param_hint"}},
    {
      "Rwitness":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":9,
          "char_start":55,
          "char_end":56
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_local"}},
    {
      "Rwitness":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":10,
          "char_start":17,
          "char_end":18
        }
      ]
    },
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    {
      "Rwitness":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":10,
          "char_start":3,
          "char_end":19
        }
      ]
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_subtype"}},
    {
      "Rsupport_dynamic_type":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":7,
          "char_start":10,
          "char_end":22
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_upper_bound",
        "out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}
      }
    },
    {
      "Rdef":[
        {
          "filename":"/tmp/jWvHwsu0Cd/supportdynamic.hhi",
          "line":6,
          "char_start":11,
          "char_end":20
        },
        {
          "Rhint":[
            {
              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
              "line":9,
              "char_start":50,
              "char_end":50
            }
          ]
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_subtype_toplevel"}},
    {
      "Rdef":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":5,
          "char_start":7,
          "char_end":7
        },
        {
          "Rhint":[
            {
              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
              "line":7,
              "char_start":24,
              "char_end":24
            }
          ]
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

error: Typing[4110] Invalid argument

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

Expected `B`

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

But got `T`

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

This error has 5 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

flows into this expression because it is a parameter hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T »$x«): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 55 - line 9, character 56:

which itself flows into this expression because the local variable has this type

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

which itself flows up into this expression as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   »rcvr_concrete($x)«;
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 3 - line 10, character 19:

which itself flows from this function or method  because they are required to be subtypes

 7 | function »rcvr_concrete«(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 10 - line 7, character 22:

which itself flows down into this hint as the 1st function parameter

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

Raw:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rflow":[
            {
              "Rflow":[
                {
                  "Rhint":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":53,
                      "char_end":53
                    }
                  ]
                },
                "Flow_param_hint",
                {
                  "Rwitness":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":55,
                      "char_end":56
                    }
                  ]
                }
              ]
            },
            "Flow_local",
            {
              "Rwitness":[
                {
                  "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                  "line":10,
                  "char_start":17,
                  "char_end":18
                }
              ]
            }
          ]
        },
        "Flow_prj",
        {
          "Rprj":[
            {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
            {
              "Rflow":[
                {
                  "Rwitness":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":10,
                      "char_start":3,
                      "char_end":19
                    }
                  ]
                },
                "Flow_subtype",
                {
                  "Rrev":[
                    {
                      "Rsupport_dynamic_type":[
                        {
                          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                          "line":7,
                          "char_start":10,
                          "char_end":22
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "Rdef":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":5,
          "char_start":7,
          "char_end":7
        },
        {
          "Rhint":[
            {
              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
              "line":7,
              "char_start":24,
              "char_end":24
            }
          ]
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Normalised:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rflow":[
            {
              "Rflow":[
                {
                  "Rhint":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":53,
                      "char_end":53
                    }
                  ]
                },
                "Flow_param_hint",
                {
                  "Rwitness":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":55,
                      "char_end":56
                    }
                  ]
                }
              ]
            },
            "Flow_local",
            {
              "Rwitness":[
                {
                  "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                  "line":10,
                  "char_start":17,
                  "char_end":18
                }
              ]
            }
          ]
        },
        "Flow_prj",
        {
          "Rprj":[
            {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
            {
              "Rflow":[
                {
                  "Rwitness":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":10,
                      "char_start":3,
                      "char_end":19
                    }
                  ]
                },
                "Flow_subtype",
                {
                  "Rsupport_dynamic_type":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":7,
                      "char_start":10,
                      "char_end":22
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "Rdef":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":5,
          "char_start":7,
          "char_end":7
        },
        {
          "Rhint":[
            {
              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
              "line":7,
              "char_start":24,
              "char_end":24
            }
          ]
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Path:
{
  "stats":{"max_depth":1,"length":5,"reversals":1},
  "path_elems":[
    {
      "Rhint":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":9,
          "char_start":53,
          "char_end":53
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_param_hint"}},
    {
      "Rwitness":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":9,
          "char_start":55,
          "char_end":56
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_local"}},
    {
      "Rwitness":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":10,
          "char_start":17,
          "char_end":18
        }
      ]
    },
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    {
      "Rwitness":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":10,
          "char_start":3,
          "char_end":19
        }
      ]
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_subtype"}},
    {
      "Rsupport_dynamic_type":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":7,
          "char_start":10,
          "char_end":22
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype_toplevel",
        "out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}
      }
    },
    {
      "Rdef":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":5,
          "char_start":7,
          "char_end":7
        },
        {
          "Rhint":[
            {
              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
              "line":7,
              "char_start":24,
              "char_end":24
            }
          ]
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

2 errors found.
