error: Typing[4110] Invalid argument

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

Expected `B`

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

But got `mixed`

 5 | namespace HH {
 6 |   newtype supportdyn<+T> as T = »(T & dynamic)«;
 7 | }

File "/tmp/pMsnGnwRlb/supportdynamic.hhi", line 6, character 33 - line 6, character 45:

This error has 9 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 5 | namespace HH {
 6 |   newtype supportdyn<+T> as T = »(T & dynamic)«;
 7 | }

File "/tmp/pMsnGnwRlb/supportdynamic.hhi", line 6, character 33 - line 6, character 45:

flows into this hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<»T«>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 50 - line 9, character 50:

which itself flows into this hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

which itself flows into this expression

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T »$x«): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 55 - line 9, character 56:

which itself flows into this expression

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

which itself flows up into this expression as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   »rcvr_concrete«($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 3 - line 10, character 15:

which itself flows from this function or method 

 7 | function »rcvr_concrete«(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 10 - line 7, character 22:

which itself flows down into this hint as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<»T«>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 50 - line 9, character 50:

which itself flows into this hint

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

Flow:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rflow":[
            {
              "Rflow":[
                {
                  "Rhint":[
                    {
                      "filename":"/tmp/pMsnGnwRlb/supportdynamic.hhi",
                      "line":6,
                      "char_start":33,
                      "char_end":45
                    }
                  ]
                },
                {
                  "Rhint":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":50,
                      "char_end":50
                    }
                  ]
                }
              ]
            },
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rflow":[
                        {
                          "Rhint":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":9,
                              "char_start":53,
                              "char_end":53
                            }
                          ]
                        },
                        {
                          "Rwitness":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":9,
                              "char_start":55,
                              "char_end":56
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "Rwitness":[
                        {
                          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                          "line":10,
                          "char_start":17,
                          "char_end":18
                        }
                      ]
                    }
                  ]
                },
                {
                  "Rprj":[
                    {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                    {
                      "Rflow":[
                        {
                          "Rwitness":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":10,
                              "char_start":3,
                              "char_end":15
                            }
                          ]
                        },
                        {
                          "Rsupport_dynamic_type":[
                            {
                              "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                              "line":7,
                              "char_start":10,
                              "char_end":22
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "Rflow":[
            {
              "Rhint":[
                {
                  "filename":"/tmp/pMsnGnwRlb/supportdynamic.hhi",
                  "line":6,
                  "char_start":33,
                  "char_end":45
                }
              ]
            },
            {
              "Rhint":[
                {
                  "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                  "line":9,
                  "char_start":50,
                  "char_end":50
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":7,
          "char_start":24,
          "char_end":24
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

error: Typing[4110] Invalid argument

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

Expected `B`

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

But got `T`

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

This error has 5 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(»T« $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 53 - line 9, character 53:

flows into this expression

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T »$x«): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 9, character 55 - line 9, character 56:

which itself flows into this expression

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete(»$x«);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 17 - line 10, character 18:

which itself flows up into this expression as the 1st function parameter

 7 | function rcvr_concrete(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   »rcvr_concrete«($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 10, character 3 - line 10, character 15:

which itself flows from this function or method 

 7 | function »rcvr_concrete«(B $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 10 - line 7, character 22:

which itself flows down into this hint as the 1st function parameter

 7 | function rcvr_concrete(»B« $x): void {}
 8 | 
 9 | function call_concrete_with_implicit_upper_bound<T>(T $x): void {
10 |   rcvr_concrete($x);
11 | }

File "generic_subtyping_caller_implicit_upper_bound.php", line 7, character 24 - line 7, character 24:

Flow:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rflow":[
            {
              "Rflow":[
                {
                  "Rhint":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":53,
                      "char_end":53
                    }
                  ]
                },
                {
                  "Rwitness":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":9,
                      "char_start":55,
                      "char_end":56
                    }
                  ]
                }
              ]
            },
            {
              "Rwitness":[
                {
                  "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                  "line":10,
                  "char_start":17,
                  "char_end":18
                }
              ]
            }
          ]
        },
        {
          "Rprj":[
            {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
            {
              "Rflow":[
                {
                  "Rwitness":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":10,
                      "char_start":3,
                      "char_end":15
                    }
                  ]
                },
                {
                  "Rsupport_dynamic_type":[
                    {
                      "filename":"generic_subtyping_caller_implicit_upper_bound.php",
                      "line":7,
                      "char_start":10,
                      "char_end":22
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "Rhint":[
        {
          "filename":"generic_subtyping_caller_implicit_upper_bound.php",
          "line":7,
          "char_start":24,
          "char_end":24
        }
      ]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

2 errors found.
