error: Typing[4110] Invalid return type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   return »$c«;
10 | }

File "intersection_subtyping_l.php", line 9, character 10 - line 9, character 11:

Expected `C`

 7 | function inter_l((A & I) $ai): »C« {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 32 - line 7, character 32:

But got `(A & I)`

 7 | function inter_l(»(A & I)« $ai): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 18 - line 7, character 24:

This error has 6 steps, a maximum depth of 0 and contains 0 reversals.

Here's why: this hint

 7 | function inter_l(»(A & I)« $ai): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 18 - line 7, character 24:

flows into this expression because it is a parameter hint

 7 | function inter_l((A & I) »$ai«): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 26 - line 7, character 28:

which itself flows into this expression because the local variable has this type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = »$ai«;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 8, character 8 - line 8, character 10:

which itself flows into this expression because of an assignment

 7 | function inter_l((A & I) $ai): C {
 8 |   »$c« = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 8, character 3 - line 8, character 4:

which itself flows into this expression because the local variable has this type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   return »$c«;
10 | }

File "intersection_subtyping_l.php", line 9, character 10 - line 9, character 11:

which itself flows into this expression because the expression is in return position

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   »return $c;«
10 | }

File "intersection_subtyping_l.php", line 9, character 3 - line 9, character 12:

which itself flows into this hint because they are required to be subtypes

 7 | function inter_l((A & I) $ai): »C« {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 32 - line 7, character 32:

error: Typing[4110] Invalid return type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   return »$c«;
10 | }

File "intersection_subtyping_l.php", line 9, character 10 - line 9, character 11:

Expected `C`

 7 | function inter_l((A & I) $ai): »C« {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 32 - line 7, character 32:

But got `A`

 7 | function inter_l((»A« & I) $ai): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 19 - line 7, character 19:

This error has 7 steps, a maximum depth of 1 and contains 0 reversals.

Here's why: this hint

 7 | function inter_l((»A« & I) $ai): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 19 - line 7, character 19:

flows up into this hint as an element of the intersection type

 7 | function inter_l(»(A & I)« $ai): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 18 - line 7, character 24:

which itself flows into this expression because it is a parameter hint

 7 | function inter_l((A & I) »$ai«): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 26 - line 7, character 28:

which itself flows into this expression because the local variable has this type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = »$ai«;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 8, character 8 - line 8, character 10:

which itself flows into this expression because of an assignment

 7 | function inter_l((A & I) $ai): C {
 8 |   »$c« = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 8, character 3 - line 8, character 4:

which itself flows into this expression because the local variable has this type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   return »$c«;
10 | }

File "intersection_subtyping_l.php", line 9, character 10 - line 9, character 11:

which itself flows into this expression because the expression is in return position

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   »return $c;«
10 | }

File "intersection_subtyping_l.php", line 9, character 3 - line 9, character 12:

which itself flows into this hint because they are required to be subtypes

 7 | function inter_l((A & I) $ai): »C« {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 32 - line 7, character 32:

error: Typing[4110] Invalid return type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   return »$c«;
10 | }

File "intersection_subtyping_l.php", line 9, character 10 - line 9, character 11:

Expected `C`

 7 | function inter_l((A & I) $ai): »C« {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 32 - line 7, character 32:

But got `I`

 7 | function inter_l((A & »I«) $ai): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 23 - line 7, character 23:

This error has 7 steps, a maximum depth of 1 and contains 0 reversals.

Here's why: this hint

 7 | function inter_l((A & »I«) $ai): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 23 - line 7, character 23:

flows up into this hint as an element of the intersection type

 7 | function inter_l(»(A & I)« $ai): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 18 - line 7, character 24:

which itself flows into this expression because it is a parameter hint

 7 | function inter_l((A & I) »$ai«): C {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 26 - line 7, character 28:

which itself flows into this expression because the local variable has this type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = »$ai«;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 8, character 8 - line 8, character 10:

which itself flows into this expression because of an assignment

 7 | function inter_l((A & I) $ai): C {
 8 |   »$c« = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 8, character 3 - line 8, character 4:

which itself flows into this expression because the local variable has this type

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   return »$c«;
10 | }

File "intersection_subtyping_l.php", line 9, character 10 - line 9, character 11:

which itself flows into this expression because the expression is in return position

 7 | function inter_l((A & I) $ai): C {
 8 |   $c = $ai;
 9 |   »return $c;«
10 | }

File "intersection_subtyping_l.php", line 9, character 3 - line 9, character 12:

which itself flows into this hint because they are required to be subtypes

 7 | function inter_l((A & I) $ai): »C« {
 8 |   $c = $ai;
 9 |   return $c;
10 | }

File "intersection_subtyping_l.php", line 7, character 32 - line 7, character 32:

3 errors found.
