error: Typing[4110] Invalid argument

 7 | function pass_my_int(myint $y) : bool {
 8 |   return expect_bool(»$y«);
 9 | }

File "newtype1.php--file2.php", line 8, character 22 - line 8, character 23:

Expected `bool`

 3 | function expect_bool(»bool« $x): bool {
 4 |   return $x;
 5 | }

File "newtype1.php--file2.php", line 3, character 22 - line 3, character 25:

But got `int`

 7 | function pass_my_int(»myint« $y) : bool {
 8 |   return expect_bool($y);
 9 | }

File "newtype1.php--file2.php", line 7, character 22 - line 7, character 26:

This error has 6 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this hint

 7 | function pass_my_int(»myint« $y) : bool {
 8 |   return expect_bool($y);
 9 | }

File "newtype1.php--file2.php", line 7, character 22 - line 7, character 26:

flows into this expression because it is a parameter hint

 7 | function pass_my_int(myint »$y«) : bool {
 8 |   return expect_bool($y);
 9 | }

File "newtype1.php--file2.php", line 7, character 28 - line 7, character 29:

which itself flows into this expression because the local variable has this type

 7 | function pass_my_int(myint $y) : bool {
 8 |   return expect_bool(»$y«);
 9 | }

File "newtype1.php--file2.php", line 8, character 22 - line 8, character 23:

which itself flows up into this expression as the 1st function parameter

 7 | function pass_my_int(myint $y) : bool {
 8 |   return »expect_bool($y)«;
 9 | }

File "newtype1.php--file2.php", line 8, character 10 - line 8, character 24:

which itself flows from this function or method  because they are required to be subtypes

 3 | function »expect_bool«(bool $x): bool {
 4 |   return $x;
 5 | }

File "newtype1.php--file2.php", line 3, character 10 - line 3, character 20:

which itself flows down into this hint as the 1st function parameter

 3 | newtype myint as »int« = int;

File "newtype1.php--file1.php", line 3, character 18 - line 3, character 20:

which itself flows into this hint because they are required to be subtypes

 3 | function expect_bool(»bool« $x): bool {
 4 |   return $x;
 5 | }

File "newtype1.php--file2.php", line 3, character 22 - line 3, character 25:

Raw:
{
  "Flow":[
    {
      "Flow":[
        {
          "Flow":[
            {
              "Flow":[
                {
                  "Flow":[
                    {
                      "Def":[
                        {"filename":"newtype1.php--file1.php","line":3,"char_start":9,"char_end":13},
                        {
                          "From_witness_decl":{
                            "Hint":[{"filename":"newtype1.php--file2.php","line":7,"char_start":22,"char_end":26}]
                          }
                        }
                      ]
                    },
                    "Flow_param_hint",
                    {
                      "From_witness_locl":{
                        "Witness":[{"filename":"newtype1.php--file2.php","line":7,"char_start":28,"char_end":29}]
                      }
                    }
                  ]
                },
                "Flow_local",
                {
                  "From_witness_locl":{
                    "Witness":[{"filename":"newtype1.php--file2.php","line":8,"char_start":22,"char_end":23}]
                  }
                }
              ]
            },
            "Flow_prj",
            {
              "Prj":[
                {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                {
                  "Flow":[
                    {
                      "From_witness_locl":{
                        "Witness":[{"filename":"newtype1.php--file2.php","line":8,"char_start":10,"char_end":24}]
                      }
                    },
                    "Flow_subtype",
                    {
                      "Rev":[
                        {
                          "From_witness_decl":{
                            "Support_dynamic_type":[{"filename":"newtype1.php--file2.php","line":3,"char_start":10,"char_end":20}]
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        "Flow_upper_bound",
        {
          "From_witness_decl":{
            "Hint":[{"filename":"newtype1.php--file1.php","line":3,"char_start":18,"char_end":20}]
          }
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "From_witness_decl":{
        "Hint":[{"filename":"newtype1.php--file2.php","line":3,"char_start":22,"char_end":25}]
      }
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Normalised:
{
  "Flow":[
    {
      "Flow":[
        {
          "Flow":[
            {
              "Flow":[
                {
                  "Flow":[
                    {
                      "Def":[
                        {"filename":"newtype1.php--file1.php","line":3,"char_start":9,"char_end":13},
                        {
                          "From_witness_decl":{
                            "Hint":[{"filename":"newtype1.php--file2.php","line":7,"char_start":22,"char_end":26}]
                          }
                        }
                      ]
                    },
                    "Flow_param_hint",
                    {
                      "From_witness_locl":{
                        "Witness":[{"filename":"newtype1.php--file2.php","line":7,"char_start":28,"char_end":29}]
                      }
                    }
                  ]
                },
                "Flow_local",
                {
                  "From_witness_locl":{
                    "Witness":[{"filename":"newtype1.php--file2.php","line":8,"char_start":22,"char_end":23}]
                  }
                }
              ]
            },
            "Flow_prj",
            {
              "Prj":[
                {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                {
                  "Flow":[
                    {
                      "From_witness_locl":{
                        "Witness":[{"filename":"newtype1.php--file2.php","line":8,"char_start":10,"char_end":24}]
                      }
                    },
                    "Flow_subtype",
                    {
                      "From_witness_decl":{
                        "Support_dynamic_type":[{"filename":"newtype1.php--file2.php","line":3,"char_start":10,"char_end":20}]
                      }
                    }
                  ]
                }
              ]
            }
          ]
        },
        "Flow_upper_bound",
        {
          "From_witness_decl":{
            "Hint":[{"filename":"newtype1.php--file1.php","line":3,"char_start":18,"char_end":20}]
          }
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "From_witness_decl":{
        "Hint":[{"filename":"newtype1.php--file2.php","line":3,"char_start":22,"char_end":25}]
      }
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Path:
{
  "stats":{"max_depth":1,"length":6,"reversals":1},
  "path_elems":[
    {
      "Def":[
        {"filename":"newtype1.php--file1.php","line":3,"char_start":9,"char_end":13},
        {
          "From_witness_decl":{
            "Hint":[{"filename":"newtype1.php--file2.php","line":7,"char_start":22,"char_end":26}]
          }
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_param_hint"}},
    {
      "From_witness_locl":{
        "Witness":[{"filename":"newtype1.php--file2.php","line":7,"char_start":28,"char_end":29}]
      }
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_local"}},
    {
      "From_witness_locl":{
        "Witness":[{"filename":"newtype1.php--file2.php","line":8,"char_start":22,"char_end":23}]
      }
    },
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    {
      "From_witness_locl":{
        "Witness":[{"filename":"newtype1.php--file2.php","line":8,"char_start":10,"char_end":24}]
      }
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_subtype"}},
    {
      "From_witness_decl":{
        "Support_dynamic_type":[{"filename":"newtype1.php--file2.php","line":3,"char_start":10,"char_end":20}]
      }
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_upper_bound",
        "out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}
      }
    },
    {
      "From_witness_decl":{
        "Hint":[{"filename":"newtype1.php--file1.php","line":3,"char_start":18,"char_end":20}]
      }
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_subtype_toplevel"}},
    {
      "From_witness_decl":{
        "Hint":[{"filename":"newtype1.php--file2.php","line":3,"char_start":22,"char_end":25}]
      }
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
