error: Typing[4110] Invalid argument

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

Expected bool

File optional_sub_newtype_if_unsat.php, line 3, character 20 - line 3, character 23:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (»bool«|int);
 4 | 
 5 | function foo(MyThing $_): void {}

But got string

File optional_sub_newtype_if_unsat.php, line 7, character 15 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?»string« $x): void {
 8 |   foo($x);
 9 | }

Here's why:


  Step 1 of 5                                                                   

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File optional_sub_newtype_if_unsat.php, line 5, character 10 - line 5, character 12:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function »foo«(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this expression

File optional_sub_newtype_if_unsat.php, line 8, character 3 - line 8, character 9:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   »foo($x)«;
 9 | }


  Step 2 of 5                                                                   

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File optional_sub_newtype_if_unsat.php, line 7, character 22 - line 7, character 23:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype comes from this hint

File optional_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

which is defined here

File optional_sub_newtype_if_unsat.php, line 3, character 19 - line 3, character 28:

 1 | <?hh
 2 | 
 3 | newtype MyThing = »(bool|int)«;
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 3 of 5                                                                   

The supertype is a union type so next I checked the subtype constraint is satisfied for at least one element.

The subtype is the same as before.

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this hint

File optional_sub_newtype_if_unsat.php, line 3, character 20 - line 3, character 23:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (»bool«|int);
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 4 of 5                                                                   

The subtype is a nullable type so next I checked the subtype constraint is satisfied for both the null & non-null parts.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File optional_sub_newtype_if_unsat.php, line 7, character 22 - line 7, character 23:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype is the same as before.

File optional_sub_newtype_if_unsat.php, line 3, character 20 - line 3, character 23:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (»bool«|int);
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 5 of 5                                 (here is where the error occurred) 

The subtype is a nullable type so next I checked the subtype constraint is satisfied for both the null & non-null parts.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 15 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?»string« $x): void {
 8 |   foo($x);
 9 | }

The supertype is the same as before.

File optional_sub_newtype_if_unsat.php, line 3, character 20 - line 3, character 23:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (»bool«|int);
 4 | 
 5 | function foo(MyThing $_): void {}

error: Typing[4110] Invalid argument

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

Expected int

File optional_sub_newtype_if_unsat.php, line 3, character 25 - line 3, character 27:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (bool|»int«);
 4 | 
 5 | function foo(MyThing $_): void {}

But got string

File optional_sub_newtype_if_unsat.php, line 7, character 15 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?»string« $x): void {
 8 |   foo($x);
 9 | }

Here's why:


  Step 1 of 5                                                                   

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File optional_sub_newtype_if_unsat.php, line 5, character 10 - line 5, character 12:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function »foo«(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this expression

File optional_sub_newtype_if_unsat.php, line 8, character 3 - line 8, character 9:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   »foo($x)«;
 9 | }


  Step 2 of 5                                                                   

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File optional_sub_newtype_if_unsat.php, line 7, character 22 - line 7, character 23:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype comes from this hint

File optional_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

which is defined here

File optional_sub_newtype_if_unsat.php, line 3, character 19 - line 3, character 28:

 1 | <?hh
 2 | 
 3 | newtype MyThing = »(bool|int)«;
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 3 of 5                                                                   

The supertype is a union type so next I checked the subtype constraint is satisfied for at least one element.

The subtype is the same as before.

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this hint

File optional_sub_newtype_if_unsat.php, line 3, character 25 - line 3, character 27:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (bool|»int«);
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 4 of 5                                                                   

The subtype is a nullable type so next I checked the subtype constraint is satisfied for both the null & non-null parts.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File optional_sub_newtype_if_unsat.php, line 7, character 22 - line 7, character 23:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype is the same as before.

File optional_sub_newtype_if_unsat.php, line 3, character 25 - line 3, character 27:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (bool|»int«);
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 5 of 5                                 (here is where the error occurred) 

The subtype is a nullable type so next I checked the subtype constraint is satisfied for both the null & non-null parts.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 15 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?»string« $x): void {
 8 |   foo($x);
 9 | }

The supertype is the same as before.

File optional_sub_newtype_if_unsat.php, line 3, character 25 - line 3, character 27:

 1 | <?hh
 2 | 
 3 | newtype MyThing = (bool|»int«);
 4 | 
 5 | function foo(MyThing $_): void {}

error: Typing[4110] Invalid argument

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

Expected (int | bool)

File optional_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

But got ?string

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

Here's why:


  Step 1 of 2                                                                   

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File optional_sub_newtype_if_unsat.php, line 5, character 10 - line 5, character 12:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function »foo«(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this expression

File optional_sub_newtype_if_unsat.php, line 8, character 3 - line 8, character 9:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   »foo($x)«;
 9 | }


  Step 2 of 2                                 (here is where the error occurred) 

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File optional_sub_newtype_if_unsat.php, line 7, character 22 - line 7, character 23:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype comes from this hint

File optional_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

which is defined here

File optional_sub_newtype_if_unsat.php, line 3, character 19 - line 3, character 28:

 1 | <?hh
 2 | 
 3 | newtype MyThing = »(bool|int)«;
 4 | 
 5 | function foo(MyThing $_): void {}

error: Typing[4110] Invalid argument

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

Expected (int | bool)

File optional_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

But got string

File optional_sub_newtype_if_unsat.php, line 7, character 15 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?»string« $x): void {
 8 |   foo($x);
 9 | }

Here's why:


  Step 1 of 4                                                                   

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File optional_sub_newtype_if_unsat.php, line 5, character 10 - line 5, character 12:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function »foo«(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

The supertype comes from this expression

File optional_sub_newtype_if_unsat.php, line 8, character 3 - line 8, character 9:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   »foo($x)«;
 9 | }


  Step 2 of 4                                                                   

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File optional_sub_newtype_if_unsat.php, line 7, character 22 - line 7, character 23:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype comes from this hint

File optional_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

which is defined here

File optional_sub_newtype_if_unsat.php, line 3, character 19 - line 3, character 28:

 1 | <?hh
 2 | 
 3 | newtype MyThing = »(bool|int)«;
 4 | 
 5 | function foo(MyThing $_): void {}


  Step 3 of 4                                                                   

The subtype is a nullable type so next I checked the subtype constraint is satisfied for both the null & non-null parts.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 14 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(»?string« $x): void {
 8 |   foo($x);
 9 | }

and flows into this expression

File optional_sub_newtype_if_unsat.php, line 7, character 22 - line 7, character 23:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string »$x«): void {
 8 |   foo($x);
 9 | }

as the parameter hint

which itself flows into this expression

File optional_sub_newtype_if_unsat.php, line 8, character 7 - line 8, character 8:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo(»$x«);
 9 | }

as the type of the local variable

The supertype is the same as before.

File optional_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }


  Step 4 of 4                                 (here is where the error occurred) 

The subtype is a nullable type so next I checked the subtype constraint is satisfied for both the null & non-null parts.

The subtype comes from this hint

File optional_sub_newtype_if_unsat.php, line 7, character 15 - line 7, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(MyThing $_): void {}
 6 | 
 7 | function bar(?»string« $x): void {
 8 |   foo($x);
 9 | }

The supertype is the same as before.

File optional_sub_newtype_if_unsat.php, line 5, character 14 - line 5, character 20:

 3 | newtype MyThing = (bool|int);
 4 | 
 5 | function foo(»MyThing« $_): void {}
 6 | 
 7 | function bar(?string $x): void {
 8 |   foo($x);
 9 | }

4 errors found
