error: Typing[4110] Invalid return type

File "refinement_equal.php", line 12, character 10 - line 12, character 11:

 11 |   }
 12 |   return »$z«;
 13 | }

Expected `C`

File "refinement_equal.php", line 6, character 36 - line 6, character 36:

 6 | function inter_equal(?A $a, C $c): »C« {
 7 |   if($a == null) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

But got `null`

File "refinement_equal.php", line 6, character 22 - line 6, character 23:

 6 | function inter_equal(»?A« $a, C $c): C {
 7 |   if($a == null) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

Here's why:

Step 1 of 2

I started by checking this subtype relationship.

The subtype comes from this type variable

File "refinement_equal.php", line 7, character 6 - line 7, character 15:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if(»$a == null«) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

and flows into this expression as the type of the local variable

File "refinement_equal.php", line 8, character 10 - line 8, character 11:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if($a == null) {
 8 |     $z = »$a«;
 9 |   } else {
10 |     $z = $c;

which itself flows into this expression via an assignment

File "refinement_equal.php", line 8, character 5 - line 8, character 6:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if($a == null) {
 8 |     »$z« = $a;
 9 |   } else {
10 |     $z = $c;

which I solved to this type variable

File "refinement_equal.php", line 7, character 6 - line 7, character 15:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if(»$a == null«) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

and flows into this expression as the type of the local variable

File "refinement_equal.php", line 12, character 10 - line 12, character 11:

 11 |   }
 12 |   return »$z«;
 13 | }

which itself flows into this expression because it is used in a return position

File "refinement_equal.php", line 12, character 3 - line 12, character 12:

 11 |   }
 12 |   »return $z;«
 13 | }

The supertype comes from this hint

File "refinement_equal.php", line 6, character 36 - line 6, character 36:

 6 | function inter_equal(?A $a, C $c): »C« {
 7 |   if($a == null) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

which is defined here

File "refinement_equal.php", line 4, character 7 - line 4, character 7:

 3 | class A {}
 4 | class »C« extends A {}
 5 | 
 6 | function inter_equal(?A $a, C $c): C {

Step 2 of 2 (here is where the error occurred)

The subtype is a nullable type so next I checked the subtype constraint is satisfied for both the null & non-null parts.

The subtype comes from this type variable

File "refinement_equal.php", line 7, character 6 - line 7, character 15:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if(»$a == null«) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

and flows into this expression as the type of the local variable

File "refinement_equal.php", line 8, character 10 - line 8, character 11:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if($a == null) {
 8 |     $z = »$a«;
 9 |   } else {
10 |     $z = $c;

which itself flows into this expression via an assignment

File "refinement_equal.php", line 8, character 5 - line 8, character 6:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if($a == null) {
 8 |     »$z« = $a;
 9 |   } else {
10 |     $z = $c;

which I solved to this type variable

File "refinement_equal.php", line 7, character 6 - line 7, character 15:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if(»$a == null«) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

and flows into this expression as the type of the local variable

File "refinement_equal.php", line 12, character 10 - line 12, character 11:

 11 |   }
 12 |   return »$z«;
 13 | }

which itself flows into this expression because it is used in a return position

File "refinement_equal.php", line 12, character 3 - line 12, character 12:

 11 |   }
 12 |   »return $z;«
 13 | }

The supertype is the same as before.

File "refinement_equal.php", line 6, character 36 - line 6, character 36:

 6 | function inter_equal(?A $a, C $c): »C« {
 7 |   if($a == null) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

1 error found
