error: Typing[4110] Invalid return type

File "refinement_equal.php", line 12, character 10 - line 12, character 11:

 11 |   }
 12 |   return »$z«;
 13 | }

Expected `~C` because the type of this return is implicitly a like-type

File "refinement_equal.php", line 6, character 36 - line 6, character 36:

 6 | function inter_equal(?A $a, C $c): »C« {
 7 |   if($a == null) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

But got `?C`

File "refinement_equal.php", line 6, character 22 - line 6, character 23:

 6 | function inter_equal(»?A« $a, C $c): C {
 7 |   if($a == null) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

Here's why:


Step 1 of 1 (here is where the error occurred)

I started by checking this subtype relationship.

The subtype comes from this type variable

File "refinement_equal.php", line 7, character 6 - line 7, character 15:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if(»$a == null«) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

and flows into this expression

File "refinement_equal.php", line 8, character 10 - line 8, character 11:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if($a == null) {
 8 |     $z = »$a«;
 9 |   } else {
10 |     $z = $c;

as the type of the local variable

which itself flows into this expression

File "refinement_equal.php", line 8, character 5 - line 8, character 6:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if($a == null) {
 8 |     »$z« = $a;
 9 |   } else {
10 |     $z = $c;

via an assignment

which I solved to this type variable

File "refinement_equal.php", line 7, character 6 - line 7, character 15:

 6 | function inter_equal(?A $a, C $c): C {
 7 |   if(»$a == null«) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

and flows into this expression

File "refinement_equal.php", line 12, character 10 - line 12, character 11:

 11 |   }
 12 |   return »$z«;
 13 | }

as the type of the local variable

which itself flows into this expression

File "refinement_equal.php", line 12, character 3 - line 12, character 12:

 11 |   }
 12 |   »return $z;«
 13 | }

because it is used in a return position

The supertype comes from this return hint

File "refinement_equal.php", line 6, character 36 - line 6, character 36:

 6 | function inter_equal(?A $a, C $c): »C« {
 7 |   if($a == null) {
 8 |     $z = $a;
 9 |   } else {
10 |     $z = $c;

1 error found
