error: Typing[4163] Invalid argument

 11 | function passes_optional_a_at_bool_alias(
 12 |   optional_a_at_bool $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

File "shape_subtyping_6.php", line 14, character 35 - line 14, character 36:

The field `a` is **optional**

 11 | function passes_optional_a_at_bool_alias(
 12 |   »optional_a_at_bool« $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

File "shape_subtyping_6.php", line 12, character 3 - line 12, character 20:

The field `a` is defined as **required**

 3 | type required_a_at_int = shape('a' => int);
 4 | type optional_a_at_bool = shape(?'a' => bool);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   »required_a_at_int« $s,
 8 | ): void {
 9 | }

File "shape_subtyping_6.php", line 7, character 3 - line 7, character 19:

`a` is defined here

 3 | type required_a_at_int = shape('a' => »int«);
 4 | type optional_a_at_bool = shape(?'a' => bool);

File "shape_subtyping_6.php", line 3, character 39 - line 3, character 41:

This error has 7 steps, a maximum depth of 2 and contains 1 reversal.

Here's why: this hint

 3 | type required_a_at_int = shape('a' => int);
 4 | type optional_a_at_bool = shape(?'a' => »bool«);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

File "shape_subtyping_6.php", line 4, character 41 - line 4, character 44:

flows up into this hint as the optional shape field `'a'`

 11 | function passes_optional_a_at_bool_alias(
 12 |   »optional_a_at_bool« $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

File "shape_subtyping_6.php", line 12, character 3 - line 12, character 20:

which itself flows into this expression because it is a parameter hint

 11 | function passes_optional_a_at_bool_alias(
 12 |   optional_a_at_bool »$s«,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

File "shape_subtyping_6.php", line 12, character 22 - line 12, character 23:

which itself flows into this expression because the local variable has this type

 11 | function passes_optional_a_at_bool_alias(
 12 |   optional_a_at_bool $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

File "shape_subtyping_6.php", line 14, character 35 - line 14, character 36:

which itself flows up into this expression as the 1st function parameter

 11 | function passes_optional_a_at_bool_alias(
 12 |   optional_a_at_bool $s,
 13 | ): void {
 14 |   »expects_required_a_at_int_alias($s)«;
 15 | }

File "shape_subtyping_6.php", line 14, character 3 - line 14, character 37:

which itself flows from this function or method  because they are required to be subtypes

 3 | type required_a_at_int = shape('a' => int);
 4 | type optional_a_at_bool = shape(?'a' => bool);
 5 | 
 6 | function »expects_required_a_at_int_alias«(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

File "shape_subtyping_6.php", line 6, character 10 - line 6, character 40:

which itself flows down into this hint as the 1st function parameter

 3 | type required_a_at_int = shape('a' => int);
 4 | type optional_a_at_bool = shape(?'a' => bool);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   »required_a_at_int« $s,
 8 | ): void {
 9 | }

File "shape_subtyping_6.php", line 7, character 3 - line 7, character 19:

which itself flows down into this hint as the required shape field `'a'`

 3 | type required_a_at_int = shape('a' => »int«);
 4 | type optional_a_at_bool = shape(?'a' => bool);

File "shape_subtyping_6.php", line 3, character 39 - line 3, character 41:

1 error found.
