error: Typing[4163] Invalid argument

File "shape_subtyping_3.php", line 11, character 29 - line 11, character 30:

  8 | function passes_optional_a_at_bool(
  9 |   shape(?'a' => bool) $s,
 10 | ): void {
 11 |   expects_required_a_at_int(»$s«);
 12 | }

The field `a` is **optional**

File "shape_subtyping_3.php", line 9, character 3 - line 9, character 21:

 8 | function passes_optional_a_at_bool(
 9 |   »shape(?'a' => bool)« $s,
10 | ): void {
11 |   expects_required_a_at_int($s);
12 | }

The field `a` is defined as **required**

File "shape_subtyping_3.php", line 4, character 3 - line 4, character 19:

 3 | function expects_required_a_at_int(
 4 |   »shape('a' => int)« $s,
 5 | ): void {
 6 | }

`a` is defined here

File "shape_subtyping_3.php", line 4, character 16 - line 4, character 18:

 3 | function expects_required_a_at_int(
 4 |   shape('a' => »int«) $s,
 5 | ): void {
 6 | }

Derivation:
{
  "Derivation":[
    {
      "Begin":{
        "sub":[
          {
            "Support_dynamic_type":[{"filename":"shape_subtyping_3.php","line":3,"char_start":10,"char_end":34}]
          }
        ],
        "super":[
          {
            "Witness":[{"filename":"shape_subtyping_3.php","line":11,"char_start":3,"char_end":31}]
          }
        ]
      }
    },
    {
      "Step":{
        "rule":{"Using_prj":{"Prj_symm_fn_param":[0,0]}},
        "on_":"Both",
        "sub":[
          {
            "Flow":{
              "from":[
                {
                  "Hint":[{"filename":"shape_subtyping_3.php","line":9,"char_start":3,"char_end":21}]
                }
              ],
              "kind":"Flow_param_hint",
              "into":[
                {
                  "Flow":{
                    "from":[
                      {
                        "Witness":[{"filename":"shape_subtyping_3.php","line":9,"char_start":23,"char_end":24}]
                      }
                    ],
                    "kind":"Flow_local",
                    "into":[
                      {
                        "Witness":[{"filename":"shape_subtyping_3.php","line":11,"char_start":29,"char_end":30}]
                      }
                    ]
                  }
                }
              ]
            }
          }
        ],
        "super":[
          {
            "Hint":[{"filename":"shape_subtyping_3.php","line":4,"char_start":3,"char_end":19}]
          }
        ]
      }
    },
    {
      "Step":{
        "rule":{"Using_prj":{" Prj_symm_shape":["a",{"Optional":[]},{"Required":[]}]}},
        "on_":"Both",
        "sub":[
          {
            "Hint":[{"filename":"shape_subtyping_3.php","line":9,"char_start":17,"char_end":20}]
          }
        ],
        "super":[
          {
            "Hint":[{"filename":"shape_subtyping_3.php","line":4,"char_start":16,"char_end":18}]
          }
        ]
      }
    }
  ]
}

File "", line 0, character 0 - line 0, character -1:


Reason:
{
  "Subtype":{
    "sub":[
      {
        "Prj_both":{
          "sub_prj":[
            {
              "Hint":[{"filename":"shape_subtyping_3.php","line":9,"char_start":17,"char_end":20}]
            }
          ],
          "prj":{" Prj_symm_shape":["a",{"Optional":[]},{"Required":[]}]},
          "sub":[
            {
              "Prj_both":{
                "sub_prj":[
                  {
                    "Flow":{
                      "from":[
                        {
                          "Hint":[{"filename":"shape_subtyping_3.php","line":9,"char_start":3,"char_end":21}]
                        }
                      ],
                      "kind":"Flow_param_hint",
                      "into":[
                        {
                          "Flow":{
                            "from":[
                              {
                                "Witness":[{"filename":"shape_subtyping_3.php","line":9,"char_start":23,"char_end":24}]
                              }
                            ],
                            "kind":"Flow_local",
                            "into":[
                              {
                                "Witness":[{"filename":"shape_subtyping_3.php","line":11,"char_start":29,"char_end":30}]
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ],
                "prj":{"Prj_symm_fn_param":[0,0]},
                "sub":[
                  {
                    "Support_dynamic_type":[{"filename":"shape_subtyping_3.php","line":3,"char_start":10,"char_end":34}]
                  }
                ],
                "super":[
                  {
                    "Witness":[{"filename":"shape_subtyping_3.php","line":11,"char_start":3,"char_end":31}]
                  }
                ]
              }
            }
          ],
          "super":[
            {
              "Hint":[{"filename":"shape_subtyping_3.php","line":4,"char_start":3,"char_end":19}]
            }
          ]
        }
      }
    ],
    "super":[
      {
        "Hint":[{"filename":"shape_subtyping_3.php","line":4,"char_start":16,"char_end":18}]
      }
    ]
  }
}

File "", line 0, character 0 - line 0, character -1:


1 error found
