error: Typing[4110] Invalid argument

 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

File "shape_subtyping_4.php", line 14, character 35 - line 14, character 36:

Expected `int`

 3 | type required_a_at_int = shape('a' => »int«);
 4 | type required_a_at_bool = shape('a' => bool);
 5 | 
 6 | function expects_required_a_at_int_alias(

File "shape_subtyping_4.php", line 3, character 39 - line 3, character 41:

But got `bool`

 3 | type required_a_at_int = shape('a' => int);
 4 | type required_a_at_bool = shape('a' => »bool«);
 5 | 
 6 | function expects_required_a_at_int_alias(

File "shape_subtyping_4.php", line 4, character 40 - line 4, character 43:

1 error found.
