error: Typing[4057] Invalid argument

 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

File "shape_subtyping_7.php", line 14, character 35 - line 14, character 36:

The field `b` is missing

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   »required_a_at_int« $s,
 8 | ): void {
 9 | }

File "shape_subtyping_7.php", line 7, character 3 - line 7, character 19:

The field `b` is defined

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape(»'b'« => int);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

File "shape_subtyping_7.php", line 4, character 24 - line 4, character 26:

error: Typing[4057] Invalid argument

 11 | function passes_missing_a_alias(
 12 |   missing_a $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

File "shape_subtyping_7.php", line 14, character 35 - line 14, character 36:

The field `a` is missing

 11 | function passes_missing_a_alias(
 12 |   »missing_a« $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

File "shape_subtyping_7.php", line 12, character 3 - line 12, character 11:

The field `a` is defined

 3 | type required_a_at_int = shape(»'a'« => int);
 4 | type missing_a = shape('b' => int);

File "shape_subtyping_7.php", line 3, character 32 - line 3, character 34:

2 errors found.
