error: Typing[4057] Invalid argument

File shape_subtyping_7.php, line 14, character 35 - line 14, character 36:

 11 | function passes_missing_a_alias(
 12 |   missing_a $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

The field b is missing

File shape_subtyping_7.php, line 7, character 3 - line 7, character 19:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   »required_a_at_int« $s,
 8 | ): void {
 9 | }

The field b is defined

File shape_subtyping_7.php, line 4, character 24 - line 4, character 26:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape(»'b'« => int);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

Here's why:


  Step 1 of 3                                                                   

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File shape_subtyping_7.php, line 6, character 10 - line 6, character 40:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function »expects_required_a_at_int_alias«(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

The supertype comes from this expression

File shape_subtyping_7.php, line 14, character 3 - line 14, character 37:

 11 | function passes_missing_a_alias(
 12 |   missing_a $s,
 13 | ): void {
 14 |   »expects_required_a_at_int_alias($s)«;
 15 | }


  Step 2 of 3                                                                   

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File shape_subtyping_7.php, line 12, character 3 - line 12, character 11:

 11 | function passes_missing_a_alias(
 12 |   »missing_a« $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

which is defined here

File shape_subtyping_7.php, line 4, character 18 - line 4, character 34:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = »shape('b' => int)«;
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

and flows into this expression

File shape_subtyping_7.php, line 12, character 13 - line 12, character 14:

 11 | function passes_missing_a_alias(
 12 |   missing_a »$s«,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

as the parameter hint

which itself flows into this expression

File shape_subtyping_7.php, line 14, character 35 - line 14, character 36:

 11 | function passes_missing_a_alias(
 12 |   missing_a $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

as the type of the local variable

The supertype comes from this hint

File shape_subtyping_7.php, line 7, character 3 - line 7, character 19:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   »required_a_at_int« $s,
 8 | ): void {
 9 | }

which is defined here

File shape_subtyping_7.php, line 3, character 26 - line 3, character 42:

 1 | <?hh
 2 | 
 3 | type required_a_at_int = »shape('a' => int)«;
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(


  Step 3 of 3                                 (here is where the error occurred) 

These are shape types so next I tried to check the b field.
The field is required in the subtype but missing in the supertype.

The subtype comes from this hint

File shape_subtyping_7.php, line 4, character 31 - line 4, character 33:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape('b' => »int«);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

The supertype didn't exist because the field was missing.
error: Typing[4057] Invalid argument

File shape_subtyping_7.php, line 14, character 35 - line 14, character 36:

 11 | function passes_missing_a_alias(
 12 |   missing_a $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

The field a is missing

File shape_subtyping_7.php, line 12, character 3 - line 12, character 11:

 11 | function passes_missing_a_alias(
 12 |   »missing_a« $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

The field a is defined

File shape_subtyping_7.php, line 3, character 32 - line 3, character 34:

 1 | <?hh
 2 | 
 3 | type required_a_at_int = shape(»'a'« => int);
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(

Here's why:


  Step 1 of 3                                                                   

I started by checking this subtype relationship.

The subtype comes from this function or method declaration

File shape_subtyping_7.php, line 6, character 10 - line 6, character 40:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function »expects_required_a_at_int_alias«(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

The supertype comes from this expression

File shape_subtyping_7.php, line 14, character 3 - line 14, character 37:

 11 | function passes_missing_a_alias(
 12 |   missing_a $s,
 13 | ): void {
 14 |   »expects_required_a_at_int_alias($s)«;
 15 | }


  Step 2 of 3                                                                   

These are function types so next I checked the 1st function parameters.
Functions are contravariant in their parameters so the direction of the subtype relationship is reversed.

The subtype comes from this hint

File shape_subtyping_7.php, line 12, character 3 - line 12, character 11:

 11 | function passes_missing_a_alias(
 12 |   »missing_a« $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

which is defined here

File shape_subtyping_7.php, line 4, character 18 - line 4, character 34:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = »shape('b' => int)«;
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   required_a_at_int $s,
 8 | ): void {
 9 | }

and flows into this expression

File shape_subtyping_7.php, line 12, character 13 - line 12, character 14:

 11 | function passes_missing_a_alias(
 12 |   missing_a »$s«,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

as the parameter hint

which itself flows into this expression

File shape_subtyping_7.php, line 14, character 35 - line 14, character 36:

 11 | function passes_missing_a_alias(
 12 |   missing_a $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

as the type of the local variable

The supertype comes from this hint

File shape_subtyping_7.php, line 7, character 3 - line 7, character 19:

 3 | type required_a_at_int = shape('a' => int);
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 |   »required_a_at_int« $s,
 8 | ): void {
 9 | }

which is defined here

File shape_subtyping_7.php, line 3, character 26 - line 3, character 42:

 1 | <?hh
 2 | 
 3 | type required_a_at_int = »shape('a' => int)«;
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(


  Step 3 of 3                                 (here is where the error occurred) 

These are shape types so next I tried to check the a field.
The field is required in the supertype but missing in the subtype.

The subtype didn't exist because the field was missing.
The supertype comes from this hint

File shape_subtyping_7.php, line 3, character 39 - line 3, character 41:

 1 | <?hh
 2 | 
 3 | type required_a_at_int = shape('a' => »int«);
 4 | type missing_a = shape('b' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(

