error: Typing[4163] Invalid argument

 11 | function passes_optional_a_at_int_alias(
 12 |   optional_a_at_int $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

File "shape_subtyping_5.php", line 14, character 35 - line 14, character 36:

The field `a` is **optional**

 11 | function passes_optional_a_at_int_alias(
 12 |   »optional_a_at_int« $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

File "shape_subtyping_5.php", line 12, character 3 - line 12, character 19:

The field `a` is defined as **required**

 3 | type required_a_at_int = shape('a' => int);
 4 | type optional_a_at_int = shape(?'a' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 | »required_a_at_int« $s,
 8 | ): void {
 9 | }

File "shape_subtyping_5.php", line 7, character 1 - line 7, character 17:

`a` is defined here

 3 | type required_a_at_int = shape('a' => »int«);
 4 | type optional_a_at_int = shape(?'a' => int);

File "shape_subtyping_5.php", line 3, character 39 - line 3, character 41:

This error has 7 steps, a maximum depth of 2 and contains 1 reversal.

Here's why: this hint

 3 | type required_a_at_int = shape('a' => int);
 4 | type optional_a_at_int = shape(?'a' => »int«);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 | required_a_at_int $s,
 8 | ): void {
 9 | }

File "shape_subtyping_5.php", line 4, character 40 - line 4, character 42:

flows up into this hint as the optional shape field `'a'`

 11 | function passes_optional_a_at_int_alias(
 12 |   »optional_a_at_int« $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

File "shape_subtyping_5.php", line 12, character 3 - line 12, character 19:

which itself flows into this expression because it is a parameter hint

 11 | function passes_optional_a_at_int_alias(
 12 |   optional_a_at_int »$s«,
 13 | ): void {
 14 |   expects_required_a_at_int_alias($s);
 15 | }

File "shape_subtyping_5.php", line 12, character 21 - line 12, character 22:

which itself flows into this expression because the local variable has this type

 11 | function passes_optional_a_at_int_alias(
 12 |   optional_a_at_int $s,
 13 | ): void {
 14 |   expects_required_a_at_int_alias(»$s«);
 15 | }

File "shape_subtyping_5.php", line 14, character 35 - line 14, character 36:

which itself flows up into this expression as the 1st function parameter

 11 | function passes_optional_a_at_int_alias(
 12 |   optional_a_at_int $s,
 13 | ): void {
 14 |   »expects_required_a_at_int_alias($s)«;
 15 | }

File "shape_subtyping_5.php", line 14, character 3 - line 14, character 37:

which itself flows from this function or method  because they are required to be subtypes

 3 | type required_a_at_int = shape('a' => int);
 4 | type optional_a_at_int = shape(?'a' => int);
 5 | 
 6 | function »expects_required_a_at_int_alias«(
 7 | required_a_at_int $s,
 8 | ): void {
 9 | }

File "shape_subtyping_5.php", line 6, character 10 - line 6, character 40:

which itself flows down into this hint as the 1st function parameter

 3 | type required_a_at_int = shape('a' => int);
 4 | type optional_a_at_int = shape(?'a' => int);
 5 | 
 6 | function expects_required_a_at_int_alias(
 7 | »required_a_at_int« $s,
 8 | ): void {
 9 | }

File "shape_subtyping_5.php", line 7, character 1 - line 7, character 17:

which itself flows down into this hint as the required shape field `'a'`

 3 | type required_a_at_int = shape('a' => »int«);
 4 | type optional_a_at_int = shape(?'a' => int);

File "shape_subtyping_5.php", line 3, character 39 - line 3, character 41:

Raw:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"shape_subtyping_5.php","line":4,"char_start":40,"char_end":42}]
        },
        "Flow_prj",
        {
          "Rprj":[
            {"Symm":[{" Prj_symm_shape":["a",{"Optional":[]},{"Required":[]}]}]},
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rflow":[
                        {
                          "Rflow":[
                            {
                              "Rdef":[
                                {"filename":"shape_subtyping_5.php","line":4,"char_start":6,"char_end":22},
                                {
                                  "Rhint":[{"filename":"shape_subtyping_5.php","line":12,"char_start":3,"char_end":19}]
                                }
                              ]
                            },
                            "Flow_param_hint",
                            {
                              "Rwitness":[{"filename":"shape_subtyping_5.php","line":12,"char_start":21,"char_end":22}]
                            }
                          ]
                        },
                        "Flow_local",
                        {
                          "Rwitness":[{"filename":"shape_subtyping_5.php","line":14,"char_start":35,"char_end":36}]
                        }
                      ]
                    },
                    "Flow_prj",
                    {
                      "Rprj":[
                        {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                        {
                          "Rflow":[
                            {
                              "Rwitness":[{"filename":"shape_subtyping_5.php","line":14,"char_start":3,"char_end":37}]
                            },
                            "Flow_subtype",
                            {
                              "Rrev":[
                                {
                                  "Rsupport_dynamic_type":[{"filename":"shape_subtyping_5.php","line":6,"char_start":10,"char_end":40}]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                "Flow_subtype",
                {
                  "Rdef":[
                    {"filename":"shape_subtyping_5.php","line":3,"char_start":6,"char_end":22},
                    {
                      "Rhint":[{"filename":"shape_subtyping_5.php","line":7,"char_start":1,"char_end":17}]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "Rhint":[{"filename":"shape_subtyping_5.php","line":3,"char_start":39,"char_end":41}]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Normalised:
{
  "Rflow":[
    {
      "Rflow":[
        {
          "Rhint":[{"filename":"shape_subtyping_5.php","line":4,"char_start":40,"char_end":42}]
        },
        "Flow_prj",
        {
          "Rprj":[
            {"Symm":[{" Prj_symm_shape":["a",{"Optional":[]},{"Required":[]}]}]},
            {
              "Rflow":[
                {
                  "Rflow":[
                    {
                      "Rflow":[
                        {
                          "Rflow":[
                            {
                              "Rdef":[
                                {"filename":"shape_subtyping_5.php","line":4,"char_start":6,"char_end":22},
                                {
                                  "Rhint":[{"filename":"shape_subtyping_5.php","line":12,"char_start":3,"char_end":19}]
                                }
                              ]
                            },
                            "Flow_param_hint",
                            {
                              "Rwitness":[{"filename":"shape_subtyping_5.php","line":12,"char_start":21,"char_end":22}]
                            }
                          ]
                        },
                        "Flow_local",
                        {
                          "Rwitness":[{"filename":"shape_subtyping_5.php","line":14,"char_start":35,"char_end":36}]
                        }
                      ]
                    },
                    "Flow_prj",
                    {
                      "Rprj":[
                        {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
                        {
                          "Rflow":[
                            {
                              "Rwitness":[{"filename":"shape_subtyping_5.php","line":14,"char_start":3,"char_end":37}]
                            },
                            "Flow_subtype",
                            {
                              "Rsupport_dynamic_type":[{"filename":"shape_subtyping_5.php","line":6,"char_start":10,"char_end":40}]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                "Flow_subtype",
                {
                  "Rdef":[
                    {"filename":"shape_subtyping_5.php","line":3,"char_start":6,"char_end":22},
                    {
                      "Rhint":[{"filename":"shape_subtyping_5.php","line":7,"char_start":1,"char_end":17}]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    "Flow_subtype_toplevel",
    {
      "Rhint":[{"filename":"shape_subtyping_5.php","line":3,"char_start":39,"char_end":41}]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

Path:
{
  "stats":{"max_depth":2,"length":7,"reversals":1},
  "path_elems":[
    {
      "Rhint":[{"filename":"shape_subtyping_5.php","line":4,"char_start":40,"char_end":42}]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_prj",
        "in_to":{"Symm":[{" Prj_symm_shape":["a",{"Optional":[]},{"Required":[]}]}]}
      }
    },
    {
      "Rdef":[
        {"filename":"shape_subtyping_5.php","line":4,"char_start":6,"char_end":22},
        {
          "Rhint":[{"filename":"shape_subtyping_5.php","line":12,"char_start":3,"char_end":19}]
        }
      ]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_param_hint"}},
    {
      "Rwitness":[{"filename":"shape_subtyping_5.php","line":12,"char_start":21,"char_end":22}]
    },
    {"Edge":{"dir":"Fwd","kind":"Flow_local"}},
    {
      "Rwitness":[{"filename":"shape_subtyping_5.php","line":14,"char_start":35,"char_end":36}]
    },
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    {
      "Rwitness":[{"filename":"shape_subtyping_5.php","line":14,"char_start":3,"char_end":37}]
    },
    {"Edge":{"dir":"Bwd","kind":"Flow_subtype"}},
    {
      "Rsupport_dynamic_type":[{"filename":"shape_subtyping_5.php","line":6,"char_start":10,"char_end":40}]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype",
        "out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}
      }
    },
    {
      "Rdef":[
        {"filename":"shape_subtyping_5.php","line":3,"char_start":6,"char_end":22},
        {
          "Rhint":[{"filename":"shape_subtyping_5.php","line":7,"char_start":1,"char_end":17}]
        }
      ]
    },
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype_toplevel",
        "out_of":{"Symm":[{" Prj_symm_shape":["a",{"Optional":[]},{"Required":[]}]}]}
      }
    },
    {
      "Rhint":[{"filename":"shape_subtyping_5.php","line":3,"char_start":39,"char_end":41}]
    }
  ]
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
