error: Typing[4110] Invalid return type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

Expected `C`

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

But got `A`

 6 | function union_l((»A« | B) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 19 - line 6, character 19:

This error has 5 steps, a maximum depth of 1 and contains 0 reversals.

Here's why: this hint

 6 | function union_l((»A« | B) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 19 - line 6, character 19:

flows up into this hint as an element of the union type

 6 | function union_l(»(A | B)« $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 18 - line 6, character 24:

which itself flows into this expression because it is a parameter hint

 6 | function union_l((A | B) »$ab«): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 26 - line 6, character 28:

which itself flows into this expression because the local variable has this type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

which itself flows into this expression because the expression is in return position

 6 | function union_l((A | B) $ab): C {
 7 |   »return $ab;«
 8 | }

File "union_subtyping_l.php", line 7, character 3 - line 7, character 13:

which itself flows into this hint because they are required to be subtypes

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

Raw:
[
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":2,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":19,"char_end":19}]
        }
      ]
    ]
  },
  "Flow_prj",
  {
    "Prj":[
      {"Asymm":["Sub","Prj_asymm_union"]},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
        },
        "Flow_param_hint",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
        },
        "Flow_local",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
        },
        "Flow_return_expr",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
        }
      ]
    ]
  },
  "Flow_subtype_toplevel",
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
        }
      ]
    ]
  }
]


File "", line 0, character 0 - line 0, character -1:

Normalised:
[
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":2,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":19,"char_end":19}]
        }
      ]
    ]
  },
  "Flow_prj",
  {
    "Prj":[
      {"Asymm":["Sub","Prj_asymm_union"]},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
        },
        "Flow_param_hint",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
        },
        "Flow_local",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
        },
        "Flow_return_expr",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
        }
      ]
    ]
  },
  "Flow_subtype_toplevel",
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
        }
      ]
    ]
  }
]


File "", line 0, character 0 - line 0, character -1:

Path:
{
  "stats":{"max_depth":1,"length":5,"reversals":0},
  "path_elems":[
    [
      {
        "Def":[
          {"filename":"union_subtyping_l.php","line":2,"char_start":7,"char_end":7},
          [
            {
              "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":19,"char_end":19}]
            }
          ]
        ]
      }
    ],
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Asymm":["Sub","Prj_asymm_union"]}}
    },
    [
      {
        "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
      }
    ],
    {"Edge":{"dir":"Fwd","kind":"Flow_param_hint"}},
    [
      {
        "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
      }
    ],
    {"Edge":{"dir":"Fwd","kind":"Flow_local"}},
    [
      {
        "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
      }
    ],
    {"Edge":{"dir":"Fwd","kind":"Flow_return_expr"}},
    [
      {
        "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
      }
    ],
    {"Edge":{"dir":"Fwd","kind":"Flow_subtype_toplevel"}},
    [
      {
        "Def":[
          {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
          [
            {
              "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
            }
          ]
        ]
      }
    ]
  ]
}


File "", line 0, character 0 - line 0, character -1:

error: Typing[4110] Invalid return type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

Expected `C`

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

But got `B`

 6 | function union_l((A | »B«) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 23 - line 6, character 23:

This error has 5 steps, a maximum depth of 1 and contains 0 reversals.

Here's why: this hint

 6 | function union_l((A | »B«) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 23 - line 6, character 23:

flows up into this hint as an element of the union type

 6 | function union_l(»(A | B)« $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 18 - line 6, character 24:

which itself flows into this expression because it is a parameter hint

 6 | function union_l((A | B) »$ab«): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 26 - line 6, character 28:

which itself flows into this expression because the local variable has this type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

which itself flows into this expression because the expression is in return position

 6 | function union_l((A | B) $ab): C {
 7 |   »return $ab;«
 8 | }

File "union_subtyping_l.php", line 7, character 3 - line 7, character 13:

which itself flows into this hint because they are required to be subtypes

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

Raw:
[
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":3,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":23,"char_end":23}]
        }
      ]
    ]
  },
  "Flow_prj",
  {
    "Prj":[
      {"Asymm":["Sub","Prj_asymm_union"]},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
        },
        "Flow_param_hint",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
        },
        "Flow_local",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
        },
        "Flow_return_expr",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
        }
      ]
    ]
  },
  "Flow_subtype_toplevel",
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
        }
      ]
    ]
  }
]


File "", line 0, character 0 - line 0, character -1:

Normalised:
[
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":3,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":23,"char_end":23}]
        }
      ]
    ]
  },
  "Flow_prj",
  {
    "Prj":[
      {"Asymm":["Sub","Prj_asymm_union"]},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
        },
        "Flow_param_hint",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
        },
        "Flow_local",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
        },
        "Flow_return_expr",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
        }
      ]
    ]
  },
  "Flow_subtype_toplevel",
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
        }
      ]
    ]
  }
]


File "", line 0, character 0 - line 0, character -1:

Path:
{
  "stats":{"max_depth":1,"length":5,"reversals":0},
  "path_elems":[
    [
      {
        "Def":[
          {"filename":"union_subtyping_l.php","line":3,"char_start":7,"char_end":7},
          [
            {
              "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":23,"char_end":23}]
            }
          ]
        ]
      }
    ],
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Asymm":["Sub","Prj_asymm_union"]}}
    },
    [
      {
        "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
      }
    ],
    {"Edge":{"dir":"Fwd","kind":"Flow_param_hint"}},
    [
      {
        "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
      }
    ],
    {"Edge":{"dir":"Fwd","kind":"Flow_local"}},
    [
      {
        "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
      }
    ],
    {"Edge":{"dir":"Fwd","kind":"Flow_return_expr"}},
    [
      {
        "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
      }
    ],
    {"Edge":{"dir":"Fwd","kind":"Flow_subtype_toplevel"}},
    [
      {
        "Def":[
          {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
          [
            {
              "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
            }
          ]
        ]
      }
    ]
  ]
}


File "", line 0, character 0 - line 0, character -1:

2 errors found.
