error: Typing[4110] Invalid return type

File "union_subtyping_r.php", line 7, character 10 - line 7, character 11:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (A|B) {
 7 |   return »$c«;
 8 | }

Expected `(A | B)`

File "union_subtyping_r.php", line 6, character 25 - line 6, character 29:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): »(A|B)« {
 7 |   return $c;
 8 | }

But got `C`

File "union_subtyping_r.php", line 6, character 18 - line 6, character 18:

 5 | <<__NoAutoLikes>>
 6 | function union_r(»C« $c): (A|B) {
 7 |   return $c;
 8 | }

Here's why:

Step 1 of 1 (here is where the error occurred)

I started by checking this subtype relationship.

The subtype comes from this hint

File "union_subtyping_r.php", line 6, character 18 - line 6, character 18:

 5 | <<__NoAutoLikes>>
 6 | function union_r(»C« $c): (A|B) {
 7 |   return $c;
 8 | }

and flows into this expression as the parameter hint

File "union_subtyping_r.php", line 7, character 3 - line 7, character 12:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (A|B) {
 7 |   »return $c;«
 8 | }

The supertype comes from this hint

File "union_subtyping_r.php", line 6, character 25 - line 6, character 29:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): »(A|B)« {
 7 |   return $c;
 8 | }

error: Typing[4110] Invalid return type

File "union_subtyping_r.php", line 7, character 10 - line 7, character 11:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (A|B) {
 7 |   return »$c«;
 8 | }

Expected `A`

File "union_subtyping_r.php", line 6, character 26 - line 6, character 26:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (»A«|B) {
 7 |   return $c;
 8 | }

But got `C`

File "union_subtyping_r.php", line 6, character 18 - line 6, character 18:

 5 | <<__NoAutoLikes>>
 6 | function union_r(»C« $c): (A|B) {
 7 |   return $c;
 8 | }

Here's why:

Step 1 of 2

I started by checking this subtype relationship.

The subtype comes from this hint

File "union_subtyping_r.php", line 6, character 18 - line 6, character 18:

 5 | <<__NoAutoLikes>>
 6 | function union_r(»C« $c): (A|B) {
 7 |   return $c;
 8 | }

and flows into this expression as the parameter hint

File "union_subtyping_r.php", line 7, character 3 - line 7, character 12:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (A|B) {
 7 |   »return $c;«
 8 | }

The supertype comes from this hint

File "union_subtyping_r.php", line 6, character 25 - line 6, character 29:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): »(A|B)« {
 7 |   return $c;
 8 | }

Step 2 of 2 (here is where the error occurred)

The supertype is a union type so next I checked at least one element.

The subtype is the same as before.

File "union_subtyping_r.php", line 6, character 18 - line 6, character 18:

 5 | <<__NoAutoLikes>>
 6 | function union_r(»C« $c): (A|B) {
 7 |   return $c;
 8 | }

The supertype comes from this hint

File "union_subtyping_r.php", line 6, character 26 - line 6, character 26:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (»A«|B) {
 7 |   return $c;
 8 | }

error: Typing[4110] Invalid return type

File "union_subtyping_r.php", line 7, character 10 - line 7, character 11:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (A|B) {
 7 |   return »$c«;
 8 | }

Expected `B`

File "union_subtyping_r.php", line 6, character 28 - line 6, character 28:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (A|»B«) {
 7 |   return $c;
 8 | }

But got `C`

File "union_subtyping_r.php", line 6, character 18 - line 6, character 18:

 5 | <<__NoAutoLikes>>
 6 | function union_r(»C« $c): (A|B) {
 7 |   return $c;
 8 | }

Here's why:

Step 1 of 2

I started by checking this subtype relationship.

The subtype comes from this hint

File "union_subtyping_r.php", line 6, character 18 - line 6, character 18:

 5 | <<__NoAutoLikes>>
 6 | function union_r(»C« $c): (A|B) {
 7 |   return $c;
 8 | }

and flows into this expression as the parameter hint

File "union_subtyping_r.php", line 7, character 3 - line 7, character 12:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (A|B) {
 7 |   »return $c;«
 8 | }

The supertype comes from this hint

File "union_subtyping_r.php", line 6, character 25 - line 6, character 29:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): »(A|B)« {
 7 |   return $c;
 8 | }

Step 2 of 2 (here is where the error occurred)

The supertype is a union type so next I checked at least one element.

The subtype is the same as before.

File "union_subtyping_r.php", line 6, character 18 - line 6, character 18:

 5 | <<__NoAutoLikes>>
 6 | function union_r(»C« $c): (A|B) {
 7 |   return $c;
 8 | }

The supertype comes from this hint

File "union_subtyping_r.php", line 6, character 28 - line 6, character 28:

 5 | <<__NoAutoLikes>>
 6 | function union_r(C $c): (A|»B«) {
 7 |   return $c;
 8 | }

3 errors found
