error: Typing[4110] Invalid return type

Expected `A`

10 | function foo(bool  $p, A $x, B $y): »A« {
11 |   if($p){
12 |     $z = $x;

File "union_subtyping.php", line 10, character 37 - line 10, character 37:

But got `B`

10 | function foo(bool  $p, A $x, »B« $y): A {
11 |   if($p){
12 |     $z = $x;

File "union_subtyping.php", line 10, character 30 - line 10, character 30:

Here's why: this hint

10 | function foo(bool  $p, A $x, »B« $y): A {
11 |   if($p){
12 |     $z = $x;

File "union_subtyping.php", line 10, character 30 - line 10, character 30:

flows *into* this expression

10 | function foo(bool  $p, A $x, B »$y«): A {
11 |   if($p){
12 |     $z = $x;

File "union_subtyping.php", line 10, character 32 - line 10, character 33:

which itself flows *into* this expression

 13 |   } else{
 14 |     $z = »$y«;
 15 |   }
 16 | 
 17 |   return $z;
 18 | }

File "union_subtyping.php", line 14, character 10 - line 14, character 11:

which itself flows *into* this expression

 13 |   } else{
 14 |     »$z« = $y;
 15 |   }
 16 | 
 17 |   return $z;
 18 | }

File "union_subtyping.php", line 14, character 5 - line 14, character 6:

which itself flows *into* this expression, via the union type

 10 | function foo(bool  $p, A $x, B $y): A {
 11 |   »if($p){
 12 |     $z = $x;
 13 |   } else{
 14 |     $z = $y;
 15 |   }«
 16 | 
 17 |   return $z;

File "union_subtyping.php", line 11, character 3 - line 15, character 3:

which itself flows *into* this expression

 13 |   } else{
 14 |     $z = $y;
 15 |   }
 16 | 
 17 |   return »$z«;
 18 | }

File "union_subtyping.php", line 17, character 10 - line 17, character 11:

which itself flows *into* this expression

 13 |   } else{
 14 |     $z = $y;
 15 |   }
 16 | 
 17 |   »return $z;«
 18 | }

File "union_subtyping.php", line 17, character 3 - line 17, character 12:

which itself flows *into* this hint

10 | function foo(bool  $p, A $x, B $y): »A« {
11 |   if($p){
12 |     $z = $x;

File "union_subtyping.php", line 10, character 37 - line 10, character 37:

error: Typing[4110] Invalid return type

Expected `C`

 21 | function union_l((A | B) $ab): »C« {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 32 - line 21, character 32:

But got `A`

 21 | function union_l((»A« | B) $ab): C {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 19 - line 21, character 19:

Here's why: this hint

 21 | function union_l((»A« | B) $ab): C {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 19 - line 21, character 19:

flows *into* this hint, via the union type

 21 | function union_l(»(A | B)« $ab): C {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 18 - line 21, character 24:

which itself flows *into* this expression

 21 | function union_l((A | B) »$ab«): C {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 26 - line 21, character 28:

which itself flows *into* this expression

 21 | function union_l((A | B) $ab): C {
 22 |   return »$ab«;
 23 | }

File "union_subtyping.php", line 22, character 10 - line 22, character 12:

which itself flows *into* this expression

 21 | function union_l((A | B) $ab): C {
 22 |   »return $ab;«
 23 | }

File "union_subtyping.php", line 22, character 3 - line 22, character 13:

which itself flows *into* this hint

 21 | function union_l((A | B) $ab): »C« {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 32 - line 21, character 32:

error: Typing[4110] Invalid return type

Expected `C`

 21 | function union_l((A | B) $ab): »C« {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 32 - line 21, character 32:

But got `B`

 21 | function union_l((A | »B«) $ab): C {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 23 - line 21, character 23:

Here's why: this hint

 21 | function union_l((A | »B«) $ab): C {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 23 - line 21, character 23:

flows *into* this hint, via the union type

 21 | function union_l(»(A | B)« $ab): C {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 18 - line 21, character 24:

which itself flows *into* this expression

 21 | function union_l((A | B) »$ab«): C {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 26 - line 21, character 28:

which itself flows *into* this expression

 21 | function union_l((A | B) $ab): C {
 22 |   return »$ab«;
 23 | }

File "union_subtyping.php", line 22, character 10 - line 22, character 12:

which itself flows *into* this expression

 21 | function union_l((A | B) $ab): C {
 22 |   »return $ab;«
 23 | }

File "union_subtyping.php", line 22, character 3 - line 22, character 13:

which itself flows *into* this hint

 21 | function union_l((A | B) $ab): »C« {
 22 |   return $ab;
 23 | }

File "union_subtyping.php", line 21, character 32 - line 21, character 32:

error: Typing[4110] Invalid return type

Expected `B`

 25 | function union_r(C $c): (A|»B«) {
 26 |   return $c;
 27 | }

File "union_subtyping.php", line 25, character 28 - line 25, character 28:

But got `C`

 25 | function union_r(»C« $c): (A|B) {
 26 |   return $c;
 27 | }

File "union_subtyping.php", line 25, character 18 - line 25, character 18:

Here's why: this hint

 25 | function union_r(»C« $c): (A|B) {
 26 |   return $c;
 27 | }

File "union_subtyping.php", line 25, character 18 - line 25, character 18:

flows *into* this expression

 25 | function union_r(C »$c«): (A|B) {
 26 |   return $c;
 27 | }

File "union_subtyping.php", line 25, character 20 - line 25, character 21:

which itself flows *into* this expression

 25 | function union_r(C $c): (A|B) {
 26 |   return »$c«;
 27 | }

File "union_subtyping.php", line 26, character 10 - line 26, character 11:

which itself flows *into* this expression

 25 | function union_r(C $c): (A|B) {
 26 |   »return $c;«
 27 | }

File "union_subtyping.php", line 26, character 3 - line 26, character 12:

which itself flows *into* this hint

 25 | function union_r(C $c): »(A|B)« {
 26 |   return $c;
 27 | }

File "union_subtyping.php", line 25, character 25 - line 25, character 29:

which itself flows *into* this hint, via the union type

 25 | function union_r(C $c): (A|»B«) {
 26 |   return $c;
 27 | }

File "union_subtyping.php", line 25, character 28 - line 25, character 28:

4 errors found.
