error: Typing[4110] Invalid return type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

Expected `C`

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

But got `A`

 6 | function union_l((»A« | B) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 19 - line 6, character 19:

This error has 5 steps, a maximum depth of 1 and contains 0 reversals.

Here's why: this hint

 6 | function union_l((»A« | B) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 19 - line 6, character 19:

flows up into this hint as an element of the union type

 6 | function union_l(»(A | B)« $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 18 - line 6, character 24:

which itself flows into this expression because it is a parameter hint

 6 | function union_l((A | B) »$ab«): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 26 - line 6, character 28:

which itself flows into this expression because the local variable has this type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

which itself flows into this expression because the expression is in return position

 6 | function union_l((A | B) $ab): C {
 7 |   »return $ab;«
 8 | }

File "union_subtyping_l.php", line 7, character 3 - line 7, character 13:

which itself flows into this hint because they are required to be subtypes

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

error: Typing[4110] Invalid return type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

Expected `C`

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

But got `B`

 6 | function union_l((A | »B«) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 23 - line 6, character 23:

This error has 5 steps, a maximum depth of 1 and contains 0 reversals.

Here's why: this hint

 6 | function union_l((A | »B«) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 23 - line 6, character 23:

flows up into this hint as an element of the union type

 6 | function union_l(»(A | B)« $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 18 - line 6, character 24:

which itself flows into this expression because it is a parameter hint

 6 | function union_l((A | B) »$ab«): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 26 - line 6, character 28:

which itself flows into this expression because the local variable has this type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

which itself flows into this expression because the expression is in return position

 6 | function union_l((A | B) $ab): C {
 7 |   »return $ab;«
 8 | }

File "union_subtyping_l.php", line 7, character 3 - line 7, character 13:

which itself flows into this hint because they are required to be subtypes

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

2 errors found.
