error: Typing[4110] Invalid return type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

Expected `C`

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

But got `A`

 6 | function union_l((»A« | B) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 19 - line 6, character 19:

Reason:
[
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":2,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":19,"char_end":19}]
        }
      ]
    ]
  },
  "Flow_prj",
  {
    "Prj":[
      {"Asymm":["Sub","Prj_asymm_union"]},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
        },
        "Flow_param_hint",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
        },
        "Flow_local",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
        },
        "Flow_return_expr",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
        }
      ]
    ]
  },
  "Flow_subtype_toplevel",
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
        }
      ]
    ]
  }
]


File "", line 0, character 0 - line 0, character -1:

error: Typing[4110] Invalid return type

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

Expected `C`

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

But got `B`

 6 | function union_l((A | »B«) $ab): C {
 7 |   return $ab;
 8 | }

File "union_subtyping_l.php", line 6, character 23 - line 6, character 23:

Reason:
[
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":3,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":23,"char_end":23}]
        }
      ]
    ]
  },
  "Flow_prj",
  {
    "Prj":[
      {"Asymm":["Sub","Prj_asymm_union"]},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
        },
        "Flow_param_hint",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
        },
        "Flow_local",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
        },
        "Flow_return_expr",
        {
          "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
        }
      ]
    ]
  },
  "Flow_subtype_toplevel",
  {
    "Def":[
      {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
      [
        {
          "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
        }
      ]
    ]
  }
]


File "", line 0, character 0 - line 0, character -1:

2 errors found.
