error: Typing[4110] Invalid return type

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

Expected `C`

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

But got `A`

File "union_subtyping_l.php", line 6, character 19 - line 6, character 19:

 6 | function union_l((»A« | B) $ab): C {
 7 |   return $ab;
 8 | }

Derivation:
{
  "Derivation":[
    {
      "Begin":{
        "sub":[
          {
            "Flow":{
              "from":[
                {
                  "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
                }
              ],
              "kind":"Flow_param_hint",
              "into":[
                {
                  "Flow":{
                    "from":[
                      {
                        "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
                      }
                    ],
                    "kind":"Flow_local",
                    "into":[
                      {
                        "Flow":{
                          "from":[
                            {
                              "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
                            }
                          ],
                          "kind":"Flow_return_expr",
                          "into":[
                            {
                              "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ],
        "super":[
          {
            "Def":[
              {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
              [
                {
                  "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
                }
              ]
            ]
          }
        ]
      }
    },
    {
      "Step":{
        "rule":{"Using_prj_sub":"Prj_asymm_union"},
        "on_":"Subtype",
        "sub":[
          {
            "Def":[
              {"filename":"union_subtyping_l.php","line":2,"char_start":7,"char_end":7},
              [
                {
                  "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":19,"char_end":19}]
                }
              ]
            ]
          }
        ],
        "super":[
          {
            "Def":[
              {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
              [
                {
                  "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
                }
              ]
            ]
          }
        ]
      }
    }
  ]
}

File "", line 0, character 0 - line 0, character -1:


Reason:
{
  "Subtype":{
    "sub":[
      {
        "Prj_one":{
          "part":[
            {
              "Def":[
                {"filename":"union_subtyping_l.php","line":2,"char_start":7,"char_end":7},
                [
                  {
                    "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":19,"char_end":19}]
                  }
                ]
              ]
            }
          ],
          "prj":"Prj_asymm_union",
          "whole":[
            {
              "Flow":{
                "from":[
                  {
                    "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
                  }
                ],
                "kind":"Flow_param_hint",
                "into":[
                  {
                    "Flow":{
                      "from":[
                        {
                          "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
                        }
                      ],
                      "kind":"Flow_local",
                      "into":[
                        {
                          "Flow":{
                            "from":[
                              {
                                "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
                              }
                            ],
                            "kind":"Flow_return_expr",
                            "into":[
                              {
                                "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    ],
    "super":[
      {
        "Def":[
          {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
          [
            {
              "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
            }
          ]
        ]
      }
    ]
  }
}

File "", line 0, character 0 - line 0, character -1:


error: Typing[4110] Invalid return type

File "union_subtyping_l.php", line 7, character 10 - line 7, character 12:

 6 | function union_l((A | B) $ab): C {
 7 |   return »$ab«;
 8 | }

Expected `C`

File "union_subtyping_l.php", line 6, character 32 - line 6, character 32:

 6 | function union_l((A | B) $ab): »C« {
 7 |   return $ab;
 8 | }

But got `B`

File "union_subtyping_l.php", line 6, character 23 - line 6, character 23:

 6 | function union_l((A | »B«) $ab): C {
 7 |   return $ab;
 8 | }

Derivation:
{
  "Derivation":[
    {
      "Begin":{
        "sub":[
          {
            "Flow":{
              "from":[
                {
                  "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
                }
              ],
              "kind":"Flow_param_hint",
              "into":[
                {
                  "Flow":{
                    "from":[
                      {
                        "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
                      }
                    ],
                    "kind":"Flow_local",
                    "into":[
                      {
                        "Flow":{
                          "from":[
                            {
                              "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
                            }
                          ],
                          "kind":"Flow_return_expr",
                          "into":[
                            {
                              "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ],
        "super":[
          {
            "Def":[
              {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
              [
                {
                  "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
                }
              ]
            ]
          }
        ]
      }
    },
    {
      "Step":{
        "rule":{"Using_prj_sub":"Prj_asymm_union"},
        "on_":"Subtype",
        "sub":[
          {
            "Def":[
              {"filename":"union_subtyping_l.php","line":3,"char_start":7,"char_end":7},
              [
                {
                  "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":23,"char_end":23}]
                }
              ]
            ]
          }
        ],
        "super":[
          {
            "Def":[
              {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
              [
                {
                  "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
                }
              ]
            ]
          }
        ]
      }
    }
  ]
}

File "", line 0, character 0 - line 0, character -1:


Reason:
{
  "Subtype":{
    "sub":[
      {
        "Prj_one":{
          "part":[
            {
              "Def":[
                {"filename":"union_subtyping_l.php","line":3,"char_start":7,"char_end":7},
                [
                  {
                    "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":23,"char_end":23}]
                  }
                ]
              ]
            }
          ],
          "prj":"Prj_asymm_union",
          "whole":[
            {
              "Flow":{
                "from":[
                  {
                    "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":18,"char_end":24}]
                  }
                ],
                "kind":"Flow_param_hint",
                "into":[
                  {
                    "Flow":{
                      "from":[
                        {
                          "Witness":[{"filename":"union_subtyping_l.php","line":6,"char_start":26,"char_end":28}]
                        }
                      ],
                      "kind":"Flow_local",
                      "into":[
                        {
                          "Flow":{
                            "from":[
                              {
                                "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":10,"char_end":12}]
                              }
                            ],
                            "kind":"Flow_return_expr",
                            "into":[
                              {
                                "Witness":[{"filename":"union_subtyping_l.php","line":7,"char_start":3,"char_end":13}]
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    ],
    "super":[
      {
        "Def":[
          {"filename":"union_subtyping_l.php","line":4,"char_start":7,"char_end":7},
          [
            {
              "Hint":[{"filename":"union_subtyping_l.php","line":6,"char_start":32,"char_end":32}]
            }
          ]
        ]
      }
    ]
  }
}

File "", line 0, character 0 - line 0, character -1:


2 errors found
