ERROR: File "unpack_optional_named_splat.php", line 7, characters 9-19:
Invalid argument (Typing[4110])
  File "unpack_optional_named_splat.php", line 5, characters 44-48:
  Expected `(int)`
  File "unpack_optional_named_splat.php", line 7, characters 9-19:
  But got `(int, int)`
ERROR: File "unpack_optional_named_splat.php", line 9, characters 9-19:
Invalid argument (Typing[4110])
  File "unpack_optional_named_splat.php", line 5, characters 44-48:
  Expected `(int)`
  File "unpack_optional_named_splat.php", line 9, characters 9-19:
  But got `(int, int)`
ERROR: File "unpack_optional_named_splat.php", line 10, characters 16-26:
Invalid argument (Typing[4110])
  File "unpack_optional_named_splat.php", line 5, characters 44-48:
  Expected `(int)`
  File "unpack_optional_named_splat.php", line 10, characters 16-26:
  But got `(int, int)`
ERROR: File "unpack_optional_named_splat.php", line 11, characters 3-4:
Invalid argument (Typing[4110])
  File "unpack_optional_named_splat.php", line 5, characters 44-48:
  Expected `(int)`
  File "unpack_optional_named_splat.php", line 11, characters 3-4:
  But got `()`
