// @generated by hh_manual from manual/hack/04-statements/04-for.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
async function example_snippet_wrapper(): Awaitable<void> {
  for ($i = 1; $i <= 5; ++$i) {
    echo "$i\t".($i * $i)."\n"; // output a table of squares
  }
  
  $i = 1;
  for (; $i <= 5; ) {
    echo "$i\t".($i * $i)."\n"; // output a table of squares
    ++$i;
  }
  
  $i = 1;
  for (; ; ) {
    if ($i > 5)
      break;
    echo "$i\t".($i * $i)."\n"; // output a table of squares
    ++$i;
  }
}
