// @generated by hh_manual from manual/hack/04-statements/04-for.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
async function example_snippet_wrapper(): Awaitable<void> {
  for ($i = 1, $j = 10; $i <= 10; $i = $i + 2, --$j) {
    // ...
  }
}
