shape<FieldsPartiallyKnown(unset fields:)>(alias => option(Tstring), classname => option(App \classname<Tint, >), elem_types => option(array), fields => option(array), generic_types => option(array), kind => Tint, name => option(Tstring), nullable => option(Tbool), param_types => option(array), return_type => option(array))
App \classname<App \C<[1]intersect(), >, >
App \classname<App \D<>, >
App \classname<App \Vector<Tint, >, >
App \classname<App \C<Tstring, >, >
option(App \classname<fun tuple(App \C<Tint, >, App \C<Tint, >),  -> App \Vector<App \C<Tint, >, >, >)
No errors
