File "higher_order_function.php", line 17, characters 3-7:
This call is not allowed because its coeffects are incompatible with the context (Typing[4390])
  File "higher_order_function.php", line 16, characters 3-7:
  From this declaration, the context of this function body provides the capability set {}
  File "higher_order_function.php", line 15, characters 19-20:
  But the function being called requires the capability Te
  File "coeffect/contexts.hhi", line 28, characters 1-23:
  Hack provides a list of supported contexts here
File "higher_order_function.php", line 32, characters 3-37:
This call is not allowed because its coeffects are incompatible with the context (Typing[4390])
  File "higher_order_function.php", line 29, characters 34-35:
  From this declaration, the context of this function body provides the capability set {}
  File "higher_order_function.php", line 6, characters 3-4:
  But the function being called requires the default capability set {AccessGlobals, Output, WriteProperty}
  File "coeffect/contexts.hhi", line 28, characters 1-23:
  Hack provides a list of supported contexts here
