// @generated by hh_manual
function takes_server2(shape('name' => string, 'age' => ?int) $s): void {
  $age = $s['age'] ?? 0;
}

function takes_server3(shape('name' => string, ...) $s): void {
  $age = Shapes::idx($s, 'age', 0) as int;
}
