File "consecutive_splicing.php", line 6, characters 13-13:
Expected `ExprTree<[unresolved], [unresolved], [unresolved]>` because this is being spliced into another Expression Tree (Typing[4110])
  File "consecutive_splicing.php", line 16, characters 46-76:
  But got `dynamic` because it is an unenforceable type
File "consecutive_splicing.php", line 7, characters 13-13:
Expected `ExprTree<[unresolved], [unresolved], [unresolved]>` because this is being spliced into another Expression Tree (Typing[4110])
  File "consecutive_splicing.php", line 16, characters 46-76:
  But got `dynamic` because it is an unenforceable type
