File "helper_function_noreturn_bad.php", line 22, characters 22-31:
Invalid argument (Typing[4110])
  File "helper_function_noreturn_bad.php", line 20, characters 70-70:
  Expected `T`
  File "helper_function_noreturn_bad.php", line 7, characters 83-90:
  But got `noreturn`
File "helper_function_noreturn_bad.php", line 23, characters 22-26:
Invalid argument (Typing[4110])
  File "helper_function_noreturn_bad.php", line 20, characters 70-70:
  Expected `T`
  File "helper_function_noreturn_bad.php", line 14, characters 81-88:
  But got `noreturn`
File "helper_function_noreturn_bad.php", line 22, characters 22-31:
You are using the return value of a `noreturn` function (Typing[4133])
  File "helper_function_noreturn_bad.php", line 7, characters 83-90:
  A `noreturn` function always throws or exits.
File "helper_function_noreturn_bad.php", line 23, characters 22-26:
You are using the return value of a `noreturn` function (Typing[4133])
  File "helper_function_noreturn_bad.php", line 14, characters 81-88:
  A `noreturn` function always throws or exits.
