File "invalid_call1.php", line 15, characters 5-18:
Expression trees only support function calls and static method calls on named classes. (Parsing[1002])
File "invalid_call1.php", line 15, characters 5-6:
Variable `$y` is undefined, or not always defined. (Naming[2050])
File "invalid_call1.php", line 15, characters 5-6:
Was expecting a class, but got an untyped value (Typing[4026])
File "invalid_call1.php", line 15, characters 5-18:
Was expecting a function value but type is unknown (Typing[4297])
  File "invalid_call1.php", line 15, characters 5-18:
  It is unknown because type parameter `T` of `symbol` could not be determined. Please add explicit type parameters to the invocation of `symbol`
  File "invalid_call1.php", line 52, characters 33-33:
    via this generic `T`
