File "nested_expression_tree_lambda.php", line 6, characters 22-28:
Expression trees may not be nested. (Parsing[1002])
File "nested_expression_tree_lambda.php", line 5, characters 1-59:
There is an error somewhere in this definition. However the type checker reports that the error is elsewhere. This is a bug in the type checker. Please run `hh rage` and post the link in https://fb.workplace.com/groups/hackforhiphop/. (Typing[4110])
  File "", line 0, characters 0-0:
  Expected `Spliceable<[unresolved], [unresolved], [unresolved]>` because this is being spliced into another Expression Tree
  File "nested_expression_tree_lambda.php", line 16, characters 6-43:
  But got `dynamic` because it is an unenforceable type
File "nested_expression_tree_lambda.php", line 5, characters 1-59:
There is an error somewhere in this definition. However the type checker reports that the error is elsewhere. This is a bug in the type checker. Please run `hh rage` and post the link in https://fb.workplace.com/groups/hackforhiphop/. (Typing[4110])
  File "", line 0, characters 0-0:
  Expected `Spliceable<[unresolved], [unresolved], [unresolved]>` because this is being spliced into another Expression Tree
  File "nested_expression_tree_lambda.php", line 30, characters 5-45:
  But got `dynamic` because it is an unenforceable type
File "nested_expression_tree_lambda.php", line 6, characters 27-27:
Expected `Spliceable<[unresolved], [unresolved], [unresolved]>` because this is being spliced into another Expression Tree (Typing[4110])
  File "nested_expression_tree_lambda.php", line 16, characters 6-43:
  But got `dynamic` because it is an unenforceable type
File "nested_expression_tree_lambda.php", line 6, characters 27-27:
Expected `Spliceable<[unresolved], [unresolved], [unresolved]>` because this is being spliced into another Expression Tree (Typing[4110])
  File "nested_expression_tree_lambda.php", line 42, characters 6-34:
  But got `dynamic` because it is an unenforceable type
File "nested_expression_tree_lambda.php", line 6, characters 27-27:
Invalid argument (Typing[4110])
  File "nested_expression_tree_lambda.php", line 15, characters 5-7:
  Expected `int`
  File "nested_expression_tree_lambda.php", line 41, characters 15-28:
  But got `ExampleContext`
