ERROR: File "pipe3.php", line 16, characters 48-49:
Invalid argument (Typing[4110])
  File "pipe3.php", line 9, characters 53-62:
  Expected `int`
  File "pipe3.php", line 9, characters 109-121:
  But got `string`
ERROR: File "pipe3.php", line 18, characters 10-12:
Invalid return type (Typing[4110])
  File "pipe3.php", line 13, characters 57-68:
  Expected `float`
  File "pipe3.php", line 9, characters 109-121:
  But got `string`
  File "expr_tree.php", line 49, characters 44-49:
    via this generic `TInfer`
  File "expr_tree.php", line 91, characters 29-34:
    via this generic `TInfer`
  File "expr_tree.php", line 504, characters 73-73:
    via this generic `T`
  File "expr_tree.php", line 85, characters 47-52:
    via this generic `TInfer`
