File "splice_state.php", line 86, characters 18-26:
Typing error (Typing[4110])
  File "splice_state.php", line 86, characters 18-22:
  Expected `num` because this is used in an arithmetic operation
  File "splice_state.php", line 6, characters 10-13:
  But got `?int`
  File "splice_state.php", line 84, characters 15-111:
  All the local information about `$x->x` has been invalidated by this lambda function.
This is a limitation of the type-checker; use a local if that's the problem.
