File "void_return_errors.php", line 7, characters 8-22:
Typing error (Typing[4110])
  File "void_return_errors.php", line 7, characters 8-22:
  Expected `Spliceable<[unresolved], [unresolved], [unresolved]>` because this is being spliced into another Expression Tree
  File "expr_tree.hhi", line 41, characters 38-76:
  But got `dynamic` because it is an unenforceable type
File "void_return_errors.php", line 7, characters 8-22:
You cannot return a value (Typing[4084])
  File "void_return_errors.php", line 7, characters 12-15:
  This is a `void` function
