File "void_return_errors2.php", line 7, characters 8-31:
Invalid return type (Typing[4110])
  File "void_return_errors2.php", line 7, characters 12-15:
  Expected `void`
  File "expr_tree.hhi", line 34, characters 38-48:
  But got `ExampleVoid`
File "void_return_errors2.php", line 7, characters 8-31:
You cannot return a value (Typing[4084])
  File "void_return_errors2.php", line 7, characters 12-15:
  This is a `void` function
File "void_return_errors2.php", line 7, characters 23-29:
Invalid return type (Typing[4110])
  File "void_return_errors2.php", line 7, characters 12-15:
  Expected `void`
  File "expr_tree.hhi", line 34, characters 38-48:
  But got `ExampleVoid`
File "void_return_errors2.php", line 7, characters 23-29:
You cannot return a value (Typing[4084])
  File "void_return_errors2.php", line 7, characters 12-15:
  This is a `void` function
