<?php
// Copyright 2004-present Facebook. All Rights Reserved.
// This file is @generated by
// fbcode/hphp/facebook/tools/code_model/Generate.sh

namespace HH\CodeModel {

/**
 * Implemented by classes that represent metadata for code.
 */
trait Node /*implements INode*/ {
  private /*?Vector<string>*/ $comments;
  private /*?ISourceLocation*/ $sourceLocation;

  /**
   * Zero or more code comments that immediately preceded this code node
   */
  public function getComments() /*: Vector<string>*/ {
    if ($this->comments === null) {
      $this->comments = Vector {};
    }
    return $this->comments;
  }
  /**
   * Zero or more code comments that immediately preceded this code node
   */
  public function setComments(/*Vector<string>*/ $value) /*: this*/ {
    $this->comments = $value;
    return $this;
  }

  /**
   * The source location corresponding to this code node.
   * This includes the repository path and version.
   */
  public function getSourceLocation() /*: ?ISourceLocation*/ {
    return $this->sourceLocation;
  }
  /**
   * The source location corresponding to this code node.
   * This includes the repository path and version.
   */
  public function setSourceLocation(/*?ISourceLocation*/ $value) /*: this*/ {
    $this->sourceLocation = $value;
    return $this;
  }

}
}
