WARN: File "trivial_compare_string_arraykey_enum_to_num_good.php", line 9, characters 10-20:
Invalid comparison: This expression will always return `false`.
A value of type `A` can never be equal to a value of type `num` (Warn[12007])
WARN: File "trivial_compare_string_arraykey_enum_to_num_good.php", line 13, characters 10-20:
Invalid comparison: This expression will always return `false`.
A value of type `num` can never be equal to a value of type `A` (Warn[12007])
WARN: File "trivial_compare_string_arraykey_enum_to_num_good.php", line 17, characters 10-20:
Invalid comparison: This expression will always return `true`.
A value of type `A` can never be equal to a value of type `num` (Warn[12007])
WARN: File "trivial_compare_string_arraykey_enum_to_num_good.php", line 21, characters 10-20:
Invalid comparison: This expression will always return `true`.
A value of type `num` can never be equal to a value of type `A` (Warn[12007])
