=== Sound Dynamic analysis results for call_arguments2.php
Constraints for \d:
?3 ⊆ [24:24-46]
Function call at [24:24-46]
Introduction at [24:25-28]
Upcast at ?3
[24:25-28] ⊆ ?3

Constraints for \e:
?2 ⊆ [20:6-10]
Function call at [20:6-10]
Introduction at [19:9-12]
Upcast at ?2
[19:9-12] ⊆ ?2

Constraints for \f:

Constraints for \g:

Constraints for \h:
?1 ⊆ [14:6-10]
Function call at [14:6-10]
Introduction at [13:8-11]
[13:8-11] ⊆ ?1

