ERROR: File "protected_internal.php--non_test.php", line 5, characters 11-18:
Cannot access an internal element from module `pi` in the default module (Typing[4444])
  File "protected_internal.php--target.php", line 7, characters 31-38:
  This is from module `pi`
ERROR: File "protected_internal.php--non_test.php", line 5, characters 11-18:
Cannot access this protected member, you don't extend ProtIntTarget (Typing[4112])
  File "protected_internal.php--target.php", line 7, characters 31-38:
  This member is protected internal
