File "instance_method_misnamed.php", line 7, characters 7-16:
Expression trees do not support calling instance methods (Parsing[1002])
File "instance_method_misnamed.php", line 7, characters 7-8:
Variable `$x` is undefined, or not always defined. (Naming[2050])
File "instance_method_misnamed.php", line 7, characters 11-14:
No instance method `fooo` in `MyClass` (Typing[4053])
  File "instance_method_misnamed.php", line 12, characters 19-21:
  Did you mean `foo` instead?
  File "instance_method_misnamed.php", line 6, characters 17-23:
  This is why I think it is an object of type MyClass
  File "instance_method_misnamed.php", line 11, characters 16-22:
  Declaration of `MyClass` is here
