File "nested_expression_trees.php", line 6, characters 26-26:
A right brace `}` is expected here. (Parsing[1002])
File "nested_expression_trees.php", line 6, characters 16-25:
Unbound name: `ExampleDsl` (a global constant) (Naming[2049])
File "nested_expression_trees.php", line 6, characters 28-28:
Unbound name: ``` (a global constant) (Naming[2049])
File "nested_expression_trees.php", line 6, characters 30-31:
Hack does not support top level statements. Use the `__EntryPoint` attribute on a function instead (Naming[2128])
File "nested_expression_trees.php", line 7, characters 1-1:
Hack does not support top level statements. Use the `__EntryPoint` attribute on a function instead (Naming[2128])
File "nested_expression_trees.php", line 6, characters 16-25:
Unbound global constant (Typing) (Typing[4106])
File "nested_expression_trees.php", line 6, characters 28-28:
Unbound global constant (Typing) (Typing[4106])
