File "private_property_access.php", line 5, characters 16-22:
Lacking `__construct`, class `MyClass` does not initialize its private member(s): `prop` (NastCheck[3030])
File "private_property_access.php", line 10, characters 7-8:
Typing error (Typing[4448])
  File "private_property_access.php", line 10, characters 11-14:
  Cannot access non-public members within expression trees.
  File "private_property_access.php", line 6, characters 11-20:
  Member defined here
