FoldedClass {
    name: "\\A",
    kind: Cclass(
        Concrete,
    ),
    ancestors: {
        "\\XHPChild": XHPChild,
        "\\Stringish": Stringish,
        "\\StringishObject": StringishObject,
    },
    methods: {
        "__toString": FoldedElement {
            flags: (empty),
            origin: "\\A",
            visibility: Public,
            deprecated: None,
            sort_text: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: HH\classname<this>,
            origin: "\\A",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\B",
    kind: Cclass(
        Abstract,
    ),
    ancestors: {
        "\\XHPChild": XHPChild,
        "\\Stringish": Stringish,
        "\\StringishObject": StringishObject,
    },
    methods: {
        "__toString": FoldedElement {
            flags: ABSTRACT,
            origin: "\\B",
            visibility: Public,
            deprecated: None,
            sort_text: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: HH\classname<this>,
            origin: "\\B",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\SomeOtherC",
    kind: Cinterface,
    ancestors: {
        "\\XHPChild": XHPChild,
        "\\Stringish": Stringish,
        "\\StringishObject": StringishObject,
    },
    methods: {
        "__toString": FoldedElement {
            flags: ABSTRACT,
            origin: "\\SomeOtherC",
            visibility: Public,
            deprecated: None,
            sort_text: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: HH\classname<this>,
            origin: "\\SomeOtherC",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\TA",
    kind: Ctrait,
    ancestors: {
        "\\XHPChild": XHPChild,
        "\\Stringish": Stringish,
        "\\StringishObject": StringishObject,
    },
    methods: {
        "__toString": FoldedElement {
            flags: (empty),
            origin: "\\TA",
            visibility: Public,
            deprecated: None,
            sort_text: None,
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: HH\classname<this>,
            origin: "\\TA",
            refs: [],
        },
    },
}
