FoldedClass {
    name: "\\A",
    kind: Cclass(
        Concrete,
    ),
    ancestors: {
        "\\XHPChild": XHPChild,
        "\\Stringish": Stringish,
        "\\StringishObject": StringishObject,
    },
    methods: {
        "__toString": FoldedElement {
            flags: ClassEltFlags(
                0,
            ),
            origin: "\\A",
            visibility: Public,
            deprecated: None,
            sealed_allowlist: None,
            sort_text: None,
            overlapping_tparams: None,
            package_requirement: Some(
                RPNormal,
            ),
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: class<this>,
            origin: "\\A",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\B",
    kind: Cclass(
        Abstract,
    ),
    ancestors: {
        "\\XHPChild": XHPChild,
        "\\Stringish": Stringish,
        "\\StringishObject": StringishObject,
    },
    methods: {
        "__toString": FoldedElement {
            flags: ClassEltFlags(
                1,
            ),
            origin: "\\B",
            visibility: Public,
            deprecated: None,
            sealed_allowlist: None,
            sort_text: None,
            overlapping_tparams: None,
            package_requirement: Some(
                RPNormal,
            ),
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: class<this>,
            origin: "\\B",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\SomeOtherC",
    kind: Cinterface,
    ancestors: {
        "\\XHPChild": XHPChild,
        "\\Stringish": Stringish,
        "\\StringishObject": StringishObject,
    },
    methods: {
        "__toString": FoldedElement {
            flags: ClassEltFlags(
                1,
            ),
            origin: "\\SomeOtherC",
            visibility: Public,
            deprecated: None,
            sealed_allowlist: None,
            sort_text: Some(
                "zzz",
            ),
            overlapping_tparams: None,
            package_requirement: Some(
                RPNormal,
            ),
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: class<this>,
            origin: "\\SomeOtherC",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\TA",
    kind: Ctrait,
    ancestors: {
        "\\XHPChild": XHPChild,
        "\\Stringish": Stringish,
        "\\StringishObject": StringishObject,
    },
    methods: {
        "__toString": FoldedElement {
            flags: ClassEltFlags(
                0,
            ),
            origin: "\\TA",
            visibility: Public,
            deprecated: None,
            sealed_allowlist: None,
            sort_text: None,
            overlapping_tparams: None,
            package_requirement: Some(
                RPNormal,
            ),
        },
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: class<this>,
            origin: "\\TA",
            refs: [],
        },
    },
}
