[(Fun
    { Aast.AnnotatedAST.f_annotation = (); f_mode = <opaque>;
      f_ret = (Some ([5:30-34], (Hprim Tvoid))); f_name = ([5:10-11], "\\f");
      f_tparams = []; f_where_constraints = []; f_variadic = FVnonVariadic;
      f_params =
      [{ Aast.AnnotatedAST.param_annotation = ([5:17-19], bool);
         param_hint = (Some ([5:12-16], (Hprim Tbool)));
         param_is_reference = false; param_is_variadic = false;
         param_pos = [5:17-19]; param_name = "$b"; param_expr = None;
         param_callconv = None; param_user_attributes = [] };
        { Aast.AnnotatedAST.param_annotation = ([5:25-27], int);
          param_hint = (Some ([5:21-24], (Hprim Tint)));
          param_is_reference = false; param_is_variadic = false;
          param_pos = [5:25-27]; param_name = "$a"; param_expr = None;
          param_callconv = None; param_user_attributes = [] }
        ];
      f_body =
      (NamedBody
         { Aast.AnnotatedAST.fnb_nast =
           [(Do (
               [(Expr (([7:5-7], (int | string)), (Lvar ([7:5-7], $a))));
                 (Expr
                    (([8:5-12], string),
                     (Binop ((Eq None),
                        (([8:5-7], string), (Lvar ([8:5-7], $a))),
                        (([8:10-12], string), (String ""))))))
                 ],
               (([9:12-14], bool), (Lvar ([9:12-14], $b)))));
             (Expr (([10:3-5], string), (Lvar ([10:3-5], $a))));
             (Do (
                [(Expr (([13:5-7], string), (Lvar ([13:5-7], $a))));
                  (Expr
                     (([14:5-12], string),
                      (Binop ((Eq None),
                         (([14:5-7], string), (Lvar ([14:5-7], $a))),
                         (([14:10-12], string), (String ""))))))
                  ],
                (([15:12-14], bool), (Lvar ([15:12-14], $b)))));
             (Do (
                [(Expr (([18:5-7], string), (Lvar ([18:5-7], $a))));
                  (Expr
                     (([19:5-11], int),
                      (Binop ((Eq None),
                         (([19:5-7], int), (Lvar ([19:5-7], $a))),
                         (([19:10-11], int), (Int "0"))))));
                  (Do (
                     [(Expr (([21:7-9], int), (Lvar ([21:7-9], $a))));
                       (Expr
                          (([22:7-13], int),
                           (Binop ((Eq None),
                              (([22:7-9], int), (Lvar ([22:7-9], $a))),
                              (([22:12-13], int), (Int "1"))))))
                       ],
                     (([23:14-16], bool), (Lvar ([23:14-16], $b)))));
                  (Expr
                     (([24:5-12], string),
                      (Binop ((Eq None),
                         (([24:5-7], string), (Lvar ([24:5-7], $a))),
                         (([24:10-12], string), (String ""))))))
                  ],
                (([25:12-14], bool), (Lvar ([25:12-14], $b)))))
             ];
           fnb_unsafe = false });
      f_fun_kind = FSync; f_user_attributes = []; f_ret_by_ref = false })
  ]
