{
  "name":"Baz",
  "kind":"ServerTypeHierarchyTypes.Class",
  "pos":"line 43, characters 16-18",
  "ancestors":[
    {
      "name":"Bar",
      "kind":"ServerTypeHierarchyTypes.Class",
      "pos":"line 41, characters 7-9"
    },
    {
      "name":"Foo",
      "kind":"ServerTypeHierarchyTypes.Class",
      "pos":"line 29, characters 7-9"
    },
    {
      "name":"Trait_1",
      "kind":"ServerTypeHierarchyTypes.Trait",
      "pos":"line 10, characters 7-13"
    },
    {
      "name":"Trait_2",
      "kind":"ServerTypeHierarchyTypes.Trait",
      "pos":"line 20, characters 7-13"
    },
    {
      "name":"Trait_3",
      "kind":"ServerTypeHierarchyTypes.Trait",
      "pos":"line 24, characters 7-13"
    }
  ],
  "members":[
    {
      "name":"method_from_Baz",
      "snippet":"method_from_Baz(int $val, int ...$vals): void",
      "kind":"ServerTypeHierarchyTypes.Method",
      "pos":"line 52, characters 12-26",
      "origin":"Baz"
    },
    {
      "name":"method_from_Foo",
      "snippet":"method_from_Foo(): void",
      "kind":"ServerTypeHierarchyTypes.Method",
      "pos":"line 36, characters 12-26",
      "origin":"Foo"
    },
    {
      "name":"method_from_trait_1",
      "snippet":"method_from_trait_1(): void",
      "kind":"ServerTypeHierarchyTypes.Method",
      "pos":"line 15, characters 12-30",
      "origin":"Trait_1"
    },
    {
      "name":"static_method_from_Baz",
      "snippet":"static_method_from_Baz(): void",
      "kind":"ServerTypeHierarchyTypes.SMethod",
      "pos":"line 54, characters 19-40",
      "origin":"Baz"
    },
    {
      "name":"static_method_from_Foo",
      "snippet":"static_method_from_Foo(): void",
      "kind":"ServerTypeHierarchyTypes.SMethod",
      "pos":"line 38, characters 19-40",
      "origin":"Foo"
    },
    {
      "name":"static_method_from_Trait_1",
      "snippet":"static_method_from_Trait_1(): void",
      "kind":"ServerTypeHierarchyTypes.SMethod",
      "pos":"line 17, characters 19-44",
      "origin":"Trait_1"
    },
    {
      "name":"prop_from_Baz",
      "snippet":"prop_from_Baz: int",
      "kind":"ServerTypeHierarchyTypes.Property",
      "pos":"line 48, characters 3-5",
      "origin":"Baz"
    },
    {
      "name":"prop_from_Foo",
      "snippet":"prop_from_Foo: int",
      "kind":"ServerTypeHierarchyTypes.Property",
      "pos":"line 32, characters 3-5",
      "origin":"Foo"
    },
    {
      "name":"prop_from_Trait_1",
      "snippet":"prop_from_Trait_1: int",
      "kind":"ServerTypeHierarchyTypes.Property",
      "pos":"line 11, characters 3-5",
      "origin":"Trait_1"
    },
    {
      "name":"$static_prop_from_Baz",
      "snippet":"$static_prop_from_Baz: int",
      "kind":"ServerTypeHierarchyTypes.SProperty",
      "pos":"line 50, characters 10-12",
      "origin":"Baz"
    },
    {
      "name":"$static_prop_from_Foo",
      "snippet":"$static_prop_from_Foo: int",
      "kind":"ServerTypeHierarchyTypes.SProperty",
      "pos":"line 34, characters 10-12",
      "origin":"Foo"
    },
    {
      "name":"$static_prop_from_Trait_1",
      "snippet":"$static_prop_from_Trait_1: int",
      "kind":"ServerTypeHierarchyTypes.SProperty",
      "pos":"line 13, characters 10-12",
      "origin":"Trait_1"
    },
    {
      "name":"class",
      "snippet":"class: classname<this>",
      "kind":"ServerTypeHierarchyTypes.Const",
      "pos":"line 43, characters 16-18",
      "origin":"Baz"
    },
    {
      "name":"const_from_Baz",
      "snippet":"const_from_Baz: int",
      "kind":"ServerTypeHierarchyTypes.Const",
      "pos":"line 46, characters 13-26",
      "origin":"Baz"
    },
    {
      "name":"const_from_Foo",
      "snippet":"const_from_Foo: int",
      "kind":"ServerTypeHierarchyTypes.Const",
      "pos":"line 30, characters 13-26",
      "origin":"Foo"
    }
  ]
}