{
  "name":"Trait_2",
  "kind":"ServerTypeHierarchyTypes.Trait",
  "pos":"line 13, characters 7-13",
  "ancestors":[
    {
      "name":"Trait_1",
      "kind":"ServerTypeHierarchyTypes.Trait",
      "pos":"line 3, characters 7-13"
    }
  ],
  "members":[
    {
      "name":"method_from_trait_1",
      "snippet":"method_from_trait_1(): void",
      "kind":"ServerTypeHierarchyTypes.Method",
      "pos":"line 8, characters 12-30",
      "origin":"Trait_1"
    },
    {
      "name":"method_from_trait_2",
      "snippet":"method_from_trait_2(): void",
      "kind":"ServerTypeHierarchyTypes.Method",
      "pos":"line 20, characters 12-30",
      "origin":"Trait_2"
    },
    {
      "name":"static_method_from_Trait_1",
      "snippet":"static_method_from_Trait_1(): void",
      "kind":"ServerTypeHierarchyTypes.SMethod",
      "pos":"line 10, characters 19-44",
      "origin":"Trait_1"
    },
    {
      "name":"static_method_from_Trait_2",
      "snippet":"static_method_from_Trait_2(): void",
      "kind":"ServerTypeHierarchyTypes.SMethod",
      "pos":"line 22, characters 19-44",
      "origin":"Trait_2"
    },
    {
      "name":"prop_from_Trait_1",
      "snippet":"prop_from_Trait_1: int",
      "kind":"ServerTypeHierarchyTypes.Property",
      "pos":"line 4, characters 3-5",
      "origin":"Trait_1"
    },
    {
      "name":"prop_from_Trait_2",
      "snippet":"prop_from_Trait_2: int",
      "kind":"ServerTypeHierarchyTypes.Property",
      "pos":"line 16, characters 3-5",
      "origin":"Trait_2"
    },
    {
      "name":"$static_prop_from_Trait_1",
      "snippet":"$static_prop_from_Trait_1: int",
      "kind":"ServerTypeHierarchyTypes.SProperty",
      "pos":"line 6, characters 10-12",
      "origin":"Trait_1"
    },
    {
      "name":"$static_prop_from_Trait_2",
      "snippet":"$static_prop_from_Trait_2: int",
      "kind":"ServerTypeHierarchyTypes.SProperty",
      "pos":"line 18, characters 10-12",
      "origin":"Trait_2"
    },
    {
      "name":"class",
      "snippet":"class: classname<this>",
      "kind":"ServerTypeHierarchyTypes.Const",
      "pos":"line 13, characters 7-13",
      "origin":"Trait_2"
    }
  ]
}