File "bad_inout_hint_parent7.php", line 10, characters 7-8:
Class C2 does not correctly implement all required methods  (Typing[4110])
File "bad_inout_hint_parent7.php", line 10, characters 18-19:
Some methods are incompatible with those declared in type C1
Read the following to see why:
File "bad_inout_hint_parent7.php", line 11, characters 19-21:
Member foo has the wrong type
File "bad_inout_hint_parent7.php", line 4, characters 42-44:
This is an int
File "bad_inout_hint_parent7.php", line 11, characters 42-49:
It is incompatible with an array key (int/string)
