error: Typing[4110] Invalid return type

File class_hint_string.php, line 10, character 10 - line 10, character 12:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   $gc = generic_string($c);
10 |   return »$gc«;
11 | }

Expected int

File class_hint_string.php, line 8, character 29 - line 8, character 31:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): »int« {
 9 |   $gc = generic_string($c);
10 |   return $gc;
11 | }

But got class<<expr#2> as C>

File class_hint_string.php, line 8, character 15 - line 8, character 22:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(»class<C>« $c): int {
 9 |   $gc = generic_string($c);
10 |   return $gc;
11 | }

  via this generic T

File class_hint_string.php, line 6, character 45 - line 6, character 45:

 5 | class C {}
 6 | function generic_string<T as string>(T $t): »T« { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   $gc = generic_string($c);

Here's why:


  Step 1 of 2                                                                   

I started by checking this subtype relationship.

The subtype comes from this return hint

File class_hint_string.php, line 6, character 45 - line 6, character 45:

 5 | class C {}
 6 | function generic_string<T as string>(T $t): »T« { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   $gc = generic_string($c);

and flows into this expression

File class_hint_string.php, line 9, character 9 - line 9, character 26:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   $gc = »generic_string($c)«;
10 |   return $gc;
11 | }

as the return type of the function call

which itself flows into this expression

File class_hint_string.php, line 9, character 3 - line 9, character 5:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   »$gc« = generic_string($c);
10 |   return $gc;
11 | }

via an assignment

which itself flows into this expression

File class_hint_string.php, line 10, character 10 - line 10, character 12:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   $gc = generic_string($c);
10 |   return »$gc«;
11 | }

as the type of the local variable

which itself flows into this expression

File class_hint_string.php, line 10, character 3 - line 10, character 13:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   $gc = generic_string($c);
10 |   »return $gc;«
11 | }

because it is used in a return position

The supertype comes from this hint

File class_hint_string.php, line 8, character 29 - line 8, character 31:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): »int« {
 9 |   $gc = generic_string($c);
10 |   return $gc;
11 | }


  Step 2 of 2                                 (here is where the error occurred) 

The subtype is a union type so next I checked the subtype constraint is satisfied for all its elements.

The subtype comes from this generic parameter T of generic_string

File class_hint_string.php, line 9, character 9 - line 9, character 22:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   $gc = »generic_string«($c);
10 |   return $gc;
11 | }

and flows into this hint

File class_hint_string.php, line 6, character 45 - line 6, character 45:

 5 | class C {}
 6 | function generic_string<T as string>(T $t): »T« { return $t; }
 7 | 
 8 | function test(class<C> $c): int {
 9 |   $gc = generic_string($c);

as the instantiation of the generic T

The supertype is the same as before.

File class_hint_string.php, line 8, character 29 - line 8, character 31:

 6 | function generic_string<T as string>(T $t): T { return $t; }
 7 | 
 8 | function test(class<C> $c): »int« {
 9 |   $gc = generic_string($c);
10 |   return $gc;
11 | }

