#if EXT_TYPE == 0
"iconv_mime_encode", T(Variant), S(0), "field_name", T(String), NULL, S(0), "field_value", T(String), NULL, S(0), "preferences", T(Variant), "null_variant", S(0), NULL, S(0), 
"iconv_mime_decode", T(Variant), S(0), "encoded_string", T(String), NULL, S(0), "mode", T(Int32), "0", S(0), "charset", T(String), "null_string", S(0), NULL, S(0), 
"iconv_mime_decode_headers", T(Variant), S(0), "encoded_headers", T(String), NULL, S(0), "mode", T(Int32), "0", S(0), "charset", T(String), "null_string", S(0), NULL, S(0), 
"iconv_get_encoding", T(Variant), S(0), "type", T(String), "\"all\"", S(0), NULL, S(0), 
"iconv_set_encoding", T(Boolean), S(0), "type", T(String), NULL, S(0), "charset", T(String), NULL, S(0), NULL, S(0), 
"iconv", T(Variant), S(0), "in_charset", T(String), NULL, S(0), "out_charset", T(String), NULL, S(0), "str", T(String), NULL, S(0), NULL, S(0), 
"iconv_strlen", T(Variant), S(0), "str", T(String), NULL, S(0), "charset", T(String), "null_string", S(0), NULL, S(0), 
"iconv_strpos", T(Variant), S(0), "haystack", T(String), NULL, S(0), "needle", T(String), NULL, S(0), "offset", T(Int32), "0", S(0), "charset", T(String), "null_string", S(0), NULL, S(0), 
"iconv_strrpos", T(Variant), S(0), "haystack", T(String), NULL, S(0), "needle", T(String), NULL, S(0), "charset", T(String), "null_string", S(0), NULL, S(0), 
"iconv_substr", T(Variant), S(0), "str", T(String), NULL, S(0), "offset", T(Int32), NULL, S(0), "length", T(Int32), "0", S(0), "charset", T(String), "null_string", S(0), NULL, S(0), 
"ob_iconv_handler", T(String), S(0), "contents", T(String), NULL, S(0), "status", T(Int32), NULL, S(0), NULL, S(0), 
#elif EXT_TYPE == 1
#elif EXT_TYPE == 2
#elif EXT_TYPE == 3

#endif
