#if EXT_TYPE == 0
"hphp_recursiveiteratoriterator___construct", T(Object), S(0), "obj", T(Object), NULL, S(0), "iterator", T(Object), NULL, S(0), "mode", T(Int64), NULL, S(0), "flags", T(Int64), NULL, S(0), NULL, S(0), 
"hphp_recursiveiteratoriterator_getinneriterator", T(Object), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursiveiteratoriterator_current", T(Variant), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursiveiteratoriterator_key", T(Variant), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursiveiteratoriterator_next", T(Void), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursiveiteratoriterator_rewind", T(Void), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursiveiteratoriterator_valid", T(Boolean), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator___construct", T(Object), S(0), "obj", T(Object), NULL, S(0), "path", T(String), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator_key", T(Variant), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator_next", T(Void), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator_rewind", T(Void), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator_seek", T(Void), S(0), "obj", T(Object), NULL, S(0), "position", T(Int64), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator_current", T(Variant), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator___tostring", T(String), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator_valid", T(Boolean), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_directoryiterator_isdot", T(Boolean), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator___construct", T(Object), S(0), "obj", T(Object), NULL, S(0), "path", T(String), NULL, S(0), "flags", T(Int64), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_key", T(Variant), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_next", T(Void), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_rewind", T(Void), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_seek", T(Void), S(0), "obj", T(Object), NULL, S(0), "position", T(Int64), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_current", T(Variant), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator___tostring", T(String), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_valid", T(Boolean), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_haschildren", T(Boolean), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_getchildren", T(Object), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_getsubpath", T(String), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
"hphp_recursivedirectoryiterator_getsubpathname", T(String), S(0), "obj", T(Object), NULL, S(0), NULL, S(0), 
#elif EXT_TYPE == 1
#elif EXT_TYPE == 2
#elif EXT_TYPE == 3

#endif
