#!/bin/bash

if [ ! -f "config.cmake" ]; then
  echo "config.cmake not found" >&2
  exit 1
fi

if [ ! -z $BASH_SOURCE ]; then
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
    DIR="$( cd "$( dirname "$0" )" && pwd )"
fi

cp ${DIR}/hphpize.cmake CMakeLists.txt

echo "** hphpize complete, now run \`cmake . && make\` to build"
