#!/bin/bash

if [ ! -f "config.cmake" ]; then
  echo "config.cmake not found" >&2
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cp ${DIR}/hphpize.cmake CMakeLists.txt

echo "** hphpize complete, now run \`cmake . && make\` to build"
