--- ocaml
+++ rupro
@@ -1,151 +1,157 @@
 FoldedClass {
     name: "\\I",
     pos: Pos(root|implement_interface.php, 3:11-12),
     kind: Cinterface,
     consts: {
         "T": ClassConst {
             is_synthesized: true,
             kind: CCAbstract(
                 false,
             ),
             pos: Pos(root|implement_interface.php, 4:23-24),
             ty: HH\TypeStructure<this::T>,
             origin: "\\I",
             refs: [],
         },
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|implement_interface.php, 3:11-12),
             ty: HH\classname<this>,
             origin: "\\I",
             refs: [],
         },
     },
     type_consts: {
         "T": TypeConst {
             is_synthesized: false,
             name: (
                 Pos(root|implement_interface.php, 4:23-24),
                 "T",
             ),
             kind: AbstractTypeconst {
                 as_constraint: None,
                 super_constraint: None,
                 default: None,
             },
             origin: "\\I",
             enforceable: None,
             reifiable: None,
             is_concretized: false,
             is_ctx: false,
         },
     },
 }
 FoldedClass {
     name: "\\A",
     pos: Pos(root|implement_interface.php, 6:16-17),
     kind: Cclass(
         Abstract,
     ),
     consts: {
         "T": ClassConst {
             is_synthesized: true,
             kind: CCAbstract(
                 true,
             ),
             pos: Pos(root|implement_interface.php, 7:23-24),
             ty: HH\TypeStructure<this::T>,
             origin: "\\A",
             refs: [],
         },
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|implement_interface.php, 6:16-17),
             ty: HH\classname<this>,
             origin: "\\A",
             refs: [],
         },
     },
     type_consts: {
         "T": TypeConst {
             is_synthesized: false,
             name: (
                 Pos(root|implement_interface.php, 7:23-24),
                 "T",
             ),
             kind: AbstractTypeconst {
                 as_constraint: None,
                 super_constraint: None,
                 default: Some(
                     string,
                 ),
             },
             origin: "\\A",
             enforceable: None,
             reifiable: None,
             is_concretized: false,
             is_ctx: false,
         },
     },
 }
 FoldedClass {
     name: "\\C",
     pos: Pos(root|implement_interface.php, 10:13-14),
     kind: Cclass(
         Concrete,
     ),
     is_final: true,
     substs: {
         "\\A": SubstContext {
             subst: Subst(
                 {},
             ),
             class_context: "\\C",
             from_req_extends: false,
         },
     },
     ancestors: {
         "\\A": A,
         "\\I": I,
     },
     consts: {
         "T": ClassConst {
             is_synthesized: true,
-            kind: CCConcrete,
-            pos: Pos(root|implement_interface.php, 7:23-24),
+            kind: CCAbstract(
+                false,
+            ),
+            pos: Pos(root|implement_interface.php, 4:23-24),
             ty: HH\TypeStructure<this::T>,
-            origin: "\\A",
+            origin: "\\I",
             refs: [],
         },
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|implement_interface.php, 10:13-14),
             ty: HH\classname<this>,
             origin: "\\C",
             refs: [],
         },
     },
     type_consts: {
         "T": TypeConst {
             is_synthesized: false,
             name: (
                 Pos(root|implement_interface.php, 7:23-24),
                 "T",
             ),
-            kind: ConcreteTypeconst {
-                ty: string,
+            kind: AbstractTypeconst {
+                as_constraint: None,
+                super_constraint: None,
+                default: Some(
+                    string,
+                ),
             },
             origin: "\\A",
             enforceable: None,
             reifiable: None,
-            is_concretized: true,
+            is_concretized: false,
             is_ctx: false,
         },
     },
     extends: {
         "\\A",
     },
 }
