((script 105
  ((list 105
    ((markup_section 4
      ((missing 0 ()) (() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))
       (missing 0 ())))
     (function_declaration 99
      ((missing 0 ())
       (function_declaration_header 18
        ((list 5 ((((end_of_line 1)) async 5 ((whitespace 1)))))
         (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
         (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
         (missing 0 ()) (missing 0 ()) (missing 0 ())))
       (compound_statement 80
        ((() { 1 ((end_of_line 1)))
         (list 74
          ((concurrent_statement 74
            ((((whitespace 2)) concurrent 10 ((whitespace 1)))
             (compound_statement 63
              ((() { 1 ((end_of_line 1)))
               (list 53
                ((expression_statement 38
                  ((lambda_expression 37
                    ((missing 0 ())
                     (((whitespace 4)) async 5 ((whitespace 1)))
                     (missing 0 ())
                     (lambda_signature 2
                      ((() "(" 1 ()) (missing 0 ())
                       (() ")" 1 ((whitespace 1))) (missing 0 ())
                       (missing 0 ())))
                     (() ==> 3 ((whitespace 1)))
                     (compound_statement 24
                      ((() { 1 ((end_of_line 1)))
                       (list 10
                        ((expression_statement 10
                          ((prefix_unary_expression 9
                            ((((whitespace 6)) await 5 ((whitespace 1)))
                             (function_call_expression 3
                              ((() name 1 ()) (() "(" 1 ()) (missing 0 ())
                               (() ")" 1 ())))))
                           (() ";" 1 ((end_of_line 1)))))))
                       (((whitespace 4)) } 1 ())))))
                   (() ";" 1 ((end_of_line 1)))))
                 (expression_statement 10
                  ((prefix_unary_expression 9
                    ((((whitespace 4)) await 5 ((whitespace 1)))
                     (function_call_expression 3
                      ((() name 1 ()) (() "(" 1 ()) (missing 0 ())
                       (() ")" 1 ())))))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
