=== base errors ===
No errors!
=== changed errors ===
b.php:4:26,28: The method `foo` is not compatible with the overridden method (Typing[4341])
  b.php:4:30,32: Expected `int`
  a.php:4:30,35: But got `string`
d.php:4:26,28: The method `foo` is not compatible with the overridden method (Typing[4341])
  d.php:4:30,35: Expected `string`
  b.php:4:30,32: But got `int`
use.php:4:10,11: Invalid argument (Typing[4110])
  b.php:4:30,32: Expected `int`
  use.php:4:10,11: But got `string`
=== fanout ===
Fun f
Type B
Type C
Type D
