=== base errors ===
No errors!
=== changed errors ===
b.php:2:17,17: Some members in class `B` are incompatible with those declared in type `A` (Typing[4348])
  a.php:3:9,12: Expected `bool`
  b.php:3:9,11: But got `int`
use.php:4:12,15: Invalid argument (Typing[4110])
  use.php:2:19,21: Expected `int`
  a.php:3:9,12: But got `bool`
=== fanout ===
Fun use_a_const
Fun use_b_const
Fun use_c_const
Type A
Type B
Type C
