ERROR: File "lambda_called_on_2string.php", line 3, characters 22-23:
Was expecting an array or collection but type is unknown (Typing[4297])
  File "lambda_called_on_2string.php", line 3, characters 10-11:
  It is unknown because the type of the lambda parameter could not be determined. Please add a type hint to the parameter
ERROR: File "lambda_called_on_2string.php", line 3, characters 30-31:
Was expecting an array or collection but type is unknown (Typing[4297])
  File "lambda_called_on_2string.php", line 3, characters 14-15:
  It is unknown because the type of the lambda parameter could not be determined. Please add a type hint to the parameter
