ERROR: File "lambda_called_on_2vec.php", line 3, characters 24-26:
Was expecting an array or collection but type is unknown (Typing[4297])
  File "lambda_called_on_2vec.php", line 3, characters 10-12:
  It is unknown because the type of the lambda parameter could not be determined. Please add a type hint to the parameter
ERROR: File "lambda_called_on_2vec.php", line 3, characters 33-35:
Was expecting an array or collection but type is unknown (Typing[4297])
  File "lambda_called_on_2vec.php", line 3, characters 15-17:
  It is unknown because the type of the lambda parameter could not be determined. Please add a type hint to the parameter
