[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-40], "\\array_const_mutation_immvector");
      fd_fun =
      { f_span = [3:1-6:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:62-66], (Hprim Tvoid))));
        f_params =
        [{ param_annotation = (ImmVector<int>); param_type_hint = ((ImmVector<int>), (Some ([3:41-55], (Happly (([3:41-50], "\\HH\\ImmVector"), [([3:51-54], (Hprim Tint))])))));
           param_is_variadic = false; param_pos = [3:56-58]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([5:3-19],
            (Expr
               ((float), [5:3-18],
                (Binop
                   { bop = (Eq None);
                     lhs =
                     ((float), [5:3-12],
                      (Array_get (((ImmVector<int>), [5:3-5], (Hole (((ImmVector<int>), [5:3-5], (Lvar ([5:3-5], $x))), (ImmVector<int>), (Vector<int>), Typing))), (Some ((bool), [5:6-11], False)))));
                     rhs = ((float), [5:15-18], (Float "1.0")) }))))
            ]
          };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })