[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict;
      fd_fun =
      { f_span = [3:1-6:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:67-71], (Hprim Tvoid)))); 
        f_name = ([3:10-30], "\\array_get_index_pair"); f_tparams = []; 
        f_where_constraints = []; f_variadic = FVnonVariadic;
        f_params =
        [{ param_annotation = ([3:49-52], Pair<string, int>);
           param_type_hint = ((Pair<string, int>), (Some ([3:31-48], (Happly (([3:31-35], "\\HH\\Pair"), [([3:36-42], (Hprim Tstring)); ([3:44-47], (Hprim Tint))]))))); 
           param_is_variadic = false; param_pos = [3:49-52]; param_name = "$xs"; 
           param_expr = None; param_readonly = None; param_callconv = None; 
           param_user_attributes = []; param_visibility = None };
          { param_annotation = ([3:60-64], mixed); param_type_hint = ((mixed), (Some ([3:54-59], Hmixed))); 
            param_is_variadic = false; param_pos = [3:60-64]; param_name = "$idx"; 
            param_expr = None; param_readonly = None; param_callconv = None; 
            param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([5:3-13],
            (Expr
               (([5:3-12], _),
                (Array_get ((([5:3-6], Pair<string, int>), (Lvar ([5:3-6], $xs))), (Some (([5:7-11], int), (Hole ((([5:7-11], mixed), (Lvar ([5:7-11], $idx))), (int), (int), Typing)))))))))
            ];
          fb_annotation = () };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None }
      })