[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-41], "\\array_get_index_keyed_container");
      fd_fun =
      { f_span = [3:1-9:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([6:4-8], (Hprim Tvoid))));
        f_params =
        [{ param_annotation = (KeyedContainer<string, int>);
           param_type_hint = ((KeyedContainer<string, int>), (Some ([4:3-30], (Happly (([4:3-17], "\\HH\\KeyedContainer"), [([4:18-24], (Hprim Tstring)); ([4:26-29], (Hprim Tint))])))));
           param_is_variadic = false; param_pos = [4:31-34]; param_name = "$xs"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None };
          { param_annotation = (mixed); param_type_hint = ((mixed), (Some ([5:3-8], Hmixed))); 
            param_is_variadic = false; param_pos = [5:9-13]; param_name = "$idx"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([8:3-13],
            (Expr
               ((int), [8:3-12],
                (Array_get (((KeyedContainer<string, int>), [8:3-6], (Lvar ([8:3-6], $xs))),
                   (Some ((mixed), [8:7-11], (Hole (((mixed), [8:7-11], (Lvar ([8:7-11], $idx))), (mixed), (arraykey), Typing)))))))))
            ]
          };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })