[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-35], "\\array_append_union_vector");
      fd_fun =
      { f_span = [3:1-8:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:66-70], (Hprim Tvoid))));
        f_params =
        [{ param_annotation = ((bool | Vector<string>));
           param_type_hint =
           (((bool | Vector<string>)), (Some ([3:36-59], (Hunion [([3:37-41], (Hprim Tbool)); ([3:44-58], (Happly (([3:44-50], "\\HH\\Vector"), [([3:51-57], (Hprim Tstring))])))]))));
           param_is_variadic = false; param_pos = [3:60-63]; param_name = "$xs"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([7:3-15],
            (Expr
               ((int), [7:3-14],
                (Binop
                   { bop = (Eq None);
                     lhs =
                     ((int), [7:3-10],
                      (Array_get ((((bool | Vector<string>)), [7:4-7], (Hole ((((bool | Vector<string>)), [7:4-7], (Lvar ([7:4-7], $xs))), ((bool | Vector<string>)), (Vector<string>), Typing))), None
                         )));
                     rhs = ((int), [7:13-14], (Hole (((int), [7:13-14], (Int "1")), (int), (string), Typing))) }))))
            ]
          };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([10:10-32], "\\array_append_union_vec");
       fd_fun =
       { f_span = [10:1-15:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([10:60-64], (Hprim Tvoid))));
         f_params =
         [{ param_annotation = ((bool | vec<string>));
            param_type_hint =
            (((bool | vec<string>)), (Some ([10:33-53], (Hunion [([10:34-38], (Hprim Tbool)); ([10:41-52], (Happly (([10:41-44], "\\HH\\vec"), [([10:45-51], (Hprim Tstring))])))]))));
            param_is_variadic = false; param_pos = [10:54-57]; param_name = "$xs"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([14:3-15],
             (Expr
                ((int), [14:3-14],
                 (Binop
                    { bop = (Eq None);
                      lhs =
                      ((int), [14:3-10],
                       (Array_get (
                          (((bool | vec<(int | string)>)), [14:4-7],
                           (Hole ((((bool | vec<(int | string)>)), [14:4-7], (Lvar ([14:4-7], $xs))), ((bool | vec<(int | string)>)), (vec<(int | string)>), Typing))),
                          None)));
                      rhs = ((int), [14:13-14], (Int "1")) }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })