[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-35], "\\assign_array_append_union");
      fd_fun =
      { f_span = [3:1-6:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:79-83], (Hprim Tvoid))));
        f_params =
        [{ param_annotation = ((int | string)); param_type_hint = (((int | string)), (Some ([3:36-48], (Hunion [([3:37-40], (Hprim Tint)); ([3:41-47], (Hprim Tstring))]))));
           param_is_variadic = false; param_pos = [3:49-51]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None };
          { param_annotation = (Vector<(int | bool)>);
            param_type_hint = ((Vector<(int | bool)>), (Some ([3:53-71], (Happly (([3:53-59], "\\HH\\Vector"), [([3:60-70], (Hunion [([3:61-64], (Hprim Tint)); ([3:65-69], (Hprim Tbool))]))])))));
            param_is_variadic = false; param_pos = [3:72-75]; param_name = "$xs"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([5:3-14],
            (Expr
               (((int | string)), [5:3-13],
                (Binop ((Eq None), (((int | string)), [5:3-8], (Array_get (((Vector<(int | bool)>), [5:3-6], (Lvar ([5:3-6], $xs))), None))),
                   (((int | string)), [5:11-13], (Hole ((((int | string)), [5:11-13], (Lvar ([5:11-13], $x))), ((int | string)), ((int | bool)), Typing))))))))
            ]
          };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })