[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-18], "\\variadic");
      fd_fun =
      { f_span = [3:1-49]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:42-46], (Hprim Tvoid))));
        f_params =
        [{ param_annotation = (int); param_type_hint = ((int), (Some ([3:19-22], (Hprim Tint)))); 
           param_is_variadic = false; param_pos = [3:23-25]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None };
          { param_annotation = (vec<float>); param_type_hint = ((vec<float>), (Some ([3:27-32], (Hprim Tfloat)))); 
            param_is_variadic = true; param_pos = [3:36-39]; param_name = "$xs"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([Pos.none], Noop)] }; 
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([5:10-23], "\\call_variadic");
       fd_fun =
       { f_span = [5:1-17:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([5:43-47], (Hprim Tvoid))));
         f_params =
         [{ param_annotation = (int); param_type_hint = ((int), (Some ([5:24-27], (Hprim Tint)))); 
            param_is_variadic = false; param_pos = [5:28-30]; param_name = "$x"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None };
           { param_annotation = (float); param_type_hint = ((float), (Some ([5:32-37], (Hprim Tfloat)))); 
             param_is_variadic = false; param_pos = [5:38-40]; param_name = "$y"; 
             param_expr = None; param_readonly = None; param_callconv = Pnormal; 
             param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([7:3-20],
             (Expr
                ((void), [7:3-19],
                 (Call
                    { func = (((function(int $x, float $xs...): void)), [7:3-11], (Id ([7:3-11], "\\variadic"))); 
                      targs = [];
                      args = [(Pnormal, ((int), [7:12-14], (Lvar ([7:12-14], $x)))); (Pnormal, ((int), [7:16-18], (Hole (((int), [7:16-18], (Lvar ([7:16-18], $x))), (int), (float), Typing))))];
                      unpacked_arg = None }))));
             ([10:3-24],
              (Expr
                 ((void), [10:3-23],
                  (Call
                     { func = (((function(int $x, float $xs...): void)), [10:3-11], (Id ([10:3-11], "\\variadic"))); 
                       targs = [];
                       args =
                       [(Pnormal, ((int), [10:12-14], (Lvar ([10:12-14], $x)))); (
                         Pnormal, ((float), [10:16-18], (Lvar ([10:16-18], $y)))); (
                         Pnormal, ((int), [10:20-22], (Hole (((int), [10:20-22], (Lvar ([10:20-22], $x))), (int), (float), Typing))))];
                       unpacked_arg = None }))));
             ([13:3-24],
              (Expr
                 ((void), [13:3-23],
                  (Call
                     { func = (((function(int $x, float $xs...): void)), [13:3-11], (Id ([13:3-11], "\\variadic"))); 
                       targs = [];
                       args =
                       [(Pnormal, ((int), [13:12-14], (Lvar ([13:12-14], $x)))); (
                         Pnormal, ((int), [13:16-18], (Hole (((int), [13:16-18], (Lvar ([13:16-18], $x))), (int), (float), Typing)))); (
                         Pnormal, ((float), [13:20-22], (Lvar ([13:20-22], $y))))];
                       unpacked_arg = None }))));
             ([16:3-24],
              (Expr
                 ((void), [16:3-23],
                  (Call
                     { func = (((function(int $x, float $xs...): void)), [16:3-11], (Id ([16:3-11], "\\variadic"))); 
                       targs = [];
                       args =
                       [(Pnormal, ((int), [16:12-14], (Lvar ([16:12-14], $x)))); (
                         Pnormal, ((int), [16:16-18], (Hole (((int), [16:16-18], (Lvar ([16:16-18], $x))), (int), (float), Typing))));
                         (Pnormal, ((int), [16:20-22], (Hole (((int), [16:20-22], (Lvar ([16:20-22], $x))), (int), (float), Typing))))];
                       unpacked_arg = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })