[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-20], "\\with_inout");
      fd_fun =
      { f_span = [3:1-43]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:36-40], (Hprim Tvoid))));
        f_params =
        [{ param_annotation = (int); param_type_hint = ((int), (Some ([3:27-30], (Hprim Tint)))); 
           param_is_variadic = false; param_pos = [3:31-33]; param_name = "$i"; 
           param_expr = None; param_readonly = None; param_callconv = (Pinout [3:21-26]); 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([Pos.none], Noop)] }; 
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([5:10-20], "\\call_inout");
       fd_fun =
       { f_span = [5:1-8:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([5:32-36], (Hprim Tvoid))));
         f_params =
         [{ param_annotation = (float); param_type_hint = ((float), (Some ([5:21-26], (Hprim Tfloat)))); 
            param_is_variadic = false; param_pos = [5:27-29]; param_name = "$f"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([7:3-24],
             (Expr
                ((void), [7:3-23],
                 (Call
                    { func = (((function(inout int $i): void)), [7:3-13], (Id ([7:3-13], "\\with_inout"))); 
                      targs = []; args = [((Pinout [7:14-19]), ((float), [7:20-22], (Hole (((float), [7:20-22], (Lvar ([7:20-22], $f))), (float), (int), Typing))))]; 
                      unpacked_arg = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })