[(Class
    { c_span = [3:1-5:2]; c_annotation = (); c_mode = Mstrict; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = Cnormal; 
      c_name = ([3:7-17], "\\TestVector"); c_tparams = []; c_extends = []; 
      c_uses = []; c_use_as_alias = []; c_insteadof_alias = []; c_xhp_attr_uses = []; 
      c_xhp_category = None; c_reqs = []; c_implements = []; c_support_dynamic_type = false; 
      c_where_constraints = []; c_consts = []; c_typeconsts = []; c_vars = [];
      c_methods =
      [{ m_span = [4:3-45]; m_annotation = (); m_final = false; m_abstract = false; 
         m_static = false; m_readonly_this = false; m_visibility = Public; 
         m_name = ([4:19-20], "g"); m_tparams = []; m_where_constraints = []; 
         m_variadic = FVnonVariadic;
         m_params =
         [{ param_annotation = ([4:33-35], Vector<int>); param_type_hint = ((Vector<int>), (Some ([4:21-32], (Happly (([4:21-27], "\\HH\\Vector"), [([4:28-31], (Hprim Tint))])))));
            param_is_variadic = false; param_pos = [4:33-35]; param_name = "$g"; 
            param_expr = None; param_readonly = None; param_callconv = None; 
            param_user_attributes = []; param_visibility = None }
           ];
         m_ctxs = None; m_unsafe_ctxs = None; m_body = { fb_ast = [([Pos.none], Noop)]; fb_annotation = () }; 
         m_fun_kind = FSync; m_user_attributes = []; m_readonly_ret = None; 
         m_ret = ((void), (Some ([4:38-42], (Hprim Tvoid)))); m_external = false; 
         m_doc_comment = None }
        ];
      c_attributes = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_enum = None; 
      c_doc_comment = None; c_emit_id = None });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict;
       fd_fun =
       { f_span = [7:1-36]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([7:29-33], (Hprim Tvoid)))); 
         f_name = ([7:10-11], "\\g"); f_tparams = []; f_where_constraints = []; 
         f_variadic = FVnonVariadic;
         f_params =
         [{ param_annotation = ([7:24-26], Vector<int>); param_type_hint = ((Vector<int>), (Some ([7:12-23], (Happly (([7:12-18], "\\HH\\Vector"), [([7:19-22], (Hprim Tint))])))));
            param_is_variadic = false; param_pos = [7:24-26]; param_name = "$g"; 
            param_expr = None; param_readonly = None; param_callconv = None; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([Pos.none], Noop)]; fb_annotation = () }; 
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None }
       });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict;
       fd_fun =
       { f_span = [9:1-19:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([11:4-8], (Hprim Tvoid)))); 
         f_name = ([9:10-21], "\\call_vector"); f_tparams = []; f_where_constraints = []; 
         f_variadic = FVnonVariadic;
         f_params =
         [{ param_annotation = ([10:17-19], Vector<float>); param_type_hint = ((Vector<float>), (Some ([10:3-16], (Happly (([10:3-9], "\\HH\\Vector"), [([10:10-15], (Hprim Tfloat))])))));
            param_is_variadic = false; param_pos = [10:17-19]; param_name = "$g"; 
            param_expr = None; param_readonly = None; param_callconv = None; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([13:3-9],
             (Expr
                (([13:3-8], void),
                 (Call ((([13:3-4], (function(Vector<int> $g): void)), (Id ([13:3-4], "\\g"))), 
                    [], [(([13:5-7], Vector<float>), (Hole ((([13:5-7], Vector<float>), (Lvar ([13:5-7], $g))), (Vector<float>), (Vector<int>), Typing)))], None)))));
             ([15:3-27],
              (Expr
                 (([15:3-26], TestVector),
                  (Binop ((Eq None), (([15:3-7], TestVector), (Lvar ([15:3-7], $foo))),
                     (([15:10-26], TestVector), (New ((([15:14-24], TestVector), (CI ([15:14-24], "\\TestVector"))), [], [], None, ([15:14-24], _)))))))));
             ([18:3-15],
              (Expr
                 (([18:3-14], void),
                  (Call (
                     (([18:3-10], (function(Vector<int> $g): void)),
                      (Obj_get ((([18:3-7], TestVector), (Lvar ([18:3-7], $foo))), (([18:9-10], (function(Vector<int> $g): void)), (Id ([18:9-10], "g"))), OG_nullthrows, false))),
                     [], [(([18:11-13], Vector<float>), (Hole ((([18:11-13], Vector<float>), (Lvar ([18:11-13], $g))), (Vector<float>), (Vector<int>), Typing)))], None)))))
             ];
           fb_annotation = () };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None }
       });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict;
       fd_fun =
       { f_span = [21:1-31:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([23:4-8], (Hprim Tvoid)))); 
         f_name = ([21:10-26], "\\call_vector_cast"); f_tparams = []; 
         f_where_constraints = []; f_variadic = FVnonVariadic;
         f_params =
         [{ param_annotation = ([22:17-19], Vector<float>); param_type_hint = ((Vector<float>), (Some ([22:3-16], (Happly (([22:3-9], "\\HH\\Vector"), [([22:10-15], (Hprim Tfloat))])))));
            param_is_variadic = false; param_pos = [22:17-19]; param_name = "$g"; 
            param_expr = None; param_readonly = None; param_callconv = None; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([25:3-49],
             (Expr
                (([25:3-48], void),
                 (Call ((([25:3-4], (function(Vector<int> $g): void)), (Id ([25:3-4], "\\g"))), 
                    [], [(([25:5-47], Vector<int>), (Hole ((([25:44-46], Vector<float>), (Lvar ([25:44-46], $g))), (Vector<float>), (Vector<int>), UnsafeCast)))], None)))));
             ([27:3-27],
              (Expr
                 (([27:3-26], TestVector),
                  (Binop ((Eq None), (([27:3-7], TestVector), (Lvar ([27:3-7], $foo))),
                     (([27:10-26], TestVector), (New ((([27:14-24], TestVector), (CI ([27:14-24], "\\TestVector"))), [], [], None, ([27:14-24], _)))))))));
             ([30:3-55],
              (Expr
                 (([30:3-54], void),
                  (Call (
                     (([30:3-10], (function(Vector<int> $g): void)),
                      (Obj_get ((([30:3-7], TestVector), (Lvar ([30:3-7], $foo))), (([30:9-10], (function(Vector<int> $g): void)), (Id ([30:9-10], "g"))), OG_nullthrows, false))),
                     [], [(([30:11-53], Vector<int>), (Hole ((([30:50-52], Vector<float>), (Lvar ([30:50-52], $g))), (Vector<float>), (Vector<int>), UnsafeCast)))], None)))))
             ];
           fb_annotation = () };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None }
       })