[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict;
      fd_fun =
      { f_span = [3:1-49]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:42-46], (Hprim Tvoid)))); 
        f_name = ([3:10-18], "\\variadic"); f_tparams = []; f_where_constraints = [];
        f_variadic =
        (FVvariadicArg
           { param_annotation = ([3:36-39], vec<float>); param_type_hint = ((vec<float>), (Some ([3:27-32], (Hprim Tfloat)))); 
             param_is_variadic = true; param_pos = [3:36-39]; param_name = "$xs"; 
             param_expr = None; param_readonly = None; param_callconv = None; 
             param_user_attributes = []; param_visibility = None });
        f_params =
        [{ param_annotation = ([3:23-25], int); param_type_hint = ((int), (Some ([3:19-22], (Hprim Tint)))); 
           param_is_variadic = false; param_pos = [3:23-25]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = None; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([Pos.none], Noop)]; fb_annotation = () }; 
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None }
      });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict;
       fd_fun =
       { f_span = [5:1-17:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([5:43-47], (Hprim Tvoid)))); 
         f_name = ([5:10-23], "\\call_variadic"); f_tparams = []; f_where_constraints = []; 
         f_variadic = FVnonVariadic;
         f_params =
         [{ param_annotation = ([5:28-30], int); param_type_hint = ((int), (Some ([5:24-27], (Hprim Tint)))); 
            param_is_variadic = false; param_pos = [5:28-30]; param_name = "$x"; 
            param_expr = None; param_readonly = None; param_callconv = None; 
            param_user_attributes = []; param_visibility = None };
           { param_annotation = ([5:38-40], float); param_type_hint = ((float), (Some ([5:32-37], (Hprim Tfloat)))); 
             param_is_variadic = false; param_pos = [5:38-40]; param_name = "$y"; 
             param_expr = None; param_readonly = None; param_callconv = None; 
             param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([7:3-20],
             (Expr
                (([7:3-19], void),
                 (Call ((([7:3-11], (function(int $x, float $xs...): void)), (Id ([7:3-11], "\\variadic"))), 
                    [], [(([7:12-14], int), (Lvar ([7:12-14], $x))); (([7:16-18], int), (Hole ((([7:16-18], int), (Lvar ([7:16-18], $x))), (int), (float), Typing)))], None)))));
             ([10:3-24],
              (Expr
                 (([10:3-23], void),
                  (Call ((([10:3-11], (function(int $x, float $xs...): void)), (Id ([10:3-11], "\\variadic"))), 
                     [],
                     [(([10:12-14], int), (Lvar ([10:12-14], $x))); (
                       ([10:16-18], float), (Lvar ([10:16-18], $y))); (
                       ([10:20-22], int), (Hole ((([10:20-22], int), (Lvar ([10:20-22], $x))), (int), (float), Typing)))],
                     None)))));
             ([13:3-24],
              (Expr
                 (([13:3-23], void),
                  (Call ((([13:3-11], (function(int $x, float $xs...): void)), (Id ([13:3-11], "\\variadic"))), 
                     [],
                     [(([13:12-14], int), (Lvar ([13:12-14], $x))); (
                       ([13:16-18], int), (Hole ((([13:16-18], int), (Lvar ([13:16-18], $x))), (int), (float), Typing))); (
                       ([13:20-22], float), (Lvar ([13:20-22], $y)))],
                     None)))));
             ([16:3-24],
              (Expr
                 (([16:3-23], void),
                  (Call ((([16:3-11], (function(int $x, float $xs...): void)), (Id ([16:3-11], "\\variadic"))), 
                     [],
                     [(([16:12-14], int), (Lvar ([16:12-14], $x))); (
                       ([16:16-18], int), (Hole ((([16:16-18], int), (Lvar ([16:16-18], $x))), (int), (float), Typing)));
                       (([16:20-22], int), (Hole ((([16:20-22], int), (Lvar ([16:20-22], $x))), (int), (float), Typing)))],
                     None)))))
             ];
           fb_annotation = () };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None }
       })