[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-25], "\\generic_bounded");
      fd_fun =
      { f_span = [3:1-56]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:49-53], (Hprim Tvoid))));
        f_params =
        [{ param_annotation = (T); param_type_hint = ((T), (Some ([3:36-37], (Habstr ("T", []))))); 
           param_is_variadic = false; param_pos = [3:38-40]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None };
          { param_annotation = (T); param_type_hint = ((T), (Some ([3:42-43], (Habstr ("T", []))))); 
            param_is_variadic = false; param_pos = [3:44-46]; param_name = "$y"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([Pos.none], Noop)] }; 
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None;
      fd_tparams =
      [{ tp_variance = Invariant; tp_name = ([3:26-27], "T"); tp_parameters = []; tp_constraints = [(Constraint_as, ([3:31-34], (Hprim Tnum)))]; tp_reified = Erased; tp_user_attributes = [] }];
      fd_where_constraints = [] });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([5:10-22], "\\call_generic");
       fd_fun =
       { f_span = [5:1-8:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([5:43-47], (Hprim Tvoid))));
         f_params =
         [{ param_annotation = (int); param_type_hint = ((int), (Some ([5:23-26], (Hprim Tint)))); 
            param_is_variadic = false; param_pos = [5:27-29]; param_name = "$x"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None };
           { param_annotation = (string); param_type_hint = ((string), (Some ([5:31-37], (Hprim Tstring)))); 
             param_is_variadic = false; param_pos = [5:38-40]; param_name = "$y"; 
             param_expr = None; param_readonly = None; param_callconv = Pnormal; 
             param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([7:3-27],
             (Expr
                ((void), [7:3-26],
                 (Call
                    { func = (((function<T as num>(int $x, int $y): void)), [7:3-18], (Id ([7:3-18], "\\generic_bounded"))); 
                      targs = [((int), ([7:3-18], Hwildcard))];
                      args = [(Pnormal, ((int), [7:19-21], (Lvar ([7:19-21], $x)))); (Pnormal, ((string), [7:23-25], (Hole (((string), [7:23-25], (Lvar ([7:23-25], $y))), (string), (int), Typing))))];
                      unpacked_arg = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([10:10-27], "\\call_generic_cast");
       fd_fun =
       { f_span = [10:1-13:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([10:48-52], (Hprim Tvoid))));
         f_params =
         [{ param_annotation = (int); param_type_hint = ((int), (Some ([10:28-31], (Hprim Tint)))); 
            param_is_variadic = false; param_pos = [10:32-34]; param_name = "$x"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None };
           { param_annotation = (string); param_type_hint = ((string), (Some ([10:36-42], (Hprim Tstring)))); 
             param_is_variadic = false; param_pos = [10:43-45]; param_name = "$y"; 
             param_expr = None; param_readonly = None; param_callconv = Pnormal; 
             param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([12:3-64],
             (Expr
                ((void), [12:3-63],
                 (Call
                    { func = (((function<T as num>(num $x, num $y): void)), [12:3-18], (Id ([12:3-18], "\\generic_bounded"))); 
                      targs = [((num), ([12:3-18], Hwildcard))];
                      args =
                      [(Pnormal, ((int), [12:19-21], (Lvar ([12:19-21], $x))));
                        (Pnormal,
                         ((float), [12:23-62], (Hole (((string), [12:59-61], (Lvar ([12:59-61], $y))), (string), (float), (UnsafeCast [([12:45-51], (Hprim Tstring)); ([12:52-57], (Hprim Tfloat))])))))
                        ];
                      unpacked_arg = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })