[(Class
    { c_span = [3:1-5:2]; c_annotation = (); c_mode = Mstrict; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
      c_name = ([3:7-21], "\\TestCollection"); c_tparams = []; c_extends = []; 
      c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; 
      c_implements = []; c_where_constraints = []; c_consts = []; c_typeconsts = []; 
      c_vars = [];
      c_methods =
      [{ m_span = [4:3-49]; m_annotation = (); m_final = false; m_abstract = false; 
         m_static = false; m_readonly_this = false; m_visibility = Public; 
         m_name = ([4:19-20], "l"); m_tparams = []; m_where_constraints = [];
         m_params =
         [{ param_annotation = (Collection<int>); param_type_hint = ((Collection<int>), (Some ([4:21-36], (Happly (([4:21-31], "\\HH\\Collection"), [([4:32-35], (Hprim Tint))])))));
            param_is_variadic = false; param_pos = [4:37-39]; param_name = "$l"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
           ];
         m_ctxs = None; m_unsafe_ctxs = None; m_body = { fb_ast = [([Pos.none], Noop)] }; 
         m_fun_kind = FSync; m_user_attributes = []; m_readonly_ret = None; 
         m_ret = ((void), (Some ([4:42-46], (Hprim Tvoid)))); m_external = false; 
         m_doc_comment = None }
        ];
      c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_docs_url = None; 
      c_enum = None; c_doc_comment = None; c_emit_id = None; c_internal = false; 
      c_module = None });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([7:10-11], "\\l");
       fd_fun =
       { f_span = [7:1-40]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([7:33-37], (Hprim Tvoid))));
         f_params =
         [{ param_annotation = (Collection<int>); param_type_hint = ((Collection<int>), (Some ([7:12-27], (Happly (([7:12-22], "\\HH\\Collection"), [([7:23-26], (Hprim Tint))])))));
            param_is_variadic = false; param_pos = [7:28-30]; param_name = "$l"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([Pos.none], Noop)] }; 
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([9:10-25], "\\call_collection");
       fd_fun =
       { f_span = [9:1-19:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([11:4-8], (Hprim Tvoid))));
         f_params =
         [{ param_annotation = (Collection<string>); param_type_hint = ((Collection<string>), (Some ([10:3-21], (Happly (([10:3-13], "\\HH\\Collection"), [([10:14-20], (Hprim Tstring))])))));
            param_is_variadic = false; param_pos = [10:22-24]; param_name = "$l"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([13:3-9],
             (Expr
                ((void), [13:3-8],
                 (Call
                    { func = (((function(Collection<int> $l): void)), [13:3-4], (Id ([13:3-4], "\\l"))); 
                      targs = [];
                      args = [(Pnormal, ((Collection<string>), [13:5-7], (Hole (((Collection<string>), [13:5-7], (Lvar ([13:5-7], $l))), (Collection<string>), (Collection<int>), Typing))))];
                      unpacked_arg = None }))));
             ([15:3-31],
              (Expr
                 ((TestCollection), [15:3-30],
                  (Binop
                     { bop = (Eq None); lhs = ((TestCollection), [15:3-7], (Lvar ([15:3-7], $foo)));
                       rhs = ((TestCollection), [15:10-30], (New (((TestCollection), [15:14-28], (CI ([15:14-28], "\\TestCollection"))), [], [], None, ((function(): void))))) }))));
             ([18:3-15],
              (Expr
                 ((void), [18:3-14],
                  (Call
                     { func =
                       (((function(Collection<int> $l): void)), [18:3-10],
                        (Obj_get (((TestCollection), [18:3-7], (Lvar ([18:3-7], $foo))), (((function(Collection<int> $l): void)), [18:9-10], (Id ([18:9-10], "l"))), OG_nullthrows, Is_method)));
                       targs = [];
                       args = [(Pnormal, ((Collection<string>), [18:11-13], (Hole (((Collection<string>), [18:11-13], (Lvar ([18:11-13], $l))), (Collection<string>), (Collection<int>), Typing))))];
                       unpacked_arg = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([21:10-30], "\\call_collection_cast");
       fd_fun =
       { f_span = [21:1-31:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([23:4-8], (Hprim Tvoid))));
         f_params =
         [{ param_annotation = (Collection<string>); param_type_hint = ((Collection<string>), (Some ([22:3-21], (Happly (([22:3-13], "\\HH\\Collection"), [([22:14-20], (Hprim Tstring))])))));
            param_is_variadic = false; param_pos = [22:22-24]; param_name = "$l"; 
            param_expr = None; param_readonly = None; param_callconv = Pnormal; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([25:3-68],
             (Expr
                ((void), [25:3-67],
                 (Call
                    { func = (((function(Collection<int> $l): void)), [25:3-4], (Id ([25:3-4], "\\l"))); 
                      targs = [];
                      args =
                      [(Pnormal,
                        ((Collection<int>), [25:5-66],
                         (Hole (((Collection<string>), [25:63-65], (Lvar ([25:63-65], $l))), (Collection<string>), (Collection<int>),
                            (UnsafeCast
                               [([25:27-45], (Happly (([25:27-37], "\\HH\\Collection"), [([25:38-44], (Hprim Tstring))])));
                                 ([25:46-61], (Happly (([25:46-56], "\\HH\\Collection"), [([25:57-60], (Hprim Tint))])))])
                            ))))
                        ];
                      unpacked_arg = None }))));
             ([27:3-31],
              (Expr
                 ((TestCollection), [27:3-30],
                  (Binop
                     { bop = (Eq None); lhs = ((TestCollection), [27:3-7], (Lvar ([27:3-7], $foo)));
                       rhs = ((TestCollection), [27:10-30], (New (((TestCollection), [27:14-28], (CI ([27:14-28], "\\TestCollection"))), [], [], None, ((function(): void))))) }))));
             ([30:3-74],
              (Expr
                 ((void), [30:3-73],
                  (Call
                     { func =
                       (((function(Collection<int> $l): void)), [30:3-10],
                        (Obj_get (((TestCollection), [30:3-7], (Lvar ([30:3-7], $foo))), (((function(Collection<int> $l): void)), [30:9-10], (Id ([30:9-10], "l"))), OG_nullthrows, Is_method)));
                       targs = [];
                       args =
                       [(Pnormal,
                         ((Collection<int>), [30:11-72],
                          (Hole (((Collection<string>), [30:69-71], (Lvar ([30:69-71], $l))), (Collection<string>), (Collection<int>),
                             (UnsafeCast
                                [([30:33-51], (Happly (([30:33-43], "\\HH\\Collection"), [([30:44-50], (Hprim Tstring))])));
                                  ([30:52-67], (Happly (([30:52-62], "\\HH\\Collection"), [([30:63-66], (Hprim Tint))])))])
                             ))))
                         ];
                       unpacked_arg = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })