[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-39], "\\non_object_member_read_method");
      fd_fun =
      { f_span = [3:1-6:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:55-59], (Hprim Tvoid))));
        f_params =
        [{ param_annotation = (nonnull); param_type_hint = ((nonnull), (Some ([3:40-47], Hnonnull))); 
           param_is_variadic = false; param_pos = [3:48-51]; param_name = "$xs"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([5:3-12],
            (Expr
               ((nothing), [5:3-11],
                (Call (
                   ((nothing), [5:3-9],
                    (Obj_get (((nonnull), [5:3-6], (Hole (((nonnull), [5:3-6], (Lvar ([5:3-6], $xs))), (nonnull), (nothing), Typing))), (
                       (nothing), [5:8-9], (Id ([5:8-9], "c"))), OG_nullthrows, Is_method))),
                   [], [], None)))))
            ]
          };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })