[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:16-28], "\\async_return");
      fd_fun =
      { f_span = [3:1-6:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((Awaitable<~int>), (Some ([3:32-46], (Happly (([3:32-41], "\\HH\\Awaitable"), [([3:42-45], (Hprim Tint))]))))); 
        f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
        f_body = { fb_ast = [([5:3-14], (Return (Some ((string), [5:10-13], (Hole (((string), [5:10-13], (String "3")), (string), (~int), Typing))))))] }; 
        f_fun_kind = FAsync; f_user_attributes = [{ ua_name = ([3:16-28], "__SupportDynamicType"); ua_params = [] }]; 
        f_external = false; f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })