File "generics.php--file2.php", line 68, characters 3-13:
  exact A<int>
File "generics.php--file2.php", line 71, characters 3-13:
  exact A<[unresolved]>
File "generics.php--file2.php", line 74, characters 3-13:
  exact A<int>
File "generics.php--file2.php", line 77, characters 3-13:
  exact B<int>
File "generics.php--file2.php", line 80, characters 3-13:
  exact B<int>
File "generics.php--file2.php", line 83, characters 3-13:
  A<int>
File "generics.php--file2.php", line 86, characters 3-13:
  A<int>
File "generics.php--file2.php", line 89, characters 3-13:
  A<T>
File "generics.php--file2.php", line 92, characters 3-13:
  (exact A<int> | A<T>)
File "generics.php--file2.php", line 95, characters 3-13:
  (A<int> | A<T>)
File "generics.php--file2.php", line 98, characters 3-13:
  A<T>
File "generics.php--file2.php", line 101, characters 3-13:
  (exact A<int> | exact A<string>)
File "generics.php--file2.php", line 102, characters 3-35:
  bool
File "generics.php--file2.php", line 105, characters 3-13:
  (exact A<num> | exact A<arraykey>)
File "generics.php--file2.php", line 106, characters 3-34:
  bool
File "generics.php--file2.php", line 109, characters 3-13:
  (exact A<int> | exact B<int>)
File "generics.php--file2.php", line 110, characters 3-25:
  bool
File "generics.php--file2.php", line 113, characters 3-13:
  D<(int | string)>
File "generics.php--file2.php", line 116, characters 3-13:
  exact D<(int | string)>
File "generics.php--file2.php", line 119, characters 3-13:
  D<(int | string)>
File "generics.php--file2.php", line 122, characters 3-13:
  E<int>
File "generics.php--file2.php", line 125, characters 3-13:
  (E<int> | E<string>)
File "generics.php--file2.php", line 128, characters 3-13:
  F<(int | string)>
File "generics.php--file2.php", line 131, characters 3-13:
  classname<C>
File "generics.php--file2.php", line 134, characters 3-13:
  (Tu | C)
  where Tu super \C
File "generics.php--file2.php", line 137, characters 3-13:
  (Tv | C)
  where Tv as \C
File "generics.php--file2.php", line 140, characters 3-13:
  (Tu | Tv)
  where Tu super \C, Tv as \C
File "generics.php--file2.php", line 143, characters 3-13:
  (Tu | Tw)
  where Tu super \C, Tw super \C
File "generics.php--file2.php", line 146, characters 3-13:
  (Tv | Ty)
  where Tv as \C, Ty as \C
File "generics.php--file2.php", line 22, characters 5-15:
  ?int
File "generics.php--file2.php", line 25, characters 5-15:
  ?(int | AA::Tabs)
File "generics.php--file2.php", line 28, characters 5-15:
  (int | AA::Tcstr)
  where \AA::Tcstr as int
File "generics.php--file2.php", line 31, characters 5-15:
  ?(int | AA::Tcstr)
  where \AA::Tcstr as int
File "generics.php--file2.php", line 102, characters 32-33:
Invalid argument (Typing[4110])
  File "generics.php--file2.php", line 100, characters 20-22:
  This is an int
  File "generics.php--file2.php", line 16, characters 36-36:
    via this generic T
  File "generics.php--file2.php", line 102, characters 32-33:
  It is incompatible with a string
