Analyzing \binop:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<\Exception, lump>
* Params:
  lvars: { $x -> <$x>; $y -> <$y> }
* Final environment:
  Deps: {}
  Locals:
    lvars: { $x -> <$x>; $y -> <$y> }
Constraints:
  [$x < bop, lit < bop, bop < ret]

Analyzing \assign0:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<\Exception, lump>
* Params:
  lvars: { $arg -> <$arg> }
* Final environment:
  Deps: {}
  Locals:
    lvars: { $arg -> <$arg>; $x -> <$x'1> }
Constraints:
  [$arg < $x, lit < $x'1, $x'1 < ret]

Analyzing \assign1:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<\Exception, lump>
* Params:
  lvars: { $arg -> <$arg> }
* Final environment:
  Deps: {}
  Locals:
    lvars: { $arg -> <$arg>; $x -> <$x'1> }
Constraints:
  [$arg < $x, $x < bop, lit < bop, bop < $x'1, $x'1 < ret]

Analyzing \condition:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<\Exception, lump>
* Params:
  lvars: { $a0 -> <$a0>; $a1 -> <$a1>; $a2 -> <$a2> }
* Final environment:
  Deps: {}
  Locals:
    lvars: { $a0 -> <$a0>; $a1 -> <$a1>; $a2 -> <$a2>; $x -> <$x'2> }
Constraints:
  [$a2 < bop, lit < bop, bop < $x, $a0 < $x, bop < $x'1, $a1 < $x'1,
   $x < $x'2, $x'1 < $x'2, $x'2 < ret]

