=== IFC analysis results for default_args.php
Analyzing __construct:
* pc: pc
* This: \C<C, C_lump>
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $i -> <$i>; $j -> <$j> }
* Final environment:
  Deps: {}
  Constraints:
    [5:42-44] C < C_lump, pc < C_lump, $i < C_lump
    [5:57-59] C < C_lump, pc < C_lump, $j < C_lump
  Locals:
    { $i -> <$i>; $j -> <$j> }

Analyzing \constructor_with_default_omitted:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $x -> <$x> }
* Final environment:
  Deps: { "\\C#__construct" }
  Constraints:
    [no pos]
      {(this: \C<C, C_lump>)->\C#__construct<pcjoin, C#__construct_self>(<$x>): <v> [\Exception<C#__construct_exn,
                                                                    C#__construct_exn_lump>]}
    [10:3-13]
      C#__construct_self < v, C#__construct_exn_lump = exn_lump,
      C#__construct_exn < exn, C#__construct_exn < exn,
      C#__construct_exn < pcjoin, pc < pcjoin
  Locals:
    { $x -> <$x> }
    pc: C#__construct_exn

Analyzing \constructor_with_default_supplied:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $x -> <$x>; $y -> <$y> }
* Final environment:
  Deps: { "\\C#__construct" }
  Constraints:
    [no pos]
      {(this: \C<C, C_lump>)->\C#__construct<pcjoin, C#__construct_self>(<$x>,
                                                                    <$y>): <v> [\Exception<C#__construct_exn,
                                                                    C#__construct_exn_lump>]}
    [15:3-17]
      C#__construct_self < v, C#__construct_exn_lump = exn_lump,
      C#__construct_exn < exn, C#__construct_exn < exn,
      C#__construct_exn < pcjoin, pc < pcjoin
  Locals:
    { $x -> <$x>; $y -> <$y> }
    pc: C#__construct_exn

Analyzing \f:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $i -> <$i>; $j -> <$j> }
* Final environment:
  Deps: {}
  Constraints:
    
  Locals:
    { $i -> <$i>; $j -> <$j> }

Analyzing \function_with_default_omitted:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $x -> <$x> }
* Final environment:
  Deps: { "\\f" }
  Constraints:
    [no pos]
      {\f<pcjoin, f_self>(<$x>): <ret'1> [\Exception<f_exn, f_exn_lump>]}
    [23:3-9]
      f_self < ret'1, exn_lump = f_exn_lump, f_exn < exn, f_exn < exn,
      f_exn < pcjoin, pc < pcjoin
  Locals:
    { $x -> <$x> }
    pc: f_exn

