=== IFC analysis results for for.php
Analyzing \test_constraints:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  {}
* Final environment:
  Deps: {}
  Constraints:
    [4:8-14] lit < $i
    [5:8-15]
      HH\Capabilities\WriteProperty_lump = HH\Capabilities\WriteProperty_lump'1,
      HH\Capabilities\WriteProperty < HH\Capabilities\WriteProperty'1,
      HH\Capabilities\AccessGlobals_lump'1 = HH\Capabilities\WriteProperty_lump,
      HH\Capabilities\WriteProperty < HH\Capabilities\AccessGlobals'1,
      HH\Capabilities\RxLocal_lump'1 = HH\Capabilities\WriteProperty_lump,
      HH\Capabilities\WriteProperty < HH\Capabilities\RxLocal'1,
      HH\Capabilities\ImplicitPolicyLocal_lump'1 = HH\Capabilities\WriteProperty_lump,
      HH\Capabilities\WriteProperty < HH\Capabilities\ImplicitPolicyLocal'1,
      HH\Capabilities\IO_lump'1 = HH\Capabilities\WriteProperty_lump,
      HH\Capabilities\WriteProperty < HH\Capabilities\IO'1,
      HH\Capabilities\WriteProperty_lump'2 = HH\Capabilities\WriteProperty_lump'3,
      HH\Capabilities\WriteProperty'2 < HH\Capabilities\WriteProperty'3,
      HH\Capabilities\AccessGlobals_lump'3 = HH\Capabilities\WriteProperty_lump'2,
      HH\Capabilities\WriteProperty'2 < HH\Capabilities\AccessGlobals'3,
      HH\Capabilities\RxLocal_lump'3 = HH\Capabilities\WriteProperty_lump'2,
      HH\Capabilities\WriteProperty'2 < HH\Capabilities\RxLocal'3,
      HH\Capabilities\ImplicitPolicyLocal_lump'3 = HH\Capabilities\WriteProperty_lump'2,
      HH\Capabilities\WriteProperty'2 < HH\Capabilities\ImplicitPolicyLocal'3,
      HH\Capabilities\IO_lump'3 = HH\Capabilities\WriteProperty_lump'2,
      HH\Capabilities\WriteProperty'2 < HH\Capabilities\IO'3, $i < $i'1,
      $i'1 < cmp, lit'1 < cmp,
      HH\Capabilities\WriteProperty_lump'1 = HH\Capabilities\WriteProperty_lump'1,
      HH\Capabilities\AccessGlobals_lump'1 = HH\Capabilities\WriteProperty_lump'1,
      HH\Capabilities\WriteProperty'1 < HH\Capabilities\AccessGlobals'1,
      HH\Capabilities\RxLocal_lump'1 = HH\Capabilities\WriteProperty_lump'1,
      HH\Capabilities\WriteProperty'1 < HH\Capabilities\RxLocal'1,
      HH\Capabilities\ImplicitPolicyLocal_lump'1 = HH\Capabilities\WriteProperty_lump'1,
      HH\Capabilities\WriteProperty'1 < HH\Capabilities\ImplicitPolicyLocal'1,
      HH\Capabilities\IO_lump'1 = HH\Capabilities\WriteProperty_lump'1,
      HH\Capabilities\WriteProperty'1 < HH\Capabilities\IO'1,
      HH\Capabilities\WriteProperty_lump'3 = HH\Capabilities\WriteProperty_lump'3,
      HH\Capabilities\AccessGlobals_lump'3 = HH\Capabilities\WriteProperty_lump'3,
      HH\Capabilities\WriteProperty'3 < HH\Capabilities\AccessGlobals'3,
      HH\Capabilities\RxLocal_lump'3 = HH\Capabilities\WriteProperty_lump'3,
      HH\Capabilities\WriteProperty'3 < HH\Capabilities\RxLocal'3,
      HH\Capabilities\ImplicitPolicyLocal_lump'3 = HH\Capabilities\WriteProperty_lump'3,
      HH\Capabilities\WriteProperty'3 < HH\Capabilities\ImplicitPolicyLocal'3,
      HH\Capabilities\IO_lump'3 = HH\Capabilities\WriteProperty_lump'3,
      HH\Capabilities\WriteProperty'3 < HH\Capabilities\IO'3, $i'2 < $i'1
    [6:8-12] cmp < $i'2, $i'1 < $i'2
  Locals:
    { $#capability ->
      (\HH\Capabilities\WriteProperty<HH\Capabilities\WriteProperty'1,
                                        HH\Capabilities\WriteProperty_lump'1> &
         \HH\Capabilities\AccessGlobals<HH\Capabilities\AccessGlobals'1,
                                          HH\Capabilities\AccessGlobals_lump'1> &
         \HH\Capabilities\RxLocal<HH\Capabilities\RxLocal'1,
                                    HH\Capabilities\RxLocal_lump'1> &
         \HH\Capabilities\ImplicitPolicyLocal<HH\Capabilities\ImplicitPolicyLocal'1,
                                                HH\Capabilities\ImplicitPolicyLocal_lump'1> &
         \HH\Capabilities\IO<HH\Capabilities\IO'1, HH\Capabilities\IO_lump'1>);
      $#local_capability ->
      (\HH\Capabilities\WriteProperty<HH\Capabilities\WriteProperty'3,
                                        HH\Capabilities\WriteProperty_lump'3> &
         \HH\Capabilities\AccessGlobals<HH\Capabilities\AccessGlobals'3,
                                          HH\Capabilities\AccessGlobals_lump'3> &
         \HH\Capabilities\RxLocal<HH\Capabilities\RxLocal'3,
                                    HH\Capabilities\RxLocal_lump'3> &
         \HH\Capabilities\ImplicitPolicyLocal<HH\Capabilities\ImplicitPolicyLocal'3,
                                                HH\Capabilities\ImplicitPolicyLocal_lump'3> &
         \HH\Capabilities\IO<HH\Capabilities\IO'3, HH\Capabilities\IO_lump'3>);
      $i -> <$i'1> }

