=== IFC analysis results for higher_order_functions.php
Analyzing \apply:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $f -> <pc'1, $f'2>(<$f'1>): <$f> [\Exception<Exception, Exception_lump>] }
* Final environment:
  Deps: {}
  Constraints:
    [6:3-16]
      anonymous_self < ret'1, anonymous_exn_lump = exn_lump,
      anonymous_exn < exn, anonymous_exn < exn, anonymous_exn < pcjoin,
      pc < pcjoin, lit < $f'1, pcjoin < pc'1, $f'2 < anonymous_self,
      $f < ret'1, Exception_lump = anonymous_exn_lump,
      Exception < anonymous_exn, ret'1 < ret, anonymous_exn < ret
  Locals:
    { $f -> <pc'1, $f'2>(<$f'1>):
      <$f> [\Exception<Exception, Exception_lump>] }
    pc: anonymous_exn

