=== IFC analysis results for nominal_subtyping.php
Analyzing __construct:
* pc: pc
* This: \D<D, D_lump>
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $pd -> <$pd> }
* Final environment:
  Deps: {}
  Constraints:
    [6:16-19] D < PD, pc < PD, $pd < PD
  Locals:
    { $pd -> <$pd> }

Analyzing __construct:
* pc: pc
* This: \E<E, E_lump>
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $pd -> <$pd>; $pe -> <$pe> }
* Final environment:
  Deps: { "\\D#__construct" }
  Constraints:
    [no pos]
      {(this: \E<E, E_lump>)->\D#__construct<pcjoin'1, D#__construct_self>(<$pd>): <D#__construct_ret> [\Exception<D#__construct_exn,
                                                                    D#__construct_exn_lump>]}
    [12:16-19] E < PD, pc < PD, $pd < PD
    [14:16-19] E < PE, pc < PE, $pe < PE
    [16:5-30]
      D#__construct_self < D#__construct_ret,
      D#__construct_exn_lump = exn_lump, D#__construct_exn < exn,
      D#__construct_exn < exn, D#__construct_self < pcjoin,
      D#__construct_exn < pcjoin, pcjoin < pcjoin'1, pc < pcjoin'1
  Locals:
    { $pd -> <$pd>; $pe -> <$pe> }
    pc: D#__construct_exn

Analyzing \testPoliciedPropertiesED:
* pc: pc
* This: None
* Return: \D<D, D_lump>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $e -> \E<E, E_lump> }
* Final environment:
  Deps: {}
  Constraints:
    [20:46-56] D_lump = E_lump, E < D
  Locals:
    { $e -> \E<E, E_lump> }

Analyzing __construct:
* pc: pc
* This: \F<F, F_lump>
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $pd -> <$pd>; $pe -> <$pe>; $pf -> <$pf> }
* Final environment:
  Deps: { "\\E#__construct" }
  Constraints:
    [no pos]
      {(this: \F<F, F_lump>)->\E#__construct<pcjoin'1, E#__construct_self>(<$pd>,
                                                                    <$pe>): <E#__construct_ret> [\Exception<E#__construct_exn,
                                                                    E#__construct_exn_lump>]}
    [24:16-19] F < PD, pc < PD, $pd < PD
    [25:16-19] F < PE, pc < PE, $pe < PE
    [27:16-19] F < PF, pc < PF, $pf < PF
    [29:5-35]
      E#__construct_self < E#__construct_ret,
      E#__construct_exn_lump = exn_lump, E#__construct_exn < exn,
      E#__construct_exn < exn, E#__construct_self < pcjoin,
      E#__construct_exn < pcjoin, pcjoin < pcjoin'1, pc < pcjoin'1
  Locals:
    { $pd -> <$pd>; $pe -> <$pe>; $pf -> <$pf> }
    pc: E#__construct_exn

Analyzing \testPoliciedPropertiesFE:
* pc: pc
* This: None
* Return: \E<E, E_lump>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $f -> \F<F, F_lump> }
* Final environment:
  Deps: {}
  Constraints:
    [33:46-56] E_lump = F_lump, F < E
  Locals:
    { $f -> \F<F, F_lump> }

Analyzing \testPoliciedPropertiesFD:
* pc: pc
* This: None
* Return: \D<D, D_lump>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $f -> \F<F, F_lump> }
* Final environment:
  Deps: {}
  Constraints:
    [34:46-56] D_lump = F_lump, F < D
  Locals:
    { $f -> \F<F, F_lump> }

