=== IFC analysis results for recursive_class.php
Analyzing __construct:
* pc: pc
* This: \R<R, R_lump>
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $prop -> <$prop>; $r -> \R<R'1, R_lump'1> }
* Final environment:
  Deps: {}
  Constraints:
    [6:16-21] R < R_lump, pc < R_lump, $prop < R_lump
    [7:14-16] R < R_lump, pc < R_lump, R_lump = R_lump'1, R'1 < R_lump
  Locals:
    { $prop -> <$prop>; $r -> \R<R'1, R_lump'1> }

Analyzing recursiveGet:
* pc: pc
* This: \R<R, R_lump>
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  {}
* Final environment:
  Deps: {}
  Constraints:
    [12:5-33]
      R_lump < .r, R < .r, R_lump < .r'1, .r < .r'1, R_lump < .r'2,
      .r'1 < .r'2, R_lump < .prop, .r'2 < .prop, .prop < ret
  Locals:
    {}

Analyzing recursiveWrite:
* pc: pc
* This: \R<R, R_lump>
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  {}
* Final environment:
  Deps: {}
  Constraints:
    [17:5-31]
      R_lump < .r, R < .r, R_lump < .r'1, .r < .r'1, R_lump < .r'2,
      .r'1 < .r'2, .r'2 < R_lump, pc < R_lump, lit < R_lump
  Locals:
    {}

