=== IFC analysis results for tuple.php
Analyzing \triple:
* pc: pc
* This: None
* Return: (<ret>, <ret'1>, \C<C, C_lump>)
* Exception: \Exception<exn, exn_lump>
* Params:
  { $c -> \C<C'1, C_lump'1>; $i -> <$i> }
* Final environment:
  Deps: {}
  Constraints:
    [6:3-33] $i < ret, lit < ret'1, C_lump = C_lump'1, C'1 < C
  Locals:
    { $c -> \C<C'1, C_lump'1>; $i -> <$i> }

Analyzing \nested:
* pc: pc
* This: None
* Return: (<ret>, (<ret'1>, \C<C, C_lump>))
* Exception: \Exception<exn, exn_lump>
* Params:
  { $c -> \C<C'1, C_lump'1>; $i -> <$i> }
* Final environment:
  Deps: {}
  Constraints:
    [10:3-40] $i < ret, lit < ret'1, C_lump = C_lump'1, C'1 < C
  Locals:
    { $c -> \C<C'1, C_lump'1>; $i -> <$i> }

