=== IFC analysis results for vec_element_union_by_assignment.php
Analyzing \testClass:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $v -> vec<<key> => <$v>; |len|>; $x -> \A<A, A_lump> }
* Final environment:
  Deps: {}
  Constraints:
    [6:3-13]
      key < key'1, $v < arr, len < len'1, A_lump = A_lump'1, A < A'1,
      key'1 < key'2, arr < $v'1, A_lump'1 = A_lump'2, A'1 < A'2,
      len'1 < len'2
  Locals:
    { $v -> vec<<key'2> => (<$v'1> | \A<A'2, A_lump'2>); |len'2|>;
      $x -> \A<A, A_lump> }

Analyzing \testPrim:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<exn, exn_lump>
* Params:
  { $v -> vec<<key> => <$v>; |len|>; $x -> <$x> }
* Final environment:
  Deps: {}
  Constraints:
    [10:3-13]
      key < key'1, $v < arr, len < len'1, $x < arr, key'1 < key'2,
      arr < $v'1, arr'1 < $v'1, len'1 < len'2
  Locals:
    { $v -> vec<<key'2> => (<$v'1> | <$v'2>); |len'2|>; $x -> <$x> }

