Analyzing \binop:
* Params: { $x -> <v2>; $y -> <v3> }
* Final env:
  Locals: { $x -> <v2>; $y -> <v3> }
  This: None
  Return: <v1>
  Constraints:
    v2 < v1

Analyzing \assign0:
* Params: { $arg -> <v5> }
* Final env:
  Locals: { $arg -> <v5>; $x -> <v7> }
  This: None
  Return: <v4>
  Constraints:
    [v5 < v6, Bot < v7, v7 < v4]

Analyzing \assign1:
* Params: { $arg -> <v9> }
* Final env:
  Locals: { $arg -> <v9>; $x -> <v11> }
  This: None
  Return: <v8>
  Constraints:
    [v9 < v10, v10 < v11, v11 < v8]

Analyzing \condition:
* Params: { $a0 -> <v13>; $a1 -> <v14>; $a2 -> <v15> }
* Final env:
  Locals: { $a0 -> <v13>; $a1 -> <v14>; $a2 -> <v15>; $x -> <v18> }
  This: None
  Return: <v12>
  Constraints:
    [v13 < v16, v15 < v16, v14 < v17, v15 < v17, v16 < v18, v17 < v18,
     v18 < v12]

