safe_abstract_logger:{"pos":"(Relative_path.Dummy, \"safe_abstract_logging1.php\") 19:2","use_kind":"new","is_safe":false}
safe_abstract_logger:{"pos":"(Relative_path.Dummy, \"safe_abstract_logging1.php\") 24:2","use_kind":"call","is_safe":true}
safe_abstract_logger:{"pos":"(Relative_path.Dummy, \"safe_abstract_logging1.php\") 25:2","use_kind":"call","is_safe":true}
safe_abstract_logger:{"pos":"(Relative_path.Dummy, \"safe_abstract_logging1.php\") 34:2","use_kind":"call","is_safe":false}
safe_abstract_logger:{"pos":"(Relative_path.Dummy, \"safe_abstract_logging1.php\") 39:2","use_kind":"call","is_safe":true}
safe_abstract_logger:{"pos":"(Relative_path.Dummy, \"safe_abstract_logging1.php\") 40:2","use_kind":"call","is_safe":true}
WARN: File "safe_abstract_logging1.php", line 19, characters 3-14:
Unsafe use of `new`: `I1` might be abstract (Warn[12015])
  File "safe_abstract_logging1.php", line 4, characters 11-12:
  I1 is from 
WARN: File "safe_abstract_logging1.php", line 34, characters 3-17:
Unsafe call: `I1::smeth` might not exist because the receiver might be abstract. (Warn[12014])
  File "safe_abstract_logging1.php", line 4, characters 11-12:
  I1 is from 
