File "explicit_type_collection_wildcard_map2.php", line 6, characters 3-13:
  Map<string, [unresolved]>
File "explicit_type_collection_wildcard_map2.php", line 7, characters 10-11:
Invalid argument (Typing[4110])
File "explicit_type_collection_wildcard_map2.php", line 5, characters 12-17:
Expected string
File "explicit_type_collection_wildcard_map2.php", line 3, characters 21-26:
But got dynamic because it is an unenforceable type
