File "explicit_type_collection_passing_darray1.php", line 6, characters 3-13:
  darray<arraykey, bool>
File "explicit_type_collection_passing_darray1.php", line 8, characters 23-24:
Invalid argument (Typing[4110])
File "explicit_type_collection_passing_darray1.php", line 3, characters 37-42:
This is a string
File "explicit_type_collection_passing_darray1.php", line 5, characters 15-22:
It is incompatible with an array key (int/string)
