File "test_memoized.php", line 18, characters 12-21:
[Foo::foo_method_memoized_lsb]{Foo::$bar}(Bar) A global variable is possibly written via function call. (Other[11003])
File "test_memoized.php", line 34, characters 5-25:
[Test::test_method_call]{Foo::$bar}(int) A global variable is definitely written. (Other[11001])
File "test_memoized.php", line 36, characters 5-35:
[Test::test_method_call]{Foo::foo_method_memoized}(int) A global variable is definitely read. (Other[11004])
File "test_memoized.php", line 39, characters 5-39:
[Test::test_method_call]{Foo::foo_method_memoized_lsb}(Bar) A global variable is definitely read. (Other[11004])
File "test_memoized.php", line 40, characters 5-16:
[Test::test_method_call]{Foo::foo_method_memoized_lsb}(int) A global variable is possibly written via reference. (Other[11002])
File "test_memoized.php", line 42, characters 5-23:
[Test::test_method_call]{\fun_memoized}(Bar) A global variable is definitely read. (Other[11004])
File "test_memoized.php", line 43, characters 5-16:
[Test::test_method_call]{\fun_memoized}(int) A global variable is possibly written via reference. (Other[11002])
File "test_memoized.php", line 45, characters 5-31:
[Test::test_method_call]{\fun_memoized_vec_int}(vec<int>) A global variable is definitely read. (Other[11004])
