File "ifc_inheritance7.php", line 18, characters 17-17:
Some members in class `M` are incompatible with those declared in type `N` (Typing[4341])
  File "ifc_inheritance7.php", line 7, characters 19-21:
  The method `foo` is not compatible with the overridden method
  File "ifc_inheritance7.php", line 18, characters 17-17:
  Some members in class `M` are incompatible with those declared in type `N`
  File "ifc_inheritance7.php", line 7, characters 19-21:
  The method `foo` is not compatible with the overridden method
  File "ifc_inheritance7.php", line 7, characters 25-26:
  Parameters with `<<__External>>` must be overridden by other parameters with <<__External>>. This parameter is marked `<<__External>>`
  File "ifc_inheritance7.php", line 13, characters 40-41:
  But this parameter is not marked `<<__External>>`
  File "ifc_inheritance7.php", line 7, characters 19-21:
  This declaration was inherited from an object of type `TA`. Redeclare this member in `M` with a compatible signature.
