FoldedClass {
    name: "\\T",
    kind: Ctrait,
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: HH\classname<this>,
            origin: "\\T",
            refs: [],
        },
    },
}
FoldedClass {
    name: "\\T2",
    kind: Ctrait,
    substs: {
        "\\T": SubstContext {
            subst: Subst(
                {},
            ),
            class_context: "\\T2",
            from_req_extends: false,
        },
    },
    ancestors: {
        "\\T": T,
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: HH\classname<this>,
            origin: "\\T2",
            refs: [],
        },
    },
    extends: {
        "\\T",
    },
}
FoldedClass {
    name: "\\T3",
    kind: Ctrait,
    substs: {
        "\\T": SubstContext {
            subst: Subst(
                {},
            ),
            class_context: "\\T3",
            from_req_extends: false,
        },
    },
    ancestors: {
        "\\T": T,
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: HH\classname<this>,
            origin: "\\T3",
            refs: [],
        },
    },
    extends: {
        "\\T",
    },
}
FoldedClass {
    name: "\\A",
    kind: Cclass(
        Concrete,
    ),
    substs: {
        "\\T": SubstContext {
            subst: Subst(
                {},
            ),
            class_context: "\\T3",
            from_req_extends: false,
        },
        "\\T2": SubstContext {
            subst: Subst(
                {},
            ),
            class_context: "\\A",
            from_req_extends: false,
        },
        "\\T3": SubstContext {
            subst: Subst(
                {},
            ),
            class_context: "\\A",
            from_req_extends: false,
        },
    },
    ancestors: {
        "\\T": T,
        "\\T3": T3,
        "\\T2": T2,
    },
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: HH\classname<this>,
            origin: "\\A",
            refs: [],
        },
    },
    extends: {
        "\\T2",
        "\\T",
        "\\T3",
    },
}
