=== Shape analysis results for class_constants6.php
Summary after closing and simplifying for \C::DICT:
[4:9-28] [Constant]:
  shape(?'a' => int, ?'b' => int, ?'c' => int, ?'d' => mixed, ?'e' => mixed)
[4:36-51] [Allocation]:
  shape('a' => int)
Summary after closing and simplifying for \D:
Summary after closing and simplifying for \D::DICT:
[8:9-28] [Constant]:
  shape(?'b' => int, ?'c' => int, ?'d' => mixed, ?'e' => mixed)
[8:36-51] [Allocation]:
  shape('b' => int)
Summary after closing and simplifying for \E:
Summary after closing and simplifying for \E::DICT:
[12:9-28] [Constant]:
  shape('c' => int, ?'d' => mixed)
[12:36-51] [Allocation]:
  shape('c' => int)
Summary after closing and simplifying for \main:
