=== Shape analysis results for incomplete.php
Summary for \:div::__construct:
(ParamLike (([5:5-24], "\\:div::__construct"), (Index 0))) : dynamic
(ParamLike (([6:5-23], "\\:div::__construct"), (Index 1))) : dynamic
(ParamLike (([7:5-11], "\\:div::__construct"), (Index 2))) : dynamic
(ParamLike (([8:5-8], "\\:div::__construct"), (Index 3))) : dynamic
(ParamLike (([9:6-10], "\\:div::__construct"), Return)) : dynamic
Summary for \C::f:
(ParamLike (([13:21-22], "\\C::f"), (Index 0))) : dynamic
(ParamLike (([13:28-32], "\\C::f"), Return)) : dynamic
Summary for \C::g:
[19:5-33] [Allocation]:
  shape('a' => int, 'b' => bool)
(ParamLike (([18:24-28], "\\C::g"), Return)) : dynamic

Errors:
"[15:5-12]: Unsupported expression: Xml"
