[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mpartial;
      fd_fun =
      { f_span = [3:1-6:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), (Some ([3:19-23], (Hprim Tvoid)))); 
        f_name = ([3:10-13], "\\foo"); f_tparams = []; f_where_constraints = []; 
        f_variadic = FVnonVariadic;
        f_params =
        [{ param_annotation = ([3:14-16], int); param_type_hint = ((int), None); 
           param_is_variadic = false; param_pos = [3:14-16]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = None; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([4:5-13], (Expr (([4:5-12], int), (Binop ((Eq None), (([4:5-7], int), (Lvar ([4:5-7], $y))), (([4:10-12], int), (Lvar ([4:10-12], $x))))))));
            ([5:5-13], (Expr (([5:5-12], void), (Call ((([5:5-8], (function(int $_): void)), (Id ([5:5-8], "\\bar"))), [], [(([5:9-11], int), (Lvar ([5:9-11], $y)))], None)))))];
          fb_annotation = () };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None }
      });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
         ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; 
         ns_disable_xhp_element_mangling = false };
       fd_file_attributes = []; fd_mode = Mpartial;
       fd_fun =
       { f_span = [8:1-30]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_ret = ((void), (Some ([8:23-27], (Hprim Tvoid)))); 
         f_name = ([8:10-13], "\\bar"); f_tparams = []; f_where_constraints = []; 
         f_variadic = FVnonVariadic;
         f_params =
         [{ param_annotation = ([8:18-20], int); param_type_hint = ((int), (Some ([8:14-17], (Hprim Tint)))); 
            param_is_variadic = false; param_pos = [8:18-20]; param_name = "$_"; 
            param_expr = None; param_readonly = None; param_callconv = None; 
            param_user_attributes = []; param_visibility = None }
           ];
         f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([Pos.none], Noop)]; fb_annotation = () }; 
         f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
         f_doc_comment = None }
       })