Typecheck for change set on line 15
No errors!
(Additionally, hh_fanout errors matched hh_server errors.)

Typecheck for change set on line 31
File "/uses_foo.php", line 4, characters 10-14:
Invalid return type (Typing[4110])
File "/uses_foo.php", line 2, characters 17-19:
Expected `int`
File "/foo.php", line 3, characters 17-22:
But got `string`
(Additionally, hh_fanout errors matched hh_server errors.)
