HHVM_DEFINE_EXTENSION("hash"
  SOURCES
    ext_hash.cpp
    hash_adler32.cpp
    hash_blake3.cpp
    hash_crc32.cpp
    hash_fnv1.cpp
    hash_furc.cpp
    hash_gost.cpp
    hash_haval.cpp
    hash_joaat.cpp
    hash_keccak.cpp
    hash_md.cpp
    hash_murmur.cpp
    hash_ripemd.cpp
    hash_salsa.cpp
    hash_sha.cpp
    hash_snefru.cpp
    hash_tiger.cpp
    hash_whirlpool.cpp
  HEADERS
    ext_hash.h
    hash_adler32.h
    hash_blake3.h
    hash_crc32.h
    hash_engine.h
    hash_fnv1.h
    hash_furc.h
    hash_gost.h
    hash_haval.h
    hash_joaat.h
    hash_keccak.h
    hash_md.h
    hash_murmur.h
    hash_ripemd.h
    hash_salsa.h
    hash_sha.h
    hash_snefru.h
    hash_tiger.h
    hash_whirlpool.h
    php_hash_crc32_tables.h
    php_hash_gost_tables.h
    php_hash_snefru_tables.h
    php_hash_tiger_tables.h
    php_hash_whirlpool_tables.h
  SYSTEMLIB
    ext_hash.php
)
