// @generated by hh_manual from manual/hack/10-types/80-case-types.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
case type CT = int | string;

// When CT is expected (super side), we can pass int or string
function accept_ct(CT $x): void {}

function f(): void {
  accept_ct(42);      // OK: int <: (int | string)
  accept_ct("hello"); // OK: string <: (int | string)
}
