# This is the default devcontainer, but explicitly Ubuntu 20.04 Focal
#
# https://github.com/devcontainers/images/tree/main/src/universal
FROM mcr.microsoft.com/devcontainers/base:focal

RUN apt-get install -y cmake

