File "test_memoized.php", line 18, characters 12-21:
[Foo::foo_method_memoized_lsb](Bar) A global variable is passed to (or returned from) a function call. (Other[11003])
File "test_memoized.php", line 34, characters 5-25:
[Test::test_method_call](int) A static variable is directly written. (Other[11001])
File "test_memoized.php", line 40, characters 5-16:
[Test::test_method_call](int) A global variable is written. (Other[11002])
File "test_memoized.php", line 43, characters 5-16:
[Test::test_method_call](int) A global variable is written. (Other[11002])
