No errors
File: void.php, line: 12, kind: Kreturn, type: void
File: void.php, line: 16, kind: Kreturn, type: void
File: void.php, line: 25, kind: Kreturn, type: Awaitable<void>
File: void.php, line: 29, kind: Kreturn, type: Awaitable<int>
File: void.php, line: 34, kind: Kreturn, type: Awaitable<?int>
File: void.php, line: 43, kind: Kreturn, type: Awaitable<?int>
File: void.php, line: 57, kind: Kreturn, type: void
