// @generated by hh_manual from manual/hack/03-expressions-and-operators/25-subscript.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
async function example_snippet_wrapper(): Awaitable<void> {
  $d = dict["a" => 1];
  $d["b"] = 2;  // inserts new key "b"
  $d["a"] = 9;  // updates existing key "a"
}
