// @generated by hh_manual from manual/hack/03-expressions-and-operators/25-subscript.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
async function example_snippet_wrapper(): Awaitable<void> {
  $k = keyset[1, 2, 3];
  $k[] = 4;     // adds 4: $k is now keyset[1, 2, 3, 4]
  $k[] = 2;     // no change: 2 is already present
}
