WARN: File "52-type-assertions-01.hack", line 4, characters 3-10:
This `is` check is always `true`. The expression on the left has type `int` which is a subtype of `int`. (Warn[12009])
WARN: File "52-type-assertions-01.hack", line 5, characters 3-14:
This `is` check is always `false`. The expression on the left has type `string` which shares no values with `int`. (Warn[12010])
WARN: File "52-type-assertions-01.hack", line 7, characters 3-10:
This `is` check is always `true`. The expression on the left has type `int` which is a subtype of `num`. (Warn[12009])
WARN: File "52-type-assertions-01.hack", line 8, characters 3-12:
This `is` check is always `true`. The expression on the left has type `float` which is a subtype of `num`. (Warn[12009])
WARN: File "52-type-assertions-01.hack", line 9, characters 3-14:
This `is` check is always `false`. The expression on the left has type `string` which shares no values with `num`. (Warn[12010])
