// @generated by hh_manual
async function example_snippet_wrapper(): Awaitable<void> {
  -10 . NAN;               // string result with value "-10NAN"
  INF . "2e+5";            // string result with value "INF2e+5"
  true . null;             // string result with value "1"
}
