Message: phpcvs1

Part 1
body-line-count => int(105)
charset => string(8) "us-ascii"
content-base => string(1) "/"
content-boundary => string(37) "=====================_71195359==_.ALT"
content-type => string(21) "multipart/alternative"
ending-pos => int(5425)
line-count => int(141)
starting-pos => int(0)
starting-pos-body => int(1976)
transfer-encoding => string(4) "8bit"

    Part 1.1
    body-line-count => int(98)
    charset => string(10) "iso-8859-1"
    content-base => string(1) "/"
    content-charset => string(10) "iso-8859-1"
    content-format => string(6) "flowed"
    content-type => string(10) "text/plain"
    ending-pos => int(5378)
    line-count => int(101)
    starting-pos => int(2017)
    starting-pos-body => int(2127)
    transfer-encoding => string(16) "quoted-printable"
