/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010-2013 Facebook, Inc. (http://www.facebook.com)     |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

/* Generated by idl_list.php. Do NOT modify. */

#ifndef incl_EXT_LIST_TEST_EXT_H_
#define incl_EXT_LIST_TEST_EXT_H_

#include "hphp/facebook/extensions/facebook/test_ext_facebook.h"
#include "hphp/facebook/extensions/fbml/test_ext_fbml.h"
#include "hphp/facebook/extensions/fdb/test_ext_fdb.h"
#include "hphp/facebook/extensions/gameskill/test_ext_gameskill.h"
#include "hphp/facebook/extensions/gatehouse/test_ext_gatehouse.h"
#include "hphp/facebook/extensions/obc/test_ext_obc.h"
#include "hphp/facebook/extensions/oracle/test_ext_oracle.h"
#include "hphp/facebook/extensions/photodna/test_ext_photodna.h"
#include "hphp/facebook/extensions/php_mcc/test_ext_php_mcc.h"
#include "hphp/facebook/extensions/phpmc/test_ext_phpmc.h"
#include "hphp/facebook/extensions/scrypt/test_ext_scrypt.h"
#include "hphp/facebook/extensions/servicerouter/test_ext_servicerouter.h"
#include "hphp/facebook/extensions/string_buffer/test_ext_string_buffer.h"
#include "hphp/facebook/extensions/tao/test_ext_tao.h"
#include "hphp/facebook/extensions/urlextraction/test_ext_urlextraction.h"
#include "hphp/test/ext/test_ext_apd.h"
#include "hphp/test/ext/test_ext_asio.h"
#include "hphp/test/ext/test_ext_bcmath.h"
#include "hphp/test/ext/test_ext_bzip2.h"
#include "hphp/test/ext/test_ext_class.h"
#include "hphp/test/ext/test_ext_closure.h"
#include "hphp/test/ext/test_ext_collections.h"
#include "hphp/test/ext/test_ext_continuation.h"
#include "hphp/test/ext/test_ext_ctype.h"
#include "hphp/test/ext/test_ext_curl.h"
#include "hphp/test/ext/test_ext_datetime.h"
#include "hphp/test/ext/test_ext_debugger.h"
#include "hphp/test/ext/test_ext_domdocument.h"
#include "hphp/test/ext/test_ext_error.h"
#include "hphp/test/ext/test_ext_file.h"
#include "hphp/test/ext/test_ext_function.h"
#include "hphp/test/ext/test_ext_hash.h"
#include "hphp/test/ext/test_ext_iconv.h"
#include "hphp/test/ext/test_ext_icu.h"
#include "hphp/test/ext/test_ext_icu_ucnv.h"
#include "hphp/test/ext/test_ext_icu_ucsdet.h"
#include "hphp/test/ext/test_ext_icu_uspoof.h"
#include "hphp/test/ext/test_ext_image.h"
#include "hphp/test/ext/test_ext_imagesprite.h"
#include "hphp/test/ext/test_ext_imap.h"
#include "hphp/test/ext/test_ext_intl.h"
#include "hphp/test/ext/test_ext_ipc.h"
#include "hphp/test/ext/test_ext_json.h"
#include "hphp/test/ext/test_ext_ldap.h"
#include "hphp/test/ext/test_ext_magick.h"
#include "hphp/test/ext/test_ext_mailparse.h"
#include "hphp/test/ext/test_ext_math.h"
#include "hphp/test/ext/test_ext_mb.h"
#include "hphp/test/ext/test_ext_mcrypt.h"
#include "hphp/test/ext/test_ext_memcache.h"
#include "hphp/test/ext/test_ext_memcached.h"
#include "hphp/test/ext/test_ext_misc.h"
#include "hphp/test/ext/test_ext_mysql.h"
#include "hphp/test/ext/test_ext_network.h"
#include "hphp/test/ext/test_ext_openssl.h"
#include "hphp/test/ext/test_ext_options.h"
#include "hphp/test/ext/test_ext_output.h"
#include "hphp/test/ext/test_ext_pdo.h"
#include "hphp/test/ext/test_ext_posix.h"
#include "hphp/test/ext/test_ext_preg.h"
#include "hphp/test/ext/test_ext_process.h"
#include "hphp/test/ext/test_ext_reflection.h"
#include "hphp/test/ext/test_ext_server.h"
#include "hphp/test/ext/test_ext_session.h"
#include "hphp/test/ext/test_ext_simplexml.h"
#include "hphp/test/ext/test_ext_soap.h"
#include "hphp/test/ext/test_ext_socket.h"
#include "hphp/test/ext/test_ext_sqlite3.h"
#include "hphp/test/ext/test_ext_stream.h"
#include "hphp/test/ext/test_ext_string.h"
#include "hphp/test/ext/test_ext_thread.h"
#include "hphp/test/ext/test_ext_thrift.h"
#include "hphp/test/ext/test_ext_url.h"
#include "hphp/test/ext/test_ext_variable.h"
#include "hphp/test/ext/test_ext_xml.h"
#include "hphp/test/ext/test_ext_xmlreader.h"
#include "hphp/test/ext/test_ext_xmlwriter.h"
#include "hphp/test/ext/test_ext_zlib.h"

#endif // incl_EXT_LIST_TEST_EXT_H_
