// @generated by hh_manual from manual/hack/20-attributes/07-predefined-attributes.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
class C {
  <<__Sealed(T::class)>>
  public function foo(): void { echo "I am foo in C\n"; }
}

trait T {
  require extends C;

  <<__Override>>
  public function foo(): void { echo "I am foo in T\n"; }
}

class D extends C {
  // D cannot override directly foo, the following raises an error
  // public function foo(): void { echo "I am foo in D\n" }

  // however D can use trait T which overrides `foo`
  use T;
}
