// @generated by hh_manual from manual/hack/20-attributes/07-predefined-attributes.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
class Dog {
  <<__AutocompleteSortText('!getName')>>
  public function getName(): string {
    return "Clifford";
  }

  public function getOwner(): string {
    return "Emily";
  }

  public function getFriends(): vec<string> {
    return vec["Cleo"];
  }
}

<<__Docs("http://www.example.com/my_framework")>>
class MyFrameworkBaseClass {}

class MyClass extends MyFrameworkBaseClass {}
