(6,10)-(6,13) This token is not valid as part of a function declaration.
(6,25)-(6,25) A type annotation is required in strict mode.
(10,17)-(10,32) This token is not valid as part of a function declaration.
(10,44)-(10,44) A type annotation is required in strict mode.
(14,26)-(14,26) A variable name is expected here.
(14,44)-(14,44) A type annotation is required in strict mode.
(18,27)-(18,27) A variable name is expected here.
(18,44)-(18,44) A class member, method, type, trait usage, trait require, xhp attribute, xhp use, or xhp category is expected here.
(18,44)-(18,55) Method declarations require a visibility modifier such as public, private or protected.
(18,55)-(18,55) A type annotation is required in strict mode.
(25,47)-(26,1) A variable name is expected here.
(27,3)-(27,14) Method declarations require a visibility modifier such as public, private or protected.
(27,14)-(27,14) A type annotation is required in strict mode.
(34,47)-(35,1) A variable name is expected here.
(36,21)-(36,21) A type annotation is required in strict mode.
