((script 703
  ((list 703
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 482
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 474
        ((() { 1 ((end_of_line 1)))
         (list 397
          ((methodish_declaration 29
            ((missing 0 ())
             (function_declaration_header 23
              ((list 6
                ((((end_of_line 1) (whitespace 2) (single_line_comment 66)
                   (end_of_line 1) (whitespace 2))
                  public 6 ((whitespace 1)))))
               (((extra_token_error 3) (whitespace 1)) function 8
                ((whitespace 1)))
               (() name 1 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
               (missing 0 ())))
             (compound_statement 5
              ((() { 1 ((end_of_line 1))) (missing 0 ())
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (methodish_declaration 48
            ((missing 0 ())
             (function_declaration_header 42
              ((list 13
                ((((end_of_line 1) (whitespace 2) (single_line_comment 66)
                   (end_of_line 1) (whitespace 2))
                  public 6 ((whitespace 1)))
                 (() static 6 ((whitespace 1)))))
               (((extra_token_error 15) (whitespace 1)) function 8
                ((whitespace 1)))
               (() name 1 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
               (missing 0 ())))
             (compound_statement 5
              ((() { 1 ((end_of_line 1))) (missing 0 ())
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (property_declaration 22
            ((missing 0 ())
             (list 6
              ((((end_of_line 1) (whitespace 2) (single_line_comment 63)
                 (end_of_line 1) (whitespace 2))
                public 6 ((whitespace 1)))))
             (simple_type_specifier 15 ((() name 15 ((whitespace 1)))))
             (list 0
              ((list_item 0
                ((property_declarator 0 ((missing 0 ()) (missing 0 ())))
                 (missing 0 ())))))
             (missing 0 ())))
           (methodish_declaration 25
            ((missing 0 ())
             (function_declaration_header 19
              ((list 6 ((() static 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (compound_statement 5
              ((() { 1 ((end_of_line 1))) (missing 0 ())
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))
           (property_declaration 23
            ((missing 0 ())
             (list 6
              ((((end_of_line 1) (whitespace 2) (single_line_comment 63)
                 (end_of_line 1) (whitespace 2))
                public 6 ((whitespace 1)))))
             (simple_type_specifier 16 ((() name 16 ((whitespace 1)))))
             (list 0
              ((list_item 0
                ((property_declarator 0 ((missing 0 ()) (missing 0 ())))
                 (missing 0 ())))))
             (missing 0 ())))
           (error 16 ((() name 16 ((whitespace 1)))))
           (methodish_declaration 18
            ((missing 0 ())
             (function_declaration_header 12
              ((missing 0 ()) (() function 8 ((whitespace 1))) (() name 1 ())
               (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
               (missing 0 ())))
             (compound_statement 5
              ((() { 1 ((end_of_line 1))) (missing 0 ())
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (((end_of_line 1)) } 1 ((end_of_line 1)))))))
     (classish_declaration 102
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 94
        ((() { 1 ((end_of_line 1)))
         (list 86
          ((property_declaration 10
            ((missing 0 ())
             (list 6
              ((((end_of_line 1) (whitespace 2)) public 6 ((whitespace 1)))))
             (simple_type_specifier 3
              ((() name 3
                ((whitespace 1) (single_line_comment 33) (end_of_line 1)))))
             (list 0
              ((list_item 0
                ((property_declarator 0 ((missing 0 ()) (missing 0 ())))
                 (missing 0 ())))))
             (missing 0 ())))
           (methodish_declaration 38
            ((missing 0 ())
             (function_declaration_header 12
              ((missing 0 ())
               (((end_of_line 1) (whitespace 2)) function 8 ((whitespace 1)))
               (() name 1 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
               (() ")" 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
               (missing 0 ())))
             (compound_statement 25
              ((() { 1
                ((whitespace 1) (single_line_comment 19) (end_of_line 1)))
               (missing 0 ()) (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (((end_of_line 1)) } 1 ((end_of_line 1)))))))
     (classish_declaration 109
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 101
        ((() { 1 ((end_of_line 1)))
         (list 93
          ((property_declaration 10
            ((missing 0 ())
             (list 6
              ((((end_of_line 1) (whitespace 2)) public 6 ((whitespace 1)))))
             (simple_type_specifier 3
              ((() name 3
                ((whitespace 1) (single_line_comment 33) (end_of_line 1)))))
             (list 0
              ((list_item 0
                ((property_declarator 0 ((missing 0 ()) (missing 0 ())))
                 (missing 0 ())))))
             (missing 0 ())))
           (methodish_declaration 45
            ((missing 0 ())
             (function_declaration_header 19
              ((list 6
                ((((end_of_line 1) (whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (compound_statement 25
              ((() { 1
                ((whitespace 1) (single_line_comment 19) (end_of_line 1)))
               (missing 0 ()) (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (((end_of_line 1)) } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
