((script 970
  ((list 970
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 907
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((single_line_comment 56) (end_of_line 1) (end_of_line 1)) trait 5
        ((whitespace 1)))
       (() name 2 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 884
        ((((extra_token_error 13) (whitespace 1)) { 1 ((end_of_line 1)))
         (list 878
          ((require_clause 33
            ((((whitespace 2)) require 7 ((whitespace 1)))
             (() extends 7 ((whitespace 1)))
             (simple_type_specifier 2 ((() name 2 ((whitespace 1)))))
             (((extra_token_error 13)) ";" 1 ((end_of_line 1)))))
           (property_declaration 35
            ((missing 0 ())
             (list 7
              ((((end_of_line 1) (whitespace 2)) private 7 ((end_of_line 1)))))
             (missing 0 ())
             (list 20
              ((list_item 20
                ((property_declarator 20
                  ((((whitespace 4)) variable 2 ((whitespace 1)))
                   (simple_initializer 17
                    ((() = 1 ((whitespace 1))) (() name 15 ((whitespace 1)))))))
                 (missing 0 ())))))
             (((extra_token_error 1)) ";" 1 ((end_of_line 1)))))
           (methodish_declaration 802
            ((missing 0 ())
             (function_declaration_header 69
              ((list 21
                ((((end_of_line 1) (whitespace 2)) final 5 ((whitespace 1)))
                 (() protected 9 ((whitespace 1)))
                 (() async 5 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 2 ((whitespace 1)))
               (missing 0 ())
               (((extra_token_error 13) (whitespace 1)) "(" 1 ())
               (list 13
                ((list_item 13
                  ((parameter_declaration 13
                    ((missing 0 ()) (missing 0 ()) (missing 0 ())
                     (simple_type_specifier 5
                      ((() array 5 ((whitespace 1)))))
                     (() variable 7 ((whitespace 1))) (missing 0 ())))
                   (missing 0 ())))))
               (((extra_token_error 5)) ")" 1 ((whitespace 1)))
               (missing 0 ()) (missing 0 ()) (missing 0 ())))
             (compound_statement 732
              ((() { 1 ((end_of_line 1)))
               (list 722
                ((expression_statement 25
                  ((binary_expression 23
                    ((variable 2
                      ((((whitespace 4)) variable 2 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (function_call_expression 18
                      ((member_selection_expression 16
                        ((variable 2 ((() variable 2 ()))) (() -> 2 ())
                         (() name 12 ())))
                       (missing 0 ()) (() "(" 1 ()) (missing 0 ())
                       (() ")" 1 ())))))
                   (((extra_token_error 1)) ";" 1 ((end_of_line 1)))))
                 (expression_statement 41
                  ((binary_expression 40
                    ((variable 2
                      ((((whitespace 4)) variable 2 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (prefix_unary_expression 35
                      ((() await 5 ((whitespace 1)))
                       (function_call_expression 29
                        ((member_selection_expression 24
                          ((function_call_expression 19
                            ((scope_resolution_expression 15
                              ((() name 1 ()) (() :: 2 ()) (() name 12 ())))
                             (missing 0 ()) (() "(" 1 ())
                             (list 2
                              ((list_item 2
                                ((variable 2 ((() variable 2 ())))
                                 (missing 0 ())))))
                             (() ")" 1 ())))
                           (() -> 2 ()) (() name 3 ())))
                         (missing 0 ()) (() "(" 1 ())
                         (list 3
                          ((list_item 3
                            ((literal 3
                              ((() single_quoted_string_literal 3 ())))
                             (missing 0 ())))))
                         (() ")" 1 ())))))))
                   (() ";" 1 ((end_of_line 1)))))
                 (if_statement 238
                  ((((end_of_line 1) (whitespace 4)) if 2 ((whitespace 1)))
                   (((extra_token_error 13) (whitespace 1)) "(" 1 ())
                   (prefix_unary_expression 3
                    ((() ! 1 ()) (variable 2 ((() variable 2 ())))))
                   (() ")" 1 ((whitespace 1)))
                   (compound_statement 215
                    ((() { 1 ((end_of_line 1)))
                     (list 201
                      ((expression_statement 14
                        ((binary_expression 13
                          ((member_selection_expression 5
                            ((variable 2 ((((whitespace 6)) variable 2 ())))
                             (() -> 2 ()) (() name 1 ((whitespace 1)))))
                           (() = 1 ((whitespace 1)))
                           (literal 5 ((() boolean_literal 5 ())))))
                         (() ";" 1 ((end_of_line 1)))))
                       (expression_statement 20
                        ((binary_expression 13
                          ((subscript_expression 7
                            ((member_selection_expression 5
                              ((variable 2
                                ((((whitespace 6)) variable 2 ())))
                               (() -> 2 ()) (() name 1 ())))
                             (() [ 1 ()) (missing 0 ())
                             (() ] 1 ((whitespace 1)))))
                           (() = 1 ((whitespace 1)))
                           (literal 3
                            ((() single_quoted_string_literal 3
                              ((whitespace 1)))))))
                         (((extra_token_error 5)) ";" 1 ((end_of_line 1)))))
                       (expression_statement 16
                        ((binary_expression 16
                          ((subscript_expression 7
                            ((member_selection_expression 5
                              ((variable 2
                                ((((whitespace 6) (single_line_comment 63)
                                   (end_of_line 1) (whitespace 6)
                                   (single_line_comment 21) (end_of_line 1)
                                   (whitespace 6))
                                  variable 2 ())))
                               (() -> 2 ()) (() name 1 ())))
                             (() [ 1 ()) (missing 0 ())
                             (() ] 1 ((whitespace 1)))))
                           (() = 1 ((whitespace 1)))
                           (binary_expression 6
                            ((literal 3
                              ((() single_quoted_string_literal 3
                                ((whitespace 1)))))
                             (() . 1 ()) (() / 1 ())))))
                         (missing 0 ())))
                       (expression_statement 5
                        ((literal 3 ((() floating_literal 3 ())))
                         (((extra_token_error 1)) ";" 1 ((end_of_line 1)))))
                       (return_statement 27
                        ((((whitespace 6)) return 6 ((whitespace 1)))
                         (literal 5
                          ((() boolean_literal 5 ((whitespace 1)))))
                         (((extra_token_error 13)) ";" 1 ((end_of_line 1)))))))
                     (((whitespace 4)) } 1 ((end_of_line 1)))))
                   (missing 0 ()) (missing 0 ())))
                 (if_statement 134
                  ((((end_of_line 1) (whitespace 4) (single_line_comment 43)
                     (end_of_line 1) (end_of_line 1) (whitespace 4))
                    if 2 ((whitespace 1)))
                   (() "(" 1 ())
                   (binary_expression 59
                    ((parenthesized_expression 21
                      ((() "(" 1 ())
                       (binary_expression 19
                        ((function_call_expression 14
                          ((() name 5 ()) (missing 0 ()) (() "(" 1 ())
                           (list 7
                            ((list_item 7
                              ((variable 7 ((() variable 7 ())))
                               (missing 0 ())))))
                           (() ")" 1 ((whitespace 1)))))
                         (() != 2 ((whitespace 1)))
                         (literal 1 ((() decimal_literal 1 ())))))
                       (() ")" 1 ((whitespace 1)))))
                     (() || 2 ((whitespace 1)))
                     (parenthesized_expression 34
                      ((() "(" 1 ())
                       (binary_expression 32
                        ((function_call_expression 10
                          ((() name 1 ()) (missing 0 ()) (() "(" 1 ())
                           (list 7
                            ((list_item 7
                              ((variable 7 ((() variable 7 ())))
                               (missing 0 ())))))
                           (() ")" 1 ((whitespace 1)))))
                         (() != 2 ((whitespace 1)))
                         (function_call_expression 18
                          ((member_selection_expression 16
                            ((variable 2 ((() variable 2 ()))) (() -> 2 ())
                             (() name 12 ())))
                           (missing 0 ()) (() "(" 1 ()) (missing 0 ())
                           (() ")" 1 ())))))
                       (() ")" 1 ())))))
                   (() ")" 1 ((whitespace 1)))
                   (compound_statement 69
                    ((() { 1 ((end_of_line 1)))
                     (list 55
                      ((expression_statement 14
                        ((binary_expression 13
                          ((subscript_expression 7
                            ((member_selection_expression 5
                              ((variable 2
                                ((((whitespace 6)) variable 2 ())))
                               (() -> 2 ()) (() name 1 ())))
                             (() [ 1 ()) (missing 0 ())
                             (() ] 1 ((whitespace 1)))))
                           (() = 1 ((whitespace 1)))
                           (literal 3
                            ((() single_quoted_string_literal 3 ())))))
                         (() ";" 1 ((end_of_line 1)))))
                       (expression_statement 14
                        ((binary_expression 13
                          ((member_selection_expression 5
                            ((variable 2 ((((whitespace 6)) variable 2 ())))
                             (() -> 2 ()) (() name 1 ((whitespace 1)))))
                           (() = 1 ((whitespace 1)))
                           (literal 5 ((() boolean_literal 5 ())))))
                         (() ";" 1 ((end_of_line 1)))))
                       (return_statement 13
                        ((((whitespace 6)) return 6 ((whitespace 1)))
                         (literal 5 ((() boolean_literal 5 ())))
                         (() ";" 1 ((end_of_line 1)))))))
                     (((whitespace 4)) } 1 ((end_of_line 1)))))
                   (missing 0 ()) (missing 0 ())))
                 (if_statement 85
                  ((((end_of_line 1) (whitespace 4)) if 2 ((whitespace 1)))
                   (() "(" 1 ())
                   (prefix_unary_expression 11
                    ((() ! 1 ())
                     (function_call_expression 10
                      ((member_selection_expression 8
                        ((variable 2 ((() variable 2 ()))) (() -> 2 ())
                         (() name 4 ())))
                       (missing 0 ()) (() "(" 1 ()) (missing 0 ())
                       (() ")" 1 ())))))
                   (() ")" 1 ((whitespace 1)))
                   (compound_statement 68
                    ((() { 1 ((end_of_line 1)))
                     (list 54
                      ((expression_statement 14
                        ((binary_expression 13
                          ((subscript_expression 7
                            ((member_selection_expression 5
                              ((variable 2
                                ((((whitespace 6)) variable 2 ())))
                               (() -> 2 ()) (() name 1 ())))
                             (() [ 1 ()) (missing 0 ())
                             (() ] 1 ((whitespace 1)))))
                           (() = 1 ((whitespace 1)))
                           (literal 3
                            ((() single_quoted_string_literal 3 ())))))
                         (() ";" 1 ((end_of_line 1)))))
                       (expression_statement 13
                        ((binary_expression 12
                          ((member_selection_expression 5
                            ((variable 2 ((((whitespace 6)) variable 2 ())))
                             (() -> 2 ()) (() name 1 ())))
                           (() = 1 ((whitespace 1)))
                           (literal 5 ((() boolean_literal 5 ())))))
                         (() ";" 1 ((end_of_line 1)))))
                       (return_statement 13
                        ((((whitespace 6)) return 6 ((whitespace 1)))
                         (literal 5 ((() boolean_literal 5 ())))
                         (() ";" 1 ((end_of_line 1)))))))
                     (((whitespace 4)) } 1 ((end_of_line 1)))))
                   (missing 0 ()) (missing 0 ())))
                 (expression_statement 121
                  ((binary_expression 120
                    ((list_expression 31
                      ((((end_of_line 1) (whitespace 4)) list 4 ())
                       (() "(" 1 ((end_of_line 1)))
                       (list 13
                        ((list_item 3
                          ((variable 2 ((((whitespace 6)) variable 2 ())))
                           (() , 1 ((end_of_line 1)))))
                         (list_item 3
                          ((variable 2 ((((whitespace 6)) variable 2 ())))
                           (() , 1 ((end_of_line 1)))))))
                       (((whitespace 4)) ")" 1 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (prefix_unary_expression 86
                      ((() await 5 ((whitespace 1)))
                       (function_call_expression 80
                        ((() name 12 ()) (missing 0 ())
                         (() "(" 1 ((end_of_line 1)))
                         (list 54
                          ((list_item 20
                            ((function_call_expression 19
                              ((scope_resolution_expression 15
                                ((((whitespace 6)) name 1 ()) (() :: 2 ())
                                 (() name 12 ())))
                               (missing 0 ()) (() "(" 1 ())
                               (list 2
                                ((list_item 2
                                  ((variable 2 ((() variable 2 ())))
                                   (missing 0 ())))))
                               (() ")" 1 ())))
                             (() , 1 ((end_of_line 1)))))
                           (list_item 27
                            ((function_call_expression 26
                              ((member_selection_expression 22
                                ((function_call_expression 8
                                  ((scope_resolution_expression 6
                                    ((((whitespace 6)) name 1 ())
                                     (() :: 2 ()) (() name 3 ())))
                                   (missing 0 ()) (() "(" 1 ())
                                   (missing 0 ()) (() ")" 1 ())))
                                 (() -> 2 ()) (() name 12 ())))
                               (missing 0 ()) (() "(" 1 ())
                               (list 2
                                ((list_item 2
                                  ((variable 2 ((() variable 2 ())))
                                   (missing 0 ())))))
                               (() ")" 1 ())))
                             (() , 1 ((end_of_line 1)))))))
                         (((whitespace 4)) ")" 1 ())))))))
                   (() ";" 1 ((end_of_line 1)))))))
               (((whitespace 2)) } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
