((script 504
  ((list 504
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (classish_declaration 10
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1) (single_line_comment 77) (end_of_line 1)
         (single_line_comment 78) (end_of_line 1) (single_line_comment 68)
         (end_of_line 1) (end_of_line 1) (single_line_comment 79)
         (end_of_line 1) (single_line_comment 76) (end_of_line 1)
         (single_line_comment 58) (end_of_line 1) (end_of_line 1))
        class 5 ((whitespace 1)))
       (() name 2 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 1
        ((() { 1 ((whitespace 1) (single_line_comment 22) (end_of_line 1)))
         (list 0 ((missing 0 ()))) (missing 0 ())))))
     (classish_declaration 14
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1) (whitespace 2)) class 5 ((whitespace 1)))
       (() name 2 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 5
        ((() { 1 ((end_of_line 1))) (missing 0 ())
         (((whitespace 2)) } 1 ((end_of_line 1)))))))
     (expression_statement 1
      ((((end_of_line 1)) } 1
        ((whitespace 1) (single_line_comment 40) (end_of_line 1)))
       (missing 0 ())))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
