(4,10)-(4,10) Encountered unexpected token 'extraNonsense'.
(5,22)-(5,22) Encountered unexpected token 'extraNonsense'.
(8,26)-(8,26) Encountered unexpected token '!'.
(10,37)-(10,37) Encountered unexpected token 'extraNonsense'.
(10,66)-(10,66) Encountered unexpected token 'extra'.
(11,28)-(11,28) Encountered unexpected token ')'.
(14,8)-(14,8) Encountered unexpected token 'extraNonsense'.
(16,21)-(16,21) Encountered unexpected token '67835'.
(19,23)-(19,23) An expression is expected here.
(19,26)-(19,26) Encountered unexpected token '$'.
(20,20)-(20,20) Encountered unexpected token 'extraNonsense'.
