{ "function": "\\takes_int", "solutions": [] }
{ "function": "\\takes_string", "solutions": [] }
{ "function": "\\get_dynamic", "solutions": [] }
{
  "function": "\\test_reassign",
  "solutions": [
    {
      "name": "$x",
      "pos": "File \"reassign.php\", line 10, characters 3-20:",
      "type": "string"
    },
    {
      "name": "$x",
      "pos": "File \"reassign.php\", line 8, characters 3-20:",
      "type": "int"
    }
  ]
}
