{
  "errors":[
    {
      "descr":"Method `foo` is also defined on `MyParent`, but this method is missing `<<__Override>>`.",
      "severity":"error",
      "path":"test_missing_override.php",
      "line":8,
      "start":19,
      "end":21,
      "code":5616,
      "bypass_changed_lines":false,
      "original":"",
      "replacement":"<<__Override>>\n  ",
      "start_offset":94,
      "width":0
    }
  ],
  "version":" Wed Dec 31 16:00:00 1969"
}