((script 80
  ((list 80
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (function_declaration 64
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 1 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 45
        ((() { 1 ((end_of_line 1)))
         (list 39
          ((expression_statement 22
            ((binary_expression 22
              ((variable 2 ((((whitespace 2)) variable 2 ((whitespace 1)))))
               (() = 1 ((whitespace 1)))
               (conditional_expression 17
                ((variable 2 ((() variable 2 ((whitespace 1)))))
                 (() ? 1 ((whitespace 1)))
                 (binary_expression 6
                  ((variable 2 ((() variable 2 ((whitespace 1)))))
                   (() = 1 ((whitespace 1))) (() & 1 ())))
                 (missing 0 ())
                 (binary_expression 6
                  ((variable 2 ((() variable 2 ((whitespace 1)))))
                   (() + 1 ((whitespace 1)))
                   (literal 1 ((() decimal_literal 1 ((whitespace 1)))))))))))
             (missing 0 ())))
           (expression_statement 1
            ((() : 1 ((whitespace 1))) (missing 0 ())))
           (expression_statement 6
            ((binary_expression 6
              ((variable 2 ((() variable 2 ((whitespace 1)))))
               (() = 1 ((whitespace 1))) (() & 1 ())))
             (missing 0 ())))
           (expression_statement 8
            ((binary_expression 7
              ((variable 3 ((() variable 3 ((whitespace 1)))))
               (() * 1 ((whitespace 1)))
               (literal 1 ((() decimal_literal 1 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
