((script 91
  ((list 91
    ((markup_section 4
      ((missing 0 ()) (() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))
       (missing 0 ())))
     (function_declaration 76
      ((missing 0 ())
       (function_declaration_header 18
        ((missing 0 ()) (() function 8 ((whitespace 1))) (() name 1 ())
         (missing 0 ()) (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())
         (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 57
        ((() { 1 ((end_of_line 1)))
         (list 51
          ((expression_statement 51
            ((binary_expression 50
              ((variable 2 ((((whitespace 2)) variable 2 ((whitespace 1)))))
               (() = 1 ((whitespace 1)))
               (binary_expression 45
                ((variable 2 ((() variable 2 ((whitespace 1)))))
                 (() = 1 ((whitespace 1)))
                 (binary_expression 40
                  ((prefix_unary_expression 4
                    ((() & 1 ())
                     (variable 3 ((() variable 3 ((whitespace 1)))))))
                   (() + 1 ((whitespace 1)))
                   (binary_expression 33
                    ((variable 2 ((() variable 2 ((whitespace 1)))))
                     (() = 1 ((whitespace 1)))
                     (binary_expression 28
                      ((prefix_unary_expression 4
                        ((() & 1 ())
                         (variable 3 ((() variable 3 ((whitespace 1)))))))
                       (() * 1 ((whitespace 1)))
                       (binary_expression 21
                        ((variable 2 ((() variable 2 ((whitespace 1)))))
                         (() = 1 ((whitespace 1)))
                         (binary_expression 16
                          ((prefix_unary_expression 4
                            ((() & 1 ())
                             (variable 3 ((() variable 3 ((whitespace 1)))))))
                           (() + 1 ((whitespace 1)))
                           (binary_expression 9
                            ((variable 2 ((() variable 2 ((whitespace 1)))))
                             (() = 1 ((whitespace 1)))
                             (prefix_unary_expression 4
                              ((() & 1 ()) (variable 3 ((() variable 3 ())))))))))))))))))))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
