array(0) {
}
array(1) {
  [0]=>
  int(10)
}
array(1) {
  [0]=>
  int(1)
}
HipHop Warning: Missing argument 1 for test2(), called in hphp/test/zend/bad/003.php on line %d and defined in hphp/test/zend/bad/003.php on line %d
array(0) {
}
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
array(0) {
}
HipHop Warning: Missing argument 2 for test3() in hphp/test/zend/bad/003.php on line %d
array(1) {
  [0]=>
  int(1)
}
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
array(1) {
  [0]=>
  int(1)
}
HipHop Warning: func_get_args():  Called from the global scope - no function context in hphp/test/zend/bad/003.php on line %d
bool(false)
Done
