array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ string\(\d+\)\ \"[^
]+\"\
\}\
array\(2\)\ \{\
\ \ \[0\]\=\>\
\ \ string\(\d+\)\ \"[^
]+\"\
\ \ \[1\]\=\>\
\ \ string\(\d+\)\ \"[^
]+\"\
\}\
HipHop\ Warning\:\ Missing\ argument\ 0\ for\ get\_included\_files\(\)\ in\ hphp\/test\/zend\/bad\/zend\/014\.php\ on\ line\ \d+\
NULL\
array\(2\)\ \{\
\ \ \[0\]\=\>\
\ \ string\(\d+\)\ \"[^
]+\"\
\ \ \[1\]\=\>\
\ \ string\(\d+\)\ \"[^
]+\"\
\}\
HipHop\ Warning\:\ Missing\ argument\ 0\ for\ get\_included\_files\(\)\ in\ hphp\/test\/zend\/bad\/zend\/014\.php\ on\ line\ \d+\
NULL\
array\(2\)\ \{\
\ \ \[0\]\=\>\
\ \ string\(\d+\)\ \"[^
]+\"\
\ \ \[1\]\=\>\
\ \ string\(\d+\)\ \"[^
]+\"\
\}\
Done