HipHop Warning: .+
NULL\
HipHop Warning: .+
NULL\
string\(6\)\ \"stream\"\
string\(7\)\ \"Unknown\"\
string\(5\)\ \"array\"\
int\(\d+\)\
string\(5\)\ \"array\"\
int\(\d+\)\
HipHop Warning: .+
NULL\
HipHop Warning: .+
NULL\
string\(5\)\ \"array\"\
string\(5\)\ \"array\"\
int\(\d+\)\
HipHop Warning: .+
NULL\
string\(5\)\ \"array\"\
int\(\d+\)\
HipHop Warning: .+
NULL\
string\(5\)\ \"array\"\
int\(\d+\)\
HipHop Warning: .+
NULL\
bool\(false\)\
string\(5\)\ \"array\"\
int\(\d+\)\
string\(5\)\ \"array\"\
int\(\d+\)\
Done