HipHop\ Notice\:\ Indirect\ modification\ of\ overloaded\ property\ A\:\:\$whatever\ has\ no\ effect\ in\ [^
]+bug32660\.php\ on\ line\ 20\
A\ Object\
\(\
\ \ \ \ \[q\]\ \=\>\ 3\
\)\
HipHop\ Notice\:\ Indirect\ modification\ of\ overloaded\ property\ A\:\:\$whatever\ has\ no\ effect\ in\ [^
]+bug32660\.php\ on\ line\ 23\
HipHop\ Fatal\ error\:\ Cannot\ assign\ by\ reference\ to\ overloaded\ object\ in\ [^
]+bug32660\.php\ on\ line\ 23