\_\_call\:\
string\(3\)\ \"ABC\"\
\_\_call\:\
string\(3\)\ \"ABC\"\
\_\_call\:\
string\(3\)\ \"xyz\"\
\_\_call\:\
string\(3\)\ \"www\"\
\_\_call\:\
string\(1\)\ \"y\"\
\_\_call\:\
string\(1\)\ \"y\"\
ok\
HipHop\ Warning\:\ call\_user\_func\(\)\ expects\ parameter\ 1\ to\ be\ a\ valid\ callback\,\ class\ \'bar\'\ does\ not\ have\ a\ method\ \'www\'\ in\ hphp\/test\/zend\/bad\/zend\/bug45186\_2\.php\ on\ line\ \d+\
HipHop\ Warning\:\ call\_user\_func\(\)\ expects\ parameter\ 1\ to\ be\ a\ valid\ callback\,\ cannot\ access\ self\:\:\ when\ no\ class\ scope\ is\ active\ in\ [^
]+bug45186\_2\.php\ on\ line\ 27