Strict\ Standards\:\ Declaration\ of\ Bar4\:\:setSelf\(\)\ should\ be\ compatible\ with\ Foo4\:\:setSelf\(Foo4\ \$s\)\ in\ [^
]+bug60573\.php\ on\ line\ \d+\
\
Strict\ Standards\:\ Declaration\ of\ Bar5\:\:setSelf\(\)\ should\ be\ compatible\ with\ Foo5\:\:setSelf\(Base\ \$s\)\ in\ [^
]+bug60573\.php\ on\ line\ \d+\
HipHop\ Fatal\ error\:\ Declaration\ of\ Bar6\:\:setSelf\(\)\ must\ be\ compatible\ with\ Foo6\:\:setSelf\(Base\ \$s\)\ in\ [^
]+bug60573\.php\ on\ line\ \d+