\*\*\*\ Indexing\ \-\ Testing\ value\ assignment\ with\ key\ \*\*\*\
array\(1\)\ \{\
\ \ \[\"foo\"\]\=\>\
\ \ array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
HipHop Warning: .+
int\(0\)\
HipHop Warning: .+
int\(1\)\
HipHop Warning: .+
bool\(true\)\
array\(1\)\ \{\
\ \ \[\"foo\"\]\=\>\
\ \ array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
array\(1\)\ \{\
\ \ \[\"foo\"\]\=\>\
\ \ array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
HipHop Warning: .+
HipHop Notice: .+
string\(1\)\ \"A\"\
HipHop Warning: .+
float\(0\.1\)\
array\(1\)\ \{\
\ \ \[\"foo\"\]\=\>\
\ \ array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
\
\*\*\*\ Indexing\ \-\ Testing\ reference\ assignment\ with\ key\ \*\*\*\
array\(1\)\ \{\
\ \ \[\"foo\"\]\=\>\
\ \ \&array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
HipHop Warning: .+
int\(0\)\
HipHop Warning: .+
int\(1\)\
HipHop Warning: .+
bool\(true\)\
array\(1\)\ \{\
\ \ \[\"foo\"\]\=\>\
\ \ \&array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
array\(1\)\ \{\
\ \ \[\"foo\"\]\=\>\
\ \ \&array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
HipHop Warning: .+
float\(0\.1\)\
array\(1\)\ \{\
\ \ \[\"foo\"\]\=\>\
\ \ \&array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
\*\*\*\ Indexing\ \-\ Testing\ value\ assignment\ no\ key\ \*\*\*\
array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
HipHop Warning: .+
int\(0\)\
HipHop Warning: .+
int\(1\)\
HipHop Warning: .+
bool\(true\)\
array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
HipHop Warning: .+
float\(0\.1\)\
array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
\
\*\*\*\ Indexing\ \-\ Testing\ reference\ assignment\ no\ key\ \*\*\*\
array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ \&array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
HipHop Warning: .+
int\(0\)\
HipHop Warning: .+
int\(1\)\
HipHop Warning: .+
bool\(true\)\
array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ \&array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ \&array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
HipHop Warning: .+
float\(0\.1\)\
array\(1\)\ \{\
\ \ \[0\]\=\>\
\ \ \&array\(1\)\ \{\
\ \ \ \ \[0\]\=\>\
\ \ \ \ int\(1\)\
\ \ \}\
\}\
\
Done