Errors:
  [3:10-13] Was expecting a return type hint
  [3:14-17] Wrong number of type arguments (expected 2, got 0)
  [55:15-18] Definition is here
[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-13], "\\foo");
      fd_fun =
      { f_span = [3:1-6:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((void), None);
        f_params =
        [{ param_annotation = (Map<string, (int | string)>); param_type_hint = ((Map<string, (int | string)>), (Some ([3:14-17], (Happly (([3:14-17], "\\HH\\Map"), []))))); 
           param_is_variadic = false; param_pos = [3:18-20]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([4:3-18],
            (Expr
               ((int), [4:3-17],
                (Binop
                   { bop = (Eq None); lhs = ((int), [4:3-12], (Array_get (((Map<string, (int | string)>), [4:3-5], (Lvar ([4:3-5], $x))), (Some ((string), [4:6-11], (String "int"))))));
                     rhs = ((int), [4:15-17], (Int "42")) }))));
            ([5:3-20],
             (Expr
                ((string), [5:3-19],
                 (Binop
                    { bop = (Eq None); lhs = ((string), [5:3-12], (Array_get (((Map<string, (int | string)>), [5:3-5], (Lvar ([5:3-5], $x))), (Some ((string), [5:6-11], (String "foo"))))));
                      rhs = ((string), [5:15-19], (String "23")) }))))
            ]
          };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })