error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `_PIRANHA_SANDBOX_QUEUED_` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `_PIRANHA_SANDBOX_QUEUED_` is defined

File "workplace_shape_mismatch.php", line 15, character 4 - line 15, character 29:

 14 |   ?'earlyreturn' => int,
 15 |   ?»'_PIRANHA_SANDBOX_QUEUED_'« => bool,
 16 |   ?'resource_requirement' => int,
 17 |   ?'execution_push_phase' => string,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `async_bulkapi_factor` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `async_bulkapi_factor` is defined

File "workplace_shape_mismatch.php", line 18, character 4 - line 18, character 25:

 17 |   ?'execution_push_phase' => string,
 18 |   ?»'async_bulkapi_factor'« => float,
 19 |   ?'devserver' => string,
 20 |   ?'fifo_ordering_key' => string,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `devserver` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `devserver` is defined

File "workplace_shape_mismatch.php", line 19, character 4 - line 19, character 14:

 18 |   ?'async_bulkapi_factor' => float,
 19 |   ?»'devserver'« => string,
 20 |   ?'fifo_ordering_key' => string,
 21 |   ?'fifo_dedup_key' => string,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `earlyreturn` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `earlyreturn` is defined

File "workplace_shape_mismatch.php", line 14, character 4 - line 14, character 16:

 13 |   ?'retry_attempt' => int,
 14 |   ?»'earlyreturn'« => int,
 15 |   ?'_PIRANHA_SANDBOX_QUEUED_' => bool,
 16 |   ?'resource_requirement' => int,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `execute_after` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `execute_after` is defined

File "workplace_shape_mismatch.php", line 7, character 4 - line 7, character 18:

 6 |   ?'serialization_format' => SerializationFormat,
 7 |   ?»'execute_after'« => int,
 8 |   ?'execute_before' => int,
 9 |   ?'expire_after' => int,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `execute_before` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `execute_before` is defined

File "workplace_shape_mismatch.php", line 8, character 4 - line 8, character 19:

 7 |   ?'execute_after' => int,
 8 |   ?»'execute_before'« => int,
 9 |   ?'expire_after' => int,
10 |   ?'region' => string,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `execution_push_phase` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `execution_push_phase` is defined

File "workplace_shape_mismatch.php", line 17, character 4 - line 17, character 25:

 16 |   ?'resource_requirement' => int,
 17 |   ?»'execution_push_phase'« => string,
 18 |   ?'async_bulkapi_factor' => float,
 19 |   ?'devserver' => string,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `expire_after` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `expire_after` is defined

File "workplace_shape_mismatch.php", line 9, character 4 - line 9, character 17:

 8 |   ?'execute_before' => int,
 9 |   ?»'expire_after'« => int,
10 |   ?'region' => string,
11 |   ?'scheduling_uid' => int,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `fifo_dedup_key` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `fifo_dedup_key` is defined

File "workplace_shape_mismatch.php", line 21, character 4 - line 21, character 19:

 20 |   ?'fifo_ordering_key' => string,
 21 |   ?»'fifo_dedup_key'« => string,
 22 |   ?'send_schedule_cats' => bool,
 23 | );

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `fifo_ordering_key` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `fifo_ordering_key` is defined

File "workplace_shape_mismatch.php", line 20, character 4 - line 20, character 22:

 19 |   ?'devserver' => string,
 20 |   ?»'fifo_ordering_key'« => string,
 21 |   ?'fifo_dedup_key' => string,
 22 |   ?'send_schedule_cats' => bool,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `region` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `region` is defined

File "workplace_shape_mismatch.php", line 10, character 4 - line 10, character 11:

 9 |   ?'expire_after' => int,
10 |   ?»'region'« => string,
11 |   ?'scheduling_uid' => int,
12 |   ?'tag' => string,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `resource_requirement` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `resource_requirement` is defined

File "workplace_shape_mismatch.php", line 16, character 4 - line 16, character 25:

 15 |   ?'_PIRANHA_SANDBOX_QUEUED_' => bool,
 16 |   ?»'resource_requirement'« => int,
 17 |   ?'execution_push_phase' => string,
 18 |   ?'async_bulkapi_factor' => float,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `retry_attempt` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `retry_attempt` is defined

File "workplace_shape_mismatch.php", line 13, character 4 - line 13, character 18:

 12 |   ?'tag' => string,
 13 |   ?»'retry_attempt'« => int,
 14 |   ?'earlyreturn' => int,
 15 |   ?'_PIRANHA_SANDBOX_QUEUED_' => bool,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `scheduling_uid` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `scheduling_uid` is defined

File "workplace_shape_mismatch.php", line 11, character 4 - line 11, character 19:

 10 |   ?'region' => string,
 11 |   ?»'scheduling_uid'« => int,
 12 |   ?'tag' => string,
 13 |   ?'retry_attempt' => int,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `send_schedule_cats` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `send_schedule_cats` is defined

File "workplace_shape_mismatch.php", line 22, character 4 - line 22, character 23:

 21 |   ?'fifo_dedup_key' => string,
 22 |   ?»'send_schedule_cats'« => bool,
 23 | );

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `serialization_format` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `serialization_format` is defined

File "workplace_shape_mismatch.php", line 6, character 4 - line 6, character 25:

 5 | type AsyncJobOptions = shape(
 6 |   ?»'serialization_format'« => SerializationFormat,
 7 |   ?'execute_after' => int,
 8 |   ?'execute_before' => int,

error: Typing[4057] Invalid argument

File "workplace_shape_mismatch.php", line 97, character 36 - line 97, character 43:

 96 |   ): Awaitable<string> {
 97 |     return await self::genAsyncJob(»$options«);
 98 |   }
 99 | }

The field `tag` is missing

File "workplace_shape_mismatch.php", line 89, character 6 - line 89, character 24:

 88 |   public static async function genAsyncJob(
 89 |     ?»AsyncTierJobOptions« $options = null,
 90 |   ): Awaitable<string> {
 91 |     return "";

The field `tag` is defined

File "workplace_shape_mismatch.php", line 12, character 4 - line 12, character 8:

 11 |   ?'scheduling_uid' => int,
 12 |   ?»'tag'« => string,
 13 |   ?'retry_attempt' => int,
 14 |   ?'earlyreturn' => int,

17 errors found
