error: Typing[4110] Invalid argument

 36 |   $ak = new ExampleArraykeyClass();
 37 |   $ak->addToContainer(»1«);
 38 | }

File "workplace_abstract_class_as_typeconst.php", line 37, character 23 - line 37, character 23:

Expected `ContainerClass::TType`

 13 |   public function addToContainer(»this::TContainerClass::TType« $val): void {
 14 |     $this->container?->add($val);
 15 |   }

File "workplace_abstract_class_as_typeconst.php", line 13, character 34 - line 13, character 61:

But got `int`

 36 |   $ak = new ExampleArraykeyClass();
 37 |   $ak->addToContainer(»1«);
 38 | }

File "workplace_abstract_class_as_typeconst.php", line 37, character 23 - line 37, character 23:

1 error found.
