error: Typing[4110] Invalid argument

 36 |   $ak = new ExampleArraykeyClass();
 37 |   $ak->addToContainer(»1«);
 38 | }

File "workplace_abstract_class_as_typeconst.php", line 37, character 23 - line 37, character 23:

Expected `ContainerClass::TType`

 13 |   public function addToContainer(»this::TContainerClass::TType« $val): void {
 14 |     $this->container?->add($val);
 15 |   }

File "workplace_abstract_class_as_typeconst.php", line 13, character 34 - line 13, character 61:

But got `int`

 36 |   $ak = new ExampleArraykeyClass();
 37 |   $ak->addToContainer(»1«);
 38 | }

File "workplace_abstract_class_as_typeconst.php", line 37, character 23 - line 37, character 23:

This error has 3 steps, a maximum depth of 1 and contains 1 reversal.

Here's why: this expression

 36 |   $ak = new ExampleArraykeyClass();
 37 |   $ak->addToContainer(»1«);
 38 | }

File "workplace_abstract_class_as_typeconst.php", line 37, character 23 - line 37, character 23:

flows up into this expression as the 1st function parameter

 36 |   $ak = new ExampleArraykeyClass();
 37 |   »$ak->addToContainer(1)«;
 38 | }

File "workplace_abstract_class_as_typeconst.php", line 37, character 3 - line 37, character 24:

which itself flows from this function or method  because they are required to be subtypes

 13 |   public function »addToContainer«(this::TContainerClass::TType $val): void {
 14 |     $this->container?->add($val);
 15 |   }

File "workplace_abstract_class_as_typeconst.php", line 13, character 19 - line 13, character 32:

which itself flows down into this type constant as the 1st function parameter

 13 |   public function addToContainer(this::TContainerClass::»TType« $val): void {
 14 |     $this->container?->add($val);
 15 |   }

File "workplace_abstract_class_as_typeconst.php", line 13, character 57 - line 13, character 61:

Raw:
[
  {
    "Witness":[
      {
        "filename":"workplace_abstract_class_as_typeconst.php",
        "line":37,
        "char_start":23,
        "char_end":23
      }
    ]
  },
  "Flow_prj",
  {
    "Prj":[
      {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
      [
        {
          "Witness":[
            {
              "filename":"workplace_abstract_class_as_typeconst.php",
              "line":37,
              "char_start":3,
              "char_end":24
            }
          ]
        },
        "Flow_subtype",
        {
          "Rev":[
            [
              {
                "Support_dynamic_type":[
                  {
                    "filename":"workplace_abstract_class_as_typeconst.php",
                    "line":13,
                    "char_start":19,
                    "char_end":32
                  }
                ]
              }
            ]
          ]
        }
      ]
    ]
  },
  "Flow_subtype_toplevel",
  {
    "Type_access":[
      [
        {
          "Typeconst":[
            [{"No_reason":[]}],
            {
              "Tuple2":[
                {
                  "filename":"workplace_abstract_class_as_typeconst.php",
                  "line":13,
                  "char_start":57,
                  "char_end":61
                },
                "TType"
              ]
            },
            "an object of type ContainerClass",
            [
              {
                "Type_access":[
                  [
                    {
                      "Typeconst":[
                        [
                          {
                            "Def":[
                              {
                                "filename":"workplace_abstract_class_as_typeconst.php",
                                "line":3,
                                "char_start":16,
                                "char_end":29
                              },
                              [
                                {
                                  "Hint":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":32,
                                      "char_start":32,
                                      "char_end":45
                                    }
                                  ]
                                }
                              ]
                            ]
                          }
                        ],
                        {
                          "Tuple2":[
                            {
                              "filename":"workplace_abstract_class_as_typeconst.php",
                              "line":13,
                              "char_start":40,
                              "char_end":54
                            },
                            "TContainerClass"
                          ]
                        },
                        "an object of type ExampleArraykeyClass",
                        [
                          {
                            "Instantiate":[
                              [
                                {
                                  "Witness":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":36,
                                      "char_start":13,
                                      "char_end":32
                                    }
                                  ]
                                },
                                "Flow_assign",
                                {
                                  "Witness":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":36,
                                      "char_start":3,
                                      "char_end":5
                                    }
                                  ]
                                },
                                "Flow_local",
                                {
                                  "Witness":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":37,
                                      "char_start":3,
                                      "char_end":5
                                    }
                                  ]
                                }
                              ],
                              "this",
                              [
                                {
                                  "Hint":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":13,
                                      "char_start":34,
                                      "char_end":61
                                    }
                                  ]
                                }
                              ]
                            ]
                          }
                        ]
                      ]
                    }
                  ],
                  [
                    {
                      "Tuple2":[
                        [
                          {
                            "Hint":[
                              {
                                "filename":"workplace_abstract_class_as_typeconst.php",
                                "line":13,
                                "char_start":34,
                                "char_end":61
                              }
                            ]
                          }
                        ],
                        "ExampleArraykeyClass::TContainerClass"
                      ]
                    }
                  ]
                ]
              }
            ]
          ]
        }
      ],
      [
        {
          "Tuple2":[
            [
              {
                "Hint":[
                  {
                    "filename":"workplace_abstract_class_as_typeconst.php",
                    "line":13,
                    "char_start":34,
                    "char_end":61
                  }
                ]
              }
            ],
            "ContainerClass::TType"
          ]
        }
      ]
    ]
  }
]


File "", line 0, character 0 - line 0, character -1:

Normalised:
[
  {
    "Witness":[
      {
        "filename":"workplace_abstract_class_as_typeconst.php",
        "line":37,
        "char_start":23,
        "char_end":23
      }
    ]
  },
  "Flow_prj",
  {
    "Prj":[
      {"Symm":[{"Prj_symm_fn_param":[0,0]}]},
      [
        {
          "Witness":[
            {
              "filename":"workplace_abstract_class_as_typeconst.php",
              "line":37,
              "char_start":3,
              "char_end":24
            }
          ]
        },
        "Flow_subtype",
        {
          "Support_dynamic_type":[
            {
              "filename":"workplace_abstract_class_as_typeconst.php",
              "line":13,
              "char_start":19,
              "char_end":32
            }
          ]
        }
      ]
    ]
  },
  "Flow_subtype_toplevel",
  {
    "Type_access":[
      [
        {
          "Typeconst":[
            [{"No_reason":[]}],
            {
              "Tuple2":[
                {
                  "filename":"workplace_abstract_class_as_typeconst.php",
                  "line":13,
                  "char_start":57,
                  "char_end":61
                },
                "TType"
              ]
            },
            "an object of type ContainerClass",
            [
              {
                "Type_access":[
                  [
                    {
                      "Typeconst":[
                        [
                          {
                            "Def":[
                              {
                                "filename":"workplace_abstract_class_as_typeconst.php",
                                "line":3,
                                "char_start":16,
                                "char_end":29
                              },
                              [
                                {
                                  "Hint":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":32,
                                      "char_start":32,
                                      "char_end":45
                                    }
                                  ]
                                }
                              ]
                            ]
                          }
                        ],
                        {
                          "Tuple2":[
                            {
                              "filename":"workplace_abstract_class_as_typeconst.php",
                              "line":13,
                              "char_start":40,
                              "char_end":54
                            },
                            "TContainerClass"
                          ]
                        },
                        "an object of type ExampleArraykeyClass",
                        [
                          {
                            "Instantiate":[
                              [
                                {
                                  "Witness":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":36,
                                      "char_start":13,
                                      "char_end":32
                                    }
                                  ]
                                },
                                "Flow_assign",
                                {
                                  "Witness":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":36,
                                      "char_start":3,
                                      "char_end":5
                                    }
                                  ]
                                },
                                "Flow_local",
                                {
                                  "Witness":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":37,
                                      "char_start":3,
                                      "char_end":5
                                    }
                                  ]
                                }
                              ],
                              "this",
                              [
                                {
                                  "Hint":[
                                    {
                                      "filename":"workplace_abstract_class_as_typeconst.php",
                                      "line":13,
                                      "char_start":34,
                                      "char_end":61
                                    }
                                  ]
                                }
                              ]
                            ]
                          }
                        ]
                      ]
                    }
                  ],
                  [
                    {
                      "Tuple2":[
                        [
                          {
                            "Hint":[
                              {
                                "filename":"workplace_abstract_class_as_typeconst.php",
                                "line":13,
                                "char_start":34,
                                "char_end":61
                              }
                            ]
                          }
                        ],
                        "ExampleArraykeyClass::TContainerClass"
                      ]
                    }
                  ]
                ]
              }
            ]
          ]
        }
      ],
      [
        {
          "Tuple2":[
            [
              {
                "Hint":[
                  {
                    "filename":"workplace_abstract_class_as_typeconst.php",
                    "line":13,
                    "char_start":34,
                    "char_end":61
                  }
                ]
              }
            ],
            "ContainerClass::TType"
          ]
        }
      ]
    ]
  }
]


File "", line 0, character 0 - line 0, character -1:

Path:
{
  "stats":{"max_depth":1,"length":3,"reversals":1},
  "path_elems":[
    [
      {
        "Witness":[
          {
            "filename":"workplace_abstract_class_as_typeconst.php",
            "line":37,
            "char_start":23,
            "char_end":23
          }
        ]
      }
    ],
    {
      "Edge":{"dir":"Fwd","kind":"Flow_prj","in_to":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}}
    },
    [
      {
        "Witness":[
          {
            "filename":"workplace_abstract_class_as_typeconst.php",
            "line":37,
            "char_start":3,
            "char_end":24
          }
        ]
      }
    ],
    {"Edge":{"dir":"Bwd","kind":"Flow_subtype"}},
    [
      {
        "Support_dynamic_type":[
          {
            "filename":"workplace_abstract_class_as_typeconst.php",
            "line":13,
            "char_start":19,
            "char_end":32
          }
        ]
      }
    ],
    {
      "Edge":{
        "dir":"Fwd",
        "kind":"Flow_subtype_toplevel",
        "out_of":{"Symm":[{"Prj_symm_fn_param":[0,0]}]}
      }
    },
    [
      {
        "Type_access":[
          [
            {
              "Typeconst":[
                [{"No_reason":[]}],
                {
                  "Tuple2":[
                    {
                      "filename":"workplace_abstract_class_as_typeconst.php",
                      "line":13,
                      "char_start":57,
                      "char_end":61
                    },
                    "TType"
                  ]
                },
                "an object of type ContainerClass",
                [
                  {
                    "Type_access":[
                      [
                        {
                          "Typeconst":[
                            [
                              {
                                "Def":[
                                  {
                                    "filename":"workplace_abstract_class_as_typeconst.php",
                                    "line":3,
                                    "char_start":16,
                                    "char_end":29
                                  },
                                  [
                                    {
                                      "Hint":[
                                        {
                                          "filename":"workplace_abstract_class_as_typeconst.php",
                                          "line":32,
                                          "char_start":32,
                                          "char_end":45
                                        }
                                      ]
                                    }
                                  ]
                                ]
                              }
                            ],
                            {
                              "Tuple2":[
                                {
                                  "filename":"workplace_abstract_class_as_typeconst.php",
                                  "line":13,
                                  "char_start":40,
                                  "char_end":54
                                },
                                "TContainerClass"
                              ]
                            },
                            "an object of type ExampleArraykeyClass",
                            [
                              {
                                "Instantiate":[
                                  [
                                    {
                                      "Witness":[
                                        {
                                          "filename":"workplace_abstract_class_as_typeconst.php",
                                          "line":36,
                                          "char_start":13,
                                          "char_end":32
                                        }
                                      ]
                                    },
                                    "Flow_assign",
                                    {
                                      "Witness":[
                                        {
                                          "filename":"workplace_abstract_class_as_typeconst.php",
                                          "line":36,
                                          "char_start":3,
                                          "char_end":5
                                        }
                                      ]
                                    },
                                    "Flow_local",
                                    {
                                      "Witness":[
                                        {
                                          "filename":"workplace_abstract_class_as_typeconst.php",
                                          "line":37,
                                          "char_start":3,
                                          "char_end":5
                                        }
                                      ]
                                    }
                                  ],
                                  "this",
                                  [
                                    {
                                      "Hint":[
                                        {
                                          "filename":"workplace_abstract_class_as_typeconst.php",
                                          "line":13,
                                          "char_start":34,
                                          "char_end":61
                                        }
                                      ]
                                    }
                                  ]
                                ]
                              }
                            ]
                          ]
                        }
                      ],
                      [
                        {
                          "Tuple2":[
                            [
                              {
                                "Hint":[
                                  {
                                    "filename":"workplace_abstract_class_as_typeconst.php",
                                    "line":13,
                                    "char_start":34,
                                    "char_end":61
                                  }
                                ]
                              }
                            ],
                            "ExampleArraykeyClass::TContainerClass"
                          ]
                        }
                      ]
                    ]
                  }
                ]
              ]
            }
          ],
          [
            {
              "Tuple2":[
                [
                  {
                    "Hint":[
                      {
                        "filename":"workplace_abstract_class_as_typeconst.php",
                        "line":13,
                        "char_start":34,
                        "char_end":61
                      }
                    ]
                  }
                ],
                "ContainerClass::TType"
              ]
            }
          ]
        ]
      }
    ]
  ]
}


File "", line 0, character 0 - line 0, character -1:

1 error found.
