File "tconst_on_generics2.php", line 50, characters 9-12:
Some type constraint(s) here are violated (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 31-32:
'T1' is a constrained type parameter
File "tconst_on_generics2.php", line 40, characters 82-82:
You are trying to access the member T but this is not an object, it is a dynamic value
File "tconst_on_generics2.php", line 40, characters 31-32:
Definition is here
File "tconst_on_generics2.php", line 50, characters 9-12:
Some type constraint(s) here are violated (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 31-32:
'T1' is a constrained type parameter
File "tconst_on_generics2.php", line 40, characters 82-82:
You are trying to access the member T but this is not an object, it is a dynamic value
File "tconst_on_generics2.php", line 40, characters 37-39:
Definition is here
File "tconst_on_generics2.php", line 50, characters 9-12:
Some type constraint(s) here are violated (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 42-43:
'T2' is a constrained type parameter
File "tconst_on_generics2.php", line 40, characters 88-88:
You are trying to access the member T but this is not an object, it is a dynamic value
File "tconst_on_generics2.php", line 40, characters 42-43:
Definition is here
File "tconst_on_generics2.php", line 50, characters 9-12:
Some type constraint(s) here are violated (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 42-43:
'T2' is a constrained type parameter
File "tconst_on_generics2.php", line 40, characters 88-88:
You are trying to access the member T but this is not an object, it is a dynamic value
File "tconst_on_generics2.php", line 40, characters 48-50:
Definition is here
File "tconst_on_generics2.php", line 50, characters 18-19:
Invalid argument (Typing[4110])
File "tconst_on_generics2.php", line 19, characters 18-23:
Expected string
File "tconst_on_generics2.php", line 40, characters 82-82:
  resulting from accessing the type constant 'T'
File "tconst_on_generics2.php", line 48, characters 12-20:
  on an object of exactly the class StringBox
File "tconst_on_generics2.php", line 10, characters 18-20:
But got int
File "tconst_on_generics2.php", line 40, characters 88-88:
  resulting from accessing the type constant 'T'
File "tconst_on_generics2.php", line 49, characters 12-17:
  on an object of exactly the class IntBox
File "tconst_on_generics2.php", line 30, characters 70-70:
You are trying to access the member T but this is not an object, it is a dynamic value (Typing[4062])
File "tconst_on_generics2.php", line 30, characters 36-38:
Definition is here
File "tconst_on_generics2.php", line 36, characters 79-79:
You are trying to access the member T but this is not an object, it is a dynamic value (Typing[4062])
File "tconst_on_generics2.php", line 36, characters 36-38:
Definition is here
File "tconst_on_generics2.php", line 40, characters 82-82:
You are trying to access the member T but this is not an object, it is a dynamic value (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 37-39:
Definition is here
File "tconst_on_generics2.php", line 40, characters 88-88:
You are trying to access the member T but this is not an object, it is a dynamic value (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 48-50:
Definition is here
File "tconst_on_generics2.php", line 30, characters 70-70:
You are trying to access the member T but this is not an object, it is a dynamic value (Typing[4062])
File "tconst_on_generics2.php", line 30, characters 36-38:
Definition is here
File "tconst_on_generics2.php", line 31, characters 14-17:
You are trying to access the member getK but this is not an object, it is a dynamic value or an object of type Box (Typing[4062])
File "tconst_on_generics2.php", line 30, characters 36-38:
Definition is here
File "tconst_on_generics2.php", line 36, characters 79-79:
You are trying to access the member T but this is not an object, it is a dynamic value (Typing[4062])
File "tconst_on_generics2.php", line 36, characters 36-38:
Definition is here
File "tconst_on_generics2.php", line 37, characters 9-12:
You are trying to access the member setK but this is not an object, it is a dynamic value or an object of type Box (Typing[4062])
File "tconst_on_generics2.php", line 36, characters 36-38:
Definition is here
File "tconst_on_generics2.php", line 40, characters 82-82:
You are trying to access the member T but this is not an object, it is a dynamic value (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 37-39:
Definition is here
File "tconst_on_generics2.php", line 40, characters 88-88:
You are trying to access the member T but this is not an object, it is a dynamic value (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 48-50:
Definition is here
File "tconst_on_generics2.php", line 41, characters 9-12:
You are trying to access the member setK but this is not an object, it is a dynamic value or an object of type Box (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 37-39:
Definition is here
File "tconst_on_generics2.php", line 41, characters 18-21:
You are trying to access the member getK but this is not an object, it is a dynamic value or an object of type Box (Typing[4062])
File "tconst_on_generics2.php", line 40, characters 48-50:
Definition is here
