[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-23], "\\pess_hint_fun");
      fd_fun =
      { f_span = [3:1-5:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None;
        f_ret =
        ((),
         (Some ([3:51-71],
                (Happly (([3:51-71], "\\HH\\supportdyn"),
                   [([3:51-71],
                     (Hfun
                        { hf_is_readonly = None; hf_param_tys = [([3:61-64], (Hprim Tint))]; 
                          hf_param_info = [(Some { hfparam_kind = Pnormal; hfparam_readonlyness = None; hfparam_optional = None })]; 
                          hf_variadic_ty = None; hf_ctxs = None; hf_return_ty = ([3:67-70], (Hlike ([3:67-70], (Hprim Tint)))); 
                          hf_is_readonly_return = None }))
                     ]
                   )))));
        f_params =
        [{ param_annotation = ();
           param_type_hint =
           ((),
            (Some ([3:24-44],
                   (Happly (([3:24-44], "\\HH\\supportdyn"),
                      [([3:24-44],
                        (Hfun
                           { hf_is_readonly = None; hf_param_tys = [([3:34-37], (Hprim Tint))];
                             hf_param_info = [(Some { hfparam_kind = Pnormal; hfparam_readonlyness = None; hfparam_optional = None })]; 
                             hf_variadic_ty = None; hf_ctxs = None; hf_return_ty = ([3:40-43], (Hlike ([3:40-43], (Hprim Tint)))); 
                             hf_is_readonly_return = None }))
                        ]
                      )))));
           param_is_variadic = false; param_pos = [3:45-47]; param_name = "$f"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = []; param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None; f_body = { fb_ast = [([4:3-13], (Return (Some ((), [4:10-12], (Lvar ([4:10-12], $f))))))] }; 
        f_fun_kind = FSync; f_user_attributes = [{ ua_name = ([3:10-23], "__SupportDynamicType"); ua_params = [] }]; 
        f_external = false; f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })
  ]
