// @generated by hh_manual from manual/hack/13-contexts-and-capabilities/06-context-constants.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
class HasGlobals {
  const ctx C = [globals];
}

abstract class AbstractDoer {
  abstract const ctx C;
  abstract public function doWork()[this::C, HasGlobals::C]: void;
}
