HipHop Warning: .+
\-\-\-\>\ Invoke\ \_\_call\ via\ simple\ method\ call\.\
NULL\
Exception\ caught\ OK\;\ continuing\.\
\
\
\-\-\-\>\ Invoke\ \_\_call\ via\ scope\ resolution\ operator\ within\ instance\.\
NULL\
Exception\ caught\ OK\;\ continuing\.\
\
\
\-\-\-\>\ Invoke\ \_\_call\ via\ scope\ resolution\ operator\ within\ child\ instance\.\
NULL\
Exception\ caught\ OK\;\ continuing\.\
\
\
\-\-\-\>\ Invoke\ \_\_call\ via\ callback\.\
NULL\
Exception\ caught\ OK\;\ continuing\.\
\=\=DONE\=\=