HHVM_DEFINE_EXTENSION("async_msyql"
  PRETTY_NAME "Async MySQL"
  SOURCES
    ext_async_mysql.cpp
  HEADERS
    ext_async_mysql.h
  EXTENSION_LIBRARY
    ext_async_msyql.php
    ext_async_mysql_exceptions.php
    ext_mysqlrow.php
  DEPENDS_UPON
    ext_asio
    ext_collections
    ext_mysql
    libFolly
    libSquangle
    libWebscaleSQL
    systemlib
    varENABLE_ASYNC_MYSQL
)
