Code actions available:
------------------------------------------
Extract interface (CodeActionKind: refactor) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"\n  implements Placeholder_",
          "range":{"end":{"character":7,"line":2},"start":{"character":7,"line":2}}
        },
        {
          "newText":"interface Placeholder_ {\n  public function foo(): void {\n// comment on first line;}\n\n",
          "range":{"end":{"character":0,"line":2},"start":{"character":0,"line":2}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Extract interface"
}

Applied edit for code action:
------------------------------------------
<?hh

interface Placeholder_ {
  public function foo(): void {
// comment on first line;}

class A
  implements Placeholder_ {
  // repro bug: commented-out closing brace in extracted interface
  /*range-start*/
  public function foo(): void {
    // comment on first line
  }
  /*range-end*/
}

