=== base errors ===
No errors!
=== changed errors ===
b.php:4:23,27: Invalid xhp value for attribute `:prop` in `child` (Typing[4343])
  child.php:4:13,18: Expected `string`
  b.php:3:31,33: But got `int`
child.php:4:13,18: The property `:prop` has the wrong type (Typing[4341])
  child.php:4:13,18: Typing error
  child.php:4:13,18: Expected `string`
  a.php:4:13,20: But got `arraykey`
=== fanout ===
0x7eeda955b68b5127
Fun xhp_simple_attribute
