(3,1)-(3,20) The `<<...>>` syntax for user attributes is not allowed. Use the `@` syntax instead.
(4,1)-(4,14) The `<<...>>` syntax for user attributes is not allowed. Use the `@` syntax instead.
(5,12)-(5,22) The `<<...>>` syntax for user attributes is not allowed. Use the `@` syntax instead.
(5,32)-(5,42) The `<<...>>` syntax for user attributes is not allowed. Use the `@` syntax instead.
(5,55)-(5,65) The `<<...>>` syntax for user attributes is not allowed. Use the `@` syntax instead.
(7,1)-(7,20) The `<<...>>` syntax for user attributes is not allowed. Use the `@` syntax instead.
(9,3)-(9,12) The `<<...>>` syntax for user attributes is not allowed. Use the `@` syntax instead.
(12,3)-(12,13) The `<<...>>` syntax for user attributes is not allowed. Use the `@` syntax instead.
