#if EXT_TYPE == 0
"mhash", T(Variant), S(0), "hash", T(Int64), NULL, S(0), "data", T(String), NULL, S(0), "key", T(String), "null_string", S(0), NULL, S(0), 
"mhash_get_hash_name", T(Variant), S(0), "hash", T(Int64), NULL, S(0), NULL, S(0), 
"mhash_count", T(Int64), S(0), NULL, S(0), 
"mhash_get_block_size", T(Variant), S(0), "hash", T(Int64), NULL, S(0), NULL, S(0), 
"mhash_keygen_s2k", T(Variant), S(0), "hash", T(Int64), NULL, S(0), "password", T(String), NULL, S(0), "salt", T(String), NULL, S(0), "bytes", T(Int64), NULL, S(0), NULL, S(0), 
#elif EXT_TYPE == 1
#elif EXT_TYPE == 2
#elif EXT_TYPE == 3

#endif
