/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010 Facebook, Inc. (http://www.facebook.com)          |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __TEST_EXT_MHASH_H__
#define __TEST_EXT_MHASH_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <test/test_cpp_ext.h>

///////////////////////////////////////////////////////////////////////////////

class TestExtMhash : public TestCppExt {
 public:
  virtual bool RunTests(const std::string &which);

  bool test_mhash();
  bool test_mhash_get_hash_name();
  bool test_mhash_count();
  bool test_mhash_get_block_size();
  bool test_mhash_keygen_s2k();
};

///////////////////////////////////////////////////////////////////////////////

#endif // __TEST_EXT_MHASH_H__
