<?hh

class :xhp implements \XHPChild {
  public function getAttribute(string $_attribute): mixed {
    throw new \Exception();
  }

  public function __construct(
    \HH\dict<string, mixed> $attr,
    \HH\vec<mixed> $children,
    string $file,
    int $line,
  ) {
    throw new \Exception();
  }
}

class :foo extends :xhp {
  attribute string quux = "";

  attribute num baz @lateinit;

  attribute int bar @required;

  public function render(): :xhp {
    return
      <xhp>
        bar = {$this->:bar},
        baz = {$this->:baz},
        quux = {$this->:quux}
      </xhp>;
  }
}
