<?hh
function call_defaulted(int $arg): void {
  with_defaults($arg);
  with_defaults();
}
function with_defaults(
  int $arg = \extract_standalone_make_default(),
  float $argf = \extract_standalone_make_default(),
): void {
  throw new \Exception();
}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
/* HH_FIXME[4101] */
type EXTRACT_STANDALONE_ANY = \EXTRACT_STANDALONE_ANY_;
type EXTRACT_STANDALONE_ANY_<T> = T;
