<?hh
function call_constructors(): void {
  $a = new ImplementingBase();
  $b = new Derived(0);
}
class ImplementingBase extends \AbstractBase {}
abstract class AbstractBase {}
final class Derived extends \ImplementingBase {
  public function __construct(int $num) {
    throw new \Exception();
  }
}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
/* HH_FIXME[4101] */
type EXTRACT_STANDALONE_ANY = \EXTRACT_STANDALONE_ANY_;
type EXTRACT_STANDALONE_ANY_<T> = T;
