<?hh
class ImplementingBase extends \AbstractBase {
  public function inherited(): void {
    throw new \Exception();
  }
  protected function must_implement(): void {
    $this->inherited();
  }
}
abstract class AbstractBase {
  abstract protected function must_implement(): void;
}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
/* HH_FIXME[4101] */
type EXTRACT_STANDALONE_ANY = \EXTRACT_STANDALONE_ANY_;
type EXTRACT_STANDALONE_ANY_<T> = T;
