<?hh
class WithProperties {
  public static int $third = 0;
  public function __construct(int $arg) {
    $this->second = \extract_standalone_make_default();
    $this->first = \extract_standalone_make_default();
  }
  public int $second;
  public int $first;
}
function use_properties(WithProperties $arg): int {
  return $arg->first + $arg->second + WithProperties::$third;
}
function extract_standalone_make_default(): nothing {
  throw new Exception();
}
