<?hh
class BoundedGeneric<T as arraykey> {
  public function emptyKeyset(): \HH\keyset<T> {
    throw new \Exception();
  }
}
function with_bounded_generic_class_tparam(
  BoundedGeneric<int> $x,
): keyset<int> {
  return $x->emptyKeyset();
}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
/* HH_FIXME[4101] */
type EXTRACT_STANDALONE_ANY = \EXTRACT_STANDALONE_ANY_;
type EXTRACT_STANDALONE_ANY_<T> = T;
