//// classes-interfaces.php
<?hh

<<__ConsistentConstruct>>
interface IWithNullaryConstructor {
  public function __construct();
}

trait TDummy implements \IWithNullaryConstructor {}

class WithOptionalConstructorArguments implements \IWithNullaryConstructor {
  use \TDummy;

  public function __construct(
    ?int $x = \EXTRACT_STANDALONE_DEFAULT,
    ?string $y = \EXTRACT_STANDALONE_DEFAULT,
  ) {
    throw new \Exception();
  }

  public static function get(): this {
    return new static();
  }
}

//// __extract_standalone__.php
<?hh

const nothing EXTRACT_STANDALONE_DEFAULT = HH\FIXME\UNSAFE_CAST<mixed, nothing>("");
