<?hh
class WithConst {

  const float CFLOAT = 0.0;
  const \SomeEnum CENUM = \SomeEnum::SECOND;
}
function with_constants(): void {
  $a = WithConst::CFLOAT;
  $b = WithConst::CENUM;
  $c = SHAPE;
  $d = OPTION;
  $e = ARR;
  $f = AGE_RANGE;
  $g = MAP_INDEX;
  $h = CLASSNAME;
  $i = KEYSET;
}
const array<string, int> ARR = [];
const varray<string> MAP_INDEX = varray[];
const shape('x' => int, 'y' => \SecondEnum) SHAPE =
  shape('y' => \SecondEnum::SECOND, 'x' => 0);
const (int, ?(string, float)) OPTION = tuple(0, null);
const darray<string, int> AGE_RANGE = darray[];
const \classname<\WithConst> CLASSNAME = \WithConst::class;
enum SomeEnum: int {
  SECOND = 0;
}
const \keyset<string> KEYSET = keyset[];
enum SecondEnum: string {
  SECOND = "";
}
function extract_standalone_make_default<T>(): T {
  throw new Exception();
}


