<?hh
class A0 {

}
class WithStaticProperty {

  public static \Vector<\A> $vector = Vector {};
  public static \Map<\SomeEnum, string> $map = Map {};
}
function with_static_property(): void {
  $a = WithStaticProperty::$map;
  $b = WithStaticProperty::$vector;
}
class A extends \A0 implements \I1 {

}
enum SomeEnum: int {

}
interface I1 {

}
function extract_standalone_make_default<T>(): T {
  throw new Exception();
}


