<?hh
abstract class HasBar {}
class StringBarWrapper extends \HasBar implements \IHasBar {
  public function getBar(): this::TBar {
    throw new \Exception();
  }
}
interface IHasBar {
  const type TBar = string;
}
function with_type_const_from_implemented_interface(
  StringBarWrapper $w,
): string {
  return $w->getBar();
}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
