<?hh
class TraitBase extends \AbstractBase {
  use \ImplementingAbstractBase;
  use \T;
}
function with_traits(TraitBase $arg): void {
  $arg->routine();
}
abstract class AbstractBase {}
trait T {
  require extends \AbstractBase;
  public function routine(): void {
    throw new \Exception();
  }
}
trait ImplementingAbstractBase {}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
/* HH_FIXME[4101] */
type EXTRACT_STANDALONE_ANY = \EXTRACT_STANDALONE_ANY_;
type EXTRACT_STANDALONE_ANY_<T> = T;
