<?hh

class WithPropWithUserAttr {
  <<\MyUserAttr('blah')>> public int $i = 0;

  public function foo(): int {
    return $this->i;
  }
}

final class MyUserAttr
  implements
    \HH\ClassAttribute,
    \HH\MethodAttribute,
    \HH\TypeAliasAttribute,
    \HH\EnumAttribute,
    \HH\FunctionAttribute,
    \HH\InstancePropertyAttribute,
    \HH\StaticPropertyAttribute,
    \HH\ParameterAttribute,
    \HH\TypeParameterAttribute,
    \HH\TypeConstantAttribute {
  public function __construct(string $first, string ...$remainder)[] {
    throw new \Exception();
  }
}
