<?hh
class WithReactiveMethods {
  <<__RxShallow>>
  public function shallow_reactive(): void {
    throw new \Exception();
  }
  <<__Rx>>
  public function reactive(): void {
    throw new \Exception();
  }
  <<__Rx>>
  public function call_reactive(): void {
    $this->reactive();
  }
}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
/* HH_FIXME[4101] */
type EXTRACT_STANDALONE_ANY = \EXTRACT_STANDALONE_ANY_;
type EXTRACT_STANDALONE_ANY_<T> = T;
