<?hh
class DerivedImplementing extends Implementing implements SimpleInterface {
  use RequiringTrait;


}
abstract class AbstractBase {

}
interface SimpleInterface {
  require extends AbstractBase;


}
interface DerivedInterface extends BaseInterface {

}
interface BaseInterface {

}
trait RequiringTrait {
  require implements SimpleInterface;
  require implements BaseInterface;


}
class Implementing extends AbstractBase implements DerivedInterface {

}
function with_requiring_trait(DerivedImplementing $arg): void {}
function extract_standalone_make_default<T>(): T {
  throw new Exception();
}


