<?hh
function with_type_constants(
  WithAbstractConst::NESTED::WITH_THIS $arg,
): WithConst::TYPECONST {
  return 1;
}
class WithConst {
  const type WITH_CONSTRAINT = \A0;
  const type TYPECONST as num = int;
  const type WITH_THIS = this::WITH_CONSTRAINT;
}
class A0 {}
abstract class WithAbstractConst {
  const type NESTED = \WithConst;
}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
/* HH_FIXME[4101] */
type EXTRACT_STANDALONE_ANY = \EXTRACT_STANDALONE_ANY_;
type EXTRACT_STANDALONE_ANY_<T> = T;
