<?hh
function with_method_defined_in_trait(IWibble $w, Wibble $_): void {
  $w->f();
}
trait TWibble {
  require implements \IWibble;
  public function f(): void {
    throw new \Exception();
  }
}
interface IWibble {
  public function f(): void;
}
class Wibble implements \IWibble {
  use \TWibble;
}
<<__Rx>>
function extract_standalone_make_default(): nothing {
  throw new \Exception();
}
/* HH_FIXME[4101] */
type EXTRACT_STANDALONE_ANY = \EXTRACT_STANDALONE_ANY_;
type EXTRACT_STANDALONE_ANY_<T> = T;
