((script 78
  ((list 78
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 72
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 4 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 50
        ((() { 1 ((end_of_line 1)))
         (list 44
          ((expression_statement 44
            ((binary_expression 43
              ((variable 2 ((((whitespace 2)) variable 2 ((whitespace 1)))))
               (() = 1 ((whitespace 1)))
               (lambda_expression 38
                ((missing 0 ()) (missing 0 ()) (missing 0 ())
                 (lambda_signature 31
                  ((() "(" 1 ())
                   (list 23
                    ((list_item 11
                      ((parameter_declaration 10
                        ((missing 0 ()) (missing 0 ()) (missing 0 ())
                         (simple_type_specifier 3
                          ((() int 3 ((whitespace 1)))))
                         (() variable 2 ((whitespace 1)))
                         (simple_initializer 3
                          ((() = 1 ((whitespace 1)))
                           (literal 1 ((() decimal_literal 1 ())))))))
                       (() , 1 ((whitespace 1)))))
                     (list_item 11
                      ((parameter_declaration 11
                        ((missing 0 ()) (missing 0 ()) (missing 0 ())
                         (simple_type_specifier 3
                          ((() int 3 ((whitespace 1)))))
                         (() variable 2 ((whitespace 1)))
                         (simple_initializer 4
                          ((() = 1 ((whitespace 1)))
                           (variable 2 ((() variable 2 ())))))))
                       (missing 0 ())))))
                   (() ")" 1 ()) (() : 1 ((whitespace 1)))
                   (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))))
                 (() ==> 3 ((whitespace 1)))
                 (compound_statement 2
                  ((() { 1 ()) (missing 0 ()) (() } 1 ())))))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
