ERROR: File "needs_concrete_override_final_1.php", line 32, characters 7-7:
Method `m` is declared as `__NeedsConcrete` but overrides a non-`__NeedsConcrete` method. Please add `__NeedsConcrete` to the overridden method or remove it from the current method. (The `__NeedsConcrete` attribute indicates that a method requires `static` to point to a concrete class) (Typing[4526])
  File "needs_concrete_override_final_1.php", line 13, characters 26-26:
  It is unsafe to declare this method as `__NeedsConcrete`, since it overrides a non-`__NeedsConcrete` method
  File "needs_concrete_override_final_1.php", line 4, characters 26-26:
  Previously defined here
ERROR: File "needs_concrete_override_final_1.php", line 42, characters 22-22:
Method `m` is declared as `__NeedsConcrete` but overrides a non-`__NeedsConcrete` method. Please add `__NeedsConcrete` to the overridden method or remove it from the current method. (The `__NeedsConcrete` attribute indicates that a method requires `static` to point to a concrete class) (Typing[4526])
  File "needs_concrete_override_final_1.php", line 13, characters 26-26:
  It is unsafe to declare this method as `__NeedsConcrete`, since it overrides a non-`__NeedsConcrete` method
  File "needs_concrete_override_final_1.php", line 4, characters 26-26:
  Previously defined here
