((script 77
  ((list 77
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4
        ((() <? 2 ())
         (() name 2 ((whitespace 1) (single_line_comment 9) (end_of_line 1)))))))
     (classish_declaration 61
      ((missing 0 ()) (missing 0 ()) (missing 0 ())
       (((end_of_line 1)) class 5 ((whitespace 1)))
       (() name 1 ((whitespace 1))) (missing 0 ()) (missing 0 ())
       (missing 0 ()) (missing 0 ()) (missing 0 ()) (missing 0 ())
       (classish_body 53
        ((() { 1 ((end_of_line 1)))
         (list 47
          ((methodish_declaration 47
            ((old_attribute_specification 16
              ((((whitespace 2)) << 2 ())
               (list 12
                ((list_item 5
                  ((constructor_call 4
                    ((() name 4 ()) (missing 0 ()) (missing 0 ())
                     (missing 0 ())))
                   (() , 1 ((whitespace 1)))))
                 (list_item 6
                  ((constructor_call 6
                    ((() name 6 ()) (missing 0 ()) (missing 0 ())
                     (missing 0 ())))
                   (missing 0 ())))))
               (() >> 2 ((end_of_line 1)))))
             (function_declaration_header 25
              ((list 6 ((((whitespace 2)) public 6 ((whitespace 1)))))
               (() function 8 ((whitespace 1))) (() name 1 ()) (missing 0 ())
               (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())
               (() : 1 ((whitespace 1)))
               (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
               (missing 0 ())))
             (compound_statement 2
              ((() { 1 ()) (missing 0 ()) (() } 1 ((end_of_line 1)))))
             (missing 0 ())))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
