File "lambda_inherits_coeffect.php--g.php", line 9, characters 7-10:
This call is not allowed because its capabilities are incompatible with the context (Typing[4390])
  File "lambda_inherits_coeffect.php--g.php", line 6, characters 17-19:
  From this declaration, the context of this function body provides the capability Foo
  File "pseudofunctions.hhi", line 44, characters 12-15:
  But the function being called requires the capability IO
