[Like_type_logger] {
  "pos":"class_const_receiver.php:7",
  "categories":{
    "Expression":{"NonLike":1},
    "Class_const_receiver":{"NonLike":1},
    "Return":{"Like":1}
  }
}
[Like_type_logger] {
  "pos":"class_const_receiver.php:9",
  "categories":{
    "Expression":{"Like":5,"NonLike":2},
    "Class_const_receiver":{"Like":1},
    "Return":{"NonLike":1}
  }
}
[Like_type_logger] {
  "pos":"class_const_receiver.php:14",
  "categories":{
    "Expression":{"NonLike":6},
    "Class_const_receiver":{"NonLike":2},
    "Return":{"NonLike":1}
  }
}
[Like_type_logger] {"pos":"class_const_receiver.php:3","categories":{"Return":{"NonLike":1}}}
No errors
