[Like_type_logger] {
  "pos":"obj_get_receiver.php:7",
  "categories":{"Expression":{"NonLike":1},"Parameter":{"NonLike":1},"Return":{"Like":1}}
}
[Like_type_logger] {
  "pos":"obj_get_receiver.php:9",
  "categories":{
    "Expression":{"Like":6,"NonLike":3},
    "Obj_get_receiver":{"Like":1},
    "Return":{"NonLike":1}
  }
}
[Like_type_logger] {
  "pos":"obj_get_receiver.php:14",
  "categories":{
    "Expression":{"NonLike":7},
    "Obj_get_receiver":{"NonLike":1},
    "Return":{"NonLike":1}
  }
}
[Like_type_logger] {"pos":"obj_get_receiver.php:3","categories":{"Return":{"NonLike":1}}}
No errors
