name: \idx, kind: function, span: line 5, characters 5-20, definition: 
 idx
   kind: function
   id: function::idx
   position: line 57, characters 10-12
   span: line 57, character 1 - line 57, character 66
   modifiers: 
   params:
     $c
       kind: param
       position: line 57, characters 46-47
       span: line 57, character 22 - line 57, character 47
       modifiers: 

     $i
       kind: param
       position: line 57, characters 50-51
       span: line 57, character 50 - line 57, character 51
       modifiers: 

     $d
       kind: param
       position: line 57, characters 54-55
       span: line 57, character 54 - line 57, character 62
       modifiers: 



