name: \IfNotPackageContinuationClass, kind: class, span: line 13, characters 23-51, is_declaration: false
affects_prod_build: true
definition:
 IfNotPackageContinuationClass
   kind: class
   id: type_id::IfNotPackageContinuationClass
   position: line 5, characters 7-35
   span: line 5, character 1 - line 5, character 38
   modifiers: 


name: \IfNotPackageContinuationClass::__construct, kind: method, span: line 13, characters 23-51, is_declaration: false
affects_prod_build: true
definition:
 IfNotPackageContinuationClass
   kind: class
   id: type_id::IfNotPackageContinuationClass
   position: line 5, characters 7-35
   span: line 5, character 1 - line 5, character 38
   modifiers: 


