name: \Foo, kind: type_id, span: line 8, characters 7-9, is_declaration: false
definition:
 Foo
   kind: class
   id: type_id::Foo
   position: line 3, characters 7-9
   span: line 3, character 1 - line 5, character 1
   modifiers: 


name: \Foo::__construct, kind: method, span: line 8, characters 7-9, is_declaration: false
definition:
 __construct
   kind: method
   id: method::Foo::__construct
   position: line 4, characters 19-29
   span: line 4, character 3 - line 4, character 34
   modifiers: public 
   params:


