name: \meth_caller, kind: function, span: line 5, characters 5-27, is_declaration: false
definition:
 meth_caller
   kind: function
   id: function::meth_caller
   position: line 87, characters 10-20
   span: line 87, character 1 - line 87, character 58
   modifiers: 
   params:
     $cls_name
       kind: param
       position: line 87, characters 29-37
       span: line 87, character 22 - line 87, character 37
       modifiers: 

     $meth_name
       kind: param
       position: line 87, characters 47-56
       span: line 87, character 40 - line 87, character 56
       modifiers: 



