Member Linearization \I:
  I (PAT)
Ancestor Linearization \I:
  I (PAT)

Member Linearization \A:
  A
  I<T> (consts_only)
Ancestor Linearization \A:
  A
  I<T> (consts_only)

Member Linearization \T:
  T (copy_private_members, PAT)
  A<mixed> (requirement)
  I<mixed> (synthesized, consts_only)
Ancestor Linearization \T:
  T (copy_private_members, PAT)

Member Linearization \B:
  B
  T (copy_private_members)
  A<int>
  I<int> (consts_only)
  A<mixed> (requirement)
Ancestor Linearization \B:
  B
  A<int>
  I<int> (consts_only)
  T (copy_private_members)

Member Linearization \C:
  C
  B
  T
  A<int>
  I<int> (consts_only)
Ancestor Linearization \C:
  C
  B
  A<int>
  I<int> (consts_only)
  T
