Member Linearization \I:
  I (PAT)
Ancestor Linearization \I:
  I (PAT)

Member Linearization \C:
  C
Ancestor Linearization \C:
  C

Member Linearization \T:
  T (copy_private_members, PAT)
  I (requirement, consts_only, PAT)
  I (PAT)
  C (requirement)
Ancestor Linearization \T:
  T (copy_private_members, PAT)

Member Linearization \T2:
  T2 (copy_private_members, PAT)
Ancestor Linearization \T2:
  T2 (copy_private_members, PAT)

Member Linearization \D:
  D
  I (consts_only)
  T (copy_private_members)
  I (requirement, consts_only)
  I
  C
  C (requirement)
Ancestor Linearization \D:
  D
  C
  I (consts_only)
  T (copy_private_members)
