Typecheck for change set on line 14
File "/foo.php", line 4, characters 10-10:
Invalid return type (Typing[4110])
File "/foo.php", line 3, characters 17-22:
Expected `string`
File "/foo.php", line 4, characters 10-10:
But got `int`
(Additionally, hh_fanout errors matched hh_server errors.)

Typecheck for change set on line 22
File "/bar.php", line 4, characters 10-10:
Invalid return type (Typing[4110])
File "/bar.php", line 3, characters 17-22:
Expected `string`
File "/bar.php", line 4, characters 10-10:
But got `int`

File "/foo.php", line 4, characters 10-10:
Invalid return type (Typing[4110])
File "/foo.php", line 3, characters 17-22:
Expected `string`
File "/foo.php", line 4, characters 10-10:
But got `int`
(Additionally, hh_fanout errors matched hh_server errors.)

Typecheck for change set on line 30
File "/foo.php", line 4, characters 10-10:
Invalid return type (Typing[4110])
File "/foo.php", line 3, characters 17-22:
Expected `string`
File "/foo.php", line 4, characters 10-10:
But got `int`
(Additionally, hh_fanout errors matched hh_server errors.)
