Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: refactor)
Inline method (CodeActionKind: refactor) SELECTED
slog variable (CodeActionKind: refactor)
Extract into method (CodeActionKind: refactor)

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"",
          "range":{"end":{"character":3,"line":7},"start":{"character":0,"line":3}}
        },
        {
          "newText":"$a = \"a\";\n    $b = \"b\";\n    $x_ = 3;\n    $z = $a.$b;\n    $res = $z;\n    ",
          "range":{"end":{"character":4,"line":10},"start":{"character":4,"line":10}}
        },
        {
          "newText":"$res",
          "range":{"end":{"character":63,"line":10},"start":{"character":9,"line":10}}
        }
      ]
    }
  },
  "kind":"refactor",
  "title":"Inline method"
}

Applied edit for code action:
------------------------------------------
<?hh

class A {

  public function foo(): void {
    $x = 2;
    $a = "a";
    $b = "b";
    $x_ = 3;
    $z = $a.$b;
    $res = $z;
    $s = $res;
  }
}

