=== SDT analysis results for dynamic_call_to_function_double3.php
Intraprocedural Constraints for (ClassLike "\\f"):
  10: NeedsSDT

Interprocedural Constraints for (Function "\\f"):
     3: (CustomInterConstraint SyntacticallyNadable)

Interprocedural Constraints for (Function "\\main1"):
     5: (CustomInterConstraint SyntacticallyNadable)

Interprocedural Constraints for (Function "\\main2"):
     9: (CustomInterConstraint SyntacticallyNadable)

