=== SDT analysis results for extends1.php
Intraprocedural Constraints for \SdMe1:
  14: NeedsSDT

Interprocedural Constraints for \NadMe2:
     4: (ClassExtends (Class "\\NadMe1"))

Interprocedural Constraints for \NadMe3:
     5: (ClassExtends (Class "\\NadMe2"))

Interprocedural Constraints for \SdMe2:
    10: (ClassExtends (Class "\\SdMe1"))

Interprocedural Constraints for \SdMe3:
    11: (ClassExtends (Class "\\SdMe2"))

