=== SDT analysis results for extends1.php
Intraprocedural Constraints for (ClassLike "\\SdMe1"):
  14: NeedsSDT

Interprocedural Constraints for (ClassLike "\\NadMe1"):
     3: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "extends1.php")) })

Interprocedural Constraints for (ClassLike "\\NadMe2"):
     4: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "extends1.php")) })
     4: (Inherits (ClassLike "\\NadMe1"))

Interprocedural Constraints for (ClassLike "\\NadMe3"):
     5: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "extends1.php")) })
     5: (Inherits (ClassLike "\\NadMe2"))

Interprocedural Constraints for (ClassLike "\\SdMe1"):
     7: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "extends1.php")) })

Interprocedural Constraints for (ClassLike "\\SdMe2"):
    10: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "extends1.php")) })
    10: (Inherits (ClassLike "\\SdMe1"))

Interprocedural Constraints for (ClassLike "\\SdMe3"):
    11: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = (Some ["\\SdMe1"; "\\SdMe2"]);
     path_opt = (Some (Relative_path.Dummy, "extends1.php")) })
    11: (Inherits (ClassLike "\\SdMe2"))

Interprocedural Constraints for (Function "\\main"):
    13: (CustomInterConstraint
   { classish_kind_opt = None; hierarchy_for_final_item = (Some []);
     path_opt = (Some (Relative_path.Dummy, "extends1.php")) })

