=== SDT analysis results for is_syntactically_nadable.php
Interprocedural Constraints for (ClassLike "\\No1"):
     8: (Inherits (ClassLike "\\HH\\BuiltinEnum"))
     8: (CustomInterConstraint
   { classish_kind_opt = (Some Cenum); hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "is_syntactically_nadable.php"))
     })

Interprocedural Constraints for (ClassLike "\\No2"):
     9: (Inherits (ClassLike "\\HH\\BuiltinEnumClass"))
     9: (CustomInterConstraint
   { classish_kind_opt = (Some (Cenum_class Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "is_syntactically_nadable.php"))
     })

Interprocedural Constraints for (ClassLike "\\Yes1"):
     3: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "is_syntactically_nadable.php"))
     })

Interprocedural Constraints for (ClassLike "\\Yes2"):
     4: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Abstract));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "is_syntactically_nadable.php"))
     })

Interprocedural Constraints for (ClassLike "\\Yes3"):
     5: (CustomInterConstraint
   { classish_kind_opt = (Some Cinterface); hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "is_syntactically_nadable.php"))
     })

Interprocedural Constraints for (ClassLike "\\Yes4"):
     6: (CustomInterConstraint
   { classish_kind_opt = (Some Ctrait); hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "is_syntactically_nadable.php"))
     })

Interprocedural Constraints for (Function "\\yes_fn"):
    11: (CustomInterConstraint
   { classish_kind_opt = None; hierarchy_for_final_item = (Some []);
     path_opt = (Some (Relative_path.Dummy, "is_syntactically_nadable.php"))
     })

