=== SDT analysis results for normal_static_method_call.php
Interprocedural Constraints for (ClassLike "\\C"):
     3: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "normal_static_method_call.php"))
     })

Interprocedural Constraints for (Function "\\main"):
     7: (CustomInterConstraint
   { classish_kind_opt = None; hierarchy_for_final_item = (Some []);
     path_opt = (Some (Relative_path.Dummy, "normal_static_method_call.php"))
     })

