=== SDT analysis results for signature_formation7.php
Intraprocedural Constraints for (Function "\\needs_sdt"):
   5: NeedsSDT

Interprocedural Constraints for (ClassLike "\\C"):
     3: (CustomInterConstraint
   { classish_kind_opt = (Some (Cclass Concrete));
     hierarchy_for_final_item = None;
     path_opt = (Some (Relative_path.Dummy, "signature_formation7.php")) })

Interprocedural Constraints for (Function "\\doesnt_need_sdt"):
     7: (CustomInterConstraint
   { classish_kind_opt = None; hierarchy_for_final_item = (Some []);
     path_opt = (Some (Relative_path.Dummy, "signature_formation7.php")) })
     7: (CustomInterConstraint
   { classish_kind_opt = None; hierarchy_for_final_item = (Some []);
     path_opt = (Some (Relative_path.Dummy, "signature_formation7.php")) })

Interprocedural Constraints for (Function "\\needs_sdt"):
     5: (CustomInterConstraint
   { classish_kind_opt = None; hierarchy_for_final_item = (Some []);
     path_opt = (Some (Relative_path.Dummy, "signature_formation7.php")) })
     5: (CustomInterConstraint
   { classish_kind_opt = None; hierarchy_for_final_item = (Some []);
     path_opt = (Some (Relative_path.Dummy, "signature_formation7.php")) })

