Decls:
  class \A: { policied_props = [i:P1] }
  class \B: { policied_props = [i:P1, j:P2, k:P3] }
  class \Exception: { policied_props = [] }
  class \HH\vec: { policied_props = [] }
  class \T: { policied_props = [j:P2] }
  function \test: { kind = public }
  
Analyzing \test:
* pc: pc
* This: None
* Return: <ret>
* Exception: \Exception<\Exception, lump>
* Params:
  lvars: { $b -> \B<\B, lump'1, i=<P1>, j=<P2>, k=<P3>> }
* Final environment:
  Deps: {}
  Locals:
    lvars: { $b -> \B<\B, lump'1, i=<P1>, j=<P2>, k=<P3>> }
Constraints:
  [P3 < .k, \B < .k, \B < P1, .k < P1, pc < P1, P3 < .k'1, \B < .k'1,
   \B < P2, .k'1 < P2, pc < P2]

Flow constraints for \test:
  
  Simplified: [P3 < P2, P3 < P1]
  Raw:
  [P3 < .k, \B < .k, \B < P1, .k < P1, pc < P1, P3 < .k'1, \B < .k'1,
   \B < P2, .k'1 < P2, pc < P2]

Lattice:
 {PUBLIC < PRIVATE}

There are privacy policy errors in \test:
  Data with policy P3 appears in context P2.
  Data with policy P3 appears in context P1.
  
