--- ocaml
+++ rupro
@@ -1,128 +1,125 @@
 FoldedClass {
     name: "\\first\\firstxhp",
     pos: Pos(root|xhp_namespace_full.php, 4:13-21),
     kind: Cclass(
         Concrete,
     ),
     is_xhp: true,
     has_xhp_keyword: true,
     ancestors: {
         "\\XHPChild": XHPChild,
         "\\XHPTest": XHPTest,
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|xhp_namespace_full.php, 4:13-21),
             ty: HH\classname<this>,
             origin: "\\first\\firstxhp",
             refs: [],
         },
     },
     extends: {
         "\\XHPTest",
     },
 }
 FoldedClass {
     name: "\\second\\foo",
     pos: Pos(root|xhp_namespace_full.php, 7:13-16),
     kind: Cclass(
         Concrete,
     ),
     is_xhp: true,
     has_xhp_keyword: true,
     substs: {
         "\\first\\firstxhp": SubstContext {
             subst: Subst(
                 {},
             ),
             class_context: "\\second\\foo",
             from_req_extends: false,
         },
     },
     ancestors: {
         "\\XHPChild": XHPChild,
         "\\XHPTest": XHPTest,
         "\\first\\firstxhp": first\firstxhp,
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|xhp_namespace_full.php, 7:13-16),
             ty: HH\classname<this>,
             origin: "\\second\\foo",
             refs: [],
         },
     },
     extends: {
         "\\XHPTest",
         "\\first\\firstxhp",
     },
 }
 FoldedClass {
     name: "\\third\\bar",
     pos: Pos(root|xhp_namespace_full.php, 10:13-16),
     kind: Cclass(
         Concrete,
     ),
     is_xhp: true,
     has_xhp_keyword: true,
     substs: {
         "\\first\\firstxhp": SubstContext {
             subst: Subst(
                 {},
             ),
             class_context: "\\third\\bar",
             from_req_extends: false,
         },
     },
     ancestors: {
         "\\XHPChild": XHPChild,
         "\\XHPTest": XHPTest,
         "\\first\\firstxhp": first\firstxhp,
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|xhp_namespace_full.php, 10:13-16),
             ty: HH\classname<this>,
             origin: "\\third\\bar",
             refs: [],
         },
     },
     extends: {
         "\\XHPTest",
         "\\first\\firstxhp",
     },
 }
 FoldedClass {
     name: "\\fourth\\A",
     pos: Pos(root|xhp_namespace_full.php, 13:9-10),
     kind: Cclass(
         Concrete,
     ),
-    ancestors: {
-        "\\StringishObject": StringishObject,
-    },
     methods: {
         "__toString": FoldedElement {
             flags: (empty),
             origin: "\\fourth\\A",
             visibility: Public,
             deprecated: None,
         },
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|xhp_namespace_full.php, 13:9-10),
             ty: HH\classname<this>,
             origin: "\\fourth\\A",
             refs: [],
         },
     },
 }
