<?hh
<<file: __EnableUnstableFeatures('expression_trees')>>
class :abc {
  public function __construct() {
  }
}

class :def {
  public function __construct() {
  }
}

function f(): void {
  ExampleDsl::makeTree(
    darray[
      "path" => __FILE__,
      "start_line" => 16,
      "end_line" => 16,
      "start_column" => 13,
      "end_column" => 33,
    ],
    darray[
      "splices" => dict[],
      "functions" => vec[],
      "static_methods" => vec[],
      "variables" => vec[],
    ],
    (
      (ExampleDsl $v) ==> {
        return $v->visitXhp(
          darray[
            "path" => __FILE__,
            "start_line" => 16,
            "end_line" => 16,
            "start_column" => 13,
            "end_column" => 33,
          ],
          nameof xhp_abc,
          dict[],
          vec[
            $v->visitXhp(
              darray[
                "path" => __FILE__,
                "start_line" => 16,
                "end_line" => 16,
                "start_column" => 19,
                "end_column" => 26,
              ],
              nameof xhp_def,
              dict[],
              vec[],
            ),
          ],
        );
      }
    ),
  );
}
