File "enum_class.php", line 10, characters 27-27:
Attribute __ViaLabel is only allowed on \HH\MemberOf (Typing[4395])
File "enum_class.php", line 30, characters 6-7:
Unknown constant C in EE (Typing[4394])
File "enum_class.php", line 36, characters 20-38:
When using __ViaLabel, only type parameters bounded by enum classes and enum classes are allowed as the first parameters of \HH\MemberOf (Typing[4395])
