HHVM_DEFINE_EXTENSION(
  "facts"
  SOURCES
    exception.cpp
    ext_facts.cpp
    fact-extractor.cpp
    logging.cpp
    sqlite-autoload-db.cpp
    sqlite-key.cpp
    static-watcher.cpp
    string-data-ptr.cpp
    symbol-map.cpp
    thread-factory.cpp
    facts-store.cpp
    watchman-watcher.cpp
  HEADERS
    attribute-argument-map.h
    attribute-map.h
    autoload-db.h
    exception.h
    fact-extractor.h
    file-facts.h
    inheritance-info.h
    lazy-two-way-map.h
    logging.h
    path-and-hash.h
    path-symbols-map.h
    sqlite-autoload-db.h
    sqlite-key.h
    static-watcher.h
    string-ptr.h
    symbol-map.h
    symbol-types.h
    thread-factory.h
    facts-store.h
    watcher.h
    watchman-watcher.h
  SYSTEMLIB
    ext_facts.php
  DEPENDS
    libwatchmanclient
)
