Code actions available:
------------------------------------------
convert to 'var_dump' (CodeActionKind: quickfix) SELECTED

JSON for selected code action:
------------------------------------------
{
  "diagnostics":[],
  "edit":{
    "changes":{
      "FILE.php":[
        {
          "newText":"var_dump(",
          "range":{"end":{"character":20,"line":5},"start":{"character":4,"line":5}}
        },
        {
          "newText":")",
          "range":{"end":{"character":35,"line":5},"start":{"character":35,"line":5}}
        }
      ]
    }
  },
  "kind":"quickfix",
  "title":"convert to 'var_dump'"
}

Applied edit for code action:
------------------------------------------
<?hh

// This tests the logic for finding relevant quickfixes for a range.
// The tests in //hphp/hack/test/quickfixes exercise quickfixes more.
function f(int $x): void {
    var_dump($x/*range-end*/);
}

