<?php <<__EntryPoint>> function main() {
echo "ok\n";
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comm
}
