<?hh <<__EntryPoint>> function main(): void {
echo "ok\n";
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comment comment comment comment comment comment comment
// comment comment comm
}
