//// newmodule.hack
// @generated by hh_manual from manual/hack/17-modules/07-closures-and-function-pointers.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
new module foo {}

//// foo.hack
module foo;
internal function f() : void {
    echo "Internal f\n";
}
public function getF(): (function():void) {
    return f<>;
}
