#
# $Id$
#
# - Find libjsonc
# Find libjsonc
#
#   LIBJSONC_INCLUDE_DIR
#   LIBJSONC_LIBRARY
#   LIBJSONC_FOUND

IF (LIBJSONC_INCLUDE_DIR)
  # Already in cache, be silent
  SET(LIBJSONC_FIND_QUIETLY TRUE)
ENDIF (LIBJSONC_INCLUDE_DIR)

FIND_PATH(LIBJSONC_INCLUDE_DIR json-c/json.h)
FIND_LIBRARY(LIBJSONC_LIBRARY json-c)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBJSONC DEFAULT_MSG LIBJSONC_LIBRARY LIBJSONC_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBJSONC_LIBRARY LIBJSONC_INCLUDE_DIR)
