
if (FREETYPE_LIBRARIES AND FREETYPE_INCLUDE_DIRS)
  set (Freetype_FIND_QUIETLY TRUE)
endif (FREETYPE_LIBRARIES AND FREETYPE_INCLUDE_DIRS)

find_path(FREETYPE_INCLUDE_DIRS NAMES freetype/freetype.h)
if (NOT FREETYPE_INCLUDE_DIRS)
	find_path(FREETYPE_INCLUDE_DIRS NAMES freetype2/freetype/freetype.h)
	if (FREETYPE_INCLUDE_DIRS)
		set(FREETYPE_INCLUDE_DIRS "${FREETYPE_INCLUDE_DIRS}/freetype2" CACHE PATH "Freetype include directory" FORCE)
	endif()
endif()

find_library(FREETYPE_LIBRARIES NAMES freetype)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Freetype DEFAULT_MSG
    FREETYPE_LIBRARIES
    FREETYPE_INCLUDE_DIRS)

mark_as_advanced(FREETYPE_INCLUDE_DIRS FREETYPE_LIBRARIES)
