
if (LIBVPX_LIBRARIES AND LIBVPX_INCLUDE_DIRS)
  set (LibVpx_FIND_QUIETLY TRUE)
endif (LIBVPX_LIBRARIES AND LIBVPX_INCLUDE_DIRS)

find_path(LIBVPX_INCLUDE_DIRS NAMES vpx_codec.h)
find_library(LIBVPX_LIBRARIES NAMES vpx)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibVpx DEFAULT_MSG
    LIBVPX_LIBRARIES
    LIBVPX_INCLUDE_DIRS)

mark_as_advanced(LIBVPX_INCLUDE_DIRS LIBVPX_LIBRARIES)
