if (EDITLINE_LIBRARIES AND EDITLINE_INCLUDE_DIRS)
  set (Editline_FIND_QUIETLY TRUE)
endif (EDITLINE_LIBRARIES AND EDITLINE_INCLUDE_DIRS)

find_path(EDITLINE_INCLUDE_DIRS NAMES editline/readline.h)
find_library(EDITLINE_LIBRARIES NAMES edit)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Editline DEFAULT_MSG
    EDITLINE_LIBRARIES
    EDITLINE_INCLUDE_DIRS)

mark_as_advanced(EDITLINE_INCLUDE_DIRS EDITLINE_LIBRARIES)
