IF(CCLIENT_FOUND)
  SET(CCLIENT_FIND_QUIETLY TRUE)
ENDIF(CCLIENT_FOUND)

FIND_PATH(CCLIENT_INCLUDE_PATH
  NAMES c-client.h
  PATH_SUFFIXES c-client imap
  PATHS /usr/include /usr/local/include /usr/pkg/include
)

FIND_LIBRARY(CCLIENT_LIBRARY
  NAMES c-client c-client4
  PATHS /lib /usr/lib /usr/local/lib /usr/pkg/lib
)

IF (CCLIENT_INCLUDE_PATH AND CCLIENT_LIBRARY)
  SET(CCLIENT_FOUND TRUE)
ENDIF()

MARK_AS_ADVANCED(
  CCLIENT_INCLUDE_PATH
  CCLIENT_LIBRARY
)
