File "call_on_subtype_of_condition_type.php", line 12, characters 12-21:
Cannot invoke conditionally reactive function in reactive context, because at least one reactivity condition is not met. (Typing[4237])
File "call_on_subtype_of_condition_type.php", line 12, characters 12-16:
Receiver type must be a subtype of \Rx2, now \A.
File "call_on_subtype_of_condition_type.php", line 16, characters 19-19:
This is the function declaration
