File "test_method_call.php", line 24, characters 3-14:
  <expr#1> as Something
File "test_method_call.php", line 13, characters 16-24:
Reactive functions can only call other reactive functions. (Typing[4200])
File "test_method_call.php", line 3, characters 19-29:
This function is normal.
File "test_method_call.php", line 26, characters 3-13:
Cannot call mutable function on immutable expression (Typing[4214])
File "test_method_call.php", line 6, characters 19-24:
This function is marked `<<__Mutable>>`, so it has a mutable `$this`.
