WARN: File "needs_concrete_fine_grained.php", line 4, characters 9-20:
Dangerous call to `Base::concreteOnly` (a `<<__NeedsConcrete>>` method). It is expecting a concrete receiver but `Base` is not concrete. (Warn[12024])
  File "needs_concrete_fine_grained.php", line 12, characters 26-37:
  Declaration is here
ERROR: File "needs_concrete_fine_grained.php", line 15, characters 13-26:
Dangerous access of abstract member `Base::abstractMethod`; it may be abstract and `static` might refer to an abstract class here. Consider adding the `__NeedsConcrete` attribute to the containing method. (Typing[4529])
  File "needs_concrete_fine_grained.php", line 9, characters 35-48:
  Declaration is here
ERROR: File "needs_concrete_fine_grained.php", line 16, characters 9-14:
Dangerous instantiation via `static`: `static` might refer to a non-concrete class here. Consider adding the `__NeedsConcrete` attribute to the containing method. (Typing[4530])
  File "needs_concrete_fine_grained.php", line 8, characters 16-19:
  Declaration is here
ERROR: File "needs_concrete_fine_grained.php", line 23, characters 11-22:
Dangerous call to `Child::concreteOnly` (a `<<__NeedsConcrete>>` method) via `self`. It requires `static` to refer to a concrete class, but `self` sets `static` to a class that may not be concrete. (Typing[4528])
  File "needs_concrete_fine_grained.php", line 12, characters 26-37:
  Declaration is here
ERROR: File "needs_concrete_fine_grained.php", line 24, characters 13-24:
Dangerous call to `Base::concreteOnly` (a `<<__NeedsConcrete>>` method) via `parent`. It requires `static` to refer to a concrete class, but `parent` sets `static` to a class that may not be concrete. (Typing[4528])
  File "needs_concrete_fine_grained.php", line 12, characters 26-37:
  Declaration is here
ERROR: File "needs_concrete_fine_grained.php", line 25, characters 13-24:
Dangerous call to `Child::concreteOnly` (a `<<__NeedsConcrete>>` method) via `static`. It requires `static` to refer to a concrete class but `static` may not be concrete. (Typing[4528])
  File "needs_concrete_fine_grained.php", line 12, characters 26-37:
  Declaration is here
