error: Parsing[1002] Assignments can no longer be used as expressions. Pull the assignment out into a separate statement. [1]

cross_package_with_package_syntax_invalid_conds.php--pkg3.php:14:11
12 |         pkg1_call(); // error; function calls don't register package info
13 |       }
[1] 14 |       if ($loaded = package pkg1) {
15 |         pkg1_call(); // error; assignments aren't allowed in conditionals
16 |

error: Typing[4472] Cannot access an element which belongs to package pkg1 from package pkg3 [1]
-> This is from cross_package_with_package_syntax_invalid_conds.php--pkg1.php, which belongs to package pkg1 [2]
-> But cross_package_with_package_syntax_invalid_conds.php--pkg3.php is in package pkg3, and package pkg3 does not include package pkg1 [3]

cross_package_with_package_syntax_invalid_conds.php--pkg3.php:6:9
4 |     public function test() : void {
5 |       if (package pkg1 == package pkg4) {
[1]  6 |         pkg1_call(); // error; comparison binops don't register package info
7 |       }
8 |       if (package pkg1 is bool) {

cross_package_with_package_syntax_invalid_conds.php--pkg1.php:2:10
1 | <?hh
[2]  2 | function pkg1_call(): void {}

PACKAGES.toml:13:11
11 | includes = ["pkg1"]
12 |
[3] 13 | [packages.pkg3]
14 | includes = ["pkg2"]
15 |

error: Typing[4472] Cannot access an element which belongs to package pkg1 from package pkg3 [1]
-> This is from cross_package_with_package_syntax_invalid_conds.php--pkg1.php, which belongs to package pkg1 [2]
-> But cross_package_with_package_syntax_invalid_conds.php--pkg3.php is in package pkg3, and package pkg3 does not include package pkg1 [3]

cross_package_with_package_syntax_invalid_conds.php--pkg3.php:9:9
7 |       }
8 |       if (package pkg1 is bool) {
[1]  9 |         pkg1_call(); // error; type ops don't register package info
10 |       }
11 |       if ($this->expect(package pkg1)) {

cross_package_with_package_syntax_invalid_conds.php--pkg1.php:2:10
1 | <?hh
[2]  2 | function pkg1_call(): void {}

PACKAGES.toml:13:11
11 | includes = ["pkg1"]
12 |
[3] 13 | [packages.pkg3]
14 | includes = ["pkg2"]
15 |

error: Typing[4472] Cannot access an element which belongs to package pkg1 from package pkg3 [1]
-> This is from cross_package_with_package_syntax_invalid_conds.php--pkg1.php, which belongs to package pkg1 [2]
-> But cross_package_with_package_syntax_invalid_conds.php--pkg3.php is in package pkg3, and package pkg3 does not include package pkg1 [3]

cross_package_with_package_syntax_invalid_conds.php--pkg3.php:12:9
10 |       }
11 |       if ($this->expect(package pkg1)) {
[1] 12 |         pkg1_call(); // error; function calls don't register package info
13 |       }
14 |       if ($loaded = package pkg1) {

cross_package_with_package_syntax_invalid_conds.php--pkg1.php:2:10
1 | <?hh
[2]  2 | function pkg1_call(): void {}

PACKAGES.toml:13:11
11 | includes = ["pkg1"]
12 |
[3] 13 | [packages.pkg3]
14 | includes = ["pkg2"]
15 |

error: Typing[4472] Cannot access an element which belongs to package pkg1 from package pkg3 [1]
-> This is from cross_package_with_package_syntax_invalid_conds.php--pkg1.php, which belongs to package pkg1 [2]
-> But cross_package_with_package_syntax_invalid_conds.php--pkg3.php is in package pkg3, and package pkg3 does not include package pkg1 [3]

cross_package_with_package_syntax_invalid_conds.php--pkg3.php:15:9
13 |       }
14 |       if ($loaded = package pkg1) {
[1] 15 |         pkg1_call(); // error; assignments aren't allowed in conditionals
16 |
17 |         if ($loaded) {

cross_package_with_package_syntax_invalid_conds.php--pkg1.php:2:10
1 | <?hh
[2]  2 | function pkg1_call(): void {}

PACKAGES.toml:13:11
11 | includes = ["pkg1"]
12 |
[3] 13 | [packages.pkg3]
14 | includes = ["pkg2"]
15 |

error: Typing[4472] Cannot access an element which belongs to package pkg1 from package pkg3 [1]
-> This is from cross_package_with_package_syntax_invalid_conds.php--pkg1.php, which belongs to package pkg1 [2]
-> But cross_package_with_package_syntax_invalid_conds.php--pkg3.php is in package pkg3, and package pkg3 does not include package pkg1 [3]

cross_package_with_package_syntax_invalid_conds.php--pkg3.php:18:11
16 |
17 |         if ($loaded) {
[1] 18 |           pkg1_call(); // error; cannot infer $loaded to be a package expression
19 |         }
20 |       }

cross_package_with_package_syntax_invalid_conds.php--pkg1.php:2:10
1 | <?hh
[2]  2 | function pkg1_call(): void {}

PACKAGES.toml:13:11
11 | includes = ["pkg1"]
12 |
[3] 13 | [packages.pkg3]
14 | includes = ["pkg2"]
15 |

warning: Warn[12009] This is check is always true. The expression on the left has type bool which is a subtype of bool. [1]

cross_package_with_package_syntax_invalid_conds.php--pkg3.php:8:11
6 |         pkg1_call(); // error; comparison binops don't register package info
7 |       }
[1] 8 |       if (package pkg1 is bool) {
9 |         pkg1_call(); // error; type ops don't register package info
10 |       }

7 errors found