error: Typing[4472] Cannot access an element which belongs to package pkg2 from package pkg1 [1]
-> This is from illegal_cross_package_with_package_override3.php--foo.php, which belongs to package pkg2 [2]
-> But illegal_cross_package_with_package_override3.php--bar.php is in package pkg1, and package pkg1 does not include package pkg2 [3]

illegal_cross_package_with_package_override3.php--bar.php:4:14
2 | // package pkg1
3 | function bar(): void {
[1] 4 |   $foo = new Foo();
5 | }

illegal_cross_package_with_package_override3.php--foo.php:4:7
2 | // package pkg2
3 | <<file: __PackageOverride('pkg2')>>
[2] 4 | class Foo {}

PACKAGES.toml:3:11
1 | [packages]
2 |
[3] 3 | [packages.pkg1]
4 | include_paths=["//"]
5 |

1 error found