// @generated by hh_manual from manual/hack/15-asynchronous-operations/10-exceptions.md
// @codegen-command : buck run fbcode//hphp/hack/src/hh_manual:hh_manual extract fbcode/hphp/hack/manual/hack/
async function exception_thrower(): Awaitable<int> {
  throw new \Exception("Return exception handle");
}

async function non_exception_thrower(): Awaitable<int> {
  return 2;
}

<<__EntryPoint>>
async function multiple_waithandle_exception(): Awaitable<void> {
  // You will get a fatal error here with the exception thrown
  concurrent {
    $r1 = await exception_thrower();
    $r2 = await non_exception_thrower();
  }

  // This won't happen
  var_dump($r1, $r2);
}
