[(Fun
    { f_span = [2:1-8:2]; f_readonly_this = None; f_annotation = (); 
      f_mode = Mstrict; f_readonly_ret = None; f_ret = ((), (Some ([2:33-37], (Hprim Tvoid)))); 
      f_name = ([2:10-29], "\\anons_with_ctx_list"); f_tparams = []; 
      f_where_constraints = []; f_variadic = FVnonVariadic; f_params = []; 
      f_ctxs = None; f_unsafe_ctxs = None;
      f_body =
      { fb_ast =
        [([3:3-63],
          (Expr
             ([3:3-62],
              (Binop ((Eq None), ([3:3-15], (Lvar ([3:3-15], $anon_no_use))),
                 ([3:18-62],
                  (Efun (
                     { f_span = [3:18-62]; f_readonly_this = None; f_annotation = (); 
                       f_mode = Mstrict; f_readonly_ret = None; f_ret = ((), (Some ([3:38-41], (Hprim Tint)))); 
                       f_name = ([3:18-62], ";anonymous"); f_tparams = []; 
                       f_where_constraints = []; f_variadic = FVnonVariadic; 
                       f_params = []; f_ctxs = (Some ([3:28-36], [([3:29-35], (Happly (([3:29-35], "\\HH\\Contexts\\output"), [])))]));
                       f_unsafe_ctxs = (Some ([3:28-36], [([3:29-35], (Happly (([3:29-35], "\\HH\\Contexts\\Unsafe\\output"), [])))]));
                       f_body = { fb_ast = [([3:51-60], (Return (Some ([3:58-59], (Int "0")))))]; fb_annotation = Named }; 
                       f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
                       f_external = false;
                       f_namespace =
                       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
                         ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; 
                         ns_const_uses = <opaque>; ns_name = None; ns_auto_ns_map = []; 
                         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
                       f_doc_comment = None },
                     [])))
                 )))));
          ([5:3-10], (Expr ([5:3-9], (Binop ((Eq None), ([5:3-5], (Lvar ([5:3-5], $x))), ([5:8-9], (Int "1")))))));
          ([6:3-64],
           (Expr
              ([6:3-63],
               (Binop ((Eq None), ([6:3-15], (Lvar ([6:3-15], $anon_no_ret))),
                  ([6:18-63],
                   (Efun (
                      { f_span = [6:18-63]; f_readonly_this = None; f_annotation = (); 
                        f_mode = Mstrict; f_readonly_ret = None; f_ret = ((), None); 
                        f_name = ([6:18-63], ";anonymous"); f_tparams = []; 
                        f_where_constraints = []; f_variadic = FVnonVariadic; 
                        f_params = []; f_ctxs = (Some ([6:28-37], [([6:29-36], (Happly (([6:29-36], "\\HH\\Contexts\\non_det"), [])))]));
                        f_unsafe_ctxs = (Some ([6:28-37], [([6:29-36], (Happly (([6:29-36], "\\HH\\Contexts\\Unsafe\\non_det"), [])))]));
                        f_body = { fb_ast = [([6:51-61], (Return (Some ([6:58-60], (Lvar ([6:58-60], $x))))))]; fb_annotation = Named }; 
                        f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
                        f_external = false;
                        f_namespace =
                        { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
                          ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; 
                          ns_const_uses = <opaque>; ns_name = None; ns_auto_ns_map = []; 
                          ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
                        f_doc_comment = None },
                      [([6:43-47], $ret)])))
                  )))));
          ([7:3-57],
           (Expr
              ([7:3-56],
               (Binop ((Eq None), ([7:3-8], (Lvar ([7:3-8], $anon))),
                  ([7:11-56],
                   (Efun (
                      { f_span = [7:11-56]; f_readonly_this = None; f_annotation = (); 
                        f_mode = Mstrict; f_readonly_ret = None; f_ret = ((), (Some ([7:27-30], (Hprim Tint)))); 
                        f_name = ([7:11-56], ";anonymous"); f_tparams = []; 
                        f_where_constraints = []; f_variadic = FVnonVariadic; 
                        f_params = []; f_ctxs = (Some ([7:21-25], [([7:22-24], (Happly (([7:22-24], "\\HH\\Contexts\\rx"), [])))]));
                        f_unsafe_ctxs = (Some ([7:21-25], [([7:22-24], (Happly (([7:22-24], "\\HH\\Contexts\\Unsafe\\rx"), [])))]));
                        f_body = { fb_ast = [([7:44-54], (Return (Some ([7:51-53], (Lvar ([7:51-53], $x))))))]; fb_annotation = Named }; 
                        f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
                        f_external = false;
                        f_namespace =
                        { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
                          ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; 
                          ns_const_uses = <opaque>; ns_name = None; ns_auto_ns_map = []; 
                          ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
                        f_doc_comment = None },
                      [([7:36-40], $ret)])))
                  )))))
          ];
        fb_annotation = Named };
      f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = []; 
      f_external = false;
      f_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      f_doc_comment = None })