[(Class
    { c_span = [3:1-5:2]; c_annotation = (); c_mode = Mstrict; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Abstract); 
      c_name = ([3:16-17], "\\C"); c_tparams = []; c_extends = []; c_uses = []; 
      c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; c_implements = []; 
      c_where_constraints = []; c_consts = [];
      c_typeconsts =
      [{ c_tconst_user_attributes = []; c_tconst_name = ([4:22-23], "C");
         c_tconst_kind =
         (TCAbstract
            { c_atc_as_constraint = (Some ([4:27-40], (Hintersection [([4:28-39], (Happly (([4:28-39], "\\HH\\Contexts\\write_props"), [])))]))); c_atc_super_constraint = None; c_atc_default = None });
         c_tconst_span = [4:3-41]; c_tconst_doc_comment = None; c_tconst_is_ctx = true }
        ];
      c_vars = []; c_methods = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_docs_url = None; 
      c_enum = None; c_doc_comment = None; c_emit_id = None; c_internal = false; 
      c_module = None });
  (Class
     { c_span = [7:1-9:2]; c_annotation = (); c_mode = Mstrict; c_final = false; 
       c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
       c_name = ([7:7-8], "\\D"); c_tparams = []; c_extends = []; c_uses = []; 
       c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; c_implements = []; 
       c_where_constraints = []; c_consts = [];
       c_typeconsts =
       [{ c_tconst_user_attributes = []; c_tconst_name = ([8:13-14], "C");
          c_tconst_kind = (TCConcrete { c_tc_type = ([8:34-44], (Hintersection [([8:35-43], (Happly (([8:35-43], "\\HH\\Contexts\\defaults"), [])))])) }); 
          c_tconst_span = [8:3-45]; c_tconst_doc_comment = None; c_tconst_is_ctx = true }
         ];
       c_vars = []; c_methods = []; c_xhp_children = []; c_xhp_attrs = [];
       c_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       c_user_attributes = []; c_file_attributes = []; c_docs_url = None; 
       c_enum = None; c_doc_comment = None; c_emit_id = None; c_internal = false; 
       c_module = None })
  ]
