[(Class
    { c_span = [3:1-8:2]; c_annotation = (); c_mode = Mstrict; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = Cabstract; 
      c_name = ([3:16-26], "\\CWithConst"); c_tparams = []; c_extends = []; 
      c_uses = []; c_use_as_alias = []; c_insteadof_alias = []; c_xhp_attr_uses = []; 
      c_xhp_category = None; c_reqs = []; c_implements = []; c_implements_dynamic = false; 
      c_where_constraints = []; c_consts = [];
      c_typeconsts =
      [{ c_tconst_user_attributes = []; c_tconst_name = ([4:22-24], "C1"); 
         c_tconst_kind = (TCAbstract { c_atc_as_constraint = None; c_atc_super_constraint = None; c_atc_default = None }); 
         c_tconst_span = [4:3-25]; c_tconst_doc_comment = None; c_tconst_is_ctx = true };
        { c_tconst_user_attributes = []; c_tconst_name = ([5:22-24], "C2");
          c_tconst_kind =
          (TCAbstract
             { c_atc_as_constraint = None; c_atc_super_constraint = None; c_atc_default = (Some ([5:27-31], (Hintersection [([5:28-30], (Happly (([5:28-30], "\\HH\\Contexts\\io"), [])))]))) });
          c_tconst_span = [5:3-32]; c_tconst_doc_comment = None; c_tconst_is_ctx = true };
        { c_tconst_user_attributes = []; c_tconst_name = ([6:22-24], "C3");
          c_tconst_kind =
          (TCAbstract
             { c_atc_as_constraint =
               (Some ([6:28-38], (Hintersection [([6:29-31], (Happly (([6:29-31], "\\HH\\Contexts\\io"), []))); ([6:33-37], (Happly (([6:33-37], "\\HH\\Contexts\\rand"), [])))])));
               c_atc_super_constraint = None; c_atc_default = None });
          c_tconst_span = [6:3-39]; c_tconst_doc_comment = None; c_tconst_is_ctx = true };
        { c_tconst_user_attributes = []; c_tconst_name = ([7:22-24], "C4");
          c_tconst_kind =
          (TCAbstract
             { c_atc_as_constraint = (Some ([7:45-49], (Hintersection [([7:46-48], (Happly (([7:46-48], "\\HH\\Contexts\\io"), [])))])));
               c_atc_super_constraint =
               (Some ([7:31-41], (Hintersection [([7:32-34], (Happly (([7:32-34], "\\HH\\Contexts\\io"), []))); ([7:36-40], (Happly (([7:36-40], "\\HH\\Contexts\\rand"), [])))])));
               c_atc_default = (Some ([7:52-56], (Hintersection [([7:53-55], (Happly (([7:53-55], "\\HH\\Contexts\\io"), [])))]))) });
          c_tconst_span = [7:3-57]; c_tconst_doc_comment = None; c_tconst_is_ctx = true }
        ];
      c_vars = []; c_methods = []; c_attributes = []; c_xhp_children = []; 
      c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_enum = None; 
      c_doc_comment = None; c_emit_id = None })