<?hh

/*
   +-------------------------------------------------------------+
   | Copyright (c) 2014 Facebook, Inc. (http://www.facebook.com) |
   +-------------------------------------------------------------+
*/


class PassengerJet extends Aircraft 
{
	public function getMaxSpeed()
	{
		// implement method
		return 550;
	}

	public function getMaxAltitude()
	{
		// implement method
		return 30000;
	}

	// ...
}
