warning: Lint[5628] This `as` assertion will always succeed and hence is redundant. The expression on the left has a type `A` which is a subtype of `A`.
   --> as_always_succeeds0.php
  8 |   $a as A;
    |   ^^^^^^^


warning: Lint[5808] This expression has a type lie that makes Hack type checker think it is a different type than what it inferred. It is achieved using a type assertion through `as`. This can lead to fatals or subtle and latent behaviour changes. Even if the code is correct at the moment, the type checker won't produce any signal when the prerequisites for correctness change.
   --> as_always_succeeds0.php
  8 |   $a as A;
    |   ^^^^^^^


