File "duplicate_key.php", line 5, characters 10-46:
This expression has a type lie that makes Hack type checker think it is a different type than what it inferred. It is achieved using an `HH_FIXME` comment. This can lead to fatals or subtle and latent behaviour changes. Even if the code is correct at the moment, the type checker won't produce any signal when the prerequisites for correctness change. (Lint[5806])
File "duplicate_key.php", line 12, characters 10-46:
This expression has a type lie that makes Hack type checker think it is a different type than what it inferred. It is achieved using an `HH_FIXME` comment. This can lead to fatals or subtle and latent behaviour changes. Even if the code is correct at the moment, the type checker won't produce any signal when the prerequisites for correctness change. (Lint[5806])
File "duplicate_key.php", line 14, characters 5-7:
This assignment to key `'a'` overwrites previous assignment on line 13. (Lint[5575])
File "duplicate_key.php", line 30, characters 5-7:
This assignment to key `'p'` overwrites previous assignments on lines 28, 29. (Lint[5575])
File "duplicate_key.php", line 46, characters 5-7:
This assignment to key `'x'` overwrites previous assignments on lines 44, 45. (Lint[5575])
