File "exception_as_int.php", line 4, characters 3-38:
This `as` assertion will always fail and lead to an exception at runtime. The expression on the left has type `Exception` which shares no values with `int`. (Lint[5629])
File "exception_as_int.php", line 4, characters 3-38:
This expression has a type lie that makes Hack type checker think it is a different type than what it inferred. It is achieved using a type assertion through `as`. This can lead to fatals or subtle and latent behaviour changes. Even if the code is correct at the moment, the type checker won't produce any signal when the prerequisites for correctness change. (Lint[5808])
