File "invalid_disjoint_check_methods.php", line 6, characters 5-19:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 7, characters 5-6:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 8, characters 6-9:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 13, characters 5-33:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 14, characters 5-22:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 15, characters 6-9:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 16, characters 13-60:
This call to 'contains' will always return the same value, because type Map<string, mixed> is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 26, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 29, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 32, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 35, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 38, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 41, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 44, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 47, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type int. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 50, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type Baz. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 53, characters 10-29:
This call to 'contains' will always return the same value, because type Foo is disjoint from type <expr#4> as Bar. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 56, characters 10-29:
This call to 'contains' will always return the same value, because type Bar is disjoint from type Foo. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 104, characters 10-29:
This call to 'contains' will always return the same value, because type string is disjoint from type EnumInt. (Lint[5638])
File "invalid_disjoint_check_methods.php", line 108, characters 19-29:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 108, characters 39-39:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 109, characters 71-72:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 109, characters 82-85:
Explicit `dynamic` type usage in APIs turn off most checks the Hack type checker performs. This frequently leads to reliability issues. (Lint[5809])
File "invalid_disjoint_check_methods.php", line 121, characters 3-25:
Non-dynamic calls to 'isEqual' will always return the same value, because type int is disjoint from type string. (Lint[5638])
