File "invariant.php", line 5, characters 13-16:
Your expression always evaluates to true. Because of this, invariant() will never throw an exception here. If this is the behavior you want simply remove or comment out the line. (Lint[5581])
File "invariant.php", line 9, characters 13-18:
Your expression always evaluates to true. Because of this, invariant() will never throw an exception here. If this is the behavior you want simply remove or comment out the line. (Lint[5581])
File "invariant.php", line 13, characters 13-17:
Your expression always evaluates to false. Because of this, invariant() will always throw an exception here. If this is the behavior you want, please use invariant_violation() explicitly instead. (Lint[5581])
