warning: Lint[5581] Your expression always evaluates to true. Because of this, invariant() will never throw an exception here. If this is the behavior you want simply remove or comment out the line.
   --> invariant.php
  5 |   invariant(true, 'This should cause lint error');
    |             ^^^^


warning: Lint[5581] Your expression always evaluates to true. Because of this, invariant() will never throw an exception here. If this is the behavior you want simply remove or comment out the line.
   --> invariant.php
  9 |   invariant(!!true, 'This should cause lint error');
    |             ^^^^^^


warning: Lint[5581] Your expression always evaluates to false. Because of this, invariant() will always throw an exception here. If this is the behavior you want, please use invariant_violation() explicitly instead.
   --> invariant.php
 13 |   invariant(!true, 'This should cause lint error');
    |             ^^^^^


