File "nullsafe3.php", line 3, characters 10-10:
f is the only function declared in nullsafe3.php, so that file should be named f.php instead. (Lint[5564])
File "nullsafe3.php", line 4, characters 8-9:
This expression has a type lie that makes Hack type checker think it is a different type than what it inferred. It is achieved using an `HH_FIXME` comment. This can lead to fatals or subtle and latent behaviour changes. Even if the code is correct at the moment, the type checker won't produce any signal when the prerequisites for correctness change. (Lint[5806])
File "nullsafe3.php", line 4, characters 8-15:
You are using the `?->` operator but this object cannot be null. You can use the `->` operator instead. (Lint[5633])
