File "null_check_strict3.php", line 3, characters 10-10:
f is the only function declared in null_check_strict3.php, so that file should be named f.php instead. (Lint[5564])
File "null_check_strict3.php", line 4, characters 7-8:
There are no statements in the body of this `if` branch. (Lint[5556])
File "null_check_strict3.php", line 6, characters 8-9:
This is a sketchy null check on an expression of type ?string.
It detects nulls, but it will also detect many other falsy values, including `false`, `0`, `0.0`, `""`, `"0"`, empty Containers, and more.
If you want to test for them, please consider doing so explicitly.
If you only meant to test for `null`, use `$x ?? $default` instead of `$x ?: $default` (Lint[5618])
File "null_check_strict3.php", line 6, characters 8-9:
`$x` is a sketchy condition: testing the truthiness of a string may not behave as expected.
The values `""` and `"0"` are both considered falsy. To check for non-emptiness, use `!Str\is_empty($x)`. (Lint[5623])
