warning: Lint[5644] The boolean expression is pointless
   --> pointless_booleans.php
  4 |      ($x === 1) && true; // pointless
    |      ^^^^^^^^^^^^^^^^^^


warning: Lint[5644] The boolean expression is pointless
   --> pointless_booleans.php
  8 |      ($x === 2) || false; // pointless
    |      ^^^^^^^^^^^^^^^^^^^


warning: Lint[5644] The boolean expression is always false
   --> pointless_booleans.php
 12 |      ($x === 3) && false; // always false
    |      ^^^^^^^^^^^^^^^^^^^


warning: Lint[5644] The boolean expression is always false
   --> pointless_booleans.php
 16 |      ($x > 3) && false; // always false
    |      ^^^^^^^^^^^^^^^^^


warning: Lint[5644] The boolean expression is always true
   --> pointless_booleans.php
 20 |      true || false; // always true
    |      ^^^^^^^^^^^^^


warning: Lint[5644] The boolean expression is always false
   --> pointless_booleans.php
 24 |      false && ($x === 3); // always false
    |      ^^^^^^^^^^^^^^^^^^^


warning: Lint[5644] The boolean expression is always false
   --> pointless_booleans.php
 32 |      $x > 3 && false; // always false
    |      ^^^^^^^^^^^^^^^


