File "pointless_booleans.php", line 4, characters 6-23:
The boolean expression is pointless (Lint[5644])
File "pointless_booleans.php", line 8, characters 6-24:
The boolean expression is pointless (Lint[5644])
File "pointless_booleans.php", line 12, characters 6-24:
The boolean expression is always false (Lint[5644])
File "pointless_booleans.php", line 16, characters 6-22:
The boolean expression is always false (Lint[5644])
File "pointless_booleans.php", line 20, characters 6-18:
The boolean expression is always true (Lint[5644])
File "pointless_booleans.php", line 24, characters 6-24:
The boolean expression is always false (Lint[5644])
File "pointless_booleans.php", line 32, characters 6-20:
The boolean expression is always false (Lint[5644])
