File "truthiness_test_03.php", line 4, characters 7-8:
`$x` is a sketchy condition: testing the truthiness of Traversable<int> may not behave as expected.
A value of this type may be truthy even when empty.
Hack collections and arrays are falsy when empty, but user-defined Traversables will always be truthy, even when empty.
If you would like to only allow containers which are falsy when empty, use the `Container` or `KeyedContainer` interfaces. (Lint[5623])
