warning: Lint[5638] This call to 'containsKey' will always return the same value, because type string is disjoint from type int.
   --> vec_contains.php
  4 |   return $vs->containsKey(3);
    |          ^^^^^^^^^^^^^^^^^^^


warning: Lint[5638] This call to 'linearSearch' will always return the same value, because type string is disjoint from type null.
   --> vec_contains.php
  9 |   return $vs->linearSearch(null);
    |          ^^^^^^^^^^^^^^^^^^^^^^^


