=== IFC analysis results for foreach_dynamic.php
File "foreach_dynamic.php", line 44, characters 5-21:
Unable to analyze information flow for dynamic. This might be unsafe. (Typing[4385])
File "foreach_dynamic.php", line 44, characters 5-21:
Data with policy `B` appears in context `D`. (Typing[4379])
  File "foreach_dynamic.php", line 29, characters 35-44:
  This may be the data source with policy `B`
  File "foreach_dynamic.php", line 30, characters 33-41:
  This may be the data sink with policy `D`
  File "foreach_dynamic.php", line 35, characters 11-12:
  Another program point contributing to the illegal flow
  File "foreach_dynamic.php", line 39, characters 5-15:
  Another program point contributing to the illegal flow
  File "foreach_dynamic.php", line 42, characters 11-12:
  Another program point contributing to the illegal flow
File "foreach_dynamic.php", line 13, characters 5-19:
Data with policy `PRIVATE` appears in context `PUBLIC`. (Typing[4379])
  File "foreach_dynamic.php", line 5, characters 18-30:
  This may be the data source with policy `PRIVATE`
  File "foreach_dynamic.php", line 7, characters 18-29:
  This may be the data sink with policy `PUBLIC`
