=== IFC analysis results for switch.php
File "switch.php", line 61, characters 3-13:
Data with policy `A` appears in context `B`. (Typing[4379])
  File "switch.php", line 6, characters 14-19:
  This may be the data source with policy `A`
  File "switch.php", line 9, characters 14-19:
  This may be the data sink with policy `B`
  File "switch.php", line 55, characters 7-17:
  Another program point contributing to the illegal flow
File "switch.php", line 73, characters 7-16:
Data with policy `A` appears in context `B`. (Typing[4379])
  File "switch.php", line 6, characters 14-19:
  This may be the data source with policy `A`
  File "switch.php", line 9, characters 14-19:
  This may be the data sink with policy `B`
  File "switch.php", line 68, characters 11-19:
  Another program point contributing to the illegal flow
File "switch.php", line 29, characters 7-17:
Data with policy `A` appears in context `B`. (Typing[4379])
  File "switch.php", line 6, characters 14-19:
  This may be the data source with policy `A`
  File "switch.php", line 9, characters 14-19:
  This may be the data sink with policy `B`
  File "switch.php", line 28, characters 10-14:
  Another program point contributing to the illegal flow
File "switch.php", line 44, characters 7-17:
Data with policy `A` appears in context `B`. (Typing[4379])
  File "switch.php", line 6, characters 14-19:
  This may be the data source with policy `A`
  File "switch.php", line 9, characters 14-19:
  This may be the data sink with policy `B`
  File "switch.php", line 41, characters 7-17:
  Another program point contributing to the illegal flow
File "switch.php", line 85, characters 3-12:
Data with policy `A` appears in context `B`. (Typing[4379])
  File "switch.php", line 6, characters 14-19:
  This may be the data source with policy `A`
  File "switch.php", line 9, characters 14-19:
  This may be the data sink with policy `B`
  File "switch.php", line 79, characters 11-15:
  Another program point contributing to the illegal flow
File "switch.php", line 101, characters 7-16:
Data with policy `A` appears in context `B`. (Typing[4379])
  File "switch.php", line 6, characters 14-19:
  This may be the data source with policy `A`
  File "switch.php", line 9, characters 14-19:
  This may be the data sink with policy `B`
  File "switch.php", line 94, characters 10-14:
  Another program point contributing to the illegal flow
File "switch.php", line 112, characters 10-13:
Data with policy `B` appears in context `A`. (Typing[4379])
  File "switch.php", line 9, characters 14-19:
  This may be the data source with policy `B`
  File "switch.php", line 6, characters 14-19:
  This may be the data sink with policy `A`
  File "switch.php", line 107, characters 3-49:
  Another program point contributing to the illegal flow
  File "switch.php", line 108, characters 5-14:
  Another program point contributing to the illegal flow
  File "switch.php", line 111, characters 11-15:
  Another program point contributing to the illegal flow
File "switch.php", line 17, characters 7-16:
Data with policy `A` appears in context `B`. (Typing[4379])
  File "switch.php", line 6, characters 14-19:
  This may be the data source with policy `A`
  File "switch.php", line 9, characters 14-19:
  This may be the data sink with policy `B`
  File "switch.php", line 14, characters 11-15:
  Another program point contributing to the illegal flow
