[("\\f",
  (Shallow_decl_defs.Fun
     { Typing_defs.fe_deprecated = None; fe_module = None;
       fe_internal = false;
       fe_type =
       (Rwitness_from_decl ([3:10-11]),
        (Tfun
           { ft_tparams = []; ft_where_constraints = [];
             ft_params =
             [{ fp_pos = [3:32-34]; fp_name = (Some "$s");
                fp_type =
                { et_enforced = Typing_defs_core.Unenforced;
                  et_type =
                  (Rhint ([3:12-31]),
                   (Tapply (([3:12-22], "\\HH\\supportdyn"),
                      [(Rhint ([3:23-30]), Tnonnull)])))
                  };
                fp_flags =
                { Typing_defs_flags.FunParam.accept_disposable = false;
                  inout = false; has_default = false; ifc_external = false;
                  ifc_can_call = false; readonly = false }
                }
               ];
             ft_implicit_params = { capability = (CapDefaults [3:10-11]) };
             ft_ret =
             { et_enforced = Typing_defs_core.Unenforced;
               et_type = (Rhint ([3:37-41]), (Tprim Tvoid)) };
             ft_flags =
             { Typing_defs_flags.Fun.return_disposable = false;
               async = false; generator = false; fun_kind = FSync;
               instantiated_targs = false; is_function_pointer = false;
               returns_readonly = false; readonly_this = false;
               support_dynamic_type = false; is_memoized = false;
               variadic = false };
             ft_ifc_decl = (FDPolicied (Some "PUBLIC"));
             ft_cross_package = None }));
       fe_pos = [3:10-11]; fe_php_std_lib = false;
       fe_support_dynamic_type = false; fe_no_auto_dynamic = false;
       fe_no_auto_likes = false }))
  ]
