function \takes_int:
  Locals:
  Constraints:
function \takes_string:
  Locals:
  Constraints:
function \test_foreach:
  Locals:
    $d File "foreach.php", line 6, characters 31-32: : dynamic#0
  Constraints:
    #0:
      <: can_traverse(val=dynamic#2)
      <: dynamic#2
    #2:
      <: mixed
      <: dynamic
      <: ~int
      <: mixed
function \test_foreach_kv:
  Locals:
    $d File "foreach.php", line 12, characters 34-35: : dynamic#0
  Constraints:
    #0:
      <: can_traverse(key=dynamic#4, val=dynamic#2)
      <: dynamic#2
    #2:
      <: mixed
      <: dynamic
      <: ~int
      <: mixed
    #4:
      <: mixed
      <: dynamic
      <: ~string
      <: mixed
