    randObj: A
    randObj: C
C::__call dubiousArgs
--------A::__call noSuchMethodBoyeee
--------A::__call noSuchMethodBoyeee
    randObj: B
    randObj: A
T2::dubiousArgs 1
--B has this method.
--B has this method.
    randObj: C
    randObj: B
T1::dubiousArgs 2, 2
--HipHop Warning:  Missing argument 1 to noSuchMethodBoyeee() in hphp/test/vm/poly-torture.php on line 41
HipHop Warning:  Missing argument 2 to noSuchMethodBoyeee() in hphp/test/vm/poly-torture.php on line 41
HipHop Warning:  Missing argument 3 to noSuchMethodBoyeee() in hphp/test/vm/poly-torture.php on line 41
HipHop Warning:  Missing argument 4 to noSuchMethodBoyeee() in hphp/test/vm/poly-torture.php on line 41
HipHop Warning:  Missing argument 5 to noSuchMethodBoyeee() in hphp/test/vm/poly-torture.php on line 41
HipHop Notice:  Undefined variable: d in hphp/test/vm/poly-torture.php on line 41
HipHop Notice:  Undefined variable: e in hphp/test/vm/poly-torture.php on line 41
C also has this method with params:  
--C also has this method with params: 3 4
    randObj: A
    randObj: C
C::__call dubiousArgs
--------A::__call noSuchMethodBoyeee
--------A::__call noSuchMethodBoyeee
    randObj: B
    randObj: A
T2::dubiousArgs 4
--B has this method.
--B has this method.
