File "override_member.php", line 17, characters 10-13:
The property `x` has the wrong type (Typing[4341])
File "override_member.php", line 17, characters 10-13:
Typing error
File "override_member.php", line 13, characters 10-12:
Expected `int`
File "override_member.php", line 17, characters 10-13:
But got `bool`
File "override_member.php", line 17, characters 10-13:
The property `x` has the wrong type (Typing[4341])
File "override_member.php", line 17, characters 10-13:
Typing error
File "override_member.php", line 17, characters 10-13:
Expected `bool`
File "override_member.php", line 13, characters 10-12:
But got `int`
