File "class_meth_reified.php", line 8, characters 3-12:
All type arguments must be specified because a type parameter is reified (Typing[4303])
  File "class_meth_reified.php", line 4, characters 26-28:
  Definition is here
File "class_meth_reified.php", line 10, characters 3-12:
All type arguments must be specified because a type parameter is reified (Typing[4303])
  File "class_meth_reified.php", line 4, characters 26-28:
  Definition is here
