Errors:
  [13:38-42] `self` is undefined outside of a class
[(Class
    { c_span = [3:1-9:2]; c_annotation = (); c_mode = Mstrict; c_final = true; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
      c_name = ([3:13-29], "\\WithConstantName"); c_tparams = []; c_extends = []; 
      c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; 
      c_implements = []; c_where_constraints = [];
      c_consts =
      [{ cc_user_attributes = []; cc_type = (Some ([4:9-15], (Hprim Tstring))); 
         cc_id = ([4:16-20], "FLD1"); cc_kind = (CCConcrete ((), [4:23-31], (String "field1"))); 
         cc_span = [4:3-32]; cc_doc_comment = None }
        ];
      c_typeconsts = []; c_vars = [];
      c_methods =
      [{ m_span = [6:3-8:4]; m_annotation = (); m_final = false; m_abstract = false; 
         m_static = false; m_readonly_this = false; m_visibility = Public; 
         m_name = ([6:19-36], "self_inside_class"); m_tparams = []; m_where_constraints = []; 
         m_params = []; m_ctxs = None; m_unsafe_ctxs = None;
         m_body = { fb_ast = [([7:5-35], (Return (Some ((), [7:12-34], (Shape [((SFclass_const (([7:18-22], "\\WithConstantName"), ([7:24-28], "FLD1"))), ((), [7:32-33], (Int "1")))])))))] };
         m_fun_kind = FSync; m_user_attributes = []; m_readonly_ret = None;
         m_ret =
         ((),
          (Some ([6:40-64],
                 (Hshape
                    { nsi_allows_unknown_fields = false;
                      nsi_field_map = [{ sfi_optional = false; sfi_hint = ([6:60-63], (Hprim Tint)); sfi_name = (SFclass_const (([6:46-50], "\\WithConstantName"), ([6:52-56], "FLD1"))) }] }))));
         m_external = false; m_doc_comment = None }
        ];
      c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_docs_url = None; 
      c_enum = None; c_doc_comment = None; c_emit_id = None; c_internal = false; 
      c_module = None });
  (Typedef
     { t_annotation = (); t_name = ([11:6-25], "\\with_class_constant"); 
       t_tparams = []; t_as_constraint = None; t_super_constraint = None;
       t_kind =
       ([11:28-64],
        (Hshape
           { nsi_allows_unknown_fields = false;
             nsi_field_map = [{ sfi_optional = false; sfi_hint = ([11:60-63], (Hprim Tint)); sfi_name = (SFclass_const (([11:34-50], "\\WithConstantName"), ([11:52-56], "FLD1"))) }] }));
       t_user_attributes = []; t_file_attributes = []; t_mode = Mstrict; 
       t_vis = Transparent;
       t_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       t_span = [11:1-65]; t_emit_id = None; t_is_ctx = false; t_internal = false; 
       t_module = None; t_docs_url = None; t_doc_comment = None });
  (Typedef
     { t_annotation = (); t_name = ([13:6-29], "\\with_self_outside_class"); 
       t_tparams = []; t_as_constraint = None; t_super_constraint = None;
       t_kind =
       ([13:32-56],
        (Hshape
           { nsi_allows_unknown_fields = false;
             nsi_field_map = [{ sfi_optional = false; sfi_hint = ([13:52-55], (Hprim Tint)); sfi_name = (SFclass_const (([13:38-42], "\\*Unknown*"), ([13:44-48], "FLD1"))) }] }));
       t_user_attributes = []; t_file_attributes = []; t_mode = Mstrict; 
       t_vis = Transparent;
       t_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       t_span = [13:1-57]; t_emit_id = None; t_is_ctx = false; t_internal = false; 
       t_module = None; t_docs_url = None; t_doc_comment = None });
  (Typedef
     { t_annotation = (); t_name = ([15:6-22], "\\with_string_name"); 
       t_tparams = []; t_as_constraint = None; t_super_constraint = None;
       t_kind =
       ([15:25-47], (Hshape { nsi_allows_unknown_fields = false; nsi_field_map = [{ sfi_optional = false; sfi_hint = ([15:43-46], (Hprim Tint)); sfi_name = (SFlit_str ([15:31-39], "field1")) }] }));
       t_user_attributes = []; t_file_attributes = []; t_mode = Mstrict; 
       t_vis = Transparent;
       t_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       t_span = [15:1-48]; t_emit_id = None; t_is_ctx = false; t_internal = false; 
       t_module = None; t_docs_url = None; t_doc_comment = None });
  (Typedef
     { t_annotation = (); t_name = ([18:6-19], "\\with_int_name"); t_tparams = []; 
       t_as_constraint = None; t_super_constraint = None;
       t_kind =
       ([18:22-37], (Hshape { nsi_allows_unknown_fields = false; nsi_field_map = [{ sfi_optional = false; sfi_hint = ([18:33-36], (Hprim Tint)); sfi_name = (SFlit_str ([18:28-29], "1")) }] }));
       t_user_attributes = []; t_file_attributes = []; t_mode = Mstrict; 
       t_vis = Transparent;
       t_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       t_span = [18:1-38]; t_emit_id = None; t_is_ctx = false; t_internal = false; 
       t_module = None; t_docs_url = None; t_doc_comment = None })
  ]
