[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>; ns_const_uses = <opaque>; 
        ns_name = None; ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict;
      fd_fun =
      { f_span = [3:1-5:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((), (Some ([3:17-21], (Hprim Tvoid)))); 
        f_name = ([3:10-13], "\\foo"); f_tparams = []; f_where_constraints = []; 
        f_variadic = FVnonVariadic; f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([4:3-54],
            (Expr
               ((), [4:3-53],
                (Binop ((Eq None), ((), [4:3-5], (Lvar ([4:3-5], $x))),
                   ((), [4:8-53],
                    (ExpressionTree
                       { et_hint = ([4:8-12], (Happly (([4:8-12], "\\Code"), []))); 
                         et_splices = []; et_function_pointers = [];
                         et_virtualized_expr =
                         ((), [4:13-52],
                          (Call (
                             ((), [4:13-52],
                              (Efun (
                                 { f_span = [4:13-52]; f_readonly_this = None; 
                                   f_annotation = (); f_readonly_ret = None; 
                                   f_ret = ((), None); f_name = ([4:13-52], ";anonymous"); 
                                   f_tparams = []; f_where_constraints = []; 
                                   f_variadic = FVnonVariadic; f_params = []; 
                                   f_ctxs = None; f_unsafe_ctxs = None;
                                   f_body =
                                   { fb_ast =
                                     [([4:13-52],
                                       (Return
                                          (Some ((), [4:13-52],
                                                 (Xml (([4:14-21], "\\:foo:bar"),
                                                    [(Xhp_simple
                                                        { xs_name = ([4:22-23], "x"); 
                                                          xs_type = ();
                                                          xs_expr =
                                                          ((), [4:24-27],
                                                           (Call (((), [4:24-27], (Class_const (((), [4:24-27], (CI ([4:24-27], "\\Code"))), ([4:24-27], "stringType")))), [], [], None)))
                                                          })
                                                      ],
                                                    [((), [4:28-35], (Xml (([4:29-32], "\\:baz"), [], [])));
                                                      ((), [4:36-41], (Call (((), [4:36-41], (Class_const (((), [4:36-41], (CI ([4:36-41], "\\Code"))), ([4:36-41], "stringType")))), [], [], None)))]
                                                    ))))))
                                       ]
                                     };
                                   f_fun_kind = FSync; f_user_attributes = []; 
                                   f_external = false; f_doc_comment = None },
                                 []))),
                             [], [], None)));
                         et_runtime_expr =
                         ((), [4:13-52],
                          (Call (((), [4:13-52], (Class_const (((), [4:13-52], (CI ([4:13-52], "\\Code"))), ([4:13-52], "makeTree")))), 
                             [],
                             [(Pnormal,
                               ((), [4:13-52],
                                (Shape
                                   [((SFlit_str ([4:13-52], "path")), ((), [4:13-52], (Id ([4:13-52], "\\__FILE__")))); (
                                     (SFlit_str ([4:13-52], "start_line")), ((), [4:13-52], (Int "4"))); (
                                     (SFlit_str ([4:13-52], "end_line")), ((), [4:13-52], (Int "4"))); (
                                     (SFlit_str ([4:13-52], "start_column")), ((), [4:13-52], (Int "12"))); (
                                     (SFlit_str ([4:13-52], "end_column")), ((), [4:13-52], (Int "51")))])));
                               (Pnormal,
                                ((), [4:13-52],
                                 (Shape
                                    [((SFlit_str ([4:13-52], "splices")), ((), [4:13-52], (KeyValCollection (Dict, None, []))));
                                      ((SFlit_str ([4:13-52], "functions")), ((), [4:13-52], (ValCollection (Vec, None, []))));
                                      ((SFlit_str ([4:13-52], "static_methods")), ((), [4:13-52], (ValCollection (Vec, None, []))))])));
                               (Pnormal,
                                ((), [4:13-52],
                                 (Lfun (
                                    { f_span = [4:13-52]; f_readonly_this = None; 
                                      f_annotation = (); f_readonly_ret = None; 
                                      f_ret = ((), None); f_name = ([4:13-52], ";anonymous"); 
                                      f_tparams = []; f_where_constraints = []; 
                                      f_variadic = FVnonVariadic;
                                      f_params =
                                      [{ param_annotation = (); param_type_hint = ((), (Some ([4:8-12], (Happly (([4:8-12], "\\Code"), []))))); 
                                         param_is_variadic = false; param_pos = [4:8-12]; 
                                         param_name = "$0v"; param_expr = None; 
                                         param_readonly = None; param_callconv = Pnormal; 
                                         param_user_attributes = []; 
                                         param_visibility = None }
                                        ];
                                      f_ctxs = None; f_unsafe_ctxs = None;
                                      f_body =
                                      { fb_ast =
                                        [([4:13-52],
                                          (Return
                                             (Some ((), [4:13-52],
                                                    (Call (((), [4:13-52], (Obj_get (((), [4:13-52], (Lvar ([4:13-52], $0v))), ((), [4:13-52], (Id ([4:13-52], "visitXhp"))), OG_nullthrows, false))),
                                                       [],
                                                       [(Pnormal,
                                                         ((), [4:13-52],
                                                          (Shape
                                                             [((SFlit_str ([4:13-52], "path")), ((), [4:13-52], (Id ([4:13-52], "\\__FILE__"))));
                                                               ((SFlit_str ([4:13-52], "start_line")), ((), [4:13-52], (Int "4"))); (
                                                               (SFlit_str ([4:13-52], "end_line")), ((), [4:13-52], (Int "4")));
                                                               ((SFlit_str ([4:13-52], "start_column")), ((), [4:13-52], (Int "12")));
                                                               ((SFlit_str ([4:13-52], "end_column")), ((), [4:13-52], (Int "51")))])));
                                                         (Pnormal, ((), [4:13-52], (Class_const (((), [4:14-21], (CI ([4:14-21], "\\:foo:bar"))), ([4:14-21], "class")))));
                                                         (Pnormal,
                                                          ((), [4:13-52],
                                                           (KeyValCollection (Dict, None,
                                                              [(((), [4:22-23], (String "x")),
                                                                ((), [4:24-27],
                                                                 (Call (
                                                                    (
                                                                    (), [4:24-27],
                                                                    (
                                                                    Obj_get (((), [4:24-27], (Lvar ([4:24-27], $0v))), ((), [4:24-27], (Id ([4:24-27], "visitString"))), OG_nullthrows, false))), 
                                                                    [],
                                                                    [(Pnormal,
                                                                    ((), [4:24-27],
                                                                    (Shape
                                                                    [((SFlit_str ([4:24-27], "path")), ((), [4:24-27], (Id ([4:24-27], "\\__FILE__"))));
                                                                    ((SFlit_str ([4:24-27], "start_line")), ((), [4:24-27], (Int "4")));
                                                                    ((SFlit_str ([4:24-27], "end_line")), ((), [4:24-27], (Int "4")));
                                                                    ((SFlit_str ([4:24-27], "start_column")), ((), [4:24-27], (Int "23")));
                                                                    ((SFlit_str ([4:24-27], "end_column")), ((), [4:24-27], (Int "26")))]))); (
                                                                    Pnormal, ((), [4:24-27], (String "1")))], None))))
                                                                ]
                                                              ))));
                                                         (Pnormal,
                                                          ((), [4:28-41],
                                                           (ValCollection (Vec, None,
                                                              [((), [4:28-35],
                                                                (Call (
                                                                   ((), [4:28-35],
                                                                    (
                                                                    Obj_get (((), [4:28-35], (Lvar ([4:28-35], $0v))), ((), [4:28-35], (Id ([4:28-35], "visitXhp"))), OG_nullthrows, false))),
                                                                   [],
                                                                   [(Pnormal,
                                                                    ((), [4:28-35],
                                                                    (Shape
                                                                    [((SFlit_str ([4:28-35], "path")), ((), [4:28-35], (Id ([4:28-35], "\\__FILE__"))));
                                                                    ((SFlit_str ([4:28-35], "start_line")), ((), [4:28-35], (Int "4")));
                                                                    ((SFlit_str ([4:28-35], "end_line")), ((), [4:28-35], (Int "4")));
                                                                    ((SFlit_str ([4:28-35], "start_column")), ((), [4:28-35], (Int "27")));
                                                                    ((SFlit_str ([4:28-35], "end_column")), ((), [4:28-35], (Int "34")))])));
                                                                    (Pnormal, ((), [4:28-35], (Class_const (((), [4:29-32], (CI ([4:29-32], "\\:baz"))), ([4:29-32], "class")))));
                                                                    (Pnormal, ((), [4:28-35], (KeyValCollection (Dict, None, [])))); (
                                                                    Pnormal, ((), [Pos.none], (ValCollection (Vec, None, []))))],
                                                                   None)));
                                                                ((), [4:36-41],
                                                                 (Call (
                                                                    (
                                                                    (), [4:36-41],
                                                                    (
                                                                    Obj_get (((), [4:36-41], (Lvar ([4:36-41], $0v))), ((), [4:36-41], (Id ([4:36-41], "visitString"))), OG_nullthrows, false))), 
                                                                    [],
                                                                    [(Pnormal,
                                                                    ((), [4:36-41],
                                                                    (Shape
                                                                    [((SFlit_str ([4:36-41], "path")), ((), [4:36-41], (Id ([4:36-41], "\\__FILE__"))));
                                                                    ((SFlit_str ([4:36-41], "start_line")), ((), [4:36-41], (Int "4")));
                                                                    ((SFlit_str ([4:36-41], "end_line")), ((), [4:36-41], (Int "4")));
                                                                    ((SFlit_str ([4:36-41], "start_column")), ((), [4:36-41], (Int "35")));
                                                                    ((SFlit_str ([4:36-41], "end_column")), ((), [4:36-41], (Int "40")))]))); (
                                                                    Pnormal, ((), [4:36-41], (String " stuff ")))], None)))
                                                                ]
                                                              ))))
                                                         ],
                                                       None))))))
                                          ]
                                        };
                                      f_fun_kind = FSync; f_user_attributes = []; 
                                      f_external = false; f_doc_comment = None },
                                    []))))
                               ],
                             None)));
                         et_dollardollar_pos = None }))
                   )))))
            ]
          };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None }
      })
  ]
