[(Fun
    { f_span = [3:1-5:2]; f_annotation = (); f_mode = Mstrict;
      f_readonly_ret = None; f_ret = ((), (Some ([3:18-22], (Hprim Tvoid))));
      f_name = ([3:10-14], "\\test"); f_tparams = [];
      f_where_constraints = []; f_variadic = FVnonVariadic; f_params = [];
      f_ctxs = None; f_unsafe_ctxs = None;
      f_body =
      { fb_ast =
        [([4:3-28],
          (Expr
             ([4:3-27],
              (ExpressionTree
                 { et_hint = ([4:3-7], (Happly (([4:3-7], "\\Code"), [])));
                   et_src_expr =
                   ([4:8-26],
                    (Binop (Plus,
                       ([4:8-14],
                        (Binop (Plus, ([4:8-9], (Int "4")),
                           ([4:12-14], (Int "10"))))),
                       ([4:17-26],
                        (ET_Splice
                           ([4:19-25],
                            (Binop (Plus,
                               ([4:19-21], (Lvar ([4:19-21], $x))),
                               ([4:24-25], (Int "2")))))))
                       )));
                   et_desugared_expr =
                   ([4:8-26],
                    (Call (
                       ([4:8-26],
                        (Lfun (
                           { f_span = [4:8-26]; f_annotation = ();
                             f_mode = Mstrict; f_readonly_ret = None;
                             f_ret = ((), None);
                             f_name = ([Pos.none], ";anonymous");
                             f_tparams = []; f_where_constraints = [];
                             f_variadic = FVnonVariadic; f_params = [];
                             f_ctxs = None; f_unsafe_ctxs = None;
                             f_body =
                             { fb_ast =
                               [([4:8-9],
                                 (Expr
                                    ([4:8-9],
                                     (Binop ((Eq None),
                                        ([4:8-9], (Lvar ([4:8-9], $0splice0))),
                                        ([4:8-9],
                                         (Call (
                                            ([4:8-9],
                                             (Class_const (
                                                ([4:8-9],
                                                 (CI ([4:8-9], "\\Code"))),
                                                ([4:8-9], "intLiteral")))),
                                            [], [([4:8-9], (Int "4"))], None
                                            )))
                                        )))));
                                 ([4:12-14],
                                  (Expr
                                     ([4:12-14],
                                      (Binop ((Eq None),
                                         ([4:12-14],
                                          (Lvar ([4:12-14], $0splice1))),
                                         ([4:12-14],
                                          (Call (
                                             ([4:12-14],
                                              (Class_const (
                                                 ([4:12-14],
                                                  (CI ([4:12-14], "\\Code"))),
                                                 ([4:12-14], "intLiteral")))),
                                             [], [([4:12-14], (Int "10"))],
                                             None)))
                                         )))));
                                 ([4:19-25],
                                  (Expr
                                     ([4:19-25],
                                      (Binop ((Eq None),
                                         ([4:19-25],
                                          (Lvar ([4:19-25], $0splice2))),
                                         ([4:19-25],
                                          (Binop (Plus,
                                             ([4:19-21],
                                              (Lvar ([4:19-21], $x))),
                                             ([4:24-25], (Int "2")))))
                                         )))));
                                 ([4:8-26],
                                  (Return
                                     (Some ([4:8-26],
                                            (Call (
                                               ([4:8-26],
                                                (Class_const (
                                                   ([4:8-26],
                                                    (CI ([4:8-26], "\\Code"))),
                                                   ([4:8-26], "makeTree")))),
                                               [],
                                               [([4:8-26],
                                                 (New (
                                                    ([4:8-26],
                                                     (CI
                                                        ([4:8-26],
                                                         "\\ExprPos"))),
                                                    [],
                                                    [([Pos.none],
                                                      (Id
                                                         ([Pos.none],
                                                          "\\__FILE__")));
                                                      ([Pos.none], (Int "4"));
                                                      ([Pos.none], (Int "7"));
                                                      ([Pos.none], (Int "4"));
                                                      ([Pos.none], (Int "25"))
                                                      ],
                                                    None, [4:8-26])));
                                                 ([Pos.none],
                                                  (KeyValCollection (Dict,
                                                     None,
                                                     [(([Pos.none],
                                                        (String "$0splice0")),
                                                       ([Pos.none],
                                                        (Lvar
                                                           ([Pos.none],
                                                            $0splice0))));
                                                       (([Pos.none],
                                                         (String "$0splice1")),
                                                        ([Pos.none],
                                                         (Lvar
                                                            ([Pos.none],
                                                             $0splice1))));
                                                       (([Pos.none],
                                                         (String "$0splice2")),
                                                        ([Pos.none],
                                                         (Lvar
                                                            ([Pos.none],
                                                             $0splice2))))
                                                       ]
                                                     )));
                                                 ([4:8-26],
                                                  (Lfun (
                                                     { f_span = [4:8-26];
                                                       f_annotation = ();
                                                       f_mode = Mstrict;
                                                       f_readonly_ret = None;
                                                       f_ret = ((), None);
                                                       f_name =
                                                       ([Pos.none],
                                                        ";anonymous");
                                                       f_tparams = [];
                                                       f_where_constraints =
                                                       [];
                                                       f_variadic =
                                                       FVnonVariadic;
                                                       f_params =
                                                       [{ param_annotation =
                                                          [4:3-7];
                                                          param_type_hint =
                                                          ((),
                                                           (Some ([4:3-7],
                                                                  (Happly (
                                                                    ([4:3-7],
                                                                    "\\Code"),
                                                                    [])))));
                                                          param_is_variadic =
                                                          false;
                                                          param_pos = [4:3-7];
                                                          param_name = "$v";
                                                          param_expr = None;
                                                          param_readonly =
                                                          None;
                                                          param_callconv =
                                                          None;
                                                          param_user_attributes =
                                                          [];
                                                          param_visibility =
                                                          None }
                                                         ];
                                                       f_ctxs = None;
                                                       f_unsafe_ctxs = None;
                                                       f_body =
                                                       { fb_ast =
                                                         [([4:8-26],
                                                           (Return
                                                              (Some (
                                                              [4:8-26],
                                                              (Call (
                                                                 ([4:8-26],
                                                                  (Obj_get (
                                                                    ([4:8-26],
                                                                    (Lvar
                                                                    ([4:8-26],
                                                                    $v))),
                                                                    ([4:8-26],
                                                                    (Id
                                                                    ([4:8-26],
                                                                    "methCall"))),
                                                                    OG_nullthrows,
                                                                    false))),
                                                                 [],
                                                                 [([4:8-26],
                                                                   (New (
                                                                    ([4:8-26],
                                                                    (CI
                                                                    ([4:8-26],
                                                                    "\\ExprPos"))),
                                                                    [],
                                                                    [([Pos.none],
                                                                    (Id
                                                                    ([Pos.none],
                                                                    "\\__FILE__")));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "7"));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "25"))
                                                                    ], None,
                                                                    [4:8-26]
                                                                    )));
                                                                   ([4:8-14],
                                                                    (
                                                                    Call (
                                                                    ([4:8-14],
                                                                    (Obj_get (
                                                                    ([4:8-14],
                                                                    (Lvar
                                                                    ([4:8-14],
                                                                    $v))),
                                                                    ([4:8-14],
                                                                    (Id
                                                                    ([4:8-14],
                                                                    "methCall"))),
                                                                    OG_nullthrows,
                                                                    false))),
                                                                    [],
                                                                    [([4:8-14],
                                                                    (New (
                                                                    ([4:8-14],
                                                                    (CI
                                                                    ([4:8-14],
                                                                    "\\ExprPos"))),
                                                                    [],
                                                                    [([Pos.none],
                                                                    (Id
                                                                    ([Pos.none],
                                                                    "\\__FILE__")));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "7"));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "13"))
                                                                    ], None,
                                                                    [4:8-14]
                                                                    )));
                                                                    ([4:8-9],
                                                                    (Call (
                                                                    ([4:8-9],
                                                                    (Obj_get (
                                                                    ([4:8-9],
                                                                    (Lvar
                                                                    ([4:8-9],
                                                                    $v))),
                                                                    ([4:8-9],
                                                                    (Id
                                                                    ([4:8-9],
                                                                    "splice"))),
                                                                    OG_nullthrows,
                                                                    false))),
                                                                    [],
                                                                    [([4:8-9],
                                                                    (New (
                                                                    ([4:8-9],
                                                                    (CI
                                                                    ([4:8-9],
                                                                    "\\ExprPos"))),
                                                                    [],
                                                                    [([Pos.none],
                                                                    (Id
                                                                    ([Pos.none],
                                                                    "\\__FILE__")));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "7"));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "8"))
                                                                    ], None,
                                                                    [4:8-9])));
                                                                    ([Pos.none],
                                                                    (String
                                                                    "$0splice0"));
                                                                    ([4:8-9],
                                                                    (Lvar
                                                                    ([4:8-9],
                                                                    $0splice0)))
                                                                    ], None)));
                                                                    ([Pos.none],
                                                                    (String
                                                                    "__plus"));
                                                                    ([4:12-14],
                                                                    (ValCollection (
                                                                    Vec,
                                                                    None,
                                                                    [([4:12-14],
                                                                    (Call (
                                                                    ([4:12-14],
                                                                    (Obj_get (
                                                                    ([4:12-14],
                                                                    (Lvar
                                                                    ([4:12-14],
                                                                    $v))),
                                                                    ([4:12-14],
                                                                    (Id
                                                                    ([4:12-14],
                                                                    "splice"))),
                                                                    OG_nullthrows,
                                                                    false))),
                                                                    [],
                                                                    [([4:12-14],
                                                                    (New (
                                                                    ([4:12-14],
                                                                    (CI
                                                                    ([4:12-14],
                                                                    "\\ExprPos"))),
                                                                    [],
                                                                    [([Pos.none],
                                                                    (Id
                                                                    ([Pos.none],
                                                                    "\\__FILE__")));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "11"));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "13"))
                                                                    ], None,
                                                                    [4:12-14]
                                                                    )));
                                                                    ([Pos.none],
                                                                    (String
                                                                    "$0splice1"));
                                                                    ([4:12-14],
                                                                    (Lvar
                                                                    ([4:12-14],
                                                                    $0splice1)))
                                                                    ], None)))
                                                                    ])))],
                                                                    None)));
                                                                   ([Pos.none],
                                                                    (
                                                                    String
                                                                    "__plus"));
                                                                   ([4:19-25],
                                                                    (
                                                                    ValCollection (
                                                                    Vec,
                                                                    None,
                                                                    [([4:19-25],
                                                                    (Call (
                                                                    ([4:19-25],
                                                                    (Obj_get (
                                                                    ([4:19-25],
                                                                    (Lvar
                                                                    ([4:19-25],
                                                                    $v))),
                                                                    ([4:19-25],
                                                                    (Id
                                                                    ([4:19-25],
                                                                    "splice"))),
                                                                    OG_nullthrows,
                                                                    false))),
                                                                    [],
                                                                    [([4:17-26],
                                                                    (New (
                                                                    ([4:17-26],
                                                                    (CI
                                                                    ([4:17-26],
                                                                    "\\ExprPos"))),
                                                                    [],
                                                                    [([Pos.none],
                                                                    (Id
                                                                    ([Pos.none],
                                                                    "\\__FILE__")));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "16"));
                                                                    ([Pos.none],
                                                                    (Int "4"));
                                                                    ([Pos.none],
                                                                    (Int "25"))
                                                                    ], None,
                                                                    [4:17-26]
                                                                    )));
                                                                    ([Pos.none],
                                                                    (String
                                                                    "$0splice2"));
                                                                    ([4:19-25],
                                                                    (Lvar
                                                                    ([4:19-25],
                                                                    $0splice2)))
                                                                    ], None)))
                                                                    ])))
                                                                   ],
                                                                 None))))))
                                                           ];
                                                         fb_annotation =
                                                         Named };
                                                       f_fun_kind = FSync;
                                                       f_user_attributes = [];
                                                       f_file_attributes = [];
                                                       f_external = false;
                                                       f_namespace =
                                                       { Namespace_env.ns_ns_uses =
                                                         <opaque>;
                                                         ns_class_uses =
                                                         <opaque>;
                                                         ns_record_def_uses =
                                                         <opaque>;
                                                         ns_fun_uses =
                                                         <opaque>;
                                                         ns_const_uses =
                                                         <opaque>;
                                                         ns_name = None;
                                                         ns_auto_ns_map = [];
                                                         ns_is_codegen =
                                                         false;
                                                         ns_disable_xhp_element_mangling =
                                                         false };
                                                       f_doc_comment = None;
                                                       f_static = false },
                                                     [([4:19-25], $0splice2);
                                                       ([4:12-14], $0splice1);
                                                       ([4:8-9], $0splice0)]
                                                     )));
                                                 ([4:8-26],
                                                  (Efun (
                                                     { f_span = [4:8-26];
                                                       f_annotation = ();
                                                       f_mode = Mstrict;
                                                       f_readonly_ret = None;
                                                       f_ret = ((), None);
                                                       f_name =
                                                       ([Pos.none],
                                                        ";anonymous");
                                                       f_tparams = [];
                                                       f_where_constraints =
                                                       [];
                                                       f_variadic =
                                                       FVnonVariadic;
                                                       f_params = [];
                                                       f_ctxs = None;
                                                       f_unsafe_ctxs = None;
                                                       f_body =
                                                       { fb_ast =
                                                         [([4:8-26],
                                                           (Return
                                                              (Some (
                                                              [4:8-26],
                                                              (Call (
                                                                 ([4:8-26],
                                                                  (Obj_get (
                                                                    ([4:8-14],
                                                                    (Call (
                                                                    ([4:8-14],
                                                                    (Obj_get (
                                                                    ([4:8-9],
                                                                    (ET_Splice
                                                                    ([4:8-9],
                                                                    (Lvar
                                                                    ([4:8-9],
                                                                    $0splice0))))),
                                                                    ([4:8-14],
                                                                    (Id
                                                                    ([4:8-14],
                                                                    "__plus"))),
                                                                    OG_nullthrows,
                                                                    false))),
                                                                    [],
                                                                    [([4:12-14],
                                                                    (ET_Splice
                                                                    ([4:12-14],
                                                                    (Lvar
                                                                    ([4:12-14],
                                                                    $0splice1)))))
                                                                    ], None))),
                                                                    ([4:8-26],
                                                                    (Id
                                                                    ([4:8-26],
                                                                    "__plus"))),
                                                                    OG_nullthrows,
                                                                    false))),
                                                                 [],
                                                                 [([4:17-26],
                                                                   (ET_Splice
                                                                    ([4:19-25],
                                                                    (Lvar
                                                                    ([4:19-25],
                                                                    $0splice2)))))
                                                                   ],
                                                                 None))))))
                                                           ];
                                                         fb_annotation =
                                                         Named };
                                                       f_fun_kind = FSync;
                                                       f_user_attributes = [];
                                                       f_file_attributes = [];
                                                       f_external = false;
                                                       f_namespace =
                                                       { Namespace_env.ns_ns_uses =
                                                         <opaque>;
                                                         ns_class_uses =
                                                         <opaque>;
                                                         ns_record_def_uses =
                                                         <opaque>;
                                                         ns_fun_uses =
                                                         <opaque>;
                                                         ns_const_uses =
                                                         <opaque>;
                                                         ns_name = None;
                                                         ns_auto_ns_map = [];
                                                         ns_is_codegen =
                                                         false;
                                                         ns_disable_xhp_element_mangling =
                                                         false };
                                                       f_doc_comment = None;
                                                       f_static = false },
                                                     [([Pos.none], $0splice0);
                                                       ([Pos.none], $0splice1);
                                                       ([Pos.none], $0splice2)
                                                       ]
                                                     )))
                                                 ],
                                               None))))))
                                 ];
                               fb_annotation = Named };
                             f_fun_kind = FSync; f_user_attributes = [];
                             f_file_attributes = []; f_external = false;
                             f_namespace =
                             { Namespace_env.ns_ns_uses = <opaque>;
                               ns_class_uses = <opaque>;
                               ns_record_def_uses = <opaque>;
                               ns_fun_uses = <opaque>;
                               ns_const_uses = <opaque>; ns_name = None;
                               ns_auto_ns_map = []; ns_is_codegen = false;
                               ns_disable_xhp_element_mangling = false };
                             f_doc_comment = None; f_static = false },
                           [([4:19-21], $x)]))),
                       [], [], None)))
                   }))))
          ];
        fb_annotation = Named };
      f_fun_kind = FSync; f_user_attributes = []; f_file_attributes = [];
      f_external = false;
      f_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>;
        ns_record_def_uses = <opaque>; ns_fun_uses = <opaque>;
        ns_const_uses = <opaque>; ns_name = None; ns_auto_ns_map = [];
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      f_doc_comment = None; f_static = false })
  ]
