[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false };
      fd_file_attributes =
      [{ fa_user_attributes = [{ ua_name = ([3:9-33], "__EnableUnstableFeatures"); ua_params = [((), [3:34-52], (String "expression_trees")); ((), [3:54-81], (String "expression_tree_subscript"))] }];
         fa_namespace =
         { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
           ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
           ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false }
         }
        ];
      fd_mode = Mstrict; fd_name = ([5:10-18], "\\test_vec");
      fd_fun =
      { f_span = [5:1-7:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_tparams = []; f_ret = ((), (Some ([5:22-26], (Hprim Tvoid)))); 
        f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
        f_body =
        { fb_ast =
          [([6:3-70],
            (Expr
               ((), [6:3-69],
                (ExpressionTree
                   { et_class = ([6:3-13], "\\ExampleDsl");
                     et_runtime_expr =
                     ((), [6:3-13],
                      (Call
                         { func = ((), [6:3-13], (Class_const (((), [6:3-13], (CI ([6:3-13], "\\ExampleDsl"))), ([6:3-13], "makeTree")))); 
                           targs = [];
                           args =
                           [(Anormal
                               ((), [6:14-68],
                                (Shape
                                   [((SFlit_str ([6:14-68], "path")), ((), [6:14-68], (Id ([6:14-68], "\\__FILE__")))); (
                                     (SFlit_str ([6:14-68], "start_line")), ((), [6:14-68], (Int "6"))); (
                                     (SFlit_str ([6:14-68], "end_line")), ((), [6:14-68], (Int "6"))); (
                                     (SFlit_str ([6:14-68], "start_column")), ((), [6:14-68], (Int "13"))); (
                                     (SFlit_str ([6:14-68], "end_column")), ((), [6:14-68], (Int "67")))])));
                             (Anormal
                                ((), [6:3-13],
                                 (Shape
                                    [((SFlit_str ([6:3-13], "splices")), ((), [6:3-13], (KeyValCollection (([6:3-13], Dict), None, []))));
                                      ((SFlit_str ([6:3-13], "functions")), ((), [6:3-13], (ValCollection (([6:3-13], Vec), None, []))));
                                      ((SFlit_str ([6:3-13], "static_methods")), ((), [6:3-13], (ValCollection (([6:3-13], Vec), None, []))));
                                      ((SFlit_str ([6:3-13], "variables")), ((), [6:3-13], (ValCollection (([6:3-13], Vec), None, []))));
                                      ((SFlit_str ([6:3-13], "lexically_enclosing_tree")), ((), [Pos.none], Null));
                                      ((SFlit_str ([6:3-13], "type")),
                                       ((), [6:14-68],
                                        (Efun
                                           { ef_fun =
                                             { f_span = [6:14-68]; f_readonly_this = None; 
                                               f_annotation = (); f_readonly_ret = None; 
                                               f_tparams = []; f_ret = ((), None); 
                                               f_params = []; f_ctxs = (Some ([6:14-68], [([6:14-68], (Happly (([6:14-68], "\\HH\\Contexts\\defaults"), [])))])); 
                                               f_unsafe_ctxs = None;
                                               f_body =
                                               { fb_ast =
                                                 [([6:14-68],
                                                   (Return
                                                      (Some ((), [6:14-68],
                                                             (Call
                                                                { func = ((), [6:14-68], (Class_const (((), [6:14-68], (CI ([6:14-68], "\\ExampleDsl"))), ([6:14-68], "lambdaType")))); 
                                                                  targs = [];
                                                                  args =
                                                                  [(Anormal
                                                                    ((), [6:14-68],
                                                                    (Lfun (
                                                                    { f_span = [6:14-68]; 
                                                                    f_readonly_this = None; 
                                                                    f_annotation = (); 
                                                                    f_readonly_ret = None; 
                                                                    f_tparams = []; 
                                                                    f_ret = ((), None);
                                                                    f_params =
                                                                    [{ param_annotation = ();
                                                                    param_type_hint =
                                                                    (
                                                                    (), (Some ([6:15-30], (Happly (([6:15-18], "\\HH\\vec"), [([6:19-29], (Happly (([6:19-29], "\\ExampleInt"), [])))])))));
                                                                    param_pos = [6:31-35]; 
                                                                    param_name = "$arr"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None };
                                                                    { param_annotation = (); 
                                                                    param_type_hint = ((), (Some ([6:37-47], (Happly (([6:37-47], "\\ExampleInt"), []))))); 
                                                                    param_pos = [6:48-52]; 
                                                                    param_name = "$idx"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None }]; 
                                                                    f_ctxs = None; 
                                                                    f_unsafe_ctxs = None;
                                                                    f_body =
                                                                    { fb_ast =
                                                                    [([6:58-68],
                                                                    (Return
                                                                    (Some (
                                                                    (), [6:58-68], (Array_get (((), [6:58-62], (Lvar ([6:58-62], $arr))), (Some ((), [6:63-67], (Lvar ([6:63-67], $idx))))))))))] };
                                                                    f_fun_kind = FSync; 
                                                                    f_user_attributes = []; 
                                                                    f_external = false; 
                                                                    f_hidden = false; 
                                                                    f_doc_comment = None }, 
                                                                    []))))];
                                                                  unpacked_arg = None })))))
                                                   ]
                                                 };
                                               f_fun_kind = FSync; f_user_attributes = []; 
                                               f_external = false; f_hidden = false; 
                                               f_doc_comment = None };
                                             ef_use = []; ef_closure_class_name = None; 
                                             ef_is_expr_tree_virtual_expr = false })))
                                      ])));
                             (Anormal
                                ((), [6:14-68],
                                 (Lfun (
                                    { f_span = [6:14-68]; f_readonly_this = None; 
                                      f_annotation = (); f_readonly_ret = None; 
                                      f_tparams = []; f_ret = ((), None);
                                      f_params =
                                      [{ param_annotation = (); param_type_hint = ((), (Some ([6:3-13], (Happly (([6:3-13], "\\ExampleDsl"), []))))); 
                                         param_pos = [6:3-13]; param_name = "$0v"; 
                                         param_info = Param_required; 
                                         param_readonly = None; param_splat = None; 
                                         param_callconv = Pnormal; param_named = None; 
                                         param_user_attributes = []; 
                                         param_visibility = None }
                                        ];
                                      f_ctxs = None; f_unsafe_ctxs = None;
                                      f_body =
                                      { fb_ast =
                                        [([6:14-68],
                                          (Return
                                             (Some ((), [6:14-68],
                                                    (Call
                                                       { func =
                                                         ((), [6:14-68], (Obj_get (((), [6:14-68], (Lvar ([6:14-68], $0v))), ((), [6:14-68], (Id ([6:14-68], "visitLambda"))), Regular, Is_method)));
                                                         targs = [];
                                                         args =
                                                         [(Anormal
                                                             ((), [6:14-68],
                                                              (Shape
                                                                 [((SFlit_str ([6:14-68], "path")), ((), [6:14-68], (Id ([6:14-68], "\\__FILE__"))));
                                                                   ((SFlit_str ([6:14-68], "start_line")), ((), [6:14-68], (Int "6")));
                                                                   ((SFlit_str ([6:14-68], "end_line")), ((), [6:14-68], (Int "6")));
                                                                   ((SFlit_str ([6:14-68], "start_column")), ((), [6:14-68], (Int "13")));
                                                                   ((SFlit_str ([6:14-68], "end_column")), ((), [6:14-68], (Int "67")))])));
                                                           (Anormal ((), [6:31-52], (ValCollection (([6:31-52], Vec), None, [((), [6:31-35], (String "$arr")); ((), [6:48-52], (String "$idx"))]))));
                                                           (Anormal
                                                              ((), [6:58-68],
                                                               (ValCollection ((
                                                                  [6:58-68], Vec), None,
                                                                  [((), [6:58-68],
                                                                    (
                                                                    Call
                                                                    { func =
                                                                    ((), [6:58-68],
                                                                    (Obj_get (((), [6:58-68], (Lvar ([6:58-68], $0v))), ((), [6:58-68], (Id ([6:58-68], "visitReturn"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [6:58-68],
                                                                    (Shape
                                                                    [((SFlit_str ([6:58-68], "path")), ((), [6:58-68], (Id ([6:58-68], "\\__FILE__"))));
                                                                    ((SFlit_str ([6:58-68], "start_line")), ((), [6:58-68], (Int "6")));
                                                                    ((SFlit_str ([6:58-68], "end_line")), ((), [6:58-68], (Int "6")));
                                                                    ((SFlit_str ([6:58-68], "start_column")), ((), [6:58-68], (Int "57")));
                                                                    ((SFlit_str ([6:58-68], "end_column")), ((), [6:58-68], (Int "67")))])));
                                                                    (Anormal
                                                                    ((), [6:58-68],
                                                                    (Call
                                                                    { func =
                                                                    ((), [6:58-68],
                                                                    (Obj_get (((), [6:58-68], (Lvar ([6:58-68], $0v))), ((), [6:58-68], (Id ([6:58-68], "visitSubscript"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [6:58-68],
                                                                    (Shape
                                                                    [((SFlit_str ([6:58-68], "path")), ((), [6:58-68], (Id ([6:58-68], "\\__FILE__"))));
                                                                    ((SFlit_str ([6:58-68], "start_line")), ((), [6:58-68], (Int "6")));
                                                                    ((SFlit_str ([6:58-68], "end_line")), ((), [6:58-68], (Int "6")));
                                                                    ((SFlit_str ([6:58-68], "start_column")), ((), [6:58-68], (Int "57")));
                                                                    ((SFlit_str ([6:58-68], "end_column")), ((), [6:58-68], (Int "67")))])));
                                                                    (Anormal
                                                                    ((), [6:58-62],
                                                                    (Call
                                                                    { func =
                                                                    ((), [6:58-62],
                                                                    (Obj_get (((), [6:58-62], (Lvar ([6:58-62], $0v))), ((), [6:58-62], (Id ([6:58-62], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [6:58-62],
                                                                    (Shape
                                                                    [((SFlit_str ([6:58-62], "path")), ((), [6:58-62], (Id ([6:58-62], "\\__FILE__"))));
                                                                    ((SFlit_str ([6:58-62], "start_line")), ((), [6:58-62], (Int "6")));
                                                                    ((SFlit_str ([6:58-62], "end_line")), ((), [6:58-62], (Int "6")));
                                                                    ((SFlit_str ([6:58-62], "start_column")), ((), [6:58-62], (Int "57")));
                                                                    ((SFlit_str ([6:58-62], "end_column")), ((), [6:58-62], (Int "61")))]))); (
                                                                    Anormal ((), [6:58-62], (String "$arr")))]; 
                                                                    unpacked_arg = None })));
                                                                    (Anormal
                                                                    ((), [6:63-67],
                                                                    (Call
                                                                    { func =
                                                                    ((), [6:63-67],
                                                                    (Obj_get (((), [6:63-67], (Lvar ([6:63-67], $0v))), ((), [6:63-67], (Id ([6:63-67], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [6:63-67],
                                                                    (Shape
                                                                    [((SFlit_str ([6:63-67], "path")), ((), [6:63-67], (Id ([6:63-67], "\\__FILE__"))));
                                                                    ((SFlit_str ([6:63-67], "start_line")), ((), [6:63-67], (Int "6")));
                                                                    ((SFlit_str ([6:63-67], "end_line")), ((), [6:63-67], (Int "6")));
                                                                    ((SFlit_str ([6:63-67], "start_column")), ((), [6:63-67], (Int "62")));
                                                                    ((SFlit_str ([6:63-67], "end_column")), ((), [6:63-67], (Int "66")))]))); (
                                                                    Anormal ((), [6:63-67], (String "$idx")))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None }))]
                                                                  ))))
                                                           ];
                                                         unpacked_arg = None })))))
                                          ]
                                        };
                                      f_fun_kind = FSync; f_user_attributes = []; 
                                      f_external = false; f_hidden = false; 
                                      f_doc_comment = None },
                                    []))))
                             ];
                           unpacked_arg = None }));
                     et_free_vars = None }))))
            ]
          };
        f_fun_kind = FSync; f_user_attributes = [{ ua_name = ([5:10-18], "__SupportDynamicType"); ua_params = [] }]; 
        f_external = false; f_hidden = false; f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = []; 
      fd_package = None });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false };
       fd_file_attributes =
       [{ fa_user_attributes =
          [{ ua_name = ([3:9-33], "__EnableUnstableFeatures"); ua_params = [((), [3:34-52], (String "expression_trees")); ((), [3:54-81], (String "expression_tree_subscript"))] }];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
            ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false }
          }
         ];
       fd_mode = Mstrict; fd_name = ([9:10-19], "\\test_dict");
       fd_fun =
       { f_span = [9:1-11:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_tparams = []; f_ret = ((), (Some ([9:23-27], (Hprim Tvoid)))); 
         f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([10:3-89],
             (Expr
                ((), [10:3-88],
                 (ExpressionTree
                    { et_class = ([10:3-13], "\\ExampleDsl");
                      et_runtime_expr =
                      ((), [10:3-13],
                       (Call
                          { func = ((), [10:3-13], (Class_const (((), [10:3-13], (CI ([10:3-13], "\\ExampleDsl"))), ([10:3-13], "makeTree")))); 
                            targs = [];
                            args =
                            [(Anormal
                                ((), [10:14-87],
                                 (Shape
                                    [((SFlit_str ([10:14-87], "path")), ((), [10:14-87], (Id ([10:14-87], "\\__FILE__")))); (
                                      (SFlit_str ([10:14-87], "start_line")), ((), [10:14-87], (Int "10"))); (
                                      (SFlit_str ([10:14-87], "end_line")), ((), [10:14-87], (Int "10"))); (
                                      (SFlit_str ([10:14-87], "start_column")), ((), [10:14-87], (Int "13"))); (
                                      (SFlit_str ([10:14-87], "end_column")), ((), [10:14-87], (Int "86")))])));
                              (Anormal
                                 ((), [10:3-13],
                                  (Shape
                                     [((SFlit_str ([10:3-13], "splices")), ((), [10:3-13], (KeyValCollection (([10:3-13], Dict), None, []))));
                                       ((SFlit_str ([10:3-13], "functions")), ((), [10:3-13], (ValCollection (([10:3-13], Vec), None, []))));
                                       ((SFlit_str ([10:3-13], "static_methods")), ((), [10:3-13], (ValCollection (([10:3-13], Vec), None, []))));
                                       ((SFlit_str ([10:3-13], "variables")), ((), [10:3-13], (ValCollection (([10:3-13], Vec), None, []))));
                                       ((SFlit_str ([10:3-13], "lexically_enclosing_tree")), ((), [Pos.none], Null));
                                       ((SFlit_str ([10:3-13], "type")),
                                        ((), [10:14-87],
                                         (Efun
                                            { ef_fun =
                                              { f_span = [10:14-87]; 
                                                f_readonly_this = None; 
                                                f_annotation = (); f_readonly_ret = None; 
                                                f_tparams = []; f_ret = ((), None); 
                                                f_params = []; f_ctxs = (Some ([10:14-87], [([10:14-87], (Happly (([10:14-87], "\\HH\\Contexts\\defaults"), [])))])); 
                                                f_unsafe_ctxs = None;
                                                f_body =
                                                { fb_ast =
                                                  [([10:14-87],
                                                    (Return
                                                       (Some ((), [10:14-87],
                                                              (Call
                                                                 { func = ((), [10:14-87], (Class_const (((), [10:14-87], (CI ([10:14-87], "\\ExampleDsl"))), ([10:14-87], "lambdaType"))));
                                                                   targs = [];
                                                                   args =
                                                                   [(Anormal
                                                                    ((), [10:14-87],
                                                                    (Lfun (
                                                                    { f_span = [10:14-87]; 
                                                                    f_readonly_this = None; 
                                                                    f_annotation = (); 
                                                                    f_readonly_ret = None; 
                                                                    f_tparams = []; 
                                                                    f_ret = ((), None);
                                                                    f_params =
                                                                    [{ param_annotation = ();
                                                                    param_type_hint =
                                                                    (
                                                                    (),
                                                                    (Some (
                                                                    [10:15-46],
                                                                    (
                                                                    Happly ((
                                                                    [10:15-19], "\\HH\\dict"),
                                                                    [([10:20-33], (Happly (([10:20-33], "\\ExampleString"), []))); ([10:35-45], (Happly (([10:35-45], "\\ExampleInt"), [])))])))));
                                                                    param_pos = [10:47-51]; 
                                                                    param_name = "$map"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None };
                                                                    { param_annotation = (); 
                                                                    param_type_hint = ((), (Some ([10:53-66], (Happly (([10:53-66], "\\ExampleString"), []))))); 
                                                                    param_pos = [10:67-71]; 
                                                                    param_name = "$key"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None }]; 
                                                                    f_ctxs = None; 
                                                                    f_unsafe_ctxs = None;
                                                                    f_body =
                                                                    { fb_ast =
                                                                    [([10:77-87],
                                                                    (Return
                                                                    (Some (
                                                                    (), [10:77-87], (
                                                                    Array_get (((), [10:77-81], (Lvar ([10:77-81], $map))), (Some ((), [10:82-86], (Lvar ([10:82-86], $key))))))))))] };
                                                                    f_fun_kind = FSync; 
                                                                    f_user_attributes = []; 
                                                                    f_external = false; 
                                                                    f_hidden = false; 
                                                                    f_doc_comment = None }, 
                                                                    []))))];
                                                                   unpacked_arg = None })))))
                                                    ]
                                                  };
                                                f_fun_kind = FSync; f_user_attributes = []; 
                                                f_external = false; f_hidden = false; 
                                                f_doc_comment = None };
                                              ef_use = []; ef_closure_class_name = None; 
                                              ef_is_expr_tree_virtual_expr = false })))
                                       ])));
                              (Anormal
                                 ((), [10:14-87],
                                  (Lfun (
                                     { f_span = [10:14-87]; f_readonly_this = None; 
                                       f_annotation = (); f_readonly_ret = None; 
                                       f_tparams = []; f_ret = ((), None);
                                       f_params =
                                       [{ param_annotation = (); param_type_hint = ((), (Some ([10:3-13], (Happly (([10:3-13], "\\ExampleDsl"), []))))); 
                                          param_pos = [10:3-13]; param_name = "$0v"; 
                                          param_info = Param_required; 
                                          param_readonly = None; param_splat = None; 
                                          param_callconv = Pnormal; param_named = None; 
                                          param_user_attributes = []; 
                                          param_visibility = None }
                                         ];
                                       f_ctxs = None; f_unsafe_ctxs = None;
                                       f_body =
                                       { fb_ast =
                                         [([10:14-87],
                                           (Return
                                              (Some ((), [10:14-87],
                                                     (Call
                                                        { func =
                                                          ((), [10:14-87],
                                                           (Obj_get (((), [10:14-87], (Lvar ([10:14-87], $0v))), ((), [10:14-87], (Id ([10:14-87], "visitLambda"))), Regular, Is_method)));
                                                          targs = [];
                                                          args =
                                                          [(Anormal
                                                              ((), [10:14-87],
                                                               (Shape
                                                                  [((SFlit_str ([10:14-87], "path")), ((), [10:14-87], (Id ([10:14-87], "\\__FILE__"))));
                                                                    (
                                                                    (SFlit_str ([10:14-87], "start_line")), ((), [10:14-87], (Int "10")));
                                                                    (
                                                                    (SFlit_str ([10:14-87], "end_line")), ((), [10:14-87], (Int "10")));
                                                                    (
                                                                    (SFlit_str ([10:14-87], "start_column")), ((), [10:14-87], (Int "13")));
                                                                    (
                                                                    (SFlit_str ([10:14-87], "end_column")), ((), [10:14-87], (Int "86")))])));
                                                            (Anormal
                                                               ((), [10:47-71], (ValCollection (([10:47-71], Vec), None, [((), [10:47-51], (String "$map")); ((), [10:67-71], (String "$key"))]))));
                                                            (Anormal
                                                               ((), [10:77-87],
                                                                (ValCollection ((
                                                                   [10:77-87], Vec), None,
                                                                   [((), [10:77-87],
                                                                    (Call
                                                                    { func =
                                                                    ((), [10:77-87],
                                                                    (Obj_get (((), [10:77-87], (Lvar ([10:77-87], $0v))), ((), [10:77-87], (Id ([10:77-87], "visitReturn"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [10:77-87],
                                                                    (Shape
                                                                    [((SFlit_str ([10:77-87], "path")), ((), [10:77-87], (Id ([10:77-87], "\\__FILE__"))));
                                                                    ((SFlit_str ([10:77-87], "start_line")), ((), [10:77-87], (Int "10")));
                                                                    ((SFlit_str ([10:77-87], "end_line")), ((), [10:77-87], (Int "10")));
                                                                    ((SFlit_str ([10:77-87], "start_column")), ((), [10:77-87], (Int "76")));
                                                                    ((SFlit_str ([10:77-87], "end_column")), ((), [10:77-87], (Int "86")))])));
                                                                    (Anormal
                                                                    ((), [10:77-87],
                                                                    (Call
                                                                    { func =
                                                                    ((), [10:77-87],
                                                                    (Obj_get (((), [10:77-87], (Lvar ([10:77-87], $0v))), ((), [10:77-87], (Id ([10:77-87], "visitSubscript"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [10:77-87],
                                                                    (Shape
                                                                    [((SFlit_str ([10:77-87], "path")), ((), [10:77-87], (Id ([10:77-87], "\\__FILE__"))));
                                                                    ((SFlit_str ([10:77-87], "start_line")), ((), [10:77-87], (Int "10")));
                                                                    ((SFlit_str ([10:77-87], "end_line")), ((), [10:77-87], (Int "10")));
                                                                    ((SFlit_str ([10:77-87], "start_column")), ((), [10:77-87], (Int "76")));
                                                                    ((SFlit_str ([10:77-87], "end_column")), ((), [10:77-87], (Int "86")))])));
                                                                    (Anormal
                                                                    ((), [10:77-81],
                                                                    (Call
                                                                    { func =
                                                                    ((), [10:77-81],
                                                                    (Obj_get (((), [10:77-81], (Lvar ([10:77-81], $0v))), ((), [10:77-81], (Id ([10:77-81], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [10:77-81],
                                                                    (Shape
                                                                    [((SFlit_str ([10:77-81], "path")), ((), [10:77-81], (Id ([10:77-81], "\\__FILE__"))));
                                                                    ((SFlit_str ([10:77-81], "start_line")), ((), [10:77-81], (Int "10")));
                                                                    ((SFlit_str ([10:77-81], "end_line")), ((), [10:77-81], (Int "10")));
                                                                    ((SFlit_str ([10:77-81], "start_column")), ((), [10:77-81], (Int "76")));
                                                                    ((SFlit_str ([10:77-81], "end_column")), ((), [10:77-81], (Int "80")))]))); (
                                                                    Anormal ((), [10:77-81], (String "$map")))]; 
                                                                    unpacked_arg = None })));
                                                                    (Anormal
                                                                    ((), [10:82-86],
                                                                    (Call
                                                                    { func =
                                                                    ((), [10:82-86],
                                                                    (Obj_get (((), [10:82-86], (Lvar ([10:82-86], $0v))), ((), [10:82-86], (Id ([10:82-86], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [10:82-86],
                                                                    (Shape
                                                                    [((SFlit_str ([10:82-86], "path")), ((), [10:82-86], (Id ([10:82-86], "\\__FILE__"))));
                                                                    ((SFlit_str ([10:82-86], "start_line")), ((), [10:82-86], (Int "10")));
                                                                    ((SFlit_str ([10:82-86], "end_line")), ((), [10:82-86], (Int "10")));
                                                                    ((SFlit_str ([10:82-86], "start_column")), ((), [10:82-86], (Int "81")));
                                                                    ((SFlit_str ([10:82-86], "end_column")), ((), [10:82-86], (Int "85")))]))); (
                                                                    Anormal ((), [10:82-86], (String "$key")))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None }))]
                                                                   ))))
                                                            ];
                                                          unpacked_arg = None })))))
                                           ]
                                         };
                                       f_fun_kind = FSync; f_user_attributes = []; 
                                       f_external = false; f_hidden = false; 
                                       f_doc_comment = None },
                                     []))))
                              ];
                            unpacked_arg = None }));
                      et_free_vars = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = [{ ua_name = ([9:10-19], "__SupportDynamicType"); ua_params = [] }]; 
         f_external = false; f_hidden = false; f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = []; 
       fd_package = None });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false };
       fd_file_attributes =
       [{ fa_user_attributes =
          [{ ua_name = ([3:9-33], "__EnableUnstableFeatures"); ua_params = [((), [3:34-52], (String "expression_trees")); ((), [3:54-81], (String "expression_tree_subscript"))] }];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
            ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false }
          }
         ];
       fd_mode = Mstrict; fd_name = ([13:10-21], "\\test_nested");
       fd_fun =
       { f_span = [13:1-15:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_tparams = []; f_ret = ((), (Some ([13:25-29], (Hprim Tvoid)))); 
         f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([14:3-90],
             (Expr
                ((), [14:3-89],
                 (ExpressionTree
                    { et_class = ([14:3-13], "\\ExampleDsl");
                      et_runtime_expr =
                      ((), [14:3-13],
                       (Call
                          { func = ((), [14:3-13], (Class_const (((), [14:3-13], (CI ([14:3-13], "\\ExampleDsl"))), ([14:3-13], "makeTree")))); 
                            targs = [];
                            args =
                            [(Anormal
                                ((), [14:14-88],
                                 (Shape
                                    [((SFlit_str ([14:14-88], "path")), ((), [14:14-88], (Id ([14:14-88], "\\__FILE__")))); (
                                      (SFlit_str ([14:14-88], "start_line")), ((), [14:14-88], (Int "14"))); (
                                      (SFlit_str ([14:14-88], "end_line")), ((), [14:14-88], (Int "14"))); (
                                      (SFlit_str ([14:14-88], "start_column")), ((), [14:14-88], (Int "13"))); (
                                      (SFlit_str ([14:14-88], "end_column")), ((), [14:14-88], (Int "87")))])));
                              (Anormal
                                 ((), [14:3-13],
                                  (Shape
                                     [((SFlit_str ([14:3-13], "splices")), ((), [14:3-13], (KeyValCollection (([14:3-13], Dict), None, []))));
                                       ((SFlit_str ([14:3-13], "functions")), ((), [14:3-13], (ValCollection (([14:3-13], Vec), None, []))));
                                       ((SFlit_str ([14:3-13], "static_methods")), ((), [14:3-13], (ValCollection (([14:3-13], Vec), None, []))));
                                       ((SFlit_str ([14:3-13], "variables")), ((), [14:3-13], (ValCollection (([14:3-13], Vec), None, []))));
                                       ((SFlit_str ([14:3-13], "lexically_enclosing_tree")), ((), [Pos.none], Null));
                                       ((SFlit_str ([14:3-13], "type")),
                                        ((), [14:14-88],
                                         (Efun
                                            { ef_fun =
                                              { f_span = [14:14-88]; 
                                                f_readonly_this = None; 
                                                f_annotation = (); f_readonly_ret = None; 
                                                f_tparams = []; f_ret = ((), None); 
                                                f_params = []; f_ctxs = (Some ([14:14-88], [([14:14-88], (Happly (([14:14-88], "\\HH\\Contexts\\defaults"), [])))])); 
                                                f_unsafe_ctxs = None;
                                                f_body =
                                                { fb_ast =
                                                  [([14:14-88],
                                                    (Return
                                                       (Some ((), [14:14-88],
                                                              (Call
                                                                 { func = ((), [14:14-88], (Class_const (((), [14:14-88], (CI ([14:14-88], "\\ExampleDsl"))), ([14:14-88], "lambdaType"))));
                                                                   targs = [];
                                                                   args =
                                                                   [(Anormal
                                                                    ((), [14:14-88],
                                                                    (Lfun (
                                                                    { f_span = [14:14-88]; 
                                                                    f_readonly_this = None; 
                                                                    f_annotation = (); 
                                                                    f_readonly_ret = None; 
                                                                    f_tparams = []; 
                                                                    f_ret = ((), None);
                                                                    f_params =
                                                                    [{ param_annotation = ();
                                                                    param_type_hint =
                                                                    (
                                                                    (),
                                                                    (Some (
                                                                    [14:15-35],
                                                                    (
                                                                    Happly ((
                                                                    [14:15-18], "\\HH\\vec"),
                                                                    [([14:19-34], (Happly (([14:19-22], "\\HH\\vec"), [([14:23-33], (Happly (([14:23-33], "\\ExampleInt"), [])))])))])))));
                                                                    param_pos = [14:36-40]; 
                                                                    param_name = "$arr"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None };
                                                                    { param_annotation = (); 
                                                                    param_type_hint = ((), (Some ([14:42-52], (Happly (([14:42-52], "\\ExampleInt"), []))))); 
                                                                    param_pos = [14:53-55]; 
                                                                    param_name = "$i"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None };
                                                                    { param_annotation = (); 
                                                                    param_type_hint = ((), (Some ([14:57-67], (Happly (([14:57-67], "\\ExampleInt"), []))))); 
                                                                    param_pos = [14:68-70]; 
                                                                    param_name = "$j"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None }]; 
                                                                    f_ctxs = None; 
                                                                    f_unsafe_ctxs = None;
                                                                    f_body =
                                                                    { fb_ast =
                                                                    [([14:76-88],
                                                                    (Return
                                                                    (Some (
                                                                    (), [14:76-88],
                                                                    (
                                                                    Array_get (
                                                                    ((), [14:76-84], (Array_get (((), [14:76-80], (Lvar ([14:76-80], $arr))), (Some ((), [14:81-83], (Lvar ([14:81-83], $i))))))),
                                                                    (Some (
                                                                    (), [14:85-87], (Lvar ([14:85-87], $j))))))))))] }; 
                                                                    f_fun_kind = FSync; 
                                                                    f_user_attributes = []; 
                                                                    f_external = false; 
                                                                    f_hidden = false; 
                                                                    f_doc_comment = None }, 
                                                                    []))))];
                                                                   unpacked_arg = None })))))
                                                    ]
                                                  };
                                                f_fun_kind = FSync; f_user_attributes = []; 
                                                f_external = false; f_hidden = false; 
                                                f_doc_comment = None };
                                              ef_use = []; ef_closure_class_name = None; 
                                              ef_is_expr_tree_virtual_expr = false })))
                                       ])));
                              (Anormal
                                 ((), [14:14-88],
                                  (Lfun (
                                     { f_span = [14:14-88]; f_readonly_this = None; 
                                       f_annotation = (); f_readonly_ret = None; 
                                       f_tparams = []; f_ret = ((), None);
                                       f_params =
                                       [{ param_annotation = (); param_type_hint = ((), (Some ([14:3-13], (Happly (([14:3-13], "\\ExampleDsl"), []))))); 
                                          param_pos = [14:3-13]; param_name = "$0v"; 
                                          param_info = Param_required; 
                                          param_readonly = None; param_splat = None; 
                                          param_callconv = Pnormal; param_named = None; 
                                          param_user_attributes = []; 
                                          param_visibility = None }
                                         ];
                                       f_ctxs = None; f_unsafe_ctxs = None;
                                       f_body =
                                       { fb_ast =
                                         [([14:14-88],
                                           (Return
                                              (Some ((), [14:14-88],
                                                     (Call
                                                        { func =
                                                          ((), [14:14-88],
                                                           (Obj_get (((), [14:14-88], (Lvar ([14:14-88], $0v))), ((), [14:14-88], (Id ([14:14-88], "visitLambda"))), Regular, Is_method)));
                                                          targs = [];
                                                          args =
                                                          [(Anormal
                                                              ((), [14:14-88],
                                                               (Shape
                                                                  [((SFlit_str ([14:14-88], "path")), ((), [14:14-88], (Id ([14:14-88], "\\__FILE__"))));
                                                                    (
                                                                    (SFlit_str ([14:14-88], "start_line")), ((), [14:14-88], (Int "14")));
                                                                    (
                                                                    (SFlit_str ([14:14-88], "end_line")), ((), [14:14-88], (Int "14")));
                                                                    (
                                                                    (SFlit_str ([14:14-88], "start_column")), ((), [14:14-88], (Int "13")));
                                                                    (
                                                                    (SFlit_str ([14:14-88], "end_column")), ((), [14:14-88], (Int "87")))])));
                                                            (Anormal
                                                               ((), [14:36-70],
                                                                (ValCollection ((
                                                                   [14:36-70], Vec), None, 
                                                                   [((), [14:36-40], (String "$arr")); ((), [14:53-55], (String "$i")); ((), [14:68-70], (String "$j"))]))));
                                                            (Anormal
                                                               ((), [14:76-88],
                                                                (ValCollection ((
                                                                   [14:76-88], Vec), None,
                                                                   [((), [14:76-88],
                                                                    (Call
                                                                    { func =
                                                                    ((), [14:76-88],
                                                                    (Obj_get (((), [14:76-88], (Lvar ([14:76-88], $0v))), ((), [14:76-88], (Id ([14:76-88], "visitReturn"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [14:76-88],
                                                                    (Shape
                                                                    [((SFlit_str ([14:76-88], "path")), ((), [14:76-88], (Id ([14:76-88], "\\__FILE__"))));
                                                                    ((SFlit_str ([14:76-88], "start_line")), ((), [14:76-88], (Int "14")));
                                                                    ((SFlit_str ([14:76-88], "end_line")), ((), [14:76-88], (Int "14")));
                                                                    ((SFlit_str ([14:76-88], "start_column")), ((), [14:76-88], (Int "75")));
                                                                    ((SFlit_str ([14:76-88], "end_column")), ((), [14:76-88], (Int "87")))])));
                                                                    (Anormal
                                                                    ((), [14:76-88],
                                                                    (Call
                                                                    { func =
                                                                    ((), [14:76-88],
                                                                    (Obj_get (((), [14:76-88], (Lvar ([14:76-88], $0v))), ((), [14:76-88], (Id ([14:76-88], "visitSubscript"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [14:76-88],
                                                                    (Shape
                                                                    [((SFlit_str ([14:76-88], "path")), ((), [14:76-88], (Id ([14:76-88], "\\__FILE__"))));
                                                                    ((SFlit_str ([14:76-88], "start_line")), ((), [14:76-88], (Int "14")));
                                                                    ((SFlit_str ([14:76-88], "end_line")), ((), [14:76-88], (Int "14")));
                                                                    ((SFlit_str ([14:76-88], "start_column")), ((), [14:76-88], (Int "75")));
                                                                    ((SFlit_str ([14:76-88], "end_column")), ((), [14:76-88], (Int "87")))])));
                                                                    (Anormal
                                                                    ((), [14:76-84],
                                                                    (Call
                                                                    { func =
                                                                    ((), [14:76-84],
                                                                    (Obj_get (((), [14:76-84], (Lvar ([14:76-84], $0v))), ((), [14:76-84], (Id ([14:76-84], "visitSubscript"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [14:76-84],
                                                                    (Shape
                                                                    [((SFlit_str ([14:76-84], "path")), ((), [14:76-84], (Id ([14:76-84], "\\__FILE__"))));
                                                                    ((SFlit_str ([14:76-84], "start_line")), ((), [14:76-84], (Int "14")));
                                                                    ((SFlit_str ([14:76-84], "end_line")), ((), [14:76-84], (Int "14")));
                                                                    ((SFlit_str ([14:76-84], "start_column")), ((), [14:76-84], (Int "75")));
                                                                    ((SFlit_str ([14:76-84], "end_column")), ((), [14:76-84], (Int "83")))])));
                                                                    (Anormal
                                                                    ((), [14:76-80],
                                                                    (Call
                                                                    { func =
                                                                    ((), [14:76-80],
                                                                    (Obj_get (((), [14:76-80], (Lvar ([14:76-80], $0v))), ((), [14:76-80], (Id ([14:76-80], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [14:76-80],
                                                                    (Shape
                                                                    [((SFlit_str ([14:76-80], "path")), ((), [14:76-80], (Id ([14:76-80], "\\__FILE__"))));
                                                                    ((SFlit_str ([14:76-80], "start_line")), ((), [14:76-80], (Int "14")));
                                                                    ((SFlit_str ([14:76-80], "end_line")), ((), [14:76-80], (Int "14")));
                                                                    ((SFlit_str ([14:76-80], "start_column")), ((), [14:76-80], (Int "75")));
                                                                    ((SFlit_str ([14:76-80], "end_column")), ((), [14:76-80], (Int "79")))]))); (
                                                                    Anormal ((), [14:76-80], (String "$arr")))]; 
                                                                    unpacked_arg = None })));
                                                                    (Anormal
                                                                    ((), [14:81-83],
                                                                    (Call
                                                                    { func =
                                                                    ((), [14:81-83],
                                                                    (Obj_get (((), [14:81-83], (Lvar ([14:81-83], $0v))), ((), [14:81-83], (Id ([14:81-83], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [14:81-83],
                                                                    (Shape
                                                                    [((SFlit_str ([14:81-83], "path")), ((), [14:81-83], (Id ([14:81-83], "\\__FILE__"))));
                                                                    ((SFlit_str ([14:81-83], "start_line")), ((), [14:81-83], (Int "14")));
                                                                    ((SFlit_str ([14:81-83], "end_line")), ((), [14:81-83], (Int "14")));
                                                                    ((SFlit_str ([14:81-83], "start_column")), ((), [14:81-83], (Int "80")));
                                                                    ((SFlit_str ([14:81-83], "end_column")), ((), [14:81-83], (Int "82")))]))); (
                                                                    Anormal ((), [14:81-83], (String "$i")))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None })));
                                                                    (Anormal
                                                                    ((), [14:85-87],
                                                                    (Call
                                                                    { func =
                                                                    ((), [14:85-87],
                                                                    (Obj_get (((), [14:85-87], (Lvar ([14:85-87], $0v))), ((), [14:85-87], (Id ([14:85-87], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [14:85-87],
                                                                    (Shape
                                                                    [((SFlit_str ([14:85-87], "path")), ((), [14:85-87], (Id ([14:85-87], "\\__FILE__"))));
                                                                    ((SFlit_str ([14:85-87], "start_line")), ((), [14:85-87], (Int "14")));
                                                                    ((SFlit_str ([14:85-87], "end_line")), ((), [14:85-87], (Int "14")));
                                                                    ((SFlit_str ([14:85-87], "start_column")), ((), [14:85-87], (Int "84")));
                                                                    ((SFlit_str ([14:85-87], "end_column")), ((), [14:85-87], (Int "86")))]))); (
                                                                    Anormal ((), [14:85-87], (String "$j")))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None }))]
                                                                   ))))
                                                            ];
                                                          unpacked_arg = None })))))
                                           ]
                                         };
                                       f_fun_kind = FSync; f_user_attributes = []; 
                                       f_external = false; f_hidden = false; 
                                       f_doc_comment = None },
                                     []))))
                              ];
                            unpacked_arg = None }));
                      et_free_vars = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = [{ ua_name = ([13:10-21], "__SupportDynamicType"); ua_params = [] }]; 
         f_external = false; f_hidden = false; f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = []; 
       fd_package = None });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false };
       fd_file_attributes =
       [{ fa_user_attributes =
          [{ ua_name = ([3:9-33], "__EnableUnstableFeatures"); ua_params = [((), [3:34-52], (String "expression_trees")); ((), [3:54-81], (String "expression_tree_subscript"))] }];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
            ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false }
          }
         ];
       fd_mode = Mstrict; fd_name = ([17:10-21], "\\test_keyset");
       fd_fun =
       { f_span = [17:1-19:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_tparams = []; f_ret = ((), (Some ([17:25-29], (Hprim Tvoid)))); 
         f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([18:3-71],
             (Expr
                ((), [18:3-70],
                 (ExpressionTree
                    { et_class = ([18:3-13], "\\ExampleDsl");
                      et_runtime_expr =
                      ((), [18:3-13],
                       (Call
                          { func = ((), [18:3-13], (Class_const (((), [18:3-13], (CI ([18:3-13], "\\ExampleDsl"))), ([18:3-13], "makeTree")))); 
                            targs = [];
                            args =
                            [(Anormal
                                ((), [18:14-69],
                                 (Shape
                                    [((SFlit_str ([18:14-69], "path")), ((), [18:14-69], (Id ([18:14-69], "\\__FILE__")))); (
                                      (SFlit_str ([18:14-69], "start_line")), ((), [18:14-69], (Int "18"))); (
                                      (SFlit_str ([18:14-69], "end_line")), ((), [18:14-69], (Int "18"))); (
                                      (SFlit_str ([18:14-69], "start_column")), ((), [18:14-69], (Int "13"))); (
                                      (SFlit_str ([18:14-69], "end_column")), ((), [18:14-69], (Int "68")))])));
                              (Anormal
                                 ((), [18:3-13],
                                  (Shape
                                     [((SFlit_str ([18:3-13], "splices")), ((), [18:3-13], (KeyValCollection (([18:3-13], Dict), None, []))));
                                       ((SFlit_str ([18:3-13], "functions")), ((), [18:3-13], (ValCollection (([18:3-13], Vec), None, []))));
                                       ((SFlit_str ([18:3-13], "static_methods")), ((), [18:3-13], (ValCollection (([18:3-13], Vec), None, []))));
                                       ((SFlit_str ([18:3-13], "variables")), ((), [18:3-13], (ValCollection (([18:3-13], Vec), None, []))));
                                       ((SFlit_str ([18:3-13], "lexically_enclosing_tree")), ((), [Pos.none], Null));
                                       ((SFlit_str ([18:3-13], "type")),
                                        ((), [18:14-69],
                                         (Efun
                                            { ef_fun =
                                              { f_span = [18:14-69]; 
                                                f_readonly_this = None; 
                                                f_annotation = (); f_readonly_ret = None; 
                                                f_tparams = []; f_ret = ((), None); 
                                                f_params = []; f_ctxs = (Some ([18:14-69], [([18:14-69], (Happly (([18:14-69], "\\HH\\Contexts\\defaults"), [])))])); 
                                                f_unsafe_ctxs = None;
                                                f_body =
                                                { fb_ast =
                                                  [([18:14-69],
                                                    (Return
                                                       (Some ((), [18:14-69],
                                                              (Call
                                                                 { func = ((), [18:14-69], (Class_const (((), [18:14-69], (CI ([18:14-69], "\\ExampleDsl"))), ([18:14-69], "lambdaType"))));
                                                                   targs = [];
                                                                   args =
                                                                   [(Anormal
                                                                    ((), [18:14-69],
                                                                    (Lfun (
                                                                    { f_span = [18:14-69]; 
                                                                    f_readonly_this = None; 
                                                                    f_annotation = (); 
                                                                    f_readonly_ret = None; 
                                                                    f_tparams = []; 
                                                                    f_ret = ((), None);
                                                                    f_params =
                                                                    [{ param_annotation = ();
                                                                    param_type_hint =
                                                                    (
                                                                    (), (Some ([18:15-33], (Happly (([18:15-21], "\\HH\\keyset"), [([18:22-32], (Happly (([18:22-32], "\\ExampleInt"), [])))])))));
                                                                    param_pos = [18:34-37]; 
                                                                    param_name = "$ks"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None };
                                                                    { param_annotation = (); 
                                                                    param_type_hint = ((), (Some ([18:39-49], (Happly (([18:39-49], "\\ExampleInt"), []))))); 
                                                                    param_pos = [18:50-54]; 
                                                                    param_name = "$key"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None }]; 
                                                                    f_ctxs = None; 
                                                                    f_unsafe_ctxs = None;
                                                                    f_body =
                                                                    { fb_ast =
                                                                    [([18:60-69],
                                                                    (Return
                                                                    (Some (
                                                                    (), [18:60-69], (Array_get (((), [18:60-63], (Lvar ([18:60-63], $ks))), (Some ((), [18:64-68], (Lvar ([18:64-68], $key))))))))))] };
                                                                    f_fun_kind = FSync; 
                                                                    f_user_attributes = []; 
                                                                    f_external = false; 
                                                                    f_hidden = false; 
                                                                    f_doc_comment = None }, 
                                                                    []))))];
                                                                   unpacked_arg = None })))))
                                                    ]
                                                  };
                                                f_fun_kind = FSync; f_user_attributes = []; 
                                                f_external = false; f_hidden = false; 
                                                f_doc_comment = None };
                                              ef_use = []; ef_closure_class_name = None; 
                                              ef_is_expr_tree_virtual_expr = false })))
                                       ])));
                              (Anormal
                                 ((), [18:14-69],
                                  (Lfun (
                                     { f_span = [18:14-69]; f_readonly_this = None; 
                                       f_annotation = (); f_readonly_ret = None; 
                                       f_tparams = []; f_ret = ((), None);
                                       f_params =
                                       [{ param_annotation = (); param_type_hint = ((), (Some ([18:3-13], (Happly (([18:3-13], "\\ExampleDsl"), []))))); 
                                          param_pos = [18:3-13]; param_name = "$0v"; 
                                          param_info = Param_required; 
                                          param_readonly = None; param_splat = None; 
                                          param_callconv = Pnormal; param_named = None; 
                                          param_user_attributes = []; 
                                          param_visibility = None }
                                         ];
                                       f_ctxs = None; f_unsafe_ctxs = None;
                                       f_body =
                                       { fb_ast =
                                         [([18:14-69],
                                           (Return
                                              (Some ((), [18:14-69],
                                                     (Call
                                                        { func =
                                                          ((), [18:14-69],
                                                           (Obj_get (((), [18:14-69], (Lvar ([18:14-69], $0v))), ((), [18:14-69], (Id ([18:14-69], "visitLambda"))), Regular, Is_method)));
                                                          targs = [];
                                                          args =
                                                          [(Anormal
                                                              ((), [18:14-69],
                                                               (Shape
                                                                  [((SFlit_str ([18:14-69], "path")), ((), [18:14-69], (Id ([18:14-69], "\\__FILE__"))));
                                                                    (
                                                                    (SFlit_str ([18:14-69], "start_line")), ((), [18:14-69], (Int "18")));
                                                                    (
                                                                    (SFlit_str ([18:14-69], "end_line")), ((), [18:14-69], (Int "18")));
                                                                    (
                                                                    (SFlit_str ([18:14-69], "start_column")), ((), [18:14-69], (Int "13")));
                                                                    (
                                                                    (SFlit_str ([18:14-69], "end_column")), ((), [18:14-69], (Int "68")))])));
                                                            (Anormal ((), [18:34-54], (ValCollection (([18:34-54], Vec), None, [((), [18:34-37], (String "$ks")); ((), [18:50-54], (String "$key"))]))));
                                                            (Anormal
                                                               ((), [18:60-69],
                                                                (ValCollection ((
                                                                   [18:60-69], Vec), None,
                                                                   [((), [18:60-69],
                                                                    (Call
                                                                    { func =
                                                                    ((), [18:60-69],
                                                                    (Obj_get (((), [18:60-69], (Lvar ([18:60-69], $0v))), ((), [18:60-69], (Id ([18:60-69], "visitReturn"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [18:60-69],
                                                                    (Shape
                                                                    [((SFlit_str ([18:60-69], "path")), ((), [18:60-69], (Id ([18:60-69], "\\__FILE__"))));
                                                                    ((SFlit_str ([18:60-69], "start_line")), ((), [18:60-69], (Int "18")));
                                                                    ((SFlit_str ([18:60-69], "end_line")), ((), [18:60-69], (Int "18")));
                                                                    ((SFlit_str ([18:60-69], "start_column")), ((), [18:60-69], (Int "59")));
                                                                    ((SFlit_str ([18:60-69], "end_column")), ((), [18:60-69], (Int "68")))])));
                                                                    (Anormal
                                                                    ((), [18:60-69],
                                                                    (Call
                                                                    { func =
                                                                    ((), [18:60-69],
                                                                    (Obj_get (((), [18:60-69], (Lvar ([18:60-69], $0v))), ((), [18:60-69], (Id ([18:60-69], "visitSubscript"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [18:60-69],
                                                                    (Shape
                                                                    [((SFlit_str ([18:60-69], "path")), ((), [18:60-69], (Id ([18:60-69], "\\__FILE__"))));
                                                                    ((SFlit_str ([18:60-69], "start_line")), ((), [18:60-69], (Int "18")));
                                                                    ((SFlit_str ([18:60-69], "end_line")), ((), [18:60-69], (Int "18")));
                                                                    ((SFlit_str ([18:60-69], "start_column")), ((), [18:60-69], (Int "59")));
                                                                    ((SFlit_str ([18:60-69], "end_column")), ((), [18:60-69], (Int "68")))])));
                                                                    (Anormal
                                                                    ((), [18:60-63],
                                                                    (Call
                                                                    { func =
                                                                    ((), [18:60-63],
                                                                    (Obj_get (((), [18:60-63], (Lvar ([18:60-63], $0v))), ((), [18:60-63], (Id ([18:60-63], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [18:60-63],
                                                                    (Shape
                                                                    [((SFlit_str ([18:60-63], "path")), ((), [18:60-63], (Id ([18:60-63], "\\__FILE__"))));
                                                                    ((SFlit_str ([18:60-63], "start_line")), ((), [18:60-63], (Int "18")));
                                                                    ((SFlit_str ([18:60-63], "end_line")), ((), [18:60-63], (Int "18")));
                                                                    ((SFlit_str ([18:60-63], "start_column")), ((), [18:60-63], (Int "59")));
                                                                    ((SFlit_str ([18:60-63], "end_column")), ((), [18:60-63], (Int "62")))]))); (
                                                                    Anormal ((), [18:60-63], (String "$ks")))]; 
                                                                    unpacked_arg = None })));
                                                                    (Anormal
                                                                    ((), [18:64-68],
                                                                    (Call
                                                                    { func =
                                                                    ((), [18:64-68],
                                                                    (Obj_get (((), [18:64-68], (Lvar ([18:64-68], $0v))), ((), [18:64-68], (Id ([18:64-68], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [18:64-68],
                                                                    (Shape
                                                                    [((SFlit_str ([18:64-68], "path")), ((), [18:64-68], (Id ([18:64-68], "\\__FILE__"))));
                                                                    ((SFlit_str ([18:64-68], "start_line")), ((), [18:64-68], (Int "18")));
                                                                    ((SFlit_str ([18:64-68], "end_line")), ((), [18:64-68], (Int "18")));
                                                                    ((SFlit_str ([18:64-68], "start_column")), ((), [18:64-68], (Int "63")));
                                                                    ((SFlit_str ([18:64-68], "end_column")), ((), [18:64-68], (Int "67")))]))); (
                                                                    Anormal ((), [18:64-68], (String "$key")))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None }))]
                                                                   ))))
                                                            ];
                                                          unpacked_arg = None })))))
                                           ]
                                         };
                                       f_fun_kind = FSync; f_user_attributes = []; 
                                       f_external = false; f_hidden = false; 
                                       f_doc_comment = None },
                                     []))))
                              ];
                            unpacked_arg = None }));
                      et_free_vars = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = [{ ua_name = ([17:10-21], "__SupportDynamicType"); ua_params = [] }]; 
         f_external = false; f_hidden = false; f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = []; 
       fd_package = None });
  (Class
     { c_span = [21:1-23:2]; c_annotation = (); c_mode = Mstrict; c_final = false; 
       c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Abstract); 
       c_name = ([21:16-23], "\\PropVec"); c_tparams = []; c_extends = []; 
       c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; c_reqs = []; 
       c_implements = []; c_consts = []; c_typeconsts = [];
       c_vars =
       [{ cv_final = false; cv_xhp_attr = None; cv_abstract = false; 
          cv_readonly = false; cv_visibility = Public; cv_type = ((), (Some ([22:10-25], (Happly (([22:10-13], "\\HH\\vec"), [([22:14-24], (Happly (([22:14-24], "\\ExampleInt"), [])))])))));
          cv_id = ([22:26-32], "items"); cv_expr = None; cv_user_attributes = []; 
          cv_doc_comment = None; cv_is_static = false; cv_span = [22:26-32] }
         ];
       c_methods = []; c_xhp_children = []; c_xhp_attrs = [];
       c_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false };
       c_user_attributes = [{ ua_name = ([21:16-23], "__SupportDynamicType"); ua_params = [] }];
       c_file_attributes =
       [{ fa_user_attributes =
          [{ ua_name = ([3:9-33], "__EnableUnstableFeatures"); ua_params = [((), [3:34-52], (String "expression_trees")); ((), [3:54-81], (String "expression_tree_subscript"))] }];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
            ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false }
          }
         ];
       c_docs_url = None; c_enum = None; c_doc_comment = None; c_emit_id = None; 
       c_internal = false; c_module = None; c_package = None });
  (Fun
     { fd_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false };
       fd_file_attributes =
       [{ fa_user_attributes =
          [{ ua_name = ([3:9-33], "__EnableUnstableFeatures"); ua_params = [((), [3:34-52], (String "expression_trees")); ((), [3:54-81], (String "expression_tree_subscript"))] }];
          fa_namespace =
          { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
            ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
            ns_mode = Namespace_env.ForTypecheck; ns_disable_xhp_element_mangling = false }
          }
         ];
       fd_mode = Mstrict; fd_name = ([25:10-29], "\\test_prop_subscript");
       fd_fun =
       { f_span = [25:1-27:2]; f_readonly_this = None; f_annotation = (); 
         f_readonly_ret = None; f_tparams = []; f_ret = ((), (Some ([25:33-37], (Hprim Tvoid)))); 
         f_params = []; f_ctxs = None; f_unsafe_ctxs = None;
         f_body =
         { fb_ast =
           [([26:3-69],
             (Expr
                ((), [26:3-68],
                 (ExpressionTree
                    { et_class = ([26:3-13], "\\ExampleDsl");
                      et_runtime_expr =
                      ((), [26:3-13],
                       (Call
                          { func = ((), [26:3-13], (Class_const (((), [26:3-13], (CI ([26:3-13], "\\ExampleDsl"))), ([26:3-13], "makeTree")))); 
                            targs = [];
                            args =
                            [(Anormal
                                ((), [26:14-67],
                                 (Shape
                                    [((SFlit_str ([26:14-67], "path")), ((), [26:14-67], (Id ([26:14-67], "\\__FILE__")))); (
                                      (SFlit_str ([26:14-67], "start_line")), ((), [26:14-67], (Int "26"))); (
                                      (SFlit_str ([26:14-67], "end_line")), ((), [26:14-67], (Int "26"))); (
                                      (SFlit_str ([26:14-67], "start_column")), ((), [26:14-67], (Int "13"))); (
                                      (SFlit_str ([26:14-67], "end_column")), ((), [26:14-67], (Int "66")))])));
                              (Anormal
                                 ((), [26:3-13],
                                  (Shape
                                     [((SFlit_str ([26:3-13], "splices")), ((), [26:3-13], (KeyValCollection (([26:3-13], Dict), None, []))));
                                       ((SFlit_str ([26:3-13], "functions")), ((), [26:3-13], (ValCollection (([26:3-13], Vec), None, []))));
                                       ((SFlit_str ([26:3-13], "static_methods")), ((), [26:3-13], (ValCollection (([26:3-13], Vec), None, []))));
                                       ((SFlit_str ([26:3-13], "variables")), ((), [26:3-13], (ValCollection (([26:3-13], Vec), None, []))));
                                       ((SFlit_str ([26:3-13], "lexically_enclosing_tree")), ((), [Pos.none], Null));
                                       ((SFlit_str ([26:3-13], "type")),
                                        ((), [26:14-67],
                                         (Efun
                                            { ef_fun =
                                              { f_span = [26:14-67]; 
                                                f_readonly_this = None; 
                                                f_annotation = (); f_readonly_ret = None; 
                                                f_tparams = []; f_ret = ((), None); 
                                                f_params = []; f_ctxs = (Some ([26:14-67], [([26:14-67], (Happly (([26:14-67], "\\HH\\Contexts\\defaults"), [])))])); 
                                                f_unsafe_ctxs = None;
                                                f_body =
                                                { fb_ast =
                                                  [([26:14-67],
                                                    (Return
                                                       (Some ((), [26:14-67],
                                                              (Call
                                                                 { func = ((), [26:14-67], (Class_const (((), [26:14-67], (CI ([26:14-67], "\\ExampleDsl"))), ([26:14-67], "lambdaType"))));
                                                                   targs = [];
                                                                   args =
                                                                   [(Anormal
                                                                    ((), [26:14-67],
                                                                    (Lfun (
                                                                    { f_span = [26:14-67]; 
                                                                    f_readonly_this = None; 
                                                                    f_annotation = (); 
                                                                    f_readonly_ret = None; 
                                                                    f_tparams = []; 
                                                                    f_ret = ((), None);
                                                                    f_params =
                                                                    [{ param_annotation = (); 
                                                                    param_type_hint = ((), (Some ([26:15-22], (Happly (([26:15-22], "\\PropVec"), []))))); 
                                                                    param_pos = [26:23-27]; 
                                                                    param_name = "$obj"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None };
                                                                    { param_annotation = (); 
                                                                    param_type_hint = ((), (Some ([26:29-39], (Happly (([26:29-39], "\\ExampleInt"), []))))); 
                                                                    param_pos = [26:40-44]; 
                                                                    param_name = "$idx"; 
                                                                    param_info = Param_required; 
                                                                    param_readonly = None; 
                                                                    param_splat = None; 
                                                                    param_callconv = Pnormal; 
                                                                    param_named = None; 
                                                                    param_user_attributes = []; 
                                                                    param_visibility = None }]; 
                                                                    f_ctxs = None; 
                                                                    f_unsafe_ctxs = None;
                                                                    f_body =
                                                                    { fb_ast =
                                                                    [([26:50-67],
                                                                    (Return
                                                                    (Some (
                                                                    (), [26:50-67],
                                                                    (
                                                                    Array_get (
                                                                    ((), [26:50-61],
                                                                    (Obj_get (((), [26:50-54], (Lvar ([26:50-54], $obj))), ((), [26:56-61], (Id ([26:56-61], "items"))), Regular, Is_prop))),
                                                                    (Some (
                                                                    (), [26:62-66], (Lvar ([26:62-66], $idx))))))))))] }; 
                                                                    f_fun_kind = FSync; 
                                                                    f_user_attributes = []; 
                                                                    f_external = false; 
                                                                    f_hidden = false; 
                                                                    f_doc_comment = None }, 
                                                                    []))))];
                                                                   unpacked_arg = None })))))
                                                    ]
                                                  };
                                                f_fun_kind = FSync; f_user_attributes = []; 
                                                f_external = false; f_hidden = false; 
                                                f_doc_comment = None };
                                              ef_use = []; ef_closure_class_name = None; 
                                              ef_is_expr_tree_virtual_expr = false })))
                                       ])));
                              (Anormal
                                 ((), [26:14-67],
                                  (Lfun (
                                     { f_span = [26:14-67]; f_readonly_this = None; 
                                       f_annotation = (); f_readonly_ret = None; 
                                       f_tparams = []; f_ret = ((), None);
                                       f_params =
                                       [{ param_annotation = (); param_type_hint = ((), (Some ([26:3-13], (Happly (([26:3-13], "\\ExampleDsl"), []))))); 
                                          param_pos = [26:3-13]; param_name = "$0v"; 
                                          param_info = Param_required; 
                                          param_readonly = None; param_splat = None; 
                                          param_callconv = Pnormal; param_named = None; 
                                          param_user_attributes = []; 
                                          param_visibility = None }
                                         ];
                                       f_ctxs = None; f_unsafe_ctxs = None;
                                       f_body =
                                       { fb_ast =
                                         [([26:14-67],
                                           (Return
                                              (Some ((), [26:14-67],
                                                     (Call
                                                        { func =
                                                          ((), [26:14-67],
                                                           (Obj_get (((), [26:14-67], (Lvar ([26:14-67], $0v))), ((), [26:14-67], (Id ([26:14-67], "visitLambda"))), Regular, Is_method)));
                                                          targs = [];
                                                          args =
                                                          [(Anormal
                                                              ((), [26:14-67],
                                                               (Shape
                                                                  [((SFlit_str ([26:14-67], "path")), ((), [26:14-67], (Id ([26:14-67], "\\__FILE__"))));
                                                                    (
                                                                    (SFlit_str ([26:14-67], "start_line")), ((), [26:14-67], (Int "26")));
                                                                    (
                                                                    (SFlit_str ([26:14-67], "end_line")), ((), [26:14-67], (Int "26")));
                                                                    (
                                                                    (SFlit_str ([26:14-67], "start_column")), ((), [26:14-67], (Int "13")));
                                                                    (
                                                                    (SFlit_str ([26:14-67], "end_column")), ((), [26:14-67], (Int "66")))])));
                                                            (Anormal
                                                               ((), [26:23-44], (ValCollection (([26:23-44], Vec), None, [((), [26:23-27], (String "$obj")); ((), [26:40-44], (String "$idx"))]))));
                                                            (Anormal
                                                               ((), [26:50-67],
                                                                (ValCollection ((
                                                                   [26:50-67], Vec), None,
                                                                   [((), [26:50-67],
                                                                    (Call
                                                                    { func =
                                                                    ((), [26:50-67],
                                                                    (Obj_get (((), [26:50-67], (Lvar ([26:50-67], $0v))), ((), [26:50-67], (Id ([26:50-67], "visitReturn"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [26:50-67],
                                                                    (Shape
                                                                    [((SFlit_str ([26:50-67], "path")), ((), [26:50-67], (Id ([26:50-67], "\\__FILE__"))));
                                                                    ((SFlit_str ([26:50-67], "start_line")), ((), [26:50-67], (Int "26")));
                                                                    ((SFlit_str ([26:50-67], "end_line")), ((), [26:50-67], (Int "26")));
                                                                    ((SFlit_str ([26:50-67], "start_column")), ((), [26:50-67], (Int "49")));
                                                                    ((SFlit_str ([26:50-67], "end_column")), ((), [26:50-67], (Int "66")))])));
                                                                    (Anormal
                                                                    ((), [26:50-67],
                                                                    (Call
                                                                    { func =
                                                                    ((), [26:50-67],
                                                                    (Obj_get (((), [26:50-67], (Lvar ([26:50-67], $0v))), ((), [26:50-67], (Id ([26:50-67], "visitSubscript"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [26:50-67],
                                                                    (Shape
                                                                    [((SFlit_str ([26:50-67], "path")), ((), [26:50-67], (Id ([26:50-67], "\\__FILE__"))));
                                                                    ((SFlit_str ([26:50-67], "start_line")), ((), [26:50-67], (Int "26")));
                                                                    ((SFlit_str ([26:50-67], "end_line")), ((), [26:50-67], (Int "26")));
                                                                    ((SFlit_str ([26:50-67], "start_column")), ((), [26:50-67], (Int "49")));
                                                                    ((SFlit_str ([26:50-67], "end_column")), ((), [26:50-67], (Int "66")))])));
                                                                    (Anormal
                                                                    ((), [26:50-61],
                                                                    (Call
                                                                    { func =
                                                                    ((), [26:50-61],
                                                                    (Obj_get ((
                                                                    (), [26:50-61], (Lvar ([26:50-61], $0v))), (
                                                                    (), [26:50-61], (Id ([26:50-61], "visitPropertyAccess"))), Regular, Is_method))); 
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [26:50-61],
                                                                    (Shape
                                                                    [((SFlit_str ([26:50-61], "path")), ((), [26:50-61], (Id ([26:50-61], "\\__FILE__"))));
                                                                    ((SFlit_str ([26:50-61], "start_line")), ((), [26:50-61], (Int "26")));
                                                                    ((SFlit_str ([26:50-61], "end_line")), ((), [26:50-61], (Int "26")));
                                                                    ((SFlit_str ([26:50-61], "start_column")), ((), [26:50-61], (Int "49")));
                                                                    ((SFlit_str ([26:50-61], "end_column")), ((), [26:50-61], (Int "60")))])));
                                                                    (Anormal
                                                                    ((), [26:50-54],
                                                                    (Call
                                                                    { func =
                                                                    ((), [26:50-54],
                                                                    (Obj_get (((), [26:50-54], (Lvar ([26:50-54], $0v))), ((), [26:50-54], (Id ([26:50-54], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [26:50-54],
                                                                    (Shape
                                                                    [((SFlit_str ([26:50-54], "path")), ((), [26:50-54], (Id ([26:50-54], "\\__FILE__"))));
                                                                    ((SFlit_str ([26:50-54], "start_line")), ((), [26:50-54], (Int "26")));
                                                                    ((SFlit_str ([26:50-54], "end_line")), ((), [26:50-54], (Int "26")));
                                                                    ((SFlit_str ([26:50-54], "start_column")), ((), [26:50-54], (Int "49")));
                                                                    ((SFlit_str ([26:50-54], "end_column")), ((), [26:50-54], (Int "53")))]))); (
                                                                    Anormal ((), [26:50-54], (String "$obj")))]; 
                                                                    unpacked_arg = None }))); (
                                                                    Anormal ((), [26:56-61], (String "items")))]; 
                                                                    unpacked_arg = None })));
                                                                    (Anormal
                                                                    ((), [26:62-66],
                                                                    (Call
                                                                    { func =
                                                                    ((), [26:62-66],
                                                                    (Obj_get (((), [26:62-66], (Lvar ([26:62-66], $0v))), ((), [26:62-66], (Id ([26:62-66], "visitLocal"))), Regular, Is_method)));
                                                                    targs = [];
                                                                    args =
                                                                    [(Anormal
                                                                    ((), [26:62-66],
                                                                    (Shape
                                                                    [((SFlit_str ([26:62-66], "path")), ((), [26:62-66], (Id ([26:62-66], "\\__FILE__"))));
                                                                    ((SFlit_str ([26:62-66], "start_line")), ((), [26:62-66], (Int "26")));
                                                                    ((SFlit_str ([26:62-66], "end_line")), ((), [26:62-66], (Int "26")));
                                                                    ((SFlit_str ([26:62-66], "start_column")), ((), [26:62-66], (Int "61")));
                                                                    ((SFlit_str ([26:62-66], "end_column")), ((), [26:62-66], (Int "65")))]))); (
                                                                    Anormal ((), [26:62-66], (String "$idx")))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None })))]; 
                                                                    unpacked_arg = None }))]
                                                                   ))))
                                                            ];
                                                          unpacked_arg = None })))))
                                           ]
                                         };
                                       f_fun_kind = FSync; f_user_attributes = []; 
                                       f_external = false; f_hidden = false; 
                                       f_doc_comment = None },
                                     []))))
                              ];
                            unpacked_arg = None }));
                      et_free_vars = None }))))
             ]
           };
         f_fun_kind = FSync; f_user_attributes = [{ ua_name = ([25:10-29], "__SupportDynamicType"); ua_params = [] }]; 
         f_external = false; f_hidden = false; f_doc_comment = None };
       fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = []; 
       fd_package = None })
  ]
