[(Fun
    { fd_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_auto_ns_map = []; ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      fd_file_attributes = []; fd_mode = Mstrict; fd_name = ([3:10-37], "\\tcopt_soft_as_like_disabled");
      fd_fun =
      { f_span = [3:1-5:2]; f_readonly_this = None; f_annotation = (); 
        f_readonly_ret = None; f_ret = ((), (Some ([3:58-62], (Hprim Tint))));
        f_params =
        [{ param_annotation = (); param_type_hint = ((), (Some ([3:49-52], (Hprim Tint)))); 
           param_is_variadic = false; param_pos = [3:53-55]; param_name = "$x"; 
           param_expr = None; param_readonly = None; param_callconv = Pnormal; 
           param_user_attributes = [{ ua_name = ([3:40-46], "__Soft"); ua_params = [] }]; 
           param_visibility = None }
          ];
        f_ctxs = None; f_unsafe_ctxs = None;
        f_body = { fb_ast = [([4:3-17], (Return (Some ((), [4:10-16], (Binop { bop = Plus; lhs = ((), [4:10-12], (Lvar ([4:10-12], $x))); rhs = ((), [4:15-16], (Int "1")) })))))] };
        f_fun_kind = FSync; f_user_attributes = []; f_external = false; 
        f_doc_comment = None };
      fd_internal = false; fd_module = None; fd_tparams = []; fd_where_constraints = [] })
  ]
