Errors:
  [3:14-18] The type `this` cannot be used as a constraint on a class generic, or as the type of a static member variable
  [7:23-27] The type `this` cannot be used as a constraint on a class generic, or as the type of a static member variable
[(Class
    { c_span = [3:1-5:2]; c_annotation = (); c_mode = Mstrict; c_final = false; 
      c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Concrete); 
      c_name = ([3:7-8], "\\C");
      c_tparams = [{ tp_variance = Invariant; tp_name = ([3:9-10], "T"); tp_parameters = []; tp_constraints = [(Constraint_as, ([3:14-18], Hthis))]; tp_reified = Erased; tp_user_attributes = [] }];
      c_extends = []; c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; 
      c_reqs = []; c_implements = []; c_where_constraints = []; c_consts = []; 
      c_typeconsts = [];
      c_vars =
      [{ cv_final = false; cv_xhp_attr = None; cv_abstract = false; cv_readonly = false; 
         cv_visibility = Private; cv_type = ((), (Some ([4:11-13], (Hoption ([4:12-13], (Habstr ("T", []))))))); 
         cv_id = ([4:14-16], "x"); cv_expr = None; cv_user_attributes = []; 
         cv_doc_comment = None; cv_is_static = false; cv_span = [4:14-16] }
        ];
      c_methods = []; c_xhp_children = []; c_xhp_attrs = [];
      c_namespace =
      { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
        ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
        ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
      c_user_attributes = []; c_file_attributes = []; c_docs_url = None; 
      c_enum = None; c_doc_comment = None; c_emit_id = None; c_internal = false; 
      c_module = None });
  (Class
     { c_span = [7:1-9:2]; c_annotation = (); c_mode = Mstrict; c_final = false; 
       c_is_xhp = false; c_has_xhp_keyword = false; c_kind = (Cclass Abstract); 
       c_name = ([7:16-17], "\\C");
       c_tparams =
       [{ tp_variance = Invariant; tp_name = ([7:18-19], "T"); tp_parameters = []; 
          tp_constraints = [(Constraint_as, ([7:23-30], (Haccess (([7:23-27], Hthis), [([7:29-30], "X")]))))]; 
          tp_reified = Erased; tp_user_attributes = [] }
         ];
       c_extends = []; c_uses = []; c_xhp_attr_uses = []; c_xhp_category = None; 
       c_reqs = []; c_implements = []; c_where_constraints = []; c_consts = [];
       c_typeconsts =
       [{ c_tconst_user_attributes = []; c_tconst_name = ([8:23-24], "X"); 
          c_tconst_kind = (TCAbstract { c_atc_as_constraint = None; c_atc_super_constraint = None; c_atc_default = None }); 
          c_tconst_span = [8:3-25]; c_tconst_doc_comment = None; c_tconst_is_ctx = false }
         ];
       c_vars = []; c_methods = []; c_xhp_children = []; c_xhp_attrs = [];
       c_namespace =
       { Namespace_env.ns_ns_uses = <opaque>; ns_class_uses = <opaque>; 
         ns_fun_uses = <opaque>; ns_const_uses = <opaque>; ns_name = None; 
         ns_is_codegen = false; ns_disable_xhp_element_mangling = false };
       c_user_attributes = []; c_file_attributes = []; c_docs_url = None; 
       c_enum = None; c_doc_comment = None; c_emit_id = None; c_internal = false; 
       c_module = None })
  ]
