HHVM_DEFINE_EXTENSION("asio" REQUIRED
  SOURCES
    asio-blockable.cpp
    asio-context.cpp
    asio-context-enter.cpp
    asio-external-thread-event.cpp
    asio-external-thread-event-queue.cpp
    asio-session.cpp
    ext_async-function-wait-handle.cpp
    ext_async-generator.cpp
    ext_async-generator-wait-handle.cpp
    ext_await-all-wait-handle.cpp
    ext_condition-wait-handle.cpp
    ext_asio.cpp
    ext_external-thread-event-wait-handle.cpp
    ext_gen-array-wait-handle.cpp
    ext_gen-map-wait-handle.cpp
    ext_gen-vector-wait-handle.cpp
    ext_reschedule-wait-handle.cpp
    ext_resumable-wait-handle.cpp
    ext_sleep-wait-handle.cpp
    socket-event.cpp
    ext_static-wait-handle.cpp
    ext_waitable-wait-handle.cpp
    ext_wait-handle.cpp
  HEADERS
    asio-blockable.h
    asio-context.h
    asio-context-inl.h
    asio-context-enter.h
    asio-context-enter-inl.h
    asio-external-thread-event.h
    asio-external-thread-event-queue.h
    asio-session.h
    ext_async-function-wait-handle.h
    ext_async-function-wait-handle-inl.h
    ext_async-generator.h
    ext_async-generator-wait-handle.h
    ext_await-all-wait-handle.h
    ext_await-all-wait-handle-inl.h
    ext_condition-wait-handle.h
    ext_asio.h
    ext_external-thread-event-wait-handle.h
    ext_gen-array-wait-handle.h
    ext_gen-array-wait-handle-inl.h
    ext_gen-map-wait-handle.h
    ext_gen-map-wait-handle-inl.h
    ext_gen-vector-wait-handle.h
    ext_gen-vector-wait-handle-inl.h
    ext_reschedule-wait-handle.h
    ext_resumable-wait-handle.h
    ext_resumable-wait-handle-defs.h
    ext_sleep-wait-handle.h
    socket-event.h
    ext_static-wait-handle.h
    ext_waitable-wait-handle.h
    ext_waitable-wait-handle-inl.h
    ext_wait-handle.h
  SYSTEMLIB
    ext_asio.php
    ext_async-generator.php
  DEPENDS
    libFolly
)
