ERROR: File "computed_constants.php", line 10, characters 34-63:
Class constant `UnresolvableShapeKey::UNMARKED` used as a shape key must be annotated with `<<__ShapeKey>>`. Prefer using an enum constant as a shape key. (Typing[4533])
  File "computed_constants.php", line 6, characters 16-23:
  The class constant is declared here
ERROR: File "computed_constants.php", line 14, characters 14-43:
Class constant `UnresolvableShapeKey::UNMARKED` used as a shape key must be annotated with `<<__ShapeKey>>`. Prefer using an enum constant as a shape key. (Typing[4533])
  File "computed_constants.php", line 6, characters 16-23:
  The class constant is declared here
