<?php

// This doc comment block generated by idl/sysdoc.php
/**
 * ( excerpt from http://php.net/manual/en/class.jsonserializable.php )
 *
 * Objects implementing JsonSerializable can customize their JSON
 * representation when encoded with json_encode().
 *
 */
interface JsonSerializable {
  // This doc comment block generated by idl/sysdoc.php
  /**
   * ( excerpt from
   * http://php.net/manual/en/jsonserializable.jsonserialize.php )
   *
   * Serializes the object to a value that can be serialized natively by
   * json_encode().
   *
   * @return     mixed   Returns data which can be serialized by
   *                     json_encode(), which is a value of any type other
   *                     than a resource.
   */
  public function jsonSerialize();
}

