use arena_trait::TrivialDrop;
use ocamlrep_derive::FromOcamlRepIn;
use ocamlrep_derive::ToOcamlRep;
use serde::Serialize;

#[allow(unused_imports)]
use crate::*;

#[derive(
    Clone, Debug, Eq, FromOcamlRepIn, Hash, Ord, PartialEq, PartialOrd, Serialize, ToOcamlRep,
)]
pub enum IntList<'a> {
    Nil,
    Cons(isize, &'a IntList<'a>),
}
impl<'a> TrivialDrop for IntList<'a> {}

#[derive(
    Clone, Debug, Eq, FromOcamlRepIn, Hash, Ord, PartialEq, PartialOrd, Serialize, ToOcamlRep,
)]
pub enum NAryTree<'a, A> {
    Leaf(A),
    Children(&'a [NAryTree<'a, A>]),
}
impl<'a, A: TrivialDrop> TrivialDrop for NAryTree<'a, A> {}
