// Copyright (c) Facebook, Inc. and its affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the "hack" directory of this source tree.
//
// @generated <<SignedSource::*O*zOeWoEQle#+L!plEphiEmie@IsG>>
use arena_trait::TrivialDrop;
use eq_modulo_pos::EqModuloPos;
use no_pos_hash::NoPosHash;
use ocamlrep_derive::FromOcamlRepIn;
use ocamlrep_derive::ToOcamlRep;
use serde::Deserialize;
use serde::Serialize;

#[allow(unused_imports)]
use crate::*;

#[derive(
    Clone,
    Copy,
    Debug,
    Deserialize,
    Eq,
    EqModuloPos,
    FromOcamlRepIn,
    Hash,
    NoPosHash,
    Ord,
    PartialEq,
    PartialOrd,
    Serialize,
    ToOcamlRep,
)]
pub enum X<'a> {
    A(Option<isize>),
    B(bool),
    C(f64),
    D(std::cell::Cell<isize>),
    #[serde(deserialize_with = "arena_deserializer::arena", borrow)]
    E(&'a str),
    #[serde(deserialize_with = "arena_deserializer::arena", borrow)]
    F(&'a (&'a str, &'a str)),
}
impl<'a> TrivialDrop for X<'a> {}
arena_deserializer::impl_deserialize_in_arena!(X<'arena>);
