use ocamlrep_derive::OcamlRep;
use serde::Deserialize;
use serde::Serialize;

#[allow(unused_imports)]
use crate::*;

#[derive(Clone, Debug, Deserialize, Eq, Hash, OcamlRep, Ord, PartialEq, PartialOrd, Serialize)]
pub enum IntList {
    Nil,
    Cons(isize, Box<IntList>),
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, OcamlRep, Ord, PartialEq, PartialOrd, Serialize)]
pub enum NAryTree<A> {
    Leaf(A),
    Children(Vec<NAryTree<A>>),
}
