((script 53
  ((list 53
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 47
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 4 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 25
        ((() { 1 ((end_of_line 1)))
         (list 19
          ((expression_statement 19
            ((function_pointer_expression 18
              ((member_selection_expression 16
                ((function_call_expression 11
                  ((member_selection_expression 9
                    ((variable 4 ((((whitespace 2)) variable 4 ())))
                     (() -> 2 ()) (() name 3 ())))
                   (missing 0 ()) (() "(" 1 ()) (missing 0 ()) (() ")" 1 ())))
                 (() -> 2 ()) (() name 3 ())))
               (type_arguments 2 ((() < 1 ()) (missing 0 ()) (() > 1 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
