((script 50
  ((list 50
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 44
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 4 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 22
        ((() { 1 ((end_of_line 1)))
         (list 16
          ((expression_statement 16
            ((function_pointer_expression 15
              ((scope_resolution_expression 10
                ((variable 4 ((((whitespace 2)) variable 4 ()))) (() :: 2 ())
                 (() variable 4 ())))
               (type_arguments 5
                ((() < 1 ())
                 (list 3
                  ((list_item 3
                    ((simple_type_specifier 3 ((() name 3 ())))
                     (missing 0 ())))))
                 (() > 1 ())))))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
