((script 49
  ((list 49
    ((markup_section 4
      ((() markup 0 ())
       (markup_suffix 4 ((() <? 2 ()) (() name 2 ((end_of_line 1)))))))
     (function_declaration 43
      ((missing 0 ())
       (function_declaration_header 21
        ((missing 0 ()) (((end_of_line 1)) function 8 ((whitespace 1)))
         (() name 4 ()) (missing 0 ()) (() "(" 1 ()) (missing 0 ())
         (() ")" 1 ()) (() : 1 ((whitespace 1)))
         (simple_type_specifier 4 ((() void 4 ((whitespace 1)))))
         (missing 0 ())))
       (compound_statement 21
        ((() { 1 ((end_of_line 1)))
         (list 15
          ((expression_statement 15
            ((binary_expression 14
              ((literal 12
                ((((whitespace 2)) single_quoted_string_literal 12 ())))
               (() < 1 ()) (() > 1 ())))
             (() ";" 1 ((end_of_line 1)))))))
         (() } 1 ((end_of_line 1)))))))
     (end_of_file 0 ((() end_of_file 0 ()))))))))
