--- ocaml
+++ rupro
@@ -1,38 +1,32 @@
 FoldedClass {
     name: "\\T",
     pos: Pos(root|requireclass_experimental.bad.php, 4:7-8),
     kind: Ctrait,
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|requireclass_experimental.bad.php, 4:7-8),
             ty: HH\classname<this>,
             origin: "\\T",
             refs: [],
         },
     },
-    req_class_ancestors: [
-        Requirement(
-            Pos(root|requireclass_experimental.bad.php, 5:17-18),
-            C,
-        ),
-    ],
 }
 FoldedClass {
     name: "\\C",
     pos: Pos(root|requireclass_experimental.bad.php, 8:7-8),
     kind: Cclass(
         Concrete,
     ),
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|requireclass_experimental.bad.php, 8:7-8),
             ty: HH\classname<this>,
             origin: "\\C",
             refs: [],
         },
     },
 }
