--- ocaml
+++ rupro
@@ -1,59 +1,47 @@
 FoldedClass {
     name: "\\T",
     pos: Pos(root|requireclass_hierarchy_01.good.php, 6:7-8),
     kind: Ctrait,
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|requireclass_hierarchy_01.good.php, 6:7-8),
             ty: HH\classname<this>,
             origin: "\\T",
             refs: [],
         },
     },
-    req_class_ancestors: [
-        Requirement(
-            Pos(root|requireclass_hierarchy_01.good.php, 7:17-18),
-            C,
-        ),
-    ],
 }
 FoldedClass {
     name: "\\C",
     pos: Pos(root|requireclass_hierarchy_01.good.php, 10:7-8),
     kind: Cclass(
         Concrete,
     ),
     substs: {
         "\\T": SubstContext {
             subst: Subst(
                 {},
             ),
             class_context: "\\C",
             from_req_extends: false,
         },
     },
     ancestors: {
         "\\T": T,
     },
     consts: {
         "class": ClassConst {
             is_synthesized: true,
             kind: CCConcrete,
             pos: Pos(root|requireclass_hierarchy_01.good.php, 10:7-8),
             ty: HH\classname<this>,
             origin: "\\C",
             refs: [],
         },
     },
     extends: {
         "\\T",
     },
-    req_class_ancestors: [
-        Requirement(
-            Pos(root|requireclass_hierarchy_01.good.php, 11:7-8),
-            C,
-        ),
-    ],
 }
